### ISSUE TITLE
how does waitForRefetchQueries work?

### ISSUE THREAD

**Issue by tibotiber** [tannerlinsley/react-query#100]
Hi,

I'm curious what is the expected behaviour of `waitForRefetchQueries: true`? 

**I would expect** that after the mutation has succeeded, it remains in `isLoading` mode while the refetch queries are refetched and finally resolves with data once the refetch queries are done with.

**I observe** in the sandbox that after I post a new todo (I've added `waitForRefetchQueries: true` on `postTodo`) the todo display "saved" and then background refresh happens.

Am I misunderstanding or missing something? Is this a bug?

Thank you

**Comment by tannerlinsley** [comment]
The promise returned by a `mutate()` call with `waitForRefetchQueries: true` won't resolve until the query refetches do. The data it receives, on the other hand, will be written as soon as possible to the cache and the page updated to give the most optimal UI feedback.

**Comment by tibotiber** [comment]
My bad, I had added `{ waitForRefetchQueries: true }` in the `useMutation` options, not in the `mutate` options 😓. I've realized my mistake while going through the codebase to understand your reply. The documentation is clear also.

Thanks for your help.
