### ISSUE TITLE
onSuccess not called when both suspense & staleTime are used

### ISSUE THREAD

**Issue by ivowork** [tannerlinsley/react-query#101]
For some reason if I pass `suspense=true` AND `staleTime` in the `useQuery` options, the `onSuccess` is not called.

I've updated the suspense example to include `onSuccess` and `staleTime` on the projects query in order to show this issue. https://codesandbox.io/s/restless-glade-kuf9n

P.S.: Thank you for making react-query available, it is so so awesome :raised_hands:

**Comment by tannerlinsley** [comment]
This is because you are using the prefetch pattern and the call is succeeding before useQuery is rendered, thus if you want `onSuccess` to fire for both the prefetch and background fetches, you must also pass onSuccess as an option in your prefetcher, not just the useQuery.

**Comment by ivowork** [comment]
You are most likely correct for the example, I didn't even noticed that it was using the prefetch, but I do not use the prefetchQuery anywhere in my project and even if I remove those calls in the example, the console.log in the Projects.ts does not log unless I remove the staleTime. 

https://codesandbox.io/s/hungry-smoke-816sl

Can you please help me understand a bit better what is happening?

**Comment by hanswilw** [comment]
@tannerlinsley 

I have a similar problem in suspense mode, so might be something here? It seems like `onSuccess` is not fired at all for prefetchQuery and is not fired for the initial useQuery call.

If you click "Show projects" the prefetchQuery triggers, but with no success callback. Only for consecutive fetches like window focus change it triggers with onSuccess callback – as the console shows.
https://codesandbox.io/s/intelligent-yalow-vnlrb?file=/src/index.js

Without the prefetchQuery, only useQuery, the same thing happens.
https://codesandbox.io/s/unruffled-kowalevski-fz2re?file=/src/index.js
