### ISSUE TITLE
Setting cacheTime to 0 re-runs query infinitely

### ISSUE THREAD

**Issue by mush159** [tannerlinsley/react-query#1019]
**Describe the bug**
using `useQuery` with `cacheTime: 0` continuously re-runs the fetch request

**To Reproduce**

This codesandbox uses the simple example provided by the docs and simply adds `cacheTime: 0` to the query options. This can very quickly kick in githubs rate limiting due to the bug.

1. Go to https://codesandbox.io/s/loving-tu-b8hg6?file=/src/index.js
2. Open the network tab
3. Watch as `react-query` hammers the github API

Occasionally this does not occur, simply changing the `cacheTime` so some other low value can make it appear e.g. `1`.
Also, this doesnt happen when the `ReactQueryDevtools` are open, it seems like the devtools prevents the cache from being cleared?

**Expected behavior**
I would expect the query to be run only once

**Additional context**
Seems like this bug was introduced in v2.7.1 with this bug fix: https://github.com/tannerlinsley/react-query/pull/899

**Comment by tannerlinsley** [comment]
Please make sure you're using the latest version (@latest, not 3.0.1, which was a mis-release)

https://codesandbox.io/s/cocky-pascal-ipien?file=/src/index.js

**Comment by Txarli** [comment]
I'm experiencing this same issue when running my Cypress tests with `cacheTime: 0`. In Cypress, it enters in an infinite loop (this doesn't happen in Chrome, or even in IE11). Using the `ReactQueryDevtools` avoids this problem.

I'm using the version 2.23.0 of `react-query`

**Comment by priyajeet** [comment]
Getting the same issue in 2.26.2 (which is the latest)?

**Comment by priyajeet** [comment]
Also seems to happen on v3.1.1
