### ISSUE TITLE
Catch block doesn't fire

### ISSUE THREAD

**Issue by juicylevel** [tannerlinsley/react-query#1023]
**Describe the bug**
If the network call fails with an error, then the mutation does not trigger the catch block.

**To Reproduce**

```
import React from "react";
import ReactDOM from "react-dom";
import { useMutation } from "react-query";

const Root = () => {
  const [test] = useMutation(() => {
    return fetch("https://fake000.com", {}); // no such server exists!!!
  });

  const handleTest = async () => {
    try {
      await test();
      console.log('This code will execute ');
    } catch (error) {
      // NOT TRIGGERED! WHY?
      alert(error.message);
    }
  };

  return <button onClick={handleTest}>TEST</button>;
};

const rootElement = document.getElementById("root");
ReactDOM.render(<Root />, rootElement);

```

**Expected behavior**
Catch block is expected to fire.

**Comment by boschni** [comment]
Hi @juicylevel! If you want the function to throw you need to set `throwOnError`:
https://react-query.tanstack.com/docs/api#usemutation

**Comment by juicylevel** [comment]
Thanks!

**Comment by tbntdima** [comment]
@boschni is there something similar for useQuery?
When my first fetch fails, onError is not called if refetch is successful, is it possible to still invoke onError?
