### ISSUE TITLE
Bug with QueryCache class

### ISSUE THREAD

**Issue by todortotev** [tannerlinsley/react-query#1026]
![Screenshot 2020-09-16 at 19 18 22](https://user-images.githubusercontent.com/51530311/93364590-680ddd80-f851-11ea-8265-a3aa4eaa67de.png)

![Screenshot 2020-09-16 at 19 18 40](https://user-images.githubusercontent.com/51530311/93364629-72c87280-f851-11ea-9cdd-cff006cfee96.png)

**Comment by boschni** [comment]
Are you able to update to the latest version?

**Comment by hukka** [comment]
This seems to also break the examples in the docs, for example https://react-query.tanstack.com/docs/examples/optimistic-updates

**Comment by boschni** [comment]
The regular examples are working https://react-query.tanstack.com/docs/examples/simple but the next.js examples seem to cache a previous version. Any idea on how to update them @tannerlinsley ?

**Comment by boschni** [comment]
Examples are working again!

**Comment by hukka** [comment]
Hm. The optimistic-updates is giving "Reloading too fast" when embedded, but works when opening in codesandbox. But surely a different issue now than this one.

**Comment by tannerlinsley** [comment]
Please open a new issue for that one with a codesandbox that replicates the issue.
