### ISSUE TITLE
query.cancelQueries is not a function bug

### ISSUE THREAD

**Issue by mrudowski** [tannerlinsley/react-query#103]
latest update with commit `call queryFn cancellation methods if provided (#94)`  triggers `query.cancelQueries is not a function` error for me on component unmount

**Comment by powah** [comment]
Yes, I'm experiencing the same.

**Comment by treio** [comment]
I'm getting the same issue.

**Comment by davidcostadev** [comment]
Hello fulks, this error are still happening to me, and the location of this is:
![Captura de tela de 2020-01-16 07-26-59](https://user-images.githubusercontent.com/3098556/72517146-9e620b80-3831-11ea-9369-71c572d2f81c.png)

**Comment by matheusalbino** [comment]
@davidcostadev the version with this fix has not been released yet. Change to v0.3.23.

**Comment by davidcostadev** [comment]
Thanks @matheusalbino this works to me

**Comment by matheusalbino** [comment]
any update when will release a new version with the fix?

**Comment by baba43** [comment]
I'm getting the same error with `0.3.24`?

**Comment by gndelia** [comment]
Same issue here, it's breaking my build :'(

**Comment by matheusalbino** [comment]
> @davidcostadev the version with this fix has not been released yet. Change to v0.3.23.

@gndelia :point_up_2:

**Comment by gndelia** [comment]
I tried that but I still got the same error.

In this case, it's happening in the context of a test: I am using `react-testing-library` to test a component tree, and the root of that uses `react-query`

**Comment by tannerlinsley** [comment]
Released! Thanks everyone!
