### ISSUE TITLE
Mutation cache invalidation is broken in typescript

### ISSUE THREAD

**Issue by mikecousins** [tannerlinsley/react-query#1032]
**Describe the bug**
Using the example code for mutation query invalidation now throws typescript errors.

**To Reproduce**
1. Add the sample code from the docs on mutation query invalidation
2. Typescript yells at you

**Expected behavior**
A clean build

**Screenshots**
![image](https://user-images.githubusercontent.com/725614/93424945-51c64880-f876-11ea-9cde-0648bdfa1a6e.jpeg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge
 - Version: Latest

**Comment by boschni** [comment]
The onSuccess callback does not expect something to be returned. The error should go away if you wrap the invalidate in curly braces
