### ISSUE TITLE
Mutation documentation assumes throwOnError

### ISSUE THREAD

**Issue by hukka** [tannerlinsley/react-query#1035]
**Describe the bug**
The doc on https://react-query.tanstack.com/docs/guides/mutations shows how to use try/catch to get errors from the mutation, but the user needs to check the API docs to figure out there is a parameter throwOnError that needs to be set. I think the doc should either set throwOnError, or show using the onSuccess/onError parameters for the useMutation call like the more advanced documentation on mutations.

**Comment by tannerlinsley** [comment]
Feel free to open a PR to improve the docs as you see fit :)

**Comment by isshesure** [comment]
Is there a reason behind the default value being `false` rather than `true`? Can the value be `true` if there is no `onError` handler?

**Comment by ssteuteville** [comment]
was throwOnError removed in v3? useErrorBoundary doesn't seem to be a direct replacement, a little confused.

**Comment by TkDodo** [comment]
It was, because we now have mutate (doesn’t throw errors - well, it catches errors internally) and mutateAsync (throws and you need to catch it for yourself)
