### ISSUE TITLE
QueryCache is not a constructor

### ISSUE THREAD

**Issue by MuzammilRafay** [tannerlinsley/react-query#1037]
**Screenshots**
![image](https://user-images.githubusercontent.com/36181738/93456158-bcb76400-f8f6-11ea-8806-c81f2683c630.png)
![image](https://user-images.githubusercontent.com/36181738/93456200-c4770880-f8f6-11ea-8f13-f8ca1474d0c2.png)

**Additional context**
hi so i am seeing this error on sandbox i don't know why can you resolve this issue i want to test code on sandbox ?

**Comment by Gorbus** [comment]
Having the same issue locally. Don't know where it comes from.

**Comment by MuzammilRafay** [comment]
Thanks for feedback :-)
