### ISSUE TITLE
QueryCache constructor is undefined

### ISSUE THREAD

**Issue by stephen776** [tannerlinsley/react-query#1042]
Using React-Native / Expo (sdk 38) I am receiving the following error when the app starts.

![image](https://user-images.githubusercontent.com/565167/93494115-a8fe0480-f8da-11ea-97e2-7bdf6ce4b3cf.png)

I am creating a new instance of QueryCache and passing it into the provider in my root component as in the examples.

![image](https://user-images.githubusercontent.com/565167/93494480-0f832280-f8db-11ea-86f9-f117efa9de42.png)

**Comment by tannerlinsley** [comment]
Make sure you are using the latest version of the library :)

**Comment by stephen776** [comment]
Updated to 2.22.0. Same problem.   
  

  
  

  
  
>

**Comment by tannerlinsley** [comment]
This codesandbox shows that there are no errors or issues: https://codesandbox.io/s/github/tannerlinsley/react-query/tree/master/examples/simple?file=/src/index.js
