### ISSUE TITLE
Possibly throwing different promises in Suspense causing the suspended tree to update unnecessarily 

### ISSUE THREAD

**Issue by alexandernanberg** [tannerlinsley/react-query#1049]
**Describe the bug**
I _think_ `react-query` throws different promises causing React to throw away the entire tree. It's very possible that I'm missing something on how Suspense works though. 

Not really sure if it's a bug in `react-query`, `react` or the expected behaviour.

**To Reproduce**
1. Go to https://codesandbox.io/s/restless-night-yynbz?fontsize=14&hidenavigation=1&theme=dark
2. Check the console
4. See multiple state initializer logs in the console

**Expected behavior**

State initializer only called once

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Firefox
 - Version: 80

**Smartphone (please complete the following information):**
 - Browser: [e.g. stock browser, safari]
 - Version: [e.g. 22]

**Additional context**

N/A

**Comment by alexandernanberg** [comment]
Tried it with concurrent mode and then it only calculates twice, so it might be a bug in React or simply expected in sync mode.

**Comment by boschni** [comment]
Hi @alexandernanberg! The state initializer should run twice. Once when the component mounts, then a promise is thrown, and when it resolves the component is rendered again. The third render is because code sandbox is using React strict mode, which will render the component twice.

**Comment by tannerlinsley** [comment]
The promise is and should be consistent from render to render. Make sure you account for strict mode (which is usually what these questions stem from)

**Comment by alexandernanberg** [comment]
I see, thanks!
