### ISSUE TITLE
return undefined instead of null

### ISSUE THREAD

**Issue by mtinner** [tannerlinsley/react-query#105]
**Improvement**

the default returnValue of `data` at least in useQuery should be `undefined` instead of `null`

if you return `undefined` then you can make use of set default values as shown below

```js
 const { data = [] } = useQuery(
    'TrendingShows',
    loadTrendingShows
  );
```

**Comment by nikoskleidis** [comment]
I agreed with your recommendation. But as a workaround for now, you can use the initialData prop as described here to set your data to an empty array for example
https://github.com/tannerlinsley/react-query#ssr--initial-data

**Comment by tannerlinsley** [comment]
This will be fixed in the next release 🎉
