### ISSUE TITLE
eslint-config-prettier is missing in package.json of basic example

### ISSUE THREAD

**Issue by wtlin1228** [tannerlinsley/react-query#1050]
**Describe the bug**
`eslint-config-prettier` is missing in package.json.

**To Reproduce**
1. `$ cd examples/basic`
2. `$ npm install`
3. `$ npm run start`
4. See Error: Cannot find module 'eslint-config-prettier'

**Expected behavior**
The basic example run well.

**Screenshots**
<img width="890" alt="截圖 2020-09-18 下午4 57 06" src="https://user-images.githubusercontent.com/16910748/93578523-058f1b80-f9d0-11ea-8d24-99a4bfae103c.png">

**Comment by tannerlinsley** [comment]
Feel free to open PR to add the dep, but since this is just a dev dependency for an example, going to close this issue
