### ISSUE TITLE
Force using cache and requesting from network only if data is not persisted in cache.

### ISSUE THREAD

**Issue by TheMisir** [tannerlinsley/react-query#1064]
I want `useQuery` to look up to the cache and send network request only if the key is not available in the cache. This is requested because otherwise my frontend DoSes my own server during any UI changes. Is there any option to make this possible? Or could be added to the library? Thanks.

**Comment by gcofficial** [comment]
I have the same question. Any updates?

**Comment by TkDodo** [comment]
I think you can just set the `staleTime` to `Infinity`, either on the `queryCache` or for a query separately through the config.

https://react-query.tanstack.com/docs/api#usequery

```
staleTime: Int | Infinity
The time in milliseconds after data is considered stale.
If set to Infinity, query will never go stale
```

**Comment by tannerlinsley** [comment]
Yep. `staleTime: Infinity`

**Comment by TheMisir** [comment]
Thanks =)

**Comment by gcofficial** [comment]
Thx a lot 👍
