### ISSUE TITLE
Suspense loader not retriggered if query is invalidated

### ISSUE THREAD

**Issue by andrewnaeve** [tannerlinsley/react-query#1065]
**Describe the bug**
If a query is invalidated because data needs to be refetched, the React Suspense loading state is not also re-triggered.

**Expected Behavior**
I would expect the fallback to retrigger when:
* The query is invalidated. A loader is appropriate because the data is invalid, and refetching must occur.
* The refetch function is called 

I would not expect the fallback to retrigger if:
* The query is "refetched" by setting the refetch prop, as polling may be wanted in the background without disrupting the current screen.

**To Reproduce**
See codepen here:
https://codesandbox.io/s/charming-joliot-nm1pt?file=/src/index.js

**Comment by tannerlinsley** [comment]
This may be related to #1059?

**Comment by boschni** [comment]
Its not exactly the same issue, but it is related because we need to explicitly define the behavior of suspense in several scenarios, including this one. Closing this issue in favor of #1059
