### ISSUE TITLE
Better error message on mutations

### ISSUE THREAD

**Issue by todortotev** [tannerlinsley/react-query#1072]
![Screenshot 2020-09-22 at 12 14 43](https://user-images.githubusercontent.com/51530311/93864253-44251e80-fccd-11ea-8904-55af8f087bd9.png)

Using the useMutation() hook without providing a function to execute results in this error.
<img width="1413" alt="Screenshot 2020-09-22 at 12 15 54" src="https://user-images.githubusercontent.com/51530311/93864314-5dc66600-fccd-11ea-9854-ef047f44ee06.png">

I think a more self-explainatory message would be better. Maybe something to suggest the user where to look at?

I'd be happy to push a PR if you're comfortable with that.

**Comment by tannerlinsley** [comment]
Yeah, that would be a good PR. Just make sure the messaging is stripped out when using the production version. Gotta keep that bundle size down!

**Comment by tannerlinsley** [comment]
Closing this, but the PR invite is still open 👍
