### ISSUE TITLE
useMutation types: variables are optional

### ISSUE THREAD

**Issue by TkDodo** [tannerlinsley/react-query#1077]
**Describe the bug**

in TypeScript, the mutation function created by the useMutation hook can always be called without passing arguments, because the type `TVariables` is set to optional:

https://github.com/tannerlinsley/react-query/blob/00b9e968a80ca7c51fd50479aee852bb41bf9bc6/src/react/useMutation.ts#L132

**To Reproduce**

I made a codeSandbox example: https://codesandbox.io/s/async-currying-wepni

Please look at the comment at line 54

I _should_ be forced to call that function like this:

`mutatePostTodo(text)`

but I _can_ also call it like this:

`mutatePostTodo()`

**Expected behavior**

The type of variables that you need to pass to that function should be equal to the type that the actual mutation function accepts, in other words, it should be `variables: TVariables` rather than `variables?: TVariables`

**Desktop (please complete the following information):**
 - OS: MacOS Catalina
 - Browser: Chrome
 - Version: 85

**Additional context**

All the usages of `variables` in that function are accessed with the bang operator, for example:

https://github.com/tannerlinsley/react-query/blob/93db5b61246dcd381d699054de48fca685bef73b/src/react/useMutation.ts#L146

or https://github.com/tannerlinsley/react-query/blob/00b9e968a80ca7c51fd50479aee852bb41bf9bc6/src/react/useMutation.ts#L174

So I don't really see why it should be optional to begin with 🤷 .

Happy to make a PR if you approve of this :)

**Comment by tannerlinsley** [comment]
Yeah a PR would be great. Be sure to include some tests too? :)

**Comment by TkDodo** [comment]
Do you have tests of the type definitions in mind, e.g. with https://github.com/Microsoft/dtslint ?

**Comment by TkDodo** [comment]
@boschni right, i didn’t think about mutations with no variables... I’ve never done that, but it’s still a legit case. 

I think this TS issue is on topic, but not sure if any of the provided workarounds to make a parameter optional if its undefined would help us here: https://github.com/microsoft/TypeScript/issues/12400

I agree that that would be a breaking change and we would thus need to wait for v3

**Comment by TkDodo** [comment]
I just found this discussion on the topic: https://github.com/tannerlinsley/react-query/discussions/991#discussioncomment-81267

Sorry for the duplicate. @tannerlinsley mentioned that type changes are not considered as “breaking”, so we could also just go ahead with making variables mandatory?

**Comment by tannerlinsley** [comment]
I would be okay implementing this in v2 as non-breaking, but I'll leave that up to @boschni since he knows more about the type implications. Otherwise, expect it in v3.

**Comment by boschni** [comment]
The typing issue has been fixed in V3

**Comment by qoalu** [comment]
I am having an issue with the required parameter case.
I have a mutation function that has parameters which are all optional and there are defaults.

When I have no parameters typescript does not complain, as well as when I pass the parameters, however calling the function without parameters now causes an error

```
useMutation((param1?: string, param2?:string) => {})
```

![image](https://user-images.githubusercontent.com/1624045/145602056-4cedfc46-7c46-49ae-8b1a-3a7a8783ded0.png)

**Comment by TkDodo** [comment]
as you can see in the signature you posted, `useMutation` only takes one `variables` argument. If you want to pass multiple arguments, you have to use an object:

```
useMutation((variables: { param1?: string, param2?:string} | undefined) => ...)
```

**Comment by qoalu** [comment]
The above function also results in a typescript error when calling it without parameters

the `variables` parameter is required

Tried with an object as well:
```
useMutation(
     ({ param1, param2 }: { param1?: string, param2?: string } = {}) => {...}, 
     ... 
)
```

the call I am trying to do is without params
```
const { mutateAsync, isLoading } = useMutation();

mutateAsync()
```

**Comment by TkDodo** [comment]
hmm this works fine for me, as `variables` are inferred to `void`:

```
      const { mutateAsync } = useMutation( () => Promise.resolve())
      mutateAsync()
```

if you have an optional parameter, you need to pass `undefined` at least I'm afraid, because that doesn't work:

```
      const { mutateAsync } = useMutation((foo?: string) =>
        Promise.resolve()
      )
      mutateAsync() //error here
```

but that does:

```
      const { mutateAsync } = useMutation((foo?: string) =>
        Promise.resolve()
      )
      mutateAsync(undefined)
```

**Comment by qoalu** [comment]
i see, I am passing an empty object as a workaround, but it does not feel elegant :)
thanks for the guidance here!

**Comment by andresgutgon** [comment]
This is what we do:

``` javascript
export function useMyThing () {
  const mutation = useMutation(...yourThing)
  const mutate = (variables: TVariables = {}) => mutation.mutate(variables)
  return { mutate, ...mutation }
}
```

This way when using this custom hook you don't need to pass variables if you don't want:

``` javascript
const { mutate } = useMyThing()
const onClick = () =>{  mutate() }
```

**Comment by qventura** [comment]
Would this be a more appropriate typing: 

```
export type MutationFunction<TData = unknown, TVariables = void> = TVariables extends void
  ? () => Promise<TData>
  : (variables: TVariables) => Promise<TData>
```

In this case, if `TVariable` is `void`, then no variable should be passed to the function.

**Comment by soobing** [comment]
> This is what we do:
> 
> ```js
> export function useMyThing () {
>   const mutation = useMutation(...yourThing)
>   const mutate = (variables: TVariables = {}) => mutation.mutate(variables)
>   return { mutate, ...mutation }
> }
> ```
> 
> This way when using this custom hook you don't need to pass variables if you don't want:
> 
> ```js
> const { mutate } = useMyThing()
> const onClick = () =>{  mutate() }
> ```

@andresgutgon I think `{ mutate, ...mutation }` should be changed to `{ ...mutation, mutate }`. Thanks anyway 😉
```
export function useMyThing () {
  const mutation = useMutation(...yourThing)
  const mutate = (variables: TVariables = {}) => mutation.mutate(variables)
  return { ...mutation, mutate }
}
```

**Comment by dalmocoop** [comment]
My workaround has been adding `| void` to the args type

```typescript
      const { mutateAsync } = useMutation((foo?: string | void) =>
        Promise.resolve()
      )
      mutateAsync() //all good
