### ISSUE TITLE
Concecutive falsey queryKeys with initialData

### ISSUE THREAD

**Issue by nikoskleidis** [tannerlinsley/react-query#108]
When we have 2 queries that have a falsy queryKey and each has an initialData set then the second one ignores the initialData set and takes the data of the first query as it's data.
I reproduce the issue here
[CodeSandBox example](https://codesandbox.io/embed/patient-wind-q7wd3?fontsize=14&hidenavigation=1&theme=dark)

**Comment by hansena** [comment]
@nikoskleidis thanks for saving me a bunch of debug time, I just hit this same issue 👍

**Comment by tannerlinsley** [comment]
`initialData` populates the cache and is intended for SSR, so this makes sense and is intended. However, If you want instance level default data, you can simply destructure from undefined in your query usage: 

```js
const Comp1 = () => {
  const { data = "Data for query 1" } = useQuery(false, () => {});
  return <h1>{data}</h1>;
};

const Comp2 = () => {
  const { data = "Data for query 2" } = useQuery(false, () => {});
  return <h1>{data}</h1>;
};

```
