### ISSUE TITLE
Support setQueryData for new queries

### ISSUE THREAD

**Issue by tibotiber** [tannerlinsley/react-query#109]
Hello,

I'm realizing that `setQueryData` only supports updating the cache for a query that has been used previously.

https://github.com/tannerlinsley/react-query/blob/db71fc0d874244da82490a05915d9324c527e9e7/src/index.js#L704-L706

What would you think of enabling it for new queries? 

My use-case is that I create a resource in one page, get the resource back from the create mutation, and redirect to another page which fetches the resource. I would like to set the cache for that fetch since I have the data, but I currently am not able to.

Happy to help if feasible.

Thank you.

**Comment by tannerlinsley** [comment]
Does the prefetch method not cover this use case?

**Comment by snorkypie** [comment]
I need this for injecting data coming from the server on initial page load. After a quick dig through the code it looks like injecting data in a nonexisting query would require non-trivial refactoring. This could be solved by adding a new option to `useQuery` though, something that tells it not to fetch if `initialData` is provided.

Would that solve your problem too @tibotiber?

**Comment by tannerlinsley** [comment]
Does prefetchQuery not cover this use case?

**Comment by snorkypie** [comment]
> Does prefetchQuery not cover this use case?

I am staring at the code but I don't see how prefetchQuery lets me inject data without executing a fetch.

**Comment by tannerlinsley** [comment]
You can feed a prefetch any function, and the result will populate the cache. Nothing says you have to use the same function with the same query key 😉 It could even be synchronous!

**Comment by snorkypie** [comment]
/me run and hides

Yeah that totally solves it. Sorry for wasting your time! :-)

**Comment by tannerlinsley** [comment]
No waste! Happy to help 😁

**Comment by tibotiber** [comment]
Haha gonna hide with @snorkypie, I really didn’t think of this either and it definitely fits the use-case. Thanks all :)
