### ISSUE TITLE
Build produces generator functions but disables regenerator runtime

### ISSUE THREAD

**Issue by slowselfip** [tannerlinsley/react-query#110]
I'm trying to use the library with a build target of ie11 but the dist of react-query contains generator functions:

```
    var _ref2 = _asyncToGenerator(function* (pageVariables) {
```

It seems that `@babel/plugin-transform-regenerator` has been excluded in favour of `fast-async` and that in order to save on the bundle size (~1.5kb), the generator runtime has been disabled with the fast-async compiler option `noRuntime: true`.

To reproduce, build react-query and search for `_asyncToGenerator` in the resulting src bundle. Notice the `function*`. Then remove the compiler option of the fast-async config in `.babelrc`, rebuild and there are no `function*` in the generated output.

**Comment by freeman** [comment]
It seems that the typescript version will not have this issue (as it is using https://github.com/rpetrich/babel-plugin-transform-async-to-promises instead of fast-async)

@tannerlinsley can we help with the typescript version ? :)

**Comment by tannerlinsley** [comment]
The latest version now uses `babel-plugin-trasnform-async-to-promises` as well. Enjoy :)
