### ISSUE TITLE
[Typescript] `updatedAt` missing from type definition for QueryResult

### ISSUE THREAD

**Issue by 1stPhormula** [tannerlinsley/react-query#1103]
**Describe the bug**

This will only ever be an issue if you are using Typescript.

When you attempt to destructure the response from `useQuery`, you will see that the `updatedAt` is not available on QueryResult.  When looking at the type definition, it is definitely not there.

**To Reproduce**

See above.

**Expected behavior**

You should be able to destructure the `updatedAt` field.

**Screenshots**

![image](https://user-images.githubusercontent.com/69131241/94373570-123ffd80-00bb-11eb-8de0-ae2a692f7664.png)

**Comment by a-khandelwal** [comment]
It is working for me. Check out - https://codesandbox.io/s/silly-aryabhata-zkrdl?fontsize=14&hidenavigation=1&theme=dark

If it is still not working for you then could you please share the version of react-query you are using.

**Comment by ak06121991** [comment]
It is working for me. Check out - https://codesandbox.io/s/silly-aryabhata-zkrdl?fontsize=14&hidenavigation=1&theme=dark

If it is still not working for you then could you please share the version of react-query you are using.

**Comment by tannerlinsley** [comment]
This issue is stale. Feel free to reopen with a reproduction in Codesandbox
