### ISSUE TITLE
Setting property queryCache from ReactQueryCacheProvider using TypeScript

### ISSUE THREAD

**Issue by sshanzel** [tannerlinsley/react-query#1110]
**Describe the bug**
I am trying to set the configuration for `QueryCache` but when exporting its `type` for declaration, it says it is not exported. I am using TypeScript

Note: I only tried the instructions from this [link](https://react-query.tanstack.com/docs/guides/window-focus-refetching).

`Attempted import error: 'QueryCache' is not exported from 'react-query'.`

**To Reproduce**
1. Create a variable with `QueryCache` type exported from `react-query`
2. Wrap a Component with `ReactQueryCacheProvider`
3. Set the value for `queryCache` with the defined variable at Step 1.

**Expected behavior**
Should apply the settings.

**Screenshots**
![image](https://user-images.githubusercontent.com/13744167/94525690-7c84a980-0245-11eb-87e4-549e67723143.png)

After Compilation
![image](https://user-images.githubusercontent.com/13744167/94525713-89a19880-0245-11eb-9adf-e38f21e9241e.png)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser: [chrome]
 - Version: [85.0.4183.121 (Official Build) (64-bit)]

**Smartphone (please complete the following information):**
 - Browser: [e.g. stock browser, safari]
 - Version: [e.g. 22]

**Additional context**
I am more than willing to provide help fixing issues. Just let me know where to start. Thanks!

**Comment by boschni** [comment]
Are you using the latest version?

**Comment by sshanzel** [comment]
Hi. Good day! I'm currently at `2.15.1` - should I render an update first?

**Comment by sshanzel** [comment]
I have updated it to `2.23.0` and it worked! Thank you! Sorry for the trouble!
