### ISSUE TITLE
Ambiguous naming in custom hooks examples

### ISSUE THREAD

**Issue by cseas** [tannerlinsley/react-query#1112]
As is observed in [this discussion](https://github.com/tannerlinsley/react-query/discussions/801#discussioncomment-86544), the examples provided for custom hooks can give a false idea that they somehow show how to implement a POST call using `useQuery` hook even though the word "post" in those examples refers to website posts and not the HTTP POST method.

Maybe [these example files](https://github.com/tannerlinsley/react-query/blob/master/examples/custom-hooks/src/hooks/usePost.js) should be renamed to something like `useArticle.js` or something similar to avoid the confusion?

**Comment by tannerlinsley** [comment]
A PR to make this change is welcomed 👍
