### ISSUE TITLE
staleTime and suspense true incompatible

### ISSUE THREAD

**Issue by onionhammer** [tannerlinsley/react-query#1116]
**Describe the bug**
useQuery does not pay attention to 'staleTime' to re-invoke the async callback if 'suspense' is set to 'true'.

**To Reproduce**
```ts
    const { data } = useQuery(
        ["somekey", somevalue], 
        () => someAsyncFn(),
        {
            staleTime: 5000,
            // suspense: true // <-- If this line is uncommented, the query will be cached forever, ignoring staleTime
        }
    );
```

**Expected behavior**
When a component with this query is remounted after 5 seconds (5000 milliseconds), it should re-invoke someAsyncFn() to re-fetch the data.

**Comment by Shaddix** [comment]
I guess, even if `staleTime` is zero, the query is forever cached.
Here's a sandbox:
https://codesandbox.io/s/elated-resonance-yqkiw?file=/src/App.js

after click on 'details' the query is unmounted and becomes inactive.
after click on 'go back' the query immediately becomes 'stale' again, without being in 'fetching' state.

**Comment by jobn** [comment]
i think it is related to this https://github.com/tannerlinsley/react-query/issues/1059
with an explanation of the current behaviour here: https://github.com/tannerlinsley/react-query/issues/1059#issuecomment-701973451

**Comment by Shaddix** [comment]
thanks for the link to an issue, it seems to be related, I agree.
Though, setting `cacheTime: 0` doesn't help in my case (could be tried on codesandbox above)

**Comment by boschni** [comment]
Should be fixed now in v3: https://react-query-beta.tanstack.com/ . Closing this issue in favor of https://github.com/tannerlinsley/react-query/issues/1059
