### ISSUE TITLE
SCRIPT1005: Expected '(' on IE11

### ISSUE THREAD

**Issue by baoduy** [tannerlinsley/react-query#112]
Hi @tannerlinsley 
Understand, raising this issue is silly. But this library is not working on IE11. Hope you can extend the support for IE11, as when developing Office Js Add-in the IE11 was used to host the application in Office (Word, Excel,...) apps.

Thanks
Duy

**Comment by freeman** [comment]
Make sure you process it with `babel`/`babel-preset-env`. For me it is working fine in IE11.

**Comment by baoduy** [comment]
@freeman I tried but seems it is not working. May be my config is not right. Let me check again

**Comment by tannerlinsley** [comment]
Yeah, you'll need babel + preset-env and possibly.... a polyfill at the most.

**Comment by rohanBagchi** [comment]
@freeman how did you process react query using babel?
[sorry for commenting on a closed issue. I got it to work with a polyfill but I am looking for a better solution so as to avoid the bloat]
