### ISSUE TITLE
useMutation onSuccess callback updates cache, but component is not re-rendered after redirect

### ISSUE THREAD

**Issue by pdambrauskas** [tannerlinsley/react-query#1138]
**Describe the bug**
When using `useMutation` and updating cache in `onSuccess` callback, data on cache is updated but component does not get re-rendered after redirect.

**To Reproduce**
1. Go to https://codesandbox.io/s/vigorous-smoke-dcq8i?fontsize=14&hidenavigation=1&theme=dark
2. Click on `Load` link & then click load button.
3. You'll see data is updated on ReactQueryDev tools, while App shows previous data

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/10032001/95090671-35f3eb00-072e-11eb-829d-f43de78a3772.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Firefox 81.0

**Additional context**

**Comment by boschni** [comment]
Hi @pdambrauskas! I'm not exactly sure what is going on here but it seems to be fixed in V3: https://codesandbox.io/s/zen-bouman-gzxq8

**Comment by pdambrauskas** [comment]
Thanks @boschni! It really does work as expected with `2.24.0-next.5`
