### ISSUE TITLE
Request: Expose cancel query function

### ISSUE THREAD

**Issue by Jekiwijaya** [tannerlinsley/react-query#114]
is it possible to expose cancel query function?

**Comment by tannerlinsley** [comment]
I'd love to see a use case for this first to determine if we should to proceed with this and how. Please reopen with more information and we'll take it from there :)

**Comment by Jekiwijaya** [comment]
my usecase is in react native, when user open a screen, and quickly go back, it would be super cool if we can terminate the ongoing query on that screens

@tannerlinsley

**Comment by tannerlinsley** [comment]
What if it did this automatically?

**Comment by Jekiwijaya** [comment]
@tannerlinsley hmm, that also would be nice, and function like `refetchAllOnWindowFocus ` also will become works in react native, but in react native to know the screen visible or not is on another API. So to be able react query do that automatically, react query need open the API `isDocumentVisible` (https://github.com/tannerlinsley/react-query/blob/master/src/index.js#L845) for each `useQuery` <-- (or maybe changed to `isScreenVisible`, since in react native, the screens is stacked.)

**Comment by tannerlinsley** [comment]
You can use this to wire up whatever event you want to drive window focus: https://github.com/tannerlinsley/react-query/blob/master/README.md
