### ISSUE TITLE
[2.24.0] cacheTime: Infinity in useQuery() doesn't work properly

### ISSUE THREAD

**Issue by nghiepit** [tannerlinsley/react-query#1140]
Hi,

I'm using `Next.js` and try to upgrade v2.24.0, `cacheTime: Infinity` doesn't seem to work properly.

```js
const cache = new QueryCache();

const client = new QueryClient({
  cache,
  defaultOptions: {
    queries: {
    // Empty here
    }
  }
});
```

```js
MyApp.getInitialProps = async () => {
  await client.prefetchQuery(
          'posts',
          () => {
            return Promise.resolve("my sample data");
          },
          {
            cacheTime: Infinity,
          },
   );
}
```

Somewhere
```js
const posts = client.getQueryData('posts');
```

**To Reproduce**
https://codesandbox.io/s/intelligent-edison-9ddd1?file=/pages/_app.js
1. Click `About` link
2. Click `Home` link
3. Way 5 minutes
4. Switch `About` and `Home`
5. Again step 4
6. Data will be lost

**Additional context**
Maybe the problem only happens when `defaultOptions.queries` is empty.

**Comment by boschni** [comment]
Think what is happening here is that the `Infinity` value gets lost while serializing to JSON. Maybe we should add some support for these kind of values, like serialize to `2147483648` and then deserialize to `Infinity` again.

**Comment by Svish** [comment]
Isn't it more common to use e.g. `-1` as `Infinity` in these types of cases?

**Comment by nghiepit** [comment]
But `v2.23` work fine 😺 
p/s: What performant if `Number.MAX_SAFE_INTEGER` instead of `Infinity `

**Comment by boschni** [comment]
Maybe `-1` would indeed be better as the value should never be negative. Think v2.23 has the same issue, but in that version it falls back to the defaultConfig on the queryCache, while it doesn't in v2.24.

**Comment by boschni** [comment]
Infinite cache times should be serialized correctly in v2.24.1

**Comment by boschni** [comment]
Also added support for providing default options when hydrating :) Closing this issue

**Comment by nghiepit** [comment]
Hey @boschni 
Maybe the `3.2.0` version and above. The issue seems to have come back again.

Reproduction (v3.4.0) https://codesandbox.io/s/infallible-meadow-7e8y1?file=/pages/_app.js

**Comment by boschni** [comment]
Hi @nghiepit! The cache time is not hydrated anymore, this allows server and client to use different cache times. Would it be an option to set an infinite cache time in the client?

**Comment by nghieptiki** [comment]
Yeah, I want to cache my data infinite. And I don't want to re-fetch these data again in the client.

**Comment by nghiepit** [comment]
@boschni 
Yeah, I want to cache my data infinite. And I don't want to re-fetch these data again in the client.

**Comment by boschni** [comment]
What if you set:
```js
const client = new QueryClient({
  defaultOptions: {
    queries: {
      cacheTime: Infinity
    }
  }
});
```

**Comment by nghiepit** [comment]
No, Just specific data want to do apply infinite cache.

**Comment by boschni** [comment]
With `staleTime` you can define when something needs to be refetched. Would that be useful in your case?

**Comment by nghiepit** [comment]
Actually, I am also confused`staleTime` about usage 😭

**Comment by nghiepit** [comment]
Tks @boschni `staleTime` resolved my issue.
