### ISSUE TITLE
useQuery hit the API more than one

### ISSUE THREAD

**Issue by andreepratama27** [tannerlinsley/react-query#115]
Hi @tannerlinsley 

I trying to use `useQuery` to fetch from API. I also debug the response after it fulfilled. But the response (in `console.log`) return more than one. How to fix that one? Is it the default behaviour of `useQuery` itself, or is it something wrong?

My code looks like:
`
const { data } = useQuery(['initProfile', {token: `the_token`}], Api.fetchProfile)
`

**Comment by nikoskleidis** [comment]
Your code looks ok. You shouldn't see more than one console.log as long as `{token:the_token}` stays the same. If it's value changes then a Api.fetchProfile will be called again

**Comment by tannerlinsley** [comment]
Yep. Make sure your variables aren't changing.

**Comment by dimaip** [comment]
I'm experiencing the same problem: the `fetchDay` api request is being performed even when it has been ran before with the same `date` parameter.

```js
const useDay = date => useQuery(['day', { date }], fetchDay);
```

The extra request is initiated here: https://github.com/tannerlinsley/react-query/blob/4cbc2ba6864ec3508fe1451169b821de6ceb0318/src/index.js#L516

![image](https://user-images.githubusercontent.com/837032/75250220-ea1cb300-57e8-11ea-90b3-630b232710a7.png)

**Comment by tannerlinsley** [comment]
You are likely either recreating your `date` object on every render, or you need to stringify it like `['day', { date: date.valueOf() }]`

**Comment by dimaip** [comment]
Thanks! But date is a string in my case.

**Comment by tannerlinsley** [comment]
Is it being used in a component(s) that is being unmounted and mounted again or several components remounting? When new instances of a query are found on a page, the query is refetched in the background.

**Comment by dimaip** [comment]
@tannerlinsley yes! The components are re-mounted on each route transition.

**Comment by dimaip** [comment]
And the query is being used from multiple components on the same page: https://github.com/psmb/calendar/search?q=useDay&unscoped_q=useDay

**Comment by dimaip** [comment]
So is it possible to prevent this re-fetching when new query instances are found?

**Comment by tannerlinsley** [comment]
In v0.x it's not as simple, (v1 will be easy to do this), but for now, the easiest way might be to set the `config.staleTime` for this query to something like `5000`. This will ensure that even if new instances are being mounted, they will only cause a refetch after the stale timeout (5 seconds), or in other words, your query instances will be considered up to date for 5 seconds.

**Comment by dimaip** [comment]
Thanks a lot, that would work perfectly for me!

Thanks for the lib, it's a game changer!

**Comment by cherniavskii** [comment]
> v1 will be easy to do this

@tannerlinsley curious, how would it look like in v1?

**Comment by tannerlinsley** [comment]
It's not implemented yet, but it will likely be an option on the `useQuery` config like `disableInstanceRefetch: true` or `refetchNewInstances: false`. Not sure yet. Essentially this would mean that you could render 100s of instances of a query, but mount/unmount refetching actions would only happen for that first mounted usage. After that you would need to rely on `queryCache.refetchQueries()` calls or manual `queryInstance.refetch()` calls for refetching.

**Comment by tannerlinsley** [comment]
Curious as I'm thinking about this more... should subsequent instances be causing refetches by default at all?

**Comment by dimaip** [comment]
@tannerlinsley it's definitely not something I would expect, I think my usecase with react-router and re-mounting on navigation is pretty common.

**Comment by tannerlinsley** [comment]
Okay, then that's going to be the default in v1. New instances won't refetch unless you specify with an option like `useQuery(key, fn, { refetchOnMount: true })`

**Comment by dougmacklin** [comment]
Hi @tannerlinsley. It looks like `refetchOnMount ` and `refetchAllOnWindowFocus` still default to `true` in v1 (I'm on 1.0.7 currently): [config](https://github.com/tannerlinsley/react-query/blob/master/src/config.js#L12). This behavior definitely caught me off guard until I found this thread. Will these defaults still be changing at some point or did you ultimately decide against it? Thanks for all the hard work on this repo 🙌

**Comment by tannerlinsley** [comment]
Ultimately decided to keep fetchOnMount as true, but made it globally configurable. Sorry for the 180 from Twitter and prior threads.

**Comment by dougmacklin** [comment]
No worries, thanks again!

**Comment by dimaip** [comment]
@tannerlinsley I think it's totally fine to leave them as is, but we should very clearly explain in bold font in the readme all the refetch-related magic. E.g. `refetchOnWindowFocus` also caught me off guard and I only figured it out by debugging in devtools.

**Comment by tannerlinsley** [comment]
Sounds good. I’ll work up a Readme section.
