### ISSUE TITLE
"onSuccess" handler does not fire when I do a "refetch()"

### ISSUE THREAD

**Issue by afilp** [tannerlinsley/react-query#1153]
**Describe the bug**
I want to fetch data only when the user clicks on a button. So I use the following logic:

```
  const { data, refetch } = useQuery(
    ['asset', assetId],
    U.fetchData,
    {
      retry: 2,
      refetchOnWindowFocus: false,
      enabled: false,
      onSuccess: U.processReceivedData,
    },
  );
```

Then, when I click the button, I run the `refetch()` method and the data is fetched.

However, when this is done ("success"), the `onSuccess` handler is not triggered.

**Expected behavior**
The `onSuccess` handler should be triggered on `refetch` too.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Additional context**
react-query version: `"react-query": "^2.23.1"`

**Comment by boschni** [comment]
Could you check if this also happens in v3? Added a test for this behavior and it seems to work ok.

**Comment by afilp** [comment]
@boschni In v3 I get this:

```
scheduler.development.js?3069:178 Uncaught TypeError: Cannot read property 'defaultQueryObserverOptions' of undefined
    at useBaseQuery (useBaseQuery.js?e893:9)
```

Version:
`"react-query": "^3.1.0",`

**Comment by boschni** [comment]
Seems like no client can be found on the context: https://react-query-beta.tanstack.com/guides/migrating-to-react-query-3

**Comment by afilp** [comment]
Indeed, I added the context and now works. 

The `onSuccess` also works, thank you!

**Comment by afilp** [comment]
@boschni Please note though that `WebStorm` "complains" about `react-query`:

![image](https://user-images.githubusercontent.com/7850073/95618220-5517b300-0a75-11eb-96bb-dd37f530f8fd.png)

`ESLint: Casing of react-query does not match the underlying filesystem.(import/no-unresolved)`

**Comment by afilp** [comment]
@boschni Sorry for hijacking this issue but I could not find it in the docs:

I use `Class` components and was simply importing `queryCache` in v1,

Now that I need to use the `const client = useQueryClient()` in a `Class` how do we subscribe to the context? I could not find a `Consumer`.

Thanks!

**Comment by boschni** [comment]
Not sure what would cause the ESLint issue, but you can either wrap the class component with a function component and pass in the client or export the client from the file you are instantiating and then import in the class component file.
