### ISSUE TITLE
All CodeSandbox examples broken

### ISSUE THREAD

**Issue by brentbaum** [tannerlinsley/react-query#1157]
**Describe the bug**
None of the codesandbox examples work, including the one on the homepage.

**To Reproduce**
1. Go to https://react-query.tanstack.com/
2. Scroll down to the example

**Screenshots**
<img width="1324" alt="Screen Shot 2020-10-10 at 5 13 45 PM" src="https://user-images.githubusercontent.com/868955/95665188-fb1df880-0b1b-11eb-8688-26ec14fc4567.png">

**Additional context**
ReactQueryCacheProvider is undefined and codesandbox is defaulting to the 3.x beta release instead of the latest 2.x. This could be a bug on their end.

**Comment by TkDodo** [comment]
Isn’t this the same as https://github.com/tannerlinsley/react-query/issues/1143 ?

**Comment by brentbaum** [comment]
You're right! This is also fixed, so I'm closing the issue.
