### ISSUE TITLE
Global onError handler on useMutation

### ISSUE THREAD

**Issue by john-pc** [tannerlinsley/react-query#116]
A really cool feature will be to handle errors globally from the configuration.
For example  i use the `useMutation` hook everywhere in my app, and my API is returning mostly the same error structure for every request, i've created a wrapper hook but maybe exposed onError handler for useMutation will be a better use case.

```
import { useEffect } from 'react'
import { useMutation } from 'react-query'
import { formatError } from 'lib/utils/helpers'
import { useDispatch } from 'react-redux'
import { showMessage } from 'store/actions'

const useMutationWithError = (func, variabels, errorMsg) => {
    const dispatch = useDispatch()
    const mutation = useMutation(func, variabels)

    useEffect(() => {
        if (mutation[1].error) {
            dispatch(showMessage({ message: formatError(errorMsg, mutation[1].error), variant: 'error' }))
        }
    }, [mutation[1].error])

    return mutation
}

export default useMutationWithError
```

**Comment by tannerlinsley** [comment]
I think the composability of useMutation is apparently strong here, and I would recommend creating your own hook like you've done, as opposed to increasing the api surface area of the library. :)
