### ISSUE TITLE
useInfiniteQuery not fetching all the data

### ISSUE THREAD

**Issue by MikeRock** [tannerlinsley/react-query#1163]
**Describe the bug**
When using `useInfiniteQuery` the data array does not contain all returned results.
I added infinite scroll to a table component that does an initial request and then refetches the data on filtering.
It looks something like this:

```js
// Some code cut for brevity

() => {
const [logs, setLogs] = useState([]);
const source = CancelToken.source();
const scrollId = useSelector((state) => state.scrollId);
const filters = useSelector((state) => state.filters);
const total = useSelector((state) => state.total);
const onPagination = useCallback(() => debounce(fetchMore, DEBOUNCE_INTERVAL));
const addFilters = () => {
source.cancel();
dispatch(resetScrollAction())
dispatch(addFiltersAction())
};
const { remove, fetchMore } = useInfiniteQuery('logs', getLogs.bind(null, filters, scrollId, source), {
    retry: false,
    refetchOnWindowFocus: false,
    refetchInterval: Infinity,
    staleTime: Infinity,
    refetchOnReconnect: false,
    cacheTime: Infinity,
    getFetchMore: (last, all) => all?.flat().length < total,
    onSuccess(data) {
        setLogs(data.filter(Boolean).flat()); // Returns not complete list of results
     },
})

useEffect(() => {
addFilters() // setting up a new search with added filter parameters
},[])

useEffect(() => {
remove() // Purge cache and refetch the query when filters change
}, [filters])

// ...
}
```

**Expected behavior**
After purging the cache the data should be refetched and scrolling should return all results.

**Additional context**
The first result is always returned. Then some of the next pagination results are missing.
I removed all options for auto refetching / retrying as I would like to decide myself when to request data.

EDIT: Same thing if I don't modify the filters at all  - so while doing regular scrolling not all data is returned even though according to redux dev tools the fetch succeeded.

**Comment by MikeRock** [comment]
Ok managed to fix this. The problem was I set a very low debouce interval on my scroll meaning some data was requested in quick succession which might have caused it to not be persisted correctly or so I'm guessing. After setting a minimum debouce of 1s the problem went away.

**Comment by TkDodo** [comment]
Quick question: why are you „syncing“ the data manually to state in `onSuccess` rather then just using the `data` that is returned from `useInfiniteQuery` ?

**Comment by tannerlinsley** [comment]
This looks to be a misunderstanding of how queries work. They have their own state and syncing state from them to local state should be unnecessary. Please open a new issue with a codesandbox (hopefully forked from an existing working example) that shows the unexpected functionality a bit better.

**Comment by rafaelcruzazevedo** [comment]
@tannerlinsley i'm new to using react-query and in general the documentation is good and the implementation it's simple, especially for those who have used apollo, swr... but i'm really not understand `useInfiniteQuery`. I'm doing an implementation with nextjs and i need SSR but the prop comes from server are different from client! on the client the `data` mutates?

I followed the implementation examples, and i have this:

#### Request
```tsx
export async function fetchCollections(options?: Options) {
  const endpoint = getApiEndpoint('getCollections');

  try {
    const currentPage = options?.params?.page;
    const { data } = await request.get(endpoint, {
      params: merge({}, { limit: 24 }, options?.params)
    });

    return {
      data: data?.data,
      nextPage: +currentPage + 1,
      total: data?.total
    };
  } catch (error) {
    throw handleRequestError(error);
  }
}
```

### Page component
```tsx
const { data, fetchMore, isLoading, isSuccess } = useInfiniteQuery(
  collectionsType,
  async (key, page = 1) => await fetchCollections({ params: { page } }),
  { getFetchMore: lastGroup => lastGroup?.nextPage }
);

return (
  <List>
    {map(data, (collections, index: number) => (
      <Fragment key={index}>
        {map(collections.data, (collection: CollectionProps) => (
          <CollectionItem
            key={collection.id}
            {...collection}
          />
        ))}
    </Fragment>
  ))}
</List>
):

// SSR
export async function getServerSideProps() {
  const queryCache = new QueryCache();
  const { data, total } = await queryCache.prefetchQuery(collectionsType, fetchCollections);

  return {
    props: {
      data,
      dehydratedState: dehydrate(queryCache),
      namespacesRequired: ['common', 'collections'],
      total
    }
  };
}
```

But i'm getting this
<img width="600" alt="Screen Shot 2020-11-05 at 15 03 23" src="https://user-images.githubusercontent.com/10829612/98257871-099ddb00-1f35-11eb-877f-2cf43598b0ad.png">

and the data mutates? something bad?
