### ISSUE TITLE
useIsFetching is not triggering on page reload

### ISSUE THREAD

**Issue by 0xR** [tannerlinsley/react-query#1165]
**Describe the bug**
I'm using `useIsFetching` as a global loading indicator.

This works usually as expected, but when I refresh the page it will not trigger the isFetching state.

**To Reproduce**
1. Add a global loading indicator:
	```typescript
	function GlobalLoadingIndicator() {
	  const isFetching = useIsFetching();
	  return <p>{isFetching ? `Loading...` : 'Not loading'}</p>;
	}
	```
1. see that is is working by focusing the page
1. reload the page and see that it is not working

**Expected behavior**
`useIsFetching` shoul return a truthy number in initial page load.

**Screenshots**
See how the react-query devtools are clearly in the fetching state while the global loading indicator stays on `Not loading`.

After the refreshing I'm changing focus, note how the loading indicator does work.

![react-query isfetching bug-2020-10-13_18 09 26](https://user-images.githubusercontent.com/6420016/95887309-f8bbd880-0d7f-11eb-8ffc-c98d7bb923ce.gif)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Chromium
 - Version: 85

React query: 2.23.1

**Comment by 0xR** [comment]
I tried building my own `isFetching`, that shows that the `queryCache.subscribe` was not firing.

```typescript
function GlobalLoadingIndicator() {
  const queryCache = useQueryCache();
  const [isFetching, setIsFetching] = React.useState(queryCache.isFetching);

  React.useEffect(
    () =>
      queryCache.subscribe((cache, query) => {
        console.log('on query', new Date().toLocaleTimeString(), query);
        setIsFetching(cache.isFetching);
      }),
    [queryCache, setIsFetching],
  );
  return <p>{isFetching ? `Loading...` : 'Not loading'}</p>;
}
```

**Comment by tannerlinsley** [comment]
Could you please provide a codesandbox using the latest version that exhibits this behavior?

**Comment by 0xR** [comment]
I'm not able to reproduce it anymore and I don't have the issue in my app anymore either. I'm sure there  is a nice explanation of what was going on, but I'm not going to spend the time on a root cause analysis.

Here is the working sandbox: https://codesandbox.io/s/global-loading-indicator-z00kw?file=/src/App.js

Thanks for your time.

**Comment by qmg-aafridi** [comment]
The issue I had was related to the order of providers (not sure why though)
This was giving me isFetching to be 0 
```js
<MyCustom.Provider>
  <QueryClientProvider client={queryClient}>
    {app}
  </QueryClientProvider>
</MyCustom.Provider>
```

This fixed the issue
```js
<QueryClientProvider client={queryClient}>
  <MyCustom.Provider>
    {app}
  </MyCustom.Provider>
</QueryClientProvider>
```

**Comment by owlas** [comment]
@qmg-aafridi Thank you!!! I've been stuck on this for a couple of hours.

I'll try and get round to a code sandbox shortly

**Comment by Sojborg** [comment]
I'm having the same issue as @qmg-aafridi with the order of providers. Having QueryClientProvider inside a custom provider makes useIsFetching never return false.

Is there any solution to this?

**Comment by TkDodo** [comment]
I think this depends on what your custom provider is doing? If it needs access to the queryClient, the QueryClientProvider must be above it ...

please provide a codesandbox that shows the issue
