### ISSUE TITLE
All the code sandboxes in the docs are dead

### ISSUE THREAD

**Issue by PepijnSenders** [tannerlinsley/react-query#1169]
**Describe the bug**

404: https://react-query.tanstack.com/docs/examples/focus-refetching

**Comment by pavanjadhaw** [comment]
![image](https://user-images.githubusercontent.com/26551780/96307484-591c7580-101f-11eb-82f7-be783d6b5c4a.png)

seems to be api rate limit

**Comment by tannerlinsley** [comment]
Not our fault. The CS team is notified of this and they take care of it upstream.
