### ISSUE TITLE
Use case of cache never going stale

### ISSUE THREAD

**Issue by smblee** [tannerlinsley/react-query#117]
Hello,

I have just found this library and it looks promising with lots of features.

I have a use case where I want to load user's data which never changes (name, profile image, etc.) but it looks like by design, everything gets refetched upon rerendering since all resources are stale by default. I can work around this by setting the `staleTime` to something ridiculous like `staleTime: 99999999999` (or maybe i can make a pull request to allow `-1` as infinite time) but before I go ahead and do that, I wonder if I am missing something in the design of this library! What are other people doing for this kind of use cases?

**Comment by tannerlinsley** [comment]
That approach should work just fine :)

**Comment by smblee** [comment]
Hmm gotcha. It would be nice to see a more complex, in production example of this library in use.

**Comment by tannerlinsley** [comment]
I think @kentcdodds might be able to help with that in the near future. :)
