### ISSUE TITLE
QueryCache.invalidateQueries() calling from useMutation's onSuccess() callback: `this` is undefined

### ISSUE THREAD

**Issue by JNotelddim** [tannerlinsley/react-query#1174]
**Describe the bug**

Using React-Query `v2.23.1` I'm calling `invalidateQueries` in the `onSuccess` callback of a `useMutation` instance, and when the `invalidateQueries` function is triggered, `this` is `undefined`, causing the function to immediately throw and error:
```
TypeError: Cannot read property 'getQueries' of undefined
    at invalidateQueries
```
![image](https://user-images.githubusercontent.com/22509134/96056785-544b9c00-0e3c-11eb-9d8d-34c7f5f31149.png)
 

It wasn't an issue on `v2.12.1` -- though the `invalidateQueries()` call wasn't triggering the adjacent component to refetch the way I was expecting.. I thought it might be a bug that was fixed here: https://github.com/tannerlinsley/react-query/issues/1032 . So I updated to `v2.21.1` and suddenly had this issue, then tried `@latest` (`v2.23.1` at the time of writing), and this issue is still present for me.

**To Reproduce**
1) call `QueryCache.invalidateQueries()` in the onSuccess callback of a `useMutation` instance.
2) trigger mutation (in a way you'd expect it to succeed)
3) see error at queryCache.js:160

##### Code Example:

```
  const { invalidateQueries } = useQueryCache();
  useMutation(completeRemediationMutationFn, {
    onSuccess: ({ body }) => {
      invalidateQueries(['/api/remediation', body.id]);
    },
  });
```

**Expected behavior**
I expected `invalidateQueries()` to be able to run without erroring in the context which I'm talking about.

**Screenshots**

#### `this` = undefined:
![image](https://user-images.githubusercontent.com/22509134/96055999-5dd40480-0e3a-11eb-8c52-1b49c0f4ecb5.png)

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.16
 - Browser:  Google Chrome 
 - Version: 85.0.4183.121 (Official Build) (64-bit)

**Additional context**

The codebase I'm working on is a client's private codebase so I can't share that, sorry.

**Comment by pwolaq** [comment]
I am able to reproduce this behaviour. It happens because QueryCache methods are not bound to its instance. 

A simple fix would be not to use destructuring:

```javascript
const cache = useQueryCache();
useMutation(completeRemediationMutationFn,
  onSuccess: ({ body }) => {
    cache.invalidateQueries(['/api/remediation', body.id]);
  },
});
```
Otherwise, all the public methods should be bound.

**Comment by JNotelddim** [comment]
@pwolaq  thanks for the suggestion!

I've tried it without the destructuring just now, but am still getting the same issue.

Just curious, did you try it without the destructuring and it worked for you?

**Comment by pwolaq** [comment]
Yes, I did. Here is full component that I tested:

```jsx
import React from 'react';
import { useQueryCache, useMutation } from 'react-query';

function App() {
    const { invalidateQueries } = useQueryCache();
    const cache = useQueryCache();
    const fn = () => Promise.resolve();

    const [mutateFail] = useMutation(fn, {
        onSuccess: () => invalidateQueries(['/api/remediation', 0])
    });

    const [mutateSuccess] = useMutation(fn, {
        onSuccess: () => cache.invalidateQueries(['/api/remediation', 0])
    });

    return (
        <React.Fragment>
            <button onClick={() => mutateFail()}>
                Throws error
            </button>
            <button onClick={() => mutateSuccess()}>
                Works
            </button>
        </React.Fragment>
    );
}
```

**Comment by JNotelddim** [comment]
@pwolaq Thanks

Sorry, I'm not sure why it didn't work for me the first time I tried, but it does seem to be working now.

My initial issue of the `invalidateQueries()` call not working the way I'd expect isn't working, but I figure that's probably a separate issue from this one. Thanks again.
