### ISSUE TITLE
Data refetching in the background triggering rendering even when no UI update

### ISSUE THREAD

**Issue by smblee** [tannerlinsley/react-query#118]
I am currently using the paginated feature + refetchInterval (for polling new things), which is good (minus the part where it tries to fetch ALL pages individually... I will have to find an alternate solution to that), but it looks like the page constantly reloads despite there being no updates.

Is there a way for me to say to the library if there are no data changes after a refetch (whether I do a deep check of the objects or specify how to check "what changed"), then don't trigger a rerender?

**Comment by tannerlinsley** [comment]
When you say the page reloads, do you mean that your entire app is rerendering? Or just the component that is using `useQuery`?

**Comment by smblee** [comment]
The component. But since it's a pagination component that handles rendering the child components, it's a pretty big piece of a component

**Comment by tannerlinsley** [comment]
There could be any number of things making your component rerender. Without more info or some code to look at I can't offer much advice. Feel free to reopen with more information :)
