### ISSUE TITLE
useMutation error bubbles up to global scope

### ISSUE THREAD

**Issue by gerhardsletten** [tannerlinsley/react-query#1180]
**Describe the bug**
If the `mutationFn` passed to `useMutation` throws an error, this error will bubbles up to the global scope.

**Expected behavior**
Expected this error to be catched by the useMutation and only passed to own try-catch wrapper if `throwOnError` is set to true. With useMutation in apollo you are able to catch error this way.

**Screenshots**
![image](https://user-images.githubusercontent.com/63344/96242891-4c0e7080-0fa4-11eb-8e2e-3279421ce6c4.png)

Did try to recreate a simple version of useMutation and with this the error will not throw on the global scope if wrapped with a try-catch

```
function useMutation(fn) {
  const [state, setState] = useState({
    isLoading: false,
    data: null,
    error: null,
  })
  const mutate = useCallback(
    async (params) => {
      try {
        setState({
          isLoading: true,
          data: null,
          error: null,
        })
        const data = await fn(params)
        setState({
          isLoading: false,
          data,
          error: null,
        })
      } catch (error) {
        setState({
          isLoading: false,
          data: null,
          error: error,
        })
        throw error
      }
    },
    [setState, fn]
  )
  return [mutate, state]
}
```

![image](https://user-images.githubusercontent.com/63344/96244601-94c72900-0fa6-11eb-927b-cdd52e7d48bb.png)

**Comment by gerhardsletten** [comment]
Looking into this and in [src/react/useMutation.ts](https://github.com/tannerlinsley/react-query/blob/master/src/react/useMutation.ts#L162) a wrapper of console is called:

```
catch (error) {
   Console.error(error)
   //...
}
```

which calls Console from [src/core/utils.ts](https://github.com/tannerlinsley/react-query/blob/master/src/core/utils.ts#L43)

```
export let Console: ConsoleObject = console || {
  error: noop,
  warn: noop,
  log: noop,
}
```

**Comment by tannerlinsley** [comment]
If you do not want the global console to be used for logging unhandled errors, you'll have to use `setConsole(v2)/setLogger(v3)` to override the logger

**Comment by gerhardsletten** [comment]
@tannerlinsley Ok, thanks. To me it should defaults to quiet, but thats only my opinion..
