### ISSUE TITLE
Latest version mismatch between npm / yarn and yarn v2

### ISSUE THREAD

**Issue by bertho-zero** [tannerlinsley/react-query#1186]
**Describe the bug**
Yarn v2 installs version `2.25.0` while npm and yarn v1 installs version `2.23.1` (tagged as latest).

**To Reproduce**
`yarn add react-query` with yarn 2 -> installs react-query v2.25.0

**Expected behavior**
The same version should be installed regardless of package manager.

**Solution**
1. Publish a version 2.26.0 which will be installed with all package managers.
2. Deprecate all v2.x packages that include breaking changes from v3.
3. No longer release breaking changes in patch or minor versions.

**Comment by TkDodo** [comment]
Has this issue been fixed with the release of v 2.25.2 ?

https://github.com/tannerlinsley/react-query/releases/tag/v2.25.2

**Comment by tannerlinsley** [comment]
Yes I believe so
