### ISSUE TITLE
Select option for the infiniteQuery (V3.2.0-beta-2)

### ISSUE THREAD

**Issue by amen-souissi** [tannerlinsley/react-query#1187]
Hello, what about the select option for the infiniteQuery.

https://github.com/tannerlinsley/react-query/blob/42b33f17404265640fb8c81a5c47479c46ca15c8/src/core/infiniteQueryObserver.ts#L114

`select: this.options.select && (data) => data.map( page => this.options.select(page))`

// OR

https://github.com/tannerlinsley/react-query/blob/42b33f17404265640fb8c81a5c47479c46ca15c8/src/core/infiniteQueryBehavior.ts#L41

```
const pageData = context.options.select ? context.options.select(page): page
return previous ? [pageData, ...pages] : [...pages, pageData]
```

**Comment by boschni** [comment]
The select option should work as it is inherited from the QueryObserver.

**Comment by amen-souissi** [comment]
The select option receives all the pages which is not intuitive in my opinion. I think you have to apply the select option to each fetch. It's also more efficient for large requests.

**Comment by boschni** [comment]
One of the use cases which will probably be used a lot is to reverse the entire list with the select function. Providing the entire list provides more flexibility on those kind of use cases.

**Comment by tannerlinsley** [comment]
It should be simple enough to map/filter/flatten here as well.
