### ISSUE TITLE
default query function

### ISSUE THREAD

**Issue by ashinzekene** [tannerlinsley/react-query#119]
It should be possible to set a default query function such as this

```jsx
<ReactQueryConfigProvider config={{ queryFn: fetch }}>
  <App />
</ReactQueryConfigProvider>
```

and then one can use
```jsx
function App() {
  const { data } = useQuery('/users')
}

```

**Comment by tannerlinsley** [comment]
Just create your own custom hook that does this and uses `useQuery` itself. It will be more flexible and powerful that way and won't increase the complexity/size of this library.
