### ISSUE TITLE
[3.2.0-beta.2] Property 'isLoading' does not exist on type 'UseMutationResult

### ISSUE THREAD

**Issue by nghiepit** [tannerlinsley/react-query#1190]
Hi,

![image](https://user-images.githubusercontent.com/4768095/96702497-01359400-13bc-11eb-98df-31fab095e846.png)

**Comment by boschni** [comment]
HI @nghiepit! Thanks for reporting, the bools should be there now in `3.2.0-beta.3`

**Comment by Gajender21** [comment]
try using isPending instead.
