### ISSUE TITLE
stale closure in invalidated queries

### ISSUE THREAD

**Issue by lukesmurray** [tannerlinsley/react-query#1194]
**Describe the bug**
First off thank you so much for this library it is tremendously useful. I understand this is quite a long bug report so if there is anything I can clarify or simplify please let me know. 

I have a query which I want to refetch based on a combination of custom logic and a throttle. I don't want the query to fetch immediately so I set `initialData` to `null` and `staleTime` to `Infinity`. The thought is I can completely control when the query fetches by calling `queryCache.invalidateQueries`. Every time I invalidate the query the query should fetch. The problem is I am running into a stale closure issue. The code is a bit long but most of it is boilerplate simple requests. The issue may be related to the fact that I am using [`useThrottledFn`](https://github.com/beautifulinteractions/beautiful-react-hooks/blob/master/docs/useThrottledFn.md) to invalidate the query.

My confusion stems from the fact that I would expect the enabled flag and the queryFn to be updated simultaneously so I'm struggling to understand why there is a stale closure issue happening here at all.

**Edit**: [Code Sandbox Repro](https://codesandbox.io/s/create-react-app-with-typescript-forked-6l38c?file=/src/queries/queries.ts:1245-1611) with stale closure highlighted.

**Edit 2**: It seems like one fix is to include the dependencies in the query key. For example making the query key `["note", "cache", init.data !== undefined, patientInfo.data !== undefined]`. I may be able to solve my problem using that approach but adding dependencies to the query key was not necessary in the dependent queries example from your react course.

```ts
/**
 * this is the custom hook which contains the problem
 */
const useQueryCacheNoteDTOQueryKey = ["note", "cache"];
const useQueryCacheNoteDTO = () => {

  // init is the first query, called once
  const init = useQuery(["init"], fetchApiInitObject, {
    staleTime: Infinity,
  });

  // patient info depends on init and is called once
  // this query works perfectly
  const patientInfo = useQuery(
    ["patient info"],
    () => fetchPatientInfo(init.data!),
    {
      enabled: init.data !== undefined,
      staleTime: Infinity,
    }
  );

  // the final query depends on init and patient info
  // and is called whenever I invalidate useQueryCacheNoteDTOQueryKey
  return useQuery(
    useQueryCacheNoteDTOQueryKey,
    () => {
      // the problem I run into is a stale closure here
      // init.data and patientInfo.data are undefined
      // even though I include checks for both in the enabled
      // parameter
      console.log("cached", init.data, patientInfo.data);
    },
    {
      enabled: init.data !== undefined && patientInfo.data !== undefined,
      initialData: null,
      staleTime: Infinity,
    }
  );
};

/**
 * this query invalidates the above query on a throttle,
 * in practice there is some logic which is included
 * to determine when the throttled function is called
 * but I removed it here
 */
export const useQueryAutoCacheNoteDTO = () => {
  const queryCache = useQueryCache();
  const cacheResult = useQueryCacheNoteDTO();

  const cacheNote = useThrottledFn(
    () => {
      queryCache.invalidateQueries(useQueryCacheNoteDTOQueryKey);
    },
    timeIntervals.autoCache,
    {
      leading: false,
      trailing: true,
    },
    [queryCache]
  );

  cacheNote();

  return cacheResult;
};
```

**Comment by lukesmurray** [comment]
Update

I found a way to fix this problem by keeping a ref to the function I want to call and then calling that ref in a separate closure.

```ts
type ClosureFunc<TArgs extends unknown[], TResult> = (
  ...args: TArgs
) => TResult | undefined;

/**
 * Create a query function which updates based on dependencies
 */
export default function useSafeClosure<TArgs extends unknown[], TResult>(
  queryFn: ClosureFunc<TArgs, TResult>,
  deps: DependencyList
): ClosureFunc<TArgs, TResult> {
  const closureCb = useCallback<ClosureFunc<TArgs, TResult>>((...args) => {
    return queryFn(...args);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, deps);

  const closureRef = useRef<typeof closureCb>();
  useEffect(() => {
    closureRef.current = closureCb;
  }, [closureCb]);

  const safeClosure = useCallback(
    (...args: TArgs) => closureRef.current?.(...args),
    []
  );
  return safeClosure;
}
```

I then replaced my queries with.

```
useSafeClosure(() => {
      console.log("cached", init.data, patientInfo.data);
}, [init.data, patientInfo.data])
```

Now everything is defined. Still not sure if there is a bug hidden in this mess but I'll close it since I think its probably impossible to deduce anything from this mess.

**Comment by TkDodo** [comment]
Hm, I’m not really sure what you are trying to achieve. It looks like you are invalidating the query cache in the render function (whenever the `useQueryAutoCacheNoteDTO` is rendered), which seems like a side-effect during render. And then, possibly throttling is introduced because it happens too often (sorry, many assumptions here, I could be wrong).

I would put the call to `cacheNote()` into a useEffect and make sure that it only runs when needed via the effect’s dependencies, or try invalidating more imperatively, e.g. on click of a button. 

A completely different (and possibly preferred) approach would be to let react-query handle the fetching rather than doing it manually via invalidation. If you want more control over when the data is fetched, you can use the `enabled` flag to turn off the query depending on some state.

**Comment by lukesmurray** [comment]
this is super helpful @TkDodo and what you said about side effects in render may in fact have been the issue. I think I just found it complicated to use `useEffect` and throttle together but I'm sure it's possible. My eventual solution is similar to what I described here with some slight modifications. Its definitely hacky and I wouldn't recommend to others but it solves a ton of issues for my use case.

**Comment by lukesmurray** [comment]
Part of my final solution is to use a flag to control `enabled` and I toggle the flag and invalidate the query in `onSuccess`. This combination means I can get the query to run whenever I want to which was really the entire goal.

**Comment by TkDodo** [comment]
> Part of my final solution is to use a flag to control enabled and I toggle the flag and invalidate the query in onSuccess. This combination means I can get the query to run whenever I want to which was really the entire goal.

this sounds reasonable. The enabled flag is a very powerful thing - I have actually never done a manual `refetch` 😅
