### ISSUE TITLE
Feature request: clearQueryKeyCache

### ISSUE THREAD

**Issue by nikoskleidis** [tannerlinsley/react-query#120]
Would it be wise for a **clearQueryKeyCache(queryKey || queryKeyList)** to exist?  
There might be some cases in which we don't want to clear everything from the cache eg. using `clearQueryCache`. Maybe we want to remove a group of keys from the cache.

**Usage example**
If a simple queryKey is passed eg **clearQueryKeyCache("todos")** it would delete all the cache entries having this queryKey.

**Comment by nikoskleidis** [comment]
Our problem arose from the refetchQueries property.  
In our project imagine that we have a paginated list of todos. The user can move through pages and multiple queries with keys `["todos", { limit: number, offset: number }]` would be inserted into react-query's cache.
When we mutate a todo, we pass the option `refetchQueries: ["todos"]`.
With the current implementation of react-query, all the queries having the key "todos" will be refetched. **Not only one, but all of them.** This creates traffic to the network that is not needed.

In order to overcome this I suggest providing the above feature so we will be able to clear all the "todos" cache entries and basically trigger a refetch only for the active one.

**Comment by tannerlinsley** [comment]
You can define specific queries to refetch like this:

```js
refetchQueries: [
  ['todos', { limit: 10, offset: 20 }], // This exact query
  ['todos', false], // Only the `todos` query with no variables, not any `todos` query
]
```
