### ISSUE TITLE
Query retries occur after component/useQuery hook is unmounted

### ISSUE THREAD

**Issue by dadamssg** [tannerlinsley/react-query#1206]
**Describe the bug**
I noticed that if a query fails, the query retries will occur even after that component/hook is unmounted.

**To Reproduce**
1. https://codesandbox.io/s/stupefied-diffie-5oqhf?file=/src/index.js
2. click on the button immediately
3. notice in the console log that attempts are still being made even though the button caused the component/useQuery hook to be unmounted.

**Expected behavior**
I do not expect to see retries for failed queries if the calling useQuery hook is unmounted

**Desktop**
 - OS: Catalina
 - Browser: Chrome
 - Version: 86.0.4240.111

**Additional context**
I know react-query is smart enough to not garbage collect data after the cache time expires if the queryKey is being used/rendered. I would expect it to be smart enough to be able to `clearTimeout` on the scheduled retries if the queryKey is no longer being used.

**Comment by boschni** [comment]
Thanks for reporting! Should be fixed in `3.2.0-beta.7`
