### ISSUE TITLE
getQueryArgs does not correctly handle all prefetchQuery signatures 

### ISSUE THREAD

**Issue by drbalm** [tannerlinsley/react-query#1207]
`prefetchQuery` [invokes `getQueryArgs`](https://github.com/tannerlinsley/react-query/blob/master/src/core/queryCache.ts#L437) to get `queryKey`, `config`, and `options`. 

`prefetchQuery` itself supports several [different signatures](https://github.com/tannerlinsley/react-query/blob/master/src/core/queryCache.ts#L382). 

We're using [the signature](https://github.com/tannerlinsley/react-query/blob/master/src/core/queryCache.ts#L395) where we pass `queryKey`, `queryFn`, and `options`.

```
  prefetchQuery<TResult = unknown, TError = unknown>(
    queryKey: QueryKey,
    queryFn: QueryFunction<TResult>,
    options?: PrefetchQueryOptions
  ): Promise<TResult | undefined>
```

In this case, the args as passed to `prefetchQuery` are forwarded on to `getQueryArgs`, which [inspects some arguments](https://github.com/tannerlinsley/react-query/blob/master/src/core/utils.ts#L126) to map them to `queryKey`, `queryFn`, `config`, and `options`, respectively.

With the `prefetchQuery` signature we're using, we fall into the `else` clause, which correctly assigns the `queryKey` and `queryFn`, but it then assigns the `options` to `config` and `undefined` to `options`, which seems incorrect. Ultimately, the `options` we get back are `undefined`.

If we instead use the `prefetchQuery` signature [that includes `queryConfig`](https://github.com/tannerlinsley/react-query/blob/master/src/core/queryCache.ts#L409), all 4 values are mapped as expected.

There is also a `prefetchQuery` signature that takes [PrefetchQueryObjectConfig](https://github.com/tannerlinsley/react-query/blob/f8ec3c1dc7c1933095df58ac02d1e458a7b94170/src/core/queryCache.ts#L66). 

It appears this would fall into the first case of `getQueryArgs`, but `getQueryArgs` expects the `options` to come from`arg2` in this case.

The `prefetchQuery` signature for passing a `PrefetchQueryObjectConfig` does not specify having to pass the `options` separately as a 2nd argument, so it's not what I was expecting for that signature.

```
  prefetchQuery<TResult = unknown, TError = unknown>(
    config: PrefetchQueryObjectConfig<TResult, TError>
  ): Promise<TResult | undefined>
```

**Comment by tannerlinsley** [comment]
@boschni thoughts on this?

**Comment by boschni** [comment]
Is this still the case in V3? And can you provide a wrong case scenario?

**Comment by petrkrejcik** [comment]
Here is an example how the `onSuccess` option is ignored in `prefetchQuery`: https://codesandbox.io/s/romantic-edison-vr8hw?file=/src/App.js

**Comment by boschni** [comment]
Hi @petrkrejcik! `prefetchQuery` does not have the same options as `useQuery`: https://github.com/tannerlinsley/react-query/blob/master/src/core/types.ts#L37 . The returned promise can be used to determine if a query is successful.

**Comment by petrkrejcik** [comment]
@boschni Ah ok, now it makes sense. I was following [the docs](https://react-query.tanstack.com/docs/api#querycacheprefetchquery) where I've read:
> The options for prefetchQuery are exactly the same as those of useQuery with the exception of the last options object

I will use your advice and change the `onSuccess` callback to the result of the promise.

**Comment by boschni** [comment]
Yeah we should definitely update the docs on this

**Comment by tannerlinsley** [comment]
A PR to clarify this is welcome.
