### ISSUE TITLE
cacheTime loading states

### ISSUE THREAD

**Issue by iamjohnlong** [tannerlinsley/react-query#1212]
**Describe the bug**
Setting `cacheTime: 0` doesn't set the loading state to `true` when refetched

**To Reproduce**
1. Go to https://codesandbox.io/s/ecstatic-cray-uobv0?file=/src/App.tsx
2. Click on the `two` link and watch the console
4. `isLoading` is never set to `true` when clicking back and forth from `root` to `two` routes

**Expected behavior**
If setting `cacheTime: 0` I would expect that the fetch gets recalled and the loadings states are `true` until the fetch resolves.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: chrome
 - Version: 86.0.4240.111 

**Additional context**

**Comment by boschni** [comment]
Thanks for reporting! Fixed in `3.2.0-beta.12`

**Comment by iamjohnlong** [comment]
@boschni will this be fixed in `v2`?

**Comment by iamjohnlong** [comment]
@boschni any thoughts on this being fixed in `v2`? Sorry to bug I have a large project in running `v2`.

**Comment by boschni** [comment]
Sure you are not able to use staleTime 0 together with isFetching?

**Comment by iamjohnlong** [comment]
I've tried both 
```js
const { isLoading, error, data } = useQuery(
    "repo",
    () =>
      fetch(
        "https://api.github.com/repos/tannerlinsley/react-query"
      ).then((res) => res.json()),
    {
      cacheTime: 0,
      staleTime: 0
    }
  );
```
and 
```js
const { isLoading, error, data } = useQuery(
    "repo",
    () =>
      fetch(
        "https://api.github.com/repos/tannerlinsley/react-query"
      ).then((res) => res.json()),
    {
      staleTime: 0
    }
  );
```

with the same issue. https://codesandbox.io/s/optimistic-bohr-bh9dk?file=/src/App.tsx

It also gets stuck in a infinite loop making requests on iOS safari.

**Comment by boschni** [comment]
What if you try to use `isFetching` instead of `isLoading`?

**Comment by iamjohnlong** [comment]
@boschni things are working correctly here https://codesandbox.io/s/goofy-tharp-h5ifu

I had to update the cache key to use an id `["repo", id]`. Using a static query key like "repo" seems to not respect `cacheTime` or `staleTime`, not sure if that's by design?

**Comment by boschni** [comment]
Changing the query key should not matter, but the `cacheTime` is generally not used and should not be changed most of the time, `staleTime: 0` should be enough.
