### ISSUE TITLE
[v3] allow multiple arguments on mutation function

### ISSUE THREAD

**Issue by stefanprobst** [tannerlinsley/react-query#1226]
**Describe the bug**

i would like to be able to pass multiple arguments (`TVariables[]`) to a `mutate` function, which currently fails with a type error. while it is possible to pack all arguments in one object, i think it makes sense to keep some things separate, e.g. for passing custom headers.

**To Reproduce**

1. create hook for mutation:

```ts
function useCreatePost() {
  return useMutation(
    (body: { title: string }, headers?: { [key: string]: string }) => {
      return fetch('https://jsonplaceholder.typicode.com/posts', {
        method: 'POST',
        body: JSON.stringify(body),
        headers: {
          ...headers,
          'Content-type': 'application/json',
        },
      }).then((response) => response.json());
    }
  );
}
```

2. call hook with two arguments:

```ts
mutate({ title: 'A post' }, { Accept: 'application/json' })
```
which will result in type error: "Argument of type '{ Accept: string; }' is not assignable to parameter of type 'MutateOptions<any, unknown, { title: string; }, unknown>'."

**Expected behavior**
it would be cool if this would work in v3.

related: https://github.com/tannerlinsley/react-query/discussions/1085

**Comment by tannerlinsley** [comment]
We may consider this in v4. v3 is going to retain the current API style for now.
