### ISSUE TITLE
Cannot switch the active status correctly when using Suspense

### ISSUE THREAD

**Issue by vimcaw** [tannerlinsley/react-query#1227]
**Describe the bug**
When using Suspense, if you use `useQuery` to fetch data in a component and repeatedly switch the query key, the active status of the query will be incorrect.

**To Reproduce**
https://codesandbox.io/s/react-query-bug-reproduction-cannot-switch-the-active-status-correctly-when-using-suspense-j7f91?file=/src/App.js

Note the devtool at the bottom.

### Reproduction 1
1. Waiting for the initial query `A` to complete.
2. Click `Invalidate Query` button, you can see the number has changed.
3. Click `Switch Key` button, Waiting for the query `B` to complete.
4. Click `Switch Key` button again, the cached result of `A` is displayed on the screen, but the active query is still `B` in devtool.
5. No matter how you switch the key, the active query never changes;
6. Click `Invalidate Query` button, nothing happen.

### Reproduction 2
1. Waiting for the initial query `A` to complete.
2. Click `Invalidate Query` button, you can see the number has changed.
3. Click `Switch Key` button, Waiting for the query `B` to complete.
4. Click `Invalidate Query` button, both of queries `A` and `B` become `inactive` in devtool and nothing happens.
5. No matter how you switch the key, no one can be `active`.

**Expected behavior**
Switching the active state correctly

**Screenshots**
![image](https://user-images.githubusercontent.com/21964227/97408103-9f82a600-1936-11eb-9d8a-3ba8ddcfbba1.png)

As you look, two query key has been set to `inactive`.

**Desktop (please complete the following information):**
 - OS: macOS 10.15.7
 - Browser: chrome
 - Version: 86.0.4240.111

**Additional context**
This problem only appears under `suspense mode`, it can work fine by setting `suspense` to `false`.

**Comment by tannerlinsley** [comment]
This is related to #1160, so I think we're going to track this there.
