### ISSUE TITLE
Not able to run an example of react-query@3 in react-native

### ISSUE THREAD

**Issue by Josema** [tannerlinsley/react-query#1228]
**To Reproduce**
In my example I use QueryCache and QueryClient because in the docs you have one and in the codesandbox you have the other one:
https://react-query-beta.tanstack.com/overview#enough-talk-show-me-some-code-already

```js
import React from 'react'
import {
    QueryCache,
    QueryClient,
    QueryClientProvider,
    ReactQueryCacheProvider
} from 'react-query'

const queryCache = new QueryCache()
const queryClient = new QueryClient({})

export default function App() {
    return (
        <QueryClientProvider client={queryClient}>
            <ReactQueryCacheProvider queryCache={queryCache}>
                <Body />
            </ReactQueryCacheProvider>
        </QueryClientProvider>
    )
}
```

**Screenshots**
![image](https://user-images.githubusercontent.com/1819888/97450608-3483a000-1933-11eb-8efa-9c3aeb8015c2.png)

**Smartphone (please complete the following information):**
 - Device: Android Emulator
 - OS: Windows

**Additional context**
If I remove `<ReactQueryCacheProvider` and I use `useQuery` then I get another error:
![image](https://user-images.githubusercontent.com/1819888/97451479-12d6e880-1934-11eb-844d-25351e23f4c8.png)

**Comment by Josema** [comment]
Is there a working example using react-query@3 in react-native?

**Comment by tannerlinsley** [comment]
Currently we do not have any hosted examples for React Native. The example you are referring to has been updated to reference the latest released beta. It should work with React Native as written now.
