### ISSUE TITLE
Broken v2.26.0 version on NPM

### ISSUE THREAD

**Issue by Spy-Seth** [tannerlinsley/react-query#1235]
**Describe the bug**
On NPM a react-query v2.26.0 exist but not in GitHub (where the v2.52.2 is the last one:
- https://www.npmjs.com/package/react-query/v/2.26.0
- https://github.com/tannerlinsley/react-query/releases/tag/v2.26.0 -> 404
- https://github.com/tannerlinsley/react-query/releases/tag/v2.25.2

When I explore the source code of the v2.26 the `types` directory is missing which leads to broken consumer TS application: 
- https://unpkg.com/browse/react-query@2.26.0/
- https://unpkg.com/browse/react-query@2.25.2/

**Expected behavior**
No v2.26 or a new v2.26.1 that solve the problem.

**Additional context**
I discover this broken version by doing a `yarn up -i react-query` on my project

**Comment by tannerlinsley** [comment]
This should be fixed now with v2.26.1 (maintenance release) :)
