### ISSUE TITLE
Add option to not log to console

### ISSUE THREAD

**Issue by timomeh** [tannerlinsley/react-query#125]
First of all: I love this library. ❤️ 

## Current situation

Failed `queryFn`s will be catched and then logged to the console with `console.error`.

## Problem

I'm using react-query with React Native, which shows all `console.error` as a big red box in development mode. I expect that some of my requests can throw an error (e.g. if it's an `401 Unauthorized`). But even if I'm expecting and handling those errors, they will appear as big red box because it has been logged with `console.error`.

![image](https://user-images.githubusercontent.com/4227520/74353907-dde13080-4dba-11ea-873b-846eff57daa7.png)

I could also imagine that when I'm using react-query inside the browser, I maybe don't want errors to be logged to the console.

## Current workaround

I'm currently overriding `console.error` to ignore all those errors. 🙈 

## Proposed solution

Maybe logging could be an opt-out? Or opt-in, like a global `debug` mode?

**Comment by tannerlinsley** [comment]
Now you can replace the `console` object used internally to `log`, `warn` and `error`. Enjoy!

**Comment by narthur** [comment]
This appears to be the relevant documentation for replacing the logger (used to be called setConsole):

https://react-query.tanstack.com/reference/setLogger#_top

**Comment by narthur** [comment]
@tannerlinsley This page in the docs seems to indicate this is going away:

https://tanstack.com/query/v4/docs/guides/custom-logger

What's the correct way to prevent things from getting logged in the future? Interested both in how to do this locally and in production.

**Comment by narthur** [comment]
@TkDodo thanks for the link! I like the proposed solution. It solves both of my issues--reducing console noise in production, and eliminating console logging in unit tests where failed queries are expected. 👍

**Comment by cmacdonnacha** [comment]
If using MSW, is there any reason why I **wouldn't** want to add this at a global level during tests? 

```
setLogger({
  log: console.log,
  warn: console.warn,
  error: () => {},
});
```
