### ISSUE TITLE
[Solution] React Native Tests won't work with react-query

### ISSUE THREAD

**Issue by timomeh** [tannerlinsley/react-query#126]
_Note: This is not a bug with react-query, but I wanted to leave this here if anyone is experiencing the same problems._

## Problem

**When trying to write react-native tests for Components which use react-query, jest seemingly gets stuck without printing anything.**

## Solution

Put this inside your jest setup file:

```js
global.window = global
```

## What's happening?

[As stated in the docs](https://github.com/tannerlinsley/react-query#ssr--initial-data), react-query's hooks only return initialData (or `null`) if it's running on the server. If the hook mounts, it will re-execute, the queries will be cached and data will be fetched.

How does this affect React Native? react-query is checking if it's running on the server with `typeof window === 'undefined'`. `window` is defined in the React Native runtime, **but it's undefined in the react-native jest preset!**

This causes the `useEffect` hooks of react-query to get stuck in an infinite loop, because it correctly assumes that when `useEffect` is executed, it is running inside the client. But `window` is still undefined, thus react-query thinks it's still on the server, and the whole thing repeats forever.

Setting `window` to something other than undefined will resolve this. Since `window` seems to have the same attributes as `global`, I just cross-referenced them, to reduce the difference between both environments.

I opened a PR inside react-native (https://github.com/facebook/react-native/pull/28067).

**Comment by tannerlinsley** [comment]
This is indeed very strange. Let's keep an eye on that issue in react-native, but going to close this for triage now. Thanks for finding a solution/workaround!

**Comment by emeraldsanto** [comment]
This absolutely needs to be documented somewhere (maybe under the "React Native" section in the docs?), I just spent a whole day trying to find a solution to Jest refusing to run a particular test (the only one using `react-query`) until I luckily stumbled upon this issue.

**Comment by timomeh** [comment]
My fix just got merged into https://github.com/facebook/react-native/, so hopefully once it's released, it will ✨ just work ✨
