### ISSUE TITLE
ReactQueryDevtools component triggers warning from axe-core

### ISSUE THREAD

**Issue by gildub** [tannerlinsley/react-query#1262]
**Describe the bug**
When using axe-core (version 4.0.0) we're getting a warning triggered by following rule [All page content must be contained by landmarks](https://dequeuniversity.com/rules/axe/4.0/region) because `<ReactQueryDevtools />` is rendered as `<div class="ReactQueryDevtools">`.

1. Yarn add -D @axe-core/react
2. Add  `<ReactQueryDevtools />
3. yarn start:dev

**Expected behavior**
ARIA attributes should conform to valid value, so no axe-core warning appears. 

**Screenshots**
![axe-issue1](https://user-images.githubusercontent.com/1901741/98266316-70011880-1f8a-11eb-8b3d-800911b8aee3.png)

**Desktop**
 - OS: Linux Fedora 33
 - Browser: Firefox 82.0.2
 - Version: [e.g. 22]

**Additional context**
Please see https://github.com/konveyor/virt-ui/blob/master/src/index.tsx#L15 and https://github.com/konveyor/virt-ui/blob/master/src/app/index.tsx#L30 for full context.

**Comment by tannerlinsley** [comment]
A PR to fix this is welcomed :)

**Comment by mturley** [comment]
You got it @tannerlinsley :) https://github.com/tannerlinsley/react-query-devtools/pull/77

**Comment by mturley** [comment]
Also I'm digging the VS Code `workbench.colorCustomizations`, didn't know you could do that 😛
