### ISSUE TITLE
Using a complex key in infiniteQuery overrides the cursor

### ISSUE THREAD

**Issue by kud** [tannerlinsley/react-query#1263]
**Describe the bug**
Setting something else than a string as key in infiniteQuery overrides the cursor.

**To Reproduce**
```
  const infiniteQuery = useInfiniteQuery(
    "infiniteQuery",
    (key, cursor = 1) => console.log(cursor) // 1
  )
```

👍🏻

```
  const infiniteQuery = useInfiniteQuery(
    ["infiniteQuery", { test: "hello" }],
    (key, cursor = 1) => console.log(cursor) // { test: "hello" }
  )
```

👎🏻

**Expected behavior**
It should work as a classic query for the key, and the cursor should be the same than an infinite query with only a string as key. Meaning, console.log should be `1`

**Desktop (please complete the following information):**
 - OS: macOS 10.15.7
 - Browser: firefox 84.0a1
 - Version: react-query `2.26.2`

**Sandbox**
https://codesandbox.io/s/polished-firefly-jhxvv?file=/pages/index.js

**Comment by kud** [comment]
![image](https://user-images.githubusercontent.com/655838/98376332-9afb7300-2043-11eb-8737-bbfb7429ad0f.png)

**Comment by tannerlinsley** [comment]
First off, the docs state that the key parts will be spread into the args of your fetcher function, so this works as intended:

```js
  const infiniteQuery = useInfiniteQuery(
    ["infiniteQuery", { test: "hello" }],
    (prefixName, { test }, cursor = 1) => console.log(cursor) // { test: "hello" }
  )
```

Secondly, in the next major version (v3) coming out soon, this will not be the case and instead will simply provide a context object for you to use: https://react-query-beta.tanstack.com/guides/migrating-to-react-query-3#query-function-parameters

**Comment by kud** [comment]
Alright, thank you very much!

**Comment by thongly** [comment]
I'm glad a found this issue. I noticed the spreading of args, but had forgotten about that section in the docs.

[_**All query keys get passed through to your query function as parameters in the order they appear in the array key:**_](https://react-query.tanstack.com/docs/guides/queries#query-key-variables)

@tannerlinsley - Good call on that for v3 too
