### ISSUE TITLE
Typescript types not compatible with cancellation

### ISSUE THREAD

**Issue by gunn4r** [tannerlinsley/react-query#1265]
**Describe the bug**
Documentation states to attach a cancel method to the promise returned from a QueryFunction. However you cannot attach a cancel method to a promise because it's not a method defined on the Promise interface.

```
TS-2339: Property `cancel` does not exist on type `Promise<Response>` 
```

**To Reproduce**
 Simply try one of the cancellation examples from the documentation in a typescript environment:

```const query = useQuery('todos', () => {
   // Create a new AbortController instance for this request
   const controller = new AbortController()
   // Get the abortController's signal
   const signal = controller.signal
 
   const promise = fetch('/todos', {
     method: 'get',
     // Pass the signal to your request
     signal,
   })
 
   // Cancel the request if React Query calls the `promise.cancel` method

   // ******* THIS WILL CAUSE A TYPE ERROR *******
   promise.cancel = () => controller.abort()
 
   return promise
 })
```

**Expected behavior**
Should be able to attach a cancel method with the built in types.

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.6
 - Browser: Chrome
 - Version: 86.0.4240.111

**Additional context**

react-query v 2.25.2
react v 16.13.1
typescript v 3.9.7

**Comment by gunn4r** [comment]
For now I am just typecasting the promise to `any` but really the shipped types should handle this.

**Comment by sergiodxa** [comment]
I think there is no way for React Query to handle this, except you want RQ to globally overwrite the types of a promise.

**Comment by gunn4r** [comment]
> I think there is no way for React Query to handle this, except you want RQ to globally overwrite the types of a promise.

Something like this I would think would do the trick...

```
interface ExtendedPromise<T> extends Promise<T> {
  cancel?: ...
}
```

**Comment by sergiodxa** [comment]
That will not solve the problem, the error is because the Promise instance returned by fetch doesn't have a property cancel so you can't assign it without TS yelling to you, you would need to cast the type of the promise returned by fetch to be your ExtendedPromise so you can add that cancel property.

**Comment by gunn4r** [comment]
You are, of course, correct. You're right this doesn't seem like something that could be resolved by RQ. Thanks!

**Comment by christopher-caldwell** [comment]
Bummer

**Comment by mwisnicki** [comment]
How about accepting result of `{promise, cancel?}` ?
