### ISSUE TITLE
Add config option to fix bad UX with Next.js static pre-rendering.

### ISSUE THREAD

**Issue by flybayer** [tannerlinsley/react-query#1271]
### Context

Next.js static pre-renders any page not doing SSR. During pre-rendering on the server, route parameters are empty (because there's no request). For example, a dynamic page like `/products/[productId].tsx` will be rendered with `query.productId === undefined`.

### Problem 1

`useQuery` will call the query function during pre-rendering, on the server, which will usually cause noisy but harmless error logs (but they are alarming if you don't know exactly what's happening here).

**Workaround**: If `typeof window === 'undefined'`, pass a never resolving promise instead of the real query function.

### Problem 2

Because the page was statically rendered with empty route params, Next.js will make the first render on the client also have empty route params (otherwise React complains). And it's very common to use a route parameter with `useQuery`. 

So now we have a problem because on the first render `useQuery` will call your query function which has invalid parameters (route parameter is undefined instead of string, for example). And so this causes noisy but harmless error logs (but they are alarming if you don't know exactly what's happening here).

**Workaround**: If the router is not ready, pass a never resolving promise instead of the real query function AND use a bogus query key.

You can see [in the blitz code](https://github.com/blitz-js/blitz/blob/canary/packages/core/src/use-query-hooks.ts#L41-L45) how we are currently using both workarounds.

### Proposed Solution

At first glance, the `enabled` config flag seems like the answer. However, that doesn't work because in concurrent mode, useQuery does not throw when `enabled = false`.

So we need a new config flag similar to `enabled` that let's us disable the query function being called but while still throwing the loading promise.

**Alternate solution:** Change the current behavior so that useQuery always throws even if `enabled = false`.

### Additional context
Earlier discussion about this problem: https://github.com/tannerlinsley/react-query/issues/744

**Comment by tannerlinsley** [comment]
So are you currently passing a never resolving promise for `typeof window === 'undefined'?

**Comment by tannerlinsley** [comment]
Are you currently fixing this by passing a never resolving promise when `typeof window === 'undefined'?

**Comment by flybayer** [comment]
@tannerlinsley I'm doing that, but that only solves Problem 1, not Problem 2.

**Comment by tannerlinsley** [comment]
When a query is disabled initially, it does have an `isIdle` state. Are you able to utilize that somehow to just render nothing until the parameters eventually resolve?

**Comment by flybayer** [comment]
No, because we want to render the suspense fallback, not something else.

**Comment by tannerlinsley** [comment]
@flybayer Did you have any ideas on how to fix this in RQ?

**Comment by flybayer** [comment]
@tannerlinsley yes, in my original post.

> So we need a new config flag similar to `enabled` that let's us disable the query function being called but while still throwing the loading promise.
> 
> **Alternate solution:** Change the current behavior so that useQuery always throws even if `enabled = false`.

|     |  Throw Loading Promise | Execute Query |
| --- |  -         | - |
| `enabled === false` | ❌  | ❌ |
| `queryEnabled === false` | ✅  | ❌ |

My personal preference would be not add a new flag but instead change current behavior to always throw promise if `enabled = false` and `suspense = true`.

**Comment by tannerlinsley** [comment]
Yeah, I think I'm on your side with this one. Can you think of any downsides to this? Any expectations where people would expect `enabled = false` to not throw in suspense? This basically means that `enabled` doesn't really work in suspense at all...

**Comment by TkDodo** [comment]
> My personal preference would be not add a new flag but instead change current behavior to always throw promise if enabled = false and suspense = true.

I would also not prefer a new flag, as there are quite many already :)

> This basically means that enabled doesn't really work in suspense at all...

If I understood this correctly, it would still "work", it would just always render the Suspense fallback if you set `enabled=false`. Not sure what people are currently rendering when a query is disabled, but if you want a differentiation between disabled and loading, you wouldn't get it. Personally, our dependent queries render a loading spinner anyways if they are disabled because they wait for some data, so 🤷 .

Middle ground would be to enhance the enabled boolean to `true | false | 'someString'` - I think that would still be better than an extra flag :)

**Comment by tannerlinsley** [comment]
Let’s just have it suspend all the time then. Suspense is experimental so I’m not too concerned about it

**Comment by flybayer** [comment]
Sweet. And yeah if you don't want it to suspend, simply set `suspense: false`

**Comment by tannerlinsley** [comment]
Wanna PR that Brandon?

**Comment by flybayer** [comment]
Yeah, but too busy! 😅

**Comment by boschni** [comment]
What if you have two queries in a suspense component and one of them is conditional? If the conditional query would throw a never resolving promise, then the component would never render? Think the custom `useQuery` hook is a pretty good solution :)

**Comment by tannerlinsley** [comment]
This is still an interesting edge case, but one that I haven't seen anywhere in the wild other than blitz, and it looks like @flybayer was able to work around it on his end. With that in mind, I think we can just leave it up to @flybayer to propose a fix if and when he finds the time.

**Comment by JanRuettinger** [comment]
@flybayer 


I am facing the same issue. Do you have a code snippet of your workaround at hand?
