### ISSUE TITLE
Calling remove() with cacheTime: 0 causes infinite query fetches

### ISSUE THREAD

**Issue by priyajeet** [tannerlinsley/react-query#1278]
**Describe the bug**
Calling remove() when cacheTime is 0 causes the xhr to happen endlessly.

**To Reproduce**
1. Go to https://codesandbox.io/s/sleepy-jennings-mryos?file=/src/index.js
2. Open the network panel
2. Click on Remove button to remove the query from cache and re-render the component
4. See xhr being executed infinitely in the network panel

**Expected behavior**
Should only make one XHR

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Chrome
 - Version: 2.26.2

**Additional context**
Similar to issue #1019

**Comment by boschni** [comment]
Seems to be fixed in V3: https://codesandbox.io/s/kind-brahmagupta-mz833?file=/src/index.js

**Comment by priyajeet** [comment]
Will it back ported to the latest released version? There isn't any documentation for upgrading to V3 and the other linked bug above it was mentioned to use the latest and not 3.x

**Comment by boschni** [comment]
A migration guide can be found here: https://react-query-beta.tanstack.com/guides/migrating-to-react-query-3 . V3 is expected to be released soon so this fix will not be back-ported.
