### ISSUE TITLE
Query Cache - network request nevertheless

### ISSUE THREAD

**Issue by nicklas-delphai** [tannerlinsley/react-query#1284]
**Describe the bug**
For my codebase and the codesandbox provided by #1082 the cache doesn't seem to kick in.

**To Reproduce**
1. Go to [mentioned codesandbox](https://rz197.csb.app) in #1082
2. Open network tab in dev tools
3. cache fills according to react-query-devtools but data is re-fetched every time nevertheless.

**Expected behavior**
On fetch of a cached query, no network request is made.

**Screenshots**
![2020-11-12_21-59](https://user-images.githubusercontent.com/67684610/98995727-0d7fbd80-2532-11eb-84e8-3063abdfd542.png)

**Desktop (please complete the following information):**
 - OS: Linux (Arch)
 - Browser: vivaldi
 - Version: 3.4.2066.99

also tested in chrome and firefox (no better there). I also tried playing around with the `react-query` version but I couldn't find any version with behavior as expected.

**Comment by tannerlinsley** [comment]
It is caching, but always updating in the background. Try setting the staleTime option to a higher number.

**Comment by nicklas-delphai** [comment]
Ok never mind me. The problem was `staleTime`. After setting `staleTime: Infinity` I had my expected behavior. Although I don't quite understand why a query going stale immediately and being cached could be useful.

**Comment by tannerlinsley** [comment]
It defaults to being as up to date as possible. Defaulting to any stale time greater than zero is already an opinion that most would want to change. This keeps things simple and configurable

**Comment by nicklas-delphai** [comment]
Sure that makes sense, but wouldn't you then want to just disable cache entirely?

**Comment by tannerlinsley** [comment]
No because then you’ll hit hard loading screens for data you have already seen.

**Comment by nicklas-delphai** [comment]
Ok. Anyway thanks a lot. I'm also using you're table library which I enjoy very much.
