### ISSUE TITLE
useMutation with Next.js API route error handling

### ISSUE THREAD

**Issue by Ihatetomatoes** [tannerlinsley/react-query#1285]
**Describe the bug**
I am using React Query's `useMutation` to subscribe users to ConvertKit email list using Next.js API route `/pages/api/subscribe.js`.

Here is a simplified code of the form.

```javascript
import React from "react";
import { useForm } from "react-hook-form";
import { useMutation } from "react-query";

const SignupForm = () => {
  // front end validation with react-hook-form
  // prevent submitting invalid or empty emails
  const { handleSubmit } = useForm();

  // react query mutation that will call our API route
  const [mutate, { isLoading, isSuccess, isError, error }] = useMutation(
    ({ email }) => {
      return fetch(`/api/subscribe?email=${email}`);
    }
  );

  // handle form submit
  const onSubmit = (data) => mutate(data);

  // if API returns error show it to the user
  if (isError) {
    return <p>{error}</p>;
  }

  // if success show confirmation message instead of the form
  if (isSuccess) {
    return <p>Success</p>;
  }

  return (
    <form className="w-full max-w-sm" onSubmit={handleSubmit(onSubmit)}>
      ...
    </form>
  );
};

export default SignupForm;
```

Here is the simplified endpoint API route:

```javascript
import fetch from "isomorphic-unfetch";

export default async (req, res) => {
  // 1. Destructure the email address from the request query.
  const { email, tags } = req.query;

  if (!email) {
    // 2. Throw an error if an email wasn't provided.
    return res.status(400).json({ error: "Email is required" });
  }
  ...
};
```

Is there a way for the Next.js API route to set `isError` to **true** and also return the `error` itself?

Or do I need to check for the returned `data`, check for the `status`, and handle the error in my component state?

At the moment any response from the Next.js API route returns `isSuccess` and `isError` or `error` is never updated.

Any suggestions on how to make **isError** and **error** work with [Next.js API route](https://nextjs.org/docs/api-routes/introduction) would be great. Thanks

**Expected behavior**
I would expect that `isError` is true if the API returns 400 status.

**Screenshots**
<img width="492" alt="img_react-query-next" src="https://user-images.githubusercontent.com/735672/99013456-ab13d500-25a4-11eb-87cd-881265fd2a19.png">

**Comment by Andrey-Bazhanov** [comment]
But in your example status is 200. Next api routes doesn't use express. So you need set status like this `res.statusCode = 400`

**Comment by Andrey-Bazhanov** [comment]
Looks like your mutation function doesn't throwing error... can you share more code?

**Comment by Ihatetomatoes** [comment]
I can share the whole `subscribe.js` file but I am trying to make the example minimal to start with.

What would I need to change in the above code to make the `isError` and `error` update?

**Comment by Ihatetomatoes** [comment]
Just to clarify. If I don't send email in the request I want the isError to be true but it is always false.

**Comment by Andrey-Bazhanov** [comment]
To get `error` in mutation state you need emit error in your mutation function. In your case thats how fetch work (promise always success if request sent "The Promise returned from fetch() won’t reject on HTTP error status even if the response is an HTTP 404 or 500. Instead, it will resolve normally (with ok status set to false), and it will only reject on network failure or if anything prevented the request from completing." [details)](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API)

so you code should looks like:
```
// subscribe  
const subscribe = async (email) => {
  const res = await fetch(`/api/subscribe?email=${email}`);
  if (!res.ok) throw 'error'
}

// your component
const [mutate, { isLoading, isSuccess, isError, error }] = useMutation(({ email }) => subscribe(email) );
```

**Comment by Ihatetomatoes** [comment]
Oh ok, this works fine, throwing the error in the subscribe function works fine.

```if (!res.ok) throw 'error'```

So there is no way to get the different error messages returned by the endpoint?

![image](https://user-images.githubusercontent.com/735672/99044269-9c98de00-25e3-11eb-86b1-3100dc7da3c6.png)

**Comment by devGW** [comment]
> Oh ok, this works fine, throwing the error in the subscribe function works fine.
> 
> `if (!res.ok) throw 'error'`
> 
> So there is no way to get the different error messages returned by the endpoint?
> 
> ![image](https://user-images.githubusercontent.com/735672/99044269-9c98de00-25e3-11eb-86b1-3100dc7da3c6.png)

Did you solve the this problem?

**Comment by Ihatetomatoes** [comment]
I ended up throwing the `error` in the subscribe function and display this error to the user. 

```
if (!res.ok) throw 'custom error message
```

**Comment by rhadu** [comment]
Based on @Andrey-Bazhanov 's initial solution i made it work this way. Not sure if it breaks React-query's workflow, just started yesterday to play with it.

In my example the api is inserting the email to a supabase db and if the email is not unique i need to show the error.

In the api function i have the following
``` js
if (error) return res.status(401).json({ error: error.message })
return res.status(200).json({ data })
```

And in the custom hook
``` js
// subscribe  
const subscribe = async (email) => {
  const res = await fetch(`/api/subscribe?email=${email}`);
  const apiRes = await res.json()

  if (!res.ok) throw apiRes.error
}

// your component
const [mutate, { isLoading, isSuccess, isError, error }] = useMutation(({ email }) => subscribe(email) );
```

**Comment by TkDodo** [comment]
>  Not sure if it breaks React-query's workflow, just started yesterday to play with it.

That looks fine. react-query expects a resolved or rejected _Promise_ to work correctly. However, `fetch` doesn't emit failed promises on erroneous status codes - only on network errors. Other libraries like `axios` or `ky` do this out of the box. For fetch, you have to `throw if not ok`. See also [usage with fetch and other libraries that do not throw by default](https://react-query.tanstack.com/guides/query-functions#usage-with-fetch-and-other-clients-that-do-not-throw-by-default)
