### ISSUE TITLE
Remove type definitions file: react-query/dist/index.d.ts

### ISSUE THREAD

**Issue by nikoskleidis** [tannerlinsley/react-query#129]
After I updated to the latest version 0.4.2 I had a problem with typescript. There seams to be a confusion between the types located in `react-query/dist/index.d.ts` and `@types/react-query/index.d.ts`.
When I deleted the first one (`react-query/dist/index.d.ts`) everything was working as expected. Since there is a dependency to @types/react-query what is the need for the dist/index.d.ts?

**Comment by rbrcsk** [comment]
Until it's removed, here's a workaround. In your tsconfig.json, add:

```
    "baseUrl": ".",
    "paths": {
      "react-query": ["./node_modules/@types/react-query"]
    }
```

**Comment by tannerlinsley** [comment]
Removed in the latest release :) Thanks!
