### ISSUE TITLE
staleTime not work as expected on queryCache.setQueryData

### ISSUE THREAD

**Issue by cxc421** [tannerlinsley/react-query#1296]
**Describe the bug** 

Let's say I have a _Display_ component to display some data from an API, so I will use _useQuery_ like this:

```js
function Display() {
  const { data, isError, isIdle, isLoading } = useQuery(queryKey, fetchDataApi);

  if (isError) {
    return `Something Wrong`;
  }

  if (isIdle || isLoading) {
    return `Loading...`;
  }

  return <h1>{data}</h1>;
}
```

But in order to let users see the data as soon as possible, I want to set the cache of the data in advance.  

This pre-set cache may come from other APIs, and I believe that these data will not change in a short time, so I set the cached staleTime to 5 seconds to avoid unnecessary queries from the _Display_ component.  

```js
function App() {
  const [showDisplay, setShowDisplay] = useState(false);

  useEffect(() => {
    bootstrapApi().then((data) => {
      queryCache.setQueryData(queryKey, data, { staleTime: 5000 });
      setShowDisplay(true);
    });
  }, []);

  return showDisplay ? <Display /> : null;
}
```
However, this _Display_ component still triggers an additional query through _useQuery_.

**To Reproduce**

1. Go to https://codesandbox.io/s/staletime-issue-v3-ln0ew?file=/src/App.js
2. The web page displays "Data from queryFn of useQuery" instead of "Data from queryCache.setQueryData".

**Comment by cxc421** [comment]
It seems that the example I wrote has some errors, and this issue is related to #962.  So I close this issue first, thanks.

**Comment by TkDodo** [comment]
could also reproduce in v3: https://codesandbox.io/s/staletime-issue-v3-forked-c95c5

Judging from the typescript types, options is of type `SetDataOptions`:

https://github.com/tannerlinsley/react-query/blob/9d66f43d0dc89213112d5aa90076037a9fff6933/src/core/queryClient.ts#L104-L111

which is defined as:

https://github.com/tannerlinsley/react-query/blob/9d66f43d0dc89213112d5aa90076037a9fff6933/src/core/query.ts#L70-L72

so it doesn't take a `staleTime`. The config is also not passed to `queryCache.build`, so I don't see how it could work.

The v3 docs also don't mention that you can pass options: https://react-query-beta.tanstack.com/reference/QueryClient#queryclientsetquerydata

The v2 docs still mention it though: https://react-query.tanstack.com/docs/api#querycachesetquerydata

so, I'm not entirely sure if this is supposed to work ... ?

**Comment by tannerlinsley** [comment]
In v3, you can optionally set the `updatedAt` to a unix time stamp of when it was considered fresh. This goes along with the core concept in RQ that stale times do not define when the data becomes stale, but instead define when a subscriber *considers* the data it's subscribing to as stale (big difference). 

Once v3 is merged, everything should be in the clear.

**Comment by Stancobridge** [comment]
> In v3, you can optionally set the `updatedAt` to a unix time stamp of when it was considered fresh. This goes along with the core concept in RQ that stale times do not define when the data becomes stale, but instead define when a subscriber _considers_ the data it's subscribing to as stale (big difference).
> 
> Once v3 is merged, everything should be in the clear.

If I set the updatedAt to a date in the future will the data still be available in the current time
