### ISSUE TITLE
useIsFetching does not count for useMutation

### ISSUE THREAD

**Issue by ilkerceng** [tannerlinsley/react-query#1298]
**Describe the bug**
I use useIsFetching for global loading component. It works weel with useQuery, but does not triggered with service call using useMutation. I use the latest version 2.26.2.

**Comment by lucbpz** [comment]
Quoting the docs:

> This isFetching property is an integer representing how many queries, if any, in the cache are currently fetching (including background-fetching, loading new pages, or loading more infinite query results)

Mutations are supposed to represent individual actions that change some data, so when you mutate you don't retrieve data or update from the cache, so I would not expect the `isFetching` to represent that state (it is not being represented in the `useMutation` hook).

**Comment by tannerlinsley** [comment]
In the future, we *may* introduce a `useIsMutating` hook or something similar, but for now their current functionality is intentional.

**Comment by ilkerceng** [comment]
@lucbpz @tannerlinsley Thanks 👍

**Comment by kachkaev** [comment]
@tannerlinsley WDYT of `useIsMutating` in some 3.x release? I wonder if the new architecture allows that with relative ease.

**Comment by tannerlinsley** [comment]
I’d be good with that

**Comment by kripod** [comment]
@tannerlinsley is there a way to implement `useIsMutating` as a userland feature? For instance, by creating a context for tracking the amount of pending mutations and then adding a wrapper for `useMutation` to manage the provider-based state.

I would love to hear your recommendations on how to implement this.

**Comment by TkDodo** [comment]
There is a `MutationObserver` exported, but it doesn’t have any documentation as far as I can see.

**Comment by kripod** [comment]
I’ve just created a custom `useIsMutating` hook which looks as follows:

```ts
import * as React from "react";
import { useQueryClient } from "react-query";

export function useIsMutating() {
	const queryClient = useQueryClient();
	const [pendingMutations, setPendingMutations] = React.useState(0);

	React.useEffect(
		() =>
			queryClient.getMutationCache().subscribe(() => {
				setPendingMutations(
					queryClient
						.getMutationCache()
						.getAll()
						.filter((mutation) => mutation.state.status === "loading").length,
				);
			}),
		[queryClient],
	);

	return pendingMutations;
}
```

I tried my best to keep it as simple as possible.

**Comment by TkDodo** [comment]
I think you need to unsubscribe in the effect cleanup function, but looks good otherwise!

**Comment by kripod** [comment]
@TkDodo the `subscribe` method returns with a cleanup function, so it should do that exactly 😊

**Comment by TkDodo** [comment]
Oooh nice, didn’t see that 🎉

**Comment by kripod** [comment]
@TkDodo As I noticed that you’re a collaborator of React Query, I would like to ask if [my implementation](https://github.com/tannerlinsley/react-query/issues/1298#issuecomment-761056202) could be exported as a built-in utility for everyone to be reused. I don’t feel motivated to open a PR for this right now, but I would love to see an official implementation of this proposal.

**Comment by TkDodo** [comment]
we would have to adapt it a bit to match the `useIsFetching` api, but if there is demand I don't see why not. @tannerlinsley ?

**Comment by ilkerceng** [comment]
thanks so much @kripod for sharing. I will try your implementation soon.

**Comment by benediktviebahn** [comment]
Any update? Would be great if this could be implemented.

**Comment by TkDodo** [comment]
do you want to give it a try @benediktviebahn ? Take the linked implementation above and adapt it to match `useIsFetching` api wise :)

**Comment by benediktviebahn** [comment]
Sure, I will do it later today :)

**Comment by ilkerceng** [comment]
@benediktviebahn the code written https://github.com/tannerlinsley/react-query/issues/1298#issuecomment-761056202 by @kripod works like o bomb :)
