### ISSUE TITLE
V3 - invalidateQueries ignores staleTime

### ISSUE THREAD

**Issue by timothyallan** [tannerlinsley/react-query#1310]
**Describe the bug**
In 3.2.0-beta.27 - Having a long/infinite `staleTime` prevents refetching after doing a `queryClient.invalidateQueries`.

The docs at https://react-query-beta.tanstack.com/guides/query-invalidation say 
````
When a query is invalidated with invalidateQueries, two things happen:
It is marked as stale. This stale state overrides any staleTime configurations being used in useQuery or related hooks
````
It doesn't look like that's happening.

**To Reproduce**
Set up a query/client with a long staleTime:
````
const queryClient = new QueryClient({
    defaultOptions: { queries: { refetchOnWindowFocus: false, staleTime: Infinity, suspense: false } },
  });
````

Create and consume a query with a key in a component 

````
  const { data, isLoading } = useQuery<MyReturnData[]>('mykey', () => myDataFunc, {
    placeholderData: [],
  });
````

It loads fine initially, then call `invalidateQueries` with some/none/all of the params I've got below:

````
  queryClient.invalidateQueries('mykey', {
            stale: true,
            refetchActive: true,
            refetchInactive: true,
          }),
````

The query never hits my API to pull the new data. As soon as I remove `staleTime: Infinity` from the `defaultOptions`, it works great and refreshes when I invalidate it. This also happens if I define `staleTime: Infinity` in the `useQuery` as well, and not in the defaults.

**Comment by boschni** [comment]
Hi @timothyallan! This test should cover the functionality you are describing: https://github.com/tannerlinsley/react-query/blob/beta/src/react/tests/useQuery.test.tsx#L892 . Could you provide a playground which replicates the bug?

**Comment by TkDodo** [comment]
I forked the simple example and it works like advertised on beta.29: https://codesandbox.io/s/sparkling-wind-m9020

**Comment by timothyallan** [comment]
Okay, that’s what I wondered, thanks. It’s probably an implementation issue on my end then if it’s working out if the box for you.

**Comment by yepMad** [comment]
@timothyallan Did you understand what was happening? Here the same thing happens. Still trying to figure out if it's a problem on my end.

**Comment by timothyallan** [comment]
> 

Wish I could be more help, but that was a long time ago! If it helps, here's my current options which are currently working:

```
defaultOptions: {
    queries: {
      refetchOnWindowFocus: false,
      staleTime: Infinity,
      suspense: false,
      refetchOnMount: true,
      refetchOnReconnect: false,
    },
  },
```

**Comment by yepMad** [comment]
Unfortunately nothing has changed. But thank you very much for that, I will investigate further and bring news when I find out.

**Comment by yepMad** [comment]
Ok, I have something.

This works:

queryClient.invalidateQueries(getUserDataQueryKey(), {
      exact: true,
      refetchActive: true,
      refetchInactive: false,
      stale: false,
});

This doesn't works:

queryClient.invalidateQueries(getUserDataQueryKey(), {
      exact: true,
      refetchActive: true,
      refetchInactive: false,
      stale: true,
});

Why? How do I include stale or no stale queries in same invalidate?

**Comment by timothyallan** [comment]
FWIW, my invalidates don't include any options and work for what I need them for i.e. `queryClient.invalidateQueries(mykey);`

**Comment by TkDodo** [comment]
@yepMad please provide a codesandbox reproduction of what is working or not working for you. That would make it a lot easier to analyze on our end. Thanks.
