### ISSUE TITLE
useQueryClient instead of useQueryCache in the documentation

### ISSUE THREAD

**Issue by sitek94** [tannerlinsley/react-query#1316]
**Describe the bug**
Throughout the Optimistic Updates section in the documentation there is `queryClient` being used everywhere where I normally would expect `queryCache`. It's initialized using `useQueryClient` hook which I couldn't find anywhere else in the docs.

[Optimistic Updates Docs](https://react-query-beta.tanstack.com/guides/optimistic-updates)

```javascript
const queryClient = useQueryClient()
 
 useMutation(updateTodo, {
   onMutate: async newTodo => {
     await queryClient.cancelQueries('todos')
 
     const previousTodos = queryClient.getQueryData('todos')
 
     queryClient.setQueryData('todos', old => [...old, newTodo])
 
     return { previousTodos }
   },
   onError: (err, newTodo, context) => {
     queryClient.setQueryData('todos', context.previousTodos)
   },
   onSettled: () => {
     queryClient.invalidateQueries('todos')
   },
 })
```

I've just been using the library for couple of days and I'm not sure if it is supposed to be like this but it's a little bit confusing for a beginner like me because in all the examples and demos (which are awesome by the way ❤️ ) you are always using `useQueryCache`.

**Comment by TkDodo** [comment]
in v3, it will be `QueryClient` and `useQueryClient`, and in v2, it is `QueryCache` and `useQueryCache`. The QueryClient will also contain a QueryCache, but the methods are publicly available on the client.

Take a look at the migration guide: https://react-query-beta.tanstack.com/guides/migrating-to-react-query-3#queryclient

So your link points to `react-query-beta`, which are the docs for v3. The v2 version would be here: https://react-query.tanstack.com/docs/guides/optimistic-updates

**Comment by sitek94** [comment]
Oh I see, It all makes perfect sense now! Thank you for clarifying this!

So it's not an issue at all.
