### ISSUE TITLE
Impossible to pass multiple arguments to mutation function in useMutation hook

### ISSUE THREAD

**Issue by CedricVanhaverbeke** [tannerlinsley/react-query#1322]
**Describe the bug**
I cannot seem to pass mutliple arguments to a function created with the `useMutation` hook.

**To Reproduce**
```js
// create a mutation
const [mutation] = useMutation((...elements) => console.log(elements));

// execute the mutation with multiple parameters
mutation(1,2,3);

// output is this:
[1]
```

**Expected behavior**
I'd expect the full array of arguments like this:

```
[1,2,3]
```

Am I missing something?

**Comment by ghostd** [comment]
Hi,

As you can see in the [documentation](https://react-query.tanstack.com/docs/guides/mutations#mutation-variables) and in the [TypeScript definitions](https://github.com/tannerlinsley/react-query/blob/7535383eba20fcfb0e476dbf199823d1423cd7e1/src/core/types.ts#L270-L278) the mutation function only accepts an object as parameter.

So you can do this:
```javascript
const [mutation] = useMutation(({data: elements}) => console.log(elements));
mutation({data: [1,2,3]});
```

**Comment by TkDodo** [comment]
Here is a discussion about that topic: https://github.com/tannerlinsley/react-query/discussions/1226

**Comment by tannerlinsley** [comment]
We'll keep talking about it in #1226, but for now, the current design will stick around.

**Comment by HarryShindika** [comment]
I placed my values in an array then passed the array to mutate(). This worked
