### ISSUE TITLE
How to get data if i'm using two mutate functions in a component?

### ISSUE THREAD

**Issue by sainhimanshu9** [tannerlinsley/react-query#133]
I'm on a component where a api call exists on componentdidmount and one when use clicks on a button of that page so how can get the data of that particular api call?

**Comment by nikoskleidis** [comment]
I am not sure I understand your question completely. If I didn't please feel free to elaborate.
When you perform a mutation and you want the data returned from the api to update the data you currently have in your cache, then you can make use of the updateQuery option 
https://github.com/tannerlinsley/react-query#query-updates-from-mutations

**Comment by tannerlinsley** [comment]
Yeah, we'll need more info here. From what you've given me, I would say first that React Query only works with React hooks and if you're using `componentDidMount`, then you are probably using class components, so React Query will not work in that situation.

Going to close this for triage, but please feel free to reopen a new issue with more information. Thanks!

**Comment by sainhimanshu9** [comment]
I am using hooks only.
I'm using useEffect with empty array to act like componentDidMount.
`  const [mutate, { isLoading, data, error }] = useMutation(handleApi);
mutate({
      method: "get",
      endpoint: apiEndpoint,
      data: {}
      
    });
`
handleApi is a centralized api call function where i just need to pass request type, endpoint url and data, now...i've a component which makes an api call(1) using componentDIdMount(using useffect) which renders a certain number of list and that list contains a button which also makes an api call(2)...Now as i'm using mutate, i expect it to use data, isLoading, error like above. i've used mutate with both the api calls with different request type and endpoint url,  but as above mentioned (data, error, isloading) how to get the (data,error,isloading) for first api call and second one.

**Comment by tannerlinsley** [comment]
Your explanation is still too vague. I think the best way forward would be to create a codesandbox showing what you would like to achieve and we can help you fill in the gaps from there.
