### ISSUE TITLE
QueryCache.fetchQuery doesn't take into account the default config

### ISSUE THREAD

**Issue by ikrastinkov** [tannerlinsley/react-query#1342]
Hi

I'm using QueryCache standalone implementation on a service level.

Example:
```
const cache = new QueryCache({ defaultConfig: queries: { staleTime: Infinity, ... } });

const get = async (name): Promise<boolean> => {
  return await cache.fetchQuery(`/path${name}`, (url) => fetcher(url));
};
```
The issue that I've found is that the queries are fetched every time even though the staleTime is set to Infinity.
After a short look into the library code on github, I've fixed it by reusing the defaultConfig.queries when calling the fetchQuery function.

```
const cacheConfig = { queries: { staleTime: Infinity, ... }};
const cache = new QueryCache(cacheConfig);

const get = async (name: string): Promise<boolean> => {
  return await cache.fetchQuery(`/path/${name}`, (url) => fetcher(url), cacheConfig.queries);
};
```

I would suggest using the staleTime property from resolvedConfig when checking if the query is stale by time.
https://github.com/tannerlinsley/react-query/blob/7535383eba20fcfb0e476dbf199823d1423cd7e1/src/core/queryCache.ts#L375

This is the first time I've integrated the library, and even though I came across this problem. I found it great and plan to use it widely in our application.

Thank you, Iliya Krastinkov.

**Comment by boschni** [comment]
This should be resolved in V3
