### ISSUE TITLE
QueryClient.setQueryData does not use custom queryKeyHashFn

### ISSUE THREAD

**Issue by schottra** [tannerlinsley/react-query#1343]
**Describe the bug**
When initializing `queryClient` with a custom hash function via `defaultOptions.queries.querykeyHashFn`, subsequent calls to `queryClient.setQueryData` do not use the custom hash function to generate a query hash. This results in a mismatch of query keys when attempting to consume the data.

**To Reproduce**
1. Initialize a queryClient with a custom query hash function. 
2. Use `queryClient.setQueryData` to insert a value for a given QueryKey
3. Use `queryClient.fetchQuery` or `useQuery` with the same query key and `staleTime: Infinity` (or any other value that should result in usage of the cached value without performing a fetch).

**Expected behavior**
The `fetchQuery` or `useQuery` calls should return the cached value, no fetch should occur.

**Actual behavior**
`setQueryData` does not use the custom hash function, resulting in a different query hash being generated. `useQuery` creates a second query object and issues a fetch/calls the `queryFn`.

**Version**
3.2.0-beta.29

[Here's a Codesandbox demonstrating the issue](https://codesandbox.io/s/queryclientsetdata-does-not-use-custom-hash-function-j990w)

**Comment by boschni** [comment]
Hi! Thanks for reporting. Should be fixed in v3.2.0-beta.30

**Comment by schottra** [comment]
Tested and confirmed it works for my use case. Thanks for the quick turnaround!
