### ISSUE TITLE
Examples in CodeSandbox not available

### ISSUE THREAD

**Issue by danactive** [tannerlinsley/react-query#1351]
**Describe the bug**
The [example code snippets](https://react-query.tanstack.com/docs/examples/simple) are not available on CodeSandbox due to Not Found or API rate limit

**To Reproduce**
1. Go to https://react-query.tanstack.com/docs/examples/simple
2. See code snippet error
3. More details available by tapping on Open in CodeSandbox

**Comment by danactive** [comment]
Issue is resolved

**Comment by anthonyhumphreys** [comment]
This seems to have come back as an issue.
