### ISSUE TITLE
Dependent queries clobber query configs

### ISSUE THREAD

**Issue by ccummings** [tannerlinsley/react-query#137]
If you have multiple dependent queries with different configurations, the first query's config will trump any other dependent queries.

In the example below, the value of `projects` will be `{ name: "Wat!?" }` instead of `[]` until it starts fetching.

```jsx
const [ready, setReady] = React.useState(false);
  const { data: user, isLoading: userLoading } = useQuery(
    ready && ["user", { userId: 1 }],
    fetchUser,
    {
      initialData: { name: "Wat!?" }
    }
  );
  const { data: projects, isLoading: projectsLoading } = useQuery(
    user.id && ["projects", { userId: user.id }],
    fetchProjects,
    {
      initialData: []
    }
  );
```
[CodeSandbox](https://codesandbox.io/s/upbeat-stallman-btcxx)

I think this [line](https://github.com/tannerlinsley/react-query/blob/master/src/index.js#L427) is the culprit. Since all dependent queries have a queryHash of `undefined`, they are all stored as instances under a single query.

**Comment by tannerlinsley** [comment]
Wow this is a weird one! I'm not sure how that's happening right now, but I'll take a look. Since they use separate query keys, these two queries should be essentially isolated.

**Comment by tannerlinsley** [comment]
Wait... I think I found a lead.

**Comment by tannerlinsley** [comment]
This likely because until the queryKey resolves, they are both `undefined` which as of today is a valid query key (but shouldn't be).

**Comment by tannerlinsley** [comment]
So the way to fix this issue would be to:
- Make sure queries that have an `undefined` falsey query key don't *use* the query object in any way
- Make double sure in this case that queries are also not setting anything on the query object if they query key is invalid.

**Comment by nikoskleidis** [comment]
@tannerlinsley  Is this similar to this https://github.com/tannerlinsley/react-query/issues/108 ?
The solution to that is not to use the initialData when the key may be a falsey one. Use the default value setting of data instead

**Comment by tannerlinsley** [comment]
The temporary solution is to destructure a default value from `data = undefined`, yes.

**Comment by tannerlinsley** [comment]
But only if you're running recent versions (as of this week) where I fixed the default value of `data` to be `undefined` instead of `null`

**Comment by tannerlinsley** [comment]
I feel like this is going to remain the case for 0.x, since a change here would technically be breaking. This is fixed the `next` branch for v1.

**Comment by russellcrl** [comment]
Hello, I do not see this query key behavior documented anywhere. Can we count on this to work? This is nice for dependent queries since I don't end up with dead query keys.

`useQuery(
    ready && ["user", { userId: 1 }],`

One thing I have seen is that if ready = null || undefined, then I get an error:

Cannot read properties of null (reading 'context')
Call Stack
 useBaseQuery
....

**Comment by russellcrl** [comment]
> falsy query keys aren't a thing for at least 2 years now. You're commenting on an old issue from 2020.

I was kinda hoping they were still a thing. If my query key is made up of the previous query (say an id that is returned from a earlier query), I see query keys with id = undefined showing up in the cache when the query is disabled. Is there a way to prevent that from occuring? I've resorted to manually removing the old key when the query is enabled.
