### ISSUE TITLE
[V3]: SSR with NextJs - undefined cannot be serialized as JSON

### ISSUE THREAD

**Issue by tatchi** [tannerlinsley/react-query#1370]
Hey, 

I've been trying to update a NextJs repo which uses hydration to V3 and got the following error:

![image](https://user-images.githubusercontent.com/5595092/101520449-ce078e00-3984-11eb-94f0-ebf5bd837367.png)

Quickly looking at the code and there's indeed a `fetchMeta` state property set by default to `undefined`.

https://github.com/tannerlinsley/react-query/blob/4d01e1fd543d304d2b07defcd4cda55e089db88b/src/core/query.ts#L442

**Comment by boschni** [comment]
This seems NextJS specific as usually `undefined` will just be dropped when serializing to JSON:
```js
JSON.stringify({ prop: undefined })
// {}
```

**Comment by tannerlinsley** [comment]
Yeah, it must be next specific. I ran into it yesterday nonetheless. Not a big deal though.

**Comment by khoale9098** [comment]
Now version 3.21 but I still have to use JSON.stringify to solve the above problem.
