### ISSUE TITLE
Typo in "Migrating to React Query 3"

### ISSUE THREAD

**Issue by flextremedev** [tannerlinsley/react-query#1378]
I've found a typo at https://react-query-beta.tanstack.com/guides/migrating-to-react-query-3#makequerycache.
It says: 
> The makeQueryCache() function has replaced by new QueryCache().

but I guess it's supposed to be:
> The makeQueryCache() function has been replaced by new QueryCache().

I can create a PR if you want me to correct it.

**Comment by TkDodo** [comment]
Yes, please create a PR. There are some other small things in the v3 docs as well, maybe you can tackle them, too? For example, there are some closing backticks missing here: https://react-query-beta.tanstack.com/guides/queries

![Screenshot 2020-12-09 at 19 55 41](https://user-images.githubusercontent.com/1021430/101674264-923df880-3a58-11eb-96d7-99dc8ba501a2.png)

**Comment by flextremedev** [comment]
Sure, I'll take care of it tomorrow :)
