### ISSUE TITLE
[v3] isFetched has different behavior than in v2

### ISSUE THREAD

**Issue by gigobyte** [tannerlinsley/react-query#1383]
**Describe the bug**
I'm not sure if this is an intended change, but `isFetched` is no longer true for queries that resolve with an error. Looking at the [v2 source code](https://github.com/tannerlinsley/react-query/blob/master/src/core/query.ts#L700), `isFetched` is based on `updateCount` and that got incremented even if the result is an error. In v3 that's no longer the case and it depends on `dataUpdateCount` instead.

What is the recommended way to check if a request has finished? `isSuccess || isError` does the job, but my guess is that most people looking through the properties will immediately pick `isFetched` which will catch them off guard.

**Comment by boschni** [comment]
Hi @gigobyte! Thanks for reporting, this seems like a bug. The `isFetched` property should also check `errorUpdateCount`.

**Comment by boschni** [comment]
Fixed in `3.2.0-beta.38 `
