### ISSUE TITLE
Stale Query Triggers Rerender

### ISSUE THREAD

**Issue by zwagner86** [tannerlinsley/react-query#1384]
**Describe the bug**
With a `staleTime` of more than 0, `useQuery` re-renders a component when the `staleTime` is hit, even if no data has changed.

Note:  Using the new flag `notifyOnStatusChange` does not prevent a stale query from re-rendering the component when the same data is returned from cache.

Note:  This issue does not appear to exist when `staleTime` is 0.  You can update `staleTime` in the code sandbox below to confirm.

**To Reproduce**
Here is a code sandbox showing the issue. https://codesandbox.io/s/restless-violet-t0sn1?file=/src/index.js

It is a fork of the Simple example from your documentation.

There are two initial renders (for fetch and success) and then once more when the query becomes stale and re-fetches.

**Expected behavior**
A component does not rerender unless the re-fetched data is different or an error has occurred.

**Comment by tannerlinsley** [comment]
Have you tried with v3?

**Comment by boschni** [comment]
In v3 you will have more granular control: https://react-query-beta.tanstack.com/guides/migrating-to-react-query-3#queryoptionsnotifyonstatuschange

**Comment by tannerlinsley** [comment]
V3 is released!

**Comment by htang014** [comment]
I am seeing similar issues using react-query on react-native. Using v3.34.12.
When running the following app in a barebones react-native setup, the console will print "app unmounted" once on load and again after 10 seconds.
```
const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      retry: false,
      staleTime: 10000,
    },
  },
});

const Wrapper = (Component) => (props) => (
  <QueryClientProvider client={queryClient}>
    <Component {...props} />
  </QueryClientProvider>
);

const App = () => {
  useEffect(() => () => console.log('app unmounted'));
  useQuery('FOO', () => Promise.resolve('bar'));
  return null;
};

export default Wrapper(App);
```
