### ISSUE TITLE
How to get data if i'm using two mutate functions in a component?(Reopen with  more info)

### ISSUE THREAD

**Issue by sainhimanshu9** [tannerlinsley/react-query#139]
I am using hooks only.
I'm using useEffect with empty array to act like componentDidMount.

`const` [mutate, { isLoading, data, error }] = useMutation(handleApi);
mutate({method: "get",endpoint: apiEndpoint,data: {}});`
handleApi is a centralized api call function where i just need to pass request type, endpoint url and data, now...i've a component which makes an api call(1) using componentDIdMount(using useffect) which renders a certain number of list and that list contains a button which also makes an api call(2)...Now as i'm using mutate, i expect it to use data, isLoading, error like above. i've used mutate with both the api calls with different request type and endpoint url, but as above mentioned (data, error, isloading) how to get the (data,error,isloading) for first api call and second one.

**Comment by tannerlinsley** [comment]
I'm still not sure what you mean. Could you please create a codesandbox example or a paste a code snippet from your project?
