### ISSUE TITLE
SSR?

### ISSUE THREAD

**Issue by lcswillems** [tannerlinsley/react-query#14]
Hi,

This package looks really great!
Does it support SSR (Server Side Rendering) like Apollo? Apollo is able to find all the requests in the view and fetch them server side.

Thank you for your work,
Lucas Willems

**Comment by tannerlinsley** [comment]
It will support pre-cache warming for SSR soon. Not until after react SSR supports async export and suspense will it be native.

Tanner Linsley

**Comment by lcswillems** [comment]
Thank you for your answer!

If you have some time,
- Could you give me a link about "react SSR and async support"? What is this? A search gave me nothing.
- Why do you want to wait for Suspense? The SWR team also wait for it, but I don't see the link between your package or SWR and Suspense.

**Comment by tannerlinsley** [comment]
SSR and suspense are not the same thing. To support suspense in an SSR m environment, the render to string methods of react Dom must be asynchronous. These features are on the roadmap for the react core team and hopefully will be released later this year.
Until then, we can get around this by using pre-cache warming to ensure that there is data synchronously available in a query before you use the render to string SSR method

Tanner Linsley

**Comment by tannerlinsley** [comment]
I am driving in my car right now, else I would give you a link to the roadmap

Tanner Linsley

**Comment by lacaux-gerome** [comment]
[This explanation](https://github.com/overlookmotel/react-async-ssr#hydrating-the-render-on-client-side) helped me to have a better understanding of what's behind `the render to string methods of react Dom must be asynchronous`, hope it helps

**Comment by lcswillems** [comment]
Thank you for the link!! This is very clear

**Comment by tannerlinsley** [comment]
- Pre-Seeding a Query will be available in the next major version
- Prefetching and thus "Render While Fetching" Suspense will also be possible in the next release
