### ISSUE TITLE
ReferenceError: regeneratorRuntime is not defined for basic and auto-refetching examples.

### ISSUE THREAD

**Issue by oyalhi** [tannerlinsley/react-query#140]
For `auto-refetching` and `basic` examples, I go to the example folder, `yarn` then `yarn dev` as the readme suggests; however, I get the following error:

`ReferenceError: regeneratorRuntime is not defined.`

Is there anything else I should be doing?

**Comment by tannerlinsley** [comment]
As of the latest version, regeneratorRuntime isn't used. Can you recheck that this error is still happening with the latest version?

**Comment by oyalhi** [comment]
I am using the example just as downloaded from your repo. It didn't work. I had to add 'react' and 'react-dom'. Then I do 'yarn dev'. I get the regeneratorRuntime error.

This is the `package.json` (`react` and `react-dom` added by me):

```
{
  "name": "basic",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "isomorphic-unfetch": "3.0.0",
    "next": "9.2.2",
    "react": "^16.12.0",
    "react-dom": "^16.12.0",
    "react-query": "latest"
  },
  "scripts": {
    "dev": "next",
    "start": "next start",
    "build": "next build"
  }
}
```

**Comment by tannerlinsley** [comment]
Hmmm strange. I’m not seeing that. But I’ll definitely look into this ASAP

**Comment by eliamartani** [comment]
Same error here.

Fixed by adding at `package.json`:

- react
- react-dom

and updating `next` to `9.2.2`

If it helps I could PR it

**Comment by sbreiler** [comment]
Hi, i got the same error today. I even upgraded react-query to the latest version (3.13.0), but it didn't helped.

To fix this error, i added `@babel/plugin-transform-runtime`
```
yarn add -D @babel/plugin-transform-runtime
```

And added the plugin to my `babel.config.js` (`.babelrc` will also work):
```javascript
module.exports = {
    plugins: ['@babel/plugin-transform-runtime'],
    presets: ['@babel/preset-env', '@babel/preset-react'],
}
```
