### ISSUE TITLE
[docs]: search not working

### ISSUE THREAD

**Issue by TkDodo** [tannerlinsley/react-query#1404]
**Describe the bug**

Since the v3 release, every search in the docs leads to this page for me:
![Screenshot 2020-12-14 at 17 05 53](https://user-images.githubusercontent.com/1021430/102104683-c5083800-3e2e-11eb-97b3-84671f65c7ef.png)

This has also been reported in the Tanstack Discord.

**To Reproduce**
1. Go to https://react-query.tanstack.com/
2. Type something in the search (e.g. useQuery) and select the found entry

**Expected behavior**
Search should work

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - Browser: Chrome
 - Version: 87

**Comment by tannerlinsley** [comment]
Algolia docsearch can take up to 24 hours to reindex.

**Comment by TkDodo** [comment]
K, I’ll check back in a couple of days. Have to say now that I’m thinking about it, i also saw this behavior on the beta docs previously but didn’t think much about it 🤔

**Comment by tannerlinsley** [comment]
Yeah it only indexes the master branch.

**Comment by TkDodo** [comment]
@tannerlinsley it's been a couple of days but I'm still getting:

> Snap! We couldn't find that page.

for most of the searches (e.g. `useQuery`)

Just wanted to make sure that there is nothing we can do, because ppl keep reporting this issue as well :)

**Comment by tannerlinsley** [comment]
Hmmm. Looks like we needed to submit some changes to algolia docsearch. We're just waiting on them now:

https://github.com/algolia/docsearch-configs/pull/3059
