### ISSUE TITLE
Devtools type definition regression

### ISSUE THREAD

**Issue by agos** [tannerlinsley/react-query#1406]
**Describe the bug**

as of v3.2.0, the type definitions for the ReactQueryDevtools component are as follows:

```typescript
export declare function ReactQueryDevtools({ initialIsOpen, panelProps, closeButtonProps, toggleButtonProps, position, containerElement: Container, }: {
    initialIsOpen: any;
    panelProps?: {} | undefined;
    closeButtonProps?: {} | undefined;
    toggleButtonProps?: {} | undefined;
    position?: string | undefined;
    containerElement?: string | undefined;
}): JSX.Element;
```

this is a regression from the [previous definitions](https://github.com/tannerlinsley/react-query-devtools/blob/master/index.d.ts), which were much more useful (and full of documentation, too)

**To Reproduce**
1. Open `node_modules/react-query/types/devtools/devtools.d.ts`

**Expected behavior**
Something like the old definitions

**Comment by tannerlinsley** [comment]
The types are now actually generated from the code. I’ll definitely merge a PR to bring back the annotations from the manual type def file from before.
