### ISSUE TITLE
query not refetched

### ISSUE THREAD

**Issue by Pat1420** [tannerlinsley/react-query#141]
Hi,

I have a component with one query to get the list of customers from firestore (loaded into a material table) and a few mutations to manage edit, delete.. 
Once performing the delete operation i tried many options to force the query refetch (list) in the usemutation  in order to have an up to date list
tried 

`const { data, isLoading, isFetching } = useQuery("list", ListCustomers);`

`
const [mutateDelete] = useMutation(DeleteCustomer, {
    refetchQueries: "list"
  });` 
edit tried
`
 const [mutateDelete] = useMutation(DeleteCustomer, {
    refetchQueries: ["list"]
  });
`
+ also tried waitForRefetchQueries: true option 
+ tried refetchQuery, refetchQueries,
and the list never get updated except sometime after a while....
The only moment when the list is updated immediately is when using the isFetching flag on the table (but this cause another effect when the table fetch on click event). This is not coming from the material table component as looking in the DevTools coponent the query data is not updated...

Finally had to remove the useQuery and now i use a simple useEffect with a listener working very well.

**Comment by cherniavskii** [comment]
`refetchQueries` accepts an **array** of queries. Does this fix your issue?

**Comment by Pat1420** [comment]
> `refetchQueries` accepts an **array** of queries. Does this fix your issue?

no i tried... in fact i tried so many options.. also with the force option

**Comment by cherniavskii** [comment]
Then simple example in codesandbox would really help to investigate

**Comment by cherniavskii** [comment]
Here's a working example:
https://codesandbox.io/s/unruffled-blackburn-ltd0l

**Comment by Pat1420** [comment]
> Here's a working example:
> https://codesandbox.io/s/unruffled-blackburn-ltd0l

Yes very similar in logic but i do not have the same result with the db.

**Comment by tannerlinsley** [comment]
As far as the codesandbox implementation goes, @cherniavskii is correct and it's working how it's expected to. Feel free to open another issue with more information or even better a codesandbox showing the issue. Thanks!
