### ISSUE TITLE
infiniteQuery continues to refetch data even  if there are no more observers

### ISSUE THREAD

**Issue by Khufu-I** [tannerlinsley/react-query#1412]
**Describe the bug**
`infiniteQuery` continues to iterate and fetch all pages even after there are no more observers to consume the data. If the `infiniteQuery` contains a large set of pages (i.e. 100) this causes unnecessary network load and keeps references to variables for a long time. 

**To Reproduce**
Open sample in [CodeSandbox](https://codesandbox.io/s/infinitequery-background-g7iye?file=/src/index.js)
1. Allow all pages to finish loading (up to 15 pages).
2. Open Console tab (bottom right) in CodeSandbox or browser console
3. Sample app will print *Fetched page* every time an API call is simulated
4. Click on **Toggle** button to unmount the component which calls `useInfiniteQuery`
5. Notice even though there are no more observers which consume the **components** query the `infiniteQuery` continues to fetch pages in the background.

**Expected behavior**
After all observers (i.e. React components) which consume an infiniteQuery go out of scope the infiniteQuery should stop fetching subsequent pages.

**Screenshots**
<img width="1425" alt="Screen Shot 2020-12-14 at 13 52 00" src="https://user-images.githubusercontent.com/8534262/102122529-94ff6b80-3e13-11eb-9091-607c3d47f1a7.png">

**Desktop (please complete the following information):**
 - OS: all
 - Browser: all
 - Version: all

**Smartphone (please complete the following information):**
 - Device: all
 - OS: all
 - Browser: all
 - Version: all

**Additional context**
Possible [code that controls this behaviour](https://github.com/tannerlinsley/react-query/blob/3c1d2f0e7707dc9deafb6be3273f4dbf87906fcc/src/core/infiniteQueryBehavior.ts#L94)

**Comment by jayakusumah** [comment]
same issue, I'm using nextjs and following the example

**Comment by GermaVinsmoke** [comment]
Gave a `staleTime` of `1000 * 60 * 60` but then also it's fetching

**Comment by FMCorz** [comment]
Same issue.

**Comment by Khufu-I** [comment]
@boschni Thank you for addressing this issue. I noticed that with the latest update the [CodeSandbox sample](https://codesandbox.io/s/infinitequery-background-382-zpfwo?file=/src/index.js) shows an error after the infinite query is cancelled and the React component is rendered again.
Please let me know if I've to change my code to consume the new changes.
