### ISSUE TITLE
View V2 Docs which are currently 404'ing

### ISSUE THREAD

**Issue by the133448** [tannerlinsley/react-query#1420]
It's great V3 is out, but unfournately for my team we will be unable to upgrade for the foreseeable future due to the breaking changes. How can I continute to view V2 docs? It seems the search is yet to update...
For example searching for `setQueryData`
![image](https://user-images.githubusercontent.com/7479387/102154130-7c9b5980-3ec4-11eb-807d-3913a92e3046.png)
takes me to a 404 not found page.
![image](https://user-images.githubusercontent.com/7479387/102154169-8f159300-3ec4-11eb-8e05-f6a2c43200e9.png)

So, how can I view this page?

**Comment by tannerlinsley** [comment]
The official link is https://react-query-v2.TanStack.com

Search unfortunately will not work until algolia docsearch supports multiple subdomains .

**Comment by the133448** [comment]
Could I recommend you include that link somewhere on the new docs? 
Also, that doesn't seem to be correct, unless v2 had queryClient on: https://react-query-v2.tanstack.com/guides/optimistic-updates
I'm fairly sure those are v3 docs

**Comment by TkDodo** [comment]
> I'm fairly sure those are v3 docs

you are right, it's definitely the v3 docs, e.g.

https://react-query-v2.tanstack.com/guides/migrating-to-react-query-3

😅

**Comment by tannerlinsley** [comment]
Looks like the deployments were broken. They are now fixed though!
