### ISSUE TITLE
queryClient.invalidateQueries not working when accessing a react-router page directly

### ISSUE THREAD

**Issue by spencerfeng** [tannerlinsley/react-query#1425]
**Describe the bug**
I have a page whose URL is like this: http://domain/products/{:productId}. Let me call this page 'Product Details' page for reference later on.

This page can be accessed in 2 ways: 

1. clicking a product item in the products list on this page: http://domain/products with the help of react-router
2. access it directly by pasting this url in browser: http://domain/products/{:productId}

In 'Product Details' page, I use useQuery with a query called 'productIssues' to retrieve all issues that are related to this product when this page is loaded. In the same page, I have also had a function to allow the user to add an issue for this product. This function is implemented with react-query useMutation hook. In its onSuccess block, I call queryClient.invalidateQueries('productIssues'), so that all issues will be refetched which includes the newly added issue.

However, issues are not refetched if the 'Product Details' page was accessed directly by using its url in the browser. On the other hand, issues are refetched if the 'Product Details' page was accessed by react-router from 'Products List' page.

**To Reproduce**
This app is currently behind a company VPN and can not be accessed by the public

**Expected behavior**
I expect the 'productIssues' query will be refetched after queryClient.invalidateQueries('productIssues') is called if the 'Product Details' page was accessed by pasting its url directly in the browser.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [macOS 10.15.7]
 - Browser: [chrome]
 - Version: [87]

**Smartphone (please complete the following information):**
 - Browser: [e.g. stock browser, safari]
 - Version: [e.g. 22]

**Additional context**

**Comment by TkDodo** [comment]
> This app is currently behind a company VPN and can not be accessed by the public

Can you please create a codesandbox that reproduces the behavior? Are you maybe using some staleTime, because invalidateQueries respects that I believe

**Comment by tannerlinsley** [comment]
Yes, we'll need more information that what is currently here. A codesandbox repro or even a link to the source code. Please open a new issue with those details and we can take a look :)
