### ISSUE TITLE
(v3) Prefetching infinite query does not return expected structure

### ISSUE THREAD

**Issue by danbeneventano** [tannerlinsley/react-query#1426]
When I use `queryClient.prefetchQuery` with a `getNextPageParam` method in `options`, the returned data looks like this:
```
{
  page: 0,
  nextPage: 1,
  posts: [...]
}
```

However, the expected data should look like this:
```
{
   pages: [
    {
      page: 0,
      nextPage: 1,
      posts: [...]
    },
  pageParams: ...
    ...
  ]
}
```

The above response is what `useInfiniteQuery` normally returns. `queryClient.prefetchQuery` should return the same response when a `getNextPageParam` method is provided.

**Comment by boschni** [comment]
Hi @danbeneventano! Currently there is no support for prefetching infinite queries. It is possible though, but separate methods will be needed like `fetchInfiniteQuery` and `prefetchInfiniteQuery` to make sure the queries are handled as infinite queries and to make sure all typings are correct.

**Comment by danbeneventano** [comment]
@boschni Thanks for the response, addition of this functionality would be great so we can take advantage of Next.js SSR.
