### ISSUE TITLE
queryClient.prefetchQuery doesn't cache the data even though response is returned from API call

### ISSUE THREAD

**Issue by vipinnair22** [tannerlinsley/react-query#1429]
**Describe the bug**
I'm implementing pagination using `useQuery` and `prefetchQuery` (to prefetch the next page data). But it seems like it's not caching the response data for the prefetch call.

I tried 2 ways to verify the data for the prefetch call and both show undefined.
1. `queryClient.getQueryData(key)` \\key is the key used for prefetch.
2. Plus, dev tools show there's no data as well for this combination of key even though network trace shows that response was returned as expected for prefetch call.
![image](https://user-images.githubusercontent.com/11910619/102192797-1ab10480-3e70-11eb-9c29-8b2ddc07c773.png)

Code is along the same lines as the pagination example.

**Expectation:** Prefetch should cache the data and be visible in dev tools. This cached data should be returned the next time `useQuery` is called with the same key.

**Comment by TkDodo** [comment]
> Code is along the same lines as the pagination example.

The pagination example in the docs does exactly that, so I'm quite sure this is working. Can you narrow down what you are doing differently? Happy to take a look at a codesandbox example that reproduces your described behaviour

**Comment by vipinnair22** [comment]
> > Code is along the same lines as the pagination example.
> 
> The pagination example in the docs does exactly that, so I'm quite sure this is working. Can you narrow down what you are doing differently? Happy to take a look at a codesandbox example that reproduces your described behaviour

This piece of code is in a hook that's used as part of a larger code structure. So, it's difficult to extract the flow to codesandbox. I'll try to do it. 
But would you happen to know why the data is empty even though the prefetch call returned a response? Under what circumstances would this happen?

**Comment by TkDodo** [comment]
> But would you happen to know why the data is empty even though the prefetch call returned a response? Under what circumstances would this happen?

I have not seen this happening yet, sorry.

**Comment by TkDodo** [comment]
if your prefetch does `Promise.resolve(undefined)` you might get that .. ?

**Comment by tannerlinsley** [comment]
We're going to need much more info to diagnose this issue properly. A codesandbox or even a link to some source code would be great. Please open a new issue with that info and we'll go from there.

**Comment by rajatdhoot123** [comment]
The same issue is happening to me

**Comment by vipinnair22** [comment]
> The same issue is happening to me

My issue was that I was missing "return" in the callback for the API call. Silly mistake!
