### ISSUE TITLE
docs: csb examples don't load in firefox

### ISSUE THREAD

**Issue by stefanprobst** [tannerlinsley/react-query#1433]
**Describe the bug**

The docs include a section with Examples in CodeSandboxes. These load fine in Chrome, but show a blank square in Firefox.

**To Reproduce**
1. Go to https://react-query.tanstack.com/examples/simple in Firefox
2. See blank square.

**Expected behavior**
Be able to view examples in firefox.

**Screenshots**
![ff](https://user-images.githubusercontent.com/20753323/102214441-8fb82480-3ed8-11eb-9a87-bb8c5b5b3af5.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Firefox 83

**Additional context**

**Comment by TkDodo** [comment]
I can confirm that it works for me, macOS Catalina, Firefox 83.0b3

Have you tried to "Open in CodeSandbox" link?

**Comment by stefanprobst** [comment]
thanks, for the quick response! this is indeed an upstream issue: https://github.com/codesandbox/codesandbox-client/issues/2726
