### ISSUE TITLE
Unexpected rerender order

### ISSUE THREAD

**Issue by pierreferry** [tannerlinsley/react-query#1436]
**Describe the bug**
When dealing with nested usage of the same query, the deepest query is updated first. In v2 this was the other way around.

**To Reproduce**
I made a codesandbox forked from react-query basic example.
I added a "next" link, at the right of the "back" link.
I added a PostTitle component which uses usePost(id).
https://codesandbox.io/s/inspiring-easley-z6lo9?file=/src/index.js

1. Click on any post link
2. Look at logs
3. Click on the "next" link
4. Look at logs
5. See that the current title gets logged one more time before the new title gets logged.

**Expected behavior**
I expect that after clicking on "next" link, the `Post` component has it status to loading and thus `PostTitle` component is not rendered. Pls see this sandbox to see v2 behavior with logs https://codesandbox.io/s/admiring-solomon-oi8hz?file=/src/index.js
In v2 the parent was re-render first. It was handy to handle the "loading" state of a given section. Now i have to deal with `undefined` value everywhere in my subcomponent.

**Additional context**
This change has huge impact on my codebase and is not documented in the migration from v2 to v3. Is this intended ?
I understand that I might be doing something wrong, thank for any explanations you could give me 🙏

**Comment by tannerlinsley** [comment]
This is fixed in the latest release :)
