### ISSUE TITLE
useQuery bug in ios safari

### ISSUE THREAD

**Issue by vrg-success** [tannerlinsley/react-query#1438]
**Describe the bug**
Incorrect status for query only in ios system, if I will back to "home" page from "Client-Only" I will get every times idle status for todos query

**To Reproduce**
Youtube video: https://youtu.be/clulorszrnM
Ready sandbox with issue: https://codesandbox.io/s/keen-shockley-hx6h7?file=/pages/index.js
Ready sandbox: link to see preview in phone https://hx6h7.sse.codesandbox.io/client-only

**Expected behavior**
idle 
loading 
success

**Smartphone (please complete the following information):**
 - Device: [iPhone12]
 - OS: [ios]
 - Browser: [safari]
 - Version: [v12]

I spend to many times for project, and I finally deployed but I got surprise about the thing, I want to die because I try to many times resolve the problem but it's unsuccessfully... I ready provide access to browser-stack for reproduce if you don't have option

**Comment by vrg-success** [comment]
@tannerlinsley Is the problem?! https://github.com/tannerlinsley/react-query/commit/6e7de8f77600607031ce67631974632f4ca8554b

**Comment by TkDodo** [comment]
Not sure what this has todo with iOS only.. in think your query might be `idle` because you set it to `{ enabled: false }`. If you only want to fetch once, I would suggest setting ` staleTime: Infinity` on the query.

**Comment by vrg-success** [comment]
Please read more my issue and try reproduce in ios

**Comment by tannerlinsley** [comment]
I wan't able to reproduce this bug in the iOS simulator. What I would suggest is updating the example to use 3.2.0 and see where that gets us.

**Comment by vrg-success** [comment]
In last version all ok, I think that fixed in the commit 6e7de8f

**Comment by AnisMobile99** [comment]
hey ,

you found the solution ?
