### ISSUE TITLE
setQueryData documentation not available

### ISSUE THREAD

**Issue by zacharypodbela** [tannerlinsley/react-query#1446]
**Describe the bug**
There is no documentation for `setQueryData`

**To Reproduce**
1. Go to https://react-query.tanstack.com/
2. Type "setQueryData" in search bar
3. Click first item
4. See page that says "Oh snap!"

**Expected behavior**
I need documentation on how this function works. I'm having problems with the data I save being marked stale.

**Screenshots**
![Screen Shot 2020-12-15 at 3 29 52 PM](https://user-images.githubusercontent.com/8572738/102269320-761fd880-3eea-11eb-9f80-92e28b9e7dbf.png)

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Chrome

**Comment by tannerlinsley** [comment]
This is because algolia has not finished reindexing the new v3 documentation. Should be resolved in the next 24 hours.

**Comment by zacharypodbela** [comment]
@tannerlinsley does this mean the v2 documentation is going to no longer be available with the release of v3? My team wont be able to slot an upgrade for a few weeks so would be really helpful to have continued access to the old docs.

**Comment by tannerlinsley** [comment]
I will contact algolia asap about it and see what can be done 👍

**Comment by zacharypodbela** [comment]
Thank you!! 💯
