### ISSUE TITLE
Caching Not Working for my implementation - Issue

### ISSUE THREAD

**Issue by stephanoparaskeva** [tannerlinsley/react-query#1447]
### *Description*:
My queries are running multiple times instead of once. The result is never cached:

AND each query results in 2 API requests, which is even worse.

---

### axiosWrap (helper function):
```ts
export const axiosWrap = async (
  requestConfig: (userId?: string) => AxiosRequestConfig
) => {
  const token = await AsyncStorage.getItem(STORED_JWT_TOKEN);
  const { sub: userId } = jwt_decode<{ sub: string }>(token || '');
  const params = requestConfig(userId);

  const attemptRequest = () =>
    axios({
      ...params,
      headers: { ...params.headers, Authorization: `Bearer ${token}` },
    });

  try {
    const response = await attemptRequest();
    return response;
  } catch (err) {
    logError(params)(err);
    if (err?.response?.data?.status !== 544) {
      throw err;
    }

    try {
      const { username, password } = (await Keychain.getGenericPassword()) || {};
      await loginReq({ email: username, password });
      return attemptRequest();
    } catch (e) {
      await Keychain.resetGenericPassword();
      await AsyncStorage.removeItem(STORED_JWT_TOKEN);
      throw e;
    }
  }
};
```

### getProfileReq:
```ts
export const getProfileReq = () => {
  console.warn('getProfileReq runs');
  return axiosWrap(userId => ({
    method: 'get',
    url: `${API_URL}/users/${userId}`,
  })).then(res => res.data);
};
```

### Component A (example): 
```ts
const Foo = () => {
  useQuery('profile.query', getProfileReq);
  return (<>Baz</>)
}
```

### Component B (example): 
```ts
const Bar = () => {
  const { data: user } = useQuery<any>('profile.query', getProfileReq, {
    initialData: { roles: [], experiences: [] },
  });
 return (<>Baz</>)
}
```

## Console:

<img width="1172" alt="Screenshot 2020-12-15 at 22 52 37" src="https://user-images.githubusercontent.com/40718272/102282272-40014980-3f28-11eb-9125-1109c94e363d.png">

> getProfileReq runs
> { context: {...}, error: {...} }                    // <-------------- Indicates an API request (comes from logError in axiosWrap)
> { context: {...}, error: {...} }                    // <-------------- Indicates a second API request 
> getProfileReq runs
> { context: {...}, error: {...} }                    // <-------------- Indicates an API request (comes from logError in axiosWrap)
> { context: {...}, error: {...} }                    // <-------------- Indicates a second API request 
> getProfileReq runs
> { context: {...}, error: {...} }                    // <-------------- Indicates an API request (comes from logError in axiosWrap)
> { context: {...}, error: {...} }                    // <-------------- Indicates a second API request

**Comment by tannerlinsley** [comment]
Is there any way we could get this setup into a codesandbox to play around with?

**Comment by stephanoparaskeva** [comment]
> Is there any way we could get this setup into a codesandbox to play around with?

I don't think I know how to isolate this one, because my components have. Complicated logic too. Is there anything you notice that's bad with the implementation described?

**Comment by TkDodo** [comment]
> I don't think I know how to isolate this one, because my components have. Complicated logic too.

This is exactly the reason why a minimal reproducible codesandbox example is needed please. A lot of the time, the complicated logic around the actual query is the culprit, making it not reproducible in a codesandbox. If that's the case, then there is little we can do.

> Is there anything you notice that's bad with the implementation described?

What I think I am seeing in the above screenshot is react-query making 3 retries to a failed query that returns `404`, and after that it fails with `404` (=goes to error state), which would maybe explain why you have no result. But that would be a "too easy" explanation imo, but I'm afraid I can't tell much more without the reproduction.

**Comment by tannerlinsley** [comment]
That would be my guess too, but without a reproduction or a look into the source code, we can't know for sure. Feel free to comment with more info and we'll take it from there.
