### ISSUE TITLE
Devtools included in production bundle on v3.2

### ISSUE THREAD

**Issue by Belco90** [tannerlinsley/react-query#1451]
**Describe the bug**
When building any app on production mode, RQ Devtools from RQ v3 should be excluded from the final bundle but it's still there.

**To Reproduce**
You can check that on [this Octoclairvoyant app](https://octoclairvoyant.vercel.app/) I updated with RQ v3 (you can see RQ init [here](https://github.com/Belco90/octoclairvoyant/blob/main/src/pages/_app.tsx)). It should be reproducible also just building any React app using RQ v3 on production mode.

**Expected behavior**
Devtools is striped from the final bundle.

**Screenshots**
![image](https://user-images.githubusercontent.com/2677072/102335132-cd2bb900-3f8f-11eb-9728-16b9ed567b76.png)

**Comment by TkDodo** [comment]
see: https://github.com/tannerlinsley/react-query/discussions/1415

**Comment by TkDodo** [comment]
this is the fix: https://github.com/tannerlinsley/react-query/commit/5e4ef153de642551d554047ce99124bfb58e254e

but it has not been released yet
