### ISSUE TITLE
useInfiniteQuery triggers API calls on click of document.

### ISSUE THREAD

**Issue by abhimanyusingh** [tannerlinsley/react-query#1454]
**Describe the bug**
 With useInfiniteQuery, on click of document it's making an api call.

**To Reproduce**
https://codesandbox.io/s/github/tannerlinsley/react-query/tree/master/examples/load-more-infinite-scroll?from-embed

**Expected behavior**
should not trigger any api call on click of document.

**Screenshots**
![ezgif com-gif-maker](https://user-images.githubusercontent.com/3057450/102350039-4b0cb600-3fca-11eb-9dd9-3ed1a01bbbb0.gif)

**Desktop (please complete the following information):**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Smartphone (please complete the following information):**
 - Browser: [e.g. stock browser, safari]
 - Version: [e.g. 22]

**Additional context**

**Comment by TkDodo** [comment]
looks like `refetchOnWindowFocus` ?

**Comment by tannerlinsley** [comment]
Yep. This is intentional. You can disable it with `refetchOnWindowFocus: false`
