### ISSUE TITLE
Tests are not running on PR

### ISSUE THREAD

**Issue by cherniavskii** [tannerlinsley/react-query#1456]
Hey there 👋

I've noticed, that tests are not running on latest PRs. Is it intentional?
Here's an example PR: https://github.com/tannerlinsley/react-query/pull/1449
And error from GitHub Actions:

![Screenshot 2020-12-16 at 17 49 49](https://user-images.githubusercontent.com/13808724/102379370-19deb680-3fc7-11eb-81c0-2b0876f29d4a.png)

**Comment by tannerlinsley** [comment]
They are now. We had a small typo for a bit.
