### ISSUE TITLE
Can't fetch at same level as QueryClientProvider?

### ISSUE THREAD

**Issue by indefinitelee** [tannerlinsley/react-query#1457]
**Describe the bug**
Modified the example in the documentation to  put all logic inside <App /> 
results in an error 
"No QueryClient set, use QueryClientProvider to set one"

https://codesandbox.io/s/busy-northcutt-uxm37?file=/src/App.js

not sure if this is expected or not but I don't see the behavior documented anywhere.

**Comment by tannerlinsley** [comment]
`useQuery` or basically any other utility that doesn't hang off of the `queryClient` object (like `queryClient.prefetchQuery`), must be used within the provider.

It's not necessarily documented in each hook, but every example and guide should show it as required.

**Comment by indefinitelee** [comment]
Thanks for the quick response - was this the case in V2 as well?

**Comment by tannerlinsley** [comment]
No v2 had a default cache which turned out to be a bad design

Tanner Linsley
