### ISSUE TITLE
No way of setting a "base" unique key for usePaginatedQuery, so that it conditionally lags data

### ISSUE THREAD

**Issue by jacklj** [tannerlinsley/react-query#1459]
**Describe the bug**

Hi, I have a use case where I only want `usePaginatedQuery` to return lagged data some of the time:

 - in the app, we have a separate page for each 'client' entity
 - on each 'client' page you can paginate and search through that client's transactions, so we want lagged transactions data to be displayed while paginating.
 - However, when the user goes to a different client's page, we don't want the previous client's transactions to be displayed while the new client's transactions are being loaded

So we want data to be lagged within a client page, but not between client pages.

I had assumed that `usePaginatedQuery` used the first item in the key list as a unique identifier to 'scope' the pagination, so I tried adding the client's ID to that (it was already in the argument list as the second item) but it didn't work - lagging was still happening between client pages.

So, is there a way to 'scope' `usePaginatedQuery` so that it knows when to lag data and when to treat the query as a separate one?

Thanks!

**Expected behavior**

I expect this to show lagged data whenever the `clientId` or `page` changes:

```javascript
usePaginatedQuery(
    ["transactions", { clientId, page }],
    getTransactions)
```

But I hoped that _this_ wouldn't show lagged data when the `clientId` changes, because  the query key 'root' (first item in the list) changes when the `clientId` changes:

 ```javascript
usePaginatedQuery(
    [`transactions-${clientId}`, { clientId, page }],
    getTransactions)
```

**Desktop (please complete the following information):**
 - OS: MacOS, Windows
 - Browser: all main browsers
 - Version: 2.26.4

**Comment by TkDodo** [comment]
The one thing that comes to mind right now is having a useEffect that runs when the `clientId` changes and removes that entry from the cache, but yeah, this is not a very elegant solution I admit...

**Comment by jacklj** [comment]
Ye I was thinking of something like that, was hoping for something more idiomatic but that will do! Thanks

**Comment by jacklj** [comment]
It would also mean that when the user returns to a previously viewed client, that client's data won't be in the cache, as all data is wiped every time you change the client :/

**Comment by tannerlinsley** [comment]
Hmmm. You know, if you were to use v3 with keepPreviousData, you can actually lag data conditionally like so:

```js
function useDidChange(deps) {
  const depsRef = React.useRef(deps)

  let changed = false

  if (
    depsRef.current.length !== deps.length ||
    deps.some((dep, index) => depsRef.current[index] !== dep)
  ) {
    changed = true
  }

  React.useEffect(() => {
    depsRef.current = deps
  }, [])

  return changed
}

function App() {
  const clientDidChange = useDidChange([clientId])

  const query = useQuery(key, fn, {
    keepPreviousData: !clientDidChange,
  })
}

```

**Comment by tannerlinsley** [comment]
That code is untested, but I've done it before without problems, so let me know if it needs any fixing.

**Comment by jacklj** [comment]
That's great thanks, works like a charm! Small correction to the `useDidChange` hook - the effect that updates the ref value should have `deps` in it's own dependency list:
```

**Comment by tannerlinsley** [comment]
Good catch. I wrote it in the Github comment box... so 🤷‍♂️ 😄

**Comment by tannerlinsley** [comment]
I honestly think that's my goto suggestion now for this issue. I'm going to close it, but it would be awesome to see a PR to document how to build that utility where you think it would be most useful.
