### ISSUE TITLE
How to replicate waitForRefetchQueries in @next

### ISSUE THREAD

**Issue by ConneXNL** [tannerlinsley/react-query#146]
Hey,

Trying to migrate from the 0.* to upcoming 1.* in @next.

Couldn't find anything on 'waitForRefetchQueries' in the changelog. How to replicate this in @next?
It seems that `status` of useMutation is already `success` (instead of still `loading`) before the onSuccess (that uses `await`) is finished.

@master first does the queries you want to wait for, then sets loading to false:
https://github.com/tannerlinsley/react-query/blob/master/src/index.js#L674-L681

@next dispatches onSuccess after the dispatch sets status to success:
https://github.com/tannerlinsley/react-query/blob/next/src/useMutation.js#L82-L84

My use-cases:
1) I want a "Add user" button to be disabled until the user is added AND the user list beneath is refetched.
2) I want a "Remove user" button in a list to be removed and the list be updated,  before a re-render.

**Comment by tannerlinsley** [comment]
Okay, I just pushed a fix for this in next. So now, instead of this:

```js
useMutation(func, {
  onSuccess: () => {
    queryCache.refetchQueries('...')
  }
}
```

You can do this:

```js
useMutation(func, {
  onSuccess: () => queryCache.refetchQueries('...')
}
```

And the `status === 'success'` state AND `mutate` promise will wait for your onSuccess function to resolve.
