### ISSUE TITLE
Devtools not mark current query in Queries for queryClient.fetchQuery

### ISSUE THREAD

**Issue by loba-b** [tannerlinsley/react-query#1466]
**Describe the bug**
I think I found problem when I'm using queryClient.fetchQuery instead useQuery. Devtools don't mark right query.

**To Reproduce**
1. Go to https://codesandbox.io/s/serene-jepsen-j8g9c
2. Click on post
3. In "Queries" right query isn't mark

**Expected behavior**
Right queries should be mark as "stale"

**Screenshots**
![devtools-queries](https://user-images.githubusercontent.com/1701766/102471758-e303b180-4055-11eb-8afe-b078551ece33.png)

**Desktop (please complete the following information):**
Not relevant

**Smartphone (please complete the following information):**
Not relevant

**Additional context**
Not relevant

**Comment by boschni** [comment]
Hi @loba-b! Within components it is definitely recommended to use the `useQuery` hook. This will let React Query know the query is being observed and it'll trigger component updates when needed.

**Comment by tannerlinsley** [comment]
Yep! Just swap out these lines for a `useQuery` instead and you'll be good to go.

https://codesandbox.io/s/hopeful-mcclintock-1pxpk?file=/src/hooks/usePost.js:227-395

**Comment by Dacaramo** [comment]
Hi guys, if using next.js >13 the queries made with `queryClient.fetchQuery()` won't appear on React Query Devtools right? I'm asking because within server components you cannot use `useQuery` or any kind of hook

**Comment by TkDodo** [comment]
the devtools show what's in the client cache. If you fetch on the server and then dehydrate there and hydrate again on the client, it should show up
