### ISSUE TITLE
All parameters given to useQuery become strings @next

### ISSUE THREAD

**Issue by ConneXNL** [tannerlinsley/react-query#147]
Using booleans or numbers in useQuery parameters become strings when they are received by their handlers.

Example:
useQuery(['user', { id: 5, test: false }], handler);

handler receives  `{ id: "5", test: "false" }` instead of `{ id: 5, test: false }` as the second argument.

Lines that are responsible for this (the stringify function) parsing everything to Strings:
https://github.com/tannerlinsley/react-query/blob/next/src/utils.js#L53

Using the stringified `queryKey` instead of `userQueryKey`.
https://github.com/tannerlinsley/react-query/blob/next/src/queryCache.js#L100-L109

**Comment by tannerlinsley** [comment]
Ah ha! Right you are. I'll get that fixed. Thanks.
