### ISSUE TITLE
[v3.3] useQueryErrorResetBoundary: undefined data from useQuery when reseting

### ISSUE THREAD

**Issue by bbenezech** [tannerlinsley/react-query#1471]
Hello @tannerlinsley 

I use latest `ReactQuery` with `suspense`.
I expect (am I wrong?) that data from `useQuery` is never undefined when using `{ suspense: true }`.
This is true all the time, expect when reseting state in `ErrorBoundary`. It happens before any refetch happens.
It used to work (flawlessly) in latest `v2` with the previous reset hook, it looks like a regression. I tried both solution from https://react-query.tanstack.com/guides/suspense , same result.

Can I be in any more help to help you help me ?

```typescript
import React from "react";
import { useQuery as useReactQuery } from "react-query";

const useQuery = <T extends Signature>({
  path,
  key,
  params,
  signature,
  headers,
  enabled = true,
}: P<T>) => {
  const { data, ...debug } = useReactQuery(
    key,
    React.useCallback(() => call({ method: "GET", path, signature, params, headers }), [
      path,
      signature,
      params,
      headers,
    ]),
    {
      suspense: true,
      refetchOnMount: false,
      refetchOnReconnect: false,
      refetchOnWindowFocus: false,
      staleTime: 1000 * 60 * 30, // 30 minutes
      cacheTime: 1000 * 60 * 60, // 60 minutes
      retry: false,
      enabled,
    }
  );

  console.log(debug) // see below

  // throws here
  if (data === undefined) throw new Error("Data not supposed to be undefined with suspense true");

  return data;
};
```

This is the debug context I receive:

```javascript
error: ApplicationError at call (http://localhost:3000/static/js/main.chunk.js:1906:36) at Object.queryFn....
errorUpdatedAt: 1
isError: true
isFetched: true
isFetchedAfterMount: false
isFetching: true
isIdle: false
isLoading: false
isLoadingError: true
isRefetchError: false
isStale: true
isSuccess: false
status: "error"
```

I am the one throwing the `ApplicationError` in the rest fetch adapter below. It happens with `react/react-dom@17` default.

**Comment by TkDodo** [comment]
`data` is undefined because the status is `"error"`. But as far as I'm aware, with suspense, your query should _never_ result in `"error"` state (and you also shouldn't get an error back) because the ErrorBoundary should handle that.

can you maybe create a codesandbox example reproducing the behaviour? Also, can you try out v3.3 (released yesterday)

**Comment by bbenezech** [comment]
Behaviour didn't change with `v3.3` in my project. I also tried with stock React and no concurrent-mode. Same.

Here is the relevant codesandbox from the docs: 

https://codesandbox.io/s/github/tannerlinsley/react-query/tree/master/examples/suspense?file=/src/queries.js

Uncomment the `count++` code, run a fetch, remove the nagging error overlay, press the ErrorBoundary retry button, and boom:

<img width="568" alt="Screenshot 2020-12-18 at 09 54 38" src="https://user-images.githubusercontent.com/26794/102594862-11959100-4117-11eb-9698-0916847dc758.png">

This does look like an unwanted regression.
