### ISSUE TITLE
TypeScript: Incorrect type for data when using select in useQuery

### ISSUE THREAD

**Issue by pfarnach** [tannerlinsley/react-query#1473]
**Describe the bug**
When defining a `select` method, the type for `data` that's returned does not match the selected data's type, and instead reflects the type `data` would be without the selector.

**To Reproduce**
1. See `Posts.tsx` in this [CodeSandbox example](https://codesandbox.io/s/naughty-newton-fv3z0?file=/src/Post.tsx).
2. Notice that the compiler says that `data` is of type `PostData | undefined` and not `string | undefined`.

**Expected behavior**
The type for `data` should reflect what's selected (in this case, `string | undefined`), not what's originally fetched (`PostData | undefined`). It's not clear to me if the correct type can be inferred somehow from the selector, or if we'd need to pass in another generic argument to `useQuery`.

**Desktop (please complete the following information):**
 - OS: macOS 10.14
 - Browser: Chrome 87.0
 - Version: 3.3.0

**Comment by pfarnach** [comment]
...and of course after spending a good chunk of time trying to figure this out before, I immediately figure it out after creating this issue. For anyone else that runs into this, this can be typed properly as-is using the third generic argument. From my example, it'd be
`useQuery<PostData["title"], Error, PostData>(...)`. Apologies for the noise.

**Comment by TkDodo** [comment]
I think the order of the generics might change with this PR: https://github.com/tannerlinsley/react-query/pull/1470

**Comment by pfarnach** [comment]
Good to know, thanks. It seems like that will be a breaking change, is that going in v4?

**Comment by tannerlinsley** [comment]
For React Query we do not consider type-only changes as breaking per-se, since that would by definition make just about every change to the codebase breaking, especially when the type change is a "fix" or "feature" that does not alter the compiled JS API.

**Comment by boschni** [comment]
When you are explicitly defining a generic the other ones are not inferred anymore unfortunately. You can solve it like this though:
```js
const fetchPost = (): Promise<PostData> =>
  fetch("https://jsonplaceholder.typicode.com/todos/1")
    .then((response) => response.json())
    .then((json) => json);

export default function Post() {
  const { data } = useQuery("post", fetchPost, {
    select: (post) => post.title
  });
```
