### ISSUE TITLE
Invocation mutate one by one

### ISSUE THREAD

**Issue by sshmyg** [tannerlinsley/react-query#1479]
**Describe the bug**
Calling same mutate with different arguments, fire `onSuccess` once with last server response.

**To Reproduce**
```
const { mutate } = useMutate()

mutate({a: 1}, {.onSuccess: () => {
    console.log(1)
} });

mutate({a: 2}, {.onSuccess: () => {
    console.log(2)
} })
```

Fires only last one.

**Expected behavior**
onSuccess fire for each mutate call separately  

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: chrome
 - Version: Version 87.0.4280.88 (

**Additional context**
async mutation works as expected.

Maybe it's not a bug it's a feature?

**Comment by boschni** [comment]
Hi @sshmyg! The callbacks are indeed only called for the latest mutation instead of all mutations. I guess there are pros and cons to either approach, but maybe @tannerlinsley can elaborate a bit more.

**Comment by tannerlinsley** [comment]
Honestly, this could be an option in the mutation config in the future, as there are use cases for both sides. But yes, for now, side-effects of the `mutate` function are debounced to the last mutation.
