### ISSUE TITLE
[v3.2 => v3.3 regression] v3.3 breaks concurrent mode

### ISSUE THREAD

**Issue by bbenezech** [tannerlinsley/react-query#1482]
When using `React.unstable_useDeferredValue` to control a value passed down to a component then used as key by `useQuery`, it causes parent component (the one with the deferred hook) to rerender multiple times for no reasons. It mostly goes "crazy". The behaviour stops when removing the `useQuery` call or using `v3.2`.

It's probably because we use a pattern that should trigger an error in React (setting state in render, mutating rev cache, this kind of stuff?) but does not yet because of the unstable/experimental state of React concurrent mode.

The diff is here: https://github.com/tannerlinsley/react-query/compare/v3.2.0...v3.3.0

If we remove tests and doc, diff is quite small (`src/core/query.ts`, `useClient` and `useBaseQuery` mosty).

How can I be of any help ?

**Comment by boschni** [comment]
This commit might be responsible: https://github.com/tannerlinsley/react-query/commit/260ec62983377e82b4d9f0b441764f4f793f68d7 .

Could you create a sandbox to demonstrate the issue?

**Comment by bbenezech** [comment]
Press the +1 and look at the logs : https://codesandbox.io/s/bold-fire-43ry7?file=/src/index.js

Compare with https://codesandbox.io/s/inspiring-night-6ydkq
