### ISSUE TITLE
Mutation retry not working as expected

### ISSUE THREAD

**Issue by Atif252** [tannerlinsley/react-query#1488]
**Describe the bug**
The `status` of the mutation stays `loading` when the mutate function is called with `retry` enabled while the device is offline.

**To Reproduce**

1. Go to https://codesandbox.io/s/gracious-mclaren-yz21u?file=/src/App.js
2. Open dev tools, go to network tab, choose offline from throttling section
3. Click post
4. `status` will remain `loading` instead of changing to `error`

**Expected behavior**
The `status` of the mutation should change to `error` when the mutate function is called with `retry` enabled while the device is offline.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 87.0.4280.88

Additional context
The `status` of mutation function works as expected when used without `retry`

**Comment by boschni** [comment]
Hi @Atif252! The mutations currently behave the same as queries. On each attempt the `failureCount` is incremented, and once all attempts have failed the `status` is set to `error`. There is also an `isPaused` flag to indicate if retrying is paused because the device is offline for example. Does this help you in any way?

**Comment by TkDodo** [comment]
I can confirm that the query will:
- stay in loading state
- have a `failureCount` of 1
- be set to `isPaused`

when trying to do a mutation while being offline. have a look here: https://codesandbox.io/s/bold-khayyam-0xh40?file=/src/App.js

I think this is all "as expected"

**Comment by ibash** [comment]
The retryer stops working if the window is not focused, even if the network comes back online. I've described this more and included a patch here: https://github.com/tannerlinsley/react-query/issues/1819

**Comment by Aung-Myint-Thein** [comment]
> I can confirm that the query will:
> 
> * stay in loading state
> * have a `failureCount` of 1
> * be set to `isPaused`
> 
> when trying to do a mutation while being offline. have a look here: https://codesandbox.io/s/bold-khayyam-0xh40?file=/src/App.js
> 
> I think this is all "as expected"

This is working fine on React but in React Native, `isPaused` is not set to true when the mutation has error because of the network offline. So, currently I am handling Persist Mutation myself using AsyncStorage and onError callback. Is anyone facing the same issue?

**Comment by huynqbibabo** [comment]
> > I can confirm that the query will:
> > 
> > * stay in loading state
> > * have a `failureCount` of 1
> > * be set to `isPaused`
> > 
> > when trying to do a mutation while being offline. have a look here: https://codesandbox.io/s/bold-khayyam-0xh40?file=/src/App.js
> > I think this is all "as expected"
> 
> This is working fine on React but in React Native, `isPaused` is not set to true when the mutation has error because of the network offline. So, currently I am handling Persist Mutation myself using AsyncStorage and onError callback. Is anyone facing the same issue?

onlineManager.setOnline may help u!

**Comment by toppsdown** [comment]
> > I can confirm that the query will:
> > 
> > * stay in loading state
> > * have a `failureCount` of 1
> > * be set to `isPaused`
> > 
> > when trying to do a mutation while being offline. have a look here: https://codesandbox.io/s/bold-khayyam-0xh40?file=/src/App.js
> > I think this is all "as expected"
> 
> This is working fine on React but in React Native, `isPaused` is not set to true when the mutation has error because of the network offline. So, currently I am handling Persist Mutation myself using AsyncStorage and onError callback. Is anyone facing the same issue?

I just ran into this same issue on React Native. My offline mutations are failing and not getting set to paused. Did you ever work out a solution?
