### ISSUE TITLE
Mutate outside of react

### ISSUE THREAD

**Issue by naorye** [tannerlinsley/react-query#149]
My app has to listen to postMessage events and act according to those messages. So, if I get 'ABC' message (for example), I have to trigger post request. How can I do it outside of react and use useMutation() (which is react hook)?

**Comment by tannerlinsley** [comment]
You can only use `useMutation` within react. If you need to make a post request outside of React, you can just make the request on your own then manually manipulate the cache using the `queryCache` APIs (as of v1)
