### ISSUE TITLE
Queries are always in refetch with cacheTime: 0 in ReactQueryCacheProvider

### ISSUE THREAD

**Issue by stanislavec** [tannerlinsley/react-query#1496]
**Describe the bug**

Can't get results of queries with ```cacheTime: 0``` in ReactQueryCacheProvider. All queries are always stale and refetching.
But using ```cacheTime: 500``` works.

**To Reproduce**

Use this configuration:

```
import { QueryCache, ReactQueryCacheProvider } from 'react-query';

const queryCache = new QueryCache({
  defaultConfig: {
    queries: {
      refetchOnWindowFocus: false,
      cacheTime: 0,
      retry: 1
    }
  }
});

<ReactQueryCacheProvider queryCache={queryCache}>
// Your app code
...
</ReactQueryCacheProvider>

```
**Expected behavior**

React-query disable caching and give opportunity to get query result.

**Screenshots**

Here is a ReactQueryDevtools:

![Screen Recording 2020-12-20 at 10 56 35 AM](https://user-images.githubusercontent.com/34837948/102708435-2a877900-42b4-11eb-86b5-585865b9c0d3.gif)

**Desktop:**

 - OS: MacOS
 - Browser: Chrome 87.0.4280.88

**Additional context**

Refference about ```cacheTime``` was here, so i tried to use this option: https://github.com/tannerlinsley/react-query/issues/99#issuecomment-572465037

**Comment by TkDodo** [comment]
> All queries are always stale and refetching.

can you create a codesandbox example that reproduces the behavior please.

> React-query disable caching and give opportunity to get query result.

i think you are looking for `staleTime`. cacheTime only comes into play when all subscribers are unmounted:

https://react-query.tanstack.com/guides/important-defaults

https://react-query.tanstack.com/guides/caching#basic-example
