### ISSUE TITLE
Examples are still failing

### ISSUE THREAD

**Issue by ConneXNL** [tannerlinsley/react-query#151]
Great job on 1.0. An hour ago I tested the alpha version that was released and it seemed the onSuccess' weren't called.

Didn't check 1.0 yet but the examples have onSuccess in them but they are currently broken this this issue.

**Comment by tannerlinsley** [comment]
Hmm. Why don't we do this in a codesandbox so we can get things isolated. Would you be willing to set up a reproduction importing 1.0.0?

**Comment by tannerlinsley** [comment]
This sandbox seems to be working fine. Adding a todo is refetching all of the todo lists, which means that onSuccess is getting called. https://codesandbox.io/s/laughing-mclean-i9qel

**Comment by ConneXNL** [comment]
It was my bad, I accidently pulled in 0.4.3 when I wanted to test the latest alpha version.

Currently integrating 1.0, I will let you know when I come accros any bugs.

**Comment by tannerlinsley** [comment]
Nice :)
