### ISSUE TITLE
placeholderData called twice

### ISSUE THREAD

**Issue by lahvey** [tannerlinsley/react-query#1522]
[Open in CodeSandbox](https://codesandbox.io/s/github/tannerlinsley/react-query/tree/master/examples/basic)

add this code to the example, you will see it's called twice
```js
 { placeholderData: () => { console.log(Date.now()); } }
```

The doc says "This function will be executed only once"

**Comment by tannerlinsley** [comment]
Confirmed. We'll look into this.

**Comment by boschni** [comment]
What if the placeholder function contains external dependencies? Do we want the placeholder data to reflect them?

**Comment by boschni** [comment]
Fixed in the documentation
