### ISSUE TITLE
Cache sharing between useQuery and useInfiniteQuery don't work as expected

### ISSUE THREAD

**Issue by vimcaw** [tannerlinsley/react-query#1526]
**Describe the bug**
Once a `queryKey` has been requested with one of `useQuery` or `useInfiniteQuery` before, when querying the same `queryKey` again with another of them, the old cache will be reused directly, which will break the app.

The data returned by a `useQuery` is the response body directly, while `useInfiniteQuery` returns an object with `pages` and `pageParams`, and each item of `data.pages` is the response body. Their structure is different and cannot directly share the cache.

**To Reproduce**
Bug reproduction: [codesandbox.io/s/react-query-v3-cache-sharing-bug-4qwef?file=/src/App.js](https://codesandbox.io/s/react-query-v3-cache-sharing-bug-4qwef?file=/src/App.js)

Just click the `Switch Mode` button, you will see the error.

Then change default mode from `useQuery` to `useInfiniteQuery` (L49) and repeat it, still see the error.

**Expected behavior**
Don't share cache directly, should change struct or simply don't share the cache.

**Screenshots**
Start with **`useQuery`** then switch to **`useInfiniteQuery`**:

![](https://user-images.githubusercontent.com/21964227/103088338-783e1180-4625-11eb-8256-fe51b4b6a8b0.png)

Start with **`useInfiniteQuery`** then switch to **`useQuery`**:

![](https://user-images.githubusercontent.com/21964227/103088504-0914ed00-4626-11eb-8548-a27afd31b921.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: chrome
 - Version: 87.0.4280.88

**Additional context**
None.

**Comment by TkDodo** [comment]
See: https://github.com/tannerlinsley/react-query/discussions/1255
