### ISSUE TITLE
Documentation right panel not scrollable

### ISSUE THREAD

**Issue by mrlubos** [tannerlinsley/react-query#1531]
**Describe the bug**
The "On This Page" section of docs is not scrollable, rendering it pretty much useless.

**To Reproduce**
1. Go to https://react-query.tanstack.com/guides/migrating-to-react-query-3
2. Scroll the page or the right panel 
3. See the right panel will never scroll

**Expected behavior**
The right panel should be scrollable the same way we can scroll the left panel

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] macOS
 - Browser: [e.g. chrome, safari] Chrome
 - Version: [e.g. 22] Version 87.0.4280.88 (Official Build) (x86_64)

**Comment by TkDodo** [comment]
it starts to scroll once you move to the very bottom though:


![screencast 2021-01-08 16-18-29](https://user-images.githubusercontent.com/1021430/104031858-9717d880-51cd-11eb-9e48-0d06c30eb420.gif)

**Comment by mrlubos** [comment]
@TkDodo Yes

**Comment by tannerlinsley** [comment]
We'll glagly accept a PR to make this experience better.
