### ISSUE TITLE
[3.5.5] queryClient.getQueryData queryKey argument is optional by docs, but not in reality.

### ISSUE THREAD

**Issue by mifrej** [tannerlinsley/react-query#1538]
**Describe the bug**
[Documentation](https://react-query.tanstack.com/reference/QueryClient#queryclientgetquerydata
) says, that `queryClient.getQueryData` both arguments  are optional
Where in reality, the TS definition defines as `queryKey` to be mandatory.

What is the reality here? Is it a bug in docs or in code?

**Expected behavior**

As with [useIsFetching](https://react-query.tanstack.com/reference/useIsFetching) where arguments are described the same as in `queryClient.getQueryData` I would expect same behaviour.

This means I should be able to fussy search any partial matching queries in cache like:

```
queryClient.getQueryData<string[]>(['partial-key'])

```
Now this returns undefined although there are active query results in queryClient with keys `['partial-key', 'something-else]`

**Screenshots**
![image](https://user-images.githubusercontent.com/2610830/103268594-00b90b00-49b4-11eb-8fe4-1f8a07b4a3dc.png)

**Additional context**

**Comment by TkDodo** [comment]
> What is the reality here? Is it a bug in docs or in code?

the queryKey is required - the typescript types are always right ;)

**Comment by tannerlinsley** [comment]
A PR to clarify here would be gladly accepted.
