### ISSUE TITLE
Selector argument type

### ISSUE THREAD

**Issue by sshmyg** [tannerlinsley/react-query#1563]
**Describe the bug**
`select` method argument described with wrong type

**To Reproduce**
```
useQuery<string, unknown, number>('id', () => fetch('some/url'), {
    select: (res) => {
        console.log(res, 'should be a number BUT not, its string, due to TS');
    },

    onSuccess: (res) => {
        console.log(res, 'should be a number');
    }
})
```

**Expected behavior**
`TData` should be applied to argument.
But for return value it should be custom.

**Screenshots**
![image](https://user-images.githubusercontent.com/1410608/103551244-c0292800-4eb2-11eb-9d04-ebe524e3461b.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: latest

**Comment by TkDodo** [comment]
Not quite sure what you mean with that screenshot. useQuery has 3 generics:
```
useQuery<
  TQueryFnData = unknown,
  TError = unknown,
  TData = TQueryFnData
>
```

the first one describes the data that is returned from the queryFn, and TData (the 3rd one) is the type that is eventually returned. It defaults to `TQueryFnData`, so you don’t need to do anything if you are not using `select`. If you are, select will transform your `TQueryFnData` to `TData`.

**Comment by sshmyg** [comment]
> Not quite sure what you mean with that screenshot. useQuery has 3 generics:
> 
> ```
> useQuery<
>   TQueryFnData = unknown,
>   TError = unknown,
>   TData = TQueryFnData
> >
> ```
> 
> the first one describes the data that is returned from the queryFn, and TData (the 3rd one) is the type that is eventually returned. It defaults to `TQueryFnData`, so you don’t need to do anything if you are not using `select`. If you are, select will transform your `TQueryFnData` to `TData`.

```
useQuery<string, unknown, number>('id', () => fetch('some/url'), {
    select: (res) => {
        console.log(res, 'should be a number BUT not, its string, due to TS');
    },

    onSuccess: (res) => {
        console.log(res, 'should be a number');
    }
})
```

**Comment by TkDodo** [comment]
I think if you do `useQuery<string, unknown, number>`, select should be a function from string to number, so `res` is a string there.

**Comment by sshmyg** [comment]
> I think if you do `useQuery<string, unknown, number>`, select should be a function from string to number, so `res` is a string there.

Argument of select is server response. So it should be a number. String as I understood is a request.

**Comment by TkDodo** [comment]
Whatever your server returns should be the first generic. In your example, the query functions returns a string. That is also the input to the select function. The output of the select function is the third generic. 

If your server returns a number and your select function transforms that to a string, you’d need: `useQuery<number, unknown, string>`. 

Also, if you don’t intend to type the `Error`, you can just leave out all generics and react query should correctly infer them.

**Comment by sshmyg** [comment]
> Whatever your server returns should be the first generic. In your example, the query functions returns a string. That is also the input to the select function. The output of the select function is the third generic.
> 
> If your server returns a number and your select function transforms that to a string, you’d need: `useQuery<number, unknown, string>`.
> 
> Also, if you don’t intend to type the `Error`, you can just leave out all generics and react query should correctly infer them.

https://codesandbox.io/s/kczxd?file=/index.tsx

![image](https://user-images.githubusercontent.com/1410608/103559518-efde2d00-4ebe-11eb-87f0-daf4daa04a34.png)


![image](https://user-images.githubusercontent.com/1410608/103559548-fa98c200-4ebe-11eb-9cf7-7f46de77b96c.png)

**Comment by TkDodo** [comment]
I think you didn’t save the codesandbox because there is nothing in it for me. 

Please make sure to use the latest version of react-query because the generic order has changed, see: https://github.com/tannerlinsley/react-query/pull/1470

**Comment by sshmyg** [comment]
> I think you didn’t save the codesandbox because there is nothing in it for me.
> 
> Please make sure to use the latest version of react-query because the generic order has changed, see: #1470

Sorry, updated link https://codesandbox.io/s/kczxd?file=/index.tsx

Code should look like on the screen.
![image](https://user-images.githubusercontent.com/1410608/103619992-628cee00-4f3b-11eb-8f55-6f9ca4eb71c8.png)

Use lates version of react-query.

**Comment by TkDodo** [comment]
not sure what is wrong with that sandbox - it doesn't even have a `tsconfig.json`, so a couple of things were not working for me. Anyways, I created a new one from the typescript template and things work fine there, have a look:

https://codesandbox.io/s/exciting-williams-186gw?file=/src/App.tsx

You can either leave out the generic completely and everything will be inferred (like I did in the first usage).

The second usage shows the correct generic order: `<number, unknown, string>`:
- number is returned from the queryFn
- unknown is the error
- string is the result of the select function

`onSuccess` will always receive the response from the queryFn, _not_ the transformed result from the `select` function. maybe that was the source of confusion after all?

I also noticed something additionally: The inferred version stops working after I added `onSuccess` there as well - have a look here: https://codesandbox.io/s/dazzling-firefly-wr1xe?file=/src/App.tsx

maybe @boschni knows why that is or what we can do to prevent it?

**Comment by sshmyg** [comment]
> not sure what is wrong with that sandbox - it doesn't even have a `tsconfig.json`, so a couple of things were not working for me. Anyways, I created a new one from the typescript template and things work fine there, have a look:
> 
> https://codesandbox.io/s/exciting-williams-186gw?file=/src/App.tsx
> 
> You can either leave out the generic completely and everything will be inferred (like I did in the first usage).
> 
> The second usage shows the correct generic order: `<number, unknown, string>`:
> 
> * number is returned from the queryFn
> * unknown is the error
> * string is the result of the select function
> 
> `onSuccess` will always receive the response from the queryFn, _not_ the transformed result from the `select` function. maybe that was the source of confusion after all?
> 
> I also noticed something additionally: The inferred version stops working after I added `onSuccess` there as well - have a look here: https://codesandbox.io/s/dazzling-firefly-wr1xe?file=/src/App.tsx
> 
> maybe @boschni knows why that is or what we can do to prevent it?

It works ok without generic. Both `select` and `onsuccess` has same argument type. (And this is should be in such a way).
But when I add request and response types to generic, it works incorrectly. 

![image](https://user-images.githubusercontent.com/1410608/103624287-fd88c680-4f41-11eb-8b91-1712ead71a0e.png)

**Comment by TkDodo** [comment]
> But when I add request and response types to generic, it works incorrectly.

it does not work incorrectly. It says it needs to be a string because you say so in the generic arguments. The 3rd argument says `string`. See:  `useQuery<number, unknown, string>`. That means:

- the queryFn (`fetchIt`) will return a `number`
- our select function should transform that `number` it gets as an input to a `string`.

so it is expected that our select function does indeed return a string. If you don't want that - change the generic to something else 🤷

**Comment by sshmyg** [comment]
> > But when I add request and response types to generic, it works incorrectly.
> 
> it does not work incorrectly. It says it needs to be a string because you say so in the generic arguments. The 3rd argument says `string`. See: `useQuery<number, unknown, string>`. That means:
> 
> * the queryFn (`fetchIt`) will return a `number`
> * our select function should transform that `number` it gets as an input to a `string`.
> 
> so it is expected that our select function does indeed return a string. If you don't want that - change the generic to something else 🤷

If I change generic to something else, than I will get an error for `onSuccess` argument!
Does `onSuccess` and `select` get same argument?

**Comment by TkDodo** [comment]
> Does onSuccess and select get same argument?

`onSuccess` gets the transformed data from `select`:

```
const queryInfo2 = useQuery<number, unknown, string>("id", fetchIt, {
    select: (response) => {
      console.log(typeof response);
      return response.toString();
    },
    onSuccess: (response) => {
      console.log(typeof response);
    }
  });
```

this will log:

```
number
string
```

**Comment by sshmyg** [comment]
> > Does onSuccess and select get same argument?
> 
> `onSuccess` gets the transformed data from `select`:
> 
> ```
> const queryInfo2 = useQuery<number, unknown, string>("id", fetchIt, {
>     select: (response) => {
>       console.log(typeof response);
>       return response.toString();
>     },
>     onSuccess: (response) => {
>       console.log(typeof response);
>     }
>   });
> ```
> 
> this will log:
> 
> ```
> number
> string
> ```

What if select not transform argument, but just sort it and returns same type as got? 

And what does `eventually` means here?
![image](https://user-images.githubusercontent.com/1410608/103993906-f5799280-519e-11eb-866a-c9e18220ef92.png)

I thought it's about request props and response ones, isn't it?

Thank you :)

**Comment by TkDodo** [comment]
> What if select not transform argument, but just sort it and returns same type as got?

then you can use the same type for both generics:

```
const queryInfo = useQuery<number, unknown, number>("id", fetchIt, {
    select: (response) => {
        return response * 2
    }
  })
```

now, select needs to be a function `(number) => number` instead of `(number) => string` like we had before.

> I thought it's about request props and response ones, isn't it?

it is not.

TQueryFnData = the data that is _returned_ by the query function
TData = the data that is returned from useQuery.

if you don't use select, they are the same (hence the default value). With eventually, I meant the resulting data that is returned by useQuery:

```
const queryInfo = useQuery<number, unknown, string>("id", fetchIt, {
    select: (response) => {
        return response.toString()
    }
  })
```

the input to `select` (named `response`) needs to be of type `number`, because that's what `fetchIt` returns.
`queryInfo.data` will be of type `string` because that is what `useQuery` returns due to the transformation in `select`.

**Comment by sshmyg** [comment]
@TkDodo Thank's for the clarification 🤝

In the future would be useful to add request type to generic ;)

**Comment by TkDodo** [comment]
not sure what you mean with request types? If you mean the input to `fetchIt` - you can just use it with inline functions in typescript:

```
const fetchIt = (id: number): Promise<number> => {
  return Promise.resolve(1);
}

const queryInfo = useQuery<number, unknown, string>("id", () => fetchIt(23), {
    select: (response) => {
        return response.toString()
    }
})
```

there is no need for any generics to `useQuery`, as it only cares about the result type of your fetchFunction, but not really the input.

**Comment by sshmyg** [comment]
Sorry, it my fault, I meant useMutation, and generic for mutation already has this type. 

Thank you one more time ;)
