### ISSUE TITLE
Document: add onSuccess (and other delayed callbacks) will only fire for the latest mutation

### ISSUE THREAD

**Issue by qkreltms** [tannerlinsley/react-query#1573]
https://github.com/tannerlinsley/react-query/issues/241#issuecomment-648973545

> Here's a sandbox: https://codesandbox.io/s/unruffled-sid-g2tzx?file=/src/App.js
> 
> * The mutation function will call it as many time as you hit the button.
> * The `onMutate` callback will fire for every time
> * The `onSuccess` (and other delayed callbacks) will only fire for the latest mutation

Why don't we describe this on document page? :
```The 'onSuccess' (and other delayed callbacks) will only fire for the latest mutation```

_Originally posted by @qkreltms in https://github.com/tannerlinsley/react-query/issues/241#issuecomment-754391100_

**Comment by tannerlinsley** [comment]
We'll gladly accept any PRs to clarify this behavior in the docs 👍

**Comment by qkreltms** [comment]
I'm on it
