### ISSUE TITLE
Error while using <QueryClientProvider />

### ISSUE THREAD

**Issue by sauzy34** [tannerlinsley/react-query#1579]
Using `react-query` `<QueryClientProvider />` in my app but getting an error mentioned below using the following dependencies
```
"react": "^17.0.1",
"react-dom": "^17.0.1",
"react-query": "^3.5.10",
"typescript": "^4.1.3"
```

**Example code**
`App.tsx`
```
import React from 'react'
import { BrowserRouter } from 'react-router-dom'
import ErrorBoundary from './components/ErrorBoundary'
import AppContainer from './components/AppContainer'
import { QueryClient, QueryClientProvider } from 'react-query'

const queryClient = new QueryClient()

function App() {
  return (
    <QueryClientProvider client={queryClient}>
      <BrowserRouter>
        <ErrorBoundary>
          <AppContainer />
        </ErrorBoundary>
      </BrowserRouter>
    </QueryClientProvider>
  )
}

export default App

```
**Error:**

```
Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
    at resolveDispatcher (react.development.js:1476)
    at Object.useEffect (react.development.js:1519)
    at QueryClientProvider (QueryClientProvider.js:33)
    at renderWithHooks (react-dom.development.js:14985)
    at mountIndeterminateComponent (react-dom.development.js:17811)
    at beginWork (react-dom.development.js:19049)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994)
    at invokeGuardedCallback (react-dom.development.js:4056)
    at beginWork$1 (react-dom.development.js:23964)
resolveDispatcher @ react.development.js:1476
useEffect @ react.development.js:1519
QueryClientProvider @ QueryClientProvider.js:33
renderWithHooks @ react-dom.development.js:14985
mountIndeterminateComponent @ react-dom.development.js:17811
beginWork @ react-dom.development.js:19049
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
beginWork$1 @ react-dom.development.js:23964
performUnitOfWork @ react-dom.development.js:22776
workLoopSync @ react-dom.development.js:22707
renderRootSync @ react-dom.development.js:22670
performSyncWorkOnRoot @ react-dom.development.js:22293
scheduleUpdateOnFiber @ react-dom.development.js:21881
updateContainer @ react-dom.development.js:25482
(anonymous) @ react-dom.development.js:26021
unbatchedUpdates @ react-dom.development.js:22431
legacyRenderSubtreeIntoContainer @ react-dom.development.js:26020
render @ react-dom.development.js:26103
./client/src/index.tsx @ index.tsx:7
__webpack_require__ @ bootstrap:21
(anonymous) @ startup:6
(anonymous) @ startup:6

The above error occurred in the <QueryClientProvider> component:

    at QueryClientProvider (http://localhost:3000/app.bundle.js:64623:22)
    at App

Consider adding an error boundary to your tree to customize error handling behaviour.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
```
**Desktop:**
 - OS: MacOS
 - Browser: chrome

**Comment by TkDodo** [comment]
Can you reproduce that in a codesandbox please? `QueryClientProvider` _does_ call `useEffect`, but definitely not conditionally, so it is likely something else.

**Comment by sauzy34** [comment]
@TkDodo 
Please find the code here: https://github.com/sauzy34/use-react-query
I'm not able to figure what's the issue. I'm facing the same errors using **formik**.

**Comment by Aubrey-Zulu** [comment]
Try to move the browserouter into index.js and see what happens

**Comment by TkDodo** [comment]
> @TkDodo
> Please find the code here: https://github.com/sauzy34/use-react-query
> I'm not able to figure what's the issue. I'm facing the same errors using **formik**.

I cloned the repo, made `yarn install && yarn start` and didn't see any error. Maybe it's as easy as nuking `node_modules` on your side.

I'm gonna close this, but if your issue persists feel free to reopen, but with a minimal reproducible _codesandbox_ example so that we can really trace it back to react-query.

**Comment by mhumeniuk** [comment]
I had similar issue - was getting the same _Invalid hook call error_ inside <QueryClientProvider/>  exclusively when testing a component with jest. It appeared that I had an extra ../node_modules folder in a parent directory and react query was somehow only installed there. Jest loaded react-query from that upper folder and was also importing a second copy of React from there. So anyone having similar issue make sure you have @tanstack/react-query properly installed and imported

**Comment by eEQK** [comment]
> It appeared that I had an extra ../node_modules folder in the parent directory and react query was somehow only installed there.

this was my exact case. I'm using bun workspaces and shadcn. When installing a new shadcn component I have to do it in `/root/client` directory, which created `node_modules` in `/root/client/node_modules` in addition to what `bun i` creates (`/root/node_modules`)

Deleting client's node_modules solved the issue
