### ISSUE TITLE
Promise cancelled at initial request

### ISSUE THREAD

**Issue by iamchanii** [tannerlinsley/react-query#158]
### Versions
- react-query: 1.0.2
- react: 16.12

### Screenshots
![Kapture 2020-02-27 at 14 41 44](https://user-images.githubusercontent.com/26643843/75415562-59241400-596f-11ea-952e-e0ba61c04b42.png)

(`self` requested from redux-saga middleware. I try to request resource what has id `6703`)

### Code
```ts
export class ResourceService {
    retrieveResource(resourceName: ResourceName, params: RetrieveResourceParams) {
        const { id, baseUrl } = params;
        const url = getRetrieveUrl(resourceName, id, baseUrl);
        const abort = new AbortController();
        const promise = HttpClient(url, { method: 'get', signal: abort.signal });
        (promise as any).cancel = () => abort.abort();

        return promise;
    }
}
```

### Description
as you see the screenshot, the request when requested at first has been cancel even if it is not duplicated. this issue did not occur in previous version. (0.3.x)

not an issue as critical, but I need request cancellation feature to prevent request as duplicate for reduce server traffic and stress.

and thanks you for your works!

**Comment by danieljb** [comment]
Experiencing the same issue. Using [why-did-you-render](https://github.com/welldone-software/why-did-you-render) hints at [`onStateUpdate`](https://github.com/tannerlinsley/react-query/blob/master/src/useBaseQuery.js#L35) being triggered, leading to the promise being cancelled.

![onStateUpdate](https://user-images.githubusercontent.com/630609/75440704-8c10dc80-595c-11ea-87c9-0f30d3b0c8e2.jpg)

And yeah, thanks for this awesome library and your work!

**Comment by tannerlinsley** [comment]
Found the issue. Had to do with the `useUid()` hook always reinitializing for the first UID generated (zero), which is falsey. Will be fixed in the latest version.
