### ISSUE TITLE
Data not recalculated when select function changes

### ISSUE THREAD

**Issue by jameshiester** [tannerlinsley/react-query#1580]
**Describe the bug**
When a select function is provided to useQuery, the data will not be recalculated if the select function changes.  

**Expected behavior**
Changing the select function should force data to be recalculated.  Perhaps the existing behavior could remain as a default, but there should be an option to include 'select' in the notifyonChangeProps param to set this behavior.  

Note: I realize I could add dependencies to the select function into the query parameter, but this results in more coupling than I would like.

**Comment by TkDodo** [comment]
Do you have a codesandbox example that shows the issue maybe? If you include `data` in `notifyOnChangeProps`, the select function will always be executed. And if it’s not included, it doesn’t matter... so i don’t quite understand the issue

**Comment by jameshiester** [comment]
I'll give this example:
```javascript
const useCustomQuery = (dep) => {
const select = useCallback(todos => todos.filter(todos => todos.id === dep),[dep]);
return useQuery(['TODOS'],fetchToDos, {select});
}
```

In such a case, if the value of dep changes, then the select function is changed, therefore I would expect the select function to be rerun.  This should force the data (i.e. that returned in the custom hook), to be recalculated even though the raw value from the query would be the same.  I've tried adding data to the notifyOnChangeProps, but the result is the same, so that does not result the issue.  

Again, I do not think the answer should be adding dep to the query key, as select could alternatively be passed into the custom hook as a prop, in which case the custom hook should not have to care about the deps of some arbitrary function.

**Comment by TkDodo** [comment]
Why bother with `useCallback` at all?

```

const useCustomQuery = (dep) => {
  return useQuery(
    ['TODOS'],
    fetchTodos,
    {
      select: todos => todos.filter(todo => todo.id === dep)
    }
  )
}
```

**Comment by jameshiester** [comment]
Your suggestion has the same result and illustrates my point, if dep changes the select function should fire again, as the calculated data result should change to reflect the new select function.  However, the current implementation does not do this, so the consumer of useCustomHook still receives the "old" data which was passed through the select function using the original value of dep.

**Comment by TkDodo** [comment]
Ah okay, i think i got you now, but i don’t think that’s how `select` works. The only “dependency” is data, so that you can subscribe to parts of the data and/or transform it. For your case, useMemo might be better. Something like:

```
const useCustomQuery = (dep) => {
  const { data, ...queryInfo } = useQuery(
    ['TODOS'],
    fetchTodos
  )
  return {
    ...queryInfo,
    data: useMemo(() => data?.filter(todo => todo.id === dep), [data, dep])
  }
}

```

**Comment by jameshiester** [comment]
Yeah that was my workaround for now.  I would still suggest warning developers that the select function must be static.
