### ISSUE TITLE
[V3] cacheTime:0 and suspense: true infinite query fetches

### ISSUE THREAD

**Issue by nghieptiki** [tannerlinsley/react-query#1582]
**Describe the bug**
The problem with the `suspense: true` mode is enabled.

**Reproduction** 
https://codesandbox.io/s/delicate-dream-83voj?file=/src/Example.jsx

**To Reproduce**
1. Uncomment `suspense: true`
2. Check the `Console` tab
3. See error loop infinity

** Screenshots**
![image](https://user-images.githubusercontent.com/54924428/103753905-30b08000-503e-11eb-85f4-6e11f7f1697c.png)

**Desktop**
- OS: macOS
- Browser: chrome
- Version: 3.5.11

**Additional context**
Related #1523

**Comment by tannerlinsley** [comment]
We're tracking this issue in #1059
