### ISSUE TITLE
Poor performance when testing

### ISSUE THREAD

**Issue by imjordanxd** [tannerlinsley/react-query#1589]
**Describe the bug**
I'm using react-query to fetch data from the backend, and in one of my test suites (using RTL) I am simulating a rejected promise.

```js
const useUser = (id) => {
	return useQuery(['use-for-id', id], () => getUserForId(id));
}

const UserDetails = ({ userId }) => {
	const { data, isError, isLoading } = useUser(userId);
	if (isError) {
		console.error(error);
		return <div>Something went wrong :(</div>;
	}

	return <div>Hello, {data.user.name}</div>;
};

// in my test file

getUserForId.mockRejectedValue(new Error());
render(<UserDetails userId={1} />);
expect(await screen.findByText('Something went wrong :(')).toBeVisible();

```
The `isError` flag does not toggle to true quick enough and the test always times out. My workaround is to set jest's timeout at the start of the test.

**Comment by TkDodo** [comment]
Per default, react-query retries a failed promise 3 times with exponential backoff - so it will take some time. It would be best to turn off retries for tests. We’ve discussed this here: https://github.com/tannerlinsley/react-query/discussions/1090
