### ISSUE TITLE
Type definitions files are not shipped with v1

### ISSUE THREAD

**Issue by dennismorello** [tannerlinsley/react-query#159]
Hi @tannerlinsley,

First of all, thank you so much for your awesome job! Version 1 is a huge improvement, but I am now having a little issue: my TS project is complaining about missing type definitions files for `react-query`. Was this intentional?

Cheers.

**Comment by tranhl** [comment]
Type definitions are available on [DefinitelyTyped](https://www.npmjs.com/package/@types/react-query).

**Comment by dennismorello** [comment]
> Type definitions are available on [DefinitelyTyped](https://www.npmjs.com/package/@types/react-query).

Yes, but they are not updated for version 1.

**Comment by tranhl** [comment]
If that’s the case it’s probably easiest to create an issue on DefinitelyTyped or make a PR yourself if a lack of typings are a blocker for you.

**Comment by dennismorello** [comment]
I am asking if the choice of removing type definitions from the lib was intentional. If this is the case, then I will open an issue on DefinitelyTyped ;)

**Comment by cherniavskii** [comment]
Type definitions were removed because they were outdated - see https://github.com/tannerlinsley/react-query/commit/d06353a6146facc608eb73a4ef62ffb2944b6cb5

**Comment by dennismorello** [comment]
Ok, so we have to manually add `@types/react-query` as a project dependency because it was *intentionally* removed from the lib's dependencies, but we cannot do it unless `@types/react-query` gets updated for `react-query` v1.

**Comment by dennismorello** [comment]
I am closing this, see [this issue](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/42678) on DefinitelyTyped.

**Comment by tannerlinsley** [comment]
Yes it was intentional. They were severely out of sync with v1, so it made very little sense to keep them as a dependency. If and when the types can catch up, I’ll add it back.

**Comment by tannerlinsley** [comment]
FYI - https://github.com/tannerlinsley/react-query/discussions/362
