### ISSUE TITLE
TypeError: Cannot read property 'prototype' of null

### ISSUE THREAD

**Issue by sanphandinh** [tannerlinsley/react-query#1591]
**Describe the bug**
Throw exception when react-query revalidate (window focus feature). Data of fetch API is good but has error from utils.js and query.js

**To Reproduce**
1. Get data when page loaded
2. Unfocus current window
3. Focus again tab

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/8844419/103846828-9a2d9e80-50d1-11eb-867d-315e2dbe5db3.png)

**Desktop (please complete the following information):**
 - OS: Window
 - Browser: Edge, Safari
 - Version: latest

**Comment by TkDodo** [comment]
Please provide a minimal reproducible example, preferably in codesandbox.

**Comment by sanphandinh** [comment]
Hi, I think I found the problem. 
In utils.js file, we have "isPlainObject" function and this is detail of it
```
export function isPlainObject(o) {
  if (!hasObjectPrototype(o)) {
    return false;
  } // If has modified constructor


  var ctor = o.constructor;

  if (typeof ctor === 'undefined') {
    return true;
  } // If has modified prototype


  var prot = ctor.prototype;

  if (!hasObjectPrototype(prot)) {
    return false;
  } // If constructor does not have an Object-specific method
``

  if (!prot.hasOwnProperty('isPrototypeOf')) {
    return false;
  } // Most likely a plain Object


  return true;
}
```

When my response has a "constructor" property in object. example
```
response = {
code: 200,
data: {
   sample: {  constructor: null }
}
}
```
Then we have exception at "var ctor = o.constructor;" and "var prot = ctor.prototype;"

=> we don't have anything to check constructor is primary value?
Of course, I must change my response

**Comment by tannerlinsley** [comment]
We *could* improve this a bit, but it's very edge case I think. If you can find a workaround, then that's great, otherwise, I'd be open to reviewing a PR to make this better in the future.

**Comment by ebramanti** [comment]
I am running into this as well, I have a field called `constructor` on one of my objects I am returning from my API and it is breaking structural sharing.

I get this error:
```
Structural sharing requires data to be JSON serializable. To fix this, turn off structuralSharing or return JSON-serializable data from your queryFn. [["contracts","contract","ethereum","0xc7bbec68d12a0d1830360f8ec58fa599ba1b0e9b"]]: TypeError: Cannot read properties of null (reading 'prototype')
```
