### ISSUE TITLE
ReactQueryDevtools showing error in console, with Nextjs!

### ISSUE THREAD

**Issue by Suzan-Dev** [tannerlinsley/react-query#1593]
**Describe the bug**
showing error in the console while using devtools with nextjs

**To Reproduce**
1. Initialize a nextjs project with react-query & devtools
2. Open in browser and you'll get error in console

**Expected behavior**
Just wanted to get rid of that error!

**Screenshots**
![devtoolError](https://user-images.githubusercontent.com/58097404/103911724-7b112a00-512e-11eb-9b7d-5ec05034ab5d.png)

**Desktop (please complete the following information):**
 - OS: Linux Mint 20
 - Browser: Chrome
 - Version: Version 87.0.4280.141 (Official Build) (64-bit)

**Comment by andrewjtait** [comment]
I also get this error with a new project using v3.5.11

It might be the same as this issue: https://github.com/tannerlinsley/react-query/issues/1543

**Comment by tannerlinsley** [comment]
Yep. Let's track this in #1543

**Comment by hiramhuang** [comment]
I still got the same error on v3.16.0, temporary solved by load the `<ReactQueryDevtools>` after DOM mounted.

```tsx
function LoadReactQueryDevtools() {
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    setMounted(true);
  }, []);

  return (
    <>
      {mounted && (
        <ReactQueryDevtools initialIsOpen={false} />
      )}
    </>
  );
}
``` 

`"react-query": "^3.16.0"`
`"next": "10.2.0"`
