### ISSUE TITLE
useQuery Window Focus Loop

### ISSUE THREAD

**Issue by johnnyflinn** [tannerlinsley/react-query#16]
May be related to #8 

Strange issue with what I believe has to do with window losing and then regaining focus.

Open below sandbox.  "useEffect called" && "query called" should only happen once.  However, if you click off the window (window loses focus) and click back on the window "query called" happens. 

https://codesandbox.io/s/headless-fast-0s20z?fontsize=14

**Comment by tannerlinsley** [comment]
I hope this answers your question :)

https://github.com/tannerlinsley/react-query#window-focus-refetching
