### ISSUE TITLE
getQueryData returns only result  from one matching cached result even with exact: false

### ISSUE THREAD

**Issue by vipinnair22** [tannerlinsley/react-query#1620]
We have a custom implementation for a multi-list view with a pattern for cache key (an example) as 
"MyList 123"
"MyList 456"
"MyList 789"
...

There's another view which uses data from any one of these rows to display the view. As you can understand, a prime candidate for using `placeholderData` functionality. 
I was trying to get data from all the cached lists using `getQueryData("MyList", { exact: false })`
But it only returns result from one match and not all. My understanding was that this would behave similar to `removeQueries` where it does a partial match and removes all matching values. 

Is there any way to make getQueryData do a partial match and return a unified list of all matches?
Thanks!

**Comment by TkDodo** [comment]
I think getQueryData only returns the first match.

**Comment by vipinnair22** [comment]
> I think getQueryData only returns the first match.

Should this be a feature request in that case? Because it does accept `QueryFilters` which has provision to choose between exact and partial matches.

**Comment by vipinnair22** [comment]
Just pinging to see if this can be taken up as a feature request.

**Comment by boschni** [comment]
The `getQueryData` method only operates on one query but you can use the `queryCache.findAll` method to get multiple queries: https://react-query.tanstack.com/reference/QueryCache#querycachefindall
