### ISSUE TITLE
Docs need to clarify React Native window refetching

### ISSUE THREAD

**Issue by shamilovtim** [tannerlinsley/react-query#1621]
**Describe the bug**
Using a default React Query v2 configuration, my expectation is that out of the box React Query fetches after the app is minimized to the task switcher and then reopened from the task switcher (blur and then focus). However currently this default functionality does not seem to work for us and we are needing to implement our own custom state management for app state. Could you please clarify if in React Native refetching works by default on window refocus or if it requires a custom implementation?

**To Reproduce**
1. useQuery
2. minimize the app
3. bring the app back into view

**Expected behavior**
The query should fetch again but doesn't

React Query 2.26.1
iPhone X Emulator w/ iOS 14.3

**Comment by lart2000** [comment]
I had the same problem, checking the source of react query, I saw that by default it uses 'window.addEventListener' in the focusManager and onlineManager

*my solution:

1.- create directory: 
App/
-->index.tsx
-->setupFocusManager.ts
-->setupOnlineManager.ts
-->... (any setup or app logic file)


2.- files: 
==== index.tsx ====
`
import React from  'react'
//... any imports ...

setupOnlineManager()
setupFocusManager()

const App= ()=> {
 ....
}
export default App
`


==== setupFocusManager.ts  ====
`import { AppState, AppStateStatus } from 'react-native'
import { focusManager } from 'react-query'

const setupFocusManager = () => {
  focusManager.setEventListener(() => {
    const handleAppStateChange = (appState: AppStateStatus) => {
      focusManager.setFocused(appState === 'active')
    }

    AppState.addEventListener('change', handleAppStateChange)

    return () => {
      AppState.removeEventListener('change', handleAppStateChange)
    }
  })
}

export default setupFocusManager
`

==== setupOnlineManager.ts  ====
`import NetInfo, { NetInfoState } from '@react-native-community/netinfo'
import { onlineManager } from 'react-query'

const setupOnlineManager = () => {
  onlineManager.setEventListener(() => {
    return NetInfo.addEventListener((state: NetInfoState) => {
      onlineManager.setOnline(state.isConnected)
    })
  })
}
export default setupOnlineManager
`

**Comment by shamilovtim** [comment]
Fix is documentation related but also code

[In the docs](https://react-query-v2.tanstack.com/docs/guides/window-focus-refetching#custom-window-focus-event) it says 

> In rare circumstances, you may want to manage your own window focus events that trigger React Query to revalidate. To do this, React Query provides a setFocusHandler function

I don't think use of React Native qualifies as a rare circumstance, so these docs should (probably) be adjusted. Correct solution is to have the code it mentions in the app entry. I will adjust this to a "doc bug" ticket.

**Comment by tannerlinsley** [comment]
I think v3 resolves all of this

https://react-query.tanstack.com/guides/window-focus-refetching#managing-focus-in-react-native

**Comment by shamilovtim** [comment]
We're planning on migrating eventually but the biggest impediment right now is a lot of broken tests the moment that we do :)

**Comment by shamilovtim** [comment]
Closed by #1622
