### ISSUE TITLE
Scroll restoration breaks when SSR + InfiniteQuery

### ISSUE THREAD

**Issue by nubpro** [tannerlinsley/react-query#1623]
**Describe the bug**
Cached data is not restored and scroll position is reset when a user return to their previously visited page.
I am not sure whether this has something to do with React Query or not, but since it did promised "it just works" I was hoping this should just had work out of the box. Or did I made a mistake in the code?

Here's a sandbox describing the issue: https://codesandbox.io/s/elated-water-x7hwx

**To Reproduce**
1. Scroll down
2. Wait for more content to be populated.
3. Hit next page.
4. Go back.
5. Scroll position at the top and cached data is lost. 

If you disable `getServerSideProps()` block entirely, and perform the same steps, scroll restoration works as intended and the cache data remains intact.

**Expected behavior**
After returning to the page which is `index`, the scroll should stay where it was and the loaded content should remain there.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOS
 - Browser: [e.g. chrome, safari] Chrome
 - Version: [e.g. 22] Version 87.0.4280.88 (Official Build) (arm64)

**Comment by nubpro** [comment]
My current workaround is to use `initialData` instead of hydration to prevent the cache data from clearing up.
As for the scrolling state, this is a little tricky to implement, but I end up storing the scroll position in the app's global state. I wish I could store this figure with useQuery? Or better yet an out of the box experience without needing to do any of this.

https://codesandbox.io/s/hardcore-pond-zjbwj?file=/pages/index.js:1938-1949

**Comment by tannerlinsley** [comment]
I'm not sure if this is the issue, as I haven't looked into it much yet, but It's important to note that codesandbox's routing doesn't really work the same way as a browsers, and thus it's not suitable to test scroll restoration. You must deploy it to a regular browser env (not even the preview in new window option works)

**Comment by nubpro** [comment]
> I'm not sure if this is the issue, as I haven't looked into it much yet, but It's important to note that codesandbox's routing doesn't really work the same way as a browsers, and thus it's not suitable to test scroll restoration. You must deploy it to a regular browser env (not even the preview in new window option works)

I can confirm this is happening on my actual environment not just in the sandbox.

**Comment by nubpro** [comment]
Yeap the scrolling restoration doesnt work neither.

**Comment by danbeneventano** [comment]
I was having this issue as well. The infinite query seems to be reset and only the first page is loaded, when using prefetchInfiniteQuery in Next.js SSR. I ended up giving up on infinite queries and opted for pagination because of this issue and #1458

**Comment by nubpro** [comment]
@tannerlinsley
Sorry to bug you but I'm on my edge to get this problem resolved, could you provide some pointers?

**Comment by nubpro** [comment]
https://github.com/tannerlinsley/react-query/blob/ead2e5dd5237f3d004b66316b5f36af718286d2d/src/hydration/hydration.ts#L145-L151

I've isolated the issue to this optimization strategy. The cached data doesnt get cleared after I commented off these codes.

However, I still cant get scroll restoration to work properly, it's a lot of harder than I thought.

**Comment by Ephem** [comment]
> It looks like query.setState will replace all the cached page entirely, what can we do here?

This is correct. If you hydrate a query with newer data than what is already in the cache, that entire querys data gets replaced with the new data. I think this is the only safe way to handle this scenario, since otherwise you would have a query with parts old and parts new data.

I'm guessing `getServerSideProps` in Next gets triggered even on back button? (Can't verify myself right now)

I'm not sure if this can be fixed entirely inside of RQ (but not sure it can't either), but as a fix(/workaround) it seems it should be possible in Next to avoid passing any new data to the Hydrate component if the navigation event was a back/pop?

**Comment by nubpro** [comment]
> I'm guessing `getServerSideProps` in Next gets triggered even on back button? (Can't verify myself right now)

Yep, it gets triggered.

> I'm not sure if this can be fixed entirely inside of RQ (but not sure it can't either), but as a fix(/workaround) it seems it should be possible in Next to avoid passing any new data to the Hydrate component if the navigation event was a back/pop?
> 
> Update: From RQs perspective, we don't know anything about navigations since we aren't integrated at the router layer. We only know that "please hydrate this new data for me into the cache". Even if we can't "fix" this in RQ, it would be good to document this pattern in the docs and/or an example.

I had to use `initialData` as the workaround as it is stands, it works flawlessly. IMO, I think we should take a look at what `initialData` is doing and lend its logic to `hydration` which is not to disregard the existing state.

This might be a naive solution:
```
if (isInfiniteQuery === false) { // <----- I added this
    if (query) {
      if (query.state.dataUpdatedAt < dehydratedQuery.state.dataUpdatedAt) {
        query.setState(dehydratedQuery.state)
      }
      return
    }
}
```

**Comment by Ephem** [comment]
The way `initialData` handles this is simply to never update the cache after the initial seed, so I do think there is a flaw in that solution in that you can't ever get subsequent data from `getServerSideProps` into the cache:

1. Go to the page with an infiniteQuery and show more
2. Navigate to a new page
3. Navigate to the page with the infiniteQuery again (not using the back button)

If data was updated on the server between 1 and 3, I don't think that will be reflected on the page even though it was fetched in the `getServerSideProps`. The reason for this is that `initialData` will only be used if there is no current data in the cache, so even if we fetched new data in `getServerSideProps`, that wont be used. (If `staleTime` has passed, that data might get fetched again on the client however, but that means double fetching)

Another way to solve this on the application level is to encode this specific application state as a query parameter in the url. That way you can know how much to fetch in `getServerSideProps`, but I know that isn't always a popular thing to add.

**Comment by ivanjeremic** [comment]
I use ReactQuery normal in Nextjs so no serverSideProps or something and I simply can't get scroll-restoration to work, has anyone a working example or an idea of what I can do to make it work in Nextjs?

**Comment by uguremirmustafa** [comment]
I am having the same problem. I fetch the data with `useInfiniteQuery` and when I change the route to another page  scroll position does not persist and also I lose cached data. I don't use `getStaticProps` or `getServerSideProps` .

**Comment by Ephem** [comment]
This specific issue is about server side rendering and infinite query, so if you are not using `getServerSideProps`, `getStaticProps` or `getInitialProps` your issue is probably unrelated to this one (but similar) and I encourage you to open a separate issue with a reproduction. If you mean you are using `getInitialProps` that works the same as I described above however so in that case it is related (but could have other solutions).

Do note that what you describe can happen if you put `<QueryClientProvider>` directly in your page instead of in `_app.jsx`, since that blows away the cache on each page navigation, so please verify that's not the case before opening a new issue. 😄

**Comment by b-barry** [comment]
I am getting the same issue than @ivanjeremic  using `getStaticProps` when navigate back. I will try with initialData.
@Ephem could we have an option to have threshold for `dataUpdatedAt` to avoid setState ?

**Comment by Ephem** [comment]
@b-barry Did I understand you correctly that it always works in prod, but you have weird behaviours in dev?

To be clear, React Query does not manage scroll position in any active way. The reason scroll position usually works with React Query is that because it keeps data cached it can show the previous page immediately which lets the built in browser scroll restoration work as intended.

**Comment by b-barry** [comment]
Hello @Ephem ,

Sorry for the delay, I was testing. When I am building in production, everything is working fine. The scroll restoration is not working directly because we are moving from static to client side. So, I am saving the first time in localStorage.
