### ISSUE TITLE
Scroll Restoration is not working even on the doc's examples

### ISSUE THREAD

**Issue by SimaAmini** [tannerlinsley/react-query#1629]
**Describe the bug**
according to the [documentation](https://react-query.tanstack.com/guides/scroll-restoration) the **Scroll Restoration** works for all queries but I couldn't be able to use it so far. When I scroll down a page and then go to another page and return to the previous page, I'm again at the top of the page.
I also check the documentation's examples like [Rick and Morty](https://react-query.tanstack.com/examples/rick-morty) and again it's not working.

 Version: ^3.3.5
![scroll-react-query](https://user-images.githubusercontent.com/12030102/104325788-402c3f00-54fe-11eb-8c05-6f482d252e0d.gif)

**Comment by tannerlinsley** [comment]
This is due to codesandbox's routing. Deployed, they work just fine: https://csb-hewky-7cp04rzhw.vercel.app/

**Comment by thkim90** [comment]
> This is due to codesandbox's routing. Deployed, they work just fine: https://csb-hewky-7cp04rzhw.vercel.app/

broken link... please restore
