### ISSUE TITLE
setQueryData slow with large data sets

### ISSUE THREAD

**Issue by andrewnaeve** [tannerlinsley/react-query#1633]
**Describe the bug**
This may be a performance question, or maybe I need a paradigm shift. 

I have a large query that comes back with several mb worth of data, for a table that gets frequently sorted. When I sort the data, and call `queryClient.setQueryData()` with the new sorted rows, it takes around half a second to complete. I've tried to break the data out into React state, and when I do that, it sorts in 10ms- but getting React state to sync nicely with React Query is challenging.

In my profiler, I see quite a bit of time being taken by "replaceEqualDeep".

I'm wondering if I'm using react-query incorrectly. Should I be replacing the cached query data like this? Are there any better strategies for large datasets?

**Screenshots**
<img width="646" alt="calltree" src="https://user-images.githubusercontent.com/16847584/104270894-6db9af80-544e-11eb-903f-a4d6ec073867.png">

**Desktop (please complete the following information):**
- MacOS, latest FIrefox and Chrome
- "react-query": "^3.5.5"

**Comment by TkDodo** [comment]
This might be due to react-query's `structural sharing` feature. You can turn that off by setting `structuralSharing: false` on your query.

however, I would advise _against_ mixing client state with server state and manipulating the query in the cache directly. The idea is that the data you see is just a borrowed "view" of the actual server state, so the client does not own it. If a background update happens, or another component mounts that also uses this query, the data will be re-fetched and you will "loose" your client side sorting.

I think a good alternative would be to keep server and client state separate. In your case, that would mean:
- keep the data that you get from the server in the queryClient and do _not_ change it.
- only store the sorting "choice" that the user made in react state on the frontend.
- compute the new data in the render function, possibly with `useMemo`, combining those two states.

This could be nicely abstracted in a custom hook, something like:

```
const useBigData = () => {
    const queryInfo = useQuery('bigData', () => fetchBigData())
    const [sorting, setSorting] = React.useState(undefined) // accepts 'foo' | 'bar' as sorting keys

  
   return {
        query: {
            ...queryInfo,
            data: React.useMemo(() =>{
                return sortedDataDependingOnStoredSorting(queryInfo.data, sorting)
            }, [queryInfo.data, sorting])
        },
        setSorting,
        sorting,
   }
}
```

You can use this like so in your component:

```
const { query, sorting, setSorting } = useBigData()

<Button onClick={() => setSorting('foo)}>Sort by Foo</Button>
<Button onClick={() => setSorting('bar)}>Sort by Bar</Button>
<DataTable>{data}</DataTable>
```

if the server data updates - it will be sorted. if the user changes the sorting - it will be sorted. I've made the experience that this approach works very well in most cases.

**Comment by andrewnaeve** [comment]
Thanks for this great reply. Thought I might have been thinking about it incorrectly. I'll give that a shot.

**Comment by stephen776** [comment]
We are experiencing this issue on `react-native` without a particularly large set of data. Dataset is an object with a handful of primitive properties and one property which is an array of objects with maybe 20 entries.

We are calling `setQueryData` upon receipt of of an event over websockets that occurs about every 3 seconds. The JS thread eventually grinds to a halt.

**Comment by baughmann** [comment]
I'm sorry to say this is still an issue, even without `structuralSharing`. I've had to move away from this library for my app's primary data because of this, though I still use it for data that is not frequently updated via a websocket.

**Comment by SebKranz** [comment]
<img width="700" alt="Screenshot 2024-01-27 at 22 58 45" src="https://github.com/TanStack/query/assets/33868262/8fb9e308-4743-40a5-b38c-b201c10271ea">

It looks like `setQueryData` uses `find` internally, which iterates over every value in the cache. This means, if I receive a list and from the server and want to prime the cache with every value, it's almost quadratic in complexity.

As a workaround, I accessed Query-Object directly:

```ts
// this returns the cache for this key if existing, or creates a new one with default options:
const query = client.getQueryCache().build(client, { queryKey: /* ... */ }) 
query.setData(data)
```

**Comment by zowebs** [comment]
Hello, this issue still persists in 2025. I am updating large data set using `setQueryData` during optimistic update. Using react-native, on web this works fine, the delay between optimistic update and rerender is apprx 15ms. On mobile (both Android/iOS) the delay between update and rerender is almost 200ms, which terribly affects user experience. Did anyone come up with a solution for this issue?

**Comment by TkDodo** [comment]
@zowebs have you tried turning off `structuralSharing` ?

**Comment by technoligest** [comment]
@TkDodo  I have a list of ~30 json objects that I'm trying to optimistically update and I'm seeing delays up to 500ms, sometimes worse. If I save the data in state manually and update it with effect, I get perfect performance, but I keep hearing Dan yelling at me [Don't stop the data flow](https://overreacted.io/writing-resilient-components/#principle-1-dont-stop-the-data-flow).

Each json object is something like this:
```typescript
{
   title: "This is a short title",
   description: "This is a paragraph",
   status: "completed"
}
```

**Comment by TkDodo** [comment]
Please show a minimal reproduction so that I can investigate, thanks.

**Comment by Mangor1no** [comment]
<img width="1353" alt="Image" src="https://github.com/user-attachments/assets/19c5ca90-8bfc-47a0-81fc-3b04d698b293" />

<img width="679" alt="Image" src="https://github.com/user-attachments/assets/7b2302d6-1002-44b0-a095-2b8d6ffa1b38" />

I'm also having the same problem. My case is using react-query as caching layer for the data I received from websocket. The data is an array of ~2000 items, each item is an object of ~40-50 keys. As you can see from the images above, I've ran the profiller and it points out `setQueryData` function. Not sure what I can do to optimize it.

**Comment by Mangor1no** [comment]
> <img alt="Image" width="1353" src="https://private-user-images.githubusercontent.com/39774481/427334009-19c5ca90-8bfc-47a0-81fc-3b04d698b293.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDMwNDc5NDksIm5iZiI6MTc0MzA0NzY0OSwicGF0aCI6Ii8zOTc3NDQ4MS80MjczMzQwMDktMTljNWNhOTAtOGJmYy00N2EwLTgxZmMtM2IwNGQ2OThiMjkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMzI3VDAzNTQwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3MGU5MTJmYjljZjJlYzIyYjdjNGU5NTdhOGQyNDMwNTFiMTQ3ZTE4MzJiMmM5Y2FiNDI1MTBlODNlZjZmM2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.L0eKbE4chmdEXoX_IWub_GOnVJCBNi0UDhlEfC77azQ"> <img alt="Image" width="679" src="https://private-user-images.githubusercontent.com/39774481/427334197-7b2302d6-1002-44b0-a095-2b8d6ffa1b38.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDMwNDc5NDksIm5iZiI6MTc0MzA0NzY0OSwicGF0aCI6Ii8zOTc3NDQ4MS80MjczMzQxOTctN2IyMzAyZDYtMTAwMi00NGIwLWEwOTUtMmI4ZDZmZmExYjM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMzI3VDAzNTQwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5ZmI1NzI1ODgxZTEyYWFhMzlhMGRiMjE5Y2E5M2NmNDkzZDM2NjU4NjFkMTM4MGYyMTAwOTNiZGRmMjM1MTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.S0SUn2bGgVe7wZ7ukYy6ekncWIkyPZD4RuFML3lx5Sw">
> I'm also having the same problem. My case is using react-query as caching layer for the data I received from websocket. The data is an array of ~2000 items, each item is an object of ~40-50 keys. As you can see from the images above, I've ran the profiller and it points out `setQueryData` function. Not sure what I can do to optimize it.

Also I should notice that I've tried to turn off the `structureSharing` option, but got no luck in it

**Comment by Mangor1no** [comment]
I've end up with a new flow, that doesn't involved into `setQueryData` by leveraging React ref and immediately I gain significant performance comparing to using `setQueryData`

**Comment by Mangor1no** [comment]
Hey, thanks for reply @TkDodo. I just investigate the benchmark again and I don't think the problem is coming from `setQueryData`. In fact, the profiler shown that it's pretty fast in my reproduction: https://codesandbox.io/p/sandbox/2mxfm7
