### ISSUE TITLE
Upgrading to v3 caused "... is not assignable to parameter of type 'QueryFunction..." error

### ISSUE THREAD

**Issue by joaoreynolds** [tannerlinsley/react-query#1644]
**Describe the bug**
Using `typescript v4.1.3` typescript ran fine, but when I upgraded `react-query` from v2 to v3.5.12 typescript threw an error if I did not inline my functions in `useQuery`. #291 exactly describes the issue I was having.

### Not Working, But Should:
```typescript
  async function fetchVehicleData(key: string, apiKey: string): Promise<{ routes: IFullRouteWithStops[]; vehicles: IVehicleData[]; }>{
      //...
      return {
        routes,
        vehicles
      }
    }
  }

  const {
    status: vehiclesStatus,
    data: vehiclesData,
    error: vehiclesError
  } = useQuery(['vehiclesData', clientSettings.apiKey], fetchVehiclesData, {
    refetchInterval: 3600000,
    refetchIntervalInBackground: true
  })
```

Which threw the following error in typescript on `fetchVehiclesData`:
```
Argument of type '(key: string, apiKey: string) => Promise<{ routes: IFullRouteWithStops[]; vehicles: IVehicleData[]; }>' is not assignable to parameter of type 'QueryFunction<{ routes: IFullRouteWithStops[]; vehicles: IVehicleData[]; }>'.
```

### Working:
```typescript
  async function fetchVehicleData(apiKey: string): Promise<{ routes: IFullRouteWithStops[]; vehicles: IVehicleData[]; }>{
      //...
      return {
        routes,
        vehicles
      }
    }
  }
  const {
    status: vehiclesStatus,
    data: vehiclesData,
    error: vehiclesError
  } = useQuery(['vehiclesData', clientSettings.apiKey], () => fetchVehiclesData(clientSettings.apiKey), {
    refetchInterval: 3600000,
    refetchIntervalInBackground: true
  })
```

**To Reproduce**
Unfortunately I could not reproduce this issue in codesandbox (I also tried downloading the sandbox locally and running it), so I'm not sure what about my environment didn't agree, I even tried the same ts config + all the same library versions - I know, that's not super helpful.

**Additional context**
Chatted directly with @tannerlinsley on Slack quite a bit about this and he recommended I post this issue and tag @boschni 

Another thread concerning this issue, if that's at all helpful:
https://www.reddit.com/r/reactjs/comments/kqg27b/reactquery_typescript_question/

**Comment by boschni** [comment]
Hi @joaoreynolds! You'll need to use either inline functions or the query context: https://react-query.tanstack.com/guides/migrating-to-react-query-3#query-key-partspieces-are-no-longer-automatically-spread-to-the-query-function

**Comment by TkDodo** [comment]
Since the linked reddit threads states that inline functions solved your problem, I’m gonna close this.
