### ISSUE TITLE
[v3] Setting cacheTime to a number >= 2^31 incorrectly garbage collects a query when it's inactive

### ISSUE THREAD

**Issue by darrenvong** [tannerlinsley/react-query#1646]
**Describe the bug**
Setting the `cacheTime` option to a "large" number (anything that is greater than or equal to `2**31`) causes the query to garbage collect as soon as it becomes inactive.

**To Reproduce**
1. Use the `useQuery` hook in a React component, and in the query's option, set the `cacheTime` to any number `>= 2**31`. i.e.
```typescript
// Inside a React component
const todos = useQuery("todos", getTodos, { cacheTime: 2**31 });
```
2. Assuming we're in an app with two pages (or any way that'd make the component that consumes the hook above unmount), navigate away from the component.
3. Go back to the page with said component that's using the query
4. The query is refetching again rather than reading from the cache, since it's being garbage collected when it isn't being used, even though the query isn't supposed to be garbage collected unless `2**31` ms (~25 days) have been passed!

**Expected behavior**
The query is not being refetched, remains and reads from the query cache, unless it's been explicitly invalidated.

**Desktop (please complete the following information):**
 - OS: MacOS Catalina
 - Browser: Brave
 - Version: 1.18.77

**Additional context**
I found this from working on a project where we know the data in a certain query is fairly stable, and so we have decided to increase the query's cache time to `30 * 24 * 60 * 60 * 1000` (30 days). When I opened the dev tool, I spotted that the query was garbage collected as soon as the query is inactive! After playing around with different values and seeing that setting to other arbitrarily large numbers still seems to work, I then noticed that 30 days is just over `2**31`, the value that'd cause a signed 32-bit integer to overflow which is how I managed to narrow down the "magic number" that breaks this.

I have to say I'm reasonably surprised by this since `Number.MAX_SAFE_INTEGER` is `2**53 - 1` so I'd have thought we'd only hit problems if we exceed that. Hopefully this is enough details, otherwise happy to provide a minimal CodeSandbox when I get a bit more time.

**Comment by boschni** [comment]
This happens because JS timers only support 32-bit numbers:
```js
setTimeout(() => console.log('test'), 2**31)
```
If we want to support such large timespans then we'd probably need to work around this limitation: https://stackoverflow.com/questions/3468607/why-does-settimeout-break-for-large-millisecond-delay-values

**Comment by lucaslcode** [comment]
I would add that while you wouldn't imagine the browser would stay open that long, it is relevant if you are using local storage to persist the query cache.

**Comment by boschni** [comment]
I do wonder about the use case because you would indeed not expect the browser to be open for that long and any time queries are hydrated the cache timer resets.

**Comment by darrenvong** [comment]
How does this work when used with the experimental local storage persist plugin? Does the `maxAge` config takes precedence on deciding which query/mutation of the cache to discard? If so, yeah I can't see a good use case where anyone would leave their browser open for that long. The 30-day number I gave was an arbitrary number we picked without knowing this `setTimeout` limitation, but it's not like it's something we can't work around.

**Comment by boschni** [comment]
It's a bit complicated, but the `cacheTime` will start counting down from the moment a query is created (hydrated) or when a query becomes inactive (not used on screen). So if the cache time is 15 minutes and a query is inactive for 15 minutes then it will be removed from the in memory cache and therefore also removed from the local storage cache. The `maxAge` is only checked when hydrating, on application startup it checks the age of the cache in the local storage and if it is older than `maxAge` then it will not hydrate it.

**Comment by darrenvong** [comment]
> The `maxAge` is only checked when hydrating

Does that mean even if the `cacheTime` of a particular query is set to the maximum number supported (so `2^31 - 1`), but if `maxAge` is left at the default of 24 hours, the next time the cache is being hydrated from local storage, it will discard the query anyway if it is older than 24 hours? In other words, is the `cacheTime` only used for the in memory cache and that info is not saved to the local storage cache?

**Comment by boschni** [comment]
Correct! The maxAge applies to the entire cache and is only checked when hydrating from local storage. The cache time is a separate mechanism for GC

**Comment by darrenvong** [comment]
Thanks for the clarification. In that case, it sounds like the long `cacheTime` wouldn't achieve our initial intended purpose of keeping a stable query around for a long time anyway without tweaking `maxAge` too. And from looking at the source for this, it doesn't look like `maxAge` would suffer from the same problem as `cacheTime`, as it's only looking at if the difference between the last timestamp the query was fetched (?) and the current time of hydration is greater than `maxAge`.
https://github.com/tannerlinsley/react-query/blob/0b8c55c3a6f4a9e12a33ec828bc415c77679cf8b/src/persist-localstorage-experimental/index.ts#L57-L65

With all that said, since I doubt there will be a huge demand for such a large timespan to be supported, I think I'll close this issue off :)
