### ISSUE TITLE
Query data not updated on instances of a successful query

### ISSUE THREAD

**Issue by fTrestour** [tannerlinsley/react-query#1653]
**Describe the bug**
`QueryClient` is configured with a 1 minute `staleTime`.
I mount many instances of a single query (all have the same `queryKey`) pretty much at the same time.
The `useQuery` instance that triggers the network call gets to a `success` status once the request is done but other instances are stuck in a `loading` state with `undefined` data.

**To Reproduce**
I didn't manage to reproduce in a simple environment.

My `queryClient` looks like this:
```
const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      staleTime: 60 * 1000,
      retry: (failureCount, error) =>
        failureCount < 10 &&
        error instanceof HTTPError &&
        (error.status === null || error.status >= 500),
    },
  },
})
```

The hook that is mounted pretty much everywhere that shows the unexpected behaviour is the following:
```
export const useAuthenticatedUser = () => {
  const { data, ...other } = useQuery({queryKey: <CONSTANT_VALUE_HERE>, queryFn: () => apiQuery(...)})
  console.log(data)
  return { user: data, ...other }
}
```

**Expected behavior**
I'd expect to have all instances of `useAuthenticatedUser` return user data when the network query is successful.

**Screenshots**
![image](https://user-images.githubusercontent.com/14646596/104707939-611eab00-571d-11eb-98f3-2f56d6aa8cea.png)

**Desktop (please complete the following information):**
 - OS: MacOS 11.1
 - Browser: Chrome
 - Version: 87.0

**Additional context**
Notice the described behaviour doesn't happen every single time. Sometimes, all instances access the received data. Overall, I noticed the issue arises more often on the production build than on the development mode (I use CRA).

**Comment by TkDodo** [comment]
> I didn't manage to reproduce in a simple environment.

not sure there is much we can do if you cannot reproduce it. One thing that comes to mind is that you maybe create different queryClients during render. make sure that the `const queryClient` is static and _not_ created within your render function and that all components have the same `QueryClientProvider` above them.

**Comment by boschni** [comment]
Does v3.6.1 fix your issue?

**Comment by fTrestour** [comment]
It does! Thanks a lot for your work

**Comment by boschni** [comment]
Good to hear!
