### ISSUE TITLE
useInfiniteQuery with initialData

### ISSUE THREAD

**Issue by josephfarina** [tannerlinsley/react-query#1658]
**Describe the bug**

It appears that if you provide `initialData` (the first page SSR'd via Next in my case) for `useInfiniteQuery` *without* setting `enabled: false` on page load it will automatically fetch the second page and replace the `initialData` with it (instead of adding the new page to the second position of the array).

I'm not 100% positive that I am hooking it up correctly. I couldn't find any documentation or examples using `useInfiniteQuery` with initial data.

Sorry if this is the wrong place! I opened up a discussion as well: https://github.com/tannerlinsley/react-query/discussions/1648

**To Reproduce**
1. Create a query using `useInfiniteQuery` and fill the `initialData` option with the first page.
2. When you load the page it will happen.

```
  const { data, fetchNextPage, hasNextPage } = useInfiniteQuery(
    "query",
    nextPageQuery,
    {
      initialData: { pages: [initialData], pageParams: [1] },
      ...
    }
  );
```

**Expected behavior**
I would assume it would put the newly fetched second page in the 2nd position of the array instead of the 1st.

**Additional context**

If you add `enabled: false` and rely on calls to `fetchNextPage` for subsequent pages then it works as expected.

**Comment by bahaa96** [comment]
I have the problem

**Comment by TkDodo** [comment]
try initializing with `pageParams: []`, thus having the pageParam for the first page be `undefined`. `pageParams` are usually filled by the `getNextPageParam` function, so it will be filled with data from the _previous_ page: The second page knows it's params because the first page tells what the "next" cursor is. The first page doesn't have that, because there is no "previous" page.

**Comment by TkDodo** [comment]
you can also see this in the devtools of the [Infinite loading example](https://codesandbox.io/s/github/tannerlinsley/react-query/tree/master/examples/load-more-infinite-scroll). after you scroll down to the bottom 2 times, this is what the data in the cache looks like:

![Screenshot 2021-02-04 at 10 37 07](https://user-images.githubusercontent.com/1021430/106873645-f5ed4680-66d4-11eb-9a7a-91fb544bd1dc.png)

**Comment by boschni** [comment]
Added a test to check the behavior and it seems to work correctly with initial data: https://github.com/tannerlinsley/react-query/commit/79e1c17cbb9068aab2dbc852551b77bc242b96d2

**Comment by tannerlinsley** [comment]
I can confirm everything works as expected as well.
