### ISSUE TITLE
Possible inconsistency with `isError` and `error` when using `keepPreviousData: true`

### ISSUE THREAD

**Issue by tannerlinsley** [tannerlinsley/react-query#1659]
- Turn on `keepPreviousData: true`
- Template using `isError`, not `error`, to detect an error state
- Fire a query that resolves and displays normally
- Fire a query that fails and introduces an error state
- The `isError` state is `false`, but there is clearly an `error` present.

I *think* the desired effect is that if an `error` is encountered in the *new/latest* query, the status should not be `success` with the previous data, but `error` with the new query.

Codesandbox: https://codesandbox.io/s/optimistic-hooks-n5v12?file=/src/index.js

**Comment by TkDodo** [comment]
if we don't want to keep anything in case of error (not even the existing previous data), I think it would be as simple as adding a check for `status !== 'error'` to this check:

https://github.com/tannerlinsley/react-query/blob/78a1e8a37ed80944e60559c0fde9fc6172a77bfe/src/core/queryObserver.ts#L367-L377
