### ISSUE TITLE
A CancelledError is thrown after refetching a previously cancelled query when useErrorBoundary: true

### ISSUE THREAD

**Issue by Donov4n** [tannerlinsley/react-query#1666]
_First and foremost, thanks for this super cool project :)_

**Describe the bug**

When `useErrorBoundary` option is `true` and the request is cancellable (presence of a `.cancel()` function on the promise),  
if a currently running query "A" is cancelled because its replaced by another query "B" then, if we go back to the "A" query, a `CancelledError` is thrown.

(Sorry, its difficult to clearly explain, please see the repro below) 

**To Reproduce**

Please see [this sandbox](https://codesandbox.io/s/react-query-error-case-6hxhd?file=/src/Bug.js).  

(See the console for the throwed `CancelledError`).

**Expected behavior**

The "A" query should be refetched without throwing a `CancelledError`.

**Desktop (please complete the following information):**
 - OS: macos
 - Browser: chrome
 - Version: 87.0.4280.141

**Comment by adeelibr** [comment]
I exactly have the same issue, with the same reproduction :) Thank you for creating this issue with a codesandbox

**Comment by tonypee** [comment]
I am experiencing something similar (getting CancellationError) when calling a fetchQuery at the same time as an invalidateQueries(). I will see if i can get a sanbox
