### ISSUE TITLE
[react native] when using persistWithLocalStorage - localStorage is not defined

### ISSUE THREAD

**Issue by nbastoWM** [tannerlinsley/react-query#1678]
**Describe the bug**
When using persistWithLocalStorage with React Native I get this error as soon as I do ```persistWithLocalStorage(queryClient)```

**To Reproduce**
My code:
```
const App = () => {

const queryClient = new QueryClient({
    defaultOptions: {
      queries: {
        cacheTime: 1000 * 60 * 60 * 24 // 24 hours
      }
    }
  })
  
persistWithLocalStorage(queryClient)

return (
    <QueryClientProvider client={queryClient}>
      <ReduxProvider store={store}>
        <PersistGate loading={<Text>...</Text>} persistor={persistor}>
          <MenuProvider backHandler={true}>
            <NavigationContainer
              ref={navigationRef}
              onReady={() =>
                (routeNameRef.current = navigationRef.current.getCurrentRoute().name)
              }
              linking={linking}
              onStateChange={onStateChange}>   
              <DrawerNav />
            </NavigationContainer>
          </MenuProvider>
        </PersistGate>
      </ReduxProvider>
    </QueryClientProvider>
  );
};

export default App;
```

**Expected behavior**
I expected to persist the react query cache

**Screenshots**
![image](https://user-images.githubusercontent.com/15138821/105520305-70c86180-5cd2-11eb-9fb3-d9ac878391b5.png)

**Smartphone (please complete the following information):**
 - Device: Android & iPhone
 - OS: Android & iOS
 - Browser: -
 - Version: 
    "react": "16.13.1",
    "react-native": "0.63.3",
    "react-query": "^3.6.0",

**Comment by delanebob** [comment]
@nbastoWM I believe this is because localStorage isn't an native API the same way it is on the web. The equivalent for react native is [Async Storage](https://github.com/react-native-async-storage/async-storage).

By the looks of the documentation there doesn't seem to be support for this at the moment. Support could be added in future though as the APIs are relatively the same. The main difference is that AsyncStorage asynchronous, where as localStorage is synchronous.

**Comment by delanebob** [comment]
@nbastoWM It might be worth looking at [this code in this discussion](https://github.com/tannerlinsley/react-query/discussions/92#discussioncomment-47324) to see if it can help for the time being.

**Comment by vstlouis** [comment]
We could easily solve this by passing in a custom storage adapter. If its not passed in we default to localStorage. It could look something like this. This would also make it backwards compatible. Thoughts @tannerlinsley  ?  👀 

```js
const queryClient = new QueryClient({
    defaultOptions: {
      storage: {
        adapter: AsyncStorage,
      },
    },
 });
```

**Comment by delanebob** [comment]
@nbastoWM & @vstlouis, looks like he has updated the persistent storage setup so you can pass in your own based off this tweet 😊

https://twitter.com/tannerlinsley/status/1360380689443483650?s=21

**Comment by vstlouis** [comment]
Sweeeeet, thanks :D

**Comment by vstlouis** [comment]
> @nbastoWM & @vstlouis, looks like he has updated the persistent storage setup so you can pass in your own based off this tweet 😊
> 
> https://twitter.com/tannerlinsley/status/1360380689443483650?s=21

Thank you ! much appreciated

**Comment by TkDodo** [comment]
closing this as you should now be able to implement your own persistor
