### ISSUE TITLE
usePaginatedQuery sometimes returns status = loading, data = undefined after initial query

### ISSUE THREAD

**Issue by episode17** [tannerlinsley/react-query#169]
I'm updating our app to 1.x, and I've noticed an issue with usePaginatedQuery.  I'm using it within the context of a filter, as you type it re-queries, however if I really go at it on my keyboard, sometimes I get a blip of status = loading. I was able to make it disappear by adding the following check:

```js
if (typeof latestData !== 'undefined' && status === 'success') {
  lastDataRef.current = latestData;
}
```
at

https://github.com/tannerlinsley/react-query/blob/b1b9ddc4961f029837ffc7b3c19af13ea3f040e1/src/usePaginatedQuery.js#L23-L25

I don't have much insight into the lib, but maybe this could help

**Comment by tannerlinsley** [comment]
Would you be able to show me this error in a codesandbox setup? That will help me make sure we're solving the problem in the right place.

**Comment by episode17** [comment]
I've setup a very minimal example here: https://codesandbox.io/s/react-queryissues169-9i7t9

It seems as if I trigger 2 uncached queries within the 1000ms window, the status returns to loading

**Comment by tannerlinsley** [comment]
Released!
