### ISSUE TITLE
disabled useQuery populates cache

### ISSUE THREAD

**Issue by henrikq** [tannerlinsley/react-query#1693]
**To Reproduce**
https://codesandbox.io/s/bold-cloud-el0zd?file=/src/App.js

**Expected behavior**
an emtpy cache

**Actual behavior**
cache has 1 entry

**Desktop (please complete the following information):**
 - OS: linux
 - Browser: firefox
 - Version: 84

**Comment by TkDodo** [comment]
I think this is per design and not really something to worry about :)
