### ISSUE TITLE
persistWithLocalStorage - Failed to execute 'setItem' on 'Storage'  REACT_QUERY_OFFLINE_CACHE exceeded the quota

### ISSUE THREAD

**Issue by cliffordfajardo** [tannerlinsley/react-query#1701]
**Describe the bug**
After loading our app and browsing our a few pages (which make useQuery calls) we get a `localStorage` error.

```
Uncaught DOMException: Failed to execute 'setItem' on 'Storage': Setting the value of 'REACT_QUERY_OFFLINE_CACHE' exceeded the quota.
```

These are the options I am using for the query config, essentially using [defaults options](https://react-query.tanstack.com/plugins/persist-localstorage#options) where throttleTime is `1000` 

```ts
const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      useErrorBoundary: true,
      refetchOnWindowFocus: false,
      cacheTime: 1000 * 60 * 60 * 24,
    },
  },
});
persistWithLocalStorage(queryClient); 
```

**To Reproduce**
1. Use the app with [persistWithLocalStorage](https://react-query.tanstack.com/plugins/persist-localstorage#usage) enabled

**Expected behavior**
Should't error, we may need a new default value for the throttle time in options

**Screenshots**
![image](https://user-images.githubusercontent.com/6743796/106076497-8370db00-60c4-11eb-819d-bf647d191b18.png)

**Comment by cliffordfajardo** [comment]
**UPDATES** & follow up comment

This error `Uncaught DOMException: Failed to execute 'setItem' on 'Storage': ` occurs when attempting to write data when localStorage if full. 


## Proposed Ideas for Solutions
When we get the exception from localStorage, inside the `catch` block, perhaps we provide different cache evication options for the user
- option1: empty the `react-query`'s localStorage completely
- option2: evict the oldest entry(s) in react-query's localStorage, until we have space AKA no thrown exception ... (LRU eviction strategy)


```ts
 try {
     var count = 100;
     var message = "LocalStorageIsNOTFull";
     for (var i = 0; i <= count; count + 250) {
         message += message;
         localStorage.setItem("stringData", message);
         console.log(localStorage);
         console.log(count);
     }
 }
 catch (e) {
     console.log("Local Storage is full, Please empty data");
     /* you can handle error here 🔵
       - option: empty local storage?
       - option: evict the oldest entry(s) until we have space AKA no thrown exception ... (LRU eviction strategy)
    */
 }
```

**Comment by tannerlinsley** [comment]
FYI, we have a new architecture for persistence happening in #1789

**Comment by tannerlinsley** [comment]
I would gladly accept a PR to catch "full" storage errors and evict oldest queries (LRU-style).

**Comment by morijenab** [comment]
@tannerlinsley  Do you have any hint on how to get the oldest query?  if it implemented already please address the file or it should be implemented from scratch?

**Comment by TkDodo** [comment]
> Do you have any hint on how to get the oldest query?

Each query has an `dataUpdatedAt` timestamp, which indicates when it was last fetched (successfully). Erroneous queries have an `errorUpdatedAt` timestamp instead. Might not be so good with disabled queries though, because they are in `idle` state and will have `0` there (or queries which are currently fetching for the first time).

Also, internally, the `QueryCache` not only has a `queriesMap` for access via the hashed query key, but also an `Array` of `queries` - which has the order of when a query was first created:

https://github.com/tannerlinsley/react-query/blob/e42cbc32dfcd9add24cadd06135e42af1dbbc8ad/src/core/queryCache.ts#L72-L73
