### ISSUE TITLE
Getting a `No QueryClient set` error for `.test` files even though it is set  

### ISSUE THREAD

**Issue by pdevito3** [tannerlinsley/react-query#1711]
**Describe the bug**
I'm working on adding RQ into an existing project, and started getting an `Error: Uncaught [Error: No QueryClient set, use QueryClientProvider to set one]` error when running tests. 

To be clear, I *do* have my app surrounded in a `QueryClientProvider` and RQ is working just fine when I run the app. 

```jsx
    return (
        <QueryClientProvider client={queryClient}>
            <LinkManager links={props.links}>
                <Layout {...props} />
                <ReactQueryDevtools initialIsOpen={false} />
            </LinkManager>
        </QueryClientProvider>
    );
```
The problem is that, when i run `npm run test`, some of our tests fail due to the error. Do I need to add the provider to my tests somehow as well? I've added the error details and an example test that's failing below.

I'm guessing it has something to do with my enzyme setup? I'm not sure why though as I'm not running any tests with RQ. I've tried this:
```js
import Enzyme from 'enzyme';
import Adapter from 'enzyme-adapter-react-16';
import { QueryClient } from 'react-query';
const queryClient = new QueryClient();

Enzyme.configure({ adapter: new Adapter() });
Object.values = (obj) => Object.keys(obj).map(key => obj[key]);
maestroStrings.LastUpdatedOn = { format: jest.fn() };

beforeAll(() => {
    console.error = error => {
        throw new Error(error);
    };
});

beforeEach(() => {
    expect.hasAssertions();
    queryClient.clear();
});
```

**To Reproduce**
Run `npm run test` some of our tests fail due to the error.

**Expected behavior**
When running `npm run test` they should run as normal and not fail due to a RQ issue that they don't touch

**Screenshots**
```
 FAIL  src/components/Page/HierarchyZone.test.js (8.438s)
  HierarchyZone
    × renders with an filter container (153ms)

  ● HierarchyZone › renders with an filter container

    Error: Uncaught [Error: No QueryClient set, use QueryClientProvider to set one]

       8 | beforeAll(() => {
       9 |     console.error = error => {
    > 10 |         throw new Error(error);
         |               ^
      11 |     };
      12 | });
      13 | 
```

```js
import React from "react";
import { mount } from "enzyme";
import HierarchyView from "../HierarchyView/HierarchyView";
import HierarchyZone from "./HierarchyZone";
import Zone from "./Zone";
import { setGlobalDom } from "../../testutil/TestDOMSetup";

const props = {placeholder};

const mountedHierarchyZone = () => {
    return mount(<HierarchyZone {...props} />);
};

beforeEach(() => {
    maestroStrings = {
        Portal_HierarchyFind_Description: ""
    };

    setGlobalDom();
});

describe("HierarchyZone", () => {

    it("renders with an filter container", () => {
        const component = mountedHierarchyZone();
        const zone = component.find(Zone);
        expect(zone.find(HierarchyView).length).toBeGreaterThan(0);
    });

});
```

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: N/A
 - Version: [e.g. 22]

**Smartphone (please complete the following information):**
N/A

**Comment by pdevito3** [comment]
It looks like I can do something like this (add the provider to the mount line) and it will pass, but doing this for all my tests is far from ideal. Is there any way to do this globally?

```jsx
import React from "react";
import { mount } from "enzyme";
import HierarchyView from "../HierarchyView/HierarchyView";
import HierarchyZone from "./HierarchyZone";
import Zone from "./Zone";
import { setGlobalDom } from "../../testutil/TestDOMSetup";
import { QueryClient, QueryClientProvider } from 'react-query';
const queryClient = new QueryClient();

const props = {
    zone: {
        width: "100",
        height: "100",
        topLeftX: "00",
        topLeftY: "0",
        displayName: "Task Grid",
    },
    controlProps: {
        controlType: 8,
        hierarchyId: null,
        subjectId: null,
        relationshipId: null,
        hierarchyName: "HierarchyName"
    }
};
jest.mock("../../common/DialogUtilities", () => {
    return {
        DialogUtilities: {
            setResizable: jest.fn(),
            destroyResizable: jest.fn(),
            getSimpleId: jest.fn().mockReturnValue("001")
        }
    };
});

const mountedHierarchyZone = () => {
    return mount(<QueryClientProvider client={queryClient}><HierarchyZone {...props} /></QueryClientProvider>);
};

beforeEach(() => {
    maestroStrings = {
        Portal_HierarchyFind_Description: ""
    };

    setGlobalDom();
});

describe("HierarchyZone", () => {

    it("renders with an filter container", () => {
        const component = mountedHierarchyZone();
        const zone = component.find(Zone);
        expect(zone.find(HierarchyView).length).toBeGreaterThan(0);
    });

});
```

**Comment by pdevito3** [comment]
best answer so far from discord:

a wrapper around mount rather than a wrapper around your component might be possible:

 ```js
const mountWithQueryClient = (component) => mount(<QueryClientProvider client={new QueryClient()}>{component}</QueryClientProvider>)

 ```

you could then import that instead of mount , but it would still mean touching all your tests :/

**Comment by ambewas** [comment]
@pdevito3 did you ever find a better solution to this? We're in the process of migrating as well, and every single component test that uses react-query now needs a <QueryClientProvider> component as well. 

This upgrade simply breaks all the tests.. is there a better solution than simply going through all the spec and wrapping our test components?

**Comment by pdevito3** [comment]
I didn't find a better solution unfortunately. I had to manually go to many of my tests and change the mount reference. 

If you're lucky, you might be able to make the new mount wrapper export as `mount` and then just do a global find and replace for the enzyme mount imports. This didn't work for me either though as it didn't break all the tests with mount, just some of them. Still not sure why.

**Comment by ambewas** [comment]
Thanks ~ I'm going to go ahead with a general testwrapper component that just provides the context.
