### ISSUE TITLE
When placeholderData is set, initial status is success

### ISSUE THREAD

**Issue by eedv** [tannerlinsley/react-query#1712]
**Describe the bug**
When placeholderData is set, initial status is success

**To Reproduce**
Example: https://codesandbox.io/s/react-query-placeholder-data-h7hz4?file=/src/App.js

**Expected behavior**
From documentation is not clear if this is expected behavior. I understand the initial status `success` using `initialData` because is persisted in the cache, but if I have partial data to show I still need to know if the rest of it is loading

**Smartphone (please complete the following information):**
any platform 

**Additional context**
I'm starting to migrate an app from redux-saga to react-query and is really wonderful 
Thanks

**Comment by tannerlinsley** [comment]
This is by design. If you need to use placeholder data while the query is loading, simply default your data variable to whatever you want:

```js
const query = useQuery(...)
const data = query.data ?? defaultData
```

**Comment by tannerlinsley** [comment]
Also, you can still know if the query is fetching by using the `query.isFetching` property.

**Comment by nerdess** [comment]
@eedv here is an example if you (or anyone else that comes acress this problem) is using useQuery with destructuring and needs a default value:

```
     const {
       isLoading: chartLoading,
       error: chartError,
       data: chart = []       //chart will be an empty array until the request returns a result
     } = useQuery('barchart', api.barchart);
```

**Comment by mchasaegh** [comment]
so if network request fails, will we still get placeholder/initialData in `data`?

**Comment by TkDodo** [comment]
> so if network request fails, will we still get placeholder/initialData in data?

here is an extensive read about placeholderData, initialData and the differences between them: 

https://tkdodo.eu/blog/placeholder-and-initial-data-in-react-query

**Comment by mchasaegh** [comment]
Thanks @TkDodo, I actually came across your blog but looked at Error Handling 

My issue was/is that my initialData was coming from an async fn, so the initial request gets `undefined` for `initialData` and thus when it fails, it fails with `undefined` for `data`.

i don't want to do `{...result, data: result.data ?? initDataFromAsync }` but it seems the only way :\

**Comment by TkDodo** [comment]
setting the queryKey shouldn't be needed. here is an example of async initialData done with dependent queries:

- https://github.com/tannerlinsley/react-query/discussions/1288#discussioncomment-129114

**Comment by mwmcode** [comment]
Thanks @TkDodo 
Just FYI, setting `queryKey` seems to be needed here. Even in [dependent queries example](https://react-query.tanstack.com/guides/dependent-queries) the 1st query is causing a change in the `queryKey` of the subsequent one. (once the 1st is resolved, its result (userId) is used in the `queryKey` of the 2nd query)

**Comment by mareksuscak** [comment]
> This is by design. If you need to use placeholder data while the query is loading, simply default your data variable to whatever you want:
> 
> ```js
> const query = useQuery(...)
> const data = query.data ?? defaultData
> ```

I might be in the minority, but this is super counterintuitive to me. It seems that there's a general confusion around how this works and the expectation that provided the `placeholderData`, the query should start with a `loading` state. To me, placeholder data should semantically work exactly as the example above. It's even more confusing in Typescript where providing the `initialData` removes the `loading` option from the `status` field but the `placeholderData` doesn't. 

I agree that if the `initialData` is provided, the query should be successful from the get go. That's what I would use if I have the initial data at page load time and I can hydrate the page immediately without waiting. However, intuitively, placeholder data is typically only used to eliminate the need to add a lot of if conditions to account for nulls and undefineds. It feels right to use `loading` as the initial state for this case.

**Comment by TkDodo** [comment]
> and the expectation that provided the placeholderData, the query should start with a loading state. 

`loading` state is used to describe and discriminate the `data` property. When you are in `loading` state, you cannot, per definition, have `data`. It is defined as:

```
status: 'loading',
data: undefined,
error: null
```

`success` state merely means that we have `data`. That is why you are in `success` state when you provide `placeholderData`.

> I'd argue that if queries with placeholderData started with a loading state, the user can still decide whether they display the loading state based on the loading status or the fetching status, or no?

You can still do that by checking for the `isPlaceholderData` flag returned from `useQuery`.

> placeholderData currently feel a little redundant and I don't have a good understanding of when it's useful.

I've written about the differences (and similarities) to `initialData` here: https://tkdodo.eu/blog/placeholder-and-initial-data-in-react-query

**Comment by mareksuscak** [comment]
> You can still do that by checking for the isPlaceholderData flag returned from useQuery.

I didn't know that. Thank you. I guess we could use this flag instead or in addition to the loading flag to display content placeholders. I wonder if this should be mentioned in the description of `placeholderData` flag.

**Comment by TkDodo** [comment]
Good idea, do you want to contribute that?

**Comment by dart200** [comment]
the [docs](https://tanstack.com/query/v3/docs/react/reference/useQuery) say:

> If set, this value will be used as the placeholder data for this particular query observer **while** the query is still in the loading data and no initialData has been provided.

**Comment by TkDodo** [comment]
The query is in loading state but your observer goes to success state because it shows placeholder data
