### ISSUE TITLE
{keepPreviousData : true} does not keep the previous data

### ISSUE THREAD

**Issue by hypo-thesis** [tannerlinsley/react-query#1721]
`{keepPreviousData : true}` fails to keep the previous data and refetches and replaces the old data with the new one.

**Expected behavior**
I expect this option to keep the old data and the new API call results to the already existing data.

```
const fetchData = async ({queryKey : [key , offset]}) => {
  
  return (await fetch(`http://jservice.io/api/clues?offset=${offset}`)).json()
}

function App() {
  const [state, setState] = React.useState(10);
  const {isLoading, error, data , } = useInfiniteQuery (['general' , state], fetchData , {keepPreviousData : true} )

  
  setTimeout(() => {
    setState(20)
  }, 4444);

  console.log(data)
  return (
    <div className="App">
      h
    </div>
  );
}
```

![res](https://user-images.githubusercontent.com/28728305/106448825-55a8df00-6494-11eb-8a40-134f517902dd.jpg)

**Comment by boschni** [comment]
The purpose of the `keepPreviousData` property is to keep displaying the previous query data while switching queries until the new query data has been loaded. You probably don't need that option in your case. If you want to load a next page you need to use the `fetchNextPage` function: https://react-query.tanstack.com/guides/infinite-queries .
