### ISSUE TITLE
useIsFetching "useEffect cleanup function." error

### ISSUE THREAD

**Issue by lukasa1993** [tannerlinsley/react-query#1724]
https://github.com/tannerlinsley/react-query/blob/ac342e237ae9fab6759f2d7be616662da6c16225/src/react/useIsFetching.ts#L37

probably needs some cleanup here

```
This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
```

this is printed when i use `useIsFetching`

![Screen Shot 2021-02-02 at 12 04 05](https://user-images.githubusercontent.com/1499012/106570025-ca405400-654e-11eb-93fb-c816dfe5498c.png)

**Comment by TkDodo** [comment]
`subscribe` returns a cleanup function, which is in turn returned from the `useEffect`.

**Comment by lukasa1993** [comment]
@TkDodo yea i saw that but it still errors out i added log screenshot it say useIsFetching.js:24

**Comment by lukasa1993** [comment]
my guess is instead 
```
React.useEffect(function () {
    return
```
must be
```
 React.useEffect(queryClient.getQueryCache().subscribe(notifyManager.batchCalls(function () {
```

so that subscribe cleanup works but its wild guess haven't tested it
