### ISSUE TITLE
Set `exact=true` as default

### ISSUE THREAD

**Issue by PepijnSenders** [tannerlinsley/react-query#1725]
**Describe the bug**

We were seeing some mixed data on our live servers and then noticed the `.exact` filter param.

Imagine having user data (luckily not in our case) server-side, `const queryKey = ['userInfo', { locale: 'en-US', userId: 1337 }]`. Now if one of these queries expires server-side and you want to get the data by using a function like `.getQueryState(['userInfo', { locale: 'en-US', userId: 1338 }])`, this query could return someone else's data. I think `.exact` should be the absolute default. If someone wants to do a loose lookup this can be optional.

This piece of code: https://github.com/tannerlinsley/react-query/blob/861faf933b610343f04661dcd62b421ef1439bf6/src/core/utils.ts#L245. Will return the other user because `.locale` is the same in both param objects.

**Expected behavior**
`.exact` to be `true` on filter params by default.

**Comment by PepijnSenders** [comment]
We used to use `getQueryData` before using `getQueryState` (which is nicer btw, thanks for that API).

As you can see in v2 `getQueryData` has `.exact=true`:

https://github.com/tannerlinsley/react-query/blob/e1970b750623d224b18bd3f6be034d8f78168214/src/core/queryCache.ts#L204

This has also been removed in v3:

https://github.com/tannerlinsley/react-query/blob/861faf933b610343f04661dcd62b421ef1439bf6/src/core/queryClient.ts#L105

But there is no mention at all about this in the [migration docs](https://react-query.tanstack.com/guides/migrating-to-react-query-3).

**Comment by PepijnSenders** [comment]
I'm trying to see how I can make it fail as it did for us on the live servers, and it seems a bit harder than I expected.

This is in basic terms what happens:

```ts
import { QueryClient } from "react-query";
import { QueryState } from "react-query/types/core/query";

const filterState = (state: QueryState) => {
  return {
    ...state.data as object,
    result: 'b'
  };
}

(async () => {
  const client = new QueryClient();

  await client.prefetchQuery(
    ["test1", { param1: "a", param2: "b" }],
    async () => Promise.resolve({ result: "a" }),
    { staleTime: 90000, cacheTime: 90000 }
  );

  const state = client.getQueryState([
    "test1",
    { param1: "a", param2: "b" },
  ]);

  if (!state) {
    throw new Error();
  }

  client.setQueryData(["test1", { param1: "a", param2: 'b', filtered: true }], filterState(state));

  console.log(client.getQueryData(['test1', { param1: 'a', param2: 'b', filtered: true }]));
})();
```

For some reason the `["test1", { param1: "a", param2: "b" }]` queryKey became the `["test1", { param1: "a", param2: 'b', filtered: true }]` queryKey, and this was fixed by adding `.exact=true`.

**Comment by PepijnSenders** [comment]
Also this entire function:

https://github.com/tannerlinsley/react-query/blob/1032804426f8db2ca3239b601914accbc4c1ddee/src/core/utils.ts#L233

It kind of sounds like that the object match is only partial.

**Comment by PepijnSenders** [comment]
I see that it only matches the params of the queryKey filter that have been provided and I think the following happened in our use-case:

1. Query has been prefetched with `['configuration', { country: 'US', locale: 'en-US', project: 'website' }]`

The query list looks like this: 

- `QueryA { country: 'US', locale: 'en-US', project: 'website' }`

2. Next we set a filtered version of this query like with `['configuration', { country: 'US', locale: 'en-US', project: 'website', filteredFor: 'pageA' }]`

The query list looks like this: 

- `QueryA { country: 'US', locale: 'en-US', project: 'website' }`
- `QueryB { country: 'US', locale: 'en-US', project: 'website', filteredFor: 'pageA' }`

Some time passes and the staleTime of the first query passes as well and `this.queries` now looks like this:

- `QueryB { country: 'US', locale: 'en-US', project: 'website', filteredFor: 'pageA' }`
- `QueryC { country: 'US', locale: 'en-US', project: 'website' }`
- `QueryD { country: 'US', locale: 'en-US', project: 'website', filteredFor: 'pageB' }`
- `QueryE { country: 'US', locale: 'en-US', project: 'website', filteredFor: 'pageC' }`

Now when someone runs:

```ts
client.getQueryState({ country: 'US', locale: 'en-US', project: 'website' });
```

It will return `QueryB` where `QueryC` was expected.

**Comment by PepijnSenders** [comment]
The following script illustrates the same thing:

```ts
const client = new QueryClient();

client.setQueryData(['test', { param1: 'a', param2: 'b' }], 'test1');
client.setQueryData(['test', { param1: 'a' }], 'test2');

console.log(client.getQueryData(['test', { param1: 'a' }]));
```

My initial example was definitely incorrect. yet this implementation of the partial match might still give people very confusing results. Furthermore, this changed from v2 to v3 without a notion in the migration docs.

**Comment by Akram-Adel** [comment]
@PepijnSenders Partial matching is mentioned in the [docs](https://react-query.tanstack.com/guides/query-keys#query-keys-are-hashed-deterministically)

> Query Keys are hashed deterministically!
This means that no matter the order of keys in objects

Why don't you have the query key as an array only? see if it solves the problem

**Comment by PepijnSenders** [comment]
The order of course doesn't matter. But if you keep one part of the object param out it will break. `.exact=true` fixes this (which was the behaviour before v3 was launched).

**Comment by TkDodo** [comment]
> The following script illustrates the same thing:
> 
> ```ts
> const client = new QueryClient();
> 
> client.setQueryData(['test', { param1: 'a', param2: 'b' }], 'test1');
> client.setQueryData(['test', { param1: 'a' }], 'test2');
> 
> console.log(client.getQueryData(['test', { param1: 'a' }])); // "test1"
> ```
> 
> My initial example was definitely incorrect. yet this implementation of the partial match might still give people very confusing results. Furthermore, this changed from v2 to v3 without a notion in the migration docs.

I would have also only expected array elements to be affected by the partial query matching. The example you gave now is a great indication of that. However, these are two different issues to me:

1) is that how partial query matching is supposed to work? If not, fixing it could fix your issue. 

2) should getQueryData be fuzzy per default or not. Judging from the name (get), I think it  should be exact, while something like `find` could indicate fuzzyness.

@tannerlinsley thoughts?

**Comment by PepijnSenders** [comment]
Agreed on both points @TkDodo. Also mind that this changed from v2 to v3.

**Comment by boschni** [comment]
When looking at the v2 code, methods for single results were exact and methods for multiple results were fuzzy. In v3 all methods behave the same, but it can be argued if this is actually desired. Changing the behavior would be a breaking change though.

**Comment by TkDodo** [comment]
@boschni `getQueryData` was exact in v2 but is now fuzzy in v3, is it not?

**Comment by boschni** [comment]
> @boschni `getQueryData` was exact in v2 but is now fuzzy in v3, is it not?

Yes `getQueryData` is one of the methods that operate on a single result (opposed to `invalidateQueries` for example).

**Comment by TkDodo** [comment]
Ah, I just re-read your message: 

>  In v3 all methods behave the same

I thought you meant "behave the same as before", but you meant "behave the same" as in: they are now all fuzzy :)

regarding the breaking change: for `getQueryData` one could argue that this was an unintentional regression introduced in v3, because it is really not mentioned anywhere, then we could "revert" that as a patch. But the open PR (https://github.com/tannerlinsley/react-query/pull/1728) does too much I believe

**Comment by boschni** [comment]
Yeah I see how it can be interpreted in different ways :) We could change the `queryCache.find` method be be exact by default, just hope it does not break applications... The current PR also changes the behavior of methods like `invalidateQueries` which we do not want.

**Comment by TkDodo** [comment]
Hm, I would keep `queryCache.find` fuzzy and only make `queryClient.getQueryData` as well as `queryClient.getQueryState` exact per default. something like:

```diff
  getQueryData<TData = unknown>(
    queryKey: QueryKey,
    filters?: QueryFilters
  ): TData | undefined {
-    return this.queryCache.find<TData>(queryKey, filters)?.state.data
+    return this.queryCache.find<TData>(queryKey, { exact: true, ...filters })?.state.data
  }
```

This would be a minimal invasive change to revert back to the v2 behaviour. It could be communicated as: a `getXXX` function is exact because it's a getter, while `findXXX` and other functions are fuzzy.

**Comment by boschni** [comment]
Think the impact is around the same as the find method is only used by those two methods. It's more that you could also have a method like "invalidateQuery", would it then be exact or fuzzy? If we say: methods for single queries are exact and methods for multiple queries are fuzzy then it would be applicable to any method regardless of the name?

**Comment by TkDodo** [comment]
> Think the impact is around the same as the find method is only used by those two methods.

k, then changing it on `find` would be fine by me.

> It's more that you could also have a method like "invalidateQuery"

good question. I'd agree that "single" methods should be exact, and "multiple" methods could be fuzzy, regardless of the name 👍 

---

quick question: Given that I have these two queries mounted:

```
// list query
useQuery(['todos'], () => fetchTodos())

// detail query
useQuery(['todos', id], (id)=>fetchTodo(id)) 
```

if I do:

```
queryClient.getQueryData(['todos'])
```

is it guaranteed that I always get the list query back? will I get `undefined` if i have no list query in the cache, but a couple of detail queries?

**Comment by PepijnSenders** [comment]
Thanks for taking this over everyone! I was on vacation so not trying to look at GitHub :), I totally agree with the final decision.

**Comment by dseipp** [comment]
Docs should be updated to match this breaking change.  Thanks.
[](https://react-query.tanstack.com/reference/QueryClient#queryclientrefetchqueries)

**Comment by TkDodo** [comment]
Imo there was no breaking change. refetchQueries is still fuzzy. In v2, getQueryData was exact, and in v3 it became fuzzy. This was not documented, and likely a bug. Now it’s fixed and works the same as in v2.
