### ISSUE TITLE
Query is executed when executing a mutation

### ISSUE THREAD

**Issue by tobias-tengler** [tannerlinsley/react-query#1744]
**Describe the bug**
I was trying out the latest version of react-query today with Suspense (no CM) and noticed that every time I was executing a mutation it would re-execute the query. Is this how it's supposed to work? I thought you would have to invalidate the query yourself in one of the mutation's event handlers!?

**To Reproduce**
1. Open the following [Code Sandbox](https://codesandbox.io/s/billowing-field-bpews?file=/src/index.js).
2. Click the 'Add' button.
3. Check the console: fetchTodos was called twice before executing the `onMutate` event handler. (The first call is the actual query of course)

**Expected behavior**
Query does not re-execute before the `onMutate` handler is called.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Chromium
 - Version: 87

**Comment by boschni** [comment]
Seems to be working like expected in the sandbox. Sure the double fetch is not because of `refetchOnWindowFocus`?

**Comment by TkDodo** [comment]
can confirm it's working, and it's very likely the `refetchOnWindowFocus`, as this also happens when you "come back" with focus from the browser devtools
