### ISSUE TITLE
isLoading always false and status always success

### ISSUE THREAD

**Issue by irsyaadbp** [tannerlinsley/react-query#1753]
**Describe the bug**
Hello i use useInfiniteQuery in react native and i want to use isLoading or status for conditional for my skeleton, but why isLoading always return false and status always return success. you can see my screenshot

**Screenshots**
this is my code
![image](https://user-images.githubusercontent.com/23293993/107114104-ed903980-6895-11eb-9348-33064c4d3915.png)

and this is my console log
![image](https://user-images.githubusercontent.com/23293993/107114113-03056380-6896-11eb-84c0-0e4f48730f17.png)

**Comment by boschni** [comment]
Think this is because of the usage of `placeholderData`. A similar issue was created a few days ago: https://github.com/tannerlinsley/react-query/issues/1712 . Maybe the documentation should be made more clear @tannerlinsley?

**Comment by TkDodo** [comment]
When setting `placeholderData`, the query will be in success state immediately with that data, and the `isPlaceholderData` flag will be true. Also, `isFetching` Will be true for every outgoing request. You can use any of these to show a background loading indicator.

**Comment by irsyaadbp** [comment]
Oh i see, it means if I want conditional rendering for my onLoading data my code looks like?
``` isLoading? kendaraanDashboard : data```

**Comment by TkDodo** [comment]
If you want a loading spinner while you are loading, why use placeholderData? placeholderData is usually used to show data _instead_ of a loading indicator.

**Comment by irsyaadbp** [comment]
> When setting `placeholderData`, the query will be in success state immediately with that data, and the `isPlaceholderData` flag will be true. Also, `isFetching` Will be true for every outgoing request. You can use any of these to show a background loading indicator.

if i use isFetching for conditional, everytime I trigger fetchNextPage, isFetching is also affected, and I don't want that

**Comment by irsyaadbp** [comment]
> If you want a loading spinner while you are loading, why use placeholderData? placeholderData is usually used to show data _instead_ of a loading indicator.

this is my code, cause i handle loading in my item for looping the data, then if isLoading true, the flatlist loop my dummy data (placeholder data) and if isLoading false, the flatlist looping the real data
![image](https://user-images.githubusercontent.com/23293993/107115043-6db99d80-689c-11eb-8c10-129eb514778d.png)

**Comment by ellamurii** [comment]
Hello @TkDodo I'm wondering if there's any other workaround instead of using isFetching?
In my case, the child component will trigger a refetch .. and the loading spinner should not show based on that refetch. That is why the isLoading flag should be used... isLoading always returns false when I put in placeholderData or initialData ..

**Comment by noahehall** [comment]
Should have started my googel search about an hour ago! definitely recommend calling this out in the docs

**Comment by Akash187** [comment]
@noahehall I am also suffering from the same issue when `enabled=false` isLoading is true. Ideally, this should not happen.

**Comment by LucasAndrad** [comment]
I am having the same issue as @Akash187 😞

**Comment by Akash187** [comment]
Hey, @LucasAndrad I am using [isInitialLoading](https://tanstack.com/query/v4/docs/react/guides/disabling-queries#isinitialloading) as a workaround.

**Comment by bombillazo** [comment]
Dang! `enabled=false` with isLoading is so unintuitive! I also tried `isInitialLoading` with enabled but nope. I had to remove the enabled for it to work.
