### ISSUE TITLE
Query function called twice when query keys are updated

### ISSUE THREAD

**Issue by lukaszfiszer** [tannerlinsley/react-query#176]
Query function is called twice when query keys are updated - first time with old keys, then with new one.

A minimal repro can be found here: https://codesandbox.io/s/react-query-keys-bug-u8d8i. Click "Update", then observe console

**Comment by cherniavskii** [comment]
This is because queries are refetching on focus by default.
When you click on that button for the first time, query is refetched (with current variable) and then variable changes, which trigger refetch.
So it works as expected.

**Comment by cherniavskii** [comment]
Here's same example with `refetchOnWindowFocus` set to `false` - https://codesandbox.io/s/react-query-keys-bug-1yt1q

**Comment by lukaszfiszer** [comment]
Yeah, that make sense
