### ISSUE TITLE
Unsafe SSR-pattern described in docs and example

### ISSUE THREAD

**Issue by Ephem** [tannerlinsley/react-query#1762]
[The SSR docs on hydration](https://react-query.tanstack.com/guides/ssr#using-hydration) currently describe an unsafe pattern:

```jsx
// _app.jsx
 import { QueryClient, QueryClientProvider } from 'react-query'
 import { Hydrate } from 'react-query/hydration'
 
 // ---- THIS IS THE PART THAT IS UNSAFE ----
 const queryClient = new QueryClient()
 
 export default function MyApp({ Component, pageProps }) {
   return (
     <QueryClientProvider client={queryClient}>
       <Hydrate state={pageProps.dehydratedState}>
         <Component {...pageProps} />
       </Hydrate>
     </QueryClientProvider>
   )
 }
```

Creating a client (and behind the scenes a cache) in the module scope will mean that cache is shared between all requests on the server which is unsafe since it can leak sensitive data between requests.

[The Next.js example](https://github.com/tannerlinsley/react-query/blob/0b8c55c3a6f4a9e12a33ec828bc415c77679cf8b/examples/nextjs/pages/_app.js#L6) uses the same pattern and should also be updated.

The correct way to create the client for SSR is to do it on the initial render and save it in state/on a ref (for reference, this was done automatically in the QueryCacheProvider in React Query v2 if no queryCache was provided).

I wont have time to submit a fix for this myself in the near future, so if someone wants to submit a PR with an update that would be much appreciated!

**Comment by tannerlinsley** [comment]
I’ll take care of this.

Tanner Linsley
