### ISSUE TITLE
setLogger makes core functionality silently fail when not set up correctly

### ISSUE THREAD

**Issue by damoberg** [tannerlinsley/react-query#1765]
**Describe the bug**

Then not setting up `setLogger` correctly results in `useMutation` errors failing silently. This might cause failures in other places of the library as well, only discovered/tested with `useMutation`.

```js
setLogger({
  log: {},
  warn: {},
  error: {}
});
```

**To Reproduce**

See codesandbox:  https://codesandbox.io/s/setlogger-bug-2x1jq

Click "Gogo", verify that the error status is never received. If the `setLogger` block is commented out however it will work when reloaded.

**Expected behavior**

Expect the library to not block on `setLogger` being set up incorrectly. Would expect the logging operation to fail but not the root functionality of the library.

Also would expect to see an error logged to the console.

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: chrome
 - Version: 88.0.4324.150

**Comment by TkDodo** [comment]
not sure what exactly is going on here, but this is a question of when to perform runtime checks and when not. The types and the docs clearly state that `log`, `warn` and `error` must be functions, and the library just calls those functions internally. if you set them to something else (null, false, new Date(), ...), it won't work.
