### ISSUE TITLE
Getting long timeout warnings on Android

### ISSUE THREAD

**Issue by lfaz** [tannerlinsley/react-query#1782]
**Describe the bug**
When running app on android with debugger I am getting multiple popup windows that warns about longtime timeout set by react-query library apparently. It seems Android only allows max timeout of 1 min according to their documentation and react query sets some timeout of lifetime of 1h. 

**Expected behavior**
Dont show any of the warnings related to timeout

**Error**

> YellowBox.js:71 Setting a timer for a long period of time, i.e. multiple minutes, is a performance and correctness issue on Android as it keeps the timer module awake, and timers can only be called when the app is in the foreground. See https://github.com/facebook/react-native/issues/12981 for more info.
> (Saw setTimeout with duration 3600000ms)

**Screenshots**
<img width="537" alt="Screen Shot 2021-02-11 at 13 48 59" src="https://user-images.githubusercontent.com/3067071/107633450-b6909e00-6c70-11eb-9c3b-62a730835f27.png">

**Smartphone (please complete the following information):**
 - Device: [Android]
 - OS: [any]

**Additional context**

I am using "react-query": "^2.18.0", for React Native app!

**Comment by dominictwlee** [comment]
@lfaz, This was addressed in a previous closed issue #1259

**Comment by YajanaRao** [comment]
I am trying to cache data by setting cacheTime value to large number. Will caching work even though there is this warning message ?

**Comment by tannerlinsley** [comment]
Please see #1259
