### ISSUE TITLE
ReferenceError: useEffect is not defined

### ISSUE THREAD

**Issue by mbaumbach** [tannerlinsley/react-query#1787]
**Describe the bug**
Runtime error of ReferenceError: useEffect is not defined in `node_modules/react-query/es/devtools/useLocalStorage.js:17`

**To Reproduce**
1. Install 3.9.0
2. Have the devtools component in your hierarchy
3. Open your app in the browser

**Expected behavior**
No errors.

**Desktop (please complete the following information):**
 - OS: All
 - Browser: All
 - Version: All

**Additional context**
Seems to be due to the change in https://github.com/tannerlinsley/react-query/pull/1727

**Comment by mbaumbach** [comment]
I suspect the fix is to simply use `React.useEffect`. I'm a little surprised the CI build and tests passed. That may be a separate issue to investigate.

**Comment by mbaumbach** [comment]
Somewhat related, I think that `useEffect` might be slightly incorrect since the `key` isn't in the dependency array too. Perhaps it should be modeled after the one here: https://usehooks.com/useLocalStorage/

**Comment by mrlubos** [comment]
+1
