### ISSUE TITLE
`useInfiniteQuery` broken on SSR

### ISSUE THREAD

**Issue by klarstrup** [tannerlinsley/react-query#1794]
**Describe the bug**
As of 3.9.0 `useInfiniteQuery` behaves differently during SSR, only returning the request data at `QueryResult.data` rather than each paginated page at `QueryResult.data.pages`. But behaves as documented when rerendered client-side.

**To Reproduce**
Change the current nextjs example to use `useInfiniteQuery` like so: https://github.com/klarstrup/react-query/commit/c2434e563038a7adf9013b30fc916276c3efda3c

I've also written a shoddy little test to confirm the issue: https://github.com/klarstrup/react-query/commit/4f3b37096b8457e742652abab88d4a7b3732ee95

**Expected behavior**
I would expect the query hooks to not behave different between server and client. 

---------

I would hazard a guess that this is fallout from #1775

**Comment by boschni** [comment]
Does version 3.9.3 fix your issue?

**Comment by klarstrup** [comment]
Yeah! That works perfectly - cheers

**Comment by klarstrup** [comment]
Brainfart on my end. The above reproductions still don't work as of 3.9.6

**Comment by vipinnair22** [comment]
I'm seeing similar issue where data is not added in `pages` property and is returned like a response for `useQuery`.

**Comment by boschni** [comment]
This seems to work: https://github.com/tannerlinsley/react-query/commit/2bcc893255818ee2093b6e7889d8b3bdeb612a97

Are you using `prefetchInfiniteQuery` instead of `prefetchQuery`?

**Comment by klarstrup** [comment]
Oh I guess I did use the wrong prefetch method in my test up there. But what I'm experiencing in my real app is with using Suspense-based SSR via `react-ssr-prepass` which worked up until 3.9.0, no prefetch methods.

**Comment by boschni** [comment]
Is it also the case with 3.9.6?

**Comment by klarstrup** [comment]
That seems to do the trick 😁 Yes!
