### ISSUE TITLE
enabled seems to be broken in 3.9

### ISSUE THREAD

**Issue by dusty** [tannerlinsley/react-query#1797]
**Describe the bug**
Somewhere in the 3.9 series enabled seems to be broken and network requests are still made even if enabled returns false.  This problem does not occur in 3.8.3

**To Reproduce**
Steps to reproduce the behavior on 3.9.3
1. Go to https://codesandbox.io/s/eloquent-ellis-dj6c1
2. Open up Network Tab in Dev tools
3. Type a string in the input box, notice the query is made
4. Remove the string from the input box, notice the query is still made with q being empty

Steps to reproduce the correct behavior on 3.8.3
1. Go to https://codesandbox.io/s/naughty-feistel-tzqe7
2. Open up Network Tab in Dev tools
3. Type a string in the input box, notice the query is made
4. Remove the string from the input box, notice no query is made

**Expected behavior**
When enabled is false no network request should be made.

**Screenshots**
3.9.3
![2021-02-13 13 46 49](https://user-images.githubusercontent.com/792/107861309-4d409480-6e02-11eb-97c9-6a1cc9ccc170.gif)

3.8.3
![2021-02-13 13 52 23](https://user-images.githubusercontent.com/792/107861445-ee2f4f80-6e02-11eb-98da-860c4496a045.gif)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Brave 
 - Version: Version 1.20.103 Chromium: 88.0.4324.152 (Official Build) (x86_64)

**Comment by boschni** [comment]
Thanks! Fixed in 3.9.4
