### ISSUE TITLE
useMutation needs two clicks to return data

### ISSUE THREAD

**Issue by DoneDeal0** [tannerlinsley/react-query#1800]
**Describe the bug**
`useMutation` works fine but needs two clicks on a "add" button to return a correct state with `isSuccess` & `data`. 

In the simple example below (see sandbox):
-  I have a basic form to create an user with a name and a job.
- I enter `name: "Jack", job:"farmer"`.
- When clicking on "add",` useMutation` is called, but no `data` nor `success` props are sent. My local state is not updated.
- I click on "add" a second time. The props `data` and `success` are correctly sent. Based on this information, I update my local state correctly. `Jack the farmer` is correctly added to the user list.
- I enter new informations for a second user: `name: "Sandy", job: "waitress"`.
- I click on "add" again. The previous user - `Jack the farmer `- is sent again. **I now have two** `Jack the farmer` **in my list**.
- I click on "add" again. `Sandy the waitress` is finally added. And so on. 

So there is a permanent delay. I think the issue simply comes from my code. How to fix this?

**To Reproduce**
https://codesandbox.io/s/usemutation-test-co7e9?file=/src/App.tsx

**Expected behavior**
A click on "add" immediately adds an user to the list if the api call is a success. Also, it doesn't add the previous user again when I want to add a brand new user.

**Desktop (please complete the following information):**
 - OS: Osx
 - Browser: chrome

**Comment by TkDodo** [comment]
I think you asked the same question on StackOverflow, and I answered it there: https://stackoverflow.com/questions/66194890/how-to-update-react-state-once-usemutation-is-done/66198773#66198773
