### ISSUE TITLE
Only the last onSuccess callback gets called when mutate is used inside of a loop

### ISSUE THREAD

**Issue by Eddie-CooRo** [tannerlinsley/react-query#1827]
**Describe the bug**
I have a use-case where I need to call a Post endpoint for each and every item in an array. I have an `useMutation` hook for the mentioned endpoint, and am using the `mutate` function returned from it in a `forEach` to call the endpoint for every item in a list. every `mutate` call has its own `onSuccess` and `onError` callbacks, and the `useMutation` itself has two main callbacks as well. 

**Expected behavior**
For a three-item list, we should see three `mutate` onSuccess calls, and three `useMutation` onSuccess calls. similar to what happens with `mutateAsync.then`

**Current behavior**
For a three-item list, the `useMutation` onSuccess gets called three times, but the `mutate` onSuccess gets called only once for the latest item in the list.

**To Reproduce**
https://codesandbox.io/s/heuristic-jones-v7zpm  
The above codesandbox demonstrates both the mutate with onSuccess, and mutateAsync with then.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Chrome
 - Version: 88.0.4324.182

**Additional context**
I'll try to look into the code myself to find any possible cause over this weekend. :v: If anyone got the time to jump on it sooner than I do, very appreciated :pray:

**Comment by TkDodo** [comment]
We just had this, see: https://github.com/tannerlinsley/react-query/issues/1573
