### ISSUE TITLE
Getting TypeScript error with useRef

### ISSUE THREAD

**Issue by ghoshnirmalya** [tannerlinsley/react-query#1871]
**Describe the bug**
I'm using **react-query** with **Next.js** and was using the [Hydration method](https://react-query.tanstack.com/guides/ssr#using-hydration). I'm getting the following error:

```bash
Type 'QueryClient' is not assignable to type 'undefined'.ts(2322)
```

**To Reproduce**
In a Next.js application, if you add the following code in **_app.tsx**, you should be able to view the issue:

```ts
import type { AppProps } from 'next/app';
import React, { useRef } from 'react';
import { QueryClient, QueryClientProvider } from 'react-query';
import { ReactQueryDevtools } from 'react-query/devtools';
import { Hydrate } from 'react-query/hydration';

const App = ({ Component, pageProps }: AppProps) => {
  const queryClientRef = useRef();

  if (!queryClientRef.current) {
    queryClientRef.current = new QueryClient(); // The error is thrown on this line
  }

  return (
    <QueryClientProvider
      client={(queryClientRef.current as unknown) as QueryClient}
    >
      <Hydrate state={pageProps.dehydratedState}>
        <Component {...pageProps} />
      </Hydrate>
      <ReactQueryDevtools />
    </QueryClientProvider>
  );
};

export default App;
```

**Expected behavior**
The error shouldn't occur.

**Screenshots**
<img width="591" alt="Screenshot 2021-02-27 at 5 33 37 PM" src="https://user-images.githubusercontent.com/6391763/109386642-ff5b7e80-7921-11eb-89dc-80e7018c3bc6.png">

**Desktop (please complete the following information):**
 - OS: macOS Big Sur
 - Browser: Chrome
 - Version: 88.0.4324.192 

**Additional context**
I'm using react-query and Next.js inside a [Lerna](https://lerna.js.org/) mono-repo.

**Comment by TkDodo** [comment]
So this is just a type error, because you haven't defined what the ref can hold (neither with a default value, nor with a generic). When using refs in TS, you have to define it's type:

```
const queryClientRef = useRef<QueryClient>();
```

then, your `ref.current` will be of type `QueryClient | undefined`. This has nothing to do with react query, that's just how refs work in react.

**Comment by Mozart409** [comment]
Hi, I had the same error and I wanted to contribute this fix to the offical docs site. I did not find it. Can you point me in the right direction @TkDodo @tannerlinsley ? Thanks

**Comment by Mozart409** [comment]
I am talking about this page https://react-query.tanstack.com/guides/ssr#using-nextjs

**Comment by TkDodo** [comment]
not sure what you want you'd want to contribute - the examples are in `js` on purpose, and the ref issue mentioned here has nothing to do with react-query - it's just how `useRef` is typed in typescript 🙃

**Comment by Mozart409** [comment]
@TkDodo I would like to add a line in the Nextjs example "for typescript users use this ...". For convenience, I would like to add it, because more users will trip and fall, and you could circumvent a lot of unnecessary GitHub issues.
