### ISSUE TITLE
Query data not fetched initially when refetchOnMount is false in 3.8.3

### ISSUE THREAD

**Issue by acSpock** [tannerlinsley/react-query#1872]
**Describe the bug**
This seems to still be an issue: https://github.com/tannerlinsley/react-query/issues/896

As the title suggests, when refetchOnMount is false, data is not initially fetched.

**To Reproduce**

1. Open this codesandbox: https://codesandbox.io/s/reverent-cohen-97pgh?file=/src/App.js
2. You can see that the username is not showing up. The service call is not fired.
3. If you now refocus the window it fetches the data as expected.

**Expected behavior**
the query should fetch data when on first execution.

**Browser**
OS: macOS Catalina 10.15.7
Browser: Chrome Version 88.0.4324.192 (Official Build) (x86_64)

**Comment by dominictwlee** [comment]
From the looks of it, you're still using v2.7.0 in your codesandbox example. Maybe try updating to the latest v2 (if you don't want a breaking change), or better yet, bump up to v3?

**Comment by TkDodo** [comment]
Upgrading the codesandbox to `2.26.4`, which is the latest 2.x version, solves the issue:

https://codesandbox.io/s/friendly-kapitsa-k6kd8?file=/src/App.js
