### ISSUE TITLE
A doc of chinese version(a individual repo), for improve influence in chinese community

### ISSUE THREAD

**Issue by cangSDARM** [tannerlinsley/react-query#1881]
This library is very useful, so I want to increase its popularity in the Chinese community, so I opened a Chinese document repo.

Hope this is a good idea to increase the influence of the web and react communities

Also, I hope to extract a separate repo from the website so that the community can provide documentation websites in other languages

repo: https://github.com/cangSDARM/react-query-web-i18n
site: https://cangsdarm.github.io/react-query-web-i18n/
Chinese mirror site: https://alleneyes.gitee.io/react-query-web-i18n

**Of course, if there are any legal, license, or other reasons, I can also delete them immediately **

**Comment by lizy0329** [comment]
芜湖

**Comment by TkDodo** [comment]
Thank you for the effort. I don’t see any issues with it
