### ISSUE TITLE
Document QueryClient({ defaultOptions })

### ISSUE THREAD

**Issue by Svish** [tannerlinsley/react-query#1884]
Not a code bug, but a documentation "bug": The `defaultOptions` you can pass in when creating a `QueryClient` doesn't seem to be documented anywhere. Can _mostly_ be figured out of if using Typescript, but yeah. The following isn't very helpful, without a link to what exactly `DefaultOptions` looks like:

![image](https://user-images.githubusercontent.com/142162/109501954-a2360900-7a98-11eb-8090-77b8358e70d3.png)

The type is currently this:

```ts
export interface DefaultOptions<TError = unknown> {
    queries?: QueryObserverOptions<unknown, TError>;
    mutations?: MutationObserverOptions<unknown, TError, unknown, unknown>;
}
```

So maybe documentation could just cover that and link to `useQuery` and `useMutation` for what `QueryObserverOptions` and `MutationObserverOptions` are (or wherever that's covered)?

**Comment by TkDodo** [comment]
It's actually `QueryClient({ defaultOptions, queryCache, mutationCache })`, all of which are optional. I agree that we can improve on the docs here :)

**Comment by Svish** [comment]
> It's actually `QueryClient({ defaultOptions, queryCache, mutationCache })`, all of which are optional. I agree that we can improve on the docs here :)

If you're referring to the title, yeah, sorry, not the best title. Skipped the ones already kind of clear 😛

**Comment by Svish** [comment]
> would you like to make a PR to update the docs?

Would love to help, but think it would be better for someone who actually know what the options are, and what they do, document the options 😬

**Comment by TkDodo** [comment]
Have a look at the type definitions and take it from there:

https://github.com/tannerlinsley/react-query/blob/f2137dc4e4553256c4ebc1891b548fe35efe9231/src/core/types.ts#L547-L550

feel free to open the PR if you like
