### ISSUE TITLE
queryClient.invalidateQueries doesn't abort request if queryFn is async/await

### ISSUE THREAD

**Issue by formalinfigs** [tannerlinsley/react-query#1893]
`queryClient.invalidateQueries` cannot close request because `query.cancel()` is not available if I use `async/await` inside `queryFn`:

```javascript
const createRequest = (method, url, options) => {
    const source = CancelToken.source();

    const promise = axios({
        method,
        url,
        ...options,
        cancelToken: source.token,
    });

    // Cancel the request if React Query calls the `promise.cancel` method
    promise.cancel = () => {
        source.cancel('Query was cancelled by React Query');
    };

    return promise;
};


export const useAlerts = () => {
    return useQuery('alerts', async () => {
        const { data } = await createRequest('get', 'alerts');

        return data;
    });
};

// cannot access .cancel() because new promise was returned from async queryFn
queryClient.cancelQueries('alerts'); 
```

**Expected behavior**
The request is canceled despite async/await. 

**Additional context**
Did I misunderstand the concept of canceling queries? How can I parse a response inside queryFn, but keep the ability to cancel a request? 

Following example works correctly because promise from `createRequest` has `cancel` field.
```javascript
export const useAlerts = () => {
    return useQuery('alerts', () => createRequest('get', 'alerts');
};
```

**Comment by TkDodo** [comment]
Yes, that is a interesting "gotcha" when using async/await. Even if you return a Promise, it will wrap it in a _new_ Promise.

I think the only solution for that would be to define a totally different approach to query cancellation, which doesn't involve adding a `.cancel` method to the returned promise. There are also typescript related problems, because you cannot attach a `.cancel` method to `Promise` without augmenting the interface or using a type assertion.

as a workaround, I think this should work:

```
export const useAlerts = () => {
    return useQuery('alerts',  () => createRequest('get', 'alerts').then(response => response.data));
};
```

**Comment by andynoster** [comment]
https://codesandbox.io/s/naughty-borg-jn31f?file=/pages/index.js

Cancel doesn't work.
In promise that you are creating you can see we don't have .cancel function in promise.

The second case shows we have cancel but 'then' callback won't be result of promise.

**Comment by TkDodo** [comment]
Yep, I was wrong. .then also creates a new promise (quite logical in hindsight). 

Any ideas how to fix / improve this?

**Comment by andynoster** [comment]
@TkDodo 
Possibly the answer is to have just usual wrapper for promise.

`const wrapCancelPromise = (promise, mapper) => {
    const promise1 = promise.then(mapper);
    const promise1.cancel = promise.cancel;
    return promise1;
}

const createRequest = (method, url, options) => {
    const source = CancelToken.source();

    const promise = axios({
        method,
        url,
        ...options,
        cancelToken: source.token,
    });

    // Cancel the request if React Query calls the `promise.cancel` method
    promise.cancel = () => {
        source.cancel('Query was cancelled by React Query');
    };

    return promise;
};

useQuery('', createCancelPromise(createRequert(method, url, options), ({data}) => { return data }));
`

**Comment by andynoster** [comment]
Possibly the answer is to have just the usual wrapper for your promise.
But I'm not sure it's the best way.

```js
const wrapCancelPromise = (promise, mapper) => {
    const promise1 = promise.then(mapper);
    const promise1.cancel = promise.cancel;
    return promise1;
}

const createRequest = (method, url, options) => {
    const source = CancelToken.source();

    const promise = axios({
        method,
        url,
        ...options,
        cancelToken: source.token,
    });

    // Cancel the request if React Query calls the `promise.cancel` method
    promise.cancel = () => {
        source.cancel('Query was cancelled by React Query');
    };

    return promise;
};

useQuery('', createCancelPromise(createRequert(method, url, options), ({data}) => { return data }));
```

**Comment by phaux** [comment]
What if the queryFn received an [abort signal](https://developer.mozilla.org/en-US/docs/Web/API/AbortController/signal) and used that for cancelling?

With fetch:

```js
useQuery(["todos", todoId], async ({ signal }) => {
  const response = await fetch(`todos/${todoId}`, { signal })
  const data = await response.json()
  return data
}
```

With other APIs you can always do `signal.addEventListener("abort", fn)` which is the same as `promise.cancel = fn`.

**Comment by TkDodo** [comment]
This article also shows a good way how to do it:

https://www.carlrippon.com/cancelling-requests-with-react-query/

- make your queryFn non-async
- there, create a `new Promise` with an async function where you do everything
- on that Promise, stick the `.cancel` method and return it

**Comment by TkDodo** [comment]
here is a working example with the above approach:

https://codesandbox.io/s/recursing-fire-n4jz1
