### ISSUE TITLE
failureCount does not reset when query succeeds

### ISSUE THREAD

**Issue by deevus** [tannerlinsley/react-query#190]
I was hoping to use `useQuery` as a status check to make sure that an API is available. It says in the documentation that `failureCount` should reset to zero when the query succeeds but in my testing that only works if you blur the window and force a full refresh. 

https://codesandbox.io/s/great-pare-0kin0?fontsize=14&hidenavigation=1&theme=dark

**Comment by adibfirman** [comment]
Hello @deevus
your codesandbox is working as well and btw i want to use `failureCount` too as the readme says it will be reset to 0 when a query is succeeds and i am trying to reset it in my PR #191 maybe it could help your issue.

Thanks

**Comment by tannerlinsley** [comment]
Fixed with your PR
