### ISSUE TITLE
Clicking within dev tools triggers event in application

### ISSUE THREAD

**Issue by indignant** [tannerlinsley/react-query#1900]
**Describe the bug**
Hello! I've been learning react-query and think it's neat, however the dev tool has some unexpected behavior. When I have an element on the screen that closes by clicking outside the element and then click within the react-query dev tools, the element I'm working with closes.

**To Reproduce**
1. Have an element that uses something like [useOnClickOutside](https://usehooks.com/useOnClickOutside/)
2. Open the element
3. Click somewhere in react-query dev tools
4. Note the element is now closed

**Expected behavior**
It would be nice if clicks within react-query dev tools didn't propagate into my application. However it would be ideal to be able to separate react-query dev tools from the application all-together. The dev tools take up a lot of real-estate and it would be really nice to have them on a separate screen than my application (maybe as a browser extension like React dev tools or Redux dev tools).

I realize you used to have something like this and [archived the project](https://github.com/tannerlinsley/react-query-devtools), but it seems like a bummer to have such great dev tools and having to choose between seeing my application or seeing the tool. Also having this overlay often prevents me from using my app at all when dev tools are open because the application wasn't built with an overlay in mind.

Sorry, I'm rambling. Your dev tools are super neat though and I would love to be able to have them open all the time (and in a way that doesn't modify my application when I interact with the tool).

**Screenshots**

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: FF
 - Version: 85.0.2

**Smartphone (please complete the following information):**
 - Browser: [e.g. stock browser, safari]
 - Version: [e.g. 22]

**Additional context**
Cool project, excited to be learning it.

**Comment by TkDodo** [comment]
making the devtools a dedicated browser extension seems like a no-go, have a look here for some reasoning (basically, it's hard): https://github.com/tannerlinsley/react-query/discussions/1834#discussioncomment-393989

you can however customize the devtools via css. you can make it floating, resizable etc and then move it wherever you like (within the window)
