### ISSUE TITLE
No way to know if the data was served from cache.

### ISSUE THREAD

**Issue by vipinnair22** [tannerlinsley/react-query#1906]
Currently there's no property in the response object which tells me if the data was served from cache or if it had to execute the queryFn to return the response. 
IIRC, previous version had an `isCached` flag which provided this information. 
I tried to use `isFetched` flag. But it's set to true in both cases.
Is there something in the response object that can be used to determine if the data was served from cache?

**Comment by TkDodo** [comment]
I don’t think so. What do you need it for?
