### ISSUE TITLE
Missing queryFn 

### ISSUE THREAD

**Issue by attiqeurrehman** [tannerlinsley/react-query#1922]
**Describe the bug**
Trying to send a get requests to fetch some appointments within a given interval and getting the error:
> missing queryFn

**To Reproduce**

Following is the custom hook: 
```js
import { useQuery } from "react-query";
import { instance as axios } from '../services/axios';

const getAppointments = async (startDate, endDate) => {
  const { data } = await axios.get(`/appointments/get-interval?calenderViewStartDay=${startDate}&calenderViewEndDay=${endDate}`);
  return data;
};

export default function useAppointments(startDate, endDate) {
  return useQuery('Appointments',getAppointments(startDate, endDate));
}
```
I can see the successful requests on the Network. I couldn't reproduce it on the sandbox. 

**Expected behavior**
Get the query result successfully. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox v86
 - Version: 3.20.1

**Comment by dusty** [comment]
You need to return a function that returns a promise.

eg
```
export default function useAppointments(startDate, endDate) {
  return useQuery('Appointments', () => getAppointments(startDate, endDate));
}
```

**Comment by TkDodo** [comment]
⬆️ that is the correct answer.

in the original example, you invoke the function immediately and return its _result_ to useQuery.
