### ISSUE TITLE
local onError is not working as expected when using global onError on MutationCache

### ISSUE THREAD

**Issue by shubham-sns** [tannerlinsley/react-query#1927]
I have global mutation cache which shows an toast when error occurs, when I am using onError on useMutation it does not show any error in useMutation. this is my current config with global errors setup

```js
const mutationCache = new MutationCache({
  onError(error, variables, context, mutation) {
    if (mutation.options.showToast) {
      console.log("from mutation cache", error.payload.message); // toast
    }
  }
});

const queryCache = new QueryCache({
  onError(error, query) {
    if (query.options.showToast) {
      console.log(error.payload.message); // toast
    }
  }
});

const queryClient = new QueryClient({
  mutationCache,
  queryCache,
  defaultOptions: {
    queries: {
      useErrorBoundary: true,
      refetchOnWindowFocus: false,
      retry(failureCount, error) {
        if (error.statusCode === 404) return false;
        if (failureCount < 2) return true;
        return false;
      },
      showToast: true
    },

    mutations: {
      showToast: true
    }
  }
});
```

```js
 const {mutate: mutateLogin} = useMutation(login, {
    onSuccess: data => {
      login(data.payload)
    },
    onError(error) {
      console.log(error) // this error never logs into console
    },
  })
```

**Expected behavior**
I am expecting that global and local onError method should run

**Codesandbox**
[codesandbox example](https://codesandbox.io/s/laughing-platform-8bz71?file=/src/App.js:207-1127)

**Desktop (please complete the following information):**
 - Windows
 - Browser: Brave
 - Version: [1.21.74]

is there any way to setup __onSuccess__ also in global (I want to show toast when submitted)

**Comment by TkDodo** [comment]
I narrowed it down. seems that passing custom properties like  `mutations: { showToast: true }` to the defaultOptions breaks it. I removed that and it works fine, see:

https://codesandbox.io/s/laughing-wood-vxd05?file=/src/App.js

plase don't do that I guess 😅

**Comment by keemor** [comment]
Hi @TkDodo,

Your CBS still uses showToast flag https://codesandbox.io/s/laughing-wood-vxd05?file=/src/App.js

My global handler shows toast error message.
```js
const onError = (error: unknown) => {
  if (axios.isAxiosError(error)) {
    console.error(error.response);
    toast.error(error?.response?.data?.message || error?.response?.statusText);
  }
};

const queryClient = new QueryClient({
  // https://tkdodo.eu/blog/practical-react-query#the-defaults-explained
  queryCache: new QueryCache({
    onError,
  }),
  mutationCache: new MutationCache({
    onError,
  }),
});
```

But for some mutation I want to handle error in another way.

```js
const { mutate } = useMutation(
    myMutate,
    {
      onError: (error: unknown) => {        
        if (axios.isAxiosError(error)) {
          console.error("My Custom Error handdler");
          console.error(error?.response?.statusText);
        }
      },
    }
  );
```

Both onErrors are fired

So how I can distinct global error handler from local handler to not show toast message?

Cheers :)

**Comment by TkDodo** [comment]
the onError handlers of the global query cache are _always_ called. To define a default that you can override on each useMutation, use the `mutationDefaults`:

```
const queryClient = new QueryClient({
  defaultOptions: {
    mutations: {
      onError
    }
  }
});
```

**Comment by loveholly** [comment]
> ```js
> onError
> ```

This works not as expected on my side because both `onError` handlers triggered.

**Comment by loveholly** [comment]
> the onError handlers of the global query cache are _always_ called. To define a default that you can override on each useMutation, use the `mutationDefaults`:
> 
> ```
> const queryClient = new QueryClient({
>   defaultOptions: {
>     mutations: {
>       onError
>     }
>   }
> });
> ```

This works not as expected on my side because both onError handlers triggered.

**Comment by loveholly** [comment]
Thanks for the quick reply. I mean `onError` handler on `defaultMutationOptions` and `onError` handler on `useMutation` both triggered.

**Comment by TkDodo** [comment]
and I mean this shouldn't be the case, [as I stated before](https://github.com/tannerlinsley/react-query/issues/1927#issuecomment-1135517016). So if it is the case for you, please show it in a codesandbox reproduction.

**Comment by loveholly** [comment]
> and I mean this shouldn't be the case, [as I stated before](https://github.com/tannerlinsley/react-query/issues/1927#issuecomment-1135517016). So if it is the case for you, please show it in a codesandbox reproduction.

Hi @TkDodo , here is the example: https://codesandbox.io/s/aged-framework-pwxtu5?file=/src/App.js

**Comment by loveholly** [comment]
Sorry, maybe it's my fault. I tested a simple example, and it works as I expected. However, it failed as I expected in my real project. I'll figure it out what's going on. Thanks for your help.

**Comment by loveholly** [comment]
Hi @TkDodo , could u please help confirm with this example: https://codesandbox.io/s/aged-framework-pwxtu5?file=/src/App.js:643-748

I'm not sure is this the correct behavior when `onError` passed through `mutate` function won't override the global `onError` handler.
