### ISSUE TITLE
One useQuery with dynamic key/url and staleTime

### ISSUE THREAD

**Issue by phphille** [tannerlinsley/react-query#193]
Hi
I think I have a bit specific use case which I have simplified:
I'am currently wrapping a useQuery hook in a custom hook. This custom hook has a url param which will be used as the url for the request and the query key. But the problem I'am facing is that when I'am setting staleTime other than 0 the useQuery Hook wont execute the second time the url changes. Please see https://codesandbox.io/s/tender-water-k7864 where clicking on "form" button and then "ability" button the it wont update. If I remove the staleTime property it works as I want to but then unnecessary request will be executed.
I'am guessing the staleTime is connected to the Hook instance and not the key?

Thanks for a great tool!

**Comment by tannerlinsley** [comment]
It's working for me! https://codesandbox.io/s/friendly-mcnulty-2pz4t

**Comment by phphille** [comment]
Darn it, sorry but I left work where staleTime is commented out, please remove the ”//” before staleTime in useQueryPage.js
