### ISSUE TITLE
isLoading doesn't display actual value from useQuery

### ISSUE THREAD

**Issue by vrg-success** [tannerlinsley/react-query#1940]
**Describe the bug**
If I will refetch of query more then 1 time, I will get always isLoading false

**To Reproduce**
1. Just set { enable: false } to useQuery
2. Then try refetch, you will see normal value in isLoading
3. Then try again refetch)) And isLoading will always show value false

**Expected behavior**
On each refetch of query I want to see actual value in property isLoading

**Sandbox**
https://codesandbox.io/s/beautiful-river-n85gt?file=/src/index.js

**Comment by TkDodo** [comment]
isLoading is a hard loading state for when you have no other data to display. When data is served from the cache, the internal status will be success, and therefore, isSuccess will be true. 

Additionally, there is the isFetching flag, which will always be true when a request is in-flight
