### ISSUE TITLE
ReactQueryDevtools warning in console: "Warning: a promise was created in a handler at webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:15660:5 but was not returned from it"

### ISSUE THREAD

**Issue by gerarddegas** [tannerlinsley/react-query#1944]
**Describe the bug**
ReactQueryDevTools is causing warnings regarding promise not being returned in chrome web console. Seems to be due [this warning](http://bluebirdjs.com/docs/warning-explanations.html#warning-a-promise-was-created-in-a-handler-but-was-not-returned-from-it) from bluebird.

Seems to be due to `scheduleMicrotask` function in `node_modules/react-query/es/devtools/utils.js`

**To Reproduce**
1. Add ReactQueryDevTools into your react app
2. Load the app
4. See error in the console

**Expected behavior**
No warning to be shown in the console

**Screenshots**
![image](https://user-images.githubusercontent.com/70550500/110749208-a7602a00-81f5-11eb-977f-0021235d44fc.png)

**Desktop (please complete the following information):**
 - OS: OSX Catalina
 - Browser: Chrome 
 - Version: Version 89.0.4389.82 (Official Build) (x86_64)

**Comment by TkDodo** [comment]
please create a reproducible example in codesandbox. As you can see in all the [examples in the docs](https://react-query.tanstack.com/examples/simple), there is no such warning. But then again, we are not using _bluebird_ :)

would explicitly ignoring the Promise with the `void` operator work, can you try that out please?

```diff
  const safeSetState = React.useCallback(
    value => {
-      scheduleMicrotask(() => {
+      void scheduleMicrotask(() => {
        if (isMounted()) {
          setState(value)
        }
      })
    },
    [isMounted]
  )

**Comment by gerarddegas** [comment]
I changed it directly in the file `node_modules/react-query/es/devtools/utils.js` and still saw the console warning. I tried a few other things like returning the promise within `scheduleMicroTask`.

Would I have to run a build step first though? or is that not necessary?

**Comment by TkDodo** [comment]
can you create a codesandbox example that uses bluebird and shows this issue? Then I can have a look

**Comment by TkDodo** [comment]
any updates on this?

**Comment by TkDodo** [comment]
closing because it's stale and likely `bluebird` related. Please reopen with a reproduction if you want.
