### ISSUE TITLE
useInfiniteQuery does not keep previous data on new fetching

### ISSUE THREAD

**Issue by gritaliana** [tannerlinsley/react-query#1945]
**Describe the bug**
I have been using version 3.8.2 of react-query and after updating to version 3.12.0 this bug appears. I am using useInfiniteQuery with param _keepPreviousData: true_, which in 3.8.2 was working fine and while updating the query by filter changing (new fetching) it was keeping previous data till new data has come. 
But in 3.12.0 while query has _isFetching: true_ and _isFetched: true_ it returns _data.pages: []_ as an empty array, and _isPreviousData: false_ and this is not what expected by using param keepPreviousData: true. Because there was data before this fetch.

**To Reproduce**
For the page with some filter and a list of items create useInfiniteQuery with param keepPreviousData: true.
It looks like: useInfiniteQuery({
queryKey: ['module', query],
queryFn: async () {},
keepPreviousData: true,
})

Then while changing query from the filters it starts fetching the list with new query params. And while it is _isFetching: true_ and _isFetched: false_ it still has _isPreviousData: true_ and returns _data.pages_ with old items, but as long as infiniteQuery has updated to  _isFetching: true_ and _isFetched: true_ it clears the _data.pages_ and returns _isPreviousData: false_. Then, when _isFetching: false_ I finally have data, which is new. But where is the old data in the middle of fetching? 

**Expected behavior**
While using param _keepPreviousData: true_ in useInfiniteQuery it is expected that in the middle of fetching _data.pages_ would not return an empty array if there was data previously. As it works in version 3.8.2.

**Screenshots**
Still have old data
![image](https://user-images.githubusercontent.com/9944499/110772113-ed53d700-8263-11eb-9123-b2dd991f3017.png)

Here it clears old data
![image](https://user-images.githubusercontent.com/9944499/110772350-3015af00-8264-11eb-9b40-a364cd11d8c6.png)

Fetched new data:
![image](https://user-images.githubusercontent.com/9944499/110771899-b54c9400-8263-11eb-8da4-cb6b4bca7a73.png)

**Desktop:**
 - OS: iOS
 - Browser: chrome
 - Version: 88.0.4324.192

**Comment by TkDodo** [comment]
it would help to narrow down the issue if you could track down the exact version when this stopped working. it could be the concurrent mode support that was introduced in [3.9.0](https://github.com/tannerlinsley/react-query/releases/tag/v3.9.0), but that's just a wild guess. A minimal codesandbox repro would also be helpful, thanks

**Comment by TkDodo** [comment]
any updates on a reproduction please?

**Comment by gritaliana** [comment]
We have found the problem on our side. Everything works fine in 3.19.0!
