### ISSUE TITLE
Prefetching in 1.0

### ISSUE THREAD

**Issue by MarceloAlves** [tannerlinsley/react-query#195]
I've built a feature where a user can select an item and then the previous/next items are prefetched for later use when `staleTime` is set.

In 0.4, an item is selected, two prefetch queries and the item query are fired off and cached. Then when a user selects the next item, cached data is loaded and the next item is prefetched. The previous item isn't prefetched since it already exists in the cache.

In 1.0, an item is selected, two prefetch queries and the item query happen but selecting the next item will trigger another item query for the new selected item and also the prefetch for the previous/next items.

I'm not quite sure if this is how it should work or if I'm doing something wrong but any guidance would be very helpful.

I've created two sandboxes with the different versions:

0.4.3 - https://codesandbox.io/s/clever-wilson-mtzph
1.0.10 - https://codesandbox.io/s/amazing-kare-zlnwp

**Comment by tannerlinsley** [comment]
Try latest :)

**Comment by MarceloAlves** [comment]
Noticing a different issue in 1.0.12 and 1.0.13. Selecting 12 fires the next prefetch (13) and not the previous but then selecting 13 and reselecting 12 the component state updates but the query doesn't run to return the cached data. Strange

**Comment by tannerlinsley** [comment]
Yeah, I'm seeing that issue too. I could have uncovered something deeper.

**Comment by tannerlinsley** [comment]
Is this better?

https://codesandbox.io/s/autumn-sun-yh5d9

**Comment by MarceloAlves** [comment]
Hey! Sorry for the delay. Upped the version to `1.0.15` and its working! Only thing I noticed is that the query that uses the `selectedChar` state only returns item 12 even after the state updates. Maybe related?

```text
09:42:15.840 index.js:27 selectedChar: 14
09:42:15.841 index.js:27 query results: {id: 12, name: "Alexander", status: "Dead", species: "Human", type: "", …}
09:42:19.239 index.js:27 selectedChar: 14
09:42:19.239 index.js:27 query results: {id: 12, name: "Alexander", status: "Dead", species: "Human", type: "", …}
09:42:20.456 index.js:27 selectedChar: 15
09:42:20.457 index.js:27 query results: {id: 12, name: "Alexander", status: "Dead", species: "Human", type: "", …}
```
