### ISSUE TITLE
useQueryClient() doesn't work properly in react-native

### ISSUE THREAD

**Issue by afiiif** [tannerlinsley/react-query#1957]
**Describe the bug**
useQueryClient works just fine in browser. But when I use it in **react-native** project, it became not reactive to state change.

This bug might be caused by **window** object used in `getQueryClientContext` function. We can't use window in react-native.
```typescript
function getQueryClientContext(contextSharing: boolean) {
  if (contextSharing && typeof window !== 'undefined') {
    if (!window.ReactQueryClientContext) {
      window.ReactQueryClientContext = defaultContext // Here
    }

    return window.ReactQueryClientContext // Here
  }

  return defaultContext
}

export const useQueryClient = () => {
  const queryClient = React.useContext(
    getQueryClientContext(React.useContext(QueryClientSharingContext))
  )

  if (!queryClient) {
    throw new Error('No QueryClient set, use QueryClientProvider to set one')
  }

  return queryClient
}
```

**To Reproduce**
1. Start any react-native project.
2. Use `useQuery()` hook.  
    Example:  
    ```javascript
    const exampleQuery = useQuery('example', someFunction);
    ````
3. Use `useQueryClient()` hook.  
    Example:  
    ```javascript
    const queryClient = useQueryClient();
    const exampleQuery2 = queryClient.getQueryState('example');
    ````
4. See that `exampleQuery2` is not reactive to state change

**Expected behavior**
`useQueryClient` hook is reactive to state change.  
In example above, `exampleQuery2` should be reactive.

**Comment by TkDodo** [comment]
contextSharing via the `window` has been turned off per default in 3.12.1, and there is also a check if window is not undefined. 

> See that exampleQuery2 is not reactive to state change

`useQueryClient` does not create a subscription to a query - only useQuery does that!

**Comment by afiiif** [comment]
> 
> 
> contextSharing via the `window` has been turned off per default in 3.12.1, and there is also a check if window is not undefined.
> 
> > See that exampleQuery2 is not reactive to state change
> 
> `useQueryClient` does not create a subscription to a query - only useQuery does that!

https://codesandbox.io/s/react-query-example-bd2ho  
👆️ Check this simple example, I think it can subscribe the state of a query

**Comment by afiiif** [comment]
Ah, sorry, my bad. 🙏🙏
The problem is not on the react-native nor useQueryClient hook.

useQueryClient became reactive because I call `useQuery()` in the parent component
