### ISSUE TITLE
Cannot use `useInfiniteQuery` together with `suspense: true`

### ISSUE THREAD

**Issue by lindskogen** [tannerlinsley/react-query#196]
```
Cannot read property 'query' of undefined
```

Lookes like `queryInfoRef.current` is `undefined` here:

![image](https://user-images.githubusercontent.com/817046/75917302-1a53f980-5e5a-11ea-9922-604af0087096.png)

Here's a repro: https://codesandbox.io/s/agitated-neumann-oswnv

**Comment by tannerlinsley** [comment]
Fixed! https://codesandbox.io/s/sharp-carson-14hii

Make sure if you refresh the sandbox you don't click directly on the fetch more button and mistake the window focus refetching event for clicking the button. First, quickly click the page after reloading, then click the fetch more. ;)

**Comment by lindskogen** [comment]
Thanks man!
