### ISSUE TITLE
Typescript with useMutation and mutliple return values

### ISSUE THREAD

**Issue by viclafouch** [tannerlinsley/react-query#1962]
**Describe the bug**

I have a bug with Typescript when I use useMutation and inside the MutationFunction, 2 possible return values..

**To Reproduce**
```ts
  const onSuccess = (data: string | number) => {
    console.log(data)
  }

  const onError = () => {
    console.log('bar')
  }

  const collectionMutation = useMutation(
    (param: string) => {
      if (param === 'new') {
        return new Promise(resolve => resolve('string'))
      }
      return new Promise(resolve => resolve(1))
    },
    { onSuccess, onError }
  )
```

> No overload matches this call.
  Overload 1 of 4, '(mutationFn: MutationFunction<string | number, string>, options?: UseMutationOptions<string | number, unknown, string, unknown> | undefined): UseMutationResult<...>', gave the following error.
    Argument of type '(param: string) => Promise<unknown>' is not assignable to parameter of type 'MutationFunction<string | number, string>'.
      Type 'Promise<unknown>' is not assignable to type 'Promise<string | number>'.
        Type 'unknown' is not assignable to type 'string | number'.
          Type 'unknown' is not assignable to type 'number'.
  Overload 2 of 4, '(mutationKey: MutationKey, options?: UseMutationOptions<string | number, unknown, void, unknown> | undefined): UseMutationResult<string | number, unknown, void, unknown>', gave the following error.
    Argument of type '(param: string) => Promise<unknown>' is not assignable to parameter of type 'MutationKey'.
      Type '(param: string) => Promise<unknown>' is missing the following properties from type 'unknown[]': pop, push, concat, join, and 27 more.
  Overload 3 of 4, '(mutationKey: MutationKey, mutationFn?: MutationFunction<unknown, void> | undefined, options?: UseMutationOptions<unknown, unknown, void, unknown> | undefined): UseMutationResult<...>', gave the following error.
    Argument of type '(param: string) => Promise<unknown>' is not assignable to parameter of type 'MutationKey'.
      Type '(param: string) => Promise<unknown>' is not assignable to type 'unknown[]'

**Expected behavior**
No error from typescript

**Screenshots**
![image](https://user-images.githubusercontent.com/23353836/111064198-ef5fa500-84b2-11eb-8ac9-43d2e0364049.png)

**Additional context**
Typescript version : 4.2.3
React Query version: 3.12.0

**Comment by TkDodo** [comment]
It seems they only `Promise` is inferred from that function. Try annotating with a concrete return type

**Comment by TkDodo** [comment]
I can confirm that this works with a proper type annotation:

`(param: string): Promise<string | number> => {`
