### ISSUE TITLE
refetch does not respect enabled false

### ISSUE THREAD

**Issue by SleeplessByte** [tannerlinsley/react-query#1965]
**Describe the bug**

~Is it possible that this (#1797) has regressed? I'm on `^3.12.1` and running into exactly this.~

When calling `refetch`, there does not seem to be a way to respect `enabled`. Manually refetching the query always goes through. **This by itself** is not an issue, but that means that the only way to use a refetch-but-respect-query-options is to:

- use `queryClient` directly
- copy the `enabled` logic and execute it before calling `refetch`

When the _refetch_ is in flight, it will _actually keep retrying_ the query too if the query fails. This can be overcome by copying the _enabled_ logic **once more** to the `retry` function.

**Expected behavior**
There is a way to `refetchIfEnabled`.

----

Perhaps this can be added to the optional options of `refetch` as a flag?

**Comment by TkDodo** [comment]
can you explain what you are trying to do? refetch is often used with disabled queries for imperative fetching, so that is expected. However, most “refetches” can and should be triggered declaratively by changing the query key.

**Comment by SleeplessByte** [comment]
I have quite a few needs in react-native apps:

- Custom revalidation logic
- Custom focus logic (not the same as screen/window is focussed)
- Custom triggers such as notification/socket/webhook

I currently feel that the code I've written is working around certain limitation. Changing the query key is not what we want, because it should use the same key across the application for the same data.

If using `queryClient` is the only way to do it, then that's fine. I would suggest documenting `refetch` for a future user 😄

**Comment by TkDodo** [comment]
Out of curiosity: which method are you using on the queryClient that refetches but respects enabled? Are you just invalidating ?

**Comment by SleeplessByte** [comment]
I've tried both invalidate + moving `enabled` logic _inside_ query and returning a cached result when it's not, and moving the enabled logic around `.refetchQuery`.

**Comment by TkDodo** [comment]
so I think if you do `queryClient.invalidateQueries`, it should respect the `enabled` flag - does it not?

**Comment by SleeplessByte** [comment]
It does because it doesn't actually refetch the query, but it means requiring at least 4 lines of code _per instance_, including the bikeshedding where I need this behaviour, only because there is no way to have `refetch` respect `enabled`.

**Comment by kitsune7** [comment]
Wait, why did this get closed? It's definitely still an issue. Is having `refetch` ignore the `enabled` option intentional? If so, why?

**Comment by kitsune7** [comment]
I'm having an issue where I'm not explicitly calling refetch anywhere and `enabled` is set to `false`. The second time my component renders, even though `enabled` is still set to false and no data relevant to `useQuery` has changed, the API call is  still made regardless.

**Comment by TkDodo** [comment]
> The second time my component renders, even though enabled is still set to false and no data relevant to useQuery has changed, the API call is still made regardless.

@kitsune7 can you provide a codesandbox that shows this issue please? I can certainly look into it if there is a reproducibility issue.

**Comment by TkDodo** [comment]
@gfox1984 this sounds more like you’d want to disable the query until you have a valid token? Generally speaking, using refetch bypass the declarative nature of RQ

**Comment by gfox1984** [comment]
Correct, this is about disabled ALL queries until I have a valid token, and then run ALL queries, with the exception of the ones that explicitly specify `enabled: false`. Maybe it's wrong of speaking of `reftech` but, in other terms, what solution would you advise to trigger a run of all queries but the disabled ones?

**Comment by TkDodo** [comment]
you can always use `queryClient.refetchQueries` and use a `predicate` function to only match the keys you want to match.

**Comment by gfox1984** [comment]
Hmm, not great, I do not know this. Each query knows at the time they execute.

**Comment by TkDodo** [comment]
just trying to make suggestions. Like I said, I would architect it differently:

```
const myQuery = () => {
  const token = useToken() // assuming this will get set and trigger a re-render once you have a token
  return useQuery(['myKey', token], () => fetchByToken(token), { enabled: !!token })
}
```

**Comment by gfox1984** [comment]
I see... This is obviously more invasive than a global method, but this logic could be wrapped in a custom hook (eg: `useAuthenticatedQuery`). Thanks for the tip.

**Comment by Abdul007Malik** [comment]
I am also facing the similar issue. This happens when I refreshed my token and calling `queryClient.refetchQueries();` onSuccess. The mounted component has the download useQuery hook `enabled: false`,  and it is being called because of this. 
So a download prompt is being triggered when a user opens a webpage due to a token refresh.

**Comment by jjunyjjuny** [comment]
I'm using v4.36.1 and the refetch works even if enabled is false.

here is example

https://playcode.io/1973194
