### ISSUE TITLE
v2 search is not working 

### ISSUE THREAD

**Issue by WaysToGo** [tannerlinsley/react-query#1968]
**Describe the bug**
Search is not working throwing 404 when any search is made in version 2 docs page.

**To Reproduce**
1. Go to https://react-query-v2.tanstack.com/docs/overview
2. Search something like "QueryCache"
3. Hit enter

**Expected behavior**
Should take user to search results

**Screenshots**
<img width="1521" alt="Screenshot 2021-03-15 at 1 13 09 PM" src="https://user-images.githubusercontent.com/17769286/111119485-34a5d480-8590-11eb-8a52-4f4cdff0b288.png">

**Desktop (please complete the following information):**
 - OS: IOS
 - Browser:  chrome
 - Version: 89

**Comment by TkDodo** [comment]
sorry for that, it's a known issue with `algolia`, see: https://github.com/tannerlinsley/react-query/issues/1420#issuecomment-745008257

> Search unfortunately will not work until algolia docsearch supports multiple subdomains .
