### ISSUE TITLE
[@types/react-query] queryCache  is not exported  

### ISSUE THREAD

**Issue by dipeshwalia** [tannerlinsley/react-query#198]
Hi, 

I am trying react-query with create-react-app (template typescript) and got following error 

```Module '"../node_modules/@types/react-query"' has no exported member 'querycache'.ts(2305) ```

here is the codesandbox,  https://codesandbox.io/s/react-query-s2m89

**Comment by tannerlinsley** [comment]
Those types are third party and not officially supported or up to date. Please file an issue there.

**Comment by spidgorny** [comment]
Restarting ```react-scripts start``` helped me.

**Comment by Big-Zude** [comment]
@tannerlinsley @dipeshwalia  I replaced queryCache with queryClient. what do you think?
