### ISSUE TITLE
Query still runs with falsey query key

### ISSUE THREAD

**Issue by Ironimus** [tannerlinsley/react-query#20]
Either there's a bug or the readme is very misleading. [Here's a codesandbox reproducing the issue](https://codesandbox.io/s/blissful-maxwell-l3qvr)

### Expected behaviour:
`useQuery` with a `false` key is ignored and nothing's printed to console

### Actual behaviour:
Despite key being `false` the function is called

**Comment by tannerlinsley** [comment]
This is indeed a bug.

**Comment by tannerlinsley** [comment]
This was fixed in version `0.3.4`. Thanks! 🎉
