### ISSUE TITLE
regression from v1.0.14 to v1.0.15, default value for param config missing

### ISSUE THREAD

**Issue by brumm** [tannerlinsley/react-query#200]
Hey, we're seeing errors `Cannot read property 'force' of undefined` when attempting to pass three params to `queryCache.prefetchQuery`

Works:
`queryCache.prefetchQuery('key', () => {})`

Breaks:
`queryCache.prefetchQuery('key', 'var', () => {})`

It seems like [this line](https://github.com/tannerlinsley/react-query/blob/v1.0.15/src/queryCache.js#L146) did not make it into the npm package for `v1.0.15`

Package diff link and screenshot:
https://diff.intrinsic.com/react-query/1.0.14/1.0.15#file-dist__react-query.development.js

![image](https://user-images.githubusercontent.com/170500/75984230-4ae37400-5eea-11ea-9cbb-a39f339c41ea.png)

**Comment by tannerlinsley** [comment]
I’ll get an updated release out
