### ISSUE TITLE
useInfiniteQuery issue with `hasNextPage` always undefined

### ISSUE THREAD

**Issue by alonfai** [tannerlinsley/react-query#2006]
**Describe the bug**
I'm implementing an infinite page scrolling with the "useInfiniteQuery" hook together with an `IntersectionObserver` API callback. All examples I saw online are using a button to implement custom loading which is great but I'm using this API and the event fires off well. However in my callback method of the `onIntersect` I want to check the `hasNextPage` prop to see if I can continue pulling another fetch request to my API, however, this always evaluates back as undefined despite having the `getNextPageParam` options method working and returning a string that gets passed to my fetcher method. 

**To Reproduce**

I use three main modules: 

1. API.js - retrieve all results from the endpoint using custom hook and react-query `` api.ts``

```

import { getUnixTime } from 'date-fns';

async function fetchData(context) {
  const { limit } = context.queryKey[1];
  let url = `${process.env.REACT_APP_API_DOMAIN}?limit=${limit}`;
  if (context.pageParam) { // Appending the max allowed to retrieve in ascending order
    url += `&before=${getUnixTime(new Date(context.pageParam)).toString()}`;
  }
  const response = await fetch(url);
  if (!response.ok) {
    throw new Error('Network response was not ok');
  }
  return response.json();
}

export default function useAPI(limit: number) {
  const result = useInfiniteQuery(
    ['fetchData', { limit}],
    fetchData,
    {
      getNextPageParam: lastPage => {
        return lastPage[lastPage.length - 1].timestamp; //timestamp passed as param to the fetchData API call
      },
    }
  );
  return result;
}

```

2. custom hook that watches for an element on my list (using TypeScript) ,  `` useIntersectionObserver.ts ``

```

import * as React from 'react';

export default function useIntersectionObserver({
  onIntersect = () => {}, // callback method
  threshold = 1.0,
  rootMargin = '0px',
}) {
  const observer = React.useRef(
    new IntersectionObserver(
      entries => {
        const first = entries[0];
        if (first.isIntersecting) {
          onIntersect();
        }
      },
      { threshold, rootMargin }
    )
  );
  const [element, setElement] = React.useState<HTMLElement | null>(null);

  React.useEffect(() => {
    const currentElement = element;
    const currentObserver = observer.current;

    if (currentElement) {
      currentObserver.observe(currentElement);
    }

    return function cleanup() {
      if (currentElement) {
        currentObserver.unobserve(currentElement);
      }
    };
  }, [element]);

// returning the setter function that gets put into the DOM element in the bottom of the scrolling page.
  return setElement;
}

```

3. Main ``App.ts`` file  

```

import useAPI from './api'
import useIntersectionObserver from './useIntersectionObserver'

const MAX_RECORDS_PER_PAGE = 50;

const App = () => {
  const result = useAPI(MAX_RECORDS_PER_PAGE);
  const { data, isLoading, error, isError, fetchNextPage, hasNextPage } = result;

  const element = useIntersectionObserver({
    onIntersect: () => {
      if (hasNextPage) { // --> always returns as 'undefined'
          fetchNextPage();
      }
    },
  });

// Show Loading element
  if (isLoading) {
    return <Loading>Loading...</Loading>;
  }

  // Unable to parse the API result
  if (isError) {
    return <ErrorMessage description={error?.message ?? ''} />;
  }

  return (
      {data?.pages.map((page, pageIndex) => (
        <React.Fragment key={pageIndex}>
          {page.map((rec, recIndex) => {
            // Last rendered record
            if (
              pageIndex + 1 === data.pages.length &&
              recIndex + 1 === MAX_RECORDS_PER_PAGE
            ) {
              return <Item key={rec.id} rec={rec} ref={element} />;
            }
            return <Item key={rec.id} rec={rec} />;
          })}
        </React.Fragment>
      ))}    
  );
}

```

As can see from above, the ``hasNextPage`` always evaluates to `undefined`

**Desktop (please complete the following information):**
 - OS: Mac OS Big Sur
 - Browser: Chrome, Safari

Any help on what is missing will be appreciate

**Comment by TkDodo** [comment]
> All examples I saw online are using a button to implement custom loading

The official docs have an infinite scrolling example that also uses an intersection observer to automatically trigger the fetch of the next page: 
https://react-query.tanstack.com/examples/load-more-infinite-scroll

yes, the element that is used to check if it's in the viewport is also a button, but it doesn't have to be. I have also used [react-intersection-observer](https://github.com/thebuilder/react-intersection-observer) together with react-query and it works very well.

I don't see anything wrong per se with the code, so please provide a runnable codesandbox example that shows the problem.

**Comment by alonfai** [comment]
@TkDodo Thanks for the link to the [react-intersection-observer](https://github.com/thebuilder/react-intersection-observer) repo. I eventually found the issue why keep getting `undefined`.
The `hasNextPage` prop was part of the original `result` object in App.ts, ignoring new result data coming from the API on subsequent calls to the `useAPI` hook method,  so I just wrapped that variable inside a custom `useRef` object and mutate it with the latest value on each change to the `result.hasNextPage` prop like so:

```
const App = () => {
    const result = useAPI(MAX_RECORDS_PER_PAGE);
    const { data, isLoading, error, isError, fetchNextPage, hasNextPage } = result;
    const hasNextPageRef = React.useRef<boolean>(hasNextPage);
    
    React.useEffect(() => {
      hasNextPageRef.current = result.hasNextPage;
    }, [result]);
    
     const element = useIntersectionObserver({
        onIntersect: () => {
          if (hasNextPageRef.current) {
              fetchNextPage();
          }
        },
      });
    
    // .... Rest of the render method
}
```
