### ISSUE TITLE
v2 QueryCache documentation missing

### ISSUE THREAD

**Issue by bugkarma** [tannerlinsley/react-query#2013]
**Describe the bug**
Documentation for v2 QueryCache returns 404.

**To Reproduce**
1. Go to https://react-query-v2.tanstack.com/
2. Search for 'QueryCache' and go to result (e.g. https://react-query-v2.tanstack.com/reference/QueryCache)
3. See error

**Comment by TkDodo** [comment]
Please see: https://github.com/tannerlinsley/react-query/issues/1968
