### ISSUE TITLE
queryClient.getQueryData(queryKey) not working on latest version of react-query (3.12 and up)

### ISSUE THREAD

**Issue by shekharsaxena** [tannerlinsley/react-query#2022]
**Describe the bug**
Previously had version 3.6.1 installed, and `queryClient.getQueryData('results')` was returning the correct data from the cache, however after upgrading to version 3.12 and beyond 

**To Reproduce**
Upgrade to 3.12 and 3.13, and I am no longer able to access the property that exists in my cache via `queryClient.getQueryData('results').unreadCount` even though it exists in the cache as well as is accessible when I downgrade to 3.6.1.

**Expected behavior**
I should be able to access the value using the same line of code unless there was a breaking change introduced in between minor versions that I missed?

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome, Safari, Firefox
 - Version: Latest

**Smartphone (please complete the following information):**
 - Browser: [e.g. stock browser, safari]
 - Version: [e.g. 22]

**Additional context**

**Comment by TkDodo** [comment]
since 3.8.1, getQueryData needs the exact key, unless you provide exact: false as an option:

https://github.com/tannerlinsley/react-query/releases/tag/v3.8.1

so my guess is you don’t have something with the key `'results'` in your cache. What do the devtools say?

**Comment by shekharsaxena** [comment]
![Screen Shot 2021-03-24 at 3 38 42 AM](https://user-images.githubusercontent.com/3086378/112272358-7995cf00-8c52-11eb-8189-02fc939c9ddd.png)
So since these are paginated queries, I need to pass in the page number and limit?

**Comment by TkDodo** [comment]
Yes, you need to pass the complete queryKey. with exact: false, you’ll get the first match. Not sure if that’s what you want. There is also `queryClient.getQueryCache().findAll` where you can provide a predicate function to filter for what you want.
