### ISSUE TITLE
Can't pass a function as argument to useQuery in v1 

### ISSUE THREAD

**Issue by nikoskleidis** [tannerlinsley/react-query#203]
What I want to do is pass a function as part of the arguments of the queryFunction in order to call it within the function. The argument though is passed as undefined. 
This used to work in earlier versions.
I have reproduced the issue here:
[codesandbox](https://codesandbox.io/s/intelligent-ganguly-3ruxu?fontsize=14&hidenavigation=1&theme=dark)

**Comment by tannerlinsley** [comment]
While it may have worked in previous versions, it definitely shouldn't have. The query key should be serializable by the `config.queryKeySerializerFn`.

If you want to pass a function to your query function, you can pass it as an optional variable like so:

```js
useQuery(['my', 'key'], [customFn], doStuff)

function doStuff('my', 'key', customFn) {
  return stuff
}
```

Keep in mind thought that it will not act as a query key. If you really really really want to use it as a query key, you are more than welcome to tinker with building your own custom queryKeySerializerFn to do so.
