### ISSUE TITLE
v2 - Query does not invalidate if using suspense + enabled options

### ISSUE THREAD

**Issue by benskz** [tannerlinsley/react-query#2035]
**Describe the bug**
When `suspense: true` and you use the enabled option, when toggling enabled to `true`, `queryCache.invalidateQueries` stops working. As far as I can tell this only happens when both options are used.

Is this something that was addressed in v3 perhaps?

**To Reproduce**
https://codesandbox.io/s/cool-lewin-6gc5o?file=/src/App.js

**Comment by TkDodo** [comment]
Please port the example to v3 to see if the issue persists

**Comment by benskz** [comment]
@TkDodo we were trying to avoid porting at the moment. Does that mean v2 is no longer supported?

**Comment by TkDodo** [comment]
I just wanted to narrow down the issue. If it’s solved in v3 I’m not sure what the policy is for patching v2

**Comment by benskz** [comment]
@TkDodo I've tried this same scenario with v3 and the problem does not seems to be present.

https://codesandbox.io/s/infallible-platform-re5dh?file=/src/App.js

**Comment by TkDodo** [comment]
That’s good to hear. I know some things were changed extensively for suspense in v3, and it’s also still experimental, so I think updating to v3 would be your best bet.

**Comment by TkDodo** [comment]
I'm gonna close this given that it works in v3.
