### ISSUE TITLE
`select` cannot be used with `onSuccess` at the same time, otherwise the type cannot be inferred

### ISSUE THREAD

**Issue by piecego** [tannerlinsley/react-query#2037]
I want to do some set state operations in `onSuccess` fn, and then convert the data structure in `select` fn, but unable to infer the correct type.
[https://codesandbox.io/s/stupefied-andras-otxpp?file=/src/App.tsx](https://codesandbox.io/s/stupefied-andras-otxpp?file=/src/App.tsx)

**Comment by TkDodo** [comment]
yeah, this seems like a case where type inference doesn't work properly. I remember having the same issues when doing the optimistic-updates-in-typescript example, where inference wouldn't work properly with multiple callbacks.

here is the discussion from that PR: https://github.com/tannerlinsley/react-query/pull/1366#discussion_r538459890

it also links to an open typescript issue: https://github.com/microsoft/TypeScript/issues/26242

the workaround for here would probably be to provide explicit generics, so:

```
useQuery<Array<string>, Error, string>
```
