### ISSUE TITLE
prefetching before changing queryKey from a to b returns stale data from key a

### ISSUE THREAD

**Issue by brumm** [tannerlinsley/react-query#204]
Hey,

another weird behavior around prefetching (although I do wonder at this point whether my assumptions how this library should behave are totally off 😅):

- component mounts with queryKey `['path', 'a']`
- click button 'change path to b'
- state updates to `'b'`
- path `'b'` is fetched
- data updates to `'b'`, as expected

reload test page
- component mounts with queryKey `['path', 'a']`
- click button 'prefetch b'
- we prefetch for queryKey `['path', 'b']`
- path `'b'` is fetched
- click button 'change path to b'
- state updates to `'b'`
- data does not update, remains at `'a'`

repro: https://codesandbox.io/s/react-query-bug-repro-j6im3

As context, my use case for this is a file tree / file contents view. Paths are selected via click and shown in the file contents view. The selected path is passed to `<FilePreview>`'s `useQuery(['file', path])` hook. Without prefetching, this works well. For a performant experience, I'd like to prefetch file contents on tree label hover. So file contents can be prefetched right before the user actually selects the path. Once I do this, I run into problems with the file preview showing file contents of the previous path.

I've disabled `refetchOnWindowFocus`, because it masks the issue somewhat. If it's true, the refetching will somehow re-render the hook with the correct value.

**Comment by tannerlinsley** [comment]
Most likely related to your last issue. Still working on that one, then I'll take a look at this one.

**Comment by brumm** [comment]
Probably, I wasn't sure whether I'm "holding it  wrong" at this point :)

Thank you so much for your work on this library, it's a joy to use!

**Comment by tannerlinsley** [comment]
This is also fixed via dbad39737f765412c8aba9819ce345f1a94da729
