### ISSUE TITLE
`queryKeyHashFn` missing in docs

### ISSUE THREAD

**Issue by vinay-deshmukh** [tannerlinsley/react-query#2042]
**Describe the bug**
On the [documentation page](https://react-query.tanstack.com/reference/useQuery) for `useQuery`, one of the arguments to `useQuery` is listed as `queryKeyHashFn`, but when you scroll down to read about it, it's entry is missing in the docs part.

**To Reproduce**
1. Go to https://react-query.tanstack.com/reference/useQuery
2. Search for "queryKeyHashFn"
3. Only one occurrence of `queryKeyHashFn` is present, when there should be at least 2 (One in the code example, and one in the docs part)

**Expected behavior**
Documentation of `queryKeyHashFn` should be present.

**Screenshots**

**Desktop (please complete the following information):**
 - N/A

**Smartphone (please complete the following information):**
 - N/A

**Additional context**

**Comment by TkDodo** [comment]
Do you want to add the missing information?

**Comment by vinay-deshmukh** [comment]
Sure.

Is there any specific order to follow when adding the doc entry in the markdown file?

And do I make the PR against `master`?
