### ISSUE TITLE
typings of initialData and select

### ISSUE THREAD

**Issue by TkDodo** [tannerlinsley/react-query#2060]
**Describe the bug**

As discussed [here](https://github.com/tannerlinsley/react-query/issues/1824#issuecomment-810554020) in point 1, `select` gets the data from the queryFn and transforms it to another type, the data from initialData is also passed to `select`, but the typings of `initialData` want you to return the transformed data already. Here is the recap from that comment:

1) initalData goes through select

you can see this proven in this example:
https://codesandbox.io/s/select-initialdata-3urc4?file=/src/App.tsx

```
  const { isLoading, error, data } = useQuery(
    "test",
    async () => {
      await waitFor(2000);
      return 5;
    },
    {
      select: (data) => String(data * 10),
      initialData: () => 10
    }
  );
```

it starts off with printing `data is 100, type is string`, and then after 2 seconds, it goes to: `data is 50, type is string`.
That does seem correct to me. `initialData` is put _into_ the cache and treated like every other data.

However, we have a TypeScript error here: `initialData` is expected to return a `string` (`TData`). That is most certainly not correct, because it goes _through_ select, so it needs to be a _number_  (`TQueryData`) = the type that the queryFn returns.

**To Reproduce**
- see the above example and sandbox

**Expected behavior**

- initialData should need to return the same data (on type level) as the queryFn

**Comment by TkDodo** [comment]
@boschni I could use your input here. I thought it would be as easy as changing the type of the select function here:

https://github.com/tannerlinsley/react-query/blob/e42cbc32dfcd9add24cadd06135e42af1dbbc8ad/src/core/types.ts#L66

```diff
- initialData?: TData | InitialDataFunction<TData>
+ initialData?: TQueryFnData | InitialDataFunction<TQueryFnData>
```

so that the `initialData` has the same typings as the data returned from the queryFn, which seems like that's what we want, because that data goes into the cache, same as the data returned from the queryFn, and it's also passed to `select`.

it does get weird with `useInfiniteQuery` though. There, we have different types:

- the queryFn shall return `TQueryFnData`
- but initialData is currently to be of type `InfiniteData<TData>` - it probably should be `InfiniteData<TQueryFnData>`
- select takes `InfiniteData<TQueryFnData>` and outputs `InfiniteData<TData>`

I'm not quite seeing through all the generics here 😅 . I think I'm most confused by the name `TData`. on a queryObserver level, it indicates the data that is produced by select, and it defaults to `TQueryFnData`, which is the data from the queryFn. Thats's fine. But on `Query` and `queryCache` level, we also have a generic called `TData`, but it is actually crated from `TQueryData`, 3rd generic here:

https://github.com/tannerlinsley/react-query/blob/e42cbc32dfcd9add24cadd06135e42af1dbbc8ad/src/core/queryObserver.ts#L210-L220

`TQueryData` also defaults to `TQueryFnData`, except for infiniteQueries where it's `InfiniteData<TQueryData>`.

so yeah, I'm a bit lost on how to make this work. On second thought the types of `initialData` are correct given that `TData` on query level is actually `TQueryData` on observer level, but then where is the mismatch coming from that `select` wants us to return a `string` in the above sandbox example, when it clearly should be a `number`? 🤯

**Comment by boschni** [comment]
Hi @TkDodo! You should be able to get it working by passing the correct data type to `QueryOptions`:

```diff
-export interface QueryObserverOptions<
-  TQueryFnData = unknown,
-  TError = unknown,
-  TData = TQueryFnData,
-  TQueryData = TQueryFnData,
-  TQueryKey extends QueryKey = QueryKey
-> extends QueryOptions<TQueryFnData, TError, TData, TQueryKey> {
+export interface QueryObserverOptions<
+  TQueryFnData = unknown,
+  TError = unknown,
+  TData = TQueryFnData,
+  TQueryData = TQueryFnData,
+  TQueryKey extends QueryKey = QueryKey
+> extends QueryOptions<TQueryFnData, TError, TQueryData, TQueryKey> {
```

**Comment by TkDodo** [comment]
😮  that works 🤯 

and seeing the diff it also make sense that we only need to change the 3rd generic here, but wow my head is spinning right now 😅 .

what do you think about renaming the generics on `Query` and `QueryOptions` level from `TData` to `TQueryData` ?

`TData` to me is observer specific, the end-result of the data returned to the useQuery consumer, _after_ we've done `select`. Or is that thinking wrong?

Thanks again, PR incoming 🚀
