### ISSUE TITLE
useInfiniteQuery doesn't work correctly

### ISSUE THREAD

**Issue by matheusalbino** [tannerlinsley/react-query#208]
Recently, I migrated a project to use the newest version (v1+) of react-query. When using the `useInfiniteQuery` the function `fetchMore()` doesn't work correctly, the `queryFn` doesn't receive an updated `nextId`, the value received is the same of started.

Steps:
- clone: https://github.com/tannerlinsley/react-query/tree/master/examples/load-more-infinite-scroll
- upgrade to version 1.0.16 

I have set the version to 1.0.7, in this version works fine.

**Comment by seonghyeonkimm** [comment]
Is it resolved? I think I am having the same issues with @matheusalbino
