### ISSUE TITLE
Errors should not be cached

### ISSUE THREAD

**Issue by Mikilll94** [tannerlinsley/react-query#2094]
**Describe the bug**
I have noticed that errors from `useQuery` hook are cached. IMO they should not be cached. They should be cleared when the component is remounted.

**To Reproduce**
1. Download this simple Node.js project
[node-api.zip](https://github.com/tannerlinsley/react-query/files/6265200/node-api.zip)
2. Open it in VSCode and run:
```
npm install
node server.js
```
3. Download this simple React project
[react-query-test.zip](https://github.com/tannerlinsley/react-query/files/6265208/react-query-test.zip)
4. Open the new instance of VSCode and run:
```
yarn
yarn dev
```
5. Click on "Go to 8". Wait until the error "Person not found" will be visible
6. Click "Go back".
7. Click again on "Go to 8". The error "Person not found" is immediately visible (which means that it was cached).

**Expected behavior**
Errors should not be cached. `error` variable should be cleared when the component remounts.

**Desktop (please complete the following information):**
 - OS: macOS 11.2.3
 - Browser: Chrome
 - Version: 89.0.4389.114

Version of react-query: 3.13.4

**Additional context**
Another solution is to provide some flag to the configuration, i.e. clearErrorsOnRemount

**Comment by TkDodo** [comment]
if an erroneous component re-mounts, it should be in `isLoading` state. You can safely ignore the error in this case and only show the error if you are in `isError` state.

**Comment by nghiepit** [comment]
Hey, 
I'm having the same issue. We need to clear cache error when `suspense: true`.

@TkDodo  You can see the problem in the example: https://codesandbox.io/s/busy-http-53kvh?file=/src/App.tsx

**Comment by TkDodo** [comment]
@nghiepit I don't understand that example. suspsense is set to false... can you explain the example with information about the issue is, what I need to click to reproduce the issue, how it behaves and how it _should_ behave instead? Thanks

**Comment by nghiepit** [comment]
@TkDodo I have been updated the example `suspense` to true.
The problem is errors should be clear after the `YourData` component unmount.

**Step1**: Click the `Toggle` button: The `Loading...` visible and after 3s the `<ErrorFallback />` will be replaced.
**Step2**: Click the `Toggle` button: The `<YourData />` will be unmounted.
**Step3**: Click the `Toggle` button:  Error should be clear and the `Loading...` should be visible and after 3s the `<ErrorFallback />` replaced again (Step 1).

The current behavior in step3:  the `<ErrorFallback />` appeared immediately

**Comment by TkDodo** [comment]
@nghiepit I looked at the updated example. You need to tell react-query that it's now okay to start refetching by _resetting_ the Error Boundary. This is described here: https://react-query.tanstack.com/reference/QueryErrorResetBoundary

I updated the example and it seems to work fine: https://codesandbox.io/s/stoic-drake-3gcn3?file=/src/App.tsx

You can also use the [useQueryErrorResetBoundary](https://react-query.tanstack.com/reference/useQueryErrorResetBoundary) hook instead, but you have to re-enable fetching somehow. Just unmounting is not enough I'm afraid. Of course, you can call the `reset` method in a useEffect that always triggers when `visible` is false in the example.

**Comment by nghiepit** [comment]
@TkDodo Thank you for clarifying.
