### ISSUE TITLE
useInfiniteQuery with suspense no longer returns pages (3.9.0+)

### ISSUE THREAD

**Issue by avaragado** [tannerlinsley/react-query#2095]
**Describe the bug**

In my app, I've just upgraded `react-query` from from 3.7.1 to 3.13.4. The app uses `useInfiniteQuery` with `suspense: true`.

After the upgrade, the `data` object in the result does not have `pages` and `pageParams` keys: it's just a flat array of values.

It seems to be related to suspense: changing to `suspense: false` brings `pages` and `pageParams` back.

A quick bisection indicates the bug was introduced in 3.9.0.

**To Reproduce**
1. Set up a query that uses `useInfiniteQuery` and set `suspense: true`
2. Note that in the result value, the `data` object does not have `pages` or `pageParams` keys.
3. Set `suspense: false` and note that the `pages` and `pageParams` keys exist.

**Expected behavior**
With `suspense: true`, the `pages` and `pageParams` keys should be present as documented.

**Comment by Avyiel** [comment]
Can confirm, having the exact same issue with 3.12.3, where using `useInfiniteQuery` with `suspense: true` will not give back `pages` and `pageParams`.

**Comment by cdpark0530** [comment]
I'm using @tanstack/react-query 4.6.0 and this issue happens.

**Comment by TkDodo** [comment]
@cdpark0530 please show a reproduce and open a new issue if you have one.
