### ISSUE TITLE
Hydration is broken, "No QueryClient set"

### ISSUE THREAD

**Issue by Ephem** [tannerlinsley/react-query#2112]
**Describe the bug**

Hydration is broken. This can also be seen in the Next.js-example:

> No QueryClient set, use QueryClientProvider to set one

The `/hydration`-package has at some point (v3 release?) switched from `import { useQueryClient } from 'react-query'` to `import { useQueryClient } from '../react'`. This bundles the `useQueryClient` code into the hydration package itself, which also means a _separate_ `QueryClientSharingContext` gets created there. This is line 124 in `dist/react-query-hydration.development.js`:

```
var QueryClientSharingContext = /*#__PURE__*/React.createContext(false);
```

Because this context is different from the one `QueryClientProvider` uses, the hydration package can't find a queryClient to work with.

I plan to fix this but wanted to document the bug as soon as I found it.

**Comment by TkDodo** [comment]
thank you @Ephem , this is a good find. could this also be the root cause for https://github.com/tannerlinsley/react-query/issues/1936, where we essentially have the same problem with the dev-tools?

**Comment by Ephem** [comment]
I think the mechanism is the same, but I don't think the hydration package itself is the root cause of that one, I'm about to post over there too. 😄

**Comment by joshuadoan** [comment]
Not sure if this will help, but I was getting errors about a missing `QueryClientProvider`  in a  `create-next-app` until I moved my components with `useQuery` out of my `pages` directory.  Using `"react-query": "^3.13.7"`

**Comment by Ephem** [comment]
Thanks for that additional info @joshuadoan. I'm not sure if that is related or something else, but I'll keep it in mind!

I intend to submit a fix for this today.
