### ISSUE TITLE
error on page : https://react-query.tanstack.com/examples/nextjs  needs "web-streams-polyfill " in codesandbox for Ky to work...

### ISSUE THREAD

**Issue by lemarcgagnon** [tannerlinsley/react-query#2122]
**Describe the bug**

**To Reproduce**
1. Go to 'https://react-query.tanstack.com/examples/nextjs'
2. Click on 'Nextjs SSG'
4. 502 Bad Gateaway

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g.Linux]
 - Browser: [e.g. chrome]
 - Version: [e.g. 22]

**Additional context**
Although I am quite a newbie, i saw that we could resolve the bad Gate Away 502 is for "Ky" by adding this dependency to the Dependencies listing:

 npm install web-streams-polyfill --save

as per https://www.npmjs.com/package/ky-universal  instructions.

then the whole thing works just fine.

Yours,

Marc

**Comment by TkDodo** [comment]
very good find. would you like to PR that please?

**Comment by lemarcgagnon** [comment]
Hello Dominik,

As i said, I am quite a newbie and have no idea about your "PR" request
proposal.   Hope I could help you with this, but sincerely I have no clue
about what your are saying.

Keep on the good work and thank you so much for your good work,

Marc

**Comment by TkDodo** [comment]
okay, no worries. So the way open source works is that everyone can contribute. To do that, you need to fork the repository to your own account (top right button in github), then create a branch. You can then implement the fix, in this case it's just adding that dependency to `package.json` in the example. After that, you can make a PR (pull request) from your branch to this repository - just go to the Pull Requests tab here and click on `New Pull Request`.

make sure to adhere to the commit message convention, you can read about it here: https://github.com/tannerlinsley/react-query/blob/master/CONTRIBUTING.md#commit-message-conventions

---

I think this is a good first issue if you want to get started with contributing to open source :)

**Comment by lemarcgagnon** [comment]
Wow thanks...I ll look into on Monday...

**Comment by nedjulius** [comment]
hey, for some reason the CodeSandbox example is now entirely missing from the Next.js example page.

**Comment by TkDodo** [comment]
Not sure what you mean - it’s still here: https://react-query.tanstack.com/examples/nextjs

**Comment by nedjulius** [comment]
yeah, now it's there. sorry for a false ping then. 12 hours ago the CodeSandbox threw an error that said that the example did not exist...
