### ISSUE TITLE
onSuccess from the options passed in a mutate function is not called

### ISSUE THREAD

**Issue by emilgpa** [tannerlinsley/react-query#2125]
**Describe the bug** 
onSuccess from options passed in a mutate function is not called:

```js
 const {
   data,
   error,
   isError,
   isIdle,
   isLoading,
   isPaused,
   isSuccess,
   mutate,
   mutateAsync,
   reset,
   status,
 } = useMutation(mutationFn, {
   mutationKey,
   onError,
   onMutate,
   onSettled,
   onSuccess,
   useErrorBoundary,
 })
 
 mutate(variables, {
   onError,
   onSettled,
   onSuccess, // <-- HERE
 })
```

**To Reproduce**

Sometimes it happens, other times, it is really difficult to reproduce it because it happens to me in a medium-size application and I don't know when it will reproduce and when not.

**Expected behavior**
onSuccess in options passed to a mutate function should be called.

**Desktop (please complete the following information):**
 - OS: Macos
 - Browser: Chrome
 - Version: 89

**Comment by emilgpa** [comment]
Sorry, it's my mistake.

**Comment by Abror1997** [comment]
@emilgpa I have the same issue here. What was your mistake? 👀

**Comment by seanbruce** [comment]
> @seanbruce My component using the query / mutation was being unmounted so the callback `onSuccess` was not being called.

me too
