### ISSUE TITLE
Using iPad I cannot navigate your docs

### ISSUE THREAD

**Issue by frederikhors** [tannerlinsley/react-query#2129]
**Describe the bug**
Using iPad I cannot navigate your docs.

**Expected behavior**
I can see the docs menu.

**Screenshots**
![image](https://user-images.githubusercontent.com/41120635/114846907-70c19480-9ddd-11eb-872d-19bd771f3d55.png)

**Comment by TkDodo** [comment]
workaround: flip it to portrait:

![Screenshot 2021-04-15 at 22 37 31](https://user-images.githubusercontent.com/1021430/114935417-6f26b980-9e3b-11eb-829c-4a77d6edacd9.png)

![Screenshot 2021-04-15 at 22 37 38](https://user-images.githubusercontent.com/1021430/114935412-6d5cf600-9e3b-11eb-8a8a-da23d67bbd86.png)

**Comment by TkDodo** [comment]
please open a PR if it's important to you.
