### ISSUE TITLE
queryKey falsy values + initialData causes infinite loop

### ISSUE THREAD

**Issue by eblin** [tannerlinsley/react-query#214]
Hi Tanner,

Whenever I pass a falsy value and I have initialData, the query goes into an infinite loop/re-renders. This does not happen if we use the object syntax.

BUG:
```js
useQuery(false && 'bug', fetcher, {initialData: 'whatever'})
```
OK:
```js
useQuery({queryKey: false && 'bug', queryFn: fetcher...})
```

I managed to reproduce it in codesandbox:
https://codesandbox.io/s/objective-wildflower-vnxii

P.S. Thank you so much for all your hard work on this, is a great lib! 👍

**Comment by tannerlinsley** [comment]
I’m on it!

**Comment by cherniavskii** [comment]
So here's what's going on:
- query key changes to `false`
- `useBaseQuery` creates a new query with `undefined` key, which is not stored in queryCache (this works as expected).
- query is marked as stale, `onStateUpdate` is invoked and it causes `useBaseQuery` to rerender (this also works as expected).
- on next render new query is created (since there's no cached query for `false` key) - this causes an infinite loop.

This is very interesting scenario...

**Comment by cherniavskii** [comment]
I think that solution would be to not create new query in `useBaseQuery`, if `typeof queryHash === 'undefined'`.

**Comment by tannerlinsley** [comment]
I had a guard against this so this is definitely a regression. I think.

**Comment by cherniavskii** [comment]
Ok, I will check recent git history.
Will submit a PR later

**Comment by cherniavskii** [comment]
> I had a guard against this so this is definitely a regression. I think.

Didn't find anything like that in v1 history

**Comment by eblin** [comment]
> So here's what's going on:
> 
> * query key changes to `false`
> * `useBaseQuery` creates a new query with `undefined` key, which is not stored in queryCache (this works as expected).
> * query is marked as stale, `onStateUpdate` is invoked and it causes `useBaseQuery` to rerender (this also works as expected).
> * on next render new query is created (since there's no cached query for `false` key) - this causes an infinite loop.
> 
> This is very interesting scenario...

Any reason why this would work differently when the object syntax is being used? Because it doesn't suffer from the bug, and I assume the same key `false` is being set as well.
