### ISSUE TITLE
It is not possible to rewrite cacheTime when using queryClient.setQueryData

### ISSUE THREAD

**Issue by joseucarvajal** [tannerlinsley/react-query#2145]
I'm iterating through a result array and using setQueryData to memoize individual results. I also have a specific hook to fetch these results individually with userQuery(...). I've tried to set the cacheTime other than 5 mins and it's been not possible when using setQueryData. I've tried many different approaches:

1. set cacheTime as configuration in queryClient.setQueryData(['task', id], data, {cacheTime:5000})
2. set cacheTime within the specific hook with the userQuery(['task', id], fetchFn, {cacheTime:5000})
3. queryClient.setQueryDefaults(['task', id], data, {cacheTime:5000})

None of them have worked, cacheTime always is 300000 when using querClient.setQueryData.

I'm working with react-query v3.13.10.

**Comment by TkDodo** [comment]
Not sure what issue you are trying to solve, what’s your use case? setQueryData can set the query data, not query options. 

However, number 2 in your list should work. useQuery accepts a cacheTime option: https://react-query.tanstack.com/reference/useQuery

**Comment by joseucarvajal** [comment]
Thanks @TkDodo,

The issue I’m facing, is that I haven’t been able to set cacheTime when using setQueryData(...).  This is my question: Is there any way to set cacheTime when using useQueryData?.

**Comment by TkDodo** [comment]
if that's the question then the answer is: no, it's not possible.

but I don't think that is the question. You're clearly trying to solve a problem by setting cacheTime via setQueryData, and I would like to know what that use-case is. Maybe there is a completely different way of solving that problem that doesn't have anything to do with setting cacheTime via setQueryData. But you need to describe your problem in order for me to help out here :)
