### ISSUE TITLE
mutationFn is missing from UseMutationOptions type

### ISSUE THREAD

**Issue by Jeday** [tannerlinsley/react-query#2150]
**Describe the bug**
 mutationFn is missing from declaration for UseMutationOptions. Preventing you from specifying mutation function in form of reusable config object similar to UseQueryOptions. Casting options object with mutationFn to any, bypassing type checks, code works fine and mutation function is called. 

**To Reproduce**

In typescript project: 
```javascript
const mutation = useMutation({
    mutationFn: ()=>Promise.resolve(console.log('I am mutationFn'))
})
```
and run type checking. 

**Expected behavior**
mutationFn should be an optional key in UseMutationOptions generic.

**Desktop (please complete the following information):**
- any

**Smartphone (please complete the following information):**
- any

**Comment by TkDodo** [comment]
`UseMutationOptions` does have an optional `mutationKey`:

https://github.com/tannerlinsley/react-query/blob/a88d80f6f7b2d96ab605ac08f4fbaed9a3bcd4b7/src/react/types.ts#L71-L77

can you create a codesandbox reproduction to show what is not working please?

**Comment by Jeday** [comment]
[`Here you go`](https://codesandbox.io/s/react-typescript-forked-y3tz6?file=/src/index.tsx)
Codesandox is not very good at marking typescript errors but it's there.

**Comment by TkDodo** [comment]
thank you. TypeScript underlines the mutationKey, but that is not the real culprit here. There error says:

`No overload matches this call.`

looking at the _useMutation_ overloads, there is no version that accepts a `mutationKey` _and_ a `mutateFn` in the same object. I think the object-only syntax is meant for usage together with the defaultMutationFn, but I'm not sure. So it's not the key that is missing, it's the `mutateFn` that is not here.

it seems to work at runtime, but not at compile time, right?

**Comment by Jeday** [comment]
Yes. The whole bug is just about  the missing `mutationFn` key from `UseMutationOptions` type declaration.  It's not crucial but currently I have to cast my mutation config objects to `any`  and that makes it ugly and type unsafe.

**Comment by TkDodo** [comment]
I don't know why I _misread_ the issue as `mutationKey` is missing 🤦 . I'll take a look at fixing this later :)

**Comment by TkDodo** [comment]
Those overloads are quite hard to get right on type level. I just looked up how useQuery is doing it, and TypeScript is fine with this:

```
  useQuery('key', () => Promise.resolve(23), {
    queryKey: 'foo',
    queryFn: () => Promise.resolve(5)
  })
```

seems a bit meh

**Comment by Jeday** [comment]
There is `mutationFn` but as an argument for an overload.  Copying it to useMutationOptions should resolve issues. Don't forget to make it optional though so it won't break other overloads.

**Comment by TkDodo** [comment]
yes, it would, but then we would have the same "problem" as shown above from useQuery, right? when using an overload that passes the `mutateFn` as a separate argument, it should ideally `Omit` the `mutateFn` key from the allowed options object

**Comment by Jeday** [comment]
Yeah you can try to add tricky types for overloads with `Omit`s  and other trickery but that sounds like a huge step in  direction of retyping the whole library. For now it's better just to add missing keys so that types are not behind actual functionality.

**Comment by christophemenager** [comment]
Hi there ! Thanks for the amazing work on this library ! ⭐ 

I have the same use case on my project, we would love to be able to write this in typescript : 

```
 useMutation({
      mutationFn : () => console.log("mutation function called!"),
      mutationKey : xxxx,
    })
```

**Comment by amanzrx4** [comment]
I'm getting a similar error in ^4.22, I don't understand why typescript fails to recognize the mutationFn here, the exact same code is working in multiple places in the project but showing errors in some. 




```ts

 const addOrder = useMutation<
    IPostOrderDetailsResponse,
    Error,
    FormData,
    unknown
  >({
    mutationKey: ['someKey],
    mutationFn: (payload) =>
     postAddOrder({
        data: payload,
        headers: {
          "Content-Type": "multipart/form-data",
        },
      }),
  });

No overload matches this call.
  The last overload gave the following error.
    Argument of type '{ mutationKey: "postAddOrder"[]; mutationFn: (payload: FormData) => Promise<IAxiosCommonResponse>; }' is not assignable to parameter of type 'MutationKey'.
      Object literal may only specify known properties, and 'mutationKey' does not exist in type 'readonly unknown[]'.```

**Comment by pigpudle** [comment]
I'm facing this issue again on version `4.28.0`.
It appears only when I use generic version of `useMutation`:

1. Works fine:
```javascript
const result = useMutation({ // <-- Works fine
    mutationFn: changeSetting,
  })
```
2. Shows error:
```javascript
const result = useMutation<unknown, any>({ // <-- Shows error
    mutationFn: changeSetting,
  })
```

**The error message:**
```
No overload matches this call.
  The last overload gave the following error.
Argument of type '{ mutationFn: ({ id, value }: { id: any; value: any; }) => AxiosPromise<any>; }' is not assignable to parameter of type 'MutationKey'.
      Object literal may only specify known properties, and 'mutationFn' does not exist in type 'readonly unknown[]'
```

**Comment by pigpudle** [comment]
I've tried to pass a single mutation function instead of options object, but this type is also broken, TS uses `mutationKey` variantinstead of `mutationFn` variant:

```javascript
const result = useMutation<unknown, any>(changeSetting)
```
results in error:
```
No overload matches this call.
  The last overload gave the following error.
    Argument of type '({ id, value }: { id: any; value: any; }) => AxiosPromise<any>' is not assignable to parameter of type 'MutationKey'.ts(2769)
useMutation.d.ts(6, 25): The last overload is declared here.
```

**Comment by pigpudle** [comment]
It seems that TS uses the last declared overload when I use `useMutation` as generic, and it breaks types
