### ISSUE TITLE
Stale While Revalidate - Wrong information in the comparison table

### ISSUE THREAD

**Issue by Mikilll94** [tannerlinsley/react-query#2151]
![Screenshot 2021-04-19 at 21 45 31](https://user-images.githubusercontent.com/17653648/115294203-97265d80-a158-11eb-9606-0cf0cef54966.png)
![Screenshot 2021-04-19 at 21 45 13](https://user-images.githubusercontent.com/17653648/115294197-95f53080-a158-11eb-85ba-a30f892656ee.png)

The comparison here: https://react-query.tanstack.com/comparison is wrong.

Stale While Revalidate is really straightforward to implement in Apollo Client.

```js
const ItemList = () => {
  const { data, loading, error } = useQuery(
    GET_ITEMS, { fetchPolicy: 'cache-and-network' }
  );

  if (!data && loading) return <Loading />;
  if (error) return <p>ERROR: {error.message}</p>;

  return (
        <>
          {data.items.map(item => (
            <Item key={item.id} item={item} />
          ))}
      </>
  );
}
```

I know that the term "Stale While Revalidate" is not used in the Apollo docs but implementing such UI behavior is really simple.

**Comment by TkDodo** [comment]
please feel free to make a PR to the comparison table. From what I can tell, there are a couple of things that might be outdated. I am not familiar with apollo, so I can't comment. If you provide some links that confirm the information in the PR, I'm happy to merge it.
