### ISSUE TITLE
seQueryData marks query as fresh

### ISSUE THREAD

**Issue by cherniavskii** [tannerlinsley/react-query#216]
Currently after setting query data via `queryCache.setQueryData`, `isStale` is set to false.

https://github.com/tannerlinsley/react-query/blob/2fb23e467698f233a2af86735fb81e89c3bffb55/src/queryCache.js#L494-L500

Is this intentional?
This means that query won't be refetched until `refetch` is called or tab is focused.

**Comment by tannerlinsley** [comment]
Sounds like a bug. The query should technically follow the same staleTime lifecycle as if it just received fresh data from a refetch.

**Comment by tannerlinsley** [comment]
Oh. If staleTime is set to above 0 then yes it will be false for whatever the staleTime is. However if it never goes back, then we have a missing timer.
