### ISSUE TITLE
Type of `data` not corresponding to the initialData

### ISSUE THREAD

**Issue by viclafouch** [tannerlinsley/react-query#2163]
**Describe the bug**
The type of `data` is not corresponding to the `initialData`. How to avoid this `undefined` type ? 

I thought this PR (https://github.com/tannerlinsley/react-query/pull/2069) fixed the issue :/ (I already remove my node_modules and `npm i`).

it starts off with printing data is`[]`, type is not undefined, and then after 2 seconds, I have my array filled, type is still not undefined.

![image](https://user-images.githubusercontent.com/23353836/115552389-91da2780-a2ac-11eb-8749-833fc6ce54d1.png)

**Desktop (please complete the following information):**
 - OS: Chrome
 - Browser: 89.0.4389.128
 - Version: 3.13.10

**Comment by TkDodo** [comment]
`data` is always potentially `undefined` on type level. `initialData` cannot narrow the type.

see also: https://github.com/tannerlinsley/react-query/discussions/1301
