### ISSUE TITLE
overly restrictive return typing for onSuccess handler

### ISSUE THREAD

**Issue by probablyup** [tannerlinsley/react-query#2166]
**Describe the bug**

At present, `onSuccess()` may return a promise that the library will await to finish processing a query/mutation result. However, that typing is restricted to a promise that explicitly returns `void`, rather than `any` which would be more appropriate.

**To Reproduce**

Fire an async mutation and in the onSuccess, return another async mutation that is meant to happen using the data from the first. TS issues a compiler error because mutateAsync does not resolve to `Promise<void>`.

**Expected behavior**
The accepted return type for onSuccess should be `Promise<any>` so you can do whatever you want to in the onSuccess handler.

**Current mitigation**
This can currently be worked around by recasting the onSuccess return:

```ts
mutateAsync1(payload, {
  onSuccess(data) {
    return (mutateAsync2(data.token) as unknown) as Promise<void>
  }
})
```

**Comment by TkDodo** [comment]
onSuccess is not meant for chaining. It is meant to execute side effects, and the result will be awaited, but not returned from the mutation. 
i guess that’s why the types are like that, but maybe it should be Promise<unknown> 🤔

If you want to use mutateAsync and the result of it, just await it and continue normally:

```
const data = await mutateAsync1(payload)
await mutateAsync2(data.token)
```

don’t forget error handling though

**Comment by probablyup** [comment]
@TkDodo Sure, I'm not expecting the result of the second async mutation to be available to me, just that I can return that promise and have it work without TS complaining.

**Comment by Daniel-TheProgrammer** [comment]
ok

**Comment by TkDodo** [comment]
can you try out the PR if that works for you?

**Comment by Daniel-TheProgrammer** [comment]
Tried and it didn't work

**Comment by TkDodo** [comment]
ahm, why not?

https://codesandbox.io/s/tannerlinsleyreact-query-basic-typescript-forked-wkhcp

**Comment by Daniel-TheProgrammer** [comment]
Well..will try again..
