### ISSUE TITLE
useInfiniteQuery does not work with fetchQuery/prefetchQuery

### ISSUE THREAD

**Issue by Ephem** [tannerlinsley/react-query#2168]
**Describe the bug**

If you prime the cache with `fetchQuery` or `prefetchQuery` and later use that same query in a `useInfiniteQuery`, `hasNextPage` will always be `undefined`.

**Expected behavior**

There should be a way to prefetch infinite queries, either working out of the box or if necessary with a separate API, something like `(pre)fetchInfiniteQuery`. 

**Cause**

When using `useInfiniteQuery`, data is stored in `.data.pages` and not directly in `.data`. `(pre)fetchQuery` places data directly in `.data` so when the internal `hasNextPage()`-function later looks for `data?.pages` that comes back `undefined` and so `hasNextPage` becomes `undefined` as well.

[Related line](https://github.com/tannerlinsley/react-query/blob/master/src/core/infiniteQueryBehavior.ts#L150)

**Solution**

I guess it's expected that you can't use the same `queryKey` with both a `useQuery` and a `useInfiniteQuery` since the cache is formed differently for those? In that case, it might be possible to solve this without having to support a separate prefetch-API for `useInfiniteQuery`. That solution might very well get complex however, so a separate API might still be desirable and also make it less magical. Different hooks->different prefetches kind of makes sense.

Not quite sure which solution would be desirable.

**Comment by msahajwani** [comment]
I'm facing similar issue.

I have a Nextjs project, where I'm using `useInfiniteQuery` as follows:

```
  const {
    status,
    data,
    error,
    isFetching,
    isFetchingNextPage,
    fetchNextPage,
    hasNextPage
  } = useInfiniteQuery("posts",fetchPosts,
    {
      getNextPageParam: (lastPage) => lastPage.nextId ?? false
    }
  );
```

It works great, but if I want to prefetch this query data using GetStaticProps or GetServerSideProps, I do it as follows:

```
export const getStaticProps: GetStaticProps = async () => {
  const queryClient = new QueryClient();
  await queryClient.prefetchQuery('posts', fetchPosts)
  return {
    props: {
      dehydratedState: dehydrate(queryClient),
    },
  }
}
```

This breaks the page because prefetch places data in .data, while the useInfiniteQuery places data in .data.pages. And my template is coded to look for data.pages.

My template:

```
{data && data.pages && data.pages.map((page) => (
  <React.Fragment key={page.nextId}>
    {page.data.map((post) => (
      <div key={post.id}>
        <Post post={post} />
      </div>
    ))}
  </React.Fragment>
))}
```

How do I resolve this?

**Comment by Ephem** [comment]
@msahajwani This is something that needs fixing in the library itself, but meanwhile I think you can do something like this as a workaround:

```ts
export const getStaticProps: GetStaticProps = async () => {
  const queryClient = new QueryClient();
  await queryClient.prefetchQuery(
    'posts', 
    fetchPosts.then((data) => {
      return {
        pages: data
      };
    })
  )
  return {
    props: {
      dehydratedState: dehydrate(queryClient),
    },
  }
}
```

**Comment by msahajwani** [comment]
Thanks so much. I'll use this solution.

**Comment by Ephem** [comment]
@msahajwani You might have noticed this yourself, but I realized I made an error in the workaround above (now fixed).

The `pages` should be an array, so the `return { pages: data }` should actually be `return { pages: [data] }`. 😄

**Comment by Ephem** [comment]
Thinking about this some more, maybe a new `(pre)fetchInfiniteQuery` that also supports prefetching several pages of data makes sense? Two examples:

* You want to prefetch and server render 20 items, but only load 10 at a time when user clicks "Show more", so you prefetch 2 pages of data
* You have the nr of pages you have fetched in a query_param and reload the page. Now you want to prefetch and server-render the correct amount of pages so scroll restoration works

I can think of more cases, but I thought those two were easiest to explain.

**Comment by Etienne-M** [comment]
I don't know if that's of any use to you, but you could use the InfiniteQueryObserver API to achieve something very similar to what you are looking for:
```js
 const observer = new InfiniteQueryObserver(queryClient, {
   queryKey: 'posts',
   queryFn: fetchPosts,
   getNextPageParam: (lastPage, allPages) => lastPage.nextCursor,
 })
const prefetch = async () => new Promise(resolve => {
   const unsubscribe = observer.subscribe(result => {
     resolve();
     unsubscribe()
   })
 })
```

**Comment by TkDodo** [comment]
> Expected behavior

>There should be a way to prefetch infinite queries, either working out of the box or if necessary with a separate API, something like (pre)fetchInfiniteQuery.

@Ephem am I missing something, because we have [queryClient.prefetchInfiniteQuery](https://react-query.tanstack.com/reference/QueryClient#queryclientprefetchinfinitequery) as well as [queryClient.fetchInfiniteQuery](https://react-query.tanstack.com/reference/QueryClient#queryclientfetchinfinitequery)

> I guess it's expected that you can't use the same queryKey with both a useQuery and a useInfiniteQuery

yes, I wouldn't do that because the structures are so different.

**Comment by Ephem** [comment]
How on earth did I miss that? 😲 I remember searching both the docs and the code, but I obviously did a terrible job at it.. 😊 Sorry for the noise!
