### ISSUE TITLE
useQuery throws an error when key value is null

### ISSUE THREAD

**Issue by jfranciscosousa** [tannerlinsley/react-query#217]
As the documentation states, if a key has a falsey value the query is "skipped", but on my project, I get a `args[0] is null` error. 

The code is from a client project so I can't show it here but basically you can reproduce it by passing `null` to `useQuery`. From my experience, `null` is a falsey value, just want to know if this is the intended behavior.

Everything works fine if I pass `false` or `undefined` instead of the `null` value.

**Comment by cherniavskii** [comment]
That's a bug.
`null` is an object, so this check fails:
https://github.com/tannerlinsley/react-query/blob/2fb23e467698f233a2af86735fb81e89c3bffb55/src/utils.js#L91

There's `isObject` function in the same file, which should be used instead.

@jfranciscosousa want to submit a PR?

**Comment by jfranciscosousa** [comment]
Yep, I'll do it a moment
