### ISSUE TITLE
suspense useQuery infinite loop when query goes from success to false and query key changes

### ISSUE THREAD

**Issue by flybayer** [tannerlinsley/react-query#2187]
**Describe the bug**
The workaround in https://github.com/tannerlinsley/react-query/issues/2157 fixed only part of the issue we are having in Blitz. We still have a case on user logout where we get infinite loops.

Failing test case included below. They key thing that makes it go into the infinite loop is the query key changing. If the key doesn't change, then it works fine.

**To Reproduce**

Add the following test to `src/react/tests/suspense.test.tsx`

```ts
  it('should not have infinite loop', async () => {
    const key = queryKey()

    const consoleMock = mockConsoleError()

    let succeed = true

    function Page() {
      const [nonce] = React.useState(0)
      const fullKey = `${key}-${succeed}`
      const result = useQuery(
        fullKey,
        async () => {
          await sleep(10)
          console.log('query', fullKey)
          if (!succeed) {
            throw new Error('Suspense Error Bingo')
          } else {
            return nonce
          }
        },
        {
          retry: false,
          suspense: true,
        }
      )
      return (
        <div>
          <span>rendered</span> <span>{result.data}</span>
          <button
            aria-label="fail"
            onClick={async () => {
              await queryClient.resetQueries()
            }}
          >
            fail
          </button>
        </div>
      )
    }

    function App() {
      const { reset } = useQueryErrorResetBoundary()
      return (
        <ErrorBoundary
          onReset={reset}
          fallbackRender={({ resetErrorBoundary }) => (
            <div>
              <div>error boundary</div>
              <button
                onClick={() => {
                  resetErrorBoundary()
                }}
              >
                retry
              </button>
            </div>
          )}
        >
          <React.Suspense fallback="Loading...">
            <Page />
          </React.Suspense>
        </ErrorBoundary>
      )
    }

    const rendered = renderWithClient(queryClient, <App />)

    await waitFor(() => rendered.getByText('Loading...'))
    await waitFor(() => rendered.getByText('rendered'))

    succeed = false
    fireEvent.click(rendered.getByLabelText('fail'))
    await waitFor(() => rendered.getByText('error boundary'))
    consoleMock.mockRestore()
  })
```

**Version**

React-query 3.13.9

**Comment by flybayer** [comment]
cc @tannerlinsley @TkDodo

**Comment by flybayer** [comment]
I could look into to fixing it, but not sure where to even start on this one

**Comment by flybayer** [comment]
I have to quit for the day, but I tracked this down to this line not being called but it should be: https://github.com/tannerlinsley/react-query/blob/master/src/react/useBaseQuery.ts#L135

**Comment by Daniel-TheProgrammer** [comment]
I think this project should have a readme so contributors can commit

**Comment by TkDodo** [comment]
> but I tracked this down to this line not being called but it should be:

not sure if I'm of much help here. At the time where the line in question is called, `result.isError` is still false. When we log it, we can se that we still have one render cycle where `succeed` is true. When the infinite loop starts, we somehow never even get to this line of code....

```
  console.log
    query query_1-true

      at src/react/tests/suspense.test.tsx:35:19

  console.log
    result.isError false

      at useBaseQuery (src/react/useBaseQuery.ts:130:11)

  console.log
    query query_1-true

      at src/react/tests/suspense.test.tsx:35:19

  console.log
    query query_1-false

      at src/react/tests/suspense.test.tsx:35:19

  console.log
    query query_1-false

      at src/react/tests/suspense.test.tsx:35:19

  console.log
    query query_1-false

      at src/react/tests/suspense.test.tsx:35:19

  console.log
    query query_1-false

      at src/react/tests/suspense.test.tsx:35:19
```

**Comment by Daniel-TheProgrammer** [comment]
Ok

**Comment by flybayer** [comment]
Whew, I spent awhile digging into this more. Haven't really got anywhere, but I did find that when query key changes, query `status` goes from `loading` to `idle` but when query key stays the same `status` goes from `loading` to `loading`.

Also it almost appears as if there are two observers for the same query fighting each other 🤔 

I'd be grateful if someone else could take this from here.

**Comment by JaeYeopHan** [comment]
same issue in react-query 3.18.0 version
