### ISSUE TITLE
Error with initializing QueryClient

### ISSUE THREAD

**Issue by raghavendracs** [tannerlinsley/react-query#2192]
**Describe the bug**

My _app.jsx has a simple instantiation of the queryClient. 

const MyApp = props => {
  const { Component, pageProps } = props;
  const { settings } = useSettings();
  const queryClientRef = React.useRef();
  if (!queryClientRef.current) {
    queryClientRef.current = new QueryClient();
  }
...
...
}

The moment I fetch the first query in one of the components I get the below TypeError and then things move ahead.

I am currently using the latest version of react-query v3.13.12

Converting circular structure to JSON
    --> starting at object with constructor 'QueryClient'
    |     property 'queryCache' -> object with constructor 'QueryCache'
    |     property 'queries' -> object with constructor 'Array'
    |     ...
    |     index 0 -> object with constructor 'QueryObserver'
    --- property 'client' closes the circle

Thanks for the help.

**Comment by TkDodo** [comment]
please provide a minimal runnable codesandbox reproduction if you think there is an issue with the library, thanks.

**Comment by raghavendracs** [comment]
@TkDodo - Please find attached the link to a Simple Code Sandbox where the same error above is visible on loading the page. [](https://codesandbox.io/s/circular-reference-error-op3z1)

Thanks in advance.
<img width="1661" alt="Screenshot 2021-04-27 at 17 00 49" src="https://user-images.githubusercontent.com/10530686/116273980-24316e00-a77a-11eb-8a6f-1d8c8a5067e0.png">

**Comment by TkDodo** [comment]
not sure what I'm doing differently, but there is no such error for me when I open that sandbox (macos, chromium) 🤔 

![Screenshot 2021-04-27 at 18 21 00](https://user-images.githubusercontent.com/1021430/116277007-58f6f280-a785-11eb-9109-56f72bc59eef.png)

**Comment by raghavendracs** [comment]
Am also on MacOS, Chrome. 

I am seeing the error in the Dev Tools of Chrome on a Page Refresh consistently. Can you please check if you see the error there?

**Comment by TkDodo** [comment]
very weird, but still no:

![Screenshot 2021-04-27 at 18 30 48](https://user-images.githubusercontent.com/1021430/116278393-bdff1800-a786-11eb-8ece-f7b0a9482a56.png)

switched to a real "chrome", and the screenshot even shows the page reload in between 🙃

**Comment by galliumsoft** [comment]
Hmm... interesting...  I am getting the same error. @raghavendracs , I used your codesandbox code above, and this is my screenshots for both on codesandbox (which was a bit erratic.. appeared sometimes and doesnt appear sometime).. and on Chrome (Version 90.0.4430.85 (Official Build) (64-bit) ... Interestingly I dont see the same error in windows edge explorer.

screenshot in codesandbox.. 
![Circular Reference Error - CodeSandbox 27-04-2021 17-43-54](https://user-images.githubusercontent.com/13764756/116281022-306cf980-a781-11eb-9734-97198397476d.png)

and in normal chrome.. 
![Screenshot (170)](https://user-images.githubusercontent.com/13764756/116281110-47abe700-a781-11eb-8ec2-9015db1890b6.png)

**Comment by TkDodo** [comment]
Ah, does it come from a browser extension that i might not have installed? (react-devtools-backend)?

**Comment by raghavendracs** [comment]
Correct. We are working on a NextJS App and hence have react-devtools extension installed on Chrome. Is there a problem in react-query-devtools playing nice with react-devtools?

**Comment by TkDodo** [comment]
so I also have the react-devtools browser extension installed - is theres an additional extension one can install for next js that I might not have installed?

**Comment by raghavendracs** [comment]
Your question prompted me to see what others extensions / devtools I had in the browser. 

I had another one called React Context DevTool 3.2 which was installed (which I was using for debugging React Context Data). Looks like that might be the culprit. Disabling it also has stopped the error from coming through. 

Just to be doubly sure if you could spend a couple of minutes to install that extension and see if you get the error it would be very helpful.

**Comment by TkDodo** [comment]
it makes sense that it is this extension. if it tries to serialize whatever is in the context to json, it will not work with the QueryClient, because it (apparently) references itself. The QueryClient itself was not meant for that :)
