### ISSUE TITLE
isLoading and isFetching remain true after an error is returned

### ISSUE THREAD

**Issue by ingro** [tannerlinsley/react-query#22]
Hello! I don't know if this is working as intended or not but it sounds a little strange to me.

When a request fails all its given retries, the `error` property is correctly updated with the Error object returned from the request's Promise, but both `isLoading` and `isFetching` properties remain `true`.

I have created a little codesandbox to show this strange behaviour:

https://codesandbox.io/s/hopeful-mendeleev-3v4xk

**Comment by tannerlinsley** [comment]
It was indeed a bug you found with regards to retries and those state flags. I just fixed it in version `0.3.5` which is now available :)

**Comment by ingro** [comment]
Thanks for the fast reply and for the fast release :)
