### ISSUE TITLE
Passing a predicate function to invalidateQueries causes queries with unmounted components to refetch when invalidated

### ISSUE THREAD

**Issue by lamaya** [tannerlinsley/react-query#2201]
**Describe the bug**
When a query is invalidated after a mutation, the invalidated query will be re-fetched even if the component it's associated with is no longer mounted. However, this only happens when the query is invalidated by passing a predicate function to the `invalidateQueries` method. If a single query is invalidated without using a predicate function, the query will not re-fetch if it is not mounted.

**To Reproduce**
Here is a [CodeSandbox](https://codesandbox.io/s/friendly-dan-njvly?file=/src/TestMutation.js) that demonstrates the issue. 
1. Clicking "Query" will mount the query
2. Clicking either "Invalidate" buttons will invalidate the query as expected
3. After clicking "Mutation" it will re-fetch the query when "invalidate with predicate" is clicked, although the component is no longer mounted, the same does not happen when "Invalidate query simple" is clicked

**Expected behavior**
Invalidating a query using a predicate function should not re-fetch if the component is not mounted

**Version**
react-query V 2.26.3

**Comment by TkDodo** [comment]
this seems to work correctly for me in the latest 3.x version:

https://codesandbox.io/s/async-fog-02v43

**Comment by TkDodo** [comment]
I'm gonna close this given that it works in v3. You'll get a ton of great new features when upgrading and we have a good [migration guide](https://react-query.tanstack.com/guides/migrating-to-react-query-3)
