### ISSUE TITLE
TypeError: _reactQuery.QueryClient is not a constructor

### ISSUE THREAD

**Issue by Mmferry** [tannerlinsley/react-query#2226]
QueryClient is not a constructor when write a unit test with jest
```
import { QueryClient, QueryClientProvider } from "react-query";
const queryClient = new QueryClient({
  defaultOptions: {
      queries: {
          retry: 2,
      },
  },
});


export function App() {
  return (
    <QueryClientProvider client={queryClient}>
      <Dashboard />
    </QueryClientProvider>
  );
}

export default App;
```

**Comment by TkDodo** [comment]
You asked the same on stackoverflow: https://stackoverflow.com/questions/67354617/typeerror-reactquery-default-is-not-a-constructor

**Comment by brodriguez-eb** [comment]
The solution for this is to import the package like this:
```js
import { QueryClient, QueryClientProvider } from "react-query/";
```

Notice the backslash in "react-query".

@TkDodo

**Comment by elvismontezumakw** [comment]
I am facing the same error but no much help in the web...
I tried @brodriguez-eb idea but it does not work.

**Comment by TkDodo** [comment]
@elvismontezumakw the stackoverflow link is broken because the author deleted the question.

please post a codesandbox reproduction of your problem, it's impossible to help otherwise.

**Comment by broadhu2** [comment]
In my case, this error message was related to an improper `jest.mock` that I had added earlier.

The fix was to change this:
```typescript
import { useQuery } from "@tanstack/react-query";

jest.mock("@tanstack/react-query", () => ({
  useQuery: () => ({ isLoading: false, error: {}, data: [] }),
}));
```

to the following:
```typescript
import * as ReactQuery from "@tanstack/react-query";

jest.mock("@tanstack/react-query", () => {
  const original = jest.requireActual<typeof ReactQuery>("@tanstack/react-query");

  return {
    ...original,
    useQuery: () => ({ isLoading: false, error: {}, data: [] }),
  };
});
```

My initial block of code overrides the entire module, when my intent was just to override the `useQuery` function and retain the rest. Hope this helps someone else who might be stuck on this!

**Comment by sevdas** [comment]
Thank you for sharing this! That change have solved the same problem I had faced! ✨
