### ISSUE TITLE
Documentation does not mention queryKeyOrPredicateFn param for setQueryData

### ISSUE THREAD

**Issue by brumm** [tannerlinsley/react-query#223]
Hey,

I needed to set a bunch of query keys to some value, and realized that `setQueryData` uses `findQueries` under the hood, allowing me to pass a `queryKeyOrPredicateFn` instead of a key.

While preparing a PR for the docs change I realized that, if we were to make this explicit in the docs, we'd have to deal with the first param being a function, from which we then could not create a query if no query was found.

How should we handle this? I'd suggest logging a warning in the console if we didn't find a query with a predicate function, and doing nothing else.
I'd like to keep the ability to dynamically setQueryData if possible.

**Comment by tannerlinsley** [comment]
There. Now you can finish that PR ;)
