### ISSUE TITLE
Apparently the "main" field isn't right in package.json

### ISSUE THREAD

**Issue by kud** [tannerlinsley/react-query#2233]
```
(node:11234) [DEP0128] DeprecationWarning: Invalid 'main' field in '/node_modules/react-query/devtools/package.json' of '/index.js'. Please either fix that or report it to the module author
```

**Comment by danditomaso** [comment]
To give more context this is also occurring to me when I had updated to NodeJS 15.x. I'm pretty sure this error relates to that change.

**Comment by kud** [comment]
This project isn't the only one to have this error in fact. And I'm using node `v16.0.0`. :)

**Comment by TkDodo** [comment]
if you know how to fix it - can you PR it please?

**Comment by kud** [comment]
I've got to have a look the reason why. :) Yeah sure.

**Comment by TkDodo** [comment]
thank you, that's awesome 🙏
