### ISSUE TITLE
refetchOnWindowFocus not working while enabled is false.

### ISSUE THREAD

**Issue by stamahto** [tannerlinsley/react-query#2240]
**Describe the bug**
Hi, I'm using useQuery hook and when I set option property enabled to false and refetchOnWindowFocus to true, the refetch is not triggered.

**Expected behavior**
When I specify property refetchOnWindowFocus to true, I expect that refetch will be triggered, even when enabled property is set to false.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome 90
 - Version: 3.15.2

Thank you

**Comment by Shaddix** [comment]
Why do you expect the query to refetch in this case?
According to the docs:
>Set this to false to disable this query from automatically running.

refetching on focus is an automatic running

**Comment by TkDodo** [comment]
a disabled query is disabled, so it won't do automatic fetches. this is on purpose.

**Comment by stamahto** [comment]
> Why do you expect the query to refetch in this case?
> According to the docs:
> 
> > Set this to false to disable this query from automatically running.
> 
> refetching on focus is an automatic running

I just don't want immediately trigger fetch, when component is mounted, because it requires params which are loaded lately from another fetch... but on window refocus I expect, that params are already fetched.

**Comment by Shaddix** [comment]
Why don't you just set the `enabled` options to true/false depending on the presence of parameters?
Something like

```
function MyComponent(props) {
  const query = useQuery([props.param1], ()=>{ /* fetching function depending on props.param1 here */ }, 
    { enabled: !!props.param1 }
  );
}
```

**Comment by stamahto** [comment]
> Why don't you just set the `enabled` options to true/false depending on the presence of parameters?
> Something like
> 
> ```
> function MyComponent(props) {
>   const query = useQuery([props.param1], ()=>{ /* fetching function depending on props.param1 here */ }, 
>     { enabled: !!props.param1 }
>   );
> }
> ```

Ok, this is a possibility too. Thank you 🥇

**Comment by TkDodo** [comment]
> Why don't you just set the enabled options to true/false depending on the presence of parameters?

This is the way :) It's also described in the docs under [dependent queries](https://react-query.tanstack.com/guides/dependent-queries)
