### ISSUE TITLE
SSR Guide - Invalid assignment expression

### ISSUE THREAD

**Issue by sgentile** [tannerlinsley/react-query#2241]
https://react-query.tanstack.com/guides/ssr

documentation shown produces an error: 

![image](https://user-images.githubusercontent.com/132404/117213625-df38b780-adc9-11eb-8ed6-d34aab212f9f.png)

**Comment by Shaddix** [comment]
Where is it exactly?..

I'm only seeing the following example (which is similar), but it doesn't have that `?.` part:
![image](https://user-images.githubusercontent.com/1249513/117228375-1e571f00-ae43-11eb-83b6-f0f27d0a38b5.png)

**Comment by TkDodo** [comment]
If you see something in the docs that can be improved, please PR it :)
