### ISSUE TITLE
useQuery enabled doesn't work with falsey values

### ISSUE THREAD

**Issue by jeff3dx** [tannerlinsley/react-query#2269]
**Describe the bug**
Falsey values such as `undefined` do not work as expected with `useQuery` `enabled` setting. This may be by design but not sure why it would be. It threw me off and I almost did not catch the extra queries being run when I set `enabled` to a falsey value instead of explicit `false`.  Note that the typescript typing accepts a falsey value.

**To Reproduce**
1. Code any simple useQuery statement
2. For the `useQuery` config set it to `{ enabled: undefined }`
3. Run the code
4. Observe the react-query dev tools panel or the browser network tab. The query runs as if enabled
 
**Expected behavior**
The query should be disabled if `enabled` is falsey

**Workaround**
Wrap all `enabled` values with `Boolean()`

**Comment by TkDodo** [comment]
This is the desired behavior, as stated in the api docs (type boolean) as well as in the v3 migration guide: https://react-query.tanstack.com/guides/migrating-to-react-query-3#if-set-the-queryoptionsenabled-option-must-be-a-boolean-truefalse

**Comment by ggascoigne** [comment]
I will say that this makes migration from v2 much more annoying that might otherwise be the case.  Not all of the previously valid falsey values are caught by typescript.  I'd have much preferred a console log message as opposed to throwing an exception.
