### ISSUE TITLE
invalidateQueries with refetchActive: false on inactive query refetches it

### ISSUE THREAD

**Issue by donysukardi** [tannerlinsley/react-query#2271]
**Describe the bug**
Calling `queryClient.invalidateQueries` with `{ refetchActive: false }` on inactive query actually refetches it.

**To Reproduce**
Codesandbox: https://codesandbox.io/s/react-query-refetchactive-bug-n3kwc

With the following query cache state:
```
['queryA'] // inactive
['queryB'] // active
```

When I call 
```
// ❌ Incorrect, refetches 😵
queryClient.invalidateQueries(['queryA'], {
  refetchActive: false
});

// ✅ Correct, doesn't refetch
queryClient.invalidateQueries(['queryB'], {
  refetchActive: false
});
```

**Expected behavior**
Option `{ refetchActive: false }` on inactive query shouldn't trigger refetch

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: chrome
 - Version: 90

**Additional context**
N.A

**Comment by TkDodo** [comment]
I understand the codesandbox example. Do I need to change something in the code? How do I trigger the invalidation? I just see a `B` on the screen 😅 🙈

**Comment by donysukardi** [comment]
Oh.. The example mounts and unmounts queryA, then mounts queryB and finally invalidates both queries.

```
function Example() {
  const queryClient = useQueryClient();
  const [shouldRenderB, setShouldRenderB] = React.useState(false);

  React.useEffect(() => {
    if (shouldRenderB) {
      setTimeout(() => {
        queryClient.invalidateQueries(["queryA"], { refetchActive: false });
        queryClient.invalidateQueries(["queryB"], { refetchActive: false });
      }, 500);
    }
  }, [shouldRenderB, queryClient]);

  return (
    <div>
      <p>Open console to see the fetching sequence</p>
      {!shouldRenderB && <CompA onSuccess={() => setShouldRenderB(true)} />}
      {shouldRenderB && <CompB />}
      <ReactQueryDevtools initialIsOpen={false} />
    </div>
  );
}
```

**Comment by TkDodo** [comment]
it looks like there is a bug in `matchQuery`: the query is "found" even though it shouldn't be. Basically:

- `invalidateQueries` sets `QueryFilters` to active here: https://github.com/tannerlinsley/react-query/blob/09116e54b98f5f15fd6777fb26a3d735573a2e4a/src/core/queryClient.ts#L241 and forwards it to `refetchQueries`
- there, we findAll queries and refetch the matching ones: https://github.com/tannerlinsley/react-query/blob/09116e54b98f5f15fd6777fb26a3d735573a2e4a/src/core/queryClient.ts#L270
- I quickly debugged and queryA is correctly seen as inactive in the cache, but for some reason, it still matches must be somewhere here: https://github.com/tannerlinsley/react-query/blob/4083c1ef8a8734d2680a4e5f031c7958c18ee176/src/core/utils.ts#L167-L216

 Do you want to take a stab at it? `queryCache.findAll` has lots of tests, but maybe we are missing this case and you can add a test and see where it takes you ...

**Comment by donysukardi** [comment]
I figured as much. I was debugging all the way till `matchQuery` 🙈.

Sure, I can take a stab at it.

What would be the intended behaviour if both `active` and `inactive` are set? It's currently possible to provide both. Given the following query cache state,

```
queryA: inactive
queryB: active
```

this would be the expected matrix?

<table>
<tr>
	<td>refetchActive
	<td>refetchInactive
	<td>results
<tr>
	<td>true
	<td>true
	<td>[queryA, queryB]
<tr>
	<td>true
	<td>false
	<td>[queryB]
<tr>
	<td>false
	<td>true
	<td>[queryA]
<tr>
	<td>false
	<td>false
	<td>[]
</table>

**Comment by TkDodo** [comment]
> Sure, I can take a stab at it.

awesome, thanks!

> this would be the expected matrix?

I would say so, yes :)

**Comment by donysukardi** [comment]
Can get your understanding of the following?

- `{ active: false }` the same as `{ inactive: true }`? 
- `{ inactive: false }` the same as `{ active: true }`?

<table>
<tr>
	<td>active
	<td>inactive
	<td>results
<tr>
	<td>true
	<td>
	<td>active queries
<tr>
	<td>
	<td>true
	<td>inactive queries
<tr>
	<td>false
	<td>
	<td>???
<tr>
	<td>
	<td>false
	<td>???
</table>

I think it complicates things and introduces ambiguity if we allow both active and inactive in the same config.

**Comment by TkDodo** [comment]
I agree having two boolean flags is sub-optimal. ideally, it would be a tri-state enum like `'all' | 'active' | 'inactive'`, but we can't really change the api now :/

the split I don't quite understand, because `refetchQueries` is a public api in itself, so we could also do:

```
queryClient.refetchQueries({ active: true, inactive: true })
```

so this a case that we need to support anyhow

this is the normal `QueryFilters` filter object that applies to many public queryClient methods, like `refetchQueries`, `removeQueries`, `resetQueries` etc. They all just pass the `filters` down to `queryCache.findAll`, which then calls `matchQuery`. The only difference with `invalidateQueries` is that it, per default, only wants to refetch active filters, which is why it falls back to `true` on the `refetchActive` input.

So I think having both to `true` is the same as having both to `undefined`. Maybe the logic in `matchQuery` can be simplified by using default values when destructing the `filters`, because we wouldn't have to deal with an input being `undefined` anymore 🤔 . This is quite hard to grasp imo:

https://github.com/tannerlinsley/react-query/blob/4083c1ef8a8734d2680a4e5f031c7958c18ee176/src/core/utils.ts#L191-L201

**Comment by donysukardi** [comment]
We need to put in `none` in the mix as well.

<table>
<tr>
	<td>active
	<td>inactive
	<td>results
<tr>
	<td>true
	<td>true
	<td>all
<tr>
	<td>true
	<td>false
	<td>active
<tr>
	<td>false
	<td>true
	<td>inactive
<tr>
	<td>false
	<td>false
	<td>none
<tr>
	<td>undefined
	<td>undefined
	<td>all
</table>

But if we default destructuring to false, then we will get no results when both are not present. We should still check if user has explicitly passed nothing for `active` and `inactive`, which in that case, it should be treated as `all`.

**Comment by TkDodo** [comment]
> But if we default destructuring to false, then we will get no results when both are not present.

I would've destructed to `true`, but I'm not sure this is right either. The docs say:

```
active?: boolean
  When set to true it will match active queries.
  When set to false it will match inactive queries.
inactive?: boolean
  When set to true it will match inactive queries.
  When set to false it will match active queries.
```

this means that inactive: false is the same as active:true ? I'm so confused right now 😅

**Comment by rozam007** [comment]
**### Difference between  refetchActive and refetchInactive** 

The **refetchActive** and **refetchInactive** options are part of the invalidateQueries method in React Query. They control whether the queries that are currently active or inactive should be refetched when they are invalidated.

-     **refetchActive:** If set to true, any active queries with the matching query key will be refetched immediately.
-     **refetchInactive:** If set to true, any inactive queries with the matching query key will be refetched the next time they are rendered or accessed.

**Here's a more detailed explanation of these options:**

-     **Active Queries:** Queries that are currently being used in rendered components. For example, if a component that uses a query is currently mounted, the query is considered active.
-     **Inactive Queries:** Queries that are not currently being used in any rendered components. For example, if a component that uses a query is unmounted, the query becomes inactive.
