### ISSUE TITLE
useMutation always idle on first attempt

### ISSUE THREAD

**Issue by qapt** [tannerlinsley/react-query#2279]
**Describe the bug**
Every time a mutation is first attempted, the status of said mutation is idle. I have to attempt the mutation a second time for it to be successful/error.

**To Reproduce**

Login mutation
```
export function useLoginUser() {
    const queryClient = useQueryClient();
    return useMutation(
        async ({ username, password }) => {
            try {
                const { data } = await axios.post(
                    '/login',
                    {
                        username,
                        password,
                    },
                    { withCredentials: true }
                );
                return data;
            } catch (error) {
                throw new Error(error);
            }
        },
        { onSuccess: () => queryClient.invalidateQueries('currentUser') }
    );
}
```

Mutation call 
```
const handleSubmit = (e) => {
    e.preventDefault();
    const loginData = { username, password };
    loginUserMutation.mutate(loginData);

    if (loginUserMutation.isSuccess) {
       // redirect user
    }
};
```

**Expected behaviour**
I understand the mutation should be in idle status at first, but shouldn't it become success after submit? Right now if the first attempt is successful it stays idle, and after a second attempt right after the first one it becomes success.

**Version**
 - React-Query 3.13.10

**Comment by TkDodo** [comment]
Can you please provide a codesandbox example?

**Comment by donysukardi** [comment]
As you're checking `isSuccess` in a callback (outside render cycle), you will be reading a snapshot value for the render cycle when `handleSubmit` got created instead.

```js
const handleSubmit = (e) => {
    e.preventDefault();
    const loginData = { username, password };
    loginUserMutation.mutate(loginData);

    if (loginUserMutation.isSuccess) { // This is a snapshot
       // redirect user
    }
};
```

You can either pass [`onSuccess`](https://react-query.tanstack.com/reference/useMutation#:~:text=mutate%3A%20(variables%3A%20tvariables%2C%20%7B%20onsuccess%2C%20onsettled%2C%20onerror%20%7D)%20%3D%3E%20void) config to the mutate function,

```js
loginUserMutation.mutate(loginData, {
  onSuccess: () => {
    // Do redirect
  }
});
```

or if you prefer Promise style, you can await on [`mutateAsync`](https://react-query.tanstack.com/reference/useMutation#:~:text=mutateasync%3A%20(variables%3A%20tvariables%2C%20%7B%20onsuccess%2C%20onsettled%2C%20onerror%20%7D)%20%3D%3E%20promise%3Ctdata%3E)

```js
await loginUserMutation.mutateAsync(loginData);
// Do redirect
```

**Comment by qapt** [comment]
After further testing, it seems the mutation is working correctly. The problem seems to be I'm checking for success without awaiting the mutation, so the "isSuccess" check only sees the first status, which is "idle". Is there a way I can explicitly await for the mutation to finish? If i use my redirect logic outside the "handleSubmit" it works properly.

https://codesandbox.io/s/withered-sound-yss2v
Here I try to console.log right after the mutation, and it shows idle every first time after refreshing, then using a useEffect it shows the status is updating correctly.

**Comment by donysukardi** [comment]
@qapt there are two options as listed above

**Comment by qapt** [comment]
I think we just commented at the same time. Thanks for the reply, that should fix the issue.
