### ISSUE TITLE
Specifying placeholder or initial data should give data prop a different type

### ISSUE THREAD

**Issue by james2mid** [tannerlinsley/react-query#2288]
**Describe the bug**
This bug is solely for the benefit of using `react-query` with TypeScript.

When specifying the `initialData` option, I don't think the `data` prop should be unioned with `undefined`. Then whenever you want to use the `data` of the returned object, you have to apply the non-null assertion operator (`!`) to use it's value.

I assume this also applies to `placeholderData` but I've not used it so not 100% here.

**To Reproduce**
Make a call to the `useQuery` hook with specifying either `initialData` or `placeholderData`.

**Expected behavior**
When either `initialData` or `placeholderData` is specified, then `data` is not unioned with `undefined`.

**Comment by TkDodo** [comment]
this is similar to https://github.com/tannerlinsley/react-query/issues/2306, and the answer is also the same:

- It's very hard to make that happen on type level
- queries can also be `disabled`, in which case `status` is `idle` and `data` is `undefined`
- every setting can be set globally in the `QueryClientProvider` or via `queryClient.setQueryDefaults`.

I actually thought "how hard can it be" and wanted to take a quick stab, but imo it would mean introducing many more generics. For what it's worth, you don't need the non-null assertion operator, you can use optional chaining.
