### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by lukaszfiszer** [tannerlinsley/react-query#23]
First of all - thanks for great library. It simplified data fetching in my apps by order of magnitude.

The biggest feature I'm missing is Typescript support - to the point I have manually added TS definitions to most part of the API by hand. @tannerlinsley would you be interested in having them added to definitely-typed? AFAIK this is a recommended way of adding typings to projects that are not written in TS.

**Comment by tannerlinsley** [comment]
Yes! Go for it. Once they are added there I will add them as a dependency for react query.

Tanner Linsley

**Comment by jparr721** [comment]
@lukaszfiszer in the meantime, would you be willing to share you types file? I'd like to use this in my typescript project.

**Comment by lukaszfiszer** [comment]
@jparr721 sure: https://gist.github.com/lukaszfiszer/0c1accfe49ede30f21ce99cfa6d51dcb

**Comment by rostero1** [comment]
I tried converting the codebase to Typescript, but had to quit an hour in.  I've also never used Typescript before.  I gave up when I realized the Data type was different for paginated results.

It doesn't compile, is only halfway done, and I probably introduced errors, but I'll leave it here for anyone that's interested.

https://gist.github.com/rostero1/4ad7088d445730a03cfdbf8475d3ea26

**Comment by tannerlinsley** [comment]
I would focus on just providing exported type defs for now.

Tanner Linsley

**Comment by lukaszfiszer** [comment]
PR created in definitely-typed: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/40312

If anyone want to test those definitions locally in their project that would be a great help!

**Comment by lukaszfiszer** [comment]
@tannerlinsley Thanks for review in dt repo. 

However I've discovered there is an issue with types of `useQuery`. The `data` in `QueryResult` should be an array of resolved values when `options.paginated=true`. This is very difficult or even impossible to represent in Typescript - types cannot depend on runtime values. 

For me it looks like that there are two versions of API of `useQuery`. Can you consider splitting it into the separate methods? Kind of like `prefetchQuery` is separated, even though it shares most of the options.

**Comment by tannerlinsley** [comment]
Hmm. Not going to lie, I really don’t like when types restrict things like this. The library could grow in size because of a decision like this. Are you sure there is no way to do this?

Tanner Linsley

**Comment by siebertm** [comment]
> However I've discovered there is an issue with types of `useQuery`. The `data` in `QueryResult` should be an array of resolved values when `options.paginated=true`. This is very difficult or even impossible to represent in Typescript - types cannot depend on runtime values.

I think this should be doable by defining a method overload on the type, like this:

```ts
interface QueryOptionsWithPagination extends QueryOptions {
  paginate: true
}

export function useQuery<TResult, TVariables extends object>(
    queryKey: QueryKey<TVariables>,
    queryFn: QueryFunction<TResult, TVariables>,
    options?: QueryOptionsWithPagination<TResult>
): QueryResult<TResult[], TVariables>;
```

I did not try it out, but that should do the trick.

**Comment by siebertm** [comment]
But, why can't the user just annotate with the proper type?

```ts

async function fetchPosts(): Promise<Post[]> {
  // ...
}

const { data, fetchMore } = useQuery<Post[]>('posts', fetchPosts, { paginated: true })
```

which can even be reduced due to TS type inferrence:

```ts

async function fetchPosts(): Promise<Post[]> {
  // ...
}

const { data, fetchMore } = useQuery('posts', fetchPosts, { paginated: true })
```

now `data` is of type `Post[] | null` and everything is fine.

I'd see it as a non-use case to have the same Query either paginated or not in the same component, wdyt?

**Comment by siebertm** [comment]
BTW: I tried some basic use cases in out TS code, it just works! Great work!

**Comment by tannerlinsley** [comment]
Types are now available via `@types/react-query`. For convenience, they are a dependency of this library by default.

**Comment by lukaszfiszer** [comment]
@siebertm you right, definition overloading does the trick. I've submitted a PR to types package: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/40399

**Comment by bgazzera** [comment]
Hi @lukaszfiszer one question, shouldn't all the properties be optional?

```typescript
export interface QueryOptions<TResult> {
    manual?: boolean;
    retry?: boolean | number;
    retryDelay?: (retryAttempt: number) => number;
    staleTime?: number;
    cacheTime?: number;
    refetchInterval?: false | number;
    onError?: (err: any) => void;
    onSucess?: (data: TResult) => void;
    suspense?: boolean;
}
```

**Comment by lukaszfiszer** [comment]
@bgazzera well they are: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-query/index.d.ts#L26

Didn't you mean options passed to `ReactQueryConfigProvider`? If yes, the fix is on the way: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/40514

**Comment by bgazzera** [comment]
Thanks! Yes you are right 😅

**Comment by LucaDe** [comment]
Hey @lukaszfiszer , thanks for adding types. Do you have any plans to update them to match the newest react-query version? If not, I can support as well.

**Comment by julianwachholz** [comment]
@LucaDe type definitions for v1 are being worked on here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/42830

**Comment by LucaDe** [comment]
my bad, didn't see it. Awesome!!

**Comment by JeremiAnastaziak** [comment]
@tannerlinsley seems like typings in DefinitelyTyped are outdated, could you please take care about it?

**Comment by tannerlinsley** [comment]
@JeremiAnastaziak. I'm sorry they're out of date! Unfortunately, that's not my responsibility right now and is one of the reasons that they are 3rd party.

**Comment by JeremiAnastaziak** [comment]
sure, if u ever plan to add official support, I would love to help

**Comment by cynosurecreative** [comment]
If the examples provided could demonstrate some robust typescript examples that would be fantastic

**Comment by tannerlinsley** [comment]
PRs are open!

**Comment by tannerlinsley** [comment]
FYI - https://github.com/tannerlinsley/react-query/discussions/362

**Comment by hmtri1011** [comment]
Hi all, just give a try on react-query, do we plan to update the type definitions? It seem outdated.

![image](https://user-images.githubusercontent.com/16288424/80198279-09e62100-864a-11ea-9e08-854aa33f3da8.png)
