### ISSUE TITLE
Question: hot to keep results always fresh (prevent them from going stale)?

### ISSUE THREAD

**Issue by alexbepple** [tannerlinsley/react-query#230]
The only way I have found is to set `staleTime` to a very high value. Surprisingly, though, `Number.MAX_SAFE_INTEGER` did not work. react-query kept revalidating.

Setting `staleTime` to a very high value bothers me slightly because I need to concern myself with incidental details.

Is there a clean way to effectively set `staleTime` to infinite?

**Comment by tannerlinsley** [comment]
Just set it to a large amount of time that would surpass the life of your users session length.

`staleTime: 1000 * 60 * 60 * 24 * 365 // One year`

**Comment by tannerlinsley** [comment]
Also, this should have been posted in the Discussions tab. :) I'll convert it to that now.
