### ISSUE TITLE
useInfiniteQuery Modify Custom Props Not Work Correctly

### ISSUE THREAD

**Issue by dim0147** [tannerlinsley/react-query#2302]
**Describe the bug**
- Not sure it's a bug or I missing knowledge but when using **useInfiniteQuery** at second parameters 
![image](https://user-images.githubusercontent.com/44487221/119088518-624d4500-ba3b-11eb-906a-76bc32629c82.png)
here is **fetchMovies** when I assign new properties from custom prop like this 
![image](https://user-images.githubusercontent.com/44487221/119088708-aa6c6780-ba3b-11eb-8682-6493d89fa2a2.png)
the fetch won't fetch correctly, it keep fetching the initialize result. to fix this have to **clone** the object
![image](https://user-images.githubusercontent.com/44487221/119088823-db4c9c80-ba3b-11eb-8134-e6db24d42f0b.png)

**Comment by dim0147** [comment]
Note: the **querySearch** is the prop of component, I pass this prop into **useInfiniteQuery** 
![image](https://user-images.githubusercontent.com/44487221/119089073-31b9db00-ba3c-11eb-8eed-dee2fa3e79da.png)

**Comment by TkDodo** [comment]
sorry, I have no idea what you are trying to achieve. converting this to a discussion so that we can discuss it.

`pageParam` is "calculated" in the `getNextPageParam` function - have you implemented that? The result of that function is passed as `pageParam` to the `queryFn` ....
