### ISSUE TITLE
types for data field can be undefined in suspense mode.

### ISSUE THREAD

**Issue by alisajadih** [tannerlinsley/react-query#2306]
hi. I'm using react query for my data fetcher in react experimental and typescript. but the return type of useQuery hook shows that data could be undefined. but actually not!. if query is fetching or has some problem in concurrent mode, it should throws an error, and boundaries will catch them.

```const res = useQuery<Books>(key,fetcher)```
```//res.data is Books | undefined```

**Comment by tomparkp** [comment]
@alisajadih Not a maintainer but this has been captured in some other issues - the data will be `undefined` if you disabled the query for example:

```js
const {data} = useQuery<Books>(key, fetcher, {enabled: false})
```

This is something specific to react-query, not suspense itself, because you can disable queries (for example if you only want to fetch after a certain condition is met).

**Comment by TkDodo** [comment]
additionally, it's very hard to do that on type level just by a flag. That flag can also be set globally in the QueryClientProvider. It's the same as with `initialData`.

The best we could do is provide a separate `useSuspenseQuery`, but then we'd also need an infiniteQuery version of it, and a useQueries version of it, and it kinda explodes pretty fast.

It's also just one more character to type (`res.data?.map` vs `res.data.map`) to make TypeScript happy :)

**Comment by rolivegab** [comment]
For the ones who want a quick fix for this one, you can create a `useSuspenseQuery.ts` util file in any place, and paste this code:

```typescript
import {
  QueryFunction,
  QueryKey,
  QueryObserverSuccessResult,
  useQuery,
  UseQueryOptions,
} from 'react-query';

type SuspenseQueryObserverResult<TData = unknown, TError = unknown> = QueryObserverSuccessResult<
  TData,
  TError
>;
type UseSuspenseBaseQueryResult<TData, TError> = SuspenseQueryObserverResult<TData, TError>;

type UseSuspenseQueryResult<TData = unknown, TError = unknown> = UseSuspenseBaseQueryResult<
  TData,
  TError
>;

export function useSuspenseQuery<
  TQueryFnData = unknown,
  TError = unknown,
  TData = TQueryFnData,
  TQueryKey extends QueryKey = QueryKey,
>(
  queryKey: TQueryKey,
  queryFn: QueryFunction<TQueryFnData, TQueryKey>,
  options?: Omit<UseQueryOptions<TQueryFnData, TError, TData, TQueryKey>, 'queryKey' | 'queryFn'>,
): UseSuspenseQueryResult<TData, TError> {
  return useQuery(queryKey, queryFn, options) as unknown as UseSuspenseQueryResult<TData, TError>;
}
```

It will work the same but with right types.
You can extend to accept other signatures too.

**Comment by blazzy** [comment]
> It's also just one more character to type (res.data?.map vs res.data.map) to make TypeScript happy :)

This isn't quite true. There would be a cascading effect of undefined values to guard against.

If it's a list that we are just going to map over we could fallback to an empty list `result.data?.map() ?? []`. That's not so bad, but if our response data is some kind of object the pain just compounds. My current solution to this problem is to add a top level guard and to throw an exception if data is undefined.

**Comment by TkDodo** [comment]
@blazzy this might work for your use-case, but there are many situations where data can still be `undefined` even if you use  `suspense`, so we cannot build anything into the library. One example would just be passing `enabled: false` to `useQuery`.

**Comment by blazzy** [comment]
Understood. I didn't meant to suggest react-query had to solve this. Just sharing my interim solution as I was too lazy wrap react-query at the moment.
