### ISSUE TITLE
useInfinityQueries do not resolve with new data, afer promise (on which is based on) is resolved with new data

### ISSUE THREAD

**Issue by ylalala** [tannerlinsley/react-query#2338]
Not sure if this is a library's bug, but for me is totally unexpected behawior. Basically I've looking for reasons / ideas why such thing could happens?
usage of useInfinityQuery: ![image](https://user-images.githubusercontent.com/9353285/120466894-de328000-c39f-11eb-8dc9-ae92fade387a.png)
its body:
![image](https://user-images.githubusercontent.com/9353285/120466982-f904f480-c39f-11eb-8e66-9ad9330fb275.png)
result:
![image](https://user-images.githubusercontent.com/9353285/120467153-28b3fc80-c3a0-11eb-8ee7-410a9977f676.png)

**Comment by TkDodo** [comment]
not sure what I'm seeing / should be seeing in these screenshots. Can you please describe:
- what the current behaviour is
- what the expected behaviour is

and please best provide a minimal runnable codesandbox example so that I can try it out in action, thanks.

**Comment by ylalala** [comment]
useInfinityQueries trigger a function to fetch new data - as expected. Meantime providing previous data - as expected.
But after request finished and promise is resolved with new set of data (in an example events array length changed from 15 to 16). Returned property of useInfinityQueries 'data' should be updated, but for some reason it isn't. (To show that, I've placed useEffect hook with dependency on pages)

**Comment by TkDodo** [comment]
without seeing a reproduction, I can only say it should works as expected, and it does work in the useInfinite example: https://react-query.tanstack.com/examples/load-more-infinite-scroll

**Comment by ylalala** [comment]
https://codesandbox.io/s/funny-ride-fcgdv?file=/pages/index.js

I hope that will show the problem, tbh i've already found a solution to it, but maybe it will be interesting to dig :)

**Comment by TkDodo** [comment]
nope, sorry. please post the resolution and close the issue if it is solved, thanks.

**Comment by ylalala** [comment]
Basically calling fetchNextPage on initial mount could resolve in unexpected results, my solution is simple  - avoid that use case entirely :)
