### ISSUE TITLE
Cannot read property createContext of undefined with Jest

### ISSUE THREAD

**Issue by TrueWill** [tannerlinsley/react-query#2339]
**Describe the bug**

Getting

> TypeError: Cannot read property 'createContext' of undefined

on `import { useQuery } from 'react-query'` when running tests with Jest.

**To Reproduce**

We saw this when using a jest.config.js with the line `moduleDirectories: ['node_modules', './'],`
react-query v3.16.0

**Expected behavior**
Every other library works fine with Jest.

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - Browser: n/a - running tests with Jest v26.6.3 and Node v14.17.0

**Additional context**

A coworker figured out a fix based on https://github.com/blitz-js/blitz/pull/1323 - changing the Jest config to `moduleDirectories: ['node_modules', '<rootDir>'],`. But this is the only library that's affected by it. According to the linked issue, this is caused by react-query having `require("react")` inside a folder named react.

**Comment by brainer1** [comment]
+1, having the same issue here

**Comment by TkDodo** [comment]
This is not the first time that having a sub-directory named `react` has led to some confusion for bundlers. I’d generally support a rename, not sure to what though (suggestions welcome), and also not sure if @tannerlinsley agrees :)

**Comment by TimMouskhelichvili** [comment]
Hey any updates on this?

**Comment by TkDodo** [comment]
should we just rename it to `reactjs` ?

**Comment by TkDodo** [comment]
@TrueWill would you like to contribute this?

**Comment by TrueWill** [comment]
> @TrueWill would you like to contribute this?

Sorry - I don't even have time to update my own OS projects right now. :/

**Comment by EddyVinck** [comment]
I am going to try to fix this on Friday, we have an OSS contribution day at work.

**Comment by EddyVinck** [comment]
@TrueWill @TkDodo I tried creating a reproduction in CodeSandbox but I can't reproduce it there 

https://codesandbox.io/s/react-query-2339-xgupz?file=/src/TestComponent.test.js

I'll try to create a reproduction locally

**Comment by EddyVinck** [comment]
PR open 🚀

**Comment by TkDodo** [comment]
will be available in v4.
