### ISSUE TITLE
Documentation website

### ISSUE THREAD

**Issue by nainardev** [tannerlinsley/react-query#234]
Its better to have it in a website rather than a single README

**Comment by cherniavskii** [comment]
Curious why website is better than Readme, can you elaborate?

**Comment by tannerlinsley** [comment]
Sure a website would be great. But who is going to build and maintain that website? An assumption that I should build and maintain such a website in my spare time is unrealistic right now.

The documentation is fine in README format unless some massive problem or issue is evident that I'm not aware of.
