### ISSUE TITLE
Unexpected re-rendering order of component tree in NextJS production build on react query state update

### ISSUE THREAD

**Issue by jlwalkerlg** [tannerlinsley/react-query#2351]
**Describe the bug**
Child components receive state updates from react query hooks before the components further up the render tree. If this state dictates whether or not a parent component renders a child component, this can lead to unexpected renders of the child, since the parent child will be passed the new state and re-rendered before the parent is updated and decides not to render it.

For example, with this heirarchy:
```lang-jsx
<AuthGuard>
  <UserDetails />
</AuthGuard>
```

both `AuthGuard` and `UserDetails` might use a `useUser()` hook, but `AuthGuard` will only render its `children` prop if the `useUser()` hook returns a `user` that is not `null` or `undefined`. As such, `UserDetails` shouldn't need to check if `user` is defined, because it would expect not to have been rendered if so.

However, this is exactly what happens: on logout, when `user` is set to `null`, `UserDetails` is re-rendered first, when it shouldn't be rendered at all.

**To Reproduce**
1. Clone the repo at https://github.com/jlwalkerlg/demo:
`git clone https://github.com/jlwalkerlg/demo`
2. Run the project in production build:
`cd demo`
`npm i`
`npm run build`
`npm start`
3. Go to `http://localhost:3000`
4. Click on "Login" in the nav bar.
5. Click on "Your Account" in the nav bar to go to the account details page.
6. Click on "Logout" in the nav bar.
7. See error.
8. Also notice the order of the `console.log` statements in the browser console: `UserDetails` is the first to be re-rendered after logging out, whereas I expected it to be `AuthGuard`.

**Expected behavior**
`AuthGuard` should receive the state update from the `useUser()` react query hook first when `user` is set to `null`, and the condition under which `UserDetails` is rendered should fail. Therefore, `UserDetails` shouldn't be re-rendered at all.

**Desktop (please complete the following information):**
 - OS: macOS Big Sur version 11.2.3
 - Browser: Chrome Version 91.0.4472.77 (Official Build) (x86_64)

**Additional context**
The problem only appears in the production build of NextJS. In dev mode (`npm run dev`), everything works as expected: `AuthGuard` receives the state update first, and `UserDetails` is never re-rendered. Check the `console.log` statements to see what I mean.

I swapped react query out with a custom implementation of React's context API and everything seemed to work fine, hence why I think this might be a problem with react query. You can find the implementation using the context API under the `context` branch of the repo.

**Comment by TkDodo** [comment]
hm, I wouldn't rely on `console.log` statements that run in the render function. since you are passing it as `children` prop to `AuthGuard`, the render function of `UserDetails` "runs", but you "discard" the result by not "rendering" it. If you want it to never run, you'd need a children function:

```
<AuthGuard>
  {() => <UserDetails />}
</AuthGuard>
```

of course, for the sake of logging, you can also just put the `console.log` in a `useEffect`. It would be interesting to see if the logging order then changes. Can you maybe try to get the whole example into a codesandbox? It's also very suspicious that it works in dev mode, but not in prod mode 🤔

**Comment by jlwalkerlg** [comment]
@TkDodo I managed to get the who example into codesandbox: https://codesandbox.io/s/proud-dream-ulm70. I tried this yesterday but codesandbox kept crashing on me...

I'm not sure how to run the project in prod mode within codesandbox though, so it won't reproduce the bug running as-is in the codesandbox I linked.

Thanks for looking into this by the way.

**Comment by TkDodo** [comment]
yeah it seems to be an open codesandbox issue: https://github.com/codesandbox/codesandbox-client/issues/2027

I'll try to checkout the app later

**Comment by jlwalkerlg** [comment]
I've just updated all my packages by deleting node_modules and package-lock.json, then re-installing, and everything works fine now so this is no longer an issue for me. Not sure exactly what package was causing it but at least everything's sorted now. Thanks again @TkDodo for looking into it for me.

**Comment by TkDodo** [comment]
glad to hear it!
