### ISSUE TITLE
refetchOnWindowFocus necessary for inactive queries?

### ISSUE THREAD

**Issue by ivowork** [tannerlinsley/react-query#237]
Hi, I have a page with some data and a faceted search, a new search request is executed every time I add a filter (as expected), but if I change to another window and then return, the refetchOnWindowFocus executes not only for the current query but all inactive search queries.

Is there a usefulness to this behavior that I'm not seeing? 

Can we maybe add some way to avoid this? I can do the PR.

(react-query version 1.0.17)

**Comment by tannerlinsley** [comment]
It shouldn't be refetching inactive queries, only stale queries. Are you sure they are inactive and not stale?

**Comment by ivowork** [comment]
@tannerlinsley  please check the video, to the best of my understanding the queries are inactive.

http://somup.com/cYeloOhkkL

**Comment by tannerlinsley** [comment]
Interesting. I’ll take a deeper look at this

**Comment by cherniavskii** [comment]
I confirm, here's a codesanbox: https://codesandbox.io/s/goofy-thunder-kzfgw

I'll submit a PR later

**Comment by cherniavskii** [comment]
Wow, that was fast :D
