### ISSUE TITLE
Add tests for react-query devtools

### ISSUE THREAD

**Issue by prateek3255** [tannerlinsley/react-query#2371]
**Describe the bug**
I saw that there aren't any tests as of now for react-query devtools. 

If there is no one working on it right now, and there are plans to add tests to devtools, then I would love to work on it.

**Comment by TkDodo** [comment]
Sure, please go ahead. If you want, enabling type checking for the devtools would also be welcome :)

**Comment by prateek3255** [comment]
@TkDodo Sorry for being late 😅, Opened PR #2433 with the test cases.
