### ISSUE TITLE
Transforming with 'select' breaks data type when using onSuccess with useInfiniteQuery (TS)

### ISSUE THREAD

**Issue by joshuaaron** [tannerlinsley/react-query#2377]
**Describe the bug**
Transforming your response data using the `select` function doesn't reflect with `onSuccess`

I'm flattening the response pages into a single array, which in turn, flattens the type into `InfiniteData<Fixture> | undefined` where Fixture is my data type.

As soon as I use onSuccess and try access the data, the parameter for both the onSuccess and returned select method revert to `InfiniteData<InfiniteQueryResponse<AllFixturesResponse>> | undefined`, which is the default response pre select

Does onSuccess receive the data pre or post select, I would imagine it's post, but I'm guessing it can't infer the type returned from select, though I didn't expect it to then throw an error in the select fn too just when logging the data in there.

Anyway to circumvent this? 

**Screenshots**
<img width="708" alt="Screen Shot 2021-06-14 at 12 03 46 PM" src="https://user-images.githubusercontent.com/13953685/121945556-22634000-cd11-11eb-8458-80ab3e6c71a4.png">

<img width="709" alt="Screen Shot 2021-06-14 at 12 05 21 PM" src="https://user-images.githubusercontent.com/13953685/121945627-360ea680-cd11-11eb-87bc-11a958628a79.png">

**Using**
```bash
"react-query": "3.13.8"
"typescript": "4.2.3"
```

**Comment by TkDodo** [comment]
I think you need to annotate what type `data` is in onSuccess in order to make onSuccess work with select. I don’t know why that is exactly, seems to be a limitation with type inference. I found out the same thing with mutations and I don’t think there is a better fix to my knowledge

**Comment by joshuaaron** [comment]
> I think you need to annotate what type `data` is in onSuccess in order to make onSuccess work with select. I don’t know why that is exactly, seems to be a limitation with type inference. I found out the same thing with mutations and I don’t think there is a better fix to my knowledge

Yeah went about it the same way in the end, thanks for that.

**Comment by lukemorales** [comment]
Been experiencing this as well, I'm creating a custom hook that accepts the options object, so my code looks like this:

```ts
type FavoritesQueryOptions<T> = UseQueryOptions<string[], unknown, T, typeof favoritesKeys.default>;

export const useFavoritesQuery = <T = string[]>(
  options?: FavoritesQueryOptions<T>,
) => {
  const queryClient = useQueryClient();

  return useQuery<string[], unknown, T, typeof favoritesKeys.default>(
    favoritesKeys.default,
    fetchFavorites,
    {
      staleTime: 15000,
      onSuccess(data: string[]) {
        data.map((charactedId) =>
          queryClient.prefetchQuery(characterKeys.single(charactedId), () =>
            fetchCharacter(charactedId),
          ),
        );
      },
      ...(options || {}),
    },
  );
};
```

onSuccess is complaining that data.map does not exists on type `T`, and this brings me the question: onSuccess is supposed to receive the data returned from the fetch function, right? So, by looking at the useQuery types, shouldn't onSuccess `data` (and other methods that receive the response from the fetch function) being typed as `TQueryFnData` instead of `TData` @TkDodo @tannerlinsley ?

**Comment by TkDodo** [comment]
>  onSuccess is supposed to receive the data returned from the fetch function, right?

nope, `select` runs before the callbacks are being called, so if you have `select` specified, it would receive the transformed data.

**Comment by TkDodo** [comment]
so in your example, I think you'd need:

```diff
- onSuccess(data: string[]) {
+ onSuccess(data: T) { 
```

but I think on this level, the generic is inferred correctly, so you can leave it out. There are only troubles when `select` with a concrete return type is in the same object as a callback.

**Comment by lukemorales** [comment]
> > onSuccess is supposed to receive the data returned from the fetch function, right?
> 
> nope, `select` runs before the callbacks are being called, so if you have `select` specified, it would receive the transformed data.

Oh I see... I thought select was getting the cached data and returning what was selected/transformed.


> so in your example, I think you'd need:
> 
> 
> - onSuccess(data: string[]) {
> + onSuccess(data: T) { 
> but I think on this level, the generic is inferred correctly, so you can leave it out. There are only troubles when `select` with a concrete return type is in the same object as a callback.

Yeah, the generic was inferred correctly, but if select transforms the data before the callbacks then what I'm trying to to won't work with onSuccess, because I was going to select some data and that transformation wouldn't be an array, therefore, there'll be no map in the onSuccess data.

**Comment by lukemorales** [comment]
My plan was to use the same hook in multiple places, but one of them I'd like to only select a part of the data

**Comment by TkDodo** [comment]
yeah, I don't think we have something like this at the moment. callbacks are called whenever an observer should be informed about the changes, which means the observer will re-render. By using select, you subscribe to parts or a slice of the actual result of the queryFn - meaning your observer will only be informed about changes if the result of the queryFn changes. As far as your observer is concerned, only the transformed data exists. Hope that makes sense.

**Comment by lukemorales** [comment]
> yeah, I don't think we have something like this at the moment. callbacks are called whenever an observer should be informed about the changes, which means the observer will re-render. By using select, you subscribe to parts or a slice of the actual result of the queryFn - meaning your observer will only be informed about changes if the result of the selectFn changes. As far as your observer is concerned, only the transformed data exists. Hope that makes sense.

Got it, thanks for the explanation! I've got it working for my purposes by just verifying if data was an array, then prefetching those keys. Also, the useQuery generics were inferred correctly just by the UseQueryOptions type, so the code just got a lot cleaner:

```tsx
type FavoritesQueryOptions<T> = UseQueryOptions<string[], unknown, T, typeof favoritesKeys.default>;

export const useFavoritesQuery = <T = string[]>(options: FavoritesQueryOptions<T> = {}) => {
  const queryClient = useQueryClient();

  return useQuery(favoritesKeys.default, fetchFavorites, {
    staleTime: 15000,
    onSuccess(data) {
      if (Array.isArray(data)) {
        data.map((charactedId) =>
          queryClient.prefetchQuery(characterKeys.single(charactedId), () =>
            fetchCharacter(charactedId),
          ),
        );
      }
    },
    ...options,
  });
};
```

**Comment by TkDodo** [comment]
It will work to some extend, so as long as you don't `select` into an `Array` that doesn't contain `characterIds` :)

```
select: data => ["foo", "bar", data.length]
```

**Comment by lukemorales** [comment]
Yeah, that would be a problem. Is there a better secure way to watch for cached data changes other than select? QueryClient would just get me the data at the moment the component access it, right? It wouldn't know when that accessed data has changed

**Comment by lukemorales** [comment]
> It will work to some extend, so as long as you don't `select` into an `Array` that doesn't contain `characterIds` :)
> 
> ```
> select: data => ["foo", "bar", data.length]
> ```

I'm just preparing a mini course for my company to implemente React Query, so this case wouldn't be an issue, but if there's a better safer way to teach what I'm trying to do, it would be great!

**Comment by TkDodo** [comment]
> QueryClient would just get me the data at the moment the component access it, right?

Yes, that's right. For anything that watches, you'd have to subscribe to the cache. Have a look at how `useIsFetching` is doing it:

https://github.com/tannerlinsley/react-query/blob/4a821b0f1f94fecdc0c19d1d914aa1f4a2cc0e6d/src/react/useIsFetching.ts#L34

The devtools also do it in a similar way
