### ISSUE TITLE
getQueryData and getQuery should be able to return all queries grouped by string part of the queryKey

### ISSUE THREAD

**Issue by smashercosmo** [tannerlinsley/react-query#238]
**Current behaviour:**
```js
usePaginatedQuery(
    [ 'todos', { page: 1, limit: 10 }], 
    fetchTodos
  )
```
```js
usePaginatedQuery(
    [ 'todos', { page: 2, limit: 10 }], 
    fetchTodos
  )
```
```js
useQuery(
    ['todos', { todoId } ],
    fetchTodo,
    {
      initialData() {
        const todos = queryCache.getQueryData('todos') // <= THIS WILL RETURN UNDEFINED
        return todos?.find(todo => todo.id === todoId)
      },
    },
  )
```

**Expected behaviour:**
If query variables are not provided getQueryData and getQuery methods should return cached data related to string part of the queryKey

**Comment by tannerlinsley** [comment]
Currently there is no method available like `getQueries` (plural) to search for queries on a partial key match. This would be pretty trivial to add though.

**Comment by tannerlinsley** [comment]
Would you like to work on a pull request?

**Comment by smashercosmo** [comment]
Sure. I assume it would something like
```
cache.getQueries = queryKey => findQueries(queryKey)
```

**Comment by tannerlinsley** [comment]
It would essentially be a direct proxy of the internal findQueries function.

**Comment by smashercosmo** [comment]
Here you go https://github.com/tannerlinsley/react-query/pull/240
Not sure about the docs

**Comment by tannerlinsley** [comment]
Perfect!
