### ISSUE TITLE
React Native RefreshControl component flickering with useQuery

### ISSUE THREAD

**Issue by krakz999** [tannerlinsley/react-query#2380]
**Describe the bug**

RefreshControl flickers when pulled down when using `isFetching` value as its `refreshing` prop. Does not happen when I test it with React state.

**To Reproduce**

1. Create a query
2. set RefreshControl refreshing value to the query's isFetching value, and invoke refetch from RefreshControl's onRefresh callback

```
const {data, isFetching, refetch} = useQuery('test-key', () =>
    api.get('/test-data'),
  );

  return (
      <FlatList
        refreshControl={
          <RefreshControl
            tintColor={colors.accent}
            refreshing={isFetching}
            onRefresh={refetch}
          />
        }
       ....
/>
```

**Expected behavior**
RefreshControl should not flicker

**Screenshots**
Wrong behaviour (with useQuery):
https://user-images.githubusercontent.com/22370549/122097317-d64af500-ce0f-11eb-907a-d81fb0d16a9c.mov

Correct behaviour (with setState):
https://user-images.githubusercontent.com/22370549/122097378-e7940180-ce0f-11eb-94b2-3965c06f71a3.mov

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone 12 Simulator]

**Comment by den1n** [comment]
The same issue with RefreshControl on Android emulator.

**Comment by krakz999** [comment]
@den1n found any solution?

**Comment by den1n** [comment]
@krakz999 Unfortunately, not.

**Comment by Kolandrious** [comment]
The solution is to mirror `isFetching` with local state. Set the local state when refreshing. Use hook to update the local state.
```jsx
function SomeScreen() {
  const { data, isLoading, isFetching, refetch } = useQuery(GET_SOMETHING_KEY, request, options);
  // to avoid bouncy behavior when pulling to refresh
  // https://github.com/tannerlinsley/react-query/issues/2380
  const [fetching, setFetching] = React.useState(isLoading);

  const handleRefresh = () => {
    setFetching(true);
    refetch();
  };

  React.useEffect(() => {
    setFetching(isFetching);
  }, [isFetching]);

  return (
    <ScrollView refreshControl={<RefreshControl refreshing={fetching} onRefresh={handleRefresh} />}>
      <OtherComponents />
    </ScrollView>
  );
}
```
For now, this solution works for me, but there might be a better fix

**Comment by wcelery** [comment]
hi guys, wrote small hook to hide the logic
```js import React from "react";
import { QueryObserverResult, RefetchOptions, RefetchQueryFilters } from "react-query";

export function usePreventFlickering(
  isFetching: number, //or bool
  refetch: (
    options?: (RefetchOptions & RefetchQueryFilters<any>) | undefined
  ) => Promise<QueryObserverResult<any, unknown>>
) {
  const [fetching, setFetching] = React.useState(isFetching ? true : false);

  const handleRefresh = () => {
    setFetching(true);
    refetch();
  };

  React.useEffect(() => {
    setFetching(isFetching ? true : false);
  }, [isFetching]);

  return { fetching, handleRefresh };
}

**Comment by arnaudbzn** [comment]
We use the following hook in our screens using `FlatList` `refreshControl`:
```ts
export function useRefreshByUser(refetch: () => Promise<unknown>) {
  const [isRefetchingByUser, setIsRefetchingByUser] = React.useState(false);

  async function refetchByUser() {
    setIsRefetchingByUser(true);
    await refetch();
    setIsRefetchingByUser(false);
  }

  return {
    isRefetchingByUser,
    refetchByUser,
  };
}
```
usage:
```ts
  // refetch is from useQuery() or useInfiniteQuery()
  const { isRefetchingByUser, refetchByUser } = useRefreshByUser(refetch);
  
  ...
  <RefreshControl
              refreshing={isRefetchingByUser}
              onRefresh={refetchByUser}>
```
We have no flickering issue and the `refreshing` is true only when the user refresh on swipe (we have another loading indicator when the screen is displayed).

**Comment by TkDodo** [comment]
let's please document this in the docs as a known limitation for now, preferably on the https://react-query.tanstack.com/react-native page.

**Comment by emilje** [comment]
Got it working like so:
`import { useCallback, useEffect, useState } from "react";
import { QueryObserverResult } from "@tanstack/react-query";

const useScrollViewRefetch = (
  isFetchingMaster: boolean,
  refetchMaster: () => Promise<QueryObserverResult<any, Error>>
) => {
  const [isFetching, setIsFetching] = useState(false);

  useEffect(() => {
    setIsFetching(isFetchingMaster);
  }, [isFetchingMaster]);

  const refetch = useCallback(() => {
    refetchMaster();
    setIsFetching(true);
  }, [refetchMaster, setIsFetching]);

  return { isFetching, refetch };
};

export default useScrollViewRefetch;
`
Usage:
`
  const commentsQuery = useEventComments(eventId);
  const { isFetching, refetch } = useScrollViewRefetch(commentsQuery.isFetching, commentsQuery.refetch);

  <RefreshControl refreshing={isFetching} onRefresh={refetch} />
`
