### ISSUE TITLE
Issue with react-query and react-router calling the query again before navigating away from the page.

### ISSUE THREAD

**Issue by Pau1fitz** [tannerlinsley/react-query#2399]
**To Reproduce**
I am using `react-query` v.3.16.0  with `react-router-dom`. I am having an issue when I navigate from a component with a sibling component using match params. 

For example I have a page with a list of Football Leagues (Leagues component in code sandbox) When I go to this page and navigate to an individual league if you check the console you can see that the useQuery gets recalled in the Leagues component gets called again, although it shouldn't as this component has unmounted and the individual `League` component is visible.
See [codesanbox here](https://codesandbox.io/s/react-router-basic-forked-skohk?file=/example.js) which will demonstrate the problem more clearly.

**Expected behavior**
I would expect when I navigate to a component (League) that is not the component (Leagues) where the useQuery exists that that query should not be called again before navigating away from that component.

**Desktop **
 - OS: osx
 - Browser: chrome
 - Version: 91.0.4472.114

Let me know if any more information is required.

**Comment by TkDodo** [comment]
Looks like a standard background update because queries are immediately marked as stale and a new observer mounts. This is the desired default behaviour of react-query (stale-while-revalidate).

please see:
- https://react-query.tanstack.com/guides/important-defaults
- https://react-query.tanstack.com/guides/caching
- https://tkdodo.eu/blog/practical-react-query

**Comment by Pau1fitz** [comment]
adding `refetchOnWindowFocus: false` seems to prevent it, but this seems slightly odd, as it's not really a window focus and I don't necessarily want to get rid of this behaviour.

**Comment by TkDodo** [comment]
refetchOnMount is what you are looking for, or even better, customize a staleTime on the query.

**Comment by Pau1fitz** [comment]
`refetchOnMount` doesn't seem to fix the issue

**Comment by ggregoire** [comment]
I see the same issue on my project, when I'm navigating to another page, react-query refetches the queries from the page I'm leaving before fetching the queries for the new page. I'm using react-router too.

**Comment by Pau1fitz** [comment]
@ggregoire are you focusing between the browser and devtools? That was what I was doing, and is what made me believe that this bug was occurring.

> If you see a refetch that you are not expecting, it is likely because you just focused the window and React Query is doing a refetchOnWindowFocus
> [...]
> During development, this will probably be triggered more frequently, especially because focusing between the Browser DevTools and your app will also cause a fetch, so be aware of that.

**Comment by ggregoire** [comment]
@Pau1fitz  My devtools was open on the Network panel but I was not focusing it. Perhaps the focus automatically switches between both? Or maybe some weird interaction with a Chrome extension, not sure.

Anyway, there was also a refetch when I clicked on a input file (which opens a new window to select a file) and I didn't understand why, but now with your reply it totally makes sense. 😉

Thanks!

**Comment by Pau1fitz** [comment]
yeah it had me pretty stumped also 😀

you can add `refetchOnWindowFocus: false` globally which prevents this. Or else you can do it on an individual query level. There are instructions [here](https://react-query.tanstack.com/guides/window-focus-refetching#disabling-globally).

**Comment by TkDodo** [comment]
`refechOnWindowFocus: process.env.NODE_ENV !== 'development'`

I have this also as a potential gotcha in my first part of react-query related articles: https://tkdodo.eu/blog/practical-react-query#the-defaults-explained

**Comment by Pau1fitz** [comment]
@TkDodo should this be added to the official docs? seems to be catching quite a few people out.

**Comment by TkDodo** [comment]
I’d say it’s mentioned on this page, but if you’d like to extend that, I’ll gladly accept a PR: https://react-query.tanstack.com/guides/important-defaults

**Comment by Pau1fitz** [comment]
@TkDodo created a PR explaining that re-fetches could occur more often during development due to focusing on the devtools  #2413

**Comment by ggregoire** [comment]
> `refechOnWindowFocus: process.env.NODE_ENV !== 'development'`
> 
> I have this also as a potential gotcha in my first part of react-query related articles: [tkdodo.eu/blog/practical-react-query#the-defaults-explained](https://tkdodo.eu/blog/practical-react-query#the-defaults-explained)

Thanks for the blog! I just read the entire series about React Query and learned a lot!
