### ISSUE TITLE
Feature request: failureCount for onError

### ISSUE THREAD

**Issue by ejkkan** [tannerlinsley/react-query#2406]
The retry callback is today receiving a "failureCount" param. Today, I'm using the for displaying alert of how the requests are doing. So for failureCount === 0, I know I can alert the user that something went wrong, but I don't want to trigger this for every callback since they are not really triggered by the result of the actual request, they are triggered for each use of the query/mutation.

I believe that for this usecase, it would be a lot more clear to be able to check this in the onError callback. But also that this belongs belongs to the context of onError overall. 

**To Reproduce**
1. make sure a query triggers error
2. use the query from multiple places
3. try to use some kind of functionality that you only want to trigger for the request that acutally makes the external request to an api from any of the senesible callback you would want to use.
4. see it trigger each time you invoke the query

**Expected behavior**
I would want to have either a specific callback that only triggers for the one query that actually makes the external request, or having the failureFlag used as param in more of the callback that it context makes sense.

**Desktop (please complete the following information):**
 - OS: mac
 - Browser: chrome
 - Version: latest

**Smartphone (please complete the following information):**
 - Device: iPhone
 - OS: all
 - Browser: chrome
 - Version: latest

**Comment by TkDodo** [comment]
> I would want to have either a specific callback that only triggers for the one query that actually makes the external request

I think you are looking for the `onError` callback on the QueryCache: https://react-query.tanstack.com/reference/QueryCache

This one will only be called once per request, _not_ per observer.
