### ISSUE TITLE
infinite query refetching after item deletion causes duplication

### ISSUE THREAD

**Issue by aryan340** [tannerlinsley/react-query#2418]
**Describe the bug**
infinite query refetching after item deletion (mutation) causes data duplication

**Simplified example**
Let's say that we have an api that returns items in sets of 5 (for simplicity).
```json
{ 
  "nextCursor": 6, 
  "results": [
   {" id": 1 }, 
   { "id": 2 }, 
   { "id": 3 },
   { "id": 4 },
   { "id": 5 }
  ]
}
```

```js
// external api call
const fetchNotes = ({ pageParam = 0 }) => ...

const useNotes = () => {
    return useInfiniteQuery("notes", fetchNotes, {
        getNextPageParam: (lastPage, pages) => lastPage.next,
        getPreviousPageParam: (firstPage, pages) => firstPage.previous
    })
}
```

say we remove an item from this list.
```js
// external api call
const destroyNote = (noteID) => ...

const useDestroyNote = () => {
    const queryClient = useQueryClient();
    return useMutation(destroyNote, {
        mutationKey: "destroyNote",
        onSuccess: () => queryClient.refetchQueries("notes"),
    })
}
```
Here, we are refetching queries after destroying the note (which is a common pattern).
From #407 I can see that pages are fetched sequentially while refetching.

Here is a possible flaw I discovered.

After we destroy an item, while refetching (onSuccess), if we get a page whose `nextPageParam` is none, then the refetch process is repeated (causing duplication). Hopefully, I have made this simple enough to understand via the added screenshots.

**Screenshots**
![image](https://user-images.githubusercontent.com/69184573/123975976-67f35e80-d9db-11eb-876f-e1797b8cab2b.png)

Here is the data returned before the query is refetched another time
![image](https://user-images.githubusercontent.com/69184573/123976284-a6891900-d9db-11eb-9249-84b84a70dc68.png)

(the nextPageParam is null over here).
**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 91

**Comment by aryan340** [comment]
https://user-images.githubusercontent.com/69184573/123986859-51053a00-d9e4-11eb-9abd-c4ca55636209.mp4

the user interface is completely broken down.
Here's a recording.

**Comment by aryan340** [comment]
https://github.com/tannerlinsley/react-query/blob/master/src/core/infiniteQueryBehavior.ts#L17

Over here,we are referencing the old pages and refetching for old page number of times. However, in this edge case, the old page's length is not synced ( a page has been removed by removing the last item present in it).

For now, I have identified this to be the source of this bug.
Hopefully, fixing this logic will resolve the issue.

**Comment by aryan340** [comment]
@tannerlinsley can this be fixed please? I identify that this bug is critical and I cannot use react-query in production right now.
This is a great library, though, thanks for maintaining it!

**Comment by TkDodo** [comment]
Can you provide a codesandbox reproduction please?

**Comment by aryan340** [comment]
@TkDodo  sure, I will get back to you as soon as possible!

**Comment by aryan340** [comment]
@TkDodo 
I've managed to create a rough example.
Hope it's simple.

*sandbox link*: https://codesandbox.io/s/delete-mutation-duplication-1ufym

*Instructions*:
1. Scroll down and load all the projects present in the mock api (there are 11).
2. once every project is loaded, start deleting projects one by one.
3. Once you've deleted about 5 projects, you'll find duplicated project components loaded below (this is the referred bug).

**Comment by TkDodo** [comment]
I've narrowed the issue down to the `getNextPageParam: (lastPage) => lastPage.nextPage` method.

The backend returns `nextPage: null` for this case, which react-query happily forwards to the queryFn. We can then see a request to `api/projects?page=null`, which returns the wrong data.

What you need to do, and this is also in the docs (https://react-query.tanstack.com/reference/useInfiniteQuery), is to return `undefined` to indicate that there is no further page.

So I've changed that method to:

```
getNextPageParam: (lastPage) => lastPage.nextPage ?? undefined
```

and now I'm no longer getting that weird behaviour. Can you double check that please

---

Now I think we need to 1) make this maybe more prominent in the docs and 2) I think it's weird that the infinite query even stops fetching initially if we return null... also, `hasNextPage` returns false if we return null / undefined or false, which is definitely inconsistent. We can see that here: 

https://github.com/tannerlinsley/react-query/blob/3d2806edb43c557be201e214edb0d503be3159f9/src/core/infiniteQueryBehavior.ts#L151-L156

Not sure how to fix this without doing a breaking change 🤔

**Comment by aryan340** [comment]
@TkDodo thanks for your response, I cannot check right now because I cannot access the backend for some time.
However, I think that this will fix it. Cheers!

Maybe for now, we could just update the docs without any breaking changes.

**Comment by TkDodo** [comment]
> Maybe for now, we could just update the docs without any breaking changes.

yes, I think we should do that. I'd appreciate a PR and will close this issue in the meantime.
