### ISSUE TITLE
Cursor Jumps to End of Input on Optimistic Updates

### ISSUE THREAD

**Issue by weipinglim14** [tannerlinsley/react-query#2424]
Hi,

## Issue
I am trying to perform optimistic updates during input field `onChange` and the cursor would jump to the end of input.

## Expected Behavior
When making changes to the input field, cursor should remain at the same position.

## Link

https://codesandbox.io/s/react-query-optimistic-input-field-ci27w?file=/src/App.js

## How to Replicate

To replicate the issue, make changes to the input field anywhere before the end of input. Any changes would force the cursor to the end of input.

**Comment by TkDodo** [comment]
not sure what is going on here, but I was able to reproduce this with react useState as well. It seems to be an async issue ?

https://codesandbox.io/s/react-query-optimistic-input-field-forked-deytr?file=/src/App.js

There is also this stackoverflow issue:

https://stackoverflow.com/questions/28922275/in-reactjs-why-does-setstate-behave-differently-when-called-synchronously

Don't think there is a lot we can do

**Comment by willy2dg** [comment]
> not sure what is going on here, but I was able to reproduce this with react useState as well. It seems to be an async issue ?
> 
> https://codesandbox.io/s/react-query-optimistic-input-field-forked-deytr?file=/src/App.js
> 
> There is also this stackoverflow issue:
> 
> https://stackoverflow.com/questions/28922275/in-reactjs-why-does-setstate-behave-differently-when-called-synchronously
> 
> Don't think there is a lot we can do

This still an issue, you added an sleep to you react example, which doesn't apply since documentation says 'setQueryData is a synchronous function that can be used to immediately update a query's cached data' so unsell you can reproduce the issue without sleep seems to be a TanStack problem

**Comment by TkDodo** [comment]
what the docs say is correct. The QueryCache is updated synchronously. You can call `queryClient.getQueryData` right after calling `setQueryData`, and it will be available.

But then the react adapter informs the observer (the custom hook) in an async way. This always happens asynchronously to batch updates together in a more performant way.

**Comment by willy2dg** [comment]
Seems a bit contraintuitive, i was specting some kind of 'setQueryState' to handle the data like another state without invalidating queries, but got this undesired result. Could be helpfull some note or havnig a feature like that.

Thanks for your fast answer and clarifications.
