### ISSUE TITLE
fetchMore is not working if call it immediately 

### ISSUE THREAD

**Issue by nucleartux** [tannerlinsley/react-query#244]
Here small example with reproduction of bug (i'm not sure it's bug or not though): https://codesandbox.io/s/clever-wing-wympu
Try remove `setTimeout` on line 70 and react-query loads only first 3 result (expected 6).

In real situation it happens with libraries such as react-virtualized, they sometimes try to load next page immediately after getting first result.

**Comment by tannerlinsley** [comment]
Hmm. I'm not sure if this is a bug either. Is this a real use case you have or just something you stumbled upon?

**Comment by nucleartux** [comment]
Yes, this is real use case. Imagine infinite scroll on large screen, for example I'm loading 10 rows per request, but on screen I can see around 15, so my app loads next 10 rows immediately.

**Comment by tannerlinsley** [comment]
After much investigation, it's going to have to be required that you set a timeout for this specific edge case. Where the component is still in the first render phase and before side-effects have run (to resolve the query promise), calling the fetchMore will get debounced with the still-in-flight request. By setting a timeout, you get around this, however that doesn't cover all of the other use cases you'll run into.

This sandbox shows a more stable way to approach triggering the load more function (which is indeed outside the scope of React Query, but a very valid use case): https://codesandbox.io/s/agitated-bardeen-m06zt
