### ISSUE TITLE
Module  has no exported member SetDataOptions and QueryFilters

### ISSUE THREAD

**Issue by IlyaZaprutski** [tannerlinsley/react-query#2448]
**Describe the bug**
How can I import types for SetDataOptions and QueryFilters?

**To Reproduce**
```
import { QueryFilters, SetDataOptions } from 'react-query';
```

**Expected behavior**
I should be able to import SetDataOptions and QueryFilters

**Screenshots**
![image](https://user-images.githubusercontent.com/10133494/125056029-824ecb80-e0b0-11eb-90d8-86d0aa68efd0.png)

**Comment by TkDodo** [comment]
Not sure why we don't export it. I guess you could `extract` it from the params of the functions that have it, but I guess we can also expose it. Care to open a PR?

**Comment by TkDodo** [comment]
A bit convoluted, but you can also do:

```
type QueryFilters = NonNullable<Parameters<QueryClient['getQueryData']>[1]>
type SetDataOptions = NonNullable<Parameters<QueryClient['setQueryData']>[2]>
```
