### ISSUE TITLE
Module react-query/createAsyncStoragePersistor-experimental has no exported member createAsyncStoragePersistor

### ISSUE THREAD

**Issue by ElGecko76** [tannerlinsley/react-query#2456]
**Describe the bug**

I installed the latest version of React Query (3.18.1) to use `AsyncStoragePersistor` but I get this typescript error:

> TS2305: Module '"react-query/createAsyncStoragePersistor-experimental"' has no exported member 'createAsyncStoragePersistor'.

When I run my React Native application, I get this error:

> react-query/createAsyncStoragePersistor-experimental could not be found within the project

I tried to remove `node_modules` folder and `package-lock.json` and run `npm install` but I get the same error.

**To Reproduce**
1. Add `"react-query": "^3.18.1"` in `dependencies` node from `package.json` file
2. Run `npm install`
3. Add this code: https://react-query.tanstack.com/plugins/createAsyncStoragePersistor#usage
4. Run the application

**Screen:**

![image](https://user-images.githubusercontent.com/19478137/125333656-c957ed80-e34a-11eb-9458-a888257a75a7.png)

**Smartphone (please complete the following information):**
 - Device: Huawei P20 EML-L29
 - OS: Android
 - Version: 10

**Additional context**
I use Expo Bare workflow

**Comment by TkDodo** [comment]
should be fixed with https://github.com/tannerlinsley/react-query/releases/tag/v3.19.0
