### ISSUE TITLE
Document QueryObject

### ISSUE THREAD

**Issue by lukaszfiszer** [tannerlinsley/react-query#246]
In order to properly write type definitions for `queryCache.getQueries` and `queryCache.getQuery` function, I would need the documentation of `QueryObject` type.

This object can be of course inspected at runtime, but it's unclear which properties are considered public and which are private.

**Comment by tannerlinsley** [comment]
The query object is deliberately undocumented for now as we find common use cases around the API and internal query object. As we find those use cases, we can slowly add documentation. PR's welcome!
