### ISSUE TITLE
useQuery onSuccess not fired

### ISSUE THREAD

**Issue by bilalesi** [tannerlinsley/react-query#2461]
Hi 
i am running a big app using react-query for managing server state
it's working properly until today (without any modification), when **useQuery** will not fire **onSuccess** after a successful fetching.
the weird thing that i am getting  the returned data but onSuccess(data) is never executed
i tried to put **cacheTime** = 0 and **staleTime** = 0 (default = 0) but no luck.
one more thing that **isLoading** do not change value to false, it's keep loading until i re-focus the window.
the same thing happen with **useMutation**, the mutation executed perfectly but 
`onSuccess :() => queryCache.invalidateQueries('Key');`
never executed.

Overall Code:
```
const queryClient = new QueryClient();
function App() {
  const messages = useMessages();
  return (
      <ErrorBoundry>
        <QueryClientProvider client={queryClient}>
          <IntlProvider locale="fr" messages={messages}>
            <BrowserRouter>
              <Layout />
              <ReactQueryDevtools initialIsOpen/>
            </BrowserRouter>
          </IntlProvider>
        </QueryClientProvider>
      </ErrorBoundry>
  );
}
```
```
const { isLoading } = useQuery(['Gather-user-files', { userId }], () => handle_gather_user_files({ userId }), {
    refetchInterval: false,
    refetchOnWindowFocus: false,
    refetchIntervalInBackground: false,
    onSuccess: (datum) => {
        let { files } = datum;
        setUserFiles(files)
      }
    }
  })
```
if i put select above **onSuccess**, it will fired normally and i get the data just in the select method.
onSuccess will have nothing
RQ devtools shows everything goes well

**Expected behavior**
Getting data in onSuccess

**Screenshots**
<img width="714" alt="Screen Shot 2021-07-14 at 21 11 14" src="https://user-images.githubusercontent.com/2632473/125686456-5d06ec70-d3bb-4ee2-b311-93700df7a817.png">

**Desktop (please complete the following information):**
 - BigSur v11
 - Browser: 
       Firefox v90, 
       Safari v14, 
       Chrome Version 91.0.4472.114

**Smartphone (please complete the following information):**
 - Device: [e.g. Huawei y9 2019]

**Additional context**

**Comment by TkDodo** [comment]
You've posted this code on multiple sources now. Here is a quick codesandbox that shows that onSuccess is working:

https://codesandbox.io/s/react-query-onsuccess-09wc2

please provide a small, reproducible example that shows your issue
