### ISSUE TITLE
isFetching remains false when refetching

### ISSUE THREAD

**Issue by ismay** [tannerlinsley/react-query#2481]
**Describe the bug**

According to the docs at https://react-query.tanstack.com/reference/useQuery: `isFetching will be true if the query is currently fetching, including background fetching.`. The comment here: https://github.com/tannerlinsley/react-query/issues/1980#issuecomment-800381568 also states: `Additionally isFetching will be true. This is always true when a request is going out.`

However, after calling refetch, isFetching remains `false` during my tests.

**To Reproduce**

1. See the minimal reproduction here: https://github.com/dhis2/react-query-repro
2. The test run on CI demonstrates the issue: https://github.com/dhis2/react-query-repro/runs/3114362559
3. The test that fails is how I expected it to work (for isFetching to be true when fetching)
4. The test that succeeds demonstrates the current situation (isFetching remains false, and at the next update the fetch has already succeeded and the new data is returned)

**Expected behavior**

I expected isFetching to be set to true after refetch and the fetcher fn have been called. Instead it seems that after they've been called isFetching is still false.

So for the test that's failing in the reproduction above to succeed (and vice versa).

**Environment:**
 - OS: Ubuntu and node 14 (running on github CI, but I can reproduce this on macOS 11.4 with node 14 as well)
 - Browser: n.a.
 - Version: see above (using react-query 3.19.0)

**Smartphone (please complete the following information):**
 - Device: n.a. (did not test on smartphone)

**Comment by TkDodo** [comment]
hmm, you're calling `refetch` here:
https://github.com/dhis2/react-query-repro/blob/6680271e89989353f1be9fe9bd6b894c3b6e148f/test/react-query.test.js#L50-L59

but then you're not waiting for the next update or anything. `isFetching` should be true after the next render transition. Sorry, haven't actually run the test yet, this would take some more time. But I'm pretty sure isFetching works and it's mainly a question of how the test is written.

**Comment by ismay** [comment]
> hmm, you're calling `refetch` here:
> https://github.com/dhis2/react-query-repro/blob/6680271e89989353f1be9fe9bd6b894c3b6e148f/test/react-query.test.js#L50-L59
> 
> but then you're not waiting for the next update or anything. `isFetching` should be true after the next render transition. Sorry, haven't actually run the test yet, this would take some more time. But I'm pretty sure isFetching works and it's mainly a question of how the test is written.

Yes that's correct. So maybe my expectations are wrong, but that's where I expected isFetching to be true. Because at that point the fetcher fn has been called (as tested by this line: https://github.com/dhis2/react-query-repro/blob/6680271e89989353f1be9fe9bd6b894c3b6e148f/test/react-query.test.js#L54).

On this line I'm waiting for the next update to the hook: https://github.com/dhis2/react-query-repro/blob/6680271e89989353f1be9fe9bd6b894c3b6e148f/test/react-query.test.js#L61, but as you can see, at that point the new data has already been returned.

So it doesn't seem like there's any point where I'm actually getting the change to isFetching (before the update it's false and there's no new data, after the update it's false and there's new data).

**Comment by ismay** [comment]
Maybe the problem is that I'm expecting isFetching to be set to true synchronously after refetch has been called? I can imagine that if it's being set async that somehow after `waitForNextUpdate`, I'm skipping over the intermediate `isFetching: true` and getting the fetched data immediately?

**Comment by TkDodo** [comment]
the way I see it, and you can see this in the examples where we show background loading indicators depending on the `isFetching` value, it should be:

- call refetch
- re-render component, isFetching is now true, data is still old
- promise resolves, component re-renders again with isFetching false and data

we do something similar here in our internal tests, but capturing of the states happens via actual component rendering, so it's a bit different. But you can see the results in the expected states:

https://github.com/tannerlinsley/react-query/blob/2b8d2af4d1d76d25c6d363db2ed0388ccbc1ccc0/src/react/tests/useQuery.test.tsx#L1541-L1624

---

a different idea: try not to use `waitForNextUpdate`, but maybe explicitly waitFor isFetching to be true, similar to what I do here: https://github.com/TkDodo/testing-react-query/blob/fd02fdfc4622ddcef5c3713ef9fc24d9df09298e/src/tests/hooks.test.tsx#L10-L16

```
await waitFor(() => result.current.isFetching)
```

on a side not, just a general question: why are you testing if react-query transitions to isFetching? This behaviour should be covered by the react-query tests internally and usually shouldn't be something that you'd need to worry about :)

**Comment by ismay** [comment]
Ah I'll add some tests that use the differerent strategies. See if they yield the result I expected.

> on a side not, just a general question: why are you testing if react-query transitions to isFetching? This behaviour should be covered by the react-query tests internally and usually shouldn't be something that you'd need to worry about :)

Yes definitely, you're right. I created this because I ran into an issue testing some code that used react-query. I wanted a minimal reproduction of it, so that it would be easier to talk about what I expected vs what I was getting. Which is why I created this.

Normally I wouldn't go and create unit tests for my dependencies 😅

**Comment by ismay** [comment]
Ok, I've updated the tests in the linked repo, tested using three different methods:

1. Assert that isFetching is true immediately after calling refetch: [here](https://github.com/dhis2/react-query-repro/blob/main/test/react-query.test.js#L24) (fails)
2. Assert that isFetching is true after calling refetch, and a rerender: [here](https://github.com/dhis2/react-query-repro/blob/main/test/react-query.test.js#L70) (succeeds)
3. Assert that isFetching is true at some point after calling refetch, using waitFor: [here](https://github.com/dhis2/react-query-repro/blob/main/test/react-query.test.js#L117) (fails)

Only test 2 succeeds. Initially I tested using method 1 and 3. Since they both failed, I figured that rerendering wouldn't make a difference (so turns out I was wrong there, as 2 shows). However, it seems strange to me that test 3 fails. Test 2 and 3 should yield identical results right?

**Comment by TkDodo** [comment]
hmm, what about:

```
await waitFor(() => result.current.isFetching === true)
expect(fetcher).toHaveBeenCalledTimes(2);
expect(result.current).toMatchObject({
  isLoading: false,
  isFetching: true,
  data: 0,
});
```

**Comment by ismay** [comment]
> hmm, what about:
> 
> ```
> await waitFor(() => result.current.isFetching === true)
> expect(fetcher).toHaveBeenCalledTimes(2);
> expect(result.current).toMatchObject({
>   isLoading: false,
>   isFetching: true,
>   data: 0,
> });
> ```

Fails as well. Added the test [here](https://github.com/dhis2/react-query-repro/commit/5d12f19eefb792015cba0a34b40ff3c186b57a92#diff-5f03d3fa4e860bed86c999a546f3eb277102488f554a8d8657e8c38449af1c26R165), and the test run is [here](https://github.com/dhis2/react-query-repro/runs/3115030317#step:5:54)

**Comment by ismay** [comment]
So since the test only passes if I manually rerender, is it possible that the unexpected behaviour is caused by a call to refetch not triggering a rerender? Because if I manually trigger a rerender in the hook I'm working on I'm getting exactly the state I suspect from react-query.

**Comment by TkDodo** [comment]
but refetch needs to trigger a re-render, because `isFetching` should turn to `true`

I created a test in my testing repo which works, please have a look: https://github.com/TkDodo/testing-react-query/blob/c5aa4856248aaf89bf6a9db5049d9563b01883d3/src/tests/hooks.test.tsx#L19-L52

essentially, I do:
- refetch
- wait for `isFetching` to be true
- assert
- wait for `isFetching` to be false
- assert again

**Comment by ismay** [comment]
> but refetch needs to trigger a re-render, because `isFetching` should turn to `true`

Exactly.

So I'm running a test that's almost identical to yours here: https://github.com/dhis2/react-query-repro/blob/main/test/react-query.test.js#L213. And for me it [fails](https://github.com/dhis2/react-query-repro/runs/3132701739#step:5:14). I'm not sure yet what the difference is between our tests that's causing mine to fail and yours to pass.

**Comment by ismay** [comment]
Ah. I see that your test description mentions that the query is disabled. But it starts fetching immediately, so it's an enabled query right?

**Comment by TkDodo** [comment]
yes, I fcked up the description, sorry. But I think this is also the reason for your test failure - you disable the query, yet you expect it immediately to be `isLoading: true`

okay, after your edit, it makes more sense. The only difference I can see between our tests is that I'm not using `jest.fn` to mock the fetch, but rather `msw` on a different layer. Maybe the mocked function returns immediately, idk.

can you try changing the `queryFn` directly to always return a `Promise.resolve` and remove the `jest.fn` ?

**Comment by ismay** [comment]
> yes, I fcked up the description, sorry. But I think this is also the reason for your test failure - you disable the query, yet you expect it immediately to be `isLoading: true`
> 
> okay, after your edit, it makes more sense. The only difference I can see between our tests is that I'm not using `jest.fn` to mock the fetch, but rather `msw` on a different layer. Maybe the mocked function returns immediately, idk.
> 
> can you try changing the `queryFn` directly to always return a `Promise.resolve` and remove the `jest.fn` ?

Removed the `jest.fn()` (see [here](https://github.com/dhis2/react-query-repro/blob/main/test/react-query.test.js#L213)) and am now directly returning the `Promise.resolve`, but the test still fails (see [here](https://github.com/dhis2/react-query-repro/runs/3132843447#step:5:14)). Strange.

**Comment by ismay** [comment]
Ok. I did some more testing and suspect something in my tests is causing the test failures. No idea why, our tests seem almost identical, but I guess something in mine is off. In apps isFetching is working as expected.

**Comment by TkDodo** [comment]
ok, let me close this then. feel free to keep the discussion going, but I don't think it's a RQ related issue

**Comment by ismay** [comment]
> ok, let me close this then. feel free to keep the discussion going, but I don't think it's a RQ related issue

Thanks! Yeah it doesn't look like it. Thanks for your patience and help in figuring this out. Appreciate it 🙏! And if I do figure out why the test results differed I'll let you know.
