### ISSUE TITLE
Key passed to fetcher incorrectly when useInifiteQuery has initialData

### ISSUE THREAD

**Issue by pawelphilipczyk** [tannerlinsley/react-query#251]
This only happens on first render it seems. 

When I'm running `fetchMore` after first render with `useInfiniteQuery` that had `initialData` passed in the fetcher function receives different arguments and it looks like it's just shifted. 

So simply my fix for that is to define fetcher function like this: `fetchMore(key, params = key)`. This fixes the case when params is `undefined` this means it's run without the key. 

This looks like a bug to me and I've discovered it along with previous bug I've created for `useInfiniteQuery`.

**Comment by cherniavskii** [comment]
Can you create reproduction example?

**Comment by tannerlinsley** [comment]
Again, I would urge you to check out this example and see if you can replicate or see the issue there: https://codesandbox.io/s/agitated-bardeen-m06zt

**Comment by tannerlinsley** [comment]
Also, since they are likely related if they are a bug, we'll just track the single issue there in #250
