### ISSUE TITLE
useQuery behavior in v3 is fundamentally different from that in v2

### ISSUE THREAD

**Issue by suhasv1995** [tannerlinsley/react-query#2517]
**Describe the bug**
I'm currently working on migrating from `react-query` v2 to v3. I noticed a fundamental difference in the behavior of `react-query` and it makes a huge difference. (especially in our test suite)

`useQuery` in `react-query` v3 undergoes one extra re-render when compared to v2. I have test cases below to prove it.

In the screenshot below, I'm simply testing out the useQuery hook and results after subsequent renders. (use both v2 and v3)
In case of v3, I must wait for two render cycles to get the results. (check the highlighted box) While in case of v2, I get the results after one render cycle.

Our tests at many places are banking on this behavior and because of an extra asynchronous cycles, the tests are breaking with `act` errors.

Am I doing something wrong? Is this behaviour intentional? Can something be done to modify this behavior?
As a user, I'd not prefer unnecessary re-renders. I feel that optimizing this behavior would the right thing to do.

**To Reproduce**
The following two repositories have tests included for v2 and v3 testing out `useQuery`.
https://github.com/suhasv1995/rq-v2-test
https://github.com/suhasv1995/rq-v3-test

**Expected behavior**
`useQuery` behavior in v3 should be similar to that in v2.

**Screenshots**
![Screenshot 2021-07-30 at 3 04 06 PM](https://user-images.githubusercontent.com/38910004/127634893-cbcd638b-a0f4-4a79-9ff3-cdbf7c5c7627.png)

**Comment by TkDodo** [comment]
let me move that to a discussion and we can re-open an issue once we've undoubtedly identified one.
