### ISSUE TITLE
Auto refetching doesn't stop when retryAttempt reach failureCount

### ISSUE THREAD

**Issue by Rhuaer** [tannerlinsley/react-query#2558]
**Describe the bug**
Auto refetching doesn't stop when retryAttempt reach failureCount

**To Reproduce**
Demo here: https://codesandbox.io/s/silly-dream-ztv01?file=/pages/index.js
1. throw an error in query function.
2. set option retry to 3 and set option refetchInterval to 1000

**Expected behavior**
If query function throw an error, React-Query should stop interval refetching, and begin to retry until retryAttempt count reach failureCount.

It should continue to interval refetch when retryAttempt count doesn't reach failureCount

**Comment by TkDodo** [comment]
I added some logging to your demo, and the behaviour looks expected:

https://codesandbox.io/s/serene-babbage-l8o57?file=/pages/index.js

the output for `status, failureCount` is:

```
loading  0
loading  1
loading  2
loading  3
Error: test
error  4
---
loading  0
loading  1
loading  2
loading  3
Error: test
error  4
```

so what we are seeing is:
- the query being in loading state with no failureCount, fetching for the first time.
- we get an error (failureCount=1), retry kicks in. now the refetchInterval of 1 second pauses.
- we retry 3 times with exponential backoff, so it takes some time.
- then we get the error logged and a final rendering in error state
- now, the refetchInterval is "back on"
--> so after 1 second, the whole thing starts again

not sure what's wrong with this behaviour, can you elaborate a bit?

if you increase the refetchInterval to 10 seconds, you will see that takes 10 seconds from when we log `error 4` and the next `loading 0`. So the refetchInterval does indeed _pause_ while we are retrying

**Comment by Rhuaer** [comment]
> now, the refetchInterval is "back on"
--> so after 1 second, the whole thing starts again

This is the problem.
If we have retried 3 times, and all fail in first round, we should never start auto refetching again.

**Comment by TkDodo** [comment]
refetchInterval works separately from retries. If a query is in error state, it will still refetch under the normal conditions. For example, on window focus, or if a new component mounts. Otherwise, we would stay in error state indefinitely. The interval doesn't care about the state of the query. It's the same as if you focus the window every N seconds, except it happens automatically.

> If we have retried 3 times, and all fail in first round, we should never start auto refetching again.

If that's what you want, you'd need to set some local state dependent on your error, and turn off polling, something like:

```
const [shouldPoll, setShouldPoll] = useState(true)
useQuery(
  key,
  fn,
  {
    refetchInterval: shouldPoll ? 1000 : 0,
    onSettled: (data, error) => setShouldPoll(!!error),
  }
)
```
