### ISSUE TITLE
When we refetch a query, it doesn't set isLoading true.

### ISSUE THREAD

**Issue by arslanalidev** [tannerlinsley/react-query#2559]
**Describe the bug**
When we refetch a query, the isLoading property doesn't set to true. It always remains false.

**To Reproduce**
1. Create a request using the useQuery.
2. Extract the refetch method from the returned object.
3. Call refetch method on any event. 
4. Now you will see that the isLoading flag is not true, if it's true then we can show the loading indication on screen.

**Expected behavior**
It should be set to true when we are re-fetching the data from the server.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 92.0.4515.131

**Additional context**
Nope

**Comment by TkDodo** [comment]
`isLoading` is only true if you have a hard loading state where you have no data. When you are refetching, you most certainly have data already, which is why the query stays in `success` state. This is the stale-while-revalidate principle react-query is built upon.

What you are most likely looking for is the `isFetching` flag, which will also be true for background updates.

**Comment by ZehuaZhang** [comment]
`IsFetching` = `isLoading` + `isRefetching`?

**Comment by TkDodo** [comment]
no, `isRefetching = isFetching && !isLoading`

**Comment by ZehuaZhang** [comment]
I think it's the same thing, `isFetching` includes `isLoading` and `isRefetching`, other words the first fetch, and refetches.

**Comment by AkshayVerma-Ipsator** [comment]
In tanStack query it is mentioned that isFetching would be of number type

**Comment by Shehryar-Naeem** [comment]
I face one issue i want to refetch the show loading show refetching loading indicator and I working correctly now I want when I like or dislike the post then refetching in background but not show refetching indicator how to do

**Comment by galletafromjell666** [comment]
> I face one issue i want to refetch the show loading show refetching loading indicator and I working correctly now I want when I like or dislike the post then refetching in background but not show refetching indicator how to do

- Create a mutation (A) for like and dislike
- Invalidate your query key for your post on the onSuccess callback from the mutation (A) 
- Invalidating the query will cause a refetch on your useQuery. So, you only need to use value from  `isFetching` to show the loading indicator
