### ISSUE TITLE
prefetchQuery fetching data even if data in cache is not invalid

### ISSUE THREAD

**Issue by lukemorales** [tannerlinsley/react-query#2560]
**Describe the bug**
The documentation says the following:
```
- If data for this query is already in the cache and not invalidated, the data will not be fetched
- If a staleTime is passed eg. prefetchQuery('todos', fn, { staleTime: 5000 }) and the data is older than the specified staleTime, the query will be fetched
```

The first statement is not working as intended, my query key has the data in the cache with a staleTime of 2 minutes, but if I access the page that prefetches the query again, and data is still marked as fresh, queryClient fires the fetch function and another call to the API is made. The API call does not happen if the staleTime is also informed to prefetchQuery options like the documentation says, but I believe that the first statement should also work as intended right? Or am I misunderstanding what the first statement represents?

**To Reproduce**
1. Prefetch a Query
2. Navigate to a page that uses the prefetched query, (set this query with a longer staleTime)
3. Go back to the page that prefetches the query
4. Devtools will display that query-key as fetching even though it was not supposed to.

**Expected behavior**
queryClient should not call the API if data is already in the cache and not invalidated.

**Desktop (please complete the following information):**
 - OS: macOS Big Sur (11.5.1)
 - Browser: Edge
 - Version: 92.0.902.62

**Comment by TkDodo** [comment]
can you please create a codesandbox reproduction?

**Comment by TkDodo** [comment]
any updates on reproducing this please?

**Comment by TkDodo** [comment]
Feel free to reopen with a reproduction
