### ISSUE TITLE
Question: How to define a query key for related resources

### ISSUE THREAD

**Issue by burtyish** [tannerlinsley/react-query#257]
Say I have multiple related queries:
1. `api/rewards/plan`
1. `api/rewards/achieved`

After a mutation, I need to refetch both queries. 
How would I construct the query keys for the queries above and what would be the query key to provide `queryCache.refetchQueries`?

The type of the query key parameter is:
`queryKey: String | [String, Variables: Object] | falsy | Function => queryKey`

Does this make sense?
1. `useQuery(["rewards", {plan: true}], ...)`
1. `useQuery(["rewards", {achieved: true}], ...)`
1. `queryCache.refetchQueries("rewards")`

Thanks

P.S.
I've posted the same question on [stackoverflow](https://stackoverflow.com/questions/60718324/how-to-define-a-react-query-query-key-for-related-resources-that-do-not-include)

**Comment by cherniavskii** [comment]
Yes, that's correct

**Comment by cherniavskii** [comment]
Although I would rather use `["rewards", "plan"]` and `["rewards", "achieved"]` for query keys.
But that shouldn't make any difference.

**Comment by tannerlinsley** [comment]
Yep! ☝️

**Comment by burtyish** [comment]
@cherniavskii @tannerlinsley thanks, that looks like a natural choice.

The documentation mentions that the 2nd item in the query key tuple can be a variables 
object. Nested arrays are also mentioned but I didn't understand from this that the 2nd item could be a string as well.

**Comment by tannerlinsley** [comment]
Technically it can be any length of any items that are serializable
