### ISSUE TITLE
MutationState type should be more specific, to allow narrowing to match useQuery

### ISSUE THREAD

**Issue by gavinwahl** [tannerlinsley/react-query#2601]
Conditionals on mutation status should narrow the type of data. For example,
```
mutation.status === 'success' && mutation.data
```
`mutation.data` can not be undefined after the guard, but the type doesn't reflect this. The object returned by useQuery does support narrowing like this, so useMutation should too.

**Comment by TkDodo** [comment]
Sounds good. Would you like to open a PR?

**Comment by pobch** [comment]
Also, the `error` status should support type narrowing too:
```
mutation.status === `error` && mutation.error
```
