### ISSUE TITLE
useQuery returns wrong data on prop change in queryKey

### ISSUE THREAD

**Issue by clphillips** [tannerlinsley/react-query#262]
I have a component that uses `useQuery` with a key provided by a prop with the following config:

```
{
    refetchAllOnWindowFocus: false,
    retry: 0,
    refetchOnMount: false,
    staleTime: 30000,
}
```

For example:

```js
    const { data } = useQuery(
        ['queryKey', { type: props.type }],
        (key, params) => {
            console.log('fetch called');
            return Promise.resolve({ ...params });
        }
    );
    console.log(props.type, data);
```

Here's the output of setting a prop called `type` to 'A', then to 'B', then back to 'A':
```
-- set type to 'A'
A undefined
fetch called
A undefined
A {type: "A"}
-- change type to 'B'
B undefined
fetch called
B undefined
B {type: "B"}
-- change type to 'A'
A {type: "B"}
```

Also worth noting:
- When `staleTime` expires for 'B', component is re-rendered and now (correctly) shows data from 'A'
- If the component unmounts and remounts in between prop changes everything works as expected.

**Comment by tannerlinsley** [comment]
Would you be willing to throw this into a codesandbox example for us?

**Comment by clphillips** [comment]
After attempting to duplicate the issue in codesandbox I discovered that this appeared to be caused by `react-hot-loader`. Rebuilding solves the issue.
