### ISSUE TITLE
useIsFetching misbehaviour when staleTime is set 

### ISSUE THREAD

**Issue by mustafawm** [tannerlinsley/react-query#263]
Hello,

**Description**
`isFetching` gets stuck as `true` (positive numeric value) when `ReactQueryConfigProvider`'s `staleTime` is set to a value more than 0

[Demo sandbox](https://codesandbox.io/s/nostalgic-shaw-v39d6)

It seems to return the number of of fresh (not-stale) requests even when they're done fetching/loading

**Comment by tannerlinsley** [comment]
Interesting. I'll take a look at this.

**Comment by tannerlinsley** [comment]
This is fixed in the latest version (1.0.31)
