### ISSUE TITLE
Cannot Override Query Key  when passed it Query Options

### ISSUE THREAD

**Issue by adam-bratin** [tannerlinsley/react-query#2647]
**Describe the bug**
I have a scenario where I want to override the default queryKey used in my customHook by passing queryKey in options. The issues is that queryKey is ignored from options if it is passed as a first arg.

**To Reproduce**
```js
export const useGetData(
  variables,
  options,
) =>
  useQuery(
    ["GetData", variables],
    fetch(
      getDataDocument,
      variables,
    ),
    options);


const component = (props)=>{
const {data} = useGetData(
  {
    filter:"ALL"
  },
  {
    queryKey:"GetData"
  })
//.... return UI
}
```

**Expected behavior**
I would expect the queryKey used to be "GetData" instead ["GetData",{filter:"All"}] is used.

This is based on https://github.com/tannerlinsley/react-query/blob/19861272f57da5e587bce5bff449d0c3020243e0/src/core/utils.ts#L128-L130

it  expands options arg and override queryKey and queryFn. I would do the reverse. I would say the passed options arg is the override from query usage and i should be the most specific.

This is an oversimplified version, but what happens if you are on a phone and add a variable for GPS location? This will cause the query to retrigger every time the phone moves. Now that would in my opinion cause a lot of unnecessary refetches that are treated as Loading instead of background fetch.

**Comment by TkDodo** [comment]
I think this is on purpose. What we could do to make that more apparent in the type definitions is to `Omit` `queryKey` from the allowed `options` when the queryKey is already passed in as first argument.

You can always achieve what you need by slightly rewriting your custom hook:

```
export const useGetData(
  variables,
  key,
) =>
  useQuery(
    key ?? ["GetData", variables],
    fetch(
      getDataDocument,
      variables,
    )
);
```

But I don't fully get the use-case. The query key should usually contain all the dependencies that you pass to the queryFn, and it seems like you'd want to bypass that for some reason 🤔

**Comment by adam-bratin** [comment]
I am using graphql codegen to auto generate my custom hooks. Therefore your solution will not work. As to why I don't want all my variables to be in the the query key is I have a map displayed to the user and I am querying poi based on the user's location. Every time the user moves it will cause the query to be cache busted because the location has changed. This will cause a continual loading experience and hammer my backend.

**Comment by TkDodo** [comment]
That’s usually what `keepPreviousData` is for. As for hammering the backend, a good approach is to denounce the parameter that goes into the query key with a hook like useDebounce: https://usehooks.com/useDebounce/

**Comment by sko-kr** [comment]
v 3.38 still has this problem;
Not perfect but ended up making a custom type, saves from writing `Omit<..., 'queryKey' | 'queryFn'>`

```ts
type UseQueryOpt<TQueryFnData = unknown, TError = unknown, TData = TQueryFnData, TQueryKey extends QueryKey = any[]> = Omit<UseQueryOptions<TQueryFnData, TError, TData, TQueryKey>, 'queryKey' | 'queryFn'>


// usage
export const useCurrencies = (
  options?: UseQueryOpt<ICurerncy[]>
) =>
  useQuery(['currencies'], () => getCurrencies(), options)
```
