### ISSUE TITLE
Optimistic cache update not working for non-primitive fields

### ISSUE THREAD

**Issue by cypcz** [tannerlinsley/react-query#2650]
**Describe the bug**
I'm updating cache with optimistic response exactly how described in the [docs](https://react-query.tanstack.com/guides/optimistic-updates). My use case is reordering nested array. Cache is registering updates in primitive values, e.g. 
```
Course {
  title: "Optimistically updated title"
}
```

however, when trying to update order of chapters (array of objects) using `queryClient.setQueryData`, it's not registering the update resulting in UI "jump". 
```
Course {
  chapters: reorderedChapters
}
```

The data only gets updated when received from server, which results in subpar UX for drag and drop feature.

**Expected behavior**
Cache should be updated for nested non-primitive values as well and trigger re-render.

**Comment by TkDodo** [comment]
not sure what you mean by that. Please provide a minimal codesandbox reproduction of your issue.

**Comment by cypcz** [comment]
The bug was in my code elsewhere. Apologies for false alarm.
