### ISSUE TITLE
placeHolderData in useInfiniteQuery renders endlessly

### ISSUE THREAD

**Issue by mustafa-hanif** [tannerlinsley/react-query#2657]
**Describe the bug**
First, using `placeholderData` is difficult, as we need to add `pages` and `pageParams` which should be transparent to the user, even after providing, the application is stuck in an endless loop.

**To Reproduce**
simply create a custom hook, and useInfiniteQuery with any placeholderData, and try to use it in your app.

**Expected behavior**
Should render once.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Any
 - Version: 3.22

**Comment by TkDodo** [comment]
Please provide a minimal codesandbox reproduction that shows your issue, thanks.

**Comment by raoufswe** [comment]
I've tried to reproduce the issue using the official useInfiniteQuery example but no luck.

here is my [sandbox](https://codesandbox.io/s/condescending-visvesvaraya-094kl?file=/pages/index.js). it would be great if you can fork it or just create your own and we can take a look.

**Comment by TkDodo** [comment]
please re-open if you have a reproduction of the issue, thanks.
