### ISSUE TITLE
Re-fetched useQuery causes re-rendering in other useQuery

### ISSUE THREAD

**Issue by MathiasNeuwert** [tannerlinsley/react-query#2663]
Hey together,

this is my very first issue I'm opening on github, I hope it is ok.
I'm struggling with a very strange behaviour of a refetched useQuery hook.

I have different API endpoints and wrote a custom hook for each call. One of those hooks is called from my navbar, where I want to fetch the users notifications. This hook has the option refetchInterval enabled.

Here is my hook:

```
export const useGetNotifications = () => {
  const dispatch = useDispatch();
  return useQuery<Notification[]>(
    'getNotifications',
    () =>
      fetchAuthorized({
        endpoint: '/user/notifications',
        method: ApiMethod.GET
      }),
    {
      retry: 0,
      refetchInterval: 10000,
      refetchIntervalInBackground: true,
      structuralSharing: true,
      onSuccess: (data: Notification[]) => {
        dispatch(onGetNotifications(data));
      }
    }
  );
};
```

This hook is called directly in the notifications area in my navbar:

```
const Notifications: React.FC = () => {
  useGetNotifications();
  //
  etc....
}
```

In another component (which is not a sub-component of the navbar) I call a hook where I fetch product data via useQuery. Everytime the useGetNotifications hook is re-fetching in the navbar component, the data result of the getProducts is re-rendered. In the Devtools I can see the notifications are fetched, but the getProducts request is stale.

I don't understand why the getProducts data is re-rendering, when the getNotifications request is re-fetching. 

Here I can clearly see, the the getNotifications request is fetching
![Screenshot 2021-09-10 135618](https://user-images.githubusercontent.com/38705193/132849993-01f0b984-7a0e-46d8-89c6-7ca5900f61a7.png)

Everytime the refetching is running, getProducts data are rendering again
![Screenshot 2021-09-10 135746](https://user-images.githubusercontent.com/38705193/132849996-7ef9de81-c216-44e9-a316-fadef57c7908.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge
 - Version: 93.0.961.38

**Comment by MathiasNeuwert** [comment]
OMG my faulty redux implementation was the problem...

**Comment by TkDodo** [comment]
didn't get to answer in time, but I was thinking as much :)

out of curiosity: You don't really need to write responses from react-query to redux or any other global state manager - react-query _is_ a state manager in and on its own. You can just call `useGetNotifications` wherever you need the notifications...

**Comment by MathiasNeuwert** [comment]
Thank you for your quick response :-) I will use it the way you mentioned. By the way, react-query is so freaking awesome, meanwhile it is implemented in most of my projects
