### ISSUE TITLE
[docs]: Add short description of queries and mutations in the Quick Start Guide

### ISSUE THREAD

**Issue by akashshyamdev** [tannerlinsley/react-query#2669]
The docs have a quick start guide but the point of a quick guide is not just to provide code, it's also to give the users a simple overview with an example. 

Currently the quick start guide only has code and 3 links to docs about queries, mutations and query invalidation. I think we should add a short paragraph for each of the above which summarises their functionality in a way a new comer is able to understand.

Apart from that, we should also give a code walkthrough(not just through comments). In this, we should also explain what the `QueryClientProvider` does because there is no guidance about that.

I would be glad to take up this issue and fix it, I'm raising this issue to learn about your opinions and whether you also think that this is a good addition. Thanks for reading, looking forward to hearing your response!

**Comment by TkDodo** [comment]
Sure, I’d appreciate that. It’s also a bit unfortunate that the page claims to go into more details next, but it then actually goes on with devtools, videos and typescript :/ it feels like you can’t really go through the docs page by page. 

But please keep in mind that the quick start page should still be “quick” :)

**Comment by akashshyamdev** [comment]
@TkDodo ok.. I'll start working on it. Could you also tell me about how the docs are setup so that I can add this page?

**Comment by akashshyamdev** [comment]
@TkDodo I've created a pull request for this
