### ISSUE TITLE
old state in useQuery after invalidateQueries

### ISSUE THREAD

**Issue by FelixIncerta** [tannerlinsley/react-query#2710]
Hi,

This is example:

```
const v = new Date();

const { data = null, isSuccess } = useQuery(
    'key',
    async () => {
      try {
         console.log(v.toString());

         return null;
})
```

and invalidate the query somewhere else in the app: 
```
     queryClient.invalidateQueries('key')
```

The value of v is still the old Date.

The initial problem was data from useContext changed but was not updating
`const { formState } = useContext(AppContext);`

in that case the component containing useQuery rerenders and the console.log shows the changed data.
useQuery invalidation is fired after this rerender but inside, it does not have this latest state.

**Comment by TkDodo** [comment]
I think this is just how closures work? When the query function runs, it "sees" all the values in the state that they are in when the function was created.

**Comment by FelixIncerta** [comment]
You are right, this is standard JS behavior. I already suspected this.

But the only solution then would be to put all variables i need in the queryKeys or use a mutate with useEffect and setQueryData to get the entities ?

**Comment by TkDodo** [comment]
yes, keep the fetch function pure, and put all dependencies it needs to perform the fetch into the queryKey.

**Comment by Jekiwijaya** [comment]
@FelixIncerta Hey, I also have same problem.

My solution is instead using invalidateQueries, I use prefetchQuery.
https://codesandbox.io/s/ancient-bash-umkdv?file=/src/App.tsx:812-825
