### ISSUE TITLE
Concurrent invalidateQueries skips some requests

### ISSUE THREAD

**Issue by yekver** [tannerlinsley/react-query#2717]
I have multiple mutations. Every mutation has multiple `invalidateQueries` calls defined `onSuccess`. These invalidation calls overlaps. In case several mutations were run sequentially some invalidation calls will be skipped.

I came up with several solutions like these:
- extract invalidation logic from mutations into custom hooks / HOC mutations and do the invalidation logic right after all mutations were called
- add a flag to skip `invalidateQueries` calls inside mutations and do the invalidation logic right after all mutations were called

Unfortunately all of these solutions are not perfect enough and provided example is very simplified. In real project there is some business login between mutations and invalidation logic is very huge to be extracted. Also extracting invalidation login from these mutations will cause lots of modifications as they are reused in many places and invalidation logic should persist there.

```javascript
const queryClient = useQueryClient()
 
const mutation1 = useMutation(doSomeStaff, {
  onSuccess: () => { queryClient.invalidateQueries('sameKey') }
})

const mutation2 = useMutation(doAnotherStaff, {
  onSuccess: () => { queryClient.invalidateQueries('sameKey') }
})

await mutation1()
// Invalidation call -> execute network request
await mutation2()
// Invalidation call -> network request is in progress thus no updated data will be received from the API
```

**Comment by TkDodo** [comment]
[The docs](https://react-query.tanstack.com/guides/mutations#mutation-side-effects) say that you can return promises from the side-effects and they will be awaited. Have you tried:

```
const mutation1 = useMutation(doSomeStaff, {
  onSuccess: () => queryClient.invalidateQueries('sameKey')
})

const mutation2 = useMutation(doAnotherStaff, {
  onSuccess: () => queryClient.invalidateQueries('sameKey')
})
```

not the missing curly brackets so that the result of `invalidateQueries`, which is a promise, is returned from `onSuccess`. `await mutation1()` should then also wait until the invalidation is finished I believe.

**Comment by TkDodo** [comment]
Any updates here pls? Have you tried the suggestion?

**Comment by TkDodo** [comment]
You can also look into calling `queryClient.cancelQueries` before invalidating. This should make sure that currently running requests are canceled / ignored and you can safely invalidate again.

**Comment by yekver** [comment]
> Any updates here pls? Have you tried the suggestion?

Yeah, that works just perfectly. Thank you very much for the solution.

Also I think it'll be very useful to update the docs ([here](https://react-query.tanstack.com/guides/query-invalidation) and [here](https://react-query.tanstack.com/guides/invalidations-from-mutations)) and describe the reason why the result of `invalidateQueries` is a `promise`.

**Comment by TkDodo** [comment]
Sure, please make a PR to the docs to improve them
