### ISSUE TITLE
use Query Select function gives incorrect result

### ISSUE THREAD

**Issue by vincentbetro** [tannerlinsley/react-query#2718]
**Describe the bug**
When using the select functionality on useQuery to transform data, instead of it running the transform on the data returned by the query at each render, it runs the transform on the previously transformed data on each render, yielding an incorrect result.  In this case, I am multiplying a rate in an object returned from useQuery by 100, and since it renders three times, it multiplies it by 1000000.

**To Reproduce**
https://codesandbox.io/s/usequeryselectwronganswer-scbjy

**Expected behavior**
I would expect that the result which is being operated on each time useQuery is run would be the result of the query, not the previously transformed result.

**Screenshots**
https://codesandbox.io/s/usequeryselectwronganswer-scbjy

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser: Chrome 
 - Version:  93.0.4577.63 (Official Build) (64-bit)

**Additional context**
In my code, it is receiving data from an endpoint (and I can attest it is coming back the same each time), whereas in the example, it is a static array that is the result of "useQuery" each time.

**Comment by Danicoco** [comment]
This is probably because of the default settings of useQuery hook. By default, React Query retries your query 3 times. You can override this default settings by either setting retries to false or a your preferred number.

In your case, setting it to false will solve your issue.

**Comment by TkDodo** [comment]
@vincentbetro you are mutating the `data` you get into select with your `foreach` loop:

```
result.forEach((item) => (item.rate *= 100));
```

as with everything in react, please embrace immutability. Otherwise, each select function will change the value of the cached data you get passed. A simple immutable version of your code would be:

```
select: (data) => data.map(item => ({ ...item, rate: item.rate * 100 }))
```

**Comment by waynebrantley** [comment]
@TkDodo so the 'select' part is not cached/stale - but runs each time the query returns data then?

**Comment by TkDodo** [comment]
`select` runs per default on each render (read [here](https://tkdodo.eu/blog/react-query-data-transformations#3-using-the-select-option) how to optimize it). It always gets the value from the cache as input and should be a pure function. You can have multiple components that `select` some parts of the cache, which is why the select value is not stored in the cache.

**Comment by vincentbetro** [comment]
Thank you, @TkDodo and @Danicoco!  I understand the reasoning and the immutability fix did the trick!
