### ISSUE TITLE
Re-render bug when clicking out of and back into app using react-query

### ISSUE THREAD

**Issue by AryanJ-NYC** [tannerlinsley/react-query#273]
Hey! What an amazing library. This has made caching a TON easier for me! Thanks a ton. I _think_ I found a bug.

Any component using `useQuery` will re-render when a user clicks out of and back into the component. I've created [a minimal reproduction of this bug](https://github.com/AryanJ-NYC/react-query-re-render-bug).

To reproduce:

1. `git clone https://github.com/AryanJ-NYC/react-query-re-render-bug`
2. `yarn start`
3. Go to http://localhost:3000/ in browser and open console.
4. Click out of the window and click into the window.
5. Watch it re-render.
6. Repeat steps 4 and 5.

![react-query-bug](https://user-images.githubusercontent.com/8263430/77219629-0cff6600-6b0e-11ea-98c5-a9c808ae3716.gif)

I am using "react-query": "^1.0.33".

**Comment by mustafawm** [comment]
It could be becose `refetchOnWindowFocus` is set to `true` by default as mentioned [here](https://github.com/tannerlinsley/react-query#usequery).

I tried setting it to `false` on your repo and the re-rendering stopped.

**Comment by tannerlinsley** [comment]
Yep. By default, queries are fetched if stale When the window or tab is focused.

**Comment by AryanJ-NYC** [comment]
It's a feature and not a bug. 🤦‍♂  I feel silly. Apologies for the false alarm!

**Comment by Migueacalle98** [comment]
@AryanJ-NYC  Thanks a lot for opening this issue, a have struggled with this for 2 days because it was really nested in my app, the solution really helped. Thanks a lot to all.
