### ISSUE TITLE
乐观更新删除的数据会回弹回来一次

### ISSUE THREAD

**Issue by guopengchang** [tannerlinsley/react-query#2735]
乐观更新

网络调特别慢的情况下,querykey查询react-query缓存的数据，会出现数据回弹
假如有3条数据，删除一条，乐观更新删了，页面显示2条，瞬间回弹，又变3条，
等接口正真的成功又变2条

**Comment by TkDodo** [comment]
please open issues in English, and only with reproducible codesandbox examples to work with. For questions around library usage, please open a discussion.
