### ISSUE TITLE
support useErrorBoundary in useQuery

### ISSUE THREAD

**Issue by kentcdodds** [tannerlinsley/react-query#275]
Here's a minimal reproduction of what I want: https://codesandbox.io/s/loving-mclean-zopr1

```javascript
import React from 'react'
import ReactDOM from 'react-dom'
import ErrorBoundary from 'react-error-boundary'
import {useQuery} from 'react-query'

function BoundaryFallback() {
  return 'oh no'
}

function Query() {
  useQuery('my-thing', () => Promise.reject('bad'), {useErrorBoundary: true})
  return '...'
}

function App() {
  return (
    <ErrorBoundary Fallback={BoundaryFallback}>
      <Query />
    </ErrorBoundary>
  )
}

ReactDOM.render(<App />, document.getElementById('root'))
```

I expect that to render `'oh no'`, but it's just rendering the `...`. I also tried `throwOnError` but that didn't work either and I don't think that's what `throwOnError` is intended for either.

This would make it much easier to manage errors for loading data (not just mutating it).

**Comment by tannerlinsley** [comment]
By adding the `suspense: true` option and also correcting the `Fallback` prop to `FallbackComponent`, it seems to work:

https://codesandbox.io/s/loving-cookies-4f9x8

**Comment by kentcdodds** [comment]
Oh 😅 Sorry about that.

What if I don't want `suspense: true`?

**Comment by tannerlinsley** [comment]
Currently it’s a requirement https://github.com/tannerlinsley/react-query/blob/master/src/useQuery.js#L7

**Comment by kentcdodds** [comment]
Can it not be? 😅

**Comment by tannerlinsley** [comment]
Sure! I’ll work on that

**Comment by kentcdodds** [comment]
Thank you Tanner!

**Comment by tannerlinsley** [comment]
![tenor](https://user-images.githubusercontent.com/5580297/77486649-f1d67400-6df5-11ea-9d4b-559d432f2ea4.gif)
