### ISSUE TITLE
Query fetching and then disappearing (not going to stale and can't be invalidated)

### ISSUE THREAD

**Issue by ivonigC** [tannerlinsley/react-query#2765]
**Describe the bug**
I am having a query and I can see it fetching in the devtools, it gets the proper data but then disappears from the react-query-devtools. I just see the name blink. The problem is that the query does not stay stale and invalidating it when needed is not retriggering it and updating the data.

What's even weirder is that the behaviour is not permanent on refresh. Sometimes it stays stale, sometimes it disappears.

**To Reproduce**
We are using react-query with Meteor with the following custom hook:

```
export const useQueryHook = <TArgs, TResult>(
  name: string,
  args?: TArgs | undefined,
  key: (string | boolean)[] = [],
  config?: LooseObjectType
): UseQueryResult<TResult, Meteor.Error> => {
  return useQuery<TResult, Meteor.Error>(
    [name, ...key],
    () =>
      new Promise((resolve, reject) => {
        Meteor.call(name, args, (err: Meteor.Error, result: TResult) => {
          if (err) {
            reject(err);
          }
          resolve(result);
        });
      }),
    { ...defaultConfig, ...config }
  );
};
```

we call the hook as such:

```
  const { data, isLoading, error } = useQueryHook<
    IActivityQuery,
    IActivityChallengesResult | undefined
  >("get.activity.challenges", { activityId, isAdmin: true }, [
    activityId,
    true,
  ]);
```

**Comment by ivonigC** [comment]
I guess, writing the issue got me the answer. The queryclient was created inside the App component and therefor rege,erated...

**Comment by adammoisa** [comment]
Can you share how you're using react-query within a meteor project? We have a meteor project that has many react components in it and I assume(d) there'd be no way to 'wrap the whole app' in a single QueryProvider. But for the components that are React, it'd be great if we can use useQuery and get the auto-caching react-query provides. Please let me know how you set your project up if it's similar!
