### ISSUE TITLE
migrate to TypeScript 

### ISSUE THREAD

**Issue by vnguyen94** [tannerlinsley/react-query#277]
Hey there, is there any interest in migrating react-query to TypeScript? About a month ago before 1.0 (congrats on that btw!) i added a feature and added it to TS types, but now it seems TS types are very out of sync with the actual code. If there is interest, I wouldn't mind spending one of these quarantined weekends migrating this to TS, so let me know.

**Comment by tannerlinsley** [comment]
Feel free to contribute to the 3rd party types on Definitely Typed! For now, I have no plans on migrating the library source.

**Comment by jannikbuschke** [comment]
@tannerlinsley would you be interested in shipping the types within this package and not via definitely typed? This way it would be easier to sync them with the actual source code.
This core would not need to be developed in typescript if I am not mistaken, we would just add a .d.ts file alongside.

**Comment by lishine** [comment]
I came across wrong types for useInfiniteQuery.
I don't know how to use it now.
@tannerlinsley what is the reason not to put index.d.ts file in the project folder and make the PRs here instead of to Definitely Typed? It would make life easier.

**Comment by tannerlinsley** [comment]
Yeah, a lot has already been said on this subject, but in summation:
- I don't use TS, so I won't maintain them (at least, not as much as everyone would like)
- By making them a first-class citizen of the repo, I would be setting a bad expectation that they would be maintained

**Comment by tannerlinsley** [comment]
FYI - https://github.com/tannerlinsley/react-query/discussions/362
