### ISSUE TITLE
Default queryFn overrides custom queryFn from observer in SSR

### ISSUE THREAD

**Issue by EasileleM** [tannerlinsley/react-query#2774]
We have default queryFn defined in defaultOptions on QueryClient creation.
We prefetch data on SSR via fetch data and use that data via useQuery with custom queryFn.
The problem is, when we invalidate that data, instead of using custom queryFn, provided in useQuery observer,
react query uses default queryFn to refetch.

From my point of view, it would be expected, if custom queryFn was used.

It seems that code causes the problem https://github.com/tannerlinsley/react-query/blob/361935a12cec6f36d0bd6ba12e84136c405047c5/src/core/query.ts#L347

**Comment by TkDodo** [comment]
feel free to reopen with a reproduction
