### ISSUE TITLE
Manual query cancellation doesn't fit TS types

### ISSUE THREAD

**Issue by yekver** [tannerlinsley/react-query#2775]
According to [this documentation](https://react-query.tanstack.com/guides/query-cancellation#manual-cancellation) Promise returned by `MutateFunction` or `QueryFunction` can be extended with a `cancel()` method. But types doesn't fit this extension because they expect only `Promise` to be returned

**Comment by TkDodo** [comment]
Query cancellation works by putting a `.cancel` function onto a `Promise`, but a `Promise` can't actually have that property on type level. API wise, I think this is a bit of a leftover from js times. In this article is a good explanation on how to do this with TypeScript:

https://www.carlrippon.com/cancelling-requests-with-react-query/

All in all, I don't think we can change that without doing a breaking change.

**Comment by TkDodo** [comment]
also, this has already been reported before: https://github.com/tannerlinsley/react-query/issues/1265 and we're discussing alternative approaches here: https://github.com/tannerlinsley/react-query/discussions/1671
