### ISSUE TITLE
useMutation throws the error even when throwOnError is false

### ISSUE THREAD

**Issue by chirag04** [tannerlinsley/react-query#279]
when using `useMutation` along with onError and throwOnError: false, i noticed that the error is thrown and the app crashes.

here is a minimal repo: https://codesandbox.io/s/festive-swartz-zpz38

**Comment by tannerlinsley** [comment]
If you throw an error in development mode with react-create-app during a render, the redbox error overlay will take over regardless of how you handle the error.  To test this thoroughly, you must call the function outside of the render loop: https://codesandbox.io/s/nostalgic-moon-2f1o9

As you can see, it does not throw when `throwOnError` is set to `false`

**Comment by chirag04** [comment]
sorry, I was a bit too eager when creating at the repo.

@tannerlinsley - in your example, it won't throw when `throwOnError` is set to `true` as well.

**Comment by tannerlinsley** [comment]
Hmm. Must have been part of my latest fix. With updated dependencies, it does: https://codesandbox.io/s/nostalgic-moon-2f1o9
