### ISSUE TITLE
No exported member "Mutation"

### ISSUE THREAD

**Issue by Brodzko** [tannerlinsley/react-query#2838]
**Describe the bug**
It looks like exports from `mutation.d.ts` are not picked up correctly by TS. Instead a 'no exported member' error is thrown, making explicit typing with `Mutation` and other members impossible. Contrast that with importing `Query` which works fine.

**To Reproduce**
[Repro sandbox here](https://codesandbox.io/s/fervent-leakey-9dt6f?file=/src/index.tsx)

**Expected behavior**
Type for `Mutation` is imported

**Comment by TkDodo** [comment]
you should be able to import `UseMutationOptions` and `UseMutationResult`. What would you need `Mutation` for please?

**Comment by Brodzko** [comment]
> you should be able to import `UseMutationOptions` and `UseMutationResult`. What would you need `Mutation` for please?

Strongly typing my global error handlers for `QueryCache` and `MutationCache`, see [updated sandbox](https://codesandbox.io/s/fervent-leakey-9dt6f?file=/src/index.tsx) 🙂

**Comment by TkDodo** [comment]
ah, now I see what you mean. if possible, would you like to contribute that?
