### ISSUE TITLE
Provide export for useConfigContext

### ISSUE THREAD

**Issue by esjs** [tannerlinsley/react-query#287]
Currently, there is no way to access final config that is set to `configContext` in `ReactQueryConfigProvider`. Is there any reason why `useConfigContext` cannot be exported for public use?
In my case I want to access user defined "retry" option (or default if not) to detect whether `rertry === failureCount` and show an error in custom error handler hook if so.

Thank you for an awesome library,
Vladimir

**Comment by tannerlinsley** [comment]
I'm not sure if what you're describing is possible, since the retry can also be defined and extended via the useQuery hook variations. Can you better describe what you're attempting to accomplish? There is likely an easier or better way to do it than manually consuming the context.

**Comment by esjs** [comment]
The main problem I'm trying to solve is the same as discussed in [this](https://github.com/tannerlinsley/react-query/discussions/84) thread. 
If there would be an option to prevent request retry based on some condition on error, then I would be more than happy.

Also it's worth mentioning that my attempt to solve issue with retries has failed, because even if custom handle Promise rejection via catch there is no correct answer that I can return from it, since rethrowing an error would still cause request retry.

Closing issue and hope that eventually there would be a way to control retries logic.
Thanks!
