### ISSUE TITLE
Typescript issues with query data selector

### ISSUE THREAD

**Issue by sem4phor** [tannerlinsley/react-query#2899]
**Describe the bug**
When I transform data with the query data selector like stated here https://react-query.tanstack.com/guides/migrating-to-react-query-3#query-data-selectors a typescript error is thrown and the type in onSuccess does not change to the type returned in the select function.

**To Reproduce**
1. Go to https://codesandbox.io/s/tannerlinsley-react-query-basic-typescript-forked-j8qro?file=/src/index.tsx
2. Click on 'src/index.tsx'
3. Scroll down to line 34, hover the error and data in line 31
4. See error & wrong type

**Expected behavior**
I expect that the return type of the select function might differ from the original type of the data and the type of the query data, the parameter for onSuccess etc. is overwritten by the type returned from the select function.

**Screenshots**
![image](https://user-images.githubusercontent.com/6383149/140715142-5427bcfa-ac84-43dd-a3b7-0e1816900274.png)

![image](https://user-images.githubusercontent.com/6383149/140715211-f139960e-54bd-4201-bb6a-d6289593da22.png)

![image](https://user-images.githubusercontent.com/6383149/140715587-57923308-b624-4de7-9658-3fe91c03975a.png)

**Additional context**
Sandbox is forked from official TS example

**Comment by sem4phor** [comment]
Thanks for the hint! I actually was not aware of it. But either way I find it preferable that the type is inferred which ACTUALLY flows into data/onsuccess. And at the end of the day this is the data coming from the selector function 😅

**Comment by TkDodo** [comment]
@Svish if you only pass 3 generics, you lose type inference for the 4th generic - the queryKey.

the sandbox shows a "known" limitation with select + other callbacks. I haven't yet figured out why TypeScript can't infer things - the best workaround I've found is to annotate the input of `select`. optimistic updates have a similar limitation, where you have to annotate `onMutate`. I've written about that one [here](https://tkdodo.eu/blog/react-query-and-type-script#optimistic-updates).

so by doing:

```diff
- select: (data) => data.map((d) => d.title)
+ select: (data: Array<Post>) => data.map((d) => d.title)
```

not only does the type error go away, but the input in `onSuccess` is also correctly inferred.

Maybe it would be good to add that to the typescript docs somewhere?

**Comment by Svish** [comment]
@TkDodo Yeah, sorry, used to working with our own useQuery wrapper where the query key is already hard coded 🤓
