### ISSUE TITLE
Improve aria-tagging of Devtools

### ISSUE THREAD

**Issue by Svish** [tannerlinsley/react-query#2901]
**Describe the bug**

1. Devtools is now defaulting to being rendered as `footer`, which doesn't make a lot of sense to me.
2. Menu-items for sorting seem to be rendered and visible in the Accessibility Tree regardless of open/closed state.
3. The Devtools toggle-button have no aria-attributes for toggled state or link to the panel it toggles.

**To Reproduce**
1. Render React-Query Devtools in an app
2. Explore the DOM tree and the Accessibility tree

**Expected behavior**
1. A better default should probably be `aside`, and it should also have an `aria-label` (like "React Query Devtools" for the landmark it generates.
2. Not sure if this is an actual issue, or just how the accessibility tree works, but I'm thinking the panel should maybe either not be rendered at all, or be rendered with `aria-hidden` or something like that when not opened?
3. Toggle-button should have appropriate aria attributes (`aria-controls`, `aria-expanded` and be linked to the panel as it should.

**Screenshots**
In the screenshot below, the React Query Devtools "root" is the generic `contentinfo` node
![image](https://user-images.githubusercontent.com/142162/140752640-7a6d35bb-35fc-4859-9b63-a06b02418602.png)
Changing the element-type to `aside` and adding an `aria-label` (just edited the HTML in Chrome for this) gives this instead, which to me at least looks more appropriate:
![image](https://user-images.githubusercontent.com/142162/140754113-689f949b-77b3-4e51-9609-16a492b660b1.png)

**Comment by TkDodo** [comment]
I agree, this could be improved. I like your suggestions. Would you like to contribute it?

**Comment by Svish** [comment]
If you weren't using yarn, I probably could, but trying to stay away from yarn as it tends to try taking over my computer and mess up non-yarn stuff as well. I've tried to just run the yarn stuff via npx, but usually ends up not building properly or something 😕

**Comment by TkDodo** [comment]
oh interesting. we're also using `npm` at work, and I'm actually enjoying yarn in RQ because it's a lot faster. I've just done `npm i -g yarn` and it worked well until now 😅

**Comment by Svish** [comment]
yarn had some advantages in the beginning, but feel they're not that much different now. So I prefer to stick with what's most "industry standard". Especially after I experienced yarn being pushy. Or rather, people writing stuff with yarn being pushy. For example (a while ago now, so might have been fixed), when I tried to use create-react-app, it would generate a lot of yarn stuff, even though I had not mentioned yarn anywhere and ran it via npm. That, and other experiences, annoy me, so I've ended up trying to stay away from it and not have it on my computer. 😛

**Comment by Andrewnt219** [comment]
Hi @TkDodo, I want to help with this request.

1. Seem straightforward.
2. Can confirm that `menuitem` should not appear in the a11y tree. Will look into this.
3. Seem straightforward. I'll follow the guidelines here https://www.w3.org/TR/wai-aria-practices/examples/menu-button/menu-button-links.html

**Comment by TkDodo** [comment]
@Andrewnt219 that would be very much appreciated - thank you  🙏
