### ISSUE TITLE
typesripted useQuery not working

### ISSUE THREAD

**Issue by cynosurecreative** [tannerlinsley/react-query#291]
Using the following slightly edited react-query example provided via the docs, all it is doing is providing strongly typed parameters  - 

```
const getPostById = async (key: string, { id }: { id: number }) => {
    const { data } = await axios.get(
        `https://jsonplaceholder.typicode.com/posts/${id}`
    );
    return data;
};
```

And after attempting to implement it as below
```
    const postId = 1;
    const { status, data, error, isFetching } = useQuery(
        Boolean(postId) && ["post", { id: postId }],
        getPostById
    );
```

I keep getting the following typescript error: 
```
Argument of type '(key: string, { id }: { id: number; }) => Promise<any>' is not assignable to parameter of type 'QueryFunction<any, object>'.ts(2345)
```

I'm at my wits end trying to get this to work so any help would be greatly appreciated.

Also, after appending a "// @ts-nocheck" at the top of the page everything works as expected, so i do believe the library is working as intended, its just infuriating trying to get typescript and this library to play nice. As a reference im using 1.1.3 of react-query and 0.3.9 of @types/react-query.

**Comment by tannerlinsley** [comment]
Yeah those types are clearly out of date. I’m not sure how to make them work without updating them.

**Comment by cynosurecreative** [comment]
Ahh rightio thats a shame, cheers for the quick reply

**Comment by Myzel394** [comment]
Still not working on version 3.2.0

**Comment by tannerlinsley** [comment]
@Myzel394 Please upgrade to 3.3.0 and open a new issue with a codesandbox/info

**Comment by joaoreynolds** [comment]
I figured out that if you inline the function this problem goes away (as of v3.5.12):

```typescript
const getPostById = async ({ id }: { id: number }) => {
    const { data } = await axios.get(
        `https://jsonplaceholder.typicode.com/posts/${id}`
    );
    return data;
}

const postId = 1;
const { status, data, error, isFetching } = useQuery(
    Boolean(postId) && ["post", { id: postId }],
    () => getPostById(postId)
);
```
