### ISSUE TITLE
remove deprecated .cancel on promises

### ISSUE THREAD

**Issue by TkDodo** [tannerlinsley/react-query#2915]
With the addition of out-of-the-box support for Query Cancellation via AbortController and AbortSignal (v3.30.0) we will remove the old way to cancel Promises by providing a .cancel method.

- [ ] remove old code
- [ ] update docs

**Comment by TkDodo** [comment]
@jcready let me know if you're interested in working on this, given that you're the mastermind behind the query cancellation :)

**Comment by prateek3255** [comment]
@TkDodo I would like to give this a shot
