### ISSUE TITLE
better query filters

### ISSUE THREAD

**Issue by TkDodo** [tannerlinsley/react-query#2917]
The [query filters](https://react-query.tanstack.com/guides/filters#query-filters) have lots of flags, some of them contradicting each other, and it become quite confusing very fast and it also supports invalid combinations. Especially the `active` and `inactive` resp. `refetchActive` and `refetchInactive` flags are problematic, as outlined [in this issue](https://github.com/tannerlinsley/react-query/issues/2271)

### Proposed solution

Replace the `active` and `inactive` booleans with a `QueryStatusFilter: 'all' | 'active' | 'inactive'`. We already map the booleans internally ([see here](https://github.com/tannerlinsley/react-query/blob/9e414e8b4f3118b571cf83121881804c0b58a814/src/core/utils.ts#L176-L193)), but we currently also allow for a `'none'` state if both booleans are set to `false`, which doesn't make any sense - you wouldn't mach any query at all.

**Comment by TkDodo** [comment]
@donysukardi maybe this would be something for you, given that you've already done the ground work in
- #2271

let me know if you want to work on this :)

**Comment by TkDodo** [comment]
note: `'none'` actually makes sense for `refetchActive` / `refetchInactive` on `invalidateQueries`, because there we default to `active` and need a possibility to say that we just want to invalidate, but don't want to refetch at all.

**Comment by donysukardi** [comment]
Wow.. That’s fast @TkDodo! Hahaha.. I wanted to reply you, but I suppose it’s too late now 😂

**Comment by TkDodo** [comment]
sorry, I was just too eager 😆 

maybe you can help me out with the naming. I went with `type` for the `filters` object and `refetchType` instead of `refetchActive` / `refetchInactive`. Let me know if you have better ideas :)

**Comment by donysukardi** [comment]
those are perfect already! 👍 great work @TkDodo!
