### ISSUE TITLE
Make tracked queries the default

### ISSUE THREAD

**Issue by TkDodo** [tannerlinsley/react-query#2922]
currently, `notifyOnChangeProps` defaults to `undefined`, but many people have already stated that the `tracked` version would be what they'd see as "expected"

also: remove `notifyOnChangePropsExclusion`

The inverse array doesn't really give you much given that you can just use tracked queries. Also, it "breaks" every time we add a new property that changes often.

For example, we have recently added a `isRefeching` computed flag to the queryResult, and since this is based on `isFetching`, people that have excluded `isFetching` would now get their re-renders again.

**Comment by babycourageous** [comment]
I'll give this one a go!

**Comment by babycourageous** [comment]
Would you prefer these be together in 1 PR or 2 separate PRs (one for default "tracked" and another for removing `notifyOnChangePropsExclusion`)?

**Comment by TkDodo** [comment]
You can do both in one PR if you like :)

**Comment by babycourageous** [comment]
For the default behavior for `notifyOnChangeProps` is the intention that `useQuery` by default would behave as though  `notifyOnChangeProps: "tracked"` was defined

```js
useQuery('key', queryFn) === useQuery('key', queryFn, {notifyOnChangeProps: "tracked"})
```

**Comment by TkDodo** [comment]
exactly. we can set the default value for `notifyOnChangeProps` to `tracked`, but people should still have the option to opt out of it, likely by doing `notifyOnChangeProps: undefined`. If it's difficult to distinguish between the explicit value `undefined` being passed and the key not being there (which could be), maybe we could:

- remove `tracked` completely and just say if it's not defined, it tracks
- add `notifyOnChangeProps: 'all' to opt out of the smart tracking

in any case, we should keep the additional array notation so that users can define the keys they want to observe.
