### ISSUE TITLE
Combine multiple selectors together

### ISSUE THREAD

**Issue by dudulasry** [tannerlinsley/react-query#2955]
### Discussed in https://github.com/tannerlinsley/react-query/discussions/2954

<div type='discussions-op-text'>

<sup>Originally posted by **dudulasry** November 16, 2021</sup>
Hey everyone,

I'm using react-query for a while now, and I was wondering whether the library allows chaining multiple selectors together. This turned out to be a real need in a project I work on.

If this isn't supported, maybe we can allow it by exposing a utility function that combines selectors:
```
const combineSelectors = (selectors) => (data) =>
  selectors.reduce((input, selector) => selector(input), data);
```

And then we can use it in the code like this:
```
const selector = combineSelectors([selector1, selector2]);
```

Another idea is to combine selectors behind the scenes. We can check if the provided `select` function is of type list or function. WDYT?</div>

**Comment by TkDodo** [comment]
let's keep this in the discussion for now please.
