### ISSUE TITLE
Query with error is retried when `enabled` changes

### ISSUE THREAD

**Issue by petrkrejcik** [tannerlinsley/react-query#2959]
When a query is in error state and the `enabled` flag is changed the query is refetched even with `retry: 0`.

**Version**
`3.23.3`

**To Reproduce**
[Sandbox](https://codesandbox.io/s/elegant-pare-bbjsp?file=/src/Query.js)

```js
const queryClient = useQueryClient();
const [enabled, setEnabled] = React.useState(false);

useQuery("one", async () => {
  throw new Error("Failed");
}, { enabled, retry: 0 });

React.useEffect(() => {
  setInterval(() => setEnabled((current) => !current), 1000);
}, []);
```

In this case `errorUpdateCount` of the query is incremented every second.

**Expected behavior**
A query with `retry: 0` should not be retried even when `enabled` flag changes.

**Comment by TkDodo** [comment]
> Expected behavior
A query with retry: 0 should not be retried even when enabled flag changes.

retries have nothing to do with `enabled`. If a disabled query is enabled, a refetch will be triggered. If that fails and you have 3 retries, it will retry 3 times more. With zero retries, it will just _not_ retry, but it will still fetch when you enable it, same as it will fetch when you call `refetch()`

**Comment by petrkrejcik** [comment]
Ok, toggling `enabled` is like calling `refetch()`. 
No bug then, thanks for explanation.
