### ISSUE TITLE
Input type=file dialogue triggers windows focus refetch

### ISSUE THREAD

**Issue by Dynalon** [tannerlinsley/react-query#2960]
**Describe the bug**
 Using an `<input type="file" onChange={onChangeHandler} />` component will bring up a file chooser to chose your files (i.e. for uploads). The problem is, that at least on on macOS/Chrome, once the dialog box disappears after you chose the file, this triggers the refetchOnFocus event (if enabled). This bug cost me hours to debug, as the onChangeHandler was never called - the refetch triggered a re-render and thus the component was unmounted (and remounted) before the onChangeHandler actually could fire.

**To Reproduce**
1. Use any `<input type="file" onChange={onChange} />`
2. Click on "Choose file" and select a file
3. Observe the refetchOnFocus (possibly triggering a re-render)
4. onChange handler is not fired

**Expected behavior**
The `<input type="file" />` dialog should be exempted from the refetchOnFocus event

**Desktop (please complete the following information):**
 - OS: macOS 
 - Browser: latest Chrome

**Comment by TkDodo** [comment]
This seems to be similar to
- #2868

to detect changes in focus, we use [browser native events ](https://github.com/tannerlinsley/react-query/blob/52854795b62946b4a4b73e4bddc6954db77e2058/src/core/focusManager.ts#L63-L64). If opening a file upload dialog triggers one of these events in certain browsers, I'm not sure what we should do here.

My recommendations from [this comment](https://github.com/tannerlinsley/react-query/issues/2868#issuecomment-962448442) would likely also apply here: Tweak the `FocusManager` to your needs or turn off `refetchOnWindowFocus` for this query.

**Comment by Dynalon** [comment]
I could work around that issue by just setting `{ refetchOnFocus: false }` for all the queries present on the site with the input dialogue, but I think this is bound to fail again in the future (when introducing a new query i.e. in something as omnipresent as the navbar).

It might make sense to highlight this in the documentation about refetchOnFocus. It would also be nice if there was a quick/simple API to temporarily disabled the refetchOnFocus App-wide so we can use it in an effect for a component. I tried using `queryClient.setDefaultOptions()` but changing the values for refetchOnFocus seem to itself trigger a refetch.

```typescript
const queryClient = useQueryClient()
React.useEffect(() => {
    queryClient.disableRefetchOnFocus()
     // dispose function triggered on unmount
    return () => queryClient.enableFetchOnFocus()
})

**Comment by TkDodo** [comment]
have a look at [focusManager.setFocused](https://react-query.tanstack.com/reference/focusManager#focusmanagersetfocused). As far as I can see, if you set:

```
focuseManager.setFoused(true)
```

before you open the file dialog, followed by

```
focuseManager.setFoused(undefined)
```

it should revert back to the normal `focusManager` behaviour

**Comment by Dynalon** [comment]
@TkDodo thanks so much for you help! I could come up with this Hook now that I call in components that have a `<input type="file" /> dialogue to disabled the `refetchOnFocus` for as long as that component is mounted:

```typescript
import { useEffect } from "react"
import { focusManager } from "react-query"

export function useDisableRefetchOnFocus() {
  useEffect(() => {
    focusManager.setFocused(false)
    return () => focusManager.setFocused(undefined)
  }, [])
}
```

**Comment by TkDodo** [comment]
That looks good indeed. If you want to contribute this to the FocusManager docs as a known gotcha, please go ahead :)

**Comment by kyawthura-gg** [comment]
Looks like only happens in dev. In production, there’s no issue.

**Comment by TkDodo** [comment]
I hope this will be fixed in v5:
- https://github.com/TanStack/query/discussions/4797
