### ISSUE TITLE
Type fix for cacheTime and staleTime

### ISSUE THREAD

**Issue by bombillazo** [tannerlinsley/react-query#3008]
**Describe the bug**
The docs and in code comments mention we can set both `cacheTime` and `staleTime` to `'Infinity'`, but their typings only specify them as a `number`. This creates issues when setting their values in typescript code.

**To Reproduce**
```ts
const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      cacheTime: 'Infinity',
      staleTime:  'Infinity',
    },
  },
});
```
**Expected behavior**
TypeScript gives no errors regarding their types.

**Screenshots**
![image](https://user-images.githubusercontent.com/44002321/142960084-ac82da79-c959-4e94-9e98-8cd8e463a114.png)

**Desktop (please complete the following information):**
 - Version: 3.31.0

**Smartphone (please complete the following information):**
 - All

**Comment by TkDodo** [comment]
You have to use `Infinity` without quotes, which is a number.
