### ISSUE TITLE
useInfiniteQuery refetchOnWindowRefocus erase the previous dataset

### ISSUE THREAD

**Issue by stevensturkop** [tannerlinsley/react-query#3026]
**Describe the bug**
On window refocus the dataset is being duplicated and overwritten. It happens when more than 1 page have been fetched.

**Expected behavior**
When the data are refetched on window focus it shouldn't overwrite the previous data but rather invalidate them.

**Screenshots**
GOOD: Page load > user scroll down to fetch more > next page is fetched and seq_id is undefined because there are no more data to fetch
<img width="392" alt="Capture d'écran 2021-11-25 à 18 03 32 PM" src="https://user-images.githubusercontent.com/42664988/143480524-2088a4f6-121b-42ab-89d7-473e8e30ae0b.png">

BAD: Refocus the window, now the data are duplicated, the seq_id is the same as the screenshot above and it has been duplicated. Also when I do a deep comparison of both pages, they are identical.
<img width="399" alt="Capture d'écran 2021-11-25 à 18 03 47 PM" src="https://user-images.githubusercontent.com/42664988/143480532-04942f6b-d675-4a1d-a19b-8bc9c1ce0e19.png">

**Desktop (please complete the following information):**
 - OS: Mac OS Big Sur 11.6.1
 - Browser: Chrome
 - Version: 96.0.4664.55

**Comment by stevensturkop** [comment]
If it helps, here is my query
````const { isLoading, isFetchingNextPage, hasNextPage, fetchNextPage } =
    useInfiniteQuery(
      "booking_pending",
      async ({ pageParam }) => {
        return await getBookingData({
          type: `orders/pending${
            pageParam?.seq_id ? `?seq_id=${pageParam.seq_id}` : ""
          }`,
        });
      },
      {
        getNextPageParam: (lastPage, allPages) => lastPage.seq_id,
        onSuccess: (data) =>
          setBookingRequests({
            list: data.pages.reduce((acc, curr) => [...acc, ...curr.list], []),
            seq_id: data.pages[data.pages.length - 1].seq_id,
          }),
      }
    );```

**Comment by TkDodo** [comment]
what would help is a codesandbox reproduction please. As you can see in our [infinite scroll example](https://react-query.tanstack.com/examples/load-more-infinite-scroll), when you scroll down for some pages and then do a window focus refetch, nothing is duplicated / overwritten.

not sure what `setBookingRequests` does but it looks like you're copying state from react-query somewhere else, and that is usually not needed.

**Comment by stevensturkop** [comment]
I just tried accessing the data directly and remove `onSuccess` function and same result.
`const { data, .... } ` 

<img width="401" alt="Capture d'écran 2021-11-25 à 19 09 46 PM" src="https://user-images.githubusercontent.com/42664988/143486643-4cc5a98d-a9d1-4c33-a2cf-0e4b3a19b361.png">

The first time pageParam `seq_id` is an object `{seq_id: 'order_68c02izdawjfjpji74qbqphd'}`
After window refocus the pageParam `seq_id` is a string `order_68c02izdawjfjpji74qbqphd`

Do you know why it does that ?

**Comment by TkDodo** [comment]
I can't tell from a screenshot. codesandbox is the way to go please.

**Comment by stevensturkop** [comment]
https://codesandbox.io/s/wizardly-parm-n58w2?file=/src/App.js

Scroll down, it will load more perfectly, then unfocus and refocus, wait 2-3 seconds and the console will return errors because data are now duplicated.

I have also added logs where you can see that the pages are identical, with the exact same `after` param.

**Comment by TkDodo** [comment]
took me some time to figure it out:

when you manually call `fetchNextPage`, you provide different nextPage params than you do in `getNextPageParam`. If you just call `fetchNextPage` and let `getNextPageParam` compute your param, you'll see that:

- you return `lastPage.data?.after`, which will become your pageParam. This is already a string
- but then in the queryFn itself, you still access try to access  `pageParam?.after`, which doesn't exist, so the queryFn just fetches again without pageParam, yielding the first page over and over again

The easiest fix is just this: https://codesandbox.io/s/pensive-fire-z901i?file=/src/App.js

- call `fetchNextPage` without parameters, so that it works the same as the refetching on window focus
- fix your queryFn because now `pageParam` is of type string
