### ISSUE TITLE
[ReactQueryDevtools] Handle in a better way the "close" button

### ISSUE THREAD

**Issue by kud** [tannerlinsley/react-query#3067]
Hello,

I've got an issue with the "close" button on the interface of the dev tools.

<img width="717" alt="image" src="https://user-images.githubusercontent.com/655838/145061093-ea70a1e5-a90c-4726-95d0-052838684c4e.png">

The "close" button doesn't allow you to see what's the name of the key behind.

Two suggestions to deal with it:
- Use the react-query logo to close the panel
- Add at least a bit of padding in the list of queries to be able to scroll enough to have some space to see the name of the key

Thank you 😊

**Comment by TkDodo** [comment]
I like using the logo. Do you want to contribute this?

**Comment by kud** [comment]
> I like using the logo. Do you want to contribute this?

Yes, 😊

**Comment by hichemfantar** [comment]
Fixed this using the props: `position `and `closeButtonProps`
`					<ReactQueryDevtools
						position={"top-left"}
						closeButtonProps={{ style: { top: 0, bottom: "unset" } }}
						initialIsOpen={false}
					/>
`

**Comment by TkDodo** [comment]
I think the general idea was to have the react-query icon that opens the devtools also have it close the devtools. one advantage of the close button is that it appears at the same spot as the open button, so you can click to open and click to close in the same spot. However, I think the react-query logo can always also close the devtools, basically giving two ways to close it: the icon and the close button. Then, you can hide the close button with:

```
<ReactQueryDevtools closeButtonProps={{ style: { display: "none" } }} />
```

and you could still close them with the logo. That solves the initial issue that the close button overlaps with many queries.

**Comment by hichemfantar** [comment]
Why not replace the close button with the logo and remove the logo inside the dev tool panel? The space taken by the logo can be used for more useful things.

**Comment by TkDodo** [comment]
the close button is always placed where you opened the devtools, but it sometimes overlaps with queries. If we move the logo there, then the logo would overlap with the queries.

the implemented solution is backwards compatible (no need to educate users that the close button is now "gone"), but you can now hide the close button via:

```
<ReactQueryDevtools closeButtonProps={{ style: { display: "none" } }} />
```

and only use the logo to close them again to sidestep the issue of the closebutton overlapping with queries.

**Comment by kud** [comment]
Sorry I forgot to help on this on this one.

Thank you!
