### ISSUE TITLE
React Query Devtools cannot serialize BigInt type

### ISSUE THREAD

**Issue by themagickoala** [tannerlinsley/react-query#3082]
**Describe the bug**
One of the models that I am caching with React Query is a BigInt type. Unfortunately, when I try and inspect the data in the devtools explorer, I get an uncaught error: `TypeError: Do not know how to serialize a BigInt`.

**To Reproduce**
1. Add an object using a BigInt type to the query cache
2. Open the Devtools
3. Select the query in the browser to inspect the data
4. See the error

**Expected behavior**
I should be able to view properly serialised data in the devtools browser.

**Screenshots**
![image](https://user-images.githubusercontent.com/48416253/145600948-09d8ea8f-a75b-4b1a-a382-73d54bd62942.png)

**Desktop (please complete the following information):**
 - OS: Pop_OS 21.04
 - Browser: Chrome
 - Version: 94

**Additional context**
The error can be traced to this line: https://github.com/tannerlinsley/react-query/blob/master/src/devtools/Explorer.tsx#L112. If there's a reason that the data is being stringified, then hopefully there's a way to keep doing it, but there are data types which cannot be parsed by JSON.stringify. There may be other options, such as https://github.com/blitz-js/superjson but I understand that would add further complexity.

**Comment by TkDodo** [comment]
hmm, how should we serialize the BigInt ? You can certainly have non-serializable data in your cache, its just not very common. A couple of things won't work with non-serializable data:
- hydration, which includes SSR and the persist plugins
- structural sharing

for the persist plugins, we actually have an option to provide a different serializer:

https://github.com/tannerlinsley/react-query/blob/b84681fdc7d37645cd149f40e98cb18fd8bc393c/src/createWebStoragePersister/index.ts#L28-L29

if you want, you can contribute something similar to the devtools, as long as it defaults to `JSON.stringify`

**Comment by themagickoala** [comment]
Thanks Dominik. I think you raise a good point, this will also cause an issue with hydration. Is there an option to specify the serializer for hydration, because that's probably a bigger issue? I'd love to take a look at this if I get the time. I'm busy right now, but might get time in the new year if my manager lets me!

**Comment by TkDodo** [comment]
@Ephem I think we decided with this issue:
- https://github.com/tannerlinsley/react-query/issues/1978#issuecomment-819440786

that its a limitation of hydration to only support json serializable values, right? We have since documented it here:

https://react-query.tanstack.com/reference/hydration#limitations

it's actually not a concern of hydration / dehydration, because that gives you an `object`, but it seems that passing this object to the return value of `getStaticProps` in nextJs expects it so be json serializable ?

**Comment by themagickoala** [comment]
Yeah I just dug into the hydration code and the serialisation will ask be the purview of Next, so I can just serialise it myself for hydration. I'll take a look into the dev tools in the new year.

**Comment by TkDodo** [comment]
@themagickoala any updates here, are you actively working on a serializer option for the devtools?

**Comment by themagickoala** [comment]
Afraid not, circumstances have conspired against me and I don't see myself having capacity for this.

**Comment by HenriqueDerosa** [comment]
Hey @themagickoala, @TkDodo , I'd like to have a look on this issue!

I didn't get why javascript doesn't stringify the BigInt. Do we lose important data when doing it? 🤔

**Comment by themagickoala** [comment]
Thanks Henrique! I've actually just this week stopped storing the bigint and started using the select option to convert to bigint on the way out of the cache.

**Comment by mc-petry** [comment]
Should we reopen this issue?

`@tanstack/react-query" 4.13.5`
`@tanstack/react-query-devtools: 4.13.5`

When i open devtools all is ok:
<img width="593" alt="image" src="https://user-images.githubusercontent.com/8122711/199080567-2443d7ce-0246-4f4f-a2d2-f95075a6e9db.png">

but when i tried to select cache with key that contains bigint i have error.

**Comment by vctqs1** [comment]
I got same issue but in `@tanstack/react-query` not in the devtool. do we have any way to bypass this since Im using generate tool and the generate code required `BigInt`

**Comment by TkDodo** [comment]
if it's in the QueryKey: pass a custom `queryKeyHashFn`
if it's in the `data`, it shouldn't be a problem.

**Comment by vctqs1** [comment]
ohh I see thank you

**Comment by 0x33dm** [comment]
I'm having the same problem but on `react-query-devtools` while using https://wagmi.sh/ library.

In some screens when i opened the dev tools it will throw that error.

```ts
BigInt.prototype['toJSON'] = function () {
  return this.toString()
}
```

I had to add this to my `ReactQueryProvider` file

**Comment by murderteeth** [comment]
> I'm having the same problem but on `react-query-devtools` while using https://wagmi.sh/ library.
> 
> In some screens when i opened the dev tools it will throw that error.
> 
> BigInt.prototype['toJSON'] = function () {
>   return this.toString()
> }
> I had to add this to my `ReactQueryProvider` file

so helpful, tu! i ended up adding it my react apps' entry, main.tsx. this way it applied everywhere which doesn't seem to hurt anything

**Comment by whoislewys** [comment]
If you are using Wagmi, do NOT follow this response:

> I'm having the same problem but on `react-query-devtools` while using https://wagmi.sh/ library.
> 
> In some screens when i opened the dev tools it will throw that error.
> 
> BigInt.prototype['toJSON'] = function () {
>   return this.toString()
> }
> I had to add this to my `ReactQueryProvider` file

--

Instead, follow TKDodo's recommendation and the [Wagmi docs example](https://wagmi.sh/react/guides/tanstack-query#devtools) - use the same `hashFn` used by Wagmi to serialize query keys. From their docs:

```js
import {
  QueryClient,
  QueryClientProvider,
} from "@tanstack/react-query";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import { hashFn } from "@wagmi/core/query";

const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      queryKeyHashFn: hashFn,
    },
  },
});
```

**Comment by 0x33dm** [comment]
> --
> 
> Instead, follow TKDodo's recommendation and the [Wagmi docs example](https://wagmi.sh/react/guides/tanstack-query#devtools) - use the same `hashFn` used by Wagmi to serialize query keys. From their docs:
> 
> import {
>   QueryClient,
>   QueryClientProvider,
> } from "@tanstack/react-query";
> import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
> import { hashFn } from "@wagmi/core/query";
> 
> const queryClient = new QueryClient({
>   defaultOptions: {
>     queries: {
>       queryKeyHashFn: hashFn,
>     },
>   },
> });

that's cool!

**Comment by Hugoo** [comment]
The dev tool part is probably what was missing from this issue in the wagmi repo:

- https://github.com/wevm/wagmi/issues/3855

Adding this for reference as the other issue is locked now.
