### ISSUE TITLE
Refetching query doesnt set error back to null

### ISSUE THREAD

**Issue by Tosheen** [tannerlinsley/react-query#3090]
### Describe the bug

When query refetching happens, for example on window focus, error object is not cleared even though types say that when isLoading is set to true, error is always null. Screenshot attached

### Your Example Website or App

https://codesandbox.io/s/boring-paper-l7jf0?file=/src/use-subscription.tsx

### Steps to reproduce

Open the console and watch for variables being displayed, once you refocus back to the window both isLoading and error are displayed.

### Expected behavior

- remove the error when we go to loading state.
- change the types so that they reflect that you can have an error in loading state, too.

### How often does this bug happen?

Every time

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/12643248/145860235-9920eae5-ed1a-4227-b442-91fdc5ea12bd.png)

### Platform

- OS: [e.g. macOS, Windows, Linux, iOS, Android]
- Browser: [e.g. Chrome, Safari, Firefox, React Native]
- Version: [e.g. 91.1]

**Comment by amanzrx4** [comment]
What if i want the error to stay until the data is not coming, on successive refetch the error should stay, is there's any option i can use to achieve that? @TkDodo might help.

**Comment by TkDodo** [comment]
don't think so
