### ISSUE TITLE
Unable to use in legacy Firefox

### ISSUE THREAD

**Issue by fynncfchen** [tannerlinsley/react-query#3134]
### Describe the bug

When use webpack to build for Firefox 34, the console displayed
```
SyntaxError: invalid for/in left-hand side
```
when remove `react-query`, it went back to normal.

### Your Example Website or App

N/A, issue only happened in real Firefox 34.0

### Steps to reproduce

1. Build by running webpack
2. Start application
3. Launch Firefox 34.0 and access to it
4. Display nothing but console shows error
5. Remove any react-query imports
6. Re-build by running webpack
7. Start application
8. Launch Firefox 34.0 and access to it
9. The application works normally

### Expected behavior

As a user, I expected there's no any errors when running application integration with react-query on legacy browser like Firefox 34.

### How often does this bug happen?

Every time

### Screenshots or Videos

![Uploading Screen Shot 2021-12-27 at 14.15.48.png…]()

### Platform

- OS: macOS
- Browser: Firefox
- Version: 34.0

**Comment by TkDodo** [comment]
Couldn't find for..in anywhere in the codebase. Firefox 34 is a 7 year old browser. Whatever the reason, unless this happens in a modern browser, I'm not gonna look into this.

**Comment by fynncfchen** [comment]
I found it in my webpack output:
```
/***/ "./node_modules/react-query/es/core/index.js":
/*!***************************************************!*\
  !*** ./node_modules/react-query/es/core/index.js ***!
  \***************************************************/
```
and it's cause by re-export
```
/* harmony reexport (unknown) */ for(const __WEBPACK_IMPORT_KEY__ in _types__WEBPACK_IMPORTED_MODULE_14__) if(["default","CancelledError","QueryCache","QueryClient","QueryObserver","QueriesObserver","InfiniteQueryObserver","MutationCache","MutationObserver","setLogger","notifyManager","focusManager","onlineManager","hashQueryKey","isError","isCancelledError","dehydrate","hydrate"].indexOf(__WEBPACK_IMPORT_KEY__) < 0) __WEBPACK_REEXPORT_OBJECT__[__WEBPACK_IMPORT_KEY__] = () => _types__WEBPACK_IMPORTED_MODULE_14__[__WEBPACK_IMPORT_KEY__]
```

**Comment by fynncfchen** [comment]
And the real cause is in `es/core/index.js` with following statement:
```
export * from './types';
```

webpack will transpile it into
```
/* harmony reexport (unknown) */ for(const __WEBPACK_IMPORT_KEY__ in _types__WEBPACK_IMPORTED_MODULE_14__) if(["default","CancelledError","QueryCache","QueryClient","QueryObserver","QueriesObserver","InfiniteQueryObserver","MutationCache","MutationObserver","setLogger","notifyManager","focusManager","onlineManager","hashQueryKey","isError","isCancelledError","dehydrate","hydrate"].indexOf(__WEBPACK_IMPORT_KEY__) < 0) __WEBPACK_REEXPORT_OBJECT__[__WEBPACK_IMPORT_KEY__] = () => _types__WEBPACK_IMPORTED_MODULE_14__[__WEBPACK_IMPORT_KEY__]
```
which cause the `for/in` syntax error in FF 34 or legacy browser.
I think it's better to create issue for webpack team, not here.

https://github.com/webpack/webpack/issues/15056
