### ISSUE TITLE
setQueryDefaults doesn't override staleTime

### ISSUE THREAD

**Issue by VividLiu** [tannerlinsley/react-query#3144]
### Describe the bug

I am trying to use queryClient.setQueryDefaults() to override individual query options, but it doesn't seem to work. 
My use case is that I need to override the staleTime base on the data I received from server after initial fetch using useQuery. 
I did some simple test to use queryClient.setQueryDefaults() to override staleTime, but there is no effect. 
Following is the code snippet: 

```
export const ServerPage: React.FC<ServerPageProps> = (props: ServerPageProps) => {
    const { isLoading, isFetching, isError, data, error } = useQuery('key1', () => fetchFn(props.url!), {
        staleTime: 1000 * 20,
    });
    const queryClient = useQueryClient();

    useEffect(() => {
        queryClient.setQueryDefaults('key1', { staleTime: 0 });
    });

    console.log('query option: ', queryClient.getQueryDefaults('key1'));
     ....
     return(...)
}
```
Although the console.log printed 'query option:  {staleTime: 0}' correctly, the page doesn't refetch every time I re-route to it. It only refetches after 20s passed. 

I am using React-Query version: 
{
  "name": "react-query",
  "version": "3.24.4",
  "description": "Hooks for managing, caching and syncing asynchronous and remote data in React",
  "author": "tannerlinsley",
  "license": "MIT",
  "repository": "tannerlinsley/react-query",
  ...
}

### Your Example Website or App

n/a

### Steps to reproduce

n/a

### Expected behavior

The page should refetch every time when it re-mounts, since the staleTime is overriden to 0. 

### Platform

- OS: iOS, Android
- Browser: React Native
- Version: 3.24.4

**Comment by TkDodo** [comment]
please provide a codesandbox reproduction. And please note that options set on useQuery will always take precedence over defaults. The order is (from least to most specific):
- defaultOptions in queryClient
- defaults set by setQueryDefaults
- options on useQuery

**Comment by VividLiu** [comment]
Thank you for informing me the order of how the options are set. It helped me to answer my question why setQueryDefaults didn't override the options set in useQuery().

**Comment by VividLiu** [comment]
I found another issue of using setQueryDefaults to set cacheTime.

code sample: https://codesandbox.io/s/react-query-cachetime-q03d9?file=/src/App.js

In the sample, I set cacheTime to 1000 * 60 in defaultOptions in queryClient . 
```
const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      cacheTime: 1000 * 60 * 1, // 1 min
    }
  }
});
```

Later on, in the component, I tried to override the cacheTime to 0 using setQueryDefaults.
```
   queryClient.setQueryDefaults("key1", {
      cacheTime: 0
    });
```

The expected behavior should be: 
1. Load the page, home page shows.
2. click 'server page', it loads ServerPage, and show 'Loading...' since it is first time loading. 
3. click 'home' to to back to home page. Wait a few second and click 'server page' to go to ServerPage again. 
4. Since the cacheTime is overriden to 0, it supposes to remove the cache after we left 'server page' and show 'Loading...' Instead, the cache is not removed, and shows 'Refreshing...'

I stepped through the source code and found: 
https://github.com/tannerlinsley/react-query/blob/3981f5219a1e3d8f48d13108b55673dcaea46319/src/core/query.ts#L191-L194
in this line, this.cacheTime is still 60000 the second time I came back to 'server page'.

Only if I wait until 60000ms passed and the cache is removed, then afterwards, the behavior is correct.

**Comment by TkDodo** [comment]
I think the issue is more that the cacheTime that is set on the observer is never passed to the query itself, as it looks like the defaultOptions for a query are set on the query when the query is created. I think this would affect all cache related options, not just cacheTime 🤔 . I think the defaultOptions are not meant to affect currently mounted queries, but I could be wrong.

**Comment by TkDodo** [comment]
>  I think the defaultOptions are not meant to affect currently mounted queries, but I could be wrong.

I can confirm this now. setting defaultOptions will also _not_ inform active observers about the change, so it needs to be set before you create the query.
