### ISSUE TITLE
Expose `queryClient` in QueryFunctionContext

### ISSUE THREAD

**Issue by GLabat** [tannerlinsley/react-query#3151]
> however, composing query functions from other queries of the same client seems useful. for example, you can currently do this via:

```
const queryClient = useQueryClient()
useQuery(key, () => queryClient.getQueryData(something) ?? axios.get(...))
```

> if the query function is not inlined, passing the client is necessary, so I agree that having the client injected might be useful in some cases. I'll definitely think about it :)

_Originally posted by @TkDodo in https://github.com/tannerlinsley/react-query/discussions/2764#discussioncomment-1887755_

This issue is a follow-up of the discussion above.
The idea is to have access to the queryClient in the queryFn, using QueryFunctionContext to simplify usage when the queryFn is defined outside of a `useQuery/fetchQuery` call.

**Comment by GLabat** [comment]
Should consider https://github.com/tannerlinsley/react-query/pull/2548 which adds the ability to nest QueryClient contexts.
Once merged, if the `queryClient` is passed in someway to the `queryFn`, it should the "good" one, ie. the one from the query context.

**Comment by TkDodo** [comment]
I've decided to not move along with this for now. The use-case is pretty narrow, and the custom context complicates that a bit more. There also doesn't seem to be an incredible need for this features.

**Comment by TkDodo** [comment]
you can use the same query from within multiple providers, but there is only one Query instance. Only observers have access to the QueryClient, the query itself (which also runs the queryFn) does not.
