### ISSUE TITLE
`queryClient.clear()` does not clear previously `setQueryDefaults` calls

### ISSUE THREAD

**Issue by omerp-explorium** [tannerlinsley/react-query#3155]
### Describe the bug

The clear function of queryClient does not clear query defaults that are previously set.

Thanks in advance, always loving & using this library ;)

### Your minimal, reproducible example

https://codesandbox.io/s/vigorous-dirac-i8elz?file=/src/index.js

### Steps to reproduce

```
/* eslint-disable jsx-a11y/anchor-is-valid */
import { QueryClient } from "react-query";

const queryClient = new QueryClient();

queryClient.setQueryDefaults("key", 5);
queryClient.clear();

console.log("is cleared?", queryClient.getQueryDefaults("key") !== 5);
```

### Expected behavior

Expected that the clear method will also clear defaults, or at least have another function "clearDefaults".

### Platform

all

### react-query version

^3.33.7

**Comment by TkDodo** [comment]
This is not what clear does - it clears the underlying _caches_ - the `queryCache` and the `mutationCache`. This is documented here: https://react-query.tanstack.com/reference/QueryClient#queryclientclear

> queryClient.setQueryDefaults("key", 5);

not sure what this should do? with `setQueryDefaults`, you can set default options, like:

```
queryClient.setQueryDefaults("key", { staleTime: 5 });
```

setting the options to `5` wouldn't do anything and is also invalid in TypeScript.

for "clearing" defaults, you can just call `queryClient.setQueryDefaults("key", {})`, basically setting them to an empty object.

**Comment by omerp-explorium** [comment]
@TkDodo Thank you for the quick response. I'm sorry my bad, I meant:

`queryClient.setQueryDefaults("key", { initialData: 5 });`

I expected that after clearing the cache, this will also be cleared. But as I understand this is not intended.. Maybe I should not use initialData with setQueryDefaults.

**Comment by TkDodo** [comment]
You can for sure use it together. But clearing the caches does not reset the defaults.
