### ISSUE TITLE
[Load More / Infinite Scroll example] wrong state of button to load older data

### ISSUE THREAD

**Issue by maricabertarini** [tannerlinsley/react-query#3171]
### Describe the bug

The button to load older projects contains `Nothing more to load` text, it is enabled and older projects gets fetched and shown when the button gets click. Its text should be `Load Older` instead because there are still some older projects to be loaded.

The mistake is in the following code snippet:
```
            <button
              onClick={() => fetchPreviousPage()}
              disabled={!hasPreviousPage || isFetchingPreviousPage}
            >
              {isFetchingNextPage
                ? 'Loading more...'
                : hasNextPage
                ? 'Load Older'
                : 'Nothing more to load'}
            </button>
```

`hasNextPage` should be replaced by `hasPreviousPage`

### Your minimal, reproducible example

https://codesandbox.io/s/github/tannerlinsley/react-query/tree/master/examples/load-more-infinite-scroll

### Steps to reproduce

1. Go to [load-more-infinite-scroll sandbox](https://codesandbox.io/s/github/tannerlinsley/react-query/tree/master/examples/load-more-infinite-scroll)
2. Scroll all the way to the bottom
3. Click "Load Newer"
4. Repeat point 2. until the bottom button says "Nothing more to load"
5. Scroll all the way to the top
6. See the top button saying "Nothing more to load" whilst being enabled.
7. Click the button described in point 5.
8. See older projects being loaded.

### Expected behavior

At point 6. of the steps to reproduce the top button text should be "Load Older" instead and keep this text until there are no more older projects to be loaded (i.e. when `hasPreviousPage` turns `false`).

### How often does this bug happen?

Every time

### Screenshots or Videos

https://user-images.githubusercontent.com/5780964/148691126-7a7fd3a2-a93d-4ac1-beb5-3a6512636fc6.mp4

### Platform

- macOS 11.6
- Chrome
- 96.0.4664.110 (Official Build) (x86_64)

### react-query version

3.5.0

### Additional context

Happy to get the issues assigned and fix it myself :)

**Comment by TkDodo** [comment]
> Happy to get the issues assigned and fix it myself :)

awesome, thank you for reporting and please feel free to contribute a PR 🙏

**Comment by maricabertarini** [comment]
PR submitted ✅ 
I do not have the rights to assign this issue to myself, is that expected?
