### ISSUE TITLE
Data becomes unstable when select is inlined

### ISSUE THREAD

**Issue by Grapedge** [tannerlinsley/react-query#3181]
### Describe the bug

react-query's structured sharing becomes unstable when selecting data using inline `select`.

### Your minimal, reproducible example

https://codesandbox.io/s/keen-dawn-jilgs?file=/src/index.js

### Steps to reproduce

1. Click `rerender!`

### Expected behavior

When the `rerender!` button is clicked, it should not print `data changed!`

### How often does this bug happen?

Every time

### Platform

- Chrome

### react-query version

v3.34.7 and above

### Additional context

May be caused by [#3140 ](https://github.com/tannerlinsley/react-query/pull/3140)

**Comment by TkDodo** [comment]
definitely caused by #3140 , thanks for reporting. working on a fix ...
