### ISSUE TITLE
Previous user data is coming to new user for sometime and then new data is coming

### ISSUE THREAD

**Issue by vinitgundeti** [tannerlinsley/react-query#3182]
### Describe the bug

I am fetching data by usinf useQuery 
`const { data: customUserData, isLoading: userLoading, refetch: refetchUser } = useQuery(
		['user-details'],
		userService.getUserProfileDetails,
	);`
The above code fetches the user's data and I am showing the response of the above to the user.
so when the current user logs out and another user comes, the previous user data is showing for some time and then new data is coming.

I tried by
queryClient.removeQueries
queryClient.invalidateQueries
queryClient.clear

but still getting the same issue.

And when I add the breakpoint for debugging the refetch is happening from other screen as well.

for ex : I am refetching data in screen 'a' and added a breakpoint on screen 'a'. This breakpoint is triggering from screen 'd' as well

### Your minimal, reproducible example

NA

### Steps to reproduce

fetch new user data, logout and refetch.

### Expected behavior

When I log in with a new user, previous user data should not come. And till new user data fetches isLoading should be true

### How often does this bug happen?

Every time

### Screenshots or Videos

https://user-images.githubusercontent.com/47896506/149125701-66c4b3ff-e62a-4cf4-8bc7-38842dffafe8.mov

### Platform

- OS: macOs
- react-native : 0.62.2

### react-query version

v3.16.0

**Comment by TkDodo** [comment]
Please add a codesandbox reproduction ❗️

**Comment by vinitgundeti** [comment]
Hi @TkDodo This is done in react native. can you tell me how can I remove the old data so that new user doesn't see data from cache.
I uploaded screen record

**Comment by TkDodo** [comment]
we have a react-native example with expo snack, you can fork it and go from there:
https://react-query.tanstack.com/examples/react-native

`queryClient.removeQueries` will remove data from the cache, but does not inform observers, so if they are rendered on the screen, it will stay there. This is a good function to use when you logout and go to the login screen and remove all queries for the user.

`queryClient.resetQueries` will reset a query to its initial state and then inform / rerender all observer / components, so that they can then refetch. Unless you have initialData specified, they will go to loading state.

**Comment by vinitgundeti** [comment]
Hi @TkDodo,

`const queryClient = useQueryClient();
		queryClient.resetQueries(['user-details'], { exact: true })
		queryClient.removeQueries(['user-details'])
		queryClient.clear();
		queryClient.invalidateQueries(['user-details'], { exact: true,}, { cancelRefetch })`
		
I have tried all these things on logout but still getting the previous data
<img width="848" alt="Screenshot 2022-01-13 at 10 28 17 AM" src="https://user-images.githubusercontent.com/47896506/149268471-05fe9c73-8767-4ca6-bc5f-1e03ca12372f.png">

You can see in the above image after new login for sometime old userdata (user_id : 'P56F6AZ64E') is fetched and later new userdata(user_id : 'E6OKD2929V') has come

The below is the code of refetch
`const { data: customUserData, isLoading: userLoading, refetch: refetchUser } = useQuery(
		['user-details'],
		userService.getUserProfileDetails
	);`

**Comment by TkDodo** [comment]
feel free to reopen once you have a minimal reproduction.

**Comment by metrnametr** [comment]
@vinitgundeti did u find the solution?
I have the same issue

**Comment by cgat** [comment]
I'm experiencing something similar in React Native. The major difference in React Native is navigation, where the root of the stack is kept around indefinitely. So in my case, my `useQueryUserAccount` query done is a provider (auth provider) near the root and thus the it doesn't become inactive and thus `removeQueries` has no effect, even in a login screen type scenario. `resetQueries` in the login screen will do the try I believe, but it seems like a bit of a smell. I'll see if I can find time to whip up a reproducible example.

**Comment by kholiqcode** [comment]
any solutions?

`"@tanstack/react-query": "^4.29.13",`

**Comment by Arsalan2004** [comment]
> > 
> 
> I fixed this with const queryClient = useQueryClient(); queryClient.removeQueries();

Is it give new data to you when login again

**Comment by huduarte** [comment]
Any updates ?

**Comment by TkDodo** [comment]
> feel free to reopen once you have a minimal reproduction.

no one has done that, so what do you expect?

**Comment by robertocerdasilva** [comment]
This case should not be closed. It is an error that continues to persist.

Log out of a user and log in with other credentials, the previous data of the previous user is displayed for a minimum of time.

This not working for me
```
const queryClient = useQueryClient();
queryClient.removeQueries();
```

**Comment by TkDodo** [comment]
@robertocerdasilva it's closed since January 2022 waiting for someone to make a reproduction that shows the error. No one has done so in 2.5 years. I wonder why that is.

**Comment by omatsola619** [comment]
not me facing the same issue today
has anyone found a solution to this in 2026 or i should look else where

**Comment by TkDodo** [comment]
@omatsola619 please show a minimal reproduction.
