### ISSUE TITLE
Typescript definitino of useInfiniteQuery is missing canFetchMore

### ISSUE THREAD

**Issue by ashleybartlett** [tannerlinsley/react-query#319]
Firstly, thanks for promptly creating the updated the TypeScript definitions. 

Found that the useInfiniteQuery is missing the response param `canFetchMore`, though this is declared in your documentation.

```
const canFetchMore: any
Property 'canFetchMore' does not exist on type 'InfiniteQueryResult<DataInterface>, number>'.ts(2339)
```

**Comment by tannerlinsley** [comment]
This issue belongs in https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-query.

**Comment by tannerlinsley** [comment]
FYI - https://github.com/tannerlinsley/react-query/discussions/362

**Comment by ashleybartlett** [comment]
cheers!  I saw that one, as I had earmarked some time to raise the ticket there. Lo and behold, it had already been done!
