### ISSUE TITLE
TData gets incorrectly inferred in useQuery when providing both select and onSuccess

### ISSUE THREAD

**Issue by davbrito** [tannerlinsley/react-query#3193]
### Describe the bug

Say that I have a `queryFn` that returns type `T` and a `select` function that returns type `U`. If I provide a `onSuccess` function, TypeScript complains that `select` function should return type `T`. And the `onSuccess` function data parameter gets typed as `T`.

```tsx
declare const data: T;

const query = useQuery(
  ['queryKey'],
  () => data,
  {
     select: data => data.u // Returns type "U" but TypeScript wants "T" for some reason
     onSuccess(data) { // Should be type U but is inferred as T
        console.log(data)
     }
  })
```

The workaround is to explicitly type the onSuccess param to be of type `U`.

```tsx
declare const data: T;

const query = useQuery(
  ['queryKey'],
  () => data,
  {
     select: data => data.u // Works as expected
     onSuccess(data: U) {
        console.log(data)
     }
  })
```

### Your minimal, reproducible example

https://codesandbox.io/s/serene-hofstadter-56r0r

### Steps to reproduce

1. Create a query with `useQuery`.
2. Pass a `select` function that select some data with diferent type than returned by the `queryFn`.
3. Pass a `onSuccess` function and let TypeScript infer the parameter types.

### Expected behavior

- The first parameter of the `onSuccess` should be the same as the return type of the `select` function.
- The `TData` type should be inferred with the return type of the `select` function.

### How often does this bug happen?

Every time

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/39559632/149356481-f7fe230b-f2d0-474e-9164-508b3fa534cf.png)
![image](https://user-images.githubusercontent.com/39559632/149356575-622b6f9f-8489-463f-bde6-d935e232fb84.png)

### Platform

- OS: Windows 11
- Browser: Not related because it's a TypeScript issue.

### react-query version

v3.34.8

### TypeScript version

v4.5.4

**Comment by TkDodo** [comment]
it's a (somewhat) known limitation that I'm unsure how to fix. `useMutation` has the same issue when you provide `onMutate` and want type inference for `onSettled`. There, the key is to explicitly type the input value for `onMutate`.

In your case, the workaround is to explicitly type the input to the `select` function: https://codesandbox.io/s/cranky-cohen-oc1sq?file=/src/App.tsx

related:
- https://github.com/tannerlinsley/react-query/pull/1366#discussion_r538459890
- https://tkdodo.eu/blog/react-query-and-type-script#optimistic-updates
- https://github.com/microsoft/TypeScript/issues/26242

**Comment by jasikpark** [comment]
https://tkdodo.eu/blog/react-query-and-type-script#partial-type-argument-inference 🤔 I finally understand *why* you would want partial argument inference - at first I didn't see what the usecase would be

**Comment by HenriqueDerosa** [comment]
In my understanding, the purpose of the `select` is to be dynamic, allowing to customize the output of the api to be whatever we need in the front end.

Thus, `select` should NOT use the same return type as the onSuccess. If we want the `useQuery` to return the same type, we can basically omit the `select`.

I found out that you can actually infer the type for the select, as [the link shared](https://tkdodo.eu/blog/react-query-and-type-script#partial-type-argument-inference) also exemplifies, as following:
```
  const { data, isLoading } = useQuery<MyResponseType, Error, string>(
    ["example query"], () => Promise.resolve(queryData),
    {
      select: (data) => data.innerData,
```

Please, correct if I'm wrong 🤔

**Comment by TkDodo** [comment]
> I found out that you can actually infer the type for the select,

yes, you can, and that also works most of the time. react-query has 4 generics, and the 3rd one (`TData`)  is so that `select` can return a different type than the `queryFn` ( the first generic, `TQueryFnData`).

However, the type inference seems to get lost as soon as you use both `select` _and_ `onSuccess` as option. `onSuccess` should also get passed `TData`, which is the transformed / selected data.

**Comment by davbrito** [comment]
I think this is related to the problem: https://devblogs.microsoft.com/typescript/announcing-typescript-4-7-beta/#improved-function-inference-in-objects-and-methods

**Comment by TkDodo** [comment]
indeed, TypeScript 4.7 seems to fix that problem: [playground link](https://www.typescriptlang.org/play?ts=4.7.0-dev.20220408#code/JYWwDg9gTgLgBAbzgVwM4FMCKz1QJ5wC+cAZlBCHAORToCGAxjALQCOO+VAUFwxAHap47XHgDS6AgF44AbQBEMdEPkAaOAEZ1AJnVIAzAC44MKDiIBdOHVRw+gmD3tC4I-ABE6MOnBkIucHDA-Py4nt7G8gAWEAA2dPJcxDZ2AkJOafBIACZedOrAqAAyEHTZwQDmRL4oGNiiABQBcvLoAB504LHorhx48haqzQ0AlL4AfHAACuQghegAdLSocQBu6A1ueOF0I0OB-oGBGN1Mxg253mNSk5d0C8GhUDv7RwD0b0dfgQB6APzNQICADKyAYDGUqAueTGh3en2+X3+gKOzjii1iEAqDXkwPQpyU2Tgd0MamJMIA3CjCM0aSMuEA)

I'll close this as an upstream issue with TypeScript.
