### ISSUE TITLE
react-native support

### ISSUE THREAD

**Issue by netfishx** [tannerlinsley/react-query#32]
now, in react-native throw error:
`
Unhandled JS Exception: TypeError: window.addEventListener is not a function. (In 'window.addEventListener('visibilitychange', revalidate, false)', 'window.addEventListener' is undefined)

RCTFatal
-[RCTExceptionsManager reportFatalException:stack:exceptionId:]
__invoking___
-[NSInvocation invoke]
-[NSInvocation invokeWithTarget:]
-[RCTModuleMethod invokeWithBridge:module:arguments:]
facebook::react::invokeInner(RCTBridge*, RCTModuleData*, unsigned int, folly::dynamic const&)
facebook::react::RCTNativeModule::invoke(unsigned int, folly::dynamic&&, int)::$_0::operator()() const
invocation function for block in facebook::react::RCTNativeModule::invoke(unsigned int, folly::dynamic&&, int)
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_lane_serial_drain
_dispatch_lane_invoke
_dispatch_workloop_worker_thread
_pthread_wqthread
start_wqthread
`

**Comment by tannerlinsley** [comment]
I'll get this fixed asap. Thanks for reporting!

**Comment by tannerlinsley** [comment]
Should be fixed in `0.3.10`. Thanks!
