### ISSUE TITLE
QueryClientProvider not working with docker

### ISSUE THREAD

**Issue by tienpvse1** [tannerlinsley/react-query#3201]
### Describe the bug

When I wrap my whole app with QueryClientProvider, and use "docker-compose up -d" command to deploy my app, it keeps reloading, but when I run my app locally without docker, everything is normal

### Your minimal, reproducible example

https://codesandbox.io/s/new

### Steps to reproduce

1.Create an React app with Vite
2. Add Dockerfile, dockercompose.yaml to deploy app
3. wrap whole app inside QueryClientProvider
4. deploy app using "docker-compose up -d" command
5. go to browser and take a look at deployed app
6. see the error

### Expected behavior

As a developer, I expect app to run normally, but it keep reloading when I deploy with docker

### How often does this bug happen?

Sometimes

### Platform

- OS: Window
- browser: Chrome
- 

### react-query version

3.34.8

### TypeScript version

latest

**Comment by TkDodo** [comment]
This doesn't sound like an issue related to react-query, and it's impossible to look into without a minimal reproduction. Please feel free to reopen the issue with a minimal codesandbox reproductive that clearly shows that your situation works without react-query and then breaks when you add a QueryClientProvider. Thank you.
