### ISSUE TITLE
type inference works unexpectedly when using 'useQueries' with queryFunction factory function.

### ISSUE THREAD

**Issue by seanbruce** [tannerlinsley/react-query#3208]
### Describe the bug

we used to use multiple 'useQuery' hooks for parallel queries. Now we start to do some prep work for React 18 release, including doing all parallel queries using 'useQueries'.

we used a lot of factory functions to generate 'queryKey' and 'queryFunction'.  It works with 'useQuery' but not 'useQuries'.

I prepared a simple demo to show TS errors.

sorry if I miss something important in the document to let these TS errors occur.

### Your minimal, reproducible example

https://codesandbox.io/s/gallant-shirley-4y51y?file=/src/App.tsx:381-393

### Steps to reproduce

1. go to codesandbox demo
2. in the App component, there are two sets of 'getQueryKey' and 'getQueryFunction'  passed to both useQuery and useQueries.
3. useQuery has no TS errors, but useQueries does.

### Expected behavior

there is no TS Errors

### How often does this bug happen?

Every time

### Platform

macOS and windows
Google Chrome v97

### react-query version

v3.34.8

### TypeScript version

v4.5.4

**Comment by TkDodo** [comment]
Thanks for reporting. It seems that types for the queryKey don't flow through in `useQueries` as they do for `useQuery`. Maybe @artysidorenko can take a look as the original author of the useQueries types?

**Comment by artysidorenko** [comment]
Yep my bad, hadn't included `TQueryKey` in the original type inference logic (hadn't thought of it 😅). The attached PR should fix it.
