### ISSUE TITLE
NotifyManager breaks when a exception occurs in onSuccess callback

### ISSUE THREAD

**Issue by sin3hz** [tannerlinsley/react-query#3215]
### Describe the bug

When a exception occurs in `onSuccess` callback
```ts
mutation.mutate(
  {},
  {
    onSuccess: () => {
      throw new Error();
    },
  },
);
```
whitch notify by `NotifyManager.batch`
```ts
batch<T>(callback: () => T): T {
  this.transactions++
  const result = callback() // exception raise
  this.transactions-- // not executed
  if (!this.transactions) { // never be 0
    this.flush()
  }
  return result
}
```
since `NotifyManager.batch` breaks, all newly created query's result would stuck in loading state even fetch succuessful

### Your minimal, reproducible example
https://codesandbox.io/s/gracious-danny-zfq8u?file=/src/App.js
1. click mutate
2. click query

### Steps to reproduce

```ts
mutation.mutate(
  {},
  {
    onSuccess: () => {
      throw new Error();
    },
  },
);
```

### Expected behavior

QueryObervable should notify onSuccess defensively

### Platform

irrelevant

### react-query version

3.34.7

**Comment by TkDodo** [comment]
> Your minimal, reproducible example
none

please create a codesandbox reproduction, thanks

**Comment by sin3hz** [comment]
> > Your minimal, reproducible example
> > none
> 
> please create a codesandbox reproduction, thanks

done

**Comment by TkDodo** [comment]
thank you. In the attached PR, the sandbox works, and I also made a test that failed before and now works. Can you give it a quick review? Then we can merge it: https://github.com/tannerlinsley/react-query/pull/3216

**Comment by sin3hz** [comment]
Thanks! I think the next batch works ok now.
I haven't try yet, but I guess there still an issue that subsequence callbacks (e.g. `getQueryCache().notify`) on the same batch whitch exception occurs wound't get call.
Catch exception above onSuccess/onSettled should fix this.

**Comment by TkDodo** [comment]
hmm, we just tested for mutations here. For queries, it would mean that listeners (useQuery) would _not_ be informed about the update because of the error. But I don't think that try/catch around those is really a better option...

**Comment by TkDodo** [comment]
I think I'll go ahead and merge the fix and we can think about further improvements separately

**Comment by ncoen97** [comment]
I think the issue is still present, it happened to me on 4.3.4 on the onSettled function.

**Comment by TkDodo** [comment]
@ncoen97 show an example please

**Comment by ncoen97** [comment]
Here is a [code sandbox](https://codesandbox.io/s/kind-johnson-d0ndh0?file=/src/index.jsx). If you look at the onSettled, I was missing the function after the `queryClient.invalidateQueries()` I can't see the error in the sandbox, but in my local development this is what I'm getting:

```
Uncaught (in promise) TypeError: callback is not a function
    at notifyManager.ts:51:9
    at notifyFn (notifyManager.ts:15:5)
    at notifyManager.ts:63:13
    at Array.forEach (<anonymous>)
    at notifyManager.ts:62:25
    at batchedUpdates$1 (react-dom.development.js:26096:12)
    at notifyManager.ts:61:9.
```

**Comment by TkDodo** [comment]
this is a different problem. by doing:

```
onSettled: queryClient.invalidateQueries()
```

you're calling `queryClient.invalidateQueries()` during render, and you pass the resulting _promise_ to `onSettled`, where a function is expected. TypeScript can solve this one.
