### ISSUE TITLE
Deconstructing useQueryClient() to access methods 

### ISSUE THREAD

**Issue by Lyncee59** [tannerlinsley/react-query#3230]
### Describe the bug

Hello everyone, not 100% sure this is a bug.

I was trying to use the invalidateQueries method from the queryClient, and simply tried to write

```const { invalidateQueries } = useQueryClient();```

However this is not working as expecting and I had to get back to 

```
const queryClient= useQueryClient();
queryClient.invalidateQueries(.....
```

This is not a big deal as I managed to get myself sorted out, however the way this hook is typed was allowing me to deconstruct the returned queryClient the way I did in the first sample. 

Any thoughts?

### Your minimal, reproducible example

None

### Steps to reproduce

None

### Expected behavior

I would expect to be able to use correctly any methods exposed by the queryClient object, by deconstructing directly the useQueryClient() hook.

### How often does this bug happen?

Every time

### Screenshots or Videos

None

### Platform

Windows 10 / Chrome

### react-query version

3.19.1

### TypeScript version

3.8.0

### Additional context

None

**Comment by TkDodo** [comment]
`QueryClient` is a class - you can see that because you instantiate it with `new QueryClient()`. class methods usually cannot be deconstructed because they lose scope. You will get the same error if you do:

```
const { getDay } = new Date()
getDay()
```

however, this works fine:

```
const date = new Date()
date.getDay()
```

**Comment by Lyncee59** [comment]
Oh thanks @TkDodo makes sense. Haven't paid attention to that. Got mislead with the typings! Thanks again
