### ISSUE TITLE
Outdated comparison

### ISSUE THREAD

**Issue by shuding** [tannerlinsley/react-query#3243]
### Describe the bug

The stable version of SWR has deep key comparison with stable serialization by default ([release note](https://github.com/vercel/swr/releases/tag/1.1.0)) for a while, but the “Query Key Change Detection” row still shows “shallow compare” for SWR. Also for “Query Data Change Detection”, SWR no longer uses dequal but deep comparison with stable serialization too.

Thanks for putting together this comparison table though! It would be great to keep it up to date.

### Your minimal, reproducible example

n/a

### Steps to reproduce

n/a

### Expected behavior

n/a

### Platform

n/a

### react-query version

n/a

**Comment by TkDodo** [comment]
Feel free to open a pr and update it please
