### ISSUE TITLE
Infinite query key is typed to only allow string

### ISSUE THREAD

**Issue by MaddBuddha** [tannerlinsley/react-query#3258]
### Describe the bug

i want to pass an array for the query key of infinite query but it is typed to only allow string which throws a bug. the array still works if i ignor it but i don't think it should throw a typer error.

### Your minimal, reproducible example

n/a

### Steps to reproduce

make an infinite query in type script
pass an array
get yelled at by linter

### Expected behavior

dont get yelled at by linter

### Platform

mac

### react-query version

"react-query": "~3.23.2",

### TypeScript version

n/a

**Comment by TkDodo** [comment]
Please provide a reproduction. Codesandbox supports typescript, or a typescript playground would also suffice here.
