### ISSUE TITLE
useQuery - failureCount does not reflect a refetch

### ISSUE THREAD

**Issue by zsid** [tannerlinsley/react-query#3259]
### Describe the bug

This might be also a feature but not a bug. My use case is:

- I have a component that uses `useQuery` with an option to `retry: false`. After the failure, I show an error with an option to retry. Here the `failureCount` will be 1 since I have only done once request, with 0 retries.
- When a user presses the retry button, I use the `refetch` function from `userQuery` to do another request.
- When this request fails again, the failure count starts with 0 while making an API call and when that fails it becomes 1 again.

### Your minimal, reproducible example

https://codesandbox.io/s/broken-fog-zduyz?file=/src/index.js

### Steps to reproduce

Open the [code sandbox](https://codesandbox.io/s/broken-fog-zduyz?file=/src/index.js). You can hit retry and see that the failure count is reset to 0.

### Expected behavior

The description of failureCount is:
```
failureCount: number
The failure count for the query.
Incremented every time the query fails.
Reset to 0 when the query succeeds.
```
- I would expect when the query fails, when I do a refetch to persist the failureCount since there query is not yet successful. When it fails on the refetch, I would expect the failure count to be incremented by 1, since I have made one more additional request.
- If I navigate away to another page and the component with the query is unmounted, when I come back to the page, I would expect the failureCount to start from 0 i.e. be reset.

### How often does this bug happen?

Every time

### Platform

I have added a sandbox link above. It shouldnt matter what operating system and browser are used. I am using Mac with the newest Chrome. 

### react-query version

3.34.12

**Comment by TkDodo** [comment]
seems to be an error in the documentation. The `failureCount` resets on every `fetch`. Is meant to show the number of failures while internally retrying. So it will go to 1, then 2, then 3 while still being in `loading` state. once it goes to `error`, it stays that way, and if start a new re-fetch, it will go to 0 again.

As far as I'm aware there is no global counter for how often a query has failed. What would you need it for?

**Comment by zsid** [comment]
My business requirement is to show an error message with a retry button when the get request fails. The user can try 3 times in a row to make a new request and if all of them fail then I will show them a different message and remove the retry button.

As a result, I need to track how many times the get request has failed. I thought I could use `failureCount` but that looks to not be a case. I will develop my own tracker then.

However, that might be a new feature request. I am curious to see how people use `failureCount` in their apps at the moment or if at all apart from the internal implementation to track how many retries it is doing.

**Comment by TkDodo** [comment]
I think the easiest way to achieve this would be with an error boundary, and when you reset it, you increment a counter. It also sounds like you'd then want to turn off react-queries internal `retry`, unless you want 3 retries before you show the user anything, and then they can retry 3 times more, which would lead to 9 requests.

**Comment by jalooc** [comment]
> seems to be an error in the documentation. (...) Is meant to show the number of failures while internally retrying

Still not reflected in the documentation, is it?
![Image](https://github.com/user-attachments/assets/c6e7c334-8011-4bd4-8abd-62ae2239b9d0)

The current behaviour is very unintuitive, so this caveat should be emphasized in the docs. It has a potential of wasting a lot of time on debugging.
