### ISSUE TITLE
useIsFetching renders too often

### ISSUE THREAD

**Issue by fzaninotto** [tannerlinsley/react-query#3261]
### Describe the bug

I use `useIsFetching` to display a loading indicator. It is on if there is at least one pending query, off otherwise. The page contains several components, each querying their data, so the number of active queries goes like this:

- 0
- 2 => loading
- 1
- 0 => not loading
- 6 => loading
- 7
- 6
- 0 => not loading

I expect the state of the loading indicator to change 4 times in this case. But since `useIsFetching` returns a number, the component renders 8 times instead (according to the React profiler).

I tried to make a hook that renders less:

```jsx
const useIsLoadingBoolean = () => {
    const isFetching = useIsFetching();
    const [isLoading, setIsLoading] = useState(isFetching > 0);
    useEffect(() => {
        setIsLoading(isFetching > 0);
    }, [isFetching]);
    return isLoading;
};
```

The component still renders 8 times. 

How could I minimize the renders of a simple loading indicator? 

### Your minimal, reproducible example

https://codesandbox.io/s/cool-field-8n96p?file=/src/index.js

### Steps to reproduce

On mount, the Loader component renders 5 times (instead of 3).

![image](https://user-images.githubusercontent.com/99944/152407982-2b6168d1-9f1a-487b-a9c8-85773dfc0709.png)

### Expected behavior

I expect the `useIsFetching()` hook not to force the rendering of a loading indicqator when it's just changing the number of active queries

### Platform

- OS: MacOS
- Browser: Chrome Evergreen

### react-query version

v3.32.1

### Additional context

I'm working on profiling and optimizing [react-admin v4](https://github.com/marmelab/react-admin/issues/5933)

**Comment by TkDodo** [comment]
I think you are forgetting the renders where the count is `0`. I've added a quick:

```
  React.useEffect(() => {
    console.log('rendering', isFetching)
  })
```

to your `Loader`, and it shows:

```
rendering  0
rendering  3
rendering  2
rendering  1
rendering  0
```

which looks expected to me. Internally, we just call `setState` with a number primitive, so even if we do call this too often, react itself would bail out of rendering if we set it to the same number multiple times:

https://github.com/tannerlinsley/react-query/blob/b84681fdc7d37645cd149f40e98cb18fd8bc393c/src/reactjs/useIsFetching.ts#L37-L40

**Comment by fzaninotto** [comment]
Right, but it's still too often - I need a simple way to render a loading indicator with just active / passive states.

For what it's worth, I've reused the code from `useIsFetching` and `useIsMutating` to create a new hook:

```jsx
import React from 'react';

import { notifyManager, useQueryClient } from 'react-query';

/**
 * Get the state of the API connection.
 *
 * Returns true if a query or a mutation is pending.
 */
export const useLoading = (): boolean => {
    const client = useQueryClient();
    const mountedRef = React.useRef(false);
    const isFetchingRef = React.useRef(client.isFetching() > 0);
    const isMutatingRef = React.useRef(client.isMutating() > 0);

    const [isLoading, setIsLoading] = React.useState<boolean>(
        isFetchingRef.current || isMutatingRef.current
    );

    React.useEffect(() => {
        mountedRef.current = true;

        const unsubscribeQueryCache = client.getQueryCache().subscribe(
            notifyManager.batchCalls(() => {
                if (mountedRef.current) {
                    isFetchingRef.current = client.isFetching() > 0;
                    setIsLoading(
                        isFetchingRef.current || isMutatingRef.current
                    );
                }
            })
        );

        const unsubscribeMutationCache = client.getMutationCache().subscribe(
            notifyManager.batchCalls(() => {
                if (mountedRef.current) {
                    isMutatingRef.current = client.isMutating() > 0;
                    setIsLoading(
                        isFetchingRef.current || isMutatingRef.current
                    );
                }
            })
        );

        return () => {
            mountedRef.current = false;
            unsubscribeQueryCache();
            unsubscribeMutationCache();
        };
    }, [client]);

    return isLoading;
};
```

I've reused the code from `useIsFetching`, which is clear enough to be derived. That'll do in my case, so I'll close this issue. 

Thanks for taking the time to take a look!
