### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by andrei9669** [tannerlinsley/react-query#3279]
### Describe the bug

When using select to prepare data and during that preparation, you do some recursive object nesting, react-query breaks because it tries to recursively clone it or something.

### Your minimal, reproducible example

https://codesandbox.io/s/inspiring-ramanujan-ziwv7?file=/src/index.js

### Steps to reproduce

1. open provided sandbox
2. open sandbox console.
3. see error in console

Alternatively

```
  const { isLoading, error, data, isFetching } = useQuery(
    "repoData",
    () =>
      fetch(
        "https://api.github.com/repos/tannerlinsley/react-query"
      ).then((res) => res.json()),
    {
      select: (data) => {
        const elOne = {};
        const elTwo = {};
        elOne.two = elTwo;
        elTwo.one = elOne;
        return elOne;
      }
    }
  );
```

### Expected behavior

I expected it to work and give no errors.

### How often does this bug happen?

Every time

### Platform

OS: windows
Browser: Brave

### react-query version

3.34.14

**Comment by TkDodo** [comment]
react-query performs `structural sharing` on results, which means it tries to keep as much of the original structure as possible. For that, it traverses the objects recursively.

If you use circular references like that, you'll likely have to turn it off via `structuralSharing: false`

[adapted, working codesandbox](https://codesandbox.io/s/dreamy-sunset-ewhd6)

but that also means that react-query cannot bail out informing observers if the selected slice hasn't changed.

**Comment by andrei9669** [comment]
> but that also means that react-query cannot bail out informing observers if the selected slice hasn't changed.

@TkDodo what do you mean by that, could you explain please?

**Comment by TkDodo** [comment]
see: https://tkdodo.eu/blog/react-query-render-optimizations#structural-sharing

**Comment by andrei9669** [comment]
thank you
