### ISSUE TITLE
Using React Devtools with useMutation can break state updates

### ISSUE THREAD

**Issue by martinkadlec0** [tannerlinsley/react-query#3303]
### Describe the bug

This is related to a bug reported here:
https://github.com/facebook/react/issues/19114

If you use React devtools (not react query devtools) with `useMutation` in your app, it can prevent `useState` updates in the same component from actually changing the state.

From what I can tell the issue is this part of `useMutation`:

```
if (!obsRef.current) {
  obsRef.current = new MutationObserver(queryClient, options);
} else {
  obsRef.current.setOptions(options);
}
```

In the linked react issue, you [can read](https://github.com/facebook/react/issues/19114#issuecomment-708438533) that the first part (assigning the mutation observer) is safe as it is lazy initiation and that is supported. However, the `else` condition is unsafe as it is a sideffect during render and is what is causing the issue.

Moving the `setOptions` line into `useEffect` fixes the issue, but I am not sure if that will not break other things like the `getCurrentResult` later in the render phase.

### Your minimal, reproducible example

https://codesandbox.io/s/egddqd

### Steps to reproduce

1. Open the linked sandbox
2. Click the "Open in new window" button beside the codesandbox browser url.
3. On the new page which is running the code, open the React Devtools Component tab.
4. Click on the App Component.
5. Refresh the page and click the "Mutate" button.
6. State is not updated.
7. Close devtools, refresh, click the button again, update works fine.

(Spamming the button works as there seem to be like a ~1s interval in which React Devtools keep the useState setter the same).

### Expected behavior

Using React devtools should not break state updates.

### How often does this bug happen?

Every time

### Platform

Windows 10
Chrome 98
React Devtools 4.23.0
React 17.0.2

### react-query version

3.34.15

**Comment by TkDodo** [comment]
Thanks for the report. I'm aware of the wrong usage of ref assignments during render. I've already refactored this for the [react 18 PR](https://github.com/tannerlinsley/react-query/pull/3064/files#diff-02c534d5d98d6a95998ae3e67f4fd6cb72965b5ffefe7765ea3902e9a16f787a)

**Comment by martinkadlec0** [comment]
I tried the PR branch and it seems to fix the issue! Thank you.
