### ISSUE TITLE
Inconsistency in onSuccess callback between being set in useMutation and mutate function

### ISSUE THREAD

**Issue by Ulian** [tannerlinsley/react-query#3340]
### Describe the bug

If you set `onSuccess` in `useMutation` options and return a promise it awaits its result before changing `isLoading` to `false`.
If you set `onSuccess` in `mutate` function options and return a promise it does not await its result and changes `isLoading` to `false` before the returned promise has finished.

### Your minimal, reproducible example

https://codesandbox.io/s/ecstatic-dew-7evm19?file=/src/index.js

### Steps to reproduce

1. Create two mutations, return a promise from one of them in the onSuccess callback

```
const { isLoading, mutate } = useMutation(
  "repoData",
  () =>
    fetch("https://run.mocky.io/v3/1bbd44cf-4dbb-455c-9954-77215ce7afd2", {
      method: "post"
    }),
  {
    onSuccess: () => new Promise(() => {})
  }
);

const { isLoading2, mutate: mutate2 } = useMutation("repoData2", () =>
  fetch("https://run.mocky.io/v3/1bbd44cf-4dbb-455c-9954-77215ce7afd2", {
    method: "post"
  })
);
```

2. Call the mutate function for both mutation. On the second mutation provied the same onSuccess first the previous mutation.

```
mutate();

mutate2(
  {},
  {
    onSuccess: () => new Promise(() => {})
  }
);
```

3. Check isLoading and isLoading2 values.

```
isLoading: true
isLoading2: false
```

### Expected behavior

onSuccess should affect mutation state the same way regardless if was set as an option in useMutation or in mutate function.

### How often does this bug happen?

Every time

### Platform

- OS: Windows & Mac
- Browser: Chrome
- Version: 98.0.4758.102

### react-query version

3.34.16

**Comment by TkDodo** [comment]
To my knowledge, this behaviour is intended. You can (theoretically) have multiple `observers` per mutation. The cache callbacks are only called once, while the observer callbacks (the one on .mutate) are called for every one of them, but only _if_ the observer is still active (=mounted) when the mutation finishes.

**Comment by Ulian** [comment]
Thanks for the reply! 

I understand. Do you consider it should be added this behavior to the useMutation docs?

While we are here...

> The mutation function you can call with variables to trigger the mutation and **optionally override options passed to useMutation**.

If I don't misunderstand this sentence if an onSucceess callback is provided on the mutate function, it should not call the callback provided in the useMutation hook? It should be overwritten.

[I did a test and both are called](https://codesandbox.io/s/silent-browser-z71jcx?file=/src/index.js). Could this be a bug, o may be the intended behavior as well?

**Comment by TkDodo** [comment]
> I understand. Do you consider it should be added this behavior to the useMutation docs?

Please feel free to update the docs if something is not clear :)

> [I did a test and both are called](https://codesandbox.io/s/silent-browser-z71jcx?file=/src/index.js). Could this be a bug, o may be the intended behavior as well?

That is also on purpose. It's [documented here](https://react-query.tanstack.com/guides/mutations#mutation-side-effects) under "trigger additional callbacks"
