### ISSUE TITLE
Typo on https://learn.tanstack.com/

### ISSUE THREAD

**Issue by josephmarkus** [tannerlinsley/react-query#3341]
### Describe the bug

Typo on https://learn.tanstack.com/

The sentence reads: "While v3 introduced a few breaking changes to API, these changes have very little affect on the core principles and concepts you will learn in this course."

The word "affect" should be "effect"

### Your minimal, reproducible example

https://learn.tanstack.com/

### Steps to reproduce

1. Go to https://learn.tanstack.com/

### Expected behavior

No typo

### Platform

n/a

### react-query version

n/a

**Comment by TkDodo** [comment]
thank you for noticing, but this is not something we can fix from within the react-query repository.
