### ISSUE TITLE
Shared cache between browser tabs?

### ISSUE THREAD

**Issue by n1ghtmare** [tannerlinsley/react-query#336]
I'm sorry for the (most probably) noob question, but I wasn't sure, so here I am.

Say that I have my app open in 2 browser tabs.  In one of the tabs I do a mutation and I optimistically update the value in the query cache, like in the example found in the documentation:

```js
useMutation(updateTodo, {
  // When mutate is called:
  onMutate: (newTodo) => {
    // Snapshot the previous value
    const previousTodos = queryCache.getQueryData('todos')

    // Optimistically update to the new value
    queryCache.setQueryData('todos', old => [...old, newTodo])

    // Return the snapshotted value
    return () => queryCache.setQueryData('todos', previousTodos)
  },
  // If the mutation fails, use the value returned from onMutate to roll back
  onError: (err, newTodo, rollback) => rollback
  // Always refetch after error or success:
  onSettled: () => {
    queryCache.refetchQueries('todos')
  }
})
```

Currently when I switch tabs my data will synchronize and re-fetch once I focus on a tab/window, but there is a slight delay since we're waiting for the refetch to be done.

Is there a way to read the data from cache first and have the refetch be done in the background. So that when I switch tabs the new data will be immediately available, before the refetch is complete. I'm not sure if the cache is shared between tabs, or if I have a misconception of how things work exactly.

I hope my question makes sense, and let me know if you need clarifications.

P.S. - I love this library, good job everyone.

**Comment by kamranayub** [comment]
AFAIK the cache is per tab because it's in-memory, so it is sandboxed to the tab by Chrome.

My team may be implementing a mechanism to allow "persistent" caching through local storage but we will likely build it on top of react-query. If we do and it's in a good state to share, I'll be happy to contribute it or as a separate "add-on" to react-query.

The way you'd likely go about this is by wrapping the `useQuery` hooks and adding callbacks to store the successful results in local storage and then in the `initialData` callback, attempt to read from the cache. Perhaps you would also need to force the query into manual mode, then write an effect on mount that would try to check the persisted cache and call `refetch` if it's not available (falling back to normal operation). This is similar to how we are also building in SSR hydration to `useQuery` as well.

**Comment by universse** [comment]
Maybe you can give this a try https://developer.mozilla.org/en-US/docs/Web/API/Window/storage_event

**Comment by n1ghtmare** [comment]
I think I had a misconception that the cache is for some reason already in local storage, I read a bit more and I see that it's in memory (and it makes sense).

Thanks for all the help folks.

**Comment by tannerlinsley** [comment]
@kamranayub I would love to see your implementation before you get to deep. Maybe I could offer a first-class integration point for this?

**Comment by olup** [comment]
Any news about an in-storage persistence? I Am considering using react query for a react native app with offline abilities, and will build some basic system to do so on top of RQ. I am interested in any prior attempt.

**Comment by kamranayub** [comment]
At the moment nothing formal. At work, we use IndexedDB / local storage but it happens within the queryFn. 

I also made a helper that can look at the cache-control header of a response and we can then set the query stale time dynamically to match the max-age value. Those are the only two approaches we use at the moment.

**Comment by nitzansan** [comment]
We are also looking to implement some localStorage syncing mechanism for react-query.
It makes a lot of sense when you take UX into consideration.

Consider the following enhanced Todo application.
The main page will have a list of todo titles. When pressing on a todo item, the todo will open in a modal with all of the todo details.
UX-wise, if this todo is fetched from the cache and no changes were made, then there are no problems.
If the todo is fetched from the cache and some changes were made from the background fetch, then a message appears to the user: "Changes were made to this todo. Press here to reload the todo".

Now imagine a user opening a todo in a new tab and editing it.
When he goes back to his previous tab and views that todo he will get this annoying message, that warns him of an interaction that he himself did.
This entire inconvenience could have been avoided if the cache was shared between the tabs.

I know that it's possible to implement the localStorage sync manually by wrapping/decorating the different hooks, but I believe that this kind of behavior makes sense to be part of the package itself and configurable.

WDYT? @tannerlinsley

**Comment by Gugols** [comment]
I would just add to this discussion, that indexddb would have benefits to offline capability compared to local storage. Local storage can't be accessable from browser's service worker which can be a serious drawback in many scenarious.
For example, imagine a case where you're trying to make a post request (mutation as per this library I guess) to a server and the connection is poor or non-existant. You would want to persist that data indefinitely but still access it via a service worker.

Currently I'm in process of refactoring my app to use react-query and this could be a cool feature.
Right now I've been using Dexie.js as wrapper for indexddb and caching received data as well as failed post requests in a scenario when there is a poor network connection (a must for my app).

**Comment by lveillard** [comment]
I'm facing this but in the same tab. Lets say you have a page P1, that pops a modal M1 (headlessui dialog, so it's a portal) and this a modal M2

Then I optimistically modify data in the modal M2. 
If I have the same component using the data from the cache in the M1 and in the P1, M1 gets updated, but P1 does not. 

Sharing in case it helps :)

![chrome_2VViCudeVV](https://user-images.githubusercontent.com/29461076/204109549-75afb650-297e-4b31-b014-c65c9bdae364.gif)
 does not!

**Comment by xmsz-stu** [comment]
any update?

**Comment by stianjensen** [comment]
> any update?

This exists now, for persisting to local storage in general:
https://tanstack.com/query/latest/docs/framework/react/plugins/createSyncStoragePersister

And this exists (experimental), to help sync data between open tabs:
https://tanstack.com/query/latest/docs/framework/react/plugins/broadcastQueryClient
