### ISSUE TITLE
prod build used in dev environments

### ISSUE THREAD

**Issue by eps1lon** [tannerlinsley/react-query#337]
If one imports from `react-query` via `import` webpack will use the `module` field which points to `dist/react-query.min.mjs` which uses the minified bundle.

This isn't an issue for source inspection since source maps are published but for react-devtools it means that components and hooks will have a minified names:

`M` is `ReactQueryConfigProvider`:
![Screenshot from 2020-04-09 15-58-07](https://user-images.githubusercontent.com/12292047/78903169-0c0d8480-7a7b-11ea-823d-1b5388ebf396.png)

`$` is `usePaginatedQuery`:
![Screenshot from 2020-04-09 15-58-29](https://user-images.githubusercontent.com/12292047/78903180-0f087500-7a7b-11ea-95cb-d6f5a2a1b3ac.png)

**Comment by tannerlinsley** [comment]
Package.json.module does not point to the minified file: 
<img width="284" alt="Screen Shot 2020-04-12 at 11 22 40 PM" src="https://user-images.githubusercontent.com/5580297/79094368-83aa1080-7d14-11ea-9643-48837ac79fd2.png">

**Comment by eps1lon** [comment]
@tannerlinsley In ^1.2.0, yes. [You seem to have changed this recently](https://unpkg.com/react-query@1.1.0/package.json), thanks.
