### ISSUE TITLE
"OnSuccess" of a useQuery get triggered even if it has the option "enabled" : false

### ISSUE THREAD

**Issue by nawfalhaddi** [tannerlinsley/react-query#3409]
### Describe the bug

the problem if we are using two useQuery with the same key , and one of them is enabled and the other one is not. the effect functions get triggered for both of them. 

### Your minimal, reproducible example

https://codesandbox.io/s/vibrant-mirzakhani-0tf2b1

### Steps to reproduce

1- Check the console in the link above, and you will notice that "onSuccess" get triggered even if useQuery  has enabled equals to false 

### Expected behavior

the onSuccess  and other effect functions should get triggered only when enabled is true 

### How often does this bug happen?

Every time

### Platform

- web
- react native

### react-query version

3.34.16

**Comment by TkDodo** [comment]
> the onSuccess and other effect functions should get triggered only when enabled is true

hm, why do you think so? when the fetch succeeds, you'll also get `data` even if one useQuery is "disabled". "disabled" just means this query won't fetch data on its own, but if data is put by other means into the cache, it will be available, which means that for a successful fetch, `onSuccess` will be called, and for errors, `onError` will be called.

what are you doing in `onSuccess` that would require a different behavior?

**Comment by jarekucinski** [comment]
I think the problem is not with onSuccess here, but that 'enabled' property seems to be ignored and fetch data despite it is set to false, which is not what it stated in documentation:
https://react-query.tanstack.com/guides/disabling-queries

**Comment by nawfalhaddi** [comment]
I just saw your comments, Thank you @TkDodo  for the clarification 🙏

**Comment by LouiseEH** [comment]
How is it fixed?
I have a GET and a PUT and I set `queryKey: ['get']` and `queryKey: ['put']` respectively, but I still have the same issue of onSuccess being called for both even though the second has `enabled: false`
