### ISSUE TITLE
cancelMutations does not seem to work as expected

### ISSUE THREAD

**Issue by abacaj** [tannerlinsley/react-query#3417]
### Describe the bug

Could not find any documentation regarding: `cancelMutations` but I assumed it worked similar to `cancelQueries` in that there is a signal passed to the mutation.

It does not seem to be the case, and cancelMutations does not cancel any previous pending mutations.
Is this the expected behavior?

Thank you!

### Your minimal, reproducible example

N/A

### Steps to reproduce

Call a mutation twice, one after the other and in onMutate call cancel (should be cancelling any previous pending).

### Expected behavior

Expect to see pending mutations cancelled

### How often does this bug happen?

Every time

### Platform

Chrome 99.0.4844.51

### react-query version

3.33.5

**Comment by TkDodo** [comment]
The function will be removed in v4. You can't really cancel mutations. See: https://github.com/tannerlinsley/react-query/discussions/1551#discussioncomment-1140721

**Comment by abacaj** [comment]
> The function will be removed in v4. You can't really cancel mutations. See: [#1551 (comment)](https://github.com/tannerlinsley/react-query/discussions/1551#discussioncomment-1140721)

Figured as much makes sense, side effect queries can't really guarantee the cancel.
