### ISSUE TITLE
[Docs - codesandbox] - Suspense Example is broken

### ISSUE THREAD

**Issue by Avivhdr** [tannerlinsley/react-query#3453]
### Describe the bug

The [Suspense Example](https://codesandbox.io/s/github/tannerlinsley/react-query/tree/master/examples/suspense?file=/src/components/Spinner.js) Codesandbox in the  [suspense](https://react-query.tanstack.com/guides/suspense) page  of the documentation is not working:
```
ModuleNotFoundError
Could not find module in path: 'react/jsx-runtime' relative to '/src/components/Spinner.js'
```

### Your minimal, reproducible example

Codesandbox

### Steps to reproduce

1. Go to https://codesandbox.io/s/github/tannerlinsley/react-query/tree/master/examples/suspense?file=/package.json.
2. See broken sandbox.

### Expected behavior

Code should run.

### Platform

Codesandbox

### react-query version

3.5.0

**Comment by pkellner** [comment]
Similar issues with vercel swr.

**Comment by Avivhdr** [comment]
Hey @TkDodo, the sandbox is still broken fyi.

**Comment by TkDodo** [comment]
I have fixed the examples for v4, but the docs still pick up the version from `master`. I've just updated all dependencies, hope that makes it work.

For now, what you can do is:
- open the sandbox
- fork it
- update react from experimental to v18
- sadly, the api for `startTransition` has changed, so you need to switch the order of the return values.

Anyways, I've just done that, so here is a working sandbox. Sorry for the troubles:

https://codesandbox.io/s/white-pine-xncu70?file=/src/index.js

**Comment by Avivhdr** [comment]
Thank you, Dominik!
