### ISSUE TITLE
Option to don't pass the queryKey as an argument to queryFn

### ISSUE THREAD

**Issue by michaeljota** [tannerlinsley/react-query#346]
Hi there. Thanks for this amazing library. Really easy to use. I'm currently in my way to implement this in a large code base, and I don't want to refactor all our services functions. Is there an option to don't pass the ID part of the queryKey to the function?

```ts
const { data = [], refetch, status } = useQuery({
    queryKey: ["IDon'tWantThis", ...ActualParamsInTheServiceFn],
    queryFn: service.getAll
  });
```

Do you this this is possible?

**Comment by cherniavskii** [comment]
Yes!
https://github.com/tannerlinsley/react-query/issues/145#issuecomment-590377800

**Comment by michaeljota** [comment]
Can this be configured globally?

**Comment by cherniavskii** [comment]
Yes, see https://github.com/tannerlinsley/react-query#reactqueryconfigprovider

**Comment by michaeljota** [comment]
Thanks! :)

**Comment by michaeljota** [comment]
I'm sorry to bother you, I know maybe this doesn't belong here, but I'm using Typescript, and I can't find a type safe way for this. Do you have any experience or suggestions?

**Comment by cherniavskii** [comment]
I don't use Typescript, but maybe you'll find this discussion useful - https://github.com/tannerlinsley/react-query/discussions/242
