### ISSUE TITLE
fetchQuery doesn't handle errors

### ISSUE THREAD

**Issue by federico-moretti** [tannerlinsley/react-query#3469]
### Describe the bug

When using `fetchQuery` on the server side, if the fetch function throws an error, it will be logged on the terminal and not caught by the external try catch block wrapping the `fetchQuery`.

I avoid this problem using `setQueryData` and fetching before, but I still think it's an unexpected behaviour.

### Your minimal, reproducible example

https://codesandbox.io/s/fetch-query-error-83fcch?file=/pages/post/%5Bid%5D.js

### Steps to reproduce

1. Open with the following url: `/post/120`
2. You will see the error in the server terminal

### Expected behavior

As there is a try catch block outside the `fetchQuery`, I expected it to catch the error.

### Platform

- Nextjs:  v12.1.0
- Nodejs: v16.10.0

### react-query version

v3.34.19

**Comment by TkDodo** [comment]
I guess you are talking about this error printed to the console:

```
Error: No result found!
    at fetchPost (webpack-internal:///./hooks/usePost/index.js:20:11)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

In v3, react-query logs errors resulting from fetches to the console. We're providing a [setLogger](https://react-query.tanstack.com/reference/setLogger) method where you can overrides this behaviour:

```
import { setLogger } from 'react-query'

setLogger({
  log: console.log,
  warn: console.warn,
  error: () => {},
})
```

working fork of your sandbox: https://codesandbox.io/s/fetch-query-error-forked-e1lydj?file=/pages/index.js

see also:
- https://tkdodo.eu/blog/testing-react-query#silence-the-error-console

---

please note that in v4 (currently in beta), things are a bit differently:
- errors are only logged in development mode, not in production. That is similar to what react does with dev-only warnings, so you don't need to turn them off with `setLogger` anymore.
- `setLogger` doesn't exist anymore. Instead, you can pass a custom logger to the `QueryClient` as a prop.

**Comment by federico-moretti** [comment]
Oh I see, thank you for the explanation! 
I was having problem with that log because Sentry somehow logged that error and was displayed differently than other tracked errors.

Thank you for the heads up, I'll leave it with `setQueryData` for now and maybe change it back once we migrate to v4.
