### ISSUE TITLE
isPaused not described in API docs

### ISSUE THREAD

**Issue by jprosevear** [tannerlinsley/react-query#3473]
### Describe the bug

At https://react-query.tanstack.com/reference/useMutation, isPaused is listed as a return value but there is no description of it.

### Your minimal, reproducible example

https://react-query.tanstack.com/reference/useMutation

### Steps to reproduce

Vistt https://react-query.tanstack.com/reference/useMutation

### Expected behavior

https://react-query.tanstack.com/reference/useMutation describes isPaused

### How often does this bug happen?

Every time

### Platform

All

### react-query version

3.34.19

**Comment by TkDodo** [comment]
lots of things have changed / will change around offline support in v4.

have a look at the beta docs, where it is described: https://react-query-beta.tanstack.com/reference/useMutation
