### ISSUE TITLE
useQuery, Argument of type 'string' is not assignable to parameter of type 'QueryKey'

### ISSUE THREAD

**Issue by wigsnes** [tannerlinsley/react-query#3500]
### Describe the bug

I assume this is a known bug, but thought I would report it just in case.

Having trouble in the beta v2 and 3, where QueryKey can not be of type string.

`Argument of type 'string' is not assignable to parameter of type 'QueryKey'`

### Your minimal, reproducible example

https://codesandbox.io/s/nervous-tree-lccbeg?file=/src/App.tsx

### Steps to reproduce

Go to the sandbox, and see the error. Data is also undefined, not sure this is also a bug.

### Expected behavior

Return User, and show Hello Fredrik.

### How often does this bug happen?

Every time

### Platform

Windows, sandbox
in vs-code
4.0.0-beta.2, and 3 tested

### react-query version

4.0.0-beta.2, and 3

### TypeScript version

4.4.2

**Comment by TkDodo** [comment]
that is one of the breaking changes in v4 - keys must always be an array. see:

https://react-query-beta.tanstack.com/guides/migrating-to-react-query-4#query-keys-and-mutation-keys-need-to-be-an-array

we also print a warning to the console:

![Screenshot 2022-04-13 at 12 32 01](https://user-images.githubusercontent.com/1021430/163159558-6f331a62-5840-4bf1-82fc-9e055975f11b.png)

**Comment by wigsnes** [comment]
Thanks, but using typescript you can't run the application because of the error, and won't get a console error telling you to use array. Should be better typed IMO.

**Comment by TkDodo** [comment]
> Should be better typed IMO.

what do you mean, better typed? The type for a key that you pass in must `extend QueryKey`, which is now:

https://github.com/tannerlinsley/react-query/blob/ba782560a715705942fd9137bfb284ac5f0445d9/src/core/types.ts#L9

and on v3, it was:

https://github.com/tannerlinsley/react-query/blob/ec4ef9b7533c3bf0f7560fc5c811da337a0972c4/src/core/types.ts#L8

so we've removed `string` from the allowed types, and that's the error you get from TypeScript:

```
Argument of type 'string' is not assignable to parameter of type 'QueryKey'
```

**Comment by wigsnes** [comment]
I feel like it was not clear that it was an array with QueryKey,
should be QueryKeys or QueryKey[] maybe.

The error `Argument of type 'string' is not assignable to parameter of type 'QueryKey'.` did not give me any indication that it should be an array, we have always used strings in our team.

It is probably just a get used to it, was trying to fix the bug with react 18 types, and had to upgrade to v4 so did not look at the breaking changes. :)
