### ISSUE TITLE
How to refetch query with params

### ISSUE THREAD

**Issue by skrivitsky** [tannerlinsley/react-query#351]
For example I created a query 
`  const {
    data = {
      result: [],
    },
  } = useQuery('data_sources', getDataSources);`

This data used for select component and I wonna refetch it with `{ search: value }` param.
Previously we had a `variables` params inside `refetch`, now it's removed.

**Comment by 1saf** [comment]
I was wondering this as well

**Comment by tannerlinsley** [comment]
Recommended: Turn your variables into a permanent query key part and just update them with state or props

```js
useQuery(['data_sources', { variables }], getDataSources)
// or
useQuery(['data_sources', variables], getDataSources)
```
