### ISSUE TITLE
`react-query/devtools`'s `module` entry points to a CJS file

### ISSUE THREAD

**Issue by sodatea** [tannerlinsley/react-query#3513]
### Describe the bug

Essentially reposting https://github.com/tannerlinsley/react-query/issues/3505 here.
Though Vite reverted that change, I believe it is a bug in `react-query`.

The [`module` field of `react-query/devtools`](https://unpkg.com/browse/react-query@3.34.19/devtools/package.json) points to a [CJS file](https://unpkg.com/browse/react-query@3.34.19/devtools/index.js) that reexports from a subfolder containing nothing but a `package.json`, and it expects the reexport resolves to the `module` field of that subfolder.

It violates the convention that [`module` field should contain ESM syntax](https://github.com/stereobooster/package.json#module).

---

To provide different exports for different environments in the ES module system, maybe the `exports` field can help here: https://nodejs.org/api/packages.html#community-conditions-definitions

### Your minimal, reproducible example

https://github.com/akharkhonov/vite-react-query

### Steps to reproduce

1. Install dependencies `yarn --frozen-lockfile`
2. Run dev mode `yarn dev`
3. Open devttools and see errors

### Expected behavior

No errors.

### How often does this bug happen?

Every time

### Platform

- OS: macOS
- Browser: Chrome
- Version: Version 100.0.4896.88 (Official Build) (arm64)

### react-query version

3.34.19

### TypeScript version

4.6.3

**Comment by TkDodo** [comment]
I would be very grateful if you could help with fixing this. My knowledge about modules and bundling is quite limited to be honest
