### ISSUE TITLE
`QueryClientProvider` children type error 

### ISSUE THREAD

**Issue by Manokii** [tannerlinsley/react-query#3519]
### Describe the bug

Adding children to `QueryClientProvider` gives a type warning

```
Type '{ children: Element; client: QueryClient; }' is not assignable to type 'IntrinsicAttributes & QueryClientProviderProps'.
  Property 'children' does not exist on type 'IntrinsicAttributes & QueryClientProviderProps'.
```

### Your minimal, reproducible example

https://stackblitz.com/edit/vitejs-vite-txwifq?file=src%2FApp.tsx&terminal=dev

### Steps to reproduce

1. Create a normal react app
2. Wrap App content 
```ts
const App = () => {
  return <QueryClientProvider client={queryClient}>
    //... content here
  </QueryClientProvider/>
}
```

### Expected behavior

It's not supposed to have an type error. Child component required for the QueryClientProvider in order to work

### How often does this bug happen?

Every time

### Screenshots or Videos

![Uploading image.png…]()

### Platform

- OS: Linux - Ubuntu latest

### react-query version

v3.30.20

### TypeScript version

v4.6.3

**Comment by TkDodo** [comment]
Duplicate: https://github.com/tannerlinsley/react-query/issues/3476
