### ISSUE TITLE
isFetchingMore behaving oddly

### ISSUE THREAD

**Issue by mattrothenberg** [tannerlinsley/react-query#352]
I've run into an issue with the latest version of react-query where `isFetchingMore` is inconsistently true/false depending on how the `fetchMore` function is invoked.

Specifically, I have an infinitely-scrolling activity feed (which uses `react-waypoint` to fire `fetchMore` when a user reaches the bottom of the feed). Oddly enough, whenever this waypoint is triggered, the `isFetchingMore` value **never** gets set to true, preventing me from rendering a helpful loading indicator to inform the user that more data is being requested. The data does eventually arrive, though, so there doesn't seem to be any problem with the underlying query logic.

Upon closer inspection, I was able to replicate this issue without using `react-waypoint`.

https://codesandbox.io/s/polished-dust-7fnq3?file=/src/App.js.

Note how when you press the button at the bottom of the feed, `isFetchingMore` reliably gets set to true/false. But also note that the timeout inside of the component (which triggers `fetchMore` after an arbitrary delay) _never_ results in `isFetchingMore` being set to true.

I hope I'm missing something glaringly obvious here! If not, I'm curious what might be causing this discrepancy.

**Comment by tannerlinsley** [comment]
Thanks for making this issue. I found the bug and have a fix. I'll try and get it out asap.

**Comment by mattrothenberg** [comment]
Thanks @tannerlinsley – really appreciate your hard work on this library!

**Comment by tannerlinsley** [comment]
Fixed in latest release!
