### ISSUE TITLE
Devtools visible on print

### ISSUE THREAD

**Issue by Svish** [tannerlinsley/react-query#3536]
### Describe the bug

The React Query Devtools button is displayed on every single page when printing.

### Your minimal, reproducible example

https://codesandbox.io/s/github/tannerlinsley/react-query/tree/master/examples/basic

### Steps to reproduce

1. Open any site that has React Query Devtools active
   * E.g. open the [basic example codesandbox](https://codesandbox.io/s/github/tannerlinsley/react-query/tree/master/examples/basic), and view the sandbox in a new window
3. Hit print in browser
4. See the Devtools flower in the bottom left corner of every single page

### Expected behavior

The Devtools-button should not be visible when printing.

### How often does this bug happen?

Every time

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/142162/164218105-0a359650-cf54-4e9b-9ffb-ac4d33df4ee8.png)

### Platform

N/A

### react-query version

v3.35.0

**Comment by Svish** [comment]
My intention was to submit a fix for this myself, but I have _no idea_ how the styled components stuff used in this project works... so... created an issue instead... should be pretty easy to solve for someone who does know how it works.

Just add this somehow to the button and devtools.

```css
@media print {
  display: none;
}
```

**Comment by Svish** [comment]
Ah, that explains why I couldn't figure out of the styled components stuff, haha.

So, I guess this is the "fix" then, unless it would be possible to inject a small `<style>` tag to hide the devtools on print, or something like that.

```jsx
        <ReactQueryDevtools
          containerElement="div"
          toggleButtonProps={{
            className: 'noPrint',
          }}
          panelProps={{
            className: 'noPrint',
          }}
          closeButtonProps={{
            className: 'noPrint',
          }}
        />
```

**Comment by TkDodo** [comment]
we could do that, because we already inject other styles (which has csp issues, so I'd rather not add more to this). This is easily fixable in user-land like described.

**Comment by rbalet** [comment]
Hey, @TkDodo 

Any idea on how to hide the latest `TanStackDevtools` one ?
