### ISSUE TITLE
React Native app crashes when storage gets full when using `asyncStoragePersister` 

### ISSUE THREAD

**Issue by anant-nft** [tannerlinsley/react-query#3537]
### Describe the bug

The `webStoragePerister` and `asyncStoragePersister` have a bit different api and have different default behaviours against errors. The `webStoragePerister` catches errors internally and tries to remove old cache entries until persistence works. But `asyncStoragePersister` does nothing like that and when storage gets full, app starts crashing. 

See #3527

### Your minimal, reproducible example

N/A

### Steps to reproduce

1. Use `asyncStoragePersister` in a react native app.
2. Use until storage gets full and we start getting storage errors.
3. App starts crashing.

### Expected behavior

Both `webStoragePerister` and `asyncStoragePersister` should have roughly the same api with the same default behaviour which is deleting old cache when storage is full.

### How often does this bug happen?

Every time

### Platform

- OS: iOS, Android

### react-query version

v3.24.3

### TypeScript version

v4.3.5

**Comment by anant-nft** [comment]
@TkDodo Should I create a PR ?

**Comment by TkDodo** [comment]
we already have an issue that tries to tackle to streamline the api, but for other reasons: the behaviour done by the webstoragepersister is not very performant, see:
- https://github.com/tannerlinsley/react-query/issues/3034

i have some proposals in that issue, and I would love your feedback. If we can settle on a streamlined api for both peristers, I would gladly accept a PR (for v4, which is currently in beta, where we have done quite some changes already).

I'll close this issue, but lets please keep discussing in the other issue :)
