### ISSUE TITLE
v4 introduces dependency on react in core package

### ISSUE THREAD

**Issue by DamianOsipiuk** [tannerlinsley/react-query#3542]
### Describe the bug

In the beta branch i have noticed that [hydration.ts](https://github.com/tannerlinsley/react-query/blob/beta/src/core/hydration.ts#L1) contains reference to `react` types.
This will introduce transitive dependency on `react` for `vue` package.

### Your minimal, reproducible example

N/A

### Steps to reproduce

N/A

### Expected behavior

I think we need to remove `react` reference from `core` package.
Maybe introducing some kind of overload in `react` sub-package would be a solution?

### Platform

N/A

### react-query version

v4

### Additional context

https://github.com/tannerlinsley/react-query/blob/beta/src/core/hydration.ts#L1
https://github.com/tannerlinsley/react-query/blob/beta/src/reactjs/types.ts#L12
https://github.com/tannerlinsley/react-query/blob/beta/src/reactjs/types.ts#L18

**Comment by TkDodo** [comment]
Thanks for spotting that, I think it's a mistake. The types in the core should stay the same as in v3, and the types we use in the react package, where we need the hydration (e.g. `Hydrate.tsx`) should just extend the base one and add the react context if needed.

would you like to fix that for us maybe?

**Comment by TkDodo** [comment]
I think I'm gonna setup [eslint import zones](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-restricted-paths.md) or so to prevent this mistake in the future 👍

**Comment by DamianOsipiuk** [comment]
Yeah, i will try to fix it when i will have some free time.
