### ISSUE TITLE
Suspense: onSuccess is called multiple times

### ISSUE THREAD

**Issue by anilanar** [tannerlinsley/react-query#3560]
_**No, this is not about using useQuery with the same key in multiple components. This is something else, related to Suspense.**_

### Describe the bug

In the reproduction, the bug happens only on the time `Toggle` is clicked.
When you click on `Toggle`, it will sometimes trigger `onSuccess` once, sometimes twice, sometimes 3 times but mostly 2 or 3 times.

### Your minimal, reproducible example

~https://codesandbox.io/s/async-firefly-jrq4hp?file=/src/App.js~
https://codesandbox.io/s/sleepy-fermi-vrl03r?file=/src/App.js

### Steps to reproduce

1. Expand codesandbox's console if it's collapsed so that you can see how many times `onSuccess` is called.
2. Click on `Toggle`.

### Expected behavior

`SUCCESS` is printed only once when `Toggle` is clicked.

### How often does this bug happen?

Every time

### Platform

- OS: Linux, MacOS
- Browser: Chrome, Firefox

### react-query version

v3.38.0

**Comment by TkDodo** [comment]
I'm pretty sure what you are seeing is merely a refetchOnWinowFocus happening at the same time as you click the button. try setting `staleTime: Infinity`, or turn that flag off, or click somewhere in the white area to trigger the window focus, then click the toggle button. I can't see anything weird.

**Comment by anilanar** [comment]
@TkDodo You are right, I was kind of excited for finding a minimal reproduction but obviously I failed.

I'll look for another minimal reproduction, we are having this bug in our product; not that onSuccess calling multiple times matters, but it actually does a heavy computation and runs more than 10 times, freezing the app.

**Comment by anilanar** [comment]
@TkDodo 

Maybe this is better? https://codesandbox.io/s/sleepy-fermi-vrl03r?file=/src/App.js

**Comment by TkDodo** [comment]
you're examples are a bit wild 😅 .

I narrowed it down a bit:
- removed the side-effect from `onSuccess`
- added more logging

the root cause seems to be the interval that fires every 50ms (is that on purpose?). I've also added logging to the suspense fallback itself, so we can see that the suspense fallback is also rendered a bunch of times. From that, I would think that:

- key changes, we throw to suspense boundary
- effect fires, re-renders parent
- react render top-down
- useQuery sees we have no data yet, throws the promise again
- effect fires, re-renders parent

or something along those lines. it's pretty wild, but what is this interval doing? can you maybe describe the problem you're trying to solve with such code?

**Comment by anilanar** [comment]
@TkDodo The interval is on purpose. In our product, there are other processes that cause rerenders to the parent component, but I don't know when those rerenders happen, so the interval is my way of introducing random rerenders from external sources.

**Comment by anilanar** [comment]
@TkDodo It actually doesn't seem to be that crazy.

**My hypothesis based on gut feelings:**

From my experiments with suspense, I can see that if a component throws a promise during render, all hooks of that component (initial values of useRef/useState/useReducer, cached values of useMemo/useCallback) are discarded.

So you cannot use suspended component to store state, because if it rerenders while being suspended, it will behave as if it's freshly mounted.

Now in the case of `onSuccess`:

- I assume that due to how it's implemented in react-query
- And because every rerender of a suspended component counts as a separate component instance
- And because the only way for react-query to distinguish component instances from each other is their lifecycle
- And because suspended components are discarded and recreated each rerender

Then, `onSuccess`, and any other callback/hook that is called per component instance will be called multiple times while a component is suspended and it's rerendered.
