### ISSUE TITLE
onSuccess is not triggered the first time around in suspense mode

### ISSUE THREAD

**Issue by n1ghtmare** [tannerlinsley/react-query#357]
Not sure if this is a bug, but when suspense is turned on, the first call to the `onSuccess` callback for `useQuery` is not being triggered, it seems that it's only being called on re-fetching.

You can reproduce by using the suspense codesanbox that's included in the examples and do something like:

```js
const { data, isFetching } = useQuery("projects", fetchProjects, {
    onSuccess: () => console.log("Testing")
});
```

You'll notice in the console that the `onSuccess` callback will be called only after you toggle "Show/Hide" projects more than once (but not the first time), or if you re-focus on the window.

[Here](https://codesandbox.io/s/hungry-cannon-vp1ld?file=/src/components/Projects.js) is a codesanbox fork if it helps.

**Comment by tannerlinsley** [comment]
Thanks for the info. I'll find a fix.

**Comment by reiff12** [comment]
Hey @tannerlinsley, I'd love to get involved in the project. This something I could help out with?

**Comment by cherniavskii** [comment]
@reiff12 Sure, you're welcome to submit a Pull Request for this or any other issue! :)
