### ISSUE TITLE
react-query trying to update state on unmounted components in beta.7

### ISSUE THREAD

**Issue by mntnoe** [tannerlinsley/react-query#3586]
### Describe the bug

When trying out the latest beta (beta.7 as of writing), I encounter a lot of warnings like these in the console:

```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
QueryRow@http://localhost:3000/[redacted]
div
div
div
styled2/<@http://localhost:3000/[redacted]
ThemeProvider2@http://localhost:3000/[redacted]
ReactQueryDevtoolsPanel2@http://localhost:3000/[redacted]
ThemeProvider2@http://localhost:3000/[redacted]
aside
ReactQueryDevtools@http://localhost:3000/[redacted]
[redacted]
Site@http://localhost:3000/[redacted]
    overrideMethod moz-extension://92e08e07-1e6b-9f4c-8a59-07f9b1cdcf22/build/react_devtools_backend.js:3973
    printWarning http://localhost:3000/[redacted]
    error http://localhost:3000/[redacted]
    warnAboutUpdateOnUnmountedFiberInDEV http://localhost:3000/[redacted]
    scheduleUpdateOnFiber http://localhost:3000/[redacted]
    dispatchAction http://localhost:3000/[redacted]
    handleStoreChange http://localhost:3000/[redacted]
    batchCalls http://localhost:3000/[redacted]
    notifyFn http://localhost:3000/[redacted]
    flush http://localhost:3000/[redacted]
    flush http://localhost:3000/[redacted]
    batchedUpdates$1 http://localhost:3000/[redacted]
    flush http://localhost:3000/[redacted]
    (Async: promise callback)
    scheduleMicrotask http://localhost:3000/[redacted]
    flush http://localhost:3000/[redacted]
    batch http://localhost:3000/[redacted]
    invalidateQueries http://localhost:3000/[redacted]
```

The above warning is generated after the devtools was remounted as a result of `QueryClient.invalidateQueries`. I solved this particular problem by moving the devtools up in the component hierarchy, but it serves as a good example of what happens, and may be easier to reproduce for you.

I encounter similar warnings all around our application, but they occur non-deterministically, and may be due to our setup. Note that these warnings do not occur at all for us in react-query 3.38.1. Also note that no functionality seems to be broken because of this, as far as I can tell.

### Your minimal, reproducible example

https://codesandbox.io/s/cool-sea-btnzkx?file=/src/App.js

### Steps to reproduce

I tried to reproduce the issue in the codesandbox above, but were unable to do so, unfortunately. At least you now have a heads up that there might be an issue in the beta wrt. effects on unmounted components.

### Expected behavior

It is important for us that there's as few warnings in the console as possible, in order not to miss other warnings.

### Platform

- OS: MacOS and Ubuntu
- Browser: Firefox
- Version: 99.0.1

### react-query version

4.0.0-beta.7

**Comment by TkDodo** [comment]
The warning was removed in react 18 because it was a false warning in most of the cases. See: https://github.com/reactwg/react-18/discussions/82

in v3, we had the "guards" with a ref, but removed them in v4 because as stated, the workaround is worse than the actual issue

**Comment by mntnoe** [comment]
I see, interesting. I guess we'll start migrating towards react 18 then (we have many useEffect hooks not designed to be remounted). Anyways, thank you for the response!
