### ISSUE TITLE
Error is not getting cought when coming back to the window

### ISSUE THREAD

**Issue by amitripshtos** [tannerlinsley/react-query#36]
Hey, great library!
I noticed that when I useQuery and it fails, go out of the page and then go back - the error will not be caught in useQuery but be raised to the UI.

How to test?
1. Use useQuery to a endpoint that does not work (using async await)
2. Let it fail one time, go out of the tab and go back in.
3. You should see the Ui crashes.

Thanks!

**Comment by tannerlinsley** [comment]
Thanks for reporting! I’ll have this fixed ASAP

Tanner Linsley

**Comment by amitripshtos** [comment]
I want to fix that in order to learn more about react-query, mind if you lead me on which part of the code should I look? Thanks!

**Comment by tannerlinsley** [comment]
Yes I can! But first, could you make a codesandbox that demonstrates the bug so we can work from there?

**Comment by amitripshtos** [comment]
Well, I'm trying to mimic the issue using codesandbox, however without any success.
I'm starting to think that it happens because im in development mode in my react environment.

The issue I'm seeing is that the development environment catches the error and not react-query - only when I go out and in to the page.

I'm attaching a image that shows how it looks like.
![image](https://user-images.githubusercontent.com/10770124/68867767-0ba4d380-06ff-11ea-8bb9-b0987af6e393.png)

**Comment by tannerlinsley** [comment]
Ah... yes. The redbox error handler for CRA dev mode is a bit overzealous sometimes. Let me look into this a bit more.

**Comment by tannerlinsley** [comment]
Just to be clear, you're not using Suspense are you?

**Comment by amitripshtos** [comment]
Not using suspense

**Comment by tannerlinsley** [comment]
So the cause of this error is that that then the window is refocused, the `refetchAllQueries` function is called. This function returns a promise and will throw if any of the queries on the page error. So essentially, you don't want the window focus fetcher to throw error into the window, you want to catch the error and just log it to the console.

Let me know if that's enough info for you to get started on fixing it and feel free to open a PR. I'll help you the rest of the way with a code review there :)

**Comment by amitripshtos** [comment]
Thanks for the help, I created a pull request and tested it on my application and it does work!
