### ISSUE TITLE
suspense not working with useQuery

### ISSUE THREAD

**Issue by dominikspiertz** [tannerlinsley/react-query#3603]
### Describe the bug

We recently updated our project from react `17.0.2` to react `18.1.0`. Also we updated react-query from `^3.34.17` to `^3.39.0`.

We have multiple sections where we use useQuery to fetch data. We wrapped some of those sections with a custom query provider that sets `suspense` as a default option to show a loading spinner, until the requests are settled. Now this leads to an infinite loop that calls the fetch function inside the hook which never finishes. It does not matter, if we use a custom query provider or if we set `suspense: true` to a single call, it always loops and calls the function.

### Your minimal, reproducible example

https://codesandbox.io/s/amazing-cherry-1qvgif

### Steps to reproduce

1. Load the example and load the browser.
2. Check the `network` tab of the browser console and see how the request is fired over and over.
3. Remove `suspense: true` from the Provider in `providers/Query` and reload the page.
4. The request is called and the data is shown.
5. Repeat the same process by setting `suspense: true` inside `hooks/useUser`

### Expected behavior

As a user, the loading spinner should not show, if the requested source has been received by the browser. Also the request should only be called once.

### How often does this bug happen?

Every time

### Platform

- OS: macOS 12.3.1
- Browser: Safari Version 15.4 (17613.1.17.1.13)

### react-query version

^3.39.0

### TypeScript version

~4.6.4

**Comment by TkDodo** [comment]
1) the reproduction is not working (`index.ts` is empty), it thus only shows:
```
Error
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
```
2) you're creating a new QueryClient during render, which makes it unstable

**Comment by dominikspiertz** [comment]
@TkDodo thanks for the fast feedback. I had some locally cached files which had not been saved. The example should work now, I tested it in a private window in another browser.

**Comment by TkDodo** [comment]
as I said in point number2: make the client stable, then it works:

https://codesandbox.io/s/bold-darkness-knpqc9?file=/src/providers/Query/Query.tsx

**Comment by dominikspiertz** [comment]
Thanks for the feedback @TkDodo. I have a question when it comes to our "real" implementation. We used the QueryProvider to have a default `onError` handler for queries and mutations (We show global toast error messages, most of the time). Our custom `onError` function other hooks, which is not possible if the query client gets initialised outside of the component.

1. What has changed, that this approach is not working anymore, and that it only affect 'suspense'? We have been working with this solution for over two years.
2. With the information given, how can I implement the option to call hooks inside the defaultOptions?

**Comment by TkDodo** [comment]
this approach never worked, if the app re-renders and re-creates the query client. with suspense, it depends on where your suspense boundary lies.

the recommended approach is to use state to make it referentially stable:
https://tkdodo.eu/blog/use-state-for-one-time-initializations

```
function App() {
  const { toast } = useToast()

  const [queryClient] = React.useState(() => new QueryClient({
    queryCache: new QueryCache({ onError: (error) => toast(error)})
  }))
}
```
