### ISSUE TITLE
Performance issue between v3.39.0 and v4

### ISSUE THREAD

**Issue by Alexandredc** [tannerlinsley/react-query#3611]
### Describe the bug

Hello guys,

I have a performance issue related to v4. My application is built on NextJS and I have noticed a huge perfomance issue between v3 and v4.

I made a performance Snapshot in Chrome devtool during route transition phase and found these results : 

React Query v4:
![Screenshot 2022-05-13 at 12 04 44](https://user-images.githubusercontent.com/7659157/168263408-b95fbc34-9bc9-4f1d-b799-62a0c8bd4e87.png)

React Query v3.39:
![Screenshot 2022-05-13 at 12 07 43](https://user-images.githubusercontent.com/7659157/168263470-1a81ab16-f57d-4f0b-b534-7957618731c6.png)

It seem related to `hashQueryKey` function. 

Thanks for your amazing work 🙏

### Your minimal, reproducible example

-

### Steps to reproduce

-

### Expected behavior

-

### Platform

MacOS

### react-query version

v4

**Comment by TkDodo** [comment]
thanks for reporting. we haven't really changed anything in that specific function, so the question would be where this function was called. From the stacktrace, I can see that the `devtools` are involved?

in any case, would be good to have a reproduction to narrow down the circumstances where this happens. Is it with lots of queries? Is it with lots of re-renders? Is it on re-fetch etc ... Thanks!

**Comment by Alexandredc** [comment]
Hi, @TkDodo thanks for your quick reply.

I found out that I have an issue on my application that cause this issue. this is not related to react-query.

Sorry to open this issue to fast, It's my fault.

**Comment by TkDodo** [comment]
happy to hear that we don't have a regression. Thanks for using and testing v4-beta 🙌

**Comment by czescwojtek** [comment]
Hey @Alexandredc, care to share your experience regarding this one? I am having a hard time hunting what might be the cause. Thanks!
