### ISSUE TITLE
Mutation cache does not contain the mutationFn key

### ISSUE THREAD

**Issue by sandergo90** [tannerlinsley/react-query#3618]
### Describe the bug

Hi!

I'm currently implementing offline support for my application using the v4 version but I'm having a problem with the mutation cache.

It seems that in the `hydration.js` file, the `mutationFn` is returned in the `dehydrateMutation` function. This is causing the warning `No mutationFn found`.

### Your minimal, reproducible example

Not able

### Steps to reproduce

1. Open your application while online
2. Go offline and do some mutation that's supposed to be persisted and resumed when going online
3. Close your application fully
4. Go back online
5. Open your application again
6. Call `queryClient.resumePausedMutations();` inside the `onSuccess` function of the `PersistQueryClientProvider`
7. Warning is shown, and the mutation is not executed.

### Expected behavior

I expect my mutation to be cached correctly, and I expect the mutation function to be executed when resumed.

### How often does this bug happen?

Every time

### Platform

iOS, Android

### react-query version

4.0.0-beta.5

**Comment by TkDodo** [comment]
The problem is a conceptual one: How would you serialize a function to JSON, so that you can store it in e.g. localStorage? You cannot :)

The workaround is to use a default mutationFn for all mutations that you want to re-run after persistence.

I have documented this limitation [in the docs here](https://react-query-beta.tanstack.com/guides/mutations#persisting-offline-mutations), and the [offline example](https://react-query-beta.tanstack.com/examples/offline) also uses this approach.

**Comment by sandergo90** [comment]
Right! ;) Then we will need to implement this for all required offline calls. Thanks!

**Comment by HugoLiconV** [comment]
I'm still getting the `No mutationFn found` warning.
Here's the code:
```javascript
// App.tsx
const asyncStoragePersister = createAsyncStoragePersister({
  storage: AsyncStorage,
  throttleTime: 1000,
});

const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      cacheTime: 1000 * 60 * 60 * 24, // 24 hours
      staleTime: 2000,
      retry: 0,
    },
  },
});

queryClient.setMutationDefaults(trackKeys.all(), {
  mutationFn: (params) => {
    return track(params);
  },
});

return (
  <PersistQueryClientProvider
    client={queryClient}
    persistOptions={{ persister: asyncStoragePersister }}
    onSuccess={() => {
      console.log('PersistQueryClientProvider.onSuccess');
      queryClient
        .resumePausedMutations()
        .then(() => queryClient.invalidateQueries());
    }}
  >
     ...
  </PersistQueryClientProvider>
)
```

```javascript
// useTrackMutation

export const trackKeys = {
  all: () => ['track'],
};

function useTrackMutation(options?: Options) {
  return useMutation({
    mutationKey: trackKeys.all(),
    ...options,
  });
}

```

Any idea of what's missing?

I'm using React native and `@react-native-async-storage/async-storage` for storage.

**Comment by HugoLiconV** [comment]
@TkDodo My bad, I actually have the QueryClient outside the render function. I updated the code

**Comment by HugoLiconV** [comment]
@TkDodo I'm following [this tutorial](https://www.benoitpaul.com/blog/react-native/offline-first-tanstack-query/#persisting-the-mutations-accross-sessions) that it is pretty similar to React Query documentation.

So what I'm doing to test this is that I go offline, I call the mutation, and then close and open the app. That's where I get the warning.

I logged the AsyncStorage content and this is what I got:
```JSON
{
  "REACT_QUERY_OFFLINE_CACHE": {
    "content": {
      "buster": "",
      "timestamp": 1683554968320,
      "clientState": {
        "mutations": [
          {
            "state": {
              "error": null,
              "failureCount": 0,
              "failureReason": null,
              "isPaused": true,
              "status": "loading"
            }
          },
          {
            "state": {
              "error": null,
              "failureCount": 0,
              "failureReason": null,
              "isPaused": true,
              "status": "loading"
            }
          },
          {
            "state": {
              "error": null,
              "failureCount": 0,
              "failureReason": null,
              "isPaused": true,
              "status": "loading"
            }
          }
        ],
        "queries": [
          {
            "state": {
              "data": "Hugo",
              "dataUpdateCount": 15,
              "dataUpdatedAt": 1683554959923,
              "error": null,
              "errorUpdateCount": 0,
              "errorUpdatedAt": 0,
              "fetchFailureCount": 0,
              "fetchFailureReason": null,
              "fetchMeta": {},
              "isInvalidated": false,
              "status": "success",
              "fetchStatus": "idle"
            },
            "queryKey": [
              "async-storage",
              "vin"
            ],
            "queryHash": "[\"async-storage\",\"vin\"]"
          }
        ]
      }
    }
  }
}

```

I don't know if it is normal that the mutations don't have a query key even when I'm setting one.

**Comment by TkDodo** [comment]
where does this tutorial actually attach a `mutationKey` to the mutation? Searching for `mutationKey` on that page yields 0 results ...

FYI, our offline example does this here:

https://github.com/TanStack/query/blob/53813e45e126dcd8f846addf69c5b78322f868b8/examples/react/offline/src/movies.js#L23

**Comment by HugoLiconV** [comment]
> where does this tutorial actually attach a `mutationKey` to the mutation? Searching for `mutationKey` on that page yields 0 results ...
> 
> FYI, our offline example does this here:
> 
> https://github.com/TanStack/query/blob/53813e45e126dcd8f846addf69c5b78322f868b8/examples/react/offline/src/movies.js#L23

You're right they don't do it in the tutorial but I found the source code and they do set a `mutationKey`

https://github.com/benoitpaul/react-native-offline-tanstack-query/blob/main/api.ts#L165

My use case is pretty similar to theirs with their `addTodoWithIdMutationFn` function, except that I don't need to store anything in the cache and I don't have any queries, I just need to send data to the backend and that's it

**Comment by TkDodo** [comment]
Have a look at our offline example. It works there.
