### ISSUE TITLE
react-query v4: useSyncExternalStore error with Create React App

### ISSUE THREAD

**Issue by tmm** [tannerlinsley/react-query#3637]
### Describe the bug

Using `react-scripts@4.0.3` (a.k.a. [Create React App](https://create-react-app.dev)) does not work with `react-query@4.0.0-beta.X`. The following is the error that occurs when running the development server:

```
./node_modules/react-query/lib/reactjs/useSyncExternalStore.mjs
Can't reexport the named export 'useSyncExternalStore' from non EcmaScript module (only default export is available)
```

### Your minimal, reproducible example

https://github.com/tmm/react-query-debug

### Steps to reproduce

1. Clone repo
2. Install dependencies `npm i`
3. Run development server `npm start`

### Expected behavior

I expected to not get an `useSyncExternalStore` error

### How often does this bug happen?

Every time

### Screenshots or Videos

<img width="1076" alt="image" src="https://user-images.githubusercontent.com/6759464/169659005-3f3f2898-aaab-4dcb-ae94-1b41c39c265f.png">

### Platform

- OS: macOS
- Browser: Firefox, Chrome

### react-query version

4.0.0-beta.X

### Additional context

Reporting based on [this comment](https://github.com/tmm/wagmi/issues/398#issuecomment-1115003119) by **TkDodo** for https://github.com/tmm/wagmi/issues/398

**Comment by milonite** [comment]
Same issue here

**Comment by Chris-Kag** [comment]
Same issue here and I'm using windows

**Comment by TkDodo** [comment]
@hirbod @sachinraja can you maybe also have a look here?

I'm not sure if we're doing some wrong in our imports / exports, or if this is CRA related? We have some examples that run on CRA 3.x and they are fine 🤔

**Comment by TkDodo** [comment]
FYI, If I change this to use the default import, like the error suggests, it doesn't complain anymore, however, it also doesn't work at runtime:

<img width="1053" alt="Screenshot 2022-05-29 at 20 33 05" src="https://user-images.githubusercontent.com/1021430/170886164-188c1c5d-2815-4f81-a2ac-2bcbea215877.png">

This suggests to me that the named re-export is actually correct ?

**Comment by hirbod** [comment]
I am afraid that I am not the best person to answer this. All my knowledge goes down to RN

**Comment by sachinraja** [comment]
The error is correct. We need to change `useSyncExternalStore.ts` to this:
```ts
import pkg from 'use-sync-external-store/shim/index.js'
export const useSyncExternalStore = pkg.useSyncExternalStore
```

**Comment by hirbod** [comment]
Ah yeah, I remember seeing this fix in another repo, I think it was reanimated or react-native-gesture-handler.

**Comment by TkDodo** [comment]
thx, I'll make a PR. One more question: is the code for `useSyncExternalStore.native.ts` correct?

```
export { useSyncExternalStore } from 'use-sync-external-store/shim/index.native.js'
```

**Comment by sachinraja** [comment]
The metro bundler only picks the cjs path for this package but yeah it should probably also be changed.
