### ISSUE TITLE
refetchQueries is not respecting the `enabled` option

### ISSUE THREAD

**Issue by APetrovics** [tannerlinsley/react-query#3642]
### Describe the bug

I have a query that has the `enabled` option as false, but when a `refetchQueries()` is executed, the query with `enabled` false still gets called.

### Your minimal, reproducible example

https://codesandbox.io/s/bold-wood-ds6f12?file=/src/index.js

### Steps to reproduce

1. Create a useQuery with enabled option as false
2. Execute `refetchQueries` somewhere
3. See query gets executed

### Expected behavior

Query not get executed per the docs...
<img width="1185" alt="Screen Shot 2022-05-23 at 12 44 56 PM" src="https://user-images.githubusercontent.com/58960030/169877414-8eb4f2af-7a3a-4688-ad91-662d88bb716b.png">

### How often does this bug happen?

Every time

### Platform

- OS: [iOS, Android]
- Browser: [Chrome]

### react-query version

3.34.6

**Comment by TkDodo** [comment]
we've fixed this in v4:

- https://github.com/tannerlinsley/react-query/issues/3202

working codesandbox reproduction:
- https://codesandbox.io/s/peaceful-sunset-3rnqfn?file=/src/index.js
