### ISSUE TITLE
useMutation context docs & typings mismatch

### ISSUE THREAD

**Issue by luixo** [tannerlinsley/react-query#3652]
### Describe the bug

I found a mismtach of types for `onSuccess`, `onError` and `onSettled` types of `MutationOptions` in typings and docs.
The difference is `TContext` being optional in `onSuccess` in docs and mandatory in typings. It seems like it should be optional in docs as well as `onMutation` may not exist and therefore provide no context.

The ideal change would be to make two separate types - one with `onMutate` (context mandatory in `onSuccess`) and one without it (context is guranteed absent in `onSuccess`, `onError` and `onSettled`).

Typings:
https://github.com/tannerlinsley/react-query/blob/5848fab8a560efcf66ef0062c207c3004bccad83/src/core/types.ts#L548-L563

Docs:
https://github.com/tannerlinsley/react-query/blob/5848fab8a560efcf66ef0062c207c3004bccad83/docs/src/pages/reference/useMutation.md?plain=1#L52-L63

### Your minimal, reproducible example

https://react-query.tanstack.com/reference/useMutation

### Steps to reproduce

Open docs: https://react-query.tanstack.com/reference/useMutation
Open typings: https://github.com/tannerlinsley/react-query/blob/5848fab8a560efcf66ef0062c207c3004bccad83/src/core/types.ts

### Expected behavior

Expected typings to match docs

### Platform

Everywhere

### react-query version

v3.39.0

**Comment by TkDodo** [comment]
I  think you are right. It should also be optional in the types. The error is hidden by the bang operator here:
https://github.com/tannerlinsley/react-query/blob/5848fab8a560efcf66ef0062c207c3004bccad83/src/core/mutation.ts#L181

If you remove that, TS will complain, and we would need to adapt the typings. Would you like to contribute that?

**Comment by sunilhari** [comment]
I have made the proposed change via https://github.com/tannerlinsley/react-query/pull/3654
Kindly review and do let me know if any changes are required.

Thanks
