### ISSUE TITLE
Refetch first page on success mutation

### ISSUE THREAD

**Issue by KostyaZgara** [tannerlinsley/react-query#3660]
### Describe the bug

Hi there. I faced with the issue when trying to refetch first page for the infinite query. Here is my hooks

```typescript
export const useInfiniteListMessagesQuery = (
  options: ListMessageOptions = {},
) => {
  const jwt = useSelector(selectAuthToken);
  const headers = new Headers();
  headers.set('Authorization', `Bearer ${jwt}`);
  const query = useInfiniteQuery<IList<Message>, HttpException, Message[]>(
    ['message', 'message_list', options],
    async ({ pageParam }) => {
      if (pageParam) {
        options = {
          ...options,
          page_after: pageParam,
        }
      }
      const queryParams = new URLSearchParams(options as any);
      const response = await fetch(
        'http://localhost:3000/v1/messages?' + queryParams,
        {
          method: 'GET',
          headers,
        },
      );
      return await response.json();
    },
    {
      select: (data) => ({
        pages: data
          .pages
          .map((list) => list.data)
          .flat()
          .reverse(),
        pageParams: [...data.pageParams].reverse(),
      }),
      getNextPageParam: (lastPage) => {
        if (!lastPage.has_more_next) {
          return;
        }
        const lastResource = lastPage.data[lastPage.data.length - 1];
        if (!lastResource) {
          return;
        }
        return btoa(
          JSON.stringify({
            id: lastResource.id,
            created_at: lastResource.created_at,
          }),
        );
      },
    },
  );
  const fetchNextPage = useCallback(() => {
    return query.fetchNextPage({ cancelRefetch: false })
  }, []);

  return {
    ...query,
    fetchNextPage,
  };
};
```

```typescript
export const useCreateMessageMutation = () => {
  const jwt = useSelector(selectAuthToken);
  const queryClient = useQueryClient();
  const headers = new Headers();
  headers.set('Authorization', `Bearer ${jwt}`);
  headers.set('content-type', 'application/json');

  return useMutation<Message, HttpException, CreateMessageBody>('message', async (payload) => {
    const response = await fetch(
      'http://localhost:3000/v1/messages',
      {
        method: 'POST',
        headers,
        body: JSON.stringify(payload),
      },
    );
    return await response.json();
  }, {
    onSuccess: () => {
      return queryClient.refetchQueries(['message', 'message_list'], {
        refetchPage: (_, index) => index === 0,
      });
    },
  });
};
```

and here is my component where I'm using `useInfiniteQuery`

```typescript
export const MessengerChat: FC = () => {
  const {
    data: { pages: messages = [] } = {},
    isLoading: isLoadingMessageList,
    hasNextPage,
    fetchNextPage,
    refetch,
  } = useInfiniteListMessagesQuery({
    limit: 50,
    ticket: router.query.ticket as string,
  });
}
```

### Your minimal, reproducible example

Sorry, I can't provide reproducible example due to using external API

### Steps to reproduce

When I call mutation, refetching queries works in inconsistency way, sometimes it refetches first page, but more often it refetches last page with page param. Also, I have tried to use `useIsMutating` to listen when mutation is fully completed

```typescript
export const MessengerChat: FC = () => {
  const shouldRefetch = useRef(false);
  const {
    data: { pages: messages = [] } = {},
    isLoading: isLoadingMessageList,
    hasNextPage,
    fetchNextPage,
    refetch,
  } = useInfiniteListMessagesQuery({
    limit: 50,
    ticket: router.query.ticket as string,
  });
  const mutationMessages = useIsMutating(['message']);
  useEffect(() => {
    if (shouldRefetch.current) {
      refetch({ refetchPage: (_, index) => index === 0 });
    }
    if (mutationMessages) {
      shouldRefetch.current = true;
    }
  }, [mutationMessages]);
}
```

in this case refetching first page is working perfectly and every time

### Expected behavior

I'm expecting `queryClient.refetchQueries` will always refetch only first page

### How often does this bug happen?

Sometimes

### Platform

- OS: macOS

### react-query version

v3.39.1

### TypeScript version

v4.6.4

### Additional context

Does mutation call `onSuccess` not right after completes all updating? Probably mutation callbacks and updating query cache have some race condition which I need to avoid in another way?

**Comment by TkDodo** [comment]
> Sorry, I can't provide reproducible example due to using external API

I've explicitly mentioned in the issue template how to solve this:

> To stub out real api requests - Promise.resolve and Promise.reject are good options for easy reproduction

I don't have a compiler in my head, so I can't automatically see from a bunch of code what is going wrong. The only thing I do see is that in the queryFn, you are mutating `options` which are also part of the query key, which is never a good idea.

also, you are reversing the data in `select`, which is an observer level property. What is stored in the cache will always be what you return from the queryFn, and that is also what you get into `getNextPageParam` and `refetchPage`, because it's the only thing that exists in the central cache.

**Comment by KostyaZgara** [comment]
Wow, incredible. You say you don't have a compiler in the head, but seems you have :) First suggestion is working, the problem was in query key mutation, I didn't expect that.

P.S. Sorry, that I didn't read issue template good. Next time, I will do it. Thanks!

**Comment by alexrequelme** [comment]
Doesn't work on V5.
