### ISSUE TITLE
allcontributors test 

### ISSUE THREAD

**Issue by gargroh** [tannerlinsley/react-query#368]
This issue is for testing -- is `allcontributors bot` working fine ?

Apologies for spamming

**Comment by gargroh** [comment]
@all-contributors please add @cherniavskii  for code, bug

**Comment by gargroh** [comment]
@tannerlinsley wanted to verify, that `allcontributors bot` is installed for this repo..

> Install all-contributor bot (https://allcontributors.org/docs/en/bot/installation) for this repo

because this seems to not work https://github.com/tannerlinsley/react-query/pull/366

**Comment by tannerlinsley** [comment]
try again

**Comment by tannerlinsley** [comment]
@all-contributors please add @cherniavskii for code, bug

**Comment by tannerlinsley** [comment]
Good to go!

**Comment by gargroh** [comment]
Cool, Thanks
