### ISSUE TITLE
#feature add support for fragment update

### ISSUE THREAD

**Issue by krunaldodiya** [tannerlinsley/react-query#371]
Hi, this is insane, almost alternative to Redux, Apollo client for GraphQL, but still I have used Apollo client a lot and there is a feature called updateFragment, so after mutation, yes we can Refetch Query and also can do Optimistic updates, but imagine a huge api backend with 100+ api endpoints and 20+ api has the same reference of may be user or post, then we have to update or refetch all api query after that mutation if we change user's name or post's title, but using fragment we can store normalized data collection 

``` javascript 
{users: {1: {name:"john do"}}, posts: {1: {title:"cool post"}}} 
```

and only updates that fragment which will be reactive

how about 

``` javascript

type Post ={
  id: string;
  title: string;
  owner: User
}

type User = {
    id: string;
    name: string;
    posts: [Post]
}

cost [mutation, {data}] = useMutation('get_auth_user', async() => {
// async api function
}, {payload: User}) 

// user will pass payload to detect the structure of response

**Comment by tannerlinsley** [comment]
Trust me I’ve thought of this and actually designed a few proofs around it, but at the end of the day without a schema to know how and where normalization happens, normalizing data actually becomes near impossible to do automatically or at least is very cumbersome to the library api and users of it. I’ll keep this in mind, but for now I don’t think we’ll be exploring normalization in the core api yet. I’d love to keep discussion how you think this could happen though.

**Comment by krunaldodiya** [comment]
I have built working prototype of this feature, may be you can have a look, not perfect but will give some idea

https://github.com/krunaldodiya/useApi

**Comment by tannerlinsley** [comment]
Yeah, this looks pretty good. Its' very very close to the proofs that I architected when exploring this idea. Maybe now that React Query is relatively polished, I'll go back and look at those proofs again.
