### ISSUE TITLE
should it retry for 404 responses?

### ISSUE THREAD

**Issue by raulingg** [tannerlinsley/react-query#372]
By default when `retry` option is enabled (it is by default) react-query will retry to fetch whenever it gets an failed response from server, even when the status code is `404`, which it's a status code normally used when no data is found for the requested resource.

is this a normally behavior?

**Comment by tannerlinsley** [comment]
Yes it is. If you wish, you can use the `retry` option with a function to determine whether the error should result in a retry:

https://github.com/tannerlinsley/react-query#retries
