### ISSUE TITLE
Retry with useMutation

### ISSUE THREAD

**Issue by tibotiber** [tannerlinsley/react-query#374]
Hi Tanner,

Is there any exposed control over how useMutation handles retries? It seems to be getting the same defaults as useQuery but the docs do not mention any option to customize it.

Thanks,
Thibaut

**Comment by tibotiber** [comment]
Me again.

Was checking the code to see what adding this would that entail, realized it's way over my head but looks like you've got a pretty efficient abstraction that make queries and mutations be the same thing under the hood (?). So I tried stuffing a retry option to useMutation and *it just works TM*. 👏

Improving the docs might be something easier to contribute so if you're keen I can do that. Just that this may not be specific to retry, seems to me a lot more options are actually applicable. How would you want to proceed?

**Comment by tannerlinsley** [comment]
I actually need to make some changes actually to make the defaults separate in some places. But improving the docs for now would be great!

**Comment by tibotiber** [comment]
What would you prefer:
- point out in useMutation options that it inherits other options that are documented in useQuery
- duplicate the options for now

Also do you happen to know which options are applicable to useMutation?

**Comment by tannerlinsley** [comment]
Whichever is less of an addition to the docs. So it think the former for now. Things will get better when I separate their configuration areas.

**Comment by danthul** [comment]
Looks like this was removed. Is there currently a way to retry a usemutation?

**Comment by DimaSmakouz** [comment]
> Looks like this was removed. Is there currently a way to retry a usemutation?

I have the same question.

**Comment by stephen776** [comment]
> > Looks like this was removed. Is there currently a way to retry a usemutation?
> 
> I have the same question.

Same here @tannerlinsley any way to retry mutations?

**Comment by tannerlinsley** [comment]
Mutations never had retries. To accomplish this, you’ll have to build your own promise retry wrapper. React Query doesn’t ship with a retry for mutations for a variety of reasons, most of them based on the non-idempotent nature of most mutations.

**Comment by jasonadkison** [comment]
Currently the [useMutation](https://react-query.tanstack.com/reference/useMutation) documentation shows a `retry` option is available so I'm a little confused by this thread. Is retrying mutations still disabled and `false` by default, which is the behavior I want my application to have, or do i need to explicitly disable it in QueryClient options?

**Comment by TkDodo** [comment]
This issue is from _before_ v3 was released, please have a look at the current docs: https://react-query.tanstack.com/guides/migrating-to-react-query-3#retryoffline-mutations

**Comment by jasonadkison** [comment]
> This issue is from _before_ v3 was released, please have a look at the current docs: https://react-query.tanstack.com/guides/migrating-to-react-query-3#retryoffline-mutations

Thanks for the tip! That answers my question. Why this information is hidden in the migration docs beats me.

**Comment by TkDodo** [comment]
Ahm, its also in the guide towards mutations: https://react-query.tanstack.com/guides/mutations#retry

**Comment by jasonadkison** [comment]
Yeah, it's just not defined in the API reference where you would expect, but that's a separate issue.

**Comment by BenLorantfy** [comment]
@TkDodo In the docs there is this line:
> If mutations fail because the device is offline, they will be retried in the same order when the device reconnects.

Is this on by default?  Is there anyway to turn it off?

**Comment by TkDodo** [comment]
> @TkDodo In the docs there is this line:
> 
> > If mutations fail because the device is offline, they will be retried in the same order when the device reconnects.
> 
> Is this on by default? Is there anyway to turn it off?

do you mean https://react-query.tanstack.com/guides/mutations#retry ?

**Comment by BenLorantfy** [comment]
Is the 'retry' option relevant to offline behaviour? The docs are a little unclear to me.

> By default React Query will not retry a mutation on error, but it is possible with the retry option:
> If mutations fail because the device is offline, they will be retried in the same order when the device reconnects.

Does the `retry` option control both "on error" and "on offline" ?

**Comment by TkDodo** [comment]
> Does the retry option control both "on error" and "on offline" ?

I think so, since it's in the same section in the docs. I never tried it tbh
