### ISSUE TITLE
Navigating to a different page causes useInfiniteQuery to drop previous queries even with useInfiniteQuery being in an _app level provider

### ISSUE THREAD

**Issue by chanced** [tannerlinsley/react-query#379]
Hey, I'm not sure what I'm doing wrong. I am using next.js with a provider at the _app level.  The infinite query portion works great (thanks btw!) with the code below:

```js 
  const listingsSearchQuery = useInfiniteQuery<SearchListingResults, [string, string], number>(
    ['listings', listingQuery],
    fetchListings,
    {
      getFetchMore: (lastGroup, allGroups) => {
        return lastGroup.nextCursor;
      }
    }
  );
```
<img width="1352" alt="Screen Shot 2020-04-19 at 3 35 15 PM" src="https://user-images.githubusercontent.com/1073892/79697897-6c5aae00-8253-11ea-8607-30ba34d6f010.png">

The problem is navigating to a new page causes the data to be lost:

<img width="1178" alt="Screen Shot 2020-04-19 at 3 32 41 PM" src="https://user-images.githubusercontent.com/1073892/79697997-e3904200-8253-11ea-9e32-3a31937f9865.png">

I'm not sure what I'm doing wrong but I'd greatly appreciate your help! Thanks!

**Comment by cherniavskii** [comment]
Can you publish an example? E.g. using Codesandbox?

**Comment by chanced** [comment]
@cherniavskii working on it but codesandbox is choking on `useRouter` from `next/router` so I'm not sure how applicable the environment will be.

https://codesandbox.io/s/objective-swartz-1hemi?file=/components/Link.js

**Comment by tannerlinsley** [comment]
You could fork one of the existing code sandbox examples that use next. They are set up correctly and everything

**Comment by chanced** [comment]
@tannerlinsley For some reason it just magically started working. Sorry,  I should have corrected that; I was hoping I got the delete in before pestering yall :)

**Comment by tannerlinsley** [comment]
No worries!

**Comment by chanced** [comment]
Sorry I meant the sandbox, I'm still having issues on my end.

**Comment by tannerlinsley** [comment]
Ah

**Comment by chanced** [comment]
So the issue with the sandbox is it's running out of memory. Nextjs + Material-UI may be a bit too much for it or there's a memory leak in how it's setup. 

I'm going to go ahead and close this until I can narrow the issue down further or I can get a functioning sandbox setup. It could be that the open API I chose to replicate this is pushing back too much data. But that was the best API I could find with any sort of cursor in the response and I was hoping to mirror it up as best I can. I'll likely need to just setup my API somewhere so I can use that in the sandbox instead.

**Comment by chanced** [comment]
Ugh, I figured it out feel silly. I'm dropping this here incase anyone else happens to run into the same issue. 

The problem was using a dynamic `next/link` without using `as=`. 

Switching this:
```js 
<Link href={`listing/${listing.slug}`}>
```
with this:

```js
<Link href="listing/[listingPath]" as={`listing/${listing.slug}`}>
```

solved my problem. I only had to rebuild my app to figure it out `<sigh>`

**Comment by tannerlinsley** [comment]
Ooof! So sorry mate!

**Comment by chanced** [comment]
@tannerlinsley heh, thanks :)

I should note that it had nothing to do with react-query. Neglecting `as=` was causing next/react to do a hard load.
