### ISSUE TITLE
InitialData breaks SSR

### ISSUE THREAD

**Issue by thebuilder** [tannerlinsley/react-query#381]
Trying to render an application with some `initialData`, which triggers some async calls.

```js
if (query.state.data) {
   query.scheduleStaleTimeout(); // Simulate a query healing process

    query.heal(); // Schedule for garbage collection in case
    // nothing subscribes to this query

    query.scheduleGarbageCollection();
}
```

The `scheduleStaleTimeout()` and `scheduleGarbageCollection()` can be prevented from running by setting `stale` and `cache` to `Infinity`, but `heal()` will always call a `clearTimeout` function.

In our server environment calling `setTimeout` or `clearTimeout` throws an error.

The fix is to add the `isServer` check to the if statement - I'm just not sure if there's any consequences to doing this? Does the server actually need to call any of these methods?

**Comment by thebuilder** [comment]
If others are wondering, the current "fix" for this in my application is the skip `initialData` when rendering serverside, and just use it.

```tsx
function App(props) {
  const { data: pageData } = usePageData(useQuery, loadPageData, {
    initialData: !process.env.SERVER ? initialData : undefined,
  });
  let data = pageData || initialData;
}
```

**Comment by thebuilder** [comment]
Thanks for the quick fix!🙏

**Comment by tannerlinsley** [comment]
My pleasure

**Comment by cherniavskii** [comment]
@thebuilder Just out of curiosity, what is your server environment?
