### ISSUE TITLE
Optimistic Updates demo failed

### ISSUE THREAD

**Issue by dpyzo0o** [tannerlinsley/react-query#388]
<img width="730" alt="Screen Shot 2020-04-22 at 10 53 29" src="https://user-images.githubusercontent.com/24768249/79935465-93012a80-8487-11ea-8227-eb855111fec1.png">
 When `/api/data` returns 500, the demo errors out, seems like error handling is not working properly.

**Comment by dpyzo0o** [comment]
I changed the implementation to use the rollback function as described [here](https://github.com/tannerlinsley/react-query#updating-a-list-of-todos-when-adding-a-new-todo) and it also failed. The error message says that `rollback is not a function`.

```js
  const [mutatePostTodo] = useMutation(
    text => axios.post("/api/data", { text }),
    {
      // Optimistically update the cache value on mutate, but store
      // the old value and return it so that it's accessible in case of
      // an error
      onMutate: text => {
        const previousValue = queryCache.getQueryData("todos");

        queryCache.setQueryData("todos", old => ({
          ...old,
          items: [...old.items, text]
        }));

        return () => queryCache.setQueryData("todos", previousValue);
      },
      // On failure, roll back to the previous value
      onError: (err, variables, rollback) => rollback(),
      onSuccess: () => {
        setText("");
      },
      // After success or failure, refetch the todos query
      onSettled: () => queryCache.refetchQueries("todos")
    }
  );
```

![Screen Shot 2020-04-22 at 14 52 35](https://user-images.githubusercontent.com/24768249/79950005-04050a00-84a9-11ea-9c30-3b3fc94fc2c9.png)

**Comment by dpyzo0o** [comment]
You can find the repo at https://codesandbox.io/s/adoring-solomon-7htrd

**Comment by tannerlinsley** [comment]
I forked it, changed nothing and it seems to be working fine.

https://codesandbox.io/s/epic-sun-3z4k8?file=/pages/index.js

Caching issue on codesandbox maybe?

**Comment by dpyzo0o** [comment]
Emm, this is really strange

> I forked it, changed nothing and it seems to be working fine.
> 
> https://codesandbox.io/s/epic-sun-3z4k8?file=/pages/index.js
> 
> Caching issue on codesandbox maybe?

So it also errors out if you do not fork?

**Comment by tannerlinsley** [comment]
Correct. And since it's an actual virtual box, it makes sense that something in the cache could be skrewy. Try forking it yourself and trying it out.

**Comment by dpyzo0o** [comment]
> Correct. And since it's an actual virtual box, it makes sense that something in the cache could be skrewy. Try forking it yourself and trying it out.

I create a same repo locally and it works correctly. I still couldn't get it working on codesandbox  (even with the demo on readme). But since the issue has nothing to do with react-query I will close it for now. Thanks
