### ISSUE TITLE
queryCache needs better generics

### ISSUE THREAD

**Issue by andriijas** [tannerlinsley/react-query#389]
I tried to clone the repo and fix these issues by my self to submit a PR but Im a bit certain whatever these are real issues at all as Im quite new to typescript.

I have issues in app code with the following examples from the readme:

```
      return queryCache.getQueryData('todos')?.find(d => d.id === todoId)
```

Typescript complains that `find` is not a method on unknown because the specified return type of `getQueryData` is unknown - should the return type by an array, empty if no records found?

---

Issue two is `updatedAt`  is not a property of `query` according to the types.
https://github.com/tannerlinsley/react-query/blob/master/README.md#initial-data-from-cache

And from the same example `getQuery`  doesn't accept key argument with type of string, should the type be string | AnyQuerKey as it is with `getQueryData`?

---

Thanks!

**Comment by mattrothenberg** [comment]
@andriijas I'm fairly certain this is a Typescript issue. You're spot on – [the return value of `getQueryData` is unknown.](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-query/index.d.ts)
```
getQueryData(key: AnyQueryKey | string): unknown | undefined;
```
I'm a big fan of the pattern outlined [in this article](https://mariusschulz.com/blog/the-unknown-type-in-typescript), demonstrated in the following Codesandbox.

https://codesandbox.io/s/wizardly-frog-dh0ni?file=/src/App.tsx

Essentially, you're going to wrap up your logic for getting a Todo by ID into a helper function that returns some kind of `Result` type or interface:

```ts
type Result = { success: true; value: Todo } | { success: false; error: Error };

function getTodoFromCache(id: string): Result {
  const cachedTodos = queryCache.getQueryData("todos") as Todo[] | undefined;

  if (cachedTodos) {
    const todo = cachedTodos.find(todo => todo.id === id);
    return todo
      ? { success: true, value: todo }
      : { success: false, error: Error("No todo found") };
  } else {
    return {
      success: false,
      error: Error("Todos cache is empty")
    };
  }
}
```

That way, any component that asks for a Todo by ID can call this helper function and handle success/error states accordingly.

```jsx
export default function App() {
  const cachedTodoResult = getTodoFromCache("3");
  return (
    <div className="App">
      {cachedTodoResult.success ? (
        <pre>{JSON.stringify(cachedTodoResult.value, null, 2)}</pre>
      ) : (
        <div>{cachedTodoResult.error.message}</div>
      )}
    </div>
  );
}
```
Let me know if this makes sense!

**Comment by andriijas** [comment]
Thanks! That makes a lot of sense and actually my code is already in a helper, however it's more generic so that I don't have to write a cache helper for each entity. I just send in the cache key and the id. 

helpers.ts
```
export function getQueryCacheFrom(key: string, id: string | number) {
  return (queryCache.getQueryData(key) as [])?.find((d: any) => d.id === id);
}

```

Random model.ts
```
export function useFoo({ id }) {
  return useQuery(
    [CACHE_KEY, id],
    () => api.getFoo(id).then((r): FooInterface => r.data),
    {
      initialData: getQueryCacheFrom(CACHE_KEY, id),
    }
  );
}
```

So Maybe I should pass in the interface or cast it at the initialData

**Comment by kamranayub** [comment]
I have a todo to help update the typings for `react-query` because there's this and a couple more issues. `getQueryData` should be generic so you can pass the right type if needed.

```ts
getQueryData<T = unknown>(key: AnyQueryKey | string): undefined
```

**Comment by tannerlinsley** [comment]
I'm marking this issue as stale. If anyone wants to contribute to the types, PRs are welcome!
