### ISSUE TITLE
useInfiniteQuery typing issues

### ISSUE THREAD

**Issue by ivancuric** [tannerlinsley/react-query#390]
https://codesandbox.io/s/youtube-react-query-2848d?file=/src/App.tsx

```ts
const getPopularVideos: (key: string, pageToken?: string | undefined) => Promise<gapi.client.youtube.VideoListResponse>
```
```
No overload matches this call.
  The last overload gave the following error.
    Argument of type '(key: string, pageToken?: string | undefined) => Promise<gapi.client.youtube.VideoListResponse>' is not assignable to parameter of type 'AnyVariables'.
      Type '(key: string, pageToken?: string | undefined) => Promise<gapi.client.youtube.VideoListResponse>' is not assignable to type 'readonly [any, ...any[]]'.ts(2769)
```

What's even weirder is how TS correctly infers the usage, but then complains about implicit `any`:

```
(parameter) lastGroup: gapi.client.youtube.VideoListResponse
Parameter 'lastGroup' implicitly has an 'any' type.ts(7006)
```

The function is working fine when used with the regular `useQuery`.

**Comment by amanolar94** [comment]
@ivancuric it is not a fix of course but I was able to bypass the issue by changing this:
` const { data: actions = [] } = useInfiniteQuery(
    params && ["actions", params],
    getActions
  )` to this: `const { data: actions = [] } = useInfiniteQuery(params && "actions", () =>
    getActions(params)
  )`  and removing the key parameter from the `getActions` function

**Comment by tannerlinsley** [comment]
I'm marking this issue as stale. PRs to improve the types are always welcome!
