### ISSUE TITLE
Not getting errors through

### ISSUE THREAD

**Issue by jim-at-jibba** [tannerlinsley/react-query#391]
Hey, 

Thanks for the awesome package. 

I am sure I am missing something but when I make a request with `useQuery` and it fails the error object is always empty. But checking in the network tab shows the error is returned. I would assume this would be returned.

Thanks

**Comment by Haqverdi** [comment]
Hi, i am also have same issue, are you resolved this?

**Comment by tannerlinsley** [comment]
For React Query to catch errors, they must be thrown inside your query function. If you are using `fetch` for example, it doesn't throw on a network error by default.
