### ISSUE TITLE
Custom cache key

### ISSUE THREAD

**Issue by john-pc** [tannerlinsley/react-query#4]
Hey Tanner, thank you for another amazing library.

I would like to suggest to add custom cache key from useQuery, since the query be can changed depending on the implementation, it would be very helpful to be able to control the cache key name

**Comment by tannerlinsley** [comment]
So instead of relying on the idempotency of the `query` for the cache keying, you want to override the ID it would be given by an arbitrary string?

**Comment by tannerlinsley** [comment]
If that's the case, then we would need to propagate the manual key to this location here: https://github.com/tannerlinsley/react-query/blob/master/src/index.js#L524.  It would need to originate in the query options and get passed through a few functions to get there.

**Comment by tannerlinsley** [comment]
Though not fully documented yet. You can now use a custom `queryID` option to override the generated queryID normally returned from the function, eg.

```js
useQuery(() => axios.get('/todos'), { queryID: 'fetchTodos' })
```

**Comment by sithuhub** [comment]
#28

**Comment by sithuhub** [comment]
#30
