### ISSUE TITLE
Comparison to zeit/swr

### ISSUE THREAD

**Issue by denis-sokolov** [tannerlinsley/react-query#40]
Could you help compare react-query and [zeit/swr](https://github.com/zeit/swr)? Both project seem very similar, and the design decisions seem to overlap in many ways. It’s not obvious how to choose one over another. If you have any guidance, it would be very appreciated!

**Comment by tannerlinsley** [comment]
React query handles automatic cache purging for inactive queries and garbage collection which to me is pretty important. Everything else is just personal taste of API design. I think the query key and variables system of React Query is more robust and forgiving especially for larger apps. Overall I feel like the api and docs are just overall better for React Query. But I’m biased. 😁

Tanner Linsley

**Comment by denis-sokolov** [comment]
Thank you so much for your answer! I think this is a clear explanation and I hope whoever else looks for it can find it in the issues.

**Comment by tannerlinsley** [comment]
I'll continue to keep my original response as up to date as possible for future reference.

**Comment by tannerlinsley** [comment]
React Query:

- Handles automatic cache purging for inactive queries and garbage collection (which to me is very important)
- Query key generation, variables, and implicit query groups. The query key and variables that are passed to a query are less URL-based and much more flexible. Both the key (`todos`) and any variables (`{ status: 'done' }`) are used to compute the unique key for a query (and it's done in a very stable, deterministic way). This also allows you to use query "groups" when refetching, eg. you can refetch every query that has a `todos` key, regardless of variables, or you can target specific queries with (or without) variables. This architecture is much more robust and forgiving especially for larger apps.
- Query cancellation integration is baked into React Query. You can easily use this to wire up request cancellation in most popular fetching libraries, including but not limited to `fetch` and `axios`.
