### ISSUE TITLE
Cancel requests

### ISSUE THREAD

**Issue by tiagofernandez** [tannerlinsley/react-query#41]
There are often times in a web application where you need to send a request for the latest user interaction. We need a way to prevent subsequent (async) logic from running for all but the most recent request – something like Axios' [cancel token](https://github.com/axios/axios#cancellation) or fetch()'s [AbortController](https://developer.mozilla.org/en-US/docs/Web/API/AbortController).

**Comment by tannerlinsley** [comment]
https://github.com/tannerlinsley/react-query#cancelling-query-requests

**Comment by tannerlinsley** [comment]
Upgrade to `0.3.14`

**Comment by condef5** [comment]
Since the documentation have moved to a new website, you also find the canceling-query-request in [this link](https://react-query.tanstack.com/docs/guides/query-cancellation)
