### ISSUE TITLE
GraphQL async function

### ISSUE THREAD

**Issue by jgwiazdowski** [tannerlinsley/react-query#411]
Hello there,

perhaps a bit silly question, but still,

so docs says
_"To make a new query, call the useQuery hook with at least:
A unique key for the query
An asynchronous function (or similar then-able) to resolve the data"_

so let's say I want to call my GraphQL server, what do I put there as a 2nd argument please?

can I have an example please? how such a async function with should look like with please

right well,
I end up with below

```
 const getMe = async () => {
    const { data } = await axios({
      url: 'http://127.0.0.1:4000/graphql',
      method: 'post',
      data: {
        query: `{ me { id email } }`
      }
    });
    return data;
  };
```

and yes I can skip url and probably method with global axios config, but still, doesn't look great, especially when is comes to mutations with variables
any alternatives please?

**Comment by tannerlinsley** [comment]
Please watch this video https://egghead.io/lessons/react-use-react-query-s-usemutation-and-querycache?pl=use-react-query-s-hooks-to-query-and-mutate-data-in-your-react-components-64d6

**Comment by jgwiazdowski** [comment]
in fact next video on the playlist explains it,
but anyway, thanks a lot, 
I really wanted to avoid apollo-client on my frontend, now I have a clear solution, 
thanks again

**Comment by MatiasVerdier** [comment]
link to the correct video https://egghead.io/lessons/react-use-graphql-with-react-query-s-usequery
