### ISSUE TITLE
Dependent query returns undefined when refetching

### ISSUE THREAD

**Issue by goopi** [tannerlinsley/react-query#415]
Hey @tannerlinsley,

I think I might have found a bug related to dependent queries and refetching (`refetchAllOnWindowFocus: true`)

Example to reproduce it:
```js
const { data: token } = useQuery(['token', userId], getToken)
const { data: user } = useQuery(token ? ['user', token] : false, getUser)
console.log({ token, user })
...
```

When refetching I expect to get the previous —current— data but instead `user` is undefined. Is that the expected behaviour?

Two things I've noticed:
- The status of the *user* query is `loading`, unlike the status of *token* query which is always `success`
- `user` is undefined but `query.state.data` has the current data

**Comment by tannerlinsley** [comment]
Dependent Queries are always in a "success" state upon initialization, so long as a falsy query key is used. Only when the query key becomes truthy does a dependent query start the `loading, success/error` phases

**Comment by tannerlinsley** [comment]
The punctuate, this is intended behavior.
