### ISSUE TITLE
refetchInterval doesn't work with multiple useQuery usages

### ISSUE THREAD

**Issue by pierissimo** [tannerlinsley/react-query#417]
If my component uses multiple useQuery hooks, and each hook have refetchInterval configured, the interval doesn't seem to fire for all the 3 queries, but only for the first one.

Here the reproduced bug (open the console): https://codesandbox.io/s/exciting-fire-tyypj?file=/src/App.js

**Comment by tannerlinsley** [comment]
As of today, it will take the shortest interval and only run that one interval as a least common denominator. Work is being done to support mixed intervals.

**Comment by tannerlinsley** [comment]
I'll consider this a feature request and move it to discussions.
