### ISSUE TITLE
Supporting a stream-based flow (EventSource, SSE)

### ISSUE THREAD

**Issue by thomasbertet** [tannerlinsley/react-query#418]
Hi! 

Just curious if you would be interested in supporting a new use case for streamed data. 
For instance, it could support [EventSource](https://developer.mozilla.org/en-US/docs/Web/API/EventSource).

From what I can foresee, this would "look-like" the infinite query flow - with the difference being that it's not the front-end pulling new data but the server sending it intermittently.

Also, just wanted to say I find the doc really nice 👍 . Great job!

**Comment by tannerlinsley** [comment]
Let me start with this... if you can write a custom hook that uses the `useInfiniteQuery` hook and does this with an event source, then we can have a better discussion on whether something like this should belong in React Query, or simply as a new npm module like `react-query-use-event-source`

**Comment by tannerlinsley** [comment]
Moving this to discussions as this is a feature request.
