### ISSUE TITLE
Display stale data from previous query

### ISSUE THREAD

**Issue by theboxer** [tannerlinsley/react-query#419]
Hello,

I have a following useQuery call:
```js
const {data, status, error} = useQuery(['people', {offset, limit, search, sortBy, sortDir}], getPeople);
```

My challenge is, whenever I change `sortBy` or `sortDir`, data goes blank (cause there's nothing in cache that would show up) and then they fill with correct values again. I'm trying to keep the stale data from the previous query to stay rendered (display a loading mask using `isFetching` flag) and render new data when available. Without the flash `data - no data - data`.

I achieved this functionality by storing the data in state and updating state `onSuccess`
```js
const [data, setData] = useState();
const {status, error} = useQuery(['people', {offset, limit, search, sortBy, sortDir}], getPeople, {onSuccess: data => setData(data)});
```

My other approach was to use optional params and force refetch:
```js
const {data, status, error, refetch} = useQuery(['people', {offset, limit, search}], [{sortBy, sortDir}], getPeople);

useEffect(() => {
    refetch({force: true});
}, [sortBy, sortDir, refetch]);
```

But I'd love to know your ideas if there's a better way of doing it, or if you plan to support it as a feature - to have a set of parameters that would trigger a refetch, but won't be part of the key.

Thank you.

**Comment by tannerlinsley** [comment]
You’ll be happy to know that you can do this with the usePaginationQuery hook. It may have pagination in its name for its majority use case, but it’s more like a useLagQuery just as you are describing. Try it out!

**Comment by theboxer** [comment]
HA, you are correct, it works, thank you!

**Comment by mateo2181** [comment]
@theboxer could you share how do you call the Api with method getPeople? I a have a similar issue working with offset and pageSize, and I would like to know how to implement it.

**Comment by theboxer** [comment]
@mateo2181 I'm using the `usePaginatedQuery` this way:
```js
const {
  resolvedData, 
  status, 
  isFetching, 
  error
} = usePaginatedQuery(['people', {offset, limit, search, sortBy, sortDir}], getPeople);
```

**Comment by mateo2181** [comment]
and how have you implemented getPeople? 
In my case I have
```javascript
const [start, setStart] = useState(1)

const { status, resolvedData, latestData, error, isFetching } = usePaginatedQuery([start, paginatedSize, firstname], getUsers)
```
and my getUsers is:
```javascript
export const getUsers = async (start, paginatedSize, firstname) => {
    const { data } = await apiAxios.get(`user?start=${start}&limit=${paginatedSize}`);
    return data.data;
}
```

I have a button to call next page:
```javascript
<button onClick={() => setStart(old => old + paginatedSize)}> Next page </button>
```
but the api call is always with start=1 instead of start=11 (paginatedSize is 10).

Thanks in advance!

**Comment by theboxer** [comment]
```js
export const getPeople = async (key, {limit, offset, search, sortBy, sortDir}) => {
    const response = await axios.get('people', {
        params: {
            limit,
            offset,
            search,
            sort: sortBy,
            dir: sortDir
        }
    });

    return response.data
}
```

**Comment by mateo2181** [comment]
Thanks! I think the problem is api call happens before setStart(old => old + paginatedSize).

**Comment by waynebloss** [comment]
The `usePaginationQuery` no longer exists as far as I can see. Should we `useInfiniteQuery` in v4 to do this?

**Comment by waynebloss** [comment]
OK, nvm - I see it was also named `usePaginatedQuery` and that's now been deprecated in favor of the `keepPreviousData` option of `useQuery` - https://react-query-beta.tanstack.com/guides/migrating-to-react-query-3#usepaginatedquery-has-been-deprecated-in-favor-of-the-keeppreviousdata-option

**Comment by VladBrok** [comment]
@waynebloss thanks

**Comment by WillSmithTE** [comment]
2024 version

```
import { keepPreviousData } from '@tanstack/react-query'

useQuery({
		placeholderData: keepPreviousData,
})

**Comment by cody-ta** [comment]
> 2024 version
> 
> ```
> import { keepPreviousData } from '@tanstack/react-query'
> 
> useQuery({
> 		placeholderData: keepPreviousData,
> })
> ```

How this can be type safe?

**Comment by oliverbenns** [comment]
2025

```
useQuery({
    keepPreviousData: true,
});
```

**Comment by erayerdin** [comment]
This must be possibly the most changed feature of this library. The suggestions above do not work. What's the new method?

**Comment by Cyral** [comment]
> This must be possibly the most changed feature of this library. The suggestions above do not work. What's the new method?

The code I showed is still correct. Is it possible you are not on v5?
