### ISSUE TITLE
[Feature request] Testing Suite

### ISSUE THREAD

**Issue by amitripshtos** [tannerlinsley/react-query#42]
Hey!
I really loved the package and it's API, and I think in order to make the contribution easier we should write up tests for the hooks and other functions.

How should we progress there? Maybe create an infrastructure to the testing and I will help writing some tests? I saw swr's tests and there is a lot in common and we can learn from their testing.

Thanks!

**Comment by tannerlinsley** [comment]
Yep! I’d like to use React-testing-library and jest. Only testing actual user api, no internals. Just follow the Kent C Dodd’s example.

Tanner Linsley

**Comment by tannerlinsley** [comment]
Looks like testing has now been set up at least. Closing this as we ramp up testing

**Comment by antgonzales** [comment]
@tannerlinsley are there any examples of testing with react-hooks-testing-library? I looked through the code base and it looks like all of the tests are wrapped in components.
