### ISSUE TITLE
`defaultConfigRef` is not cleared when ReactQueryConfigProvider is unmounted

### ISSUE THREAD

**Issue by kamranayub** [tannerlinsley/react-query#428]
Working within Storybook, stories are unmounted when switching between each other. Using "decorator" functions, this is useful because we can manage different query configs for different stories.

However, I see that `defaultConfigRef` is updated when config changes but not reset to the original defaults when the provider unmounts. This persists config across Stories even when config provider is unmounted.

I have reproduced this in a test case and can submit a PR to address this.

**Comment by tannerlinsley** [comment]
Yeah, a PR would be great!
