### ISSUE TITLE
Avoid usage async/await

### ISSUE THREAD

**Issue by JiLiZART** [tannerlinsley/react-query#43]
Hi! Cool project!
Yes it's sounds strange, but if you use async/await with transpilers they generate large amount code for every `async` construction

Some examples
With async
![image](https://user-images.githubusercontent.com/62051/69013917-a1559280-098d-11ea-94db-1361330e2af5.png)
Without async
![image](https://user-images.githubusercontent.com/62051/69013939-f0032c80-098d-11ea-8c87-2503d7d42431.png)

https://unpkg.com/react-query@0.3.13/dist/index.js You can check it by yourself

**Comment by tannerlinsley** [comment]
It may incur a Small amount of overhead, but it gzips out in usage. Well worth the cost.
