### ISSUE TITLE
queryCache.refetchQueries not working with array keys

### ISSUE THREAD

**Issue by shizpi** [tannerlinsley/react-query#435]
There is something wrong with `refetchQueries`. I'm not able to trigger a refetch on multiple queries, nothing happens, but when called separately everything works fine.

This doesn't work:
```
queryCache.refetchQueries(['blacklist', 'search', 'search_count'], {
  force: true,
});
```

This works:
```
queryCache.refetchQueries('blacklist', {
  force: true,
});
queryCache.refetchQueries('search', {
  force: true,
});
queryCache.refetchQueries('search_count', {
  force: true,
});
```

**Comment by tannerlinsley** [comment]
This is by design. Refetch queries accepts a query key, which can be an array itself. If you Want to refetch multiple queries with different query keys, you must call it again with that key.

**Comment by shizpi** [comment]
@tannerlinsley Shouldn't it be called `refetchQuery` then?
Previous version had the `refetchQueries` query option inside `useQuery` that used so accept an array of multiple queries.

**Comment by tannerlinsley** [comment]
Technically it can refetch multiple queries if they share the same passed prefix. Maybe I Will consider renaming it in the next major version.

**Comment by rolivegab** [comment]
This confused me too. Lose a considerably amount of minutes until figure it out.
I think refetchQuery is better than refetchQueries.
