### ISSUE TITLE
Add support for opening Next.js examples in Codesandbox

### ISSUE THREAD

**Issue by derekblank** [tannerlinsley/react-query#44]
Installing node dependencies for any of the examples produces an error on a fresh clone of the repo, as `react` and `react-dom` are not included in package.json. Is this intended, or is it assumed these libraries would be installed globally? It's easy enough to get around it by adding them, but it might be more helpful if these were included by default in the dependency manifest.

Also, since all of the package.json files are the same, perhaps it might be easier to use one package.json for all examples and link them together via an index page that can be navigated in the browser? I was just wanting to check out the functionality of the library and it was a bit tedious to navigate and install deps in every directory. Happy to help with a PR, if it's a path you'd want to go down.

**Comment by tannerlinsley** [comment]
I would be fine with a single site for all of the non codesandbox examples.

**Comment by tannerlinsley** [comment]
Another approach here would be to set up these examples as codesandboxes (but using the next server-side template) That way, you could easily demo/tweak them individually.

Honestly, I think I like that more. Any reason not to do that?

**Comment by derekblank** [comment]
Going total codesandbox seems like it'd be better for users who are just evaluating the library and checking out the features. That would solve the dependency installation issues and provide a tweakable demo all at once. An argument the other way would be that keeping examples in the repo serves as documentation, of sorts. The README is already pretty robust, though..

**Comment by tannerlinsley** [comment]
You can have the best of both worlds. As you can see, the existing sandbox examples are hosted in the repo, but use import links to open them in codesandbox.

Tanner Linsley

**Comment by dstroot** [comment]
I can't for the life of me figure out how to test this.  I am mocking fetch and I can see that fetch is called, and can validate the URL but the component never renders.  A test example that shows how to test with this library and suspense would be awesome.  I used CRA so in setupTests.js I also mock the scheduler but I'm not sure about it: `jest.mock("scheduler", () => require("scheduler/unstable_mock"));`

Here's my test

```js
import React, { Suspense } from 'react';
import { render, waitForElement, cleanup } from '@testing-library/react';

// component to test
import InstagramBackground from '.';
import data from './__mocks__/data.json';

// automatically unmount and cleanup DOM after each test is finished.
afterEach(cleanup);

describe('InstagramBackground', () => {
  // cleanup mocks
  beforeEach(() => {
    fetch.resetMocks();
  });

  it('it renders with suspense', async () => {
    fetch.mockResponseOnce(data);

    // const { getByTestId } = render(
    //   <Suspense fallback={<div>Not Rendered Yet</div>}>
    //     <InstagramBackground username="ferrytalecreative" />
    //   </Suspense>
    // );
    // const element = await waitForElement(() => getByTestId('container'));
    // expect(element.toMatchSnapshot());

    const { asFragment } = await waitForElement(() =>
      render(
        <Suspense fallback={<div>Not Rendered Yet</div>}>
          <InstagramBackground username="ferrytalecreative" />
        </Suspense>
      )
    );

    // assert the snapshot matches
    expect(asFragment()).toMatchSnapshot();

    //assert on the times called and arguments given to fetch
    expect(fetch.mock.calls.length).toEqual(1);
    expect(fetch.mock.calls[0][0]).toEqual(
      '/.netlify/functions/photos?username=ferrytalecreative'
    );
  });
});
```

**Comment by tannerlinsley** [comment]
I’ll set up a basic test scenario to easily duplicate and extend.

Tanner Linsley

**Comment by tannerlinsley** [comment]
Yes, if you are trying to test concurrent mode, you'll need to configure for that. I would suggest starting with a simpler test.

As for the original purpose of this PR, is there anything new here? I would still love for the examples to be easier to access via codesandbox

**Comment by derekblank** [comment]
Codesandbox examples in each of the example directories seems like a good compromise. You'd likely want to create those under your own codesandbox account, though, right?

I'll create a PR to resolve the dependency installation errors on the exisiting examples.

**Comment by tannerlinsley** [comment]
Yeah I’ll create them

Tanner Linsley
