### ISSUE TITLE
Error when building app with react-query@1.3.0 and @types/react-query@1.1

### ISSUE THREAD

**Issue by ivandevp** [tannerlinsley/react-query#445]
I'm trying to build an app that is using react-query@1.3.0 and it breaks due to @types/react-query are not updated. I see that types in the [source code](https://github.com/tannerlinsley/react-query/blob/master/types/index.d.ts#L582) are updated but they're not in [@types/react-query@1.1](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-query/index.d.ts#L362).

May I help updating them?

**Comment by smashercosmo** [comment]
From now on types live in this repo. So just don't use DefinitelyTyped.

**Comment by ivandevp** [comment]
Oh... got it! So, is there some place where that is stated in the doc in order to not use it from some specific version. I mean, this will help let users that were using the DefinitelyTyped know that it's deprecated.

**Comment by tannerlinsley** [comment]
The types are kept as up to date as possible and since this is not a TS-written project, that's what we have to live with right now. A fix has been published for this issue, so you should be good to go :)
