### ISSUE TITLE
setQueryData doesn't create a new query

### ISSUE THREAD

**Issue by antgonzales** [tannerlinsley/react-query#453]
My team recently attempted to test a component that reads from the cache by creating a dummy data set. We noticed that when using `setQueryData`, no new queries are created.

```
import { queryCache } from 'react-query'

queryCache.setQueryData('test', () => ({test: 'test'})); // <-- Should create a new query if missing
console.log('get query cache', queryCache.getQueryData('test')); // <-- Doesn't create a new query
```

I believe it has something to do in these lines:
https://github.com/tannerlinsley/react-query/blob/master/src/queryCache.js#L186

**Comment by antgonzales** [comment]
@jeffreytierney discovered you can create queries with `prefetchQuery`:

```
prefetchQuery('test', () => Promise.resolve());
```
now you can interface with the cache item `test` via the getter/setter. hopefully this gives some clues about the issue.

**Comment by tannerlinsley** [comment]
I think this is more of an issue TBH. I don't personally like that `setQueryData` can affect multiple queries. It feels weird, even though I designed it lol. 

I would accept a patch PR to fix this by making this only update or create a single query, not multiple and also pass config options to it.

**Comment by antgonzales** [comment]
I think I might have had an outdated `react-query` installation. I found the tests and it appears to correctly create a new query when a query is not found. Closing this out 👍
