### ISSUE TITLE
Query is not deactivated when component unmounts in suspense mode

### ISSUE THREAD

**Issue by Grimones** [tannerlinsley/react-query#459]
Hi. First of all thanks for the great lib, i'm really enjoying using it.

The problem is that v1.3.0 creates 2 instances of query in suspense mode. And when you unmount component they are still active. In my project only 1 gets deactivated and the other one stays active, but I was not able to reproduce it here. It creates problem for me because that query is not cached and it should be removed as soon as it gets inactive but it doesn't happen.

You can check minimal reproducible example on [codesandbox](https://codesandbox.io/s/xenodochial-tdd-wj0q6?file=/src/index.js)

If you change react-query to 1.2.9 version the issue is not reproducible

At first I was thinking that https://github.com/tannerlinsley/react-query/issues/324#issuecomment-624261636 created this issue. It was late night so I haven't got a lot of concentration to check 😅
But I've made a test for that case in https://github.com/tannerlinsley/react-query/pull/455

Today I've went through commits between 1.2.9 and 1.3.0 and found https://github.com/tannerlinsley/react-query/commit/1353c420d1330082ac7e60b98b5f89723c1b065e.
I've reverted it and the my test started to pass. Still not sure what is causing, but it seems that it happens because `query.updateInstance` is called outside of useEffect

**Comment by tannerlinsley** [comment]
Fixed :)
