### ISSUE TITLE
fast-async babel plugin modifies `Function.prototype` globally

### ISSUE THREAD

**Issue by purelysloth** [tannerlinsley/react-query#46]
I wonder if we can let the user decide to use `fast-async` themselves, rather than being baked in this project.

One reason could be that it can impact other parts of their app (see my PR to react-native https://github.com/facebook/react-native/pull/27264).

It currently breaks react native apps that does dynamic styling through passing a function to `StyleSheet.create`

**Comment by tannerlinsley** [comment]
I would be okay moving back to the generator transformer. As long as someone PRs something to the docs on how to properly use fast-async

**Comment by tannerlinsley** [comment]
Would you be willing to do that?

**Comment by purelysloth** [comment]
Yes! I'll submit a PR :)

**Comment by purelysloth** [comment]
I think I've found another solution: exclude nodent runtime.

https://github.com/tannerlinsley/react-query/pull/52.
