### ISSUE TITLE
Regression in minor version 1.1.0

### ISSUE THREAD

**Issue by Goues** [tannerlinsley/react-query#462]
Hello, I'd like to report a regression bug in v1.1.0. Last working version is v1.0.36.

Usecase:

```javascript
function MyComponent() {
  const [mutate] = useMutation(event => {
    event.preventDefault()
    return MyAPI.post('/endpoint/', event.target.elements) // simplified
  }
  return <form onSubmit={mutate}>
    // omitted
  </form>
}
```

In v1.0.36, it correctly prevents default on the event and submits data. In v1.1.0 however, an error is thrown: `Cannot read property "elements" of undefined` because event no longer has a target. We all know React synthetic events cannot be used asynchronously so I expect something in v1.1.0 change and the `mutate` function is not run immediately anymore.

I don't believe this use case is that uncommon to become unsupported in a minor release.

Workaround is to wrap it, but I though I would just report it.

```javascript
function MyComponent() {
  const [mutate] = useMutation(data => {
    return MyAPI.post('/endpoint/', data)
  }
  const onSubmit = event => {
    event.preventDefault()
    mutate(event.target.elements) // simplified
  }
  return <form onSubmit={onSubmit}>
    // omitted
  </form>
}
```

Thank you for your work!

**Comment by denisborovikov** [comment]
I believe, you have to call `event.persist()` before using the event in the asynchronous call.

https://reactjs.org/docs/events.html#event-pooling

**Comment by denisborovikov** [comment]
You have to call `event.persist()` to use the event in the asynchronous call. I don't think you should rely on library internal implementation hoping it persists it for you.

**Comment by tannerlinsley** [comment]
Yep. This is out of scope for React Query. It has never prevented default, nor made any guarantees around synchronously calling on mutate. Persist the event and handle this in your own callbacks before you trigger the Mutation
