### ISSUE TITLE
errors are cached and not reset if the component using useQuery is remounted

### ISSUE THREAD

**Issue by aaronjensen** [tannerlinsley/react-query#468]
Here's an example: https://codesandbox.io/s/elegant-minsky-wwfko?file=/src/index.js

Close the error report window then click "retry". That will remount the Posts component but it will error immediately.

If you uncomment the `queryCache.clear()` it works.

I would expect that errors are not cached, or that they're cleared when the component is remounted. 

My guess is that since the component never officially mounts, there's some edge case here that isn't accounted for, or that this is an intractable problem and I should just always clear the cache on an error (which may very well be a good idea anyway).

**Comment by tannerlinsley** [comment]
I’m looking into this

**Comment by aaronjensen** [comment]
Thank you for the quick fix.

**Comment by jacklj** [comment]
Hello, I'm getting the same issue in `v.2.26.4`, so I guess there was a regression? Have solved it by clearing the cache as above, but just FYI. Thanks.

**Comment by danielowens1** [comment]
@tannerlinsley I am also getting the same issue in `v.2.26.3`. For us the cache clearing is not an optimal solution. Perhaps this issue should be reopened?

**Comment by TkDodo** [comment]
Feel free to create a new issue / discussion with a codesandbox that shows the issue, preferably on v3.

**Comment by jakepeyser** [comment]
For others facing this issue in `v2.26.x`, it looks like like the bug was also observed in https://github.com/tannerlinsley/react-query/issues/1412#issuecomment-775407972 and is being addressed in https://github.com/tannerlinsley/react-query/pull/1781

**Comment by tncbbthositg** [comment]
We just ran into the same issue with `v3.27.0`.  If I get a chance to make a code sandbox I will.  

This will get us by for now:
```typescript
  const { reset } = useQueryErrorResetBoundary();
  const queryClient = useQueryClient();

  const resetErrors = () => {
    queryClient.clear();
    reset();
  }

  return (
    <ErrorBoundary onReset={resetErrors} fallbackRender={Fallback}>
      { children }
    </ErrorBoundary>
  );
```

**Comment by TkDodo** [comment]
Can you try updating to the latest version please? I remember we had a bug somewhere that was since fixed. Otherwise please open a new issue with a codesandbox reproduction
