### ISSUE TITLE
Performance violation in Chrome when using `refetchInterval`

### ISSUE THREAD

**Issue by mmiszy** [tannerlinsley/react-query#469]
It's a very simple query:

```js
useQuery(['health-check'], getHealthCheck, {
  refetchInterval: 5000,
});
```

Unfortunately, this results in a performance problem:

<img width="926" alt="Screenshot 2020-05-08 at 17 03 03" src="https://user-images.githubusercontent.com/1338731/81419152-1ab88b80-914e-11ea-84cb-9dd36347e482.png">

**Comment by tannerlinsley** [comment]
Can you make a codesandbox that replicates this behavior please?

**Comment by mmiszy** [comment]
Oh, sorry, sure I can.. I don't know why I didn't do it in the first place!
I'll get it to you Monday morning.

**Comment by mmiszy** [comment]
Sorry, this was my fault. When I moved the `healthCheck` query to a separate component, the warning is gone! Which means I have a performance problem elsewhere in my app which affects react-query.
