### ISSUE TITLE
Needed custom params to refetch function

### ISSUE THREAD

**Issue by caiorios** [tannerlinsley/react-query#470]
First of all, congratulations to the author for this wonderful lib. It made all sense to me when writting components, and my applications became faster.

I believe that I am facing a very edge case. I read all (I think) the docs and didn't found anything about this. In advance, sorry in case this is a common case or too obvious. In my application, I have a board (trello like) that I need to mount. To make the loading process more friendly, I have to make several requests to the server.

So, here is my problem: in a piece of my code, I have to make a request for each of the lanes. However, I can't declare a hook inside a function. The first thing that came to my mind was to make my second request manual, and use the `refetch` function to manually make this call using the laneId param needed to this. However `refetch` seems to ignore custom params passed.

What is the recomendation for this case? I would like to have my data of cards cached, so I imagine that those custom params passed to refetch should be considered to the cache rule too.

Here is a example of my code. My custom hooks `useGetLanes` and `useGetCards` simply declare a async function and return `useQuery`:

```
const useLanes = () => {
  const { data, status } = useGetLanes();
  const { data: cards, refetch: getCards } = useGetCards({ manual: true });

  const isLoading = status === 'loading';
  let lanes = null;

  if (!isLoading) {
    lanes = data.reduce((result, { id, description }) => {
      getCards(id) // ---> id (laneId) is ignored
      return {
        ...result,
        [id]: {
          id: `${id}`,
          title: description,
          isLoading: true
        }
      };
    }, {});
  }

  return [isLoading, lanes];
};
```

**Comment by tannerlinsley** [comment]
Any time you are faced with the idea or restriction of using hooks in loops, that means it time to break out your loop into new child component instances. This allows you, in a way, to use hooks within a loop, as long as you are creating a new parent component for the hooks within each item.

**Comment by caiorios** [comment]
I see what you mean. In the end, the problem lies in how I implemented my board component. Right now it only expects a few little props and is not able to receive custom components.

Thank you for clarify my problem @tannerlinsley.
