### ISSUE TITLE
refetchQueries doesn't work correctly if another request is already in flight

### ISSUE THREAD

**Issue by markopy** [tannerlinsley/react-query#471]
When using `queryCache.refetchQueries()` on a query which is currently fetching it won't actually do anything and instead return the promise of the fetch already in flight. If the data changed since the first request was sent then the promise will yield old data.

This might seem like an obscure edge case but it readily causes problems in combination with `refetchAllOnWindowFocus`. I have a page which shows some data and a button to modify the data on the server. When the modification request completes I'm calling `queryCache.refetchQueries()` to update the data.

This works fine generally except when the clicking on the button while the browser doesn't have focus. Doing so triggers a refetch due to `refetchAllOnWindowFocus` which is still pending when the button handler calls `queryCache.refetchQueries()`. The refetch never happens and the data is not updated.

It seems it would make more sense for the first request to be cancelled and replaced with a new one when `refetchQueries()` is called.

**Comment by markopy** [comment]
Sorry, small clarification, it's not the button handler directly which calls `refetchQueries()`. The button triggers a PUT request to change server state and when that succeeds `refetchQueries()` is called.

**Comment by tannerlinsley** [comment]
I’m working on a way to forcefully cancel outgoing queries before mutations happen to avoid this very problem. Stay tuned :)

**Comment by tannerlinsley** [comment]
There is now a `queryCache.cancelQueries` method and both the documentation and the optimistic updates example show how to use it to avoid this situation :)

**Comment by markopy** [comment]
Thanks for the very quick turnaround on this!

A note for others who might find this issue:

In my specific case I'm calling `queryCache.cancelQueries()` immediately followed by `queryCache.refetchQueries()` when the server state has changed. This doesn't work because while `cancelQueries` cancels the previous promise it is not deleted until the promise handler is executed. The solution to this is to delay the refetch by one tick:

```
 queryCache.cancelQueries(key);
 setTimeout(() => queryCache.refetchQueries(key), 0);
```

**Comment by tannerlinsley** [comment]
Hmmm. I think we should probably have it delete the promise. Thoughts?

**Comment by markopy** [comment]
I think that would make sense from an API behavior POV but I don't understand the react-query codebase enough to appreciate all the implications.

**Comment by lifehackett** [comment]
Just checking on the latest thinking around this issue. I ran into the problem @markopy did, and while his workaround works, I would prefer for `cancelQueries` to delete the promise as was proposed.

(Note: I am using `invalidateQueries` instead of the deprecated (?) `refetchQueries`)
