### ISSUE TITLE
¿Hook useIsFetching not Working?

### ISSUE THREAD

**Issue by iamsteeve** [tannerlinsley/react-query#48]
I am trying to use this hook to show the buttons in loading mode, the problem is that what throws the hook is always false, and does not capture the first load and does not refetch them,
Are there any restrictions on this hook? o Should there be additional configuration?
Am I misunderstanding the meaning? o Do I have any erroneous configuration?
The isLoading does work correctly, but the global does not.
This is my _app with the provider.
```tsx 
// _app.tsx
 <StoreProvider store={store}>

                    <ThemeProvider theme={creatorCommerciTheme()}>

                        <CssBaseline/>

                        <ReactQueryConfigProvider>

                            <AppLayout type={AppRoles.Admin}>
                                <AnimatePresence exitBeforeEnter>


                                    <Component {...pageProps} key={router.route}/>

                                </AnimatePresence>

                            </AppLayout>
                        </ReactQueryConfigProvider>

                    </ThemeProvider>
</StoreProvider>
```

And this is one of my queries with a personalized hook.
 ```tsx
// useCustomer.tsx
interface UseCustomerProps {
    id?: string | number;
}
export const useCustomerKey = 'UseCustomerGetCustomer';

function useCustomer(props: UseCustomerProps) {
    const customerApi = new CustomersAPI();
    return useQuery(
        [useCustomerKey, {id: props.id}],
        (args) => customerApi.getOneCustomer(args.id)
    );
}
```
```tsx 
// [cid].tsx
const CID = router.query.cid as string;
    const uiActions = useStoreActions((actions) => actions.ui);
    const ui = useStoreState((state) => state.ui);

   
    const {data: customer, isFetching, isLoading} = useCustomer({
        id: CID,
    });
```
Here I try to print the status of isFetching
```tsx
// Form.tsx
const isFetching = useIsFetching();
const [mutate, { isLoading, error  }] = useUpdateCustomer();
console.log(isFetching); // ever false in loading o windows focus or mutation false false false false false
```
I need something more? Thank you very much c:
I use nextjs if they need extra information to replicate the problem can you tell me. I wanted to keep an eye on him but time consumes me so I will leave him here and I hope to be the only one that happens to him (hopefully it is my mistake)
LastVersion -- Jejejej

**Comment by tannerlinsley** [comment]
Mutations do not affect `useIsFetching`, which is meant to know if any `useQuery` instances are fetching. Mutation's come with their own state via `const [mutate, { isLoading }] = useMutation(...)`.

**Comment by tannerlinsley** [comment]
If you still believe this is an issue, please create a new codesandbox with the least amount of code possible to replicate the issue.

**Comment by julianwachholz** [comment]
Hi @tannerlinsley, I have noticed the same problem.
In this code sandbox, you can see that the global isFetching is always `false`:
https://codesandbox.io/s/nervous-knuth-ijple?fontsize=14&hidenavigation=1&theme=dark

**Comment by tannerlinsley** [comment]
I’ll look into this

Tanner Linsley

**Comment by tannerlinsley** [comment]
This should be fixed in the latest version

**Comment by julianwachholz** [comment]
Thank you! That was super fast. The sandbox works now, too! :smile:

**Comment by tannerlinsley** [comment]
😉😁
