### ISSUE TITLE
How to refetch with a new query variables in manual mode.

### ISSUE THREAD

**Issue by abouolia** [tannerlinsley/react-query#484]
When manual is false, everything work fine, once a change query variables state the useQuery refetch with a new query variables, i have no problem with that.

But once i add {  manual: true } than change query variables state and refetch, the useQuery still fetch with initial query variables data, if query variables is not reactive than how to change query variables to refetch with a new query.

Eventually thanks for such a great tool.

**Comment by tannerlinsley** [comment]
Please post a codesandbox with what you’re trying to do?

**Comment by abouolia** [comment]
Thanks @tannerlinsley i've fixed the issue, some of variables were not in dependencies, 
best regards.

**Comment by virajsoni06** [comment]
Hey @abouolia can you share the snippet of what you did to fix. Facing the exact same issue, haven't figured a solution yet.

Thanks in advance.

**Comment by mmiszy** [comment]
Yeah, any tips would be great. Can't figure it out.

**Comment by abouolia** [comment]
Hey @virajsoni06 @mmiszy, Remember that query variables is reactive with useEffect,
in this example i've wrote example check it out and follow queries changing on console log.

If the example not same your use case, please let me know. 

https://codesandbox.io/s/elastic-cannon-2r3wu?file=/src/index.js

**Comment by mmiszy** [comment]
My scenario is different. I need to trigger a refetch and handle it on button click:

https://codesandbox.io/s/rough-wave-4i4mh?file=/src/index.js

**Comment by tannerlinsley** [comment]
Firstly, if you are not subscribing to data or caching it in any way, or just downloading it one time, then you don't *have* to use React Query to do that. You can just use fetch or axios and do it that one time. If you do want to subscribe/cache/consume that data with react query, you can just make a variable for the type of data you want and pass it in the query key:

```js

const getDocumentPage = (_, page) => axios.get(`/document/${page}`).then(res => res.data)

const [page, setPage] = React.useState(0)

const query = useQuery(['document', page], getDocumentPage)

return <button onClick={() => setPage(2)}>Goto Page 2</button>
```
