### ISSUE TITLE
there should be a method like `queryCache.hasQueryData`

### ISSUE THREAD

**Issue by Shahzayb** [tannerlinsley/react-query#486]
The default case with `queryCache.setQueryData` is "If the query does not exist, it will be created and immediately be marked as stale"

1. What if you want to check if query exists or not

2. In case of using `queryCache.setQueryData`, What to do if you don't want to create query if it does not exist

I did that to resolve 2nd issue:
```
const oldTimeline = queryCache.getQueryData('timeline');
if (oldTimeline) {
    queryCache.setQueryData('timeline', (groups) => {
        groups.forEach((group, i) => {
            groups[i] = group.filter((post) => post._id !== photoId);
        });
        return groups;
    });
}
```
As you can see, the above solution is quite cumbersome.

What if there's a method called `queryCache.hasQueryData` which I can use so I don't have to use
`queryCache.getQueryData`?

**Comment by tannerlinsley** [comment]
You can do this:

```js
const query = queryCache.getQuery(queryKey)
// or
const queries = queryCache.getQueries(queryKeyPrefix)
```

Neither of those will create a query.

**Comment by mrlubos** [comment]
> 2. In case of using `queryCache.setQueryData`, What to do if you don't want to create query if it does not exist

Hey @tannerlinsley, any chance this could be an optional config parameter for `setQueryData()`? Or is your preferred approach to implement a custom wrapper in apps that require this functionality?
