### ISSUE TITLE
Prefetching on routing example

### ISSUE THREAD

**Issue by tibotiber** [tannerlinsley/react-query#49]
Hi! 

I am amazed by the work that went into this and thankful for having a fetching / caching / suspense library that is independent of the fetching mechanism used. Thank you 🙇.

I know this is not really strictly react-query's land, but would you happen to have an example of prefetching on routing? Maybe with react-router or similar. I'm really tempted by your teasing of [fetch-as-you-render ](https://github.com/tannerlinsley/react-query#fetch-on-render-vs-fetch-as-you-render) which is also described in the [react docs](https://reactjs.org/docs/concurrent-mode-suspense.html#approach-3-render-as-you-fetch-using-suspense). I have read through [this discussion](https://github.com/ReactTraining/react-router/issues/4407) in the react-router repo, but it's pretty hard getting a clear example / demo out of it 😬. So trying my luck in case anyone happen to have tried this already.

**Comment by tannerlinsley** [comment]
Did you see the suspense example in this repo?

Tanner Linsley

**Comment by tibotiber** [comment]
Yes, it's a great start for sure. That would cover prefetching on user interaction, I was hoping to find something on routing events. Maybe some more declarative prefetching depending on location change? Not sure if react-router (or others) as builtin stuff to handle this.

**Comment by tannerlinsley** [comment]
Yeah it seems tooling hasn’t really caught up just yet. This is an interesting thread with some of my thoughts on this: https://twitter.com/tannerlinsley/status/1194976554553446403?s=21

Tanner Linsley

**Comment by tibotiber** [comment]
Agreed, that’s a good thread and we’re gonna need to wait and see what’s cooking in the routing world. I’d be happy with a `Route` that let’s me define a prefetch function prop along with the component or render prop. What do you think about this approach? Wouldn’t this work at runtime and avoid having to define data requirements at build time? You just want to call prefetch at the same time as you request your new “page” bundle no?

**Comment by tannerlinsley** [comment]
Yes that would work, but if you code split any of your routing logic, now you get a waterfall effect

Tanner Linsley

**Comment by tibotiber** [comment]
Right! Thanks for pointing that out, and for sharing your thoughts on this. Hope this thread can be useful to others. And feel free to close when you wish :).

**Comment by tannerlinsley** [comment]
You bet!
