### ISSUE TITLE
Link to official docs on the repo's description

### ISSUE THREAD

**Issue by bugzpodder** [tannerlinsley/react-query#499]
if you search on react-query on Google, github is the first thing that pops up but the official docs site is not there.  It takes a lot of mental effort to get to the official docs site.  Can you Edit the repo's description to include the docs site?

**Comment by tannerlinsley** [comment]
There is no official doc site. The Readme is the official docs. Which site are you referring to?

**Comment by bugzpodder** [comment]
my bad, I use both react-table and react-query, it must have been react-table then.  I am 100% sure there was a docs site for react-table but I cant find it today either...

**Comment by bugzpodder** [comment]
It use to be https://react-table.js.org/ but it's gone now...  Anyway closing this issue, thanks for the response.

**Comment by tannerlinsley** [comment]
There used to be a docs site for react table, but we were having some big issues with it. The Readme There has now been reverted back to include the links and main menu for the docs which are in the docs directory in the repo until a new doc site is designed and released. This will likely coincide with the next major update to RT.
