### ISSUE TITLE
suspense mode fetches twice when no prefetching

### ISSUE THREAD

**Issue by tibotiber** [tannerlinsley/react-query#51]
Hello,

I've been fighting a double fetch issue which I thought came from my custom hook that wraps `useQuery`. Turns out it seems to come from `useQuery` itself.

When using the suspense mode, the fetch function is called twice, once on initial render, and once when the data comes in. This only happens if the query was not prefetched. I've forked your codesandbox and disabled prefetching of projects when you click "Show projects", I've also added a log at the start of the fetch function so it's easy to debug in the console.

Have a look here: https://codesandbox.io/s/react-query-double-fetch-q5zgl

Let me know if there is additional details I can provide.

Thanks!

EDIT: note that I've noted tried the non-suspense mode. I'm _assuming_ this is a suspense only issue.

**Comment by tannerlinsley** [comment]
Yeah I know what’s happening now that you describe it. I’ll have a fix out tomorrow.

Tanner Linsley

**Comment by tannerlinsley** [comment]
Fixed in 0.3.17

**Comment by tannerlinsley** [comment]
Fixed in 0.3.17

**Comment by tibotiber** [comment]
Yep, tested and we're all good. Thanks for the quick release :).

**Comment by tannerlinsley** [comment]
You bet!

Tanner Linsley

**Comment by amanolar94** [comment]
Hello @tannerlinsley! First of all amazing work on the whole project. I still stumble upon the same issue with suspense enabled. Is there maybe a hint on why this is happening?

**Comment by simoncarpinter** [comment]
Raised #342 with a test for this behaviour :)

**Comment by tibotiber** [comment]
@simoncarpinter meant #324?

**Comment by simoncarpinter** [comment]
I did, yes, doh!
