### ISSUE TITLE
Does react-query abstract rfc5861 like SWR?

### ISSUE THREAD

**Issue by coryhouse** [tannerlinsley/react-query#513]
The SWR docs link to [rfc5861](https://tools.ietf.org/html/rfc5861) to help clarify their intent. I found that spec helpful for understanding what it's abstracting and why. 

I believe react-query is basically doing so as well? If so, I suggest linking to the RFC in the docs.

**Comment by tannerlinsley** [comment]
I would happily accept a PR to add this as a reference to the docs :)
