### ISSUE TITLE
useInfiniteQuery is fetching twice the first page

### ISSUE THREAD

**Issue by alveshelio** [tannerlinsley/react-query#520]
Hi,

I've been reading the doc and trying to figure out what I'm doing wrong but.

I have this code 
```
  const { status, data, error, isFetching, isFetchingMore, fetchMore, canFetchMore } = useInfiniteQuery(
    "activities",
    async (_key: any, nextPage = 1) => {
      return eventsServices.getActivities({ ...selectedParams, page: nextPage, perPage: 30 });
    },
    {
      getFetchMore: (lastGroup: IActivity[], groups: IActivity[][]) => {
        return lastGroup?.length ? groups.length : false;
      }
    }
  );
```

The firs time the page loads it will fetch my activities from page one, then when I scroll and fetchMore it's called, it's still fetching the first page.
According to the docs, there should be a `nextCursor` property in `lastGroup` but either the docs aren't up to date or I'm doing something wrong because I'm getting an `undefined`.

Also, according to the docs, `By default, the info returned from getFetchMore will be supplied to the query function`. So I'm wondering if there's something I'm doing wrong but it should be pretty straight forward according to the docs.

Any help would be greatly appreciated.

**Comment by alveshelio** [comment]
Thank you very much for the help, really appreciated guys. I've solved the problem by completely uninstalling react-query.

**Comment by tannerlinsley** [comment]
I’m sorry to see you go! Its a shame you weren’t able to wait just a day or two longer when I regularly plan on reviewing, answering, and fixing issues just like this one.  Of course, if you truly need same day turnaround on issues, you’re more than welcome to sign up for my diamond sponsorship plan!

**Comment by georgiosd** [comment]
@tannerlinsley hey :) 

Any luck solving this? I'm seeing it also

**Comment by Myzel394** [comment]
@georgiosd Did you find a solution? I'm having the same issue.
After refocusing the window (after the data has been fetched at least once), the first page isn't being fetched twice and it works normally.

**Comment by georgiosd** [comment]
@Myzel394 I've let it live with a double request I guess.... not sure if @tannerlinsley is seeing these messages because it's a closed issue

**Comment by TkDodo** [comment]
Hi 👋 
I’m using infinite query in production with no issues. The original issue sounds strange to me: 

> According to the docs, there should be a nextCursor property in lastGroup but either the docs aren't up to date or I'm doing something wrong because I'm getting an undefined.

getFetchMore receives the response from your backend. If it contains a field called nextCursor you can retrieve that, but it’s your duty to return something from getFetchMore that will then be supplied as the last parameter to the fetch function. There’s nothing magic that react query will do here.

Happy to help if you would provide a codesandbox example that shows the behavior you are experiencing :)

**Comment by nollidnosnhoj** [comment]
Hi!

I am having a similar issue. When fetching the initial first page of the infinite paginated request, it will fetch the page twice. 

![image](https://user-images.githubusercontent.com/11327220/105092394-401fc800-5a45-11eb-8143-6a204c960813.png)

Here is the code for the useInfiniteQuery:

```typescript
export const useAudiosInfiniteQuery = (options: useAudiosInfiniteOptions = { type: 'audios' }) => {
  const key = generateUseAudiosKey(options);
  const fetchAudios = async (params?: Record<string, any>, page: number = 1) => {
    console.log(page)
    const qs = `?page=${page}&${queryString.stringify(params)}`
    const { data } = await request<AudioListItem[]>(key + qs);
    return data;
  }
  const params = {...options.params, size: options.size = 15 };
  return useInfiniteQuery<AudioListItem[], ErrorResponse>([key, params], ({ pageParam = 1 }) => 
    fetchAudios(params, pageParam), {
      getNextPageParam: (lastPage, allPages) => {
        return lastPage.length > 0 ? allPages.length + 1 : undefined
      },
    });
}
```

Sorry if this is considered necro-posting...

**Comment by TkDodo** [comment]
Hi, me again. There is not much we can do without a minimal reproducible codesandbox example. Feel free to stub out the actual requests with a Promise.resolve or so, it doesn’t take long to setup. I’m happy to take a look at it.

**Comment by nollidnosnhoj** [comment]
Interesting.... I created a codesandbox demo to try and demonstrate the issue, but the demo seems to be working fine (only fetching the first page once)

https://codesandbox.io/s/spring-sun-3yh46

There must be something wrong with my component that is causing the useInfiniteQuery to run twice....

**Comment by TkDodo** [comment]
Now i would either add code to the working example until it looks like your code, or work from your code backwards until it looks like the example. 

Could it be that the second request you are seeing is just because of `refetchOnWindowFocus`, because that happens a lot...

**Comment by MaximeConan** [comment]
Thanks @TkDodo. I knew this options but forget it could happen in this way. Solved the twice fetching by disabling it.

**Comment by soufDev** [comment]
I still have the same issue in my project.

https://user-images.githubusercontent.com/15775944/158273593-4f774122-6c78-45bf-88e3-8fa5c7069898.mp4

**Comment by TkDodo** [comment]
impossible to say without seeing some code, please provide a codesandbox reproduction

**Comment by lironezra** [comment]
Hi,

Facing the same issue, here the codesandbox from react-query documentation, you can notice that the second page fetched twice.   
[https://codesandbox.io/s/flamboyant-wu-y7ukkg?file=/pages/index.js](url)

Thanks for the help!

**Comment by lironezra** [comment]
I see two requests on network tab, what I did is just scrolling down for the firs time and then I got:

**Comment by lironezra** [comment]
I don't know how you saw 1 request per page because I saw two requests on network tab, what I did is scrolling down for the firs time and then I got:

![image](https://user-images.githubusercontent.com/28096499/158382523-3fb94943-9116-42a2-b64a-404c62a2d1b4.png)

Thanks for the quick response!

**Comment by TkDodo** [comment]
sorry, I'm not sure how I've missed this.

seems to be an issue with the implementation of `useIntersectionObserver`. I can see that `onIntersect` is called twice, not sure why. adding a check solves it:

```
  useIntersectionObserver({
    target: loadMoreButtonRef,
    onIntersect: () => {
      if (!isFetchingNextPage) {
        fetchNextPage();
      }
    },
    enabled: !!hasNextPage
  });
```

Personally, I've been using `useInView` from [react-intersection-observer](https://github.com/thebuilder/react-intersection-observer) with great success in our products.

**Comment by TkDodo** [comment]
I'm aware. would you like to update the example to use `react-intersection-observer` ? I'm currently quite busy with v4 :)

**Comment by soufDev** [comment]
hello @TkDodo thanks for the response, I'm trying to have an isolated case but it's really hard to reproduce it, I will try to post a `codesandbox` asap

**Comment by lironezra** [comment]
> I'm aware. would you like to update the example to use `react-intersection-observer` ? I'm currently quite busy with v4 :)

Of course I'll be happy to :), I think that I need permissions to do a pull request for the examples section right?

**Comment by TkDodo** [comment]
> Of course I'll be happy to :), I think that I need permissions to do a pull request for the examples section right?

no, you just need to fork the repo and then make a PR from your fork to this repo :)

**Comment by soufDev** [comment]
@TkDodo The issue was because of my routing, the route was mounting the component twice this is why I had the issue. it was not related to `react-query`, thank you anyway 🙏

**Comment by jayarjo** [comment]
`refetchOnWindowFocus` should be `false` by default - double request is not intuitive at all and if it goes double then one of the requests is obsolete and useless in best case scenario, in worst case scenario might cause unwanted side-effects.

**Comment by VivoCyber** [comment]
> Now i would either add code to the working example until it looks like your code, or work from your code backwards until it looks like the example.
> 
> Could it be that the second request you are seeing is just because of `refetchOnWindowFocus`, because that happens a lot...

it solve mater

**Comment by emil-malmgaard-rasmussen** [comment]
@nollidnosnhoj I just want to thank you and everyone else here! have been sitting with an ovbious mistake, but the code snippet provided by @nollidnosnhoj made me realize my mistake, so, thank you sir!

**Comment by MokDevelopment** [comment]
Ok it seems that this issue is still a problem. I just spend good 2h trying to fix my bindings until I found this bug report. Is there any workaround?

**Comment by TkDodo** [comment]
@MokDevelopment all "bug" reports in this issue turned out to be false positives, either something wrong implementation wise, or mixing things up with window focus refetches, or buggy intersection observers. At no time was there a real issue with react-query fetching the first page of an infinite query twice for no reason.

Please, if you have a minimal reproducible codesandbox example that shows your issue, I'm more than happy to take a look.

**Comment by MokDevelopment** [comment]
I want my wasted time back.... arrrghh ;)
@TkDodo  Sorry...  - you are totally right 

It seems, that the issue just exists on the dev layer. Even when producing a local build, there is just one request. 

Sorry again.

**Comment by gssrinivas59** [comment]
In “dev mode” each component gets mounted twice, it's a side effect of reacts strict mode. This will not happen once build.
https://reactjs.org/docs/strict-mode.html


Are you using React 18 and Strict Mode? If yes, this is the problem. It's a "feature" included in React 18 to test that your component can be un-mounted and mounted again, in preparation for a future React feature. It's enabled only when in Strick Mode. So either take Strick Mode out or work around it similar to what the blog here describes.

Here it's explained with a solution: https://blog.ag-grid.com/avoiding-react-18-double-mount/

**Comment by Nazaire** [comment]
In my case, I was requesting another page before the previous one had completed.
```
useEffect(() => {
    query.fetchNextPage();
  }, [inView]);
```
So I ignore further requests if the query is currently loading and I don't get duplicate pages any more.
```
useEffect(() => {
    if (!query.isFetching) query.fetchNextPage();
  }, [inView]);
```

**Comment by Shaxadhere** [comment]
Did anyone find a simple solution to this?

**Comment by grishkovelli** [comment]
`refetchOnWindowFocus: false` helped me. thanks @TkDodo

**Comment by Roman-H91** [comment]
`refetchOnWindowFocus: false` - it helps! Thanks
