### ISSUE TITLE
status resets to "loading" when initial query resulted in an error

### ISSUE THREAD

**Issue by probablyup** [tannerlinsley/react-query#529]
Based on the docs it looks like once the query has initially fired, the way to tell if a query is being fetched again is to look at the `isFetching` flag, not the `status` flag.

This seems to work fine for queries that were successful the first time but, if there was an error, `status` is reset to "loading" when the normal refresh mechanism is triggered (switching browser tabs, etc.) If that is the desired behavior, I'd love a configuration option to disable it and just defer to the `isFetching` flag.

**Comment by tannerlinsley** [comment]
This is intentional for now. In the future, errors that are retried may fall back to success + isFetching by default.

**Comment by tannerlinsley** [comment]
The next major version will not revert to a loading state unless `typeof query.state.data === 'undefined'` 👍

**Comment by probablyup** [comment]
Thanks @tannerlinsley!
