### ISSUE TITLE
Reset mutation state

### ISSUE THREAD

**Issue by purelysloth** [tannerlinsley/react-query#53]
When a mutation raises and error, it would be nice if we could `reset()` the `error` state.

**Comment by tannerlinsley** [comment]
Just refetch the query 🤷‍♂️ Which is essentially the Same thing.

Tanner Linsley

**Comment by tannerlinsley** [comment]
If that proves to not be a viable solution, please reopen (or open a new issue). The API wouldn't be hard to add for that. Closing for now.
