### ISSUE TITLE
Best way to edit data after useQuery call?

### ISSUE THREAD

**Issue by Buuntu** [tannerlinsley/react-query#530]
I've had some weird instances where changing the data fetched from a query changes it in the cache (and therefore everywhere that depends on that data).

What's the current best practice for altering data after fetching it - in the query function itself?  Is there any good way to change it in the component after the data is loaded?

An example:
```JSX
const Comp = () => {
  const { data } = useQuery('get', asyncFunc);

  if (data) {
    const dataCopy = [...data];
    dataCopy.push('new object'); // data is corrupted here everywhere that depends on this query
  }
  ...
  // do something with dataCopy
```

Maybe this is expected behavior and I should just do all my post-fetch mutations in the query function itself?

**Comment by jackmellis** [comment]
The key is with the term *mutations*. If you edit the data object it’ll affect the data value in the cache. Any post-query transformations should always be done with immutability in mind

**Comment by Buuntu** [comment]
I guess I'm a little confused because even when I make a deep copy of the data with the spread operator it seems to affect this cache.  Maybe there's something weird I don't understand with `push` that's happening under the hood.

**Comment by jackmellis** [comment]
It shouldn’t do. If you clone an array by spreading, then `newArray.push` shouldn’t have any impact on the original array.

Do you have a more comprehensive example? Or the repo?

**Comment by tannerlinsley** [comment]
This is not a bug, but definitely a good question. Converting to discussion....
