### ISSUE TITLE
QueryFn does not recall when Query Variables is updated!

### ISSUE THREAD

**Issue by hmtri1011** [tannerlinsley/react-query#532]
This is my first try on react-query, not sure if my implementation is correct, any help would be appreciated!

When I click the button and call `handleLoadMore()`, `offset` is updated but the queryFn does not recall and so that the data does not update.

Below is the screenshot of my code and query cached data on `ReactQueryDevtools`

A little note that: `ReactQueryDevtools` also has a bug that it will crash my page when I click to query detail.

![image](https://user-images.githubusercontent.com/16288424/83327308-c0ba6a00-a2a4-11ea-8afa-b7ba2dd59515.png)

![image](https://user-images.githubusercontent.com/16288424/83327405-bc428100-a2a5-11ea-98ee-7ba9186e51ac.png)

**Comment by hmtri1011** [comment]
Seem like I found the problem, `config.initialData` is the problem that makes the query does not re-fetch when offset changed.

FYI, I'm using SSR and initialData is the data I fetched from server. May I know what is the correct way to use `config.initialData` on react-query?

**Comment by cherniavskii** [comment]
Yeah, looks like a bug
Here's a minimal example: https://codesandbox.io/s/infallible-shape-ofysh?file=/src/App.js

**Comment by cherniavskii** [comment]
Actually, maybe that's because you shouldn't pass initialData after query variables change?
I mean, if you have initial data for page 1, you shouldn't use them as initial data of page 2, right?

**Comment by cherniavskii** [comment]
Something like this: https://codesandbox.io/s/nameless-platform-5dyhj?file=/src/App.js

**Comment by hmtri1011** [comment]
@cherniavskii ahh I see, thank you!
 So is this the correct way to use `config.initialData`? IMO, I think it is better to have `config.initialData` affected when mounted only

**Comment by hmtri1011** [comment]
Hi is there any news for this?

**Comment by tannerlinsley** [comment]
If you change the queryKey, `initialData` will act the same. If there is no data present in the cache for the query, the initial data you pass (if any) will be used. This is remaining the same in 2.0 as well.

**Comment by huchenme** [comment]
What shall we do if we just have initial data for certain queries but want to perform a fetch when query change?

**Comment by tannerlinsley** [comment]
The query should refetch on mount even if initial data is set.

**Comment by hmtri1011** [comment]
Hmm I see, so the efficient way to use `initialData` is:
`const { data = initData, status } = useQuery(key, QueryFn)`

right?

**Comment by tannerlinsley** [comment]
Nor sure what you mean by efficient, but sure, that works. The difference is that by setting the initialData option itself the cache will be populated with that data. By destructuring with a default value like you are doing here does not set the cache data.

**Comment by hmtri1011** [comment]
Thank you!
