### ISSUE TITLE
[Typescript] Unexpected type errors

### ISSUE THREAD

**Issue by vmajsuk** [tannerlinsley/react-query#534]
CodeSandbox: https://codesandbox.io/s/romantic-tharp-kxg7n?file=/src/useQuery.ts

```typescript
import {
  useQuery as useQueryBase,
  QueryOptions,
  QueryResult
} from "react-query";
import { useCallback } from "react";

export function useQuery<Data, Variables>(
  fetchData: (v: Variables) => Promise<Data>,
  variables: Variables,
  config?: QueryOptions<Data>
): QueryResult<Data> {
  const fetchDataEnhanced = useCallback((_, v: Variables) => fetchData(v), [
    fetchData
  ]);
  const result = useQueryBase(
    [fetchData.name, variables],
    fetchDataEnhanced,
    config
  );
  return result;
}
```

Even though this is a valid usage according to the docs: https://github.com/tannerlinsley/react-query#query-key-variables

**Comment by hankeypancake** [comment]
Your `Variables` doesn't have any form. Try to make them extend `AnyVariables` from react-query, that might solve your issue (I'm not sure as I have a little trouble reading all the overloads for useQuery myself). In any case, I'm pretty sure this is not an issue with react-query.

**Comment by jakwuh** [comment]
```
export function useQuery<Data, Variables extends object> (
  fetchData: (v: Variables) => Promise<Data>,
  variables: Variables,
  config: QueryOptions<Data> = {
    retry: 2,
    cacheTime: 5 * 60 * 1000,
  },
): QueryResult<Data> {
  const fetchDataEnhanced = useCallback((_, v: Variables) => fetchData(v), [fetchData]);
  return useQueryBase([fetchData.name, variables], fetchDataEnhanced, config);
}
```

see `extends object`

**Comment by tannerlinsley** [comment]
This issue has become stale. Please reopen a new issue with more/better information on how to replicate or solve the problem. Thanks!
