### ISSUE TITLE
The examples are broken

### ISSUE THREAD

**Issue by sarpik** [tannerlinsley/react-query#536]
The posts never finish loading, at least @

* https://codesandbox.io/s/github/tannerlinsley/react-query/tree/master/examples/basic
* https://codesandbox.io/s/github/tannerlinsley/react-query/tree/master/examples/custom-hooks?file=/src/index.js
* etc

**Comment by leimonio** [comment]
I can't see this issue, I've tried both examples but they are loading and working as expected.

**Comment by sarpik** [comment]
Now they're working for me too - strange.
