### ISSUE TITLE
Ability to rate limit useInfiniteQuery rebuild

### ISSUE THREAD

**Issue by conzett** [tannerlinsley/react-query#537]
In https://github.com/tannerlinsley/react-query/pull/408 the ability to properly rebuild cursors to prevent gaps and duplicates was added and it works great! I'm running into an issue however with requests that are rate limited by the server as the implementation tries to fire off the requests as fast as possible it seems.

Additionally, with a large number of pages, we will run into an issue where we're going to hit the maximum number of async requests a browser can issue simultaneously, probably an edge case but I have run into it.

It would be nice if there was some kind of configuration option to throttle the rebuild requests.

Thanks for all your work on react-query!

**Comment by conzett** [comment]
I've gotten reasonably close to what I'm looking to do by throttling the fetcher function. I thought this approach wasn't working at first but that thankfully it mostly seems to do the trick!

**Comment by georgiosd** [comment]
@conzett how can we track this feature build?
