### ISSUE TITLE
useInfiniteQuery getFetchMore firing multiple times with old states

### ISSUE THREAD

**Issue by effectiveduck** [tannerlinsley/react-query#541]
```ts
const {
  status,
  data,
  error,
  fetchMore,
  isFetching,
  isFetchingMore,
  canFetchMore
} = useInfiniteQuery(
  ["search", searchTerm],
  async (_, _1, nextPage = 0) => {
    console.log("fetching")
    const headers: any = {
      accept: "application/json"
    }
    const response = await fetch(SEARCH_URL + `?Query=${searchTerm}&Start=${nextPage}`, { headers })
    if (response.ok) return await response.json()
    throw await response.json()
  },
  {
    getFetchMore: (l, all) => { console.log({l, all}); return l.nextPage; }
  }
)
```

For the first fetch, getFetchMore is only called once as expected, but when I call fetchMore afterward, getFetchMore is called twice and crucially the last call is using the return from the first fetch.

Here's the console output

```
fetching
{l: {…}, all: Array(1)} 
fetching
{l: {…}, all: Array(2)}
{l: {…}, all: Array(1)}
```

In this example there's only 2 pages but canFetchMore is true. getFetchMore is resolving correctly it's just using the wrong state.

If the query is refetched, from refocusing the window for example, it seems to correct the error but getFetchMore is called many times, just not with old state.

Thanks for any help!

**Comment by johnslay** [comment]
I had a similar problem and the issue is that you need to coerce ‘undefined’ to null in ‘getFetchMore’ so that your default parameter does not get set in the api call.

**Comment by effectiveduck** [comment]
@johnslay yea that seems to have done the trick, thank you!
