### ISSUE TITLE
[TypeScript] ReactQueryConfigProvider type miss match

### ISSUE THREAD

**Issue by pete-redmond-cko** [tannerlinsley/react-query#542]
I noticed that use can pass the type of error to the `ReactQueryProviderConfig` interface, however the `ReactQueryConfigProvider` does not except the `TError` so it sets the error in config to be `Error` (the default).

```ts
const reactQueryConfig: ReactQueryProviderConfig<AxiosError> = {
  refetchAllOnWindowFocus: false,
  refetchOnWindowFocus: false,
  retry: (failureCount, error) => {
    if (error.response?.status === 404) {
      return false;
    }

    return failureCount > 2;
  },
};
```

```ts
<ReactQueryConfigProvider
  config={reactQueryConfig}
>
      ...
</ReactQueryConfigProvider>
```

 I am getting a type error when trying to use a `AxiosError` in the config.

![Screenshot 2020-06-03 at 13 03 27](https://user-images.githubusercontent.com/48683566/83634548-a3361a80-a59a-11ea-8f4b-cd085b3e7c44.png)

Shouldn't the ReactQueryConfigProvider take in the Error Type?

```ts
<ReactQueryConfigProvider<AxiosError>
  config={reactQueryConfig}
>
      ...
</ReactQueryConfigProvider>
```

**Comment by thebuilder** [comment]
Have you tried in the latest version?

**Comment by pete-redmond-cko** [comment]
@thebuilder tried 1.5.5 and still getting the same warning

Looking at the typings, the error in config was always fall back to `Error` because the type of Error isnt passed to `ReactQueryProviderConfig`

```
export const ReactQueryConfigProvider: React.ComponentType<{
  config?: ReactQueryProviderConfig
}>
```

**Comment by thebuilder** [comment]
I think that should be fine. It expects an instance of the config type, which you are providing.

**Comment by pete-redmond-cko** [comment]
> I think that should be fine. It expects an instance of the config type, which you are providing.

@thebuilder here is a link to the a codesandbox with the error

You cant pass the error type to `ReactQueryConfigProvider` as it doesnt take any generics, `ReactQueryProviderConfig` does but not the actual provider component

**Comment by thebuilder** [comment]
You're right. Haven't had to use a generic on JSX before. Not pretty - might wan't to also add documentation for this use case.

But in that case, then yes - this would be the correct way.

```tsx
<ReactQueryConfigProvider
  <AxiosError>
  config={reactQueryConfig}
>
      ...
</ReactQueryConfigProvider>
```

**Comment by thebuilder** [comment]
Rewriting the type into this, should solve it:

```typescript
export function ReactQueryConfigProvider<TError = Error>(props: {
  config?: ReactQueryProviderConfig<TError>;
  children?: React.ReactNode;
}): React.ReactElement;
```

**Comment by mustafawm** [comment]
@pete-redmond-cko has this `<ReactQueryConfigProvider<AxiosError> config..>...` worked for you? 

Is it supposed to override the type of error returned by `userQuery` and others?

May I ask what form of `useQuery` you're using? (not sure if it matters, but I cannot see  `TError` being used/inherited 
```
// Object Syntax
export function useQuery<TResult, TKey extends AnyQueryKey, TError = Error>({
  queryKey,
  queryFn,
  config,
}: {
  queryKey: TKey
  queryFn?: QueryFunction<TResult, TKey>
  config?: QueryOptions<TResult, TError>
}): QueryResult<TResult, TError>
```

**Comment by pete-redmond-cko** [comment]
@mustafawm yeah it worked. It only overrides the type of Error in `ReactQueryProviderConfig`. You will still have to pass `AxiosError` too `useQuery`.

My use case was to handle retry logic on the config provider so I didnt have to do it on every `useQuery`, I dont want to retry if the API returns `404`.

```js
const reactQueryConfig: ReactQueryProviderConfig<AxiosError> = {
  refetchAllOnWindowFocus: false,
  refetchOnWindowFocus: false,
  retry: (failureCount, error) => {
    if (is404Error(error)) {
      return false;
    }

    return failureCount > 2;
  },
};

<ReactQueryConfigProvider<AxiosError> config={reactQueryConfig}>...<../>
```

**Comment by mustafawm** [comment]
Thanks for your quick reply @pete-redmond-cko 🙏. Will start passing error type to `useQuery`s then.
