### ISSUE TITLE
Add docs on how to use the types?

### ISSUE THREAD

**Issue by probablyup** [tannerlinsley/react-query#543]
As someone that's relatively new to TS, I've been finding the types included in this library a bit unapproachable since they're not commented on how to use them. For example:

```ts
useQuery<arg, arg>()
```

How does one know what those args do? How do I specify the query result only in a success scenario, etc.

Thanks, love the library!

**Comment by tannerlinsley** [comment]
Types are a great addon to this library, but I do not maintain them personally. Feel free to open a PR to the docs or types to help with this! Thanks!

**Comment by probablyup** [comment]
@tannerlinsley perhaps you could leave this open with a "help wanted" label then?
