### ISSUE TITLE
latest patch release causes a breaking ts change

### ISSUE THREAD

**Issue by jackmellis** [tannerlinsley/react-query#546]
In some cases the new `TError` type is defaulted to `Error` but I've already found that I'm getting a lot of errors now because `QueryOptions` suddenly requires a `TError` type. I think everywhere this new type is used it should have some fallback behaviour.

**Comment by thebuilder** [comment]
Thanks for fixing this. The PR was merged before being fully tested for issues like this, but great way to discover them afterwards.
