### ISSUE TITLE
"promise" being shown at useMutation return type and documentation

### ISSUE THREAD

**Issue by MathMesquita** [tannerlinsley/react-query#548]
Hello everyone.

While creating my application, I found out that the [`MutationResultBase`](https://github.com/tannerlinsley/react-query/blob/master/types/index.d.ts#L547) interface and the [useMutation's](https://github.com/tannerlinsley/react-query#returns-3) documentation are mentioning a `promise` key in the MutationResultObject but `promise` isn't returned at [`useMutation.js`](https://github.com/tannerlinsley/react-query/blob/master/src/useMutation.js#L53).

Is it a bug in useMutation implementation or in the documentation?

I can open a PR for either, just want to know where the fix should be done. :)

**Comment by tannerlinsley** [comment]
I don't know much about the types per se, but `mutate` is asynchronous, so there are some generics and options in there for that promise. Feel free to open a PR with any other suggestions you may have. Thanks!
