### ISSUE TITLE
useInfiniteQuery doesn't pass getFetchMore when invoked using object syntax

### ISSUE THREAD

**Issue by kamranayub** [tannerlinsley/react-query#549]
When `useInfiniteQuery` is invoked using the object-based method:

```js
useInfiniteQuery({
  queryKey,
  queryFn,
  getFetchMore
})
```

**Then** the `getFetchMore` is `undefined`

```js
useInfiniteQuery({
  queryKey: 'test',
  queryFn: (_, nextId = 0) => fetchItems(nextId, fetchCountRef.current++),
  getFetchMore: () => (lastGroup, allGroups) => lastGroup.nextId
})
```

I can see in `useInfiniteQuery` that `config.getFetchMore` is `undefined`.

I have a failing test case and I'm trying to fix it.

**edit:** hold on lol

**Comment by kamranayub** [comment]
Hmm nevermind, there may not be an issue here, my test case setup incorrectly. Will re-open if I learn otherwise.

**Comment by levani** [comment]
I have the same problem. The second parameter of the query function is always undefined no matter what I return from `getFetchMore`.
