### ISSUE TITLE
Ephemeral Network Traffic in Dependent Queries upon Key Change

### ISSUE THREAD

**Issue by seanstern** [tannerlinsley/react-query#550]
## Problem Description
When a [dependent query](https://github.com/tannerlinsley/react-query#dependent-queries) has an [array key](https://github.com/tannerlinsley/react-query#query-keys) where
- one element of the key is dependent on mutable React state (in a React.useState sense) of the component
- another element of the key is derived from the data of a query which is itself relies on the exact same state mentioned above as its query key

the two elements can become mismatched.

The code below outlines the setup:
```javascript
const [state, setState] = React.useState(/*some value*/); 
const queryA = useQuery(['queryA', state], networkReqA);
// In this generalzed example state and queryA.data can become mismatched
// when state changes
const queryB = useQuery(queryA.data && ['queryB', state, queryA.data], networkReqB);
```
When the state changes, it does not immediately generate a change in the returned data of the first (i.e. non-dependent) query. In the above example, this means that when `state` changes to a new value, `queryA` does not immediately change. Instead, `queryA` initially returns the same `status` (i.e. `success`) and the same `data` (i.e. whatever was returned for the previous value of state). Only subsequent renders that occur *after the initial change* result in a change to `queryA`.

This results in the dependent query relying on
- a *new* state value as one element of the key
- a *stale* data value as another element of the key

If the dependent query in question generates network traffic with these keys, then the server will receive a request for a mismatched set of parameters (i.e. *new state* and *stale data*). This generates useless requests for the server--which can increase load, generate meaningless errors, etc.

## Repro
Below are links to a react project that demonstrates the behavior:
- [Github](https://github.com/seanstern/react-query-ephemeral-dependent-query-demo)
- [CodeSandbox](https://codesandbox.io/s/github/seanstern/react-query-ephemeral-dependent-query-demo)
## Desired Behavior
It seems like react-query should immediately return the query value that corresponds to a changed key at the moment the key changes, not on subsequent re-renders.

**Comment by jackmellis** [comment]
Refetches don’t clear out the data property anyway so after the initial load you’d never get a falsy value for the dependent query. I’m wondering if you can work around this by calling useQuery with `queryA.data && !queryA.isFetching` ? Then when you’re refetching the first query, your second query should in theory be postponed until fetching is false...

**Comment by seanstern** [comment]
@jackmellis thanks for taking the time to respond. Really appreciate it.

Just ran a test on the demo code I linked to and `queryA.isFetching` won't help. It also isn't changing when `state` changes.

In fact, when `state` changes the following properties of `queryA` **do not** change on that first render
- `status`
- `data`
- `isFetching`
- `failureCount`

In my example ([Github](https://github.com/seanstern/react-query-ephemeral-dependent-query-demo) or [CodeSandbox](https://codesandbox.io/s/github/seanstern/react-query-ephemeral-dependent-query-demo)), this means that the changes to `state` and `queryA` look as follows

| render | `state` | `queryA` |
| :------------- | :----------: | -------: |
| 0 | `'dog'` | ```{ "status":"success",  "error":null, "isFetching":false, "failureCount":0, "data":"animal"}``` |
| 1 | `'juniper'` | ```{ "status":"success",  "error":null, "isFetching":false, "failureCount":0, "data":"animal"}``` |
| 2 | `'juniper'` | ```{ "status":"loading", "error":null, "isFetching":true, "failureCount":0, "data":undefined}``` |

**Comment by seanstern** [comment]
I did a little more digging and it seems like this delayed change behavior's root cause is tied to an outdated version of react-query in my codebase and in my examples ([Github](https://github.com/seanstern/react-query-ephemeral-dependent-query-demo) and [CodeSandbox](https://codesandbox.io/s/github/seanstern/react-query-ephemeral-dependent-query-demo)).

I built my examples by forking the react-query repository's examples--specifically the [basic example](https://github.com/tannerlinsley/react-query/tree/master/examples/basic). The basic example relies on `react-query@1.0.12` (c.f. [yarn.lock line 8168](https://github.com/tannerlinsley/react-query/blob/master/examples/basic/yarn.lock#L8168) and [package.json line 13](https://github.com/tannerlinsley/react-query/blob/master/examples/basic/package.json#L13)).

This delayed change behavior persists up to `react-query@1.0.15`. However, the issue seems to be resolved in `react-query@^1.0.16`.

I recognize it's not high priority, but updating the examples to use more up to date versions of react-query would be helpful so that others don't make similar mistakes when experimenting with the codebase. Is that worth filing an issue for?

**Comment by tannerlinsley** [comment]
The sandbox’s are in the examples directory, so a PR to update their deps would be even better :)

**Comment by seanstern** [comment]
Can do! I'll try to submit something in the next few days.
