### ISSUE TITLE
status is 'succes' on manual useQuery

### ISSUE THREAD

**Issue by likrot** [tannerlinsley/react-query#559]
Hi,

I have an issue and I don't know what I am doing wrong (RN app).

code:
```
const { status, data, error, refetch, isFetching } = useQuery(['search', search, chosenType], fetchSearchResults, {
        manual: true,
    });

[...]

const onKeyPressHandle = () => {
        if (startSearch) { 
            refetch();
        }
    };
```

When I am fetching data with useQuery status is always `success`, but in an example from readme file, I see that `status` can be different than `success` (as in auto mode). 
Question is what I am missing?

react: 16.13.1
react-native: 0.62.2
react-query: 1.5.2

**Comment by ntrabue** [comment]
Per the docs, when using a manual query the status will initially be 'success' and the status won't change until you refetch. Is the value of isFetching changing whenever your query is fired?

**Comment by tannerlinsley** [comment]
This is consistent with the docs. It starts as success in 1.x. In the next version (2.x), dependent and manual queries (or if we're being official, `enabled` queries) will start with an `idle` version.
