### ISSUE TITLE
useQuery sometimes throws error multiple times with { suspense: true }

### ISSUE THREAD

**Issue by adaddeo** [tannerlinsley/react-query#564]
```
useQuery("key", () => Promise.reject(new Error("failure")), { suspense: true, retry: false }
```
results in the error is _sometimes_ being thrown twice (though the queryFn is only being called once). I'm expecting it to only throw once. 

The context for my use case is I'm taking a redirect action (using `redirectTo` from @reach/router) based on the thrown error but am running into this problem where two redirects happen when the error is thrown twice. I can definitely work around this but I wanted to at least to surface in case this was unknown behavior.

Reproduced here:
https://codesandbox.io/s/wonderful-thunder-r3om5?fontsize=14&hidenavigation=1&theme=dark

And thank you for this library!

**Comment by adaddeo** [comment]
I was able to isolate the problem.

The error boundary that is catching the error ([coming from @reach/router](https://github.com/reach/router/blob/master/src/index.js#L72-L83)) doesn't immediately cause it's children to unmount, so after the error has been thrown there is a race condition where sometimes the `useQuery` hook that threw the error get's called in an additional render cycle after having already thrown the error.

I'm guessing this isn't a bug, because I'm not sure what other behavior it could be expected to take in suspense mode than continuing to throw the same error.

**Comment by tannerlinsley** [comment]
Yeah, I see what you're saying. This might be better in 2.0 as well. As per usual with suspense, it's all experimental right now, so we'll just have to keep doing our best to make it better. If you have suggestions, please open a PR. Closing this for now. Thanks!
