### ISSUE TITLE
initialData option for useQuery

### ISSUE THREAD

**Issue by mickykebe** [tannerlinsley/react-query#59]
Is it possible to have an initialData option for useQuery like in swr.

I'm using Next.js to fetch data in getInitialProps and i'd like that value to be the initial data when the same request is made with useQuery.

**Comment by tannerlinsley** [comment]
`config.initialData` is now supported in version 0.3.19 🎉

**Comment by pawan52tiwari** [comment]
where can i find the config.initialData document. I don;t see any details

**Comment by sergiodxa** [comment]
@pawan52tiwari you can read it https://react-query.tanstack.com/docs/guides/initial-query-data
