### ISSUE TITLE
TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by nikoisonfire** [tannerlinsley/react-query#591]
Im using Firebase in my Query function with a custom Promise

When i click on the query in the React Query Console , it throws this error:
![image](https://user-images.githubusercontent.com/22169321/85011199-81739080-b161-11ea-8dce-e50e44c4bfe3.png)

code: 
![image](https://user-images.githubusercontent.com/22169321/85011249-8b958f00-b161-11ea-91a4-472f34b9f7bc.png)

I have a nearly identical queryFn in another component, and it dosent throw the error if i use the RQ Console there.

**Comment by tannerlinsley** [comment]
This is because your data that you are caching contains a circular reference. Unfortunately you would need to remove this  to use the dev tools right now. And honestly I don’t think you would necessarily want the circular reference anyway. They can cause issues with caching and storage.

**Comment by nikoisonfire** [comment]
Thanks for the comment, Tanner! 

Meanwhile i found out the glitch in the matrix. If you encounter the same bug, this might help:

**Look for parameters, variable declarations, loops etc. that might use the same name as elements from the _useQuery-Hook_ (data, error, etc.) ANYWHERE in that component (one other time i had the problem with using identical variable names in queryFn Tags)**

my rather silly mistake
```
render(
....
{
data.map(
data => ... 
)
}
);
```

**Comment by bloodykheeng** [comment]
Thanks verry much
