### ISSUE TITLE
Inconsistencies in getQueryData

### ISSUE THREAD

**Issue by Ayc0** [tannerlinsley/react-query#599]
**Describe the bug**

When defining a query with `useQuery([mainKey, subKey], fetcher)`, both of those calls return `undefined`:
- `queryCache.getQueryData(mainKey)`
- `queryCache.getQueryData([mainKey])`

But `queryCache.getQueries(mainKey /* [mainKey] */)` works as expected.

However, if we remove `subKey` from useQuery, it works again.

**To Reproduce**

1. Go to https://codesandbox.io/s/amazing-currying-z0ls8
2. Click on any item in the list
3. Open the console
4. You can see that the 1st line is `undefined` instead of `[{ ... }]`

**Expected behavior**

`queryCache.getQueries` shouldn't return undefined with partial key match.

**Screenshots**

![image](https://user-images.githubusercontent.com/22725671/85299972-45fcfd00-b4a6-11ea-9392-e8ee264fc506.png)

**Comment by tannerlinsley** [comment]
So you would expect it to return an array of all matching queries’ data? Eg, [data, data, data]

**Comment by Ayc0** [comment]
yes, as described in `refetchQueries`, if we only have a partial match, every query that matches this pattern should be matched. Otherwise we should provide the `exact: true` parameter

I'd expect all of those to have the same behavior and the same API

**Comment by Ayc0** [comment]
i don't know if this is a bug or the wanted API for `getQueryData`
if this is a bug, I can take a look if you want

**Comment by tannerlinsley** [comment]
Hmmm, sounds like we need to make the docs better. Anything with the pluralized form of query (somethingQueries) supports partial matching, and anything in the singular form does not (somethingQuery).

**Comment by tannerlinsley** [comment]
Open to accepting any PRs to make this more clear. Thanks!
