### ISSUE TITLE
Exception if variables are undefined

### ISSUE THREAD

**Issue by john-pc** [tannerlinsley/react-query#6]
If there are no variables defined so it throws an exception.
In order to overcome this error i just pass "variables: {}" to all useQuery functions that i use

**Comment by tannerlinsley** [comment]
Could you screenshot the exception and stack trace please?

**Comment by john-pc** [comment]
Noticed that it only happens when i not providing an object as the second parameter 

![Screen Shot 2019-10-03 at 17 12 53](https://user-images.githubusercontent.com/44257941/66134557-2add1b00-e601-11e9-96e7-9bcf52072cd9.png)

**Comment by tannerlinsley** [comment]
Should be an easy fix :) Thanks!

**Comment by tannerlinsley** [comment]
Fixed!

**Comment by JaceHensley** [comment]
This seems to be an issue again, but it's `_ref11` now (same function)

**Comment by tannerlinsley** [comment]
Currently working on the next major version. This will be fixed (actually the code causing this error won't even be in the library any more 😄) Stay tuned!
