### ISSUE TITLE
Pause interval refreshing when page is backgrounded

### ISSUE THREAD

**Issue by camflan** [tannerlinsley/react-query#60]
Is there a setting that will let us suspend interval updates once the page is backgrounded, and then resume when it's regained focus?

**Comment by tannerlinsley** [comment]
Just released version 0.3.20, in which queries will no longer automatically attempt to refetch in the background when using `refetchInterval`. If you want the query to refetch while in the background, there is now a query config option called `refetchIntervalInBackground` that you can set to `true`.
