### ISSUE TITLE
setQueryData doesn't update the cache

### ISSUE THREAD

**Issue by cdaringe** [tannerlinsley/react-query#610]
**Describe the bug**

`cache.setQueryData(['todos'], [1,2,3])` doesn't update the cache.

**To Reproduce**

```js
// from node
const { makeQueryCache } = require("react-query")
const cache = makeQueryCache()
cache.setQueryData(['todos'], [1,2,3])
console.log(cache.queries) // {}, not { "'[todos]'": [1,2,3] }
```

**Expected behavior**

- `cache` to be updated

**Screenshots**

n/a

**Additional context**

while debugging, i found this little tid-bit:

```js
if (query.queryHash) {
  if (!isServer) {
    cache.queries[queryHash] = query
    // Here, we setTimeout so as to not trigger
    // any setState's in parent components in the
    // middle of the render phase.
    setTimeout(() => {
      notifyGlobalListeners()
    })
  }
}
```

this line intentionally blocks me updating my cache. i am trying to update the cache such that i can write it to my HTML document on SSR, and re-hydrate my cache after SSR.

thanks for the cool lib and support!

**Comment by tannerlinsley** [comment]
@Ephem  what do you make of this?

**Comment by Ephem** [comment]
In the current version of React Query this is by intent, no caching at all is allowed server side to avoid leaking sensitive information between requests.

That said, this is solved in the `next`-branch! In v2 any cache explicitly created with `makeQueryCache` will have working caching on the server. You can already try this in the `next` release channel.

There will also be an official solution for SSR-hydration with docs and examples. That part has not been implemented just yet, but isn't far away so stay tuned. :smile:

**Comment by Ephem** [comment]
Im on vacation and a bit out of the loop, v2 is released so try that and see if the issue is fixed! :tada:

**Comment by tannerlinsley** [comment]
Bingo! In v2, this is fixed. Thanks Ephem!
