### ISSUE TITLE
Error not thrown when using suspense and error boundary

### ISSUE THREAD

**Issue by PepijnSenders** [tannerlinsley/react-query#614]
**Describe the bug**

When you throw an error in the fetcher it's not handled. React-query does a couple of retries, but the error is never shown and it stays in the loading state.

**To Reproduce**

I added a `throw new Error()` in the example sandbox for using suspense and error boundary: https://codesandbox.io/s/pensive-cherry-wl42m Check queries.js

**Expected behavior**
The error should pop up in the ErrorBoundary.

**Comment by tannerlinsley** [comment]
When using the suspense example, all works as expected. Even if I throw an error inside one of the fetcher functions:

<img width="1012" alt="Screen Shot 2020-06-24 at 10 24 37 AM" src="https://user-images.githubusercontent.com/5580297/85594220-f84ad680-b604-11ea-9984-98ab3bc7beea.png">

**Comment by tannerlinsley** [comment]
If you could please replicate this in a codesandbox, that would be great.

**Comment by PepijnSenders** [comment]
That's not the expected error though, or is it? It needs to be `new Error('test')`

**Comment by PepijnSenders** [comment]
Did you check my sandbox @tannerlinsley ? This one definitely swallows the error:

https://wl42m.csb.app/
https://codesandbox.io/s/pensive-cherry-wl42m

<img width="579" alt="Screen Shot 2020-06-24 at 18 29 40" src="https://user-images.githubusercontent.com/2052659/85594936-afb50c80-b648-11ea-84bb-9a5ec2a71a89.png">

**Comment by tannerlinsley** [comment]
Okay, this was definitely a bug. And now, we have a new API feature! Please check out the fix and new API here: 4c741f74994a3d8f87f229e4fb313736616600a0
