### ISSUE TITLE
Suspense stopped working after update to 2.0.3.

### ISSUE THREAD

**Issue by nikoisonfire** [tannerlinsley/react-query#615]
I've just updated to 2.0.3. and suspense mode seemed to stop working.

I'm getting `undefined` for `data` properties on every page + no fallback rendered.

![image](https://user-images.githubusercontent.com/22169321/85546201-f2f98600-b61c-11ea-94ab-5fd6ef2fbd83.png)

FYI
```
"react-dom": "^16.13.1"
"react": "^16.13.1"
```

![image](https://user-images.githubusercontent.com/22169321/85547797-8aaba400-b61e-11ea-9629-804846e180d2.png)

**Comment by PepijnSenders** [comment]
I think this is related to my issue: https://github.com/tannerlinsley/react-query/issues/614. For some reason it doesn't catch errors in the fetcher anymore. If you put a try/catch around your fetcher you'll see the actual error.

**Comment by tannerlinsley** [comment]
Let's track this in #615, instead of two places. If you could please make a codesandbox that shows this error happening, that would be great.

**Comment by tannerlinsley** [comment]
Also see this comment: https://github.com/tannerlinsley/react-query/issues/614#issuecomment-648924718

**Comment by nikoisonfire** [comment]
Unfortunately I cannot replicate this in a codesandbox, because I am using Firebase / Firestore with domain restriction as my API.

Here's an example code that renders unsuspended, therefore causing data props not found.

What's bugging me: this works perfectly in version `"react-query": "^1.5.9"` until I updated. 

I'd rather not add the ? to every use of data object, because then I would just not use suspend and work with the loading parameter as this is less hassle... 

```
const getPosts = (key, postId) => {
        return new Promise((resolve, reject) => {
            firebase.getNewestPosts().then(
                snapshot => {
                    let posts = [];
                    snapshot.forEach(
                        doc => posts.push({...doc.data(), id: doc.id})
                    );
                    return resolve(posts);
                }
            ).catch(
                error => reject(error)
            );
        });
    };
    const {data, error} = useQuery('newestPosts', getPosts);
```

**Comment by tannerlinsley** [comment]
This should be fixed now. Please see the latest release notes!
