### ISSUE TITLE
Pass though queryKey on useQuery

### ISSUE THREAD

**Issue by jimthedev** [tannerlinsley/react-query#62]
Hi @tannerlinsley,

One thing that would be nice is to return the queryKey on the object returned from the useQuery hook.

Would you consider this?

**Comment by tannerlinsley** [comment]
What is your use case?

Tanner Linsley

**Comment by tannerlinsley** [comment]
Please reopen with a use case and we can discuss more :)

**Comment by jimthedev** [comment]
Hey sorry, been running around a bit. 

Anyhow, the use case is for someone who is creating a redistributable subey'ed queries in redistributable custom hooks. We want to return the final key so that it can be used for refetching. It is totally an optimization, pure and simple:

this works:

```js

// definition
function useMyCustomHook (subkey) {
  const queryKey="apple" + subkey;
  return {
   queryKey,
    ...useQuery(queryKey);
}

// usage
const { queryKey } = useMyCustomHook('banana')
```

but this would be preferable: 

```js

// definition
function useMyCustomHook (subkey) {
  return useQuery('apple'+subkey)
}

// usage
const { queryKey } = useMyCustomHook('banana')
```

Cheers.

**Comment by jimthedev** [comment]
@tannerlinsley Looks like I could open a new issue or you can open this one, whatever you prefer. Didn't want to dupe the issues board if you decide this isn't something you'd want.
