### ISSUE TITLE
still fetches when { manual: true } 

### ISSUE THREAD

**Issue by wolverineks** [tannerlinsley/react-query#621]
**Describe the bug**
setting `{ manual: true }` doesnt prevent fetching

**To Reproduce**
https://codesandbox.io/s/react-query-manual-bug-7m6j9

switch between versions of `react-query`
v1 doesnt fetch posts
v2 fetches posts

**Expected behavior**
same behavior

**Comment by pokorson** [comment]
@wolverineks did you figure it out? Working on 1 -> 2 upgrade right now and encountered the same issue. Couldn't find any mention on that in release notes

**Comment by wolverineks** [comment]
Option was changed to `{ enabled: boolean }`

**Comment by pokorson** [comment]
can I have `{ enabled: false }` and still call `refetch` ? or it will get suppressed?

**Comment by tannerlinsley** [comment]
`refetch` will bypass `enabled` and always refetch

**Comment by pokorson** [comment]
@tannerlinsley small suggestion - if you can still edit release note for 2.0, might be good to mention `manual` prop explicitly. What I've tried first was to `cmd + f` for this string. Also it wasn't obvious to me that `enabled` replaces `manual`
