### ISSUE TITLE
Console.error when API fails

### ISSUE THREAD

**Issue by ninobc** [tannerlinsley/react-query#622]
**Describe the bug**
In both `useQuery` and `useMutation`, whenever the API that has been passed to them fails, it results in a console.error which would then appear on screen. Also, when the mutation API fails, it crashes the app entirely and the error can't be caught, even if calling the mutation within a try/catch block as mentioned in the docs.

**Additional context**
using it in a react native app.

**Comment by tannerlinsley** [comment]
When using in React Native, you'll need to override the Logger, otherwise, it will cause redboxing all over the place.

```js
import { setConsole } from 'react-query'

setConsole({
  log: console.log,
  warn: console.log,
  error: console.log,
})
```
