### ISSUE TITLE
when { enabled: false }, isFetching === true

### ISSUE THREAD

**Issue by wolverineks** [tannerlinsley/react-query#624]
**Describe the bug**
when `{ enabled: false }`, `isFetching === true`

**To Reproduce**
https://codesandbox.io/s/react-query-bugs-7m6j9

**Expected behavior**
when `{ enabled: false }`, `isFetching === false`

**Comment by Haqverdi** [comment]
use ```isLoading``` instead

```
const { isLoading } = query()
```

**Comment by wolverineks** [comment]
is this intended behavior?

**Comment by gornyyvladimir** [comment]
From docs:

> isFetching: boolean
Defaults to true so long as enabled is set to false

But behavior after this issue: 

> Defaults to false

@tannerlinsley which behavior is correct for this case? Is it a bug in docs? 
https://react-query.tanstack.com/reference/useQuery
