### ISSUE TITLE
onSuccess (and other hooks) not fired for multiple queries sharing a key first time

### ISSUE THREAD

**Issue by benswinburne** [tannerlinsley/react-query#629]
**Describe the bug**
If two components `useQuery()` with the same key and render at the same time, as expected the `queryFn` fires once. However, the `onSuccess` function does not fire for both components on the first render.

**To Reproduce**
1. Go to https://codesandbox.io/s/modest-leavitt-l5ij2?file=/src/App.js
2. Open the console then refresh the sandbox browser (for first render again)
3. Observe console and see one todo shown (from component one).
4. Click button to invalidate todo cache (or force window refetch etc)
5. See the onSuccess function fire for both components and console log two todos.

**Expected behavior**
The query should only run once to get the data as the key is the same but each use of useQuery should still fire its own `onSuccess` methods (I've also tried with `onSettled`).

**Desktop (please complete the following information):**
 - OS: OSX Catalina 10.15.3
 - Browser Chrome
 - Version Version 83.0.4103.106 (Official Build) (64-bit)

**Comment by benswinburne** [comment]
@tannerlinsley commit a05cb50 appears to just commit my bad codesandbox example to the repo. Presumably that was unintentional?

**Comment by tannerlinsley** [comment]
Yeah bad staging in my part. It’s fixed now :)

**Comment by benswinburne** [comment]
Nice one thanks so much for the speedy fix! Can confirm that it works as expected now.

Thanks again
