### ISSUE TITLE
[Feature Request] useClearQueryCache Hook

### ISSUE THREAD

**Issue by JaceHensley** [tannerlinsley/react-query#63]
Hey, I just thought it'd be nice to have a hook to clear the query cache.

I think it would just be:

```js
const useClearQueryCache = () => {
  useEffect(() => {
    clearQueryCache()
  })
}
```

**Comment by tannerlinsley** [comment]
Seems simple enough to do on your own if you need to. I don’t think we need to add those kbs to the lib for that.

**Comment by JaceHensley** [comment]
Fair enough :)
