### ISSUE TITLE
Type definitions in react-query v2.2.3 are not loaded.

### ISSUE THREAD

**Issue by toshi1127** [tannerlinsley/react-query#634]
**Describe the bug**
Type definitions in react-query v2.2.3 are not loaded.

**To Reproduce**
1. Creating a project with typescript. 
`npx create-react-app react-ts-app --typescript`
2. Change Project.
`cd react-ts-app`
3. Install react-query v2.2.3
`yarn add react-query`
4. Import useQuery from react-query in App.tsx(`@types/react-query` is not supported for v2.23)
![image](https://user-images.githubusercontent.com/32378535/85738948-62fe2e00-b73b-11ea-8e4b-0536e5c3d187.png)

**Additional context**
v2.2.3 type definition exists in `react-query/types`, move `types/index.d.ts` to root Then we would be able to load the type definition file.
Or is it possible to update `@types/react-query`?

**Comment by ghostd** [comment]
For now the types are obsolete. There is a work in progress to update them: #626

**Comment by toshi1127** [comment]
Sorry I didn't notice that, thank you so much!
