### ISSUE TITLE
Disabled query gets called anyway by the refetch feature

### ISSUE THREAD

**Issue by GuillaumeSpera** [tannerlinsley/react-query#635]
**Describe the bug**
I have some disabled queries awaiting for some change on my components.
And even if the value doesn't change, the queryFn is called at each refetchInterval.

**To Reproduce**
```
const [neverUpdatedValue] = React.useState(null);
useQuery({
    queryKey: ["test", neverUpdatedValue],
    queryFn: (key, value) => {
        console.log(key, value);
        return Promise.resolve();
    },
    config: {
        enabled: !!neverUpdatedValue,
        refetchInterval: 2000
    }
});
```
I set up a sandbox derived from your "Basic" example :
https://codesandbox.io/s/busy-moon-pon1t?file=/src/index.js

The refretchInterval triggers the queryFn even if it is disabled.

**Expected behavior**
Do not trigger the queryFn.

**Desktop (please complete the following information):**
 - Version 2.2.3

**Comment by bishwenduk029** [comment]
@tannerlinsley , Can you please guide me, I would love to work on this to fix if this is an issue? If you could help me how to approach I can start looking into it. Thank You.

**Comment by tannerlinsley** [comment]
Yeah sure. [This line here](https://github.com/tannerlinsley/react-query/blob/master/src/core/queryCache.js#L397) would need an extra check before running anything that there is *at least* one query that is enabled (`instance.config.enabled`).

**Comment by GuillaumeSpera** [comment]
Still isn't fixed in the released version mentionned above.
https://codesandbox.io/s/sad-roentgen-8g0yc?file=/src/index.js
The issue #648 probably reports the same problem.

**Comment by tannerlinsley** [comment]
Just released a fix again. 👍

**Comment by qwen-3108** [comment]
Here to offer a different voice. I find the ability to imperatively refetch disabled queries with `queryClient.refetchQueries` very useful (since I can refetch multiple disabled queries with `refetchQueries`, but not with the returned `refetch` method) 

Would rather not have this behavior removed

Also thanks @tannerlinsley  for the awesome library. It's a breeze to finally be able to ditch Redux for remote state management
