### ISSUE TITLE
Latest version of 'retry' no longer includes error

### ISSUE THREAD

**Issue by onionhammer** [tannerlinsley/react-query#638]
Just tried out upgrading to 2.4.0, and I see now that I can no longer check the error before retrying?

This was my logic

```ts
const queryConfig: ReactQueryProviderConfig<any> = {
    refetchOnWindowFocus: false,
    suspense: true,
    retry: (failures, err) => {
        if ("status" in err && err.status === 401)
            return false;
        else
            return failures < 5;
    }
};
```

Not sure how I would reproduce this with the new API, since the `onError` expects `void`, `retryDelay` does not give an error, and retry no longer takes a function.

**Comment by tannerlinsley** [comment]
Is this a types restriction, or have you tried this without types?

**Comment by onionhammer** [comment]
@tannerlinsley If I add in a ts-expect-error it compiles, but no longer works, the 'retry' function is no longer invoked in the newest version of react-query

```ts
const queryConfig: ReactQueryProviderConfig = {
    refetchOnWindowFocus: false,
    suspense: true,
    // @ts-expect-error
    retry: (failures, err) => {
        if ("status" in err && err.status === 401)
            return false;
        else
            return failures < 5;
    }
};
```

**Comment by bugzpodder** [comment]
@onionhammer  I thought it was (note queries part):
```
queryConfig = {
  queries: {
    retry: (failures, err) => ...
  }
}
```

**Comment by tannerlinsley** [comment]
That’s for your global config. If you are configuring at the query level, you don’t need to nest everything inside of the queries object

**Comment by tannerlinsley** [comment]
I can't replicate this, so it may just be an outdated types issue. Please reopen with more info if you'd like.

**Comment by onionhammer** [comment]
@tannerlinsley thanks for looking into it, I resolved this by removing any reference to @types/react-query. Looks like the combination of the latest version and the old type definition were causing this
