### ISSUE TITLE
`query.error` is reset to null when using refetchInterval option

### ISSUE THREAD

**Issue by cherniavskii** [tannerlinsley/react-query#64]
HI,
I've used `react-query` for polling request and noticed weird behavior.

### Expect behavior:

When request fails, `query.error` shouldn't be reset `null` until request succeed.

### Current behavior:

When request fails, `query.error` value is constantly switching between `null` and request error value

### Steps to reproduce:

- open https://codesandbox.io/s/nostalgic-swirles-q4unq
- see console output

I will debug it and keep this issue updated if I'll get more info

**Comment by tannerlinsley** [comment]
I think what happens Is that when a query is fetched (regardless) of cause, the error is set to null. This may not be right.

https://github.com/tannerlinsley/react-query/blob/master/src/index.js#L258

Tanner Linsley

**Comment by cherniavskii** [comment]
Yes, indeed.
I'll submit a PR.

BTW, looks like the source code in the repo is outdated comparing to NPM releases.
Can you update it?

Also, it would be great if you update [Github Releases](https://help.github.com/en/github/administering-a-repository/about-releases) as well - this way users can subscribe to new releases and be notified when new release is out!

Let me know if I can help with something!

**Comment by cherniavskii** [comment]
Not sure if you noticed my previous comment, so adding mention @tannerlinsley
https://github.com/tannerlinsley/react-query/issues/64#issuecomment-562990605

**Comment by tannerlinsley** [comment]
Yep. I’m away from my computer right now. I’ll update and release soon

**Comment by cherniavskii** [comment]
@tannerlinsley Thanks!
