### ISSUE TITLE
[v2] stuck on isLoading when I setQueryData for initial load

### ISSUE THREAD

**Issue by huchenme** [tannerlinsley/react-query#649]
**Describe the bug**

For my app, as the initial data was saved in local storage, I do not wish to make network call and show spinner. After upgrade to v2, I noticed that the app stuck at `isLoading` equal to true
https://codesandbox.io/s/react-query-2-setquerydata-18k47

**To Reproduce**
1. Go to https://codesandbox.io/s/react-query-2-setquerydata-18k47
2. See the screen stuck at "Loading..." (you might need to click the browser refresh on the right panel)

**Expected behavior**
It should load the data in `queryCache`

**Screenshots**
![image](https://user-images.githubusercontent.com/2078389/85949842-9df6a080-b98b-11ea-88c3-e2e8eda0cb41.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]: macOs catalina
 - Browser [e.g. chrome, safari]: chrome
 - Version [e.g. 22]: 83

**Additional context**
I tried another approach using `initialData`, but it is not working as expected as well: https://github.com/tannerlinsley/react-query/issues/650

**Comment by tannerlinsley** [comment]
I think this is what you're looking to do: https://codesandbox.io/s/react-query-2-setquerydata-5765w?file=/src/index.js
