### ISSUE TITLE
[v2] initialData does not work if query is dynamic 

### ISSUE THREAD

**Issue by huchenme** [tannerlinsley/react-query#650]
**Describe the bug**

For my app, as the initial data was saved in local storage, I do not wish to make network call and show spinner. After upgrade to v2, I noticed that the app stuck at `isLoading` equal to true
https://codesandbox.io/s/react-query-2-initialdata-k1gpk

**To Reproduce**
1. Go to https://codesandbox.io/s/react-query-2-initialdata-k1gpk
2. Change the dropdown to "weekly"
2. Change the dropdown to "monthly"

**Expected behavior**
It should load the data in for weekly and monthly

**Actual behavior**
Data does not change

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]: macOs catalina
 - Browser [e.g. chrome, safari]: chrome
 - Version [e.g. 22]: 83

**Additional context**
I tried another approach using `setQueryData`, it was working in v1, issue here: https://github.com/tannerlinsley/react-query/issues/649

**Comment by tannerlinsley** [comment]
Please see my response in #649
