### ISSUE TITLE
queries retrying even though option is set to false

### ISSUE THREAD

**Issue by alexandernanberg** [tannerlinsley/react-query#652]
**Describe the bug**

While upgrading to v2 I noticed that some tests broke because `useQuery` does no longer use the config from the provider when you prefetch.

**To Reproduce**

1. Go to https://codesandbox.io/s/sweet-resonance-zu0em?file=/src/App.js
2. Check the console
4. See multiple logs from react-query trying to retry even though the option is set to `false`

**Expected behavior**

Queries does not retry if option is set to `false`

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by otaciliolacerda** [comment]
The problems seems to be that `prefetchQuery` do not use the context configuration so it is retrying 3 times (default). `useQuery` is working as expected.

**Comment by alexandernanberg** [comment]
Sure, but I wouldn't expect the prefetch to retry by default 🤔 IMO that should be handled by the `useQuery` hook

**Comment by tannerlinsley** [comment]
I would accept a PR to make prefetching default to `retry: false`

**Comment by otaciliolacerda** [comment]
Do you want to change any other defaults in prefetching?
