### ISSUE TITLE
Remove scarf-js malware

### ISSUE THREAD

**Issue by samsch** [tannerlinsley/react-query#676]
This package is infected with the scarf-js malware, the dependency should be removed, and all major versions using it should have patch bumps with the change.

https://github.com/final-form/react-final-form/issues/822

**Comment by tannerlinsley** [comment]
I can see you’ve been busy, trying for whatever reason to label scarf as malware in like 5 other repos. It seems you don’t really understand it’s origins or what it even does. 

Let me set this straight, scarf is not malware.

It’s an analytics package that is gdrp compliant out of the box, collects install counts, version counts, and publicly linkable company information at dev-install time (and nothing else) and reports that information to a dashboard that only Maintainers have access to.

By definition, is not even close to malware, nor does it have any more malicious capability on your machine that any other npm library you install every day.

Now, that said, if you really wish that Maintainers personally don’t see your company’s name and website on internal lists of users, then just opt out.

If you choose not to opt out for whatever reason, and you just have some issue with my personal choice to include analytics in these libraries that Are distributed to you for free... then sure. Fork it, change it, get yourself stuck. It’s open source after all.

But for heavens sake, get your terms right. Usages analytics is nothing even close to your “malware” claims.

**Comment by tannerlinsley** [comment]
More to say on this matter over at the issue above, but I'll extract one of my comments here:

> It looks like this will just come down to maintainer's choice on if they consider an associated company name, website, and install count sensitive data. Clearly, this specific project belongs to @erikras, so that decision is up to him. Personally, I have been able to use scarf to reach out to companies that use my libraries and offer support, consultation, and sometimes facilitate a sponsorship to help fund my open source work. For now, I think I can say that as long as scarf isn't doing anything illegal, mishandling personally identifiable data, or causing harm to my users, I will continue to use it to help fund my open source work. It has ultimately done zero harm to my users and allows them to keep using a library that is well-maintained.

**Comment by tannerlinsley** [comment]
The scarf-js maintainer also offered even more insight to the discussion [here](https://github.com/final-form/react-final-form/issues/822#issuecomment-651920379).

**Comment by tannerlinsley** [comment]
Scarf has been removed from all of my libraries following a more granular discussion in the Reactiflux Discord.

**Comment by samsch** [comment]
Oof, sorry, I forgot linking other issues into here would spam.
