### ISSUE TITLE
Pull cached data?

### ISSUE THREAD

**Issue by minipai** [tannerlinsley/react-query#68]
Hey Tanner, thank you for another amazing library.

Is there a way to pull cached data to use in a component?

For example, I know "users" data is loaded when my App is started, and won't change.
So I know I can just pull the data from the cache when I need it.

Now I cache the data myself in context.

**Comment by tannerlinsley** [comment]
Technically you could set initialData to your data and then set the staleTime to something ridiculous. Then your data will never refresh and always pull from the cache.

**Comment by minipai** [comment]
Looks like I can use `manual: true`.
