### ISSUE TITLE
[Typescript] Type error when using useInfiniteQuery hook

### ISSUE THREAD

**Issue by AleVul** [tannerlinsley/react-query#709]
**Describe the bug**
Attempting to use useInfiniteQuery with ts throws a type error related to query function

**To Reproduce**
See this [codesandbox](https://codesandbox.io/s/priceless-newton-6kfdd)

**Expected behavior**
To not fail type check

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Pop!_OS 20.04 LTS
 - Browser: chrome
 - Version: 83.0.4103.116

**Additional context**
Using ts version 3.9.4 and react-query 2.4.13

**Comment by nucleartux** [comment]
Second parameter should be optional in your example.
So replace it to `something?: number` and everything will be fine.

**Comment by AleVul** [comment]
Thank you, i still get errors related to type, even after making optional, i'll investigate more and get back here with a comment

**Comment by AleVul** [comment]
For some reason the codesandbox version work just fine, i assume differences in ts version or configuration. Anyway ended up using a type guard and an union with `unknown` to second argument to the query function.

**Comment by MichaelDeBoey** [comment]
Is this still a valid problem now #767 is merged? 🤔

**Comment by tannerlinsley** [comment]
It's likely that this will be fixed, and if not, I'm fine letting it get opened again, but for now, I'll consider this stale.
