### ISSUE TITLE
queryInstance.clearInterval() is not called on Unmount

### ISSUE THREAD

**Issue by johnsetzer** [tannerlinsley/react-query#711]
When a component unmounts `queryInstance.unsubscribe()` tries to clear intervals here:
https://github.com/tannerlinsley/react-query/blob/master/src/core/queryInstance.js#L73
Note that `query.instances.length===0`

BUG:
`query.clearIntervals()` does no clear any intervals because the array it iterates over is empty.
https://github.com/tannerlinsley/react-query/blob/master/src/core/query.js#L138

**Comment by tannerlinsley** [comment]
Well shoot dang! Looks like we need to change that. If you want to make a PR, it could be this:

```diff
   if (!query.instances.length) {
-      query.clearIntervals()
+      instance.clearInterval()
      query.cancel()

      if (!isServer) {
        // Schedule garbage collection
        query.scheduleGarbageCollection()
      }
    }
```
