### ISSUE TITLE
Docs website can't be reached

### ISSUE THREAD

**Issue by nathanqueija** [tannerlinsley/react-query#724]
**Describe the bug**
Hi there. It looks like the server where the documentation is hosted is down.
I checked the docs folder and it looks like nextjs is being used. Maybe Node is having a hard time and the docs are down.
Just wanted to let you know and let me know if I can do something to help.

**To Reproduce**
1. Go to https://react-query.tanstack.com/

**Expected behavior**
The docs should open, but the server can't be reached.

**Screenshots**
![image](https://user-images.githubusercontent.com/8295374/87012499-a6d84500-c1c9-11ea-956f-ad4663e77843.png)

**Comment by rtpm** [comment]
Not having problems with docs site at the moment.

**Comment by tannerlinsley** [comment]
Hosted on Vercel. Working great.
