### ISSUE TITLE
no refetch with suspense since 0.3.17

### ISSUE THREAD

**Issue by hyperivo** [tannerlinsley/react-query#73]
I've updated my dependencies and the fetching behaviour is different. In my app, whenever I now navigate to a page I was previously at, there is no refetch if I use suspense.

The same happens in the suspense codesandbox examples, please notice the network requests as I click the button:

0.3.21 without suspense:
![0321-no-suspense](https://user-images.githubusercontent.com/23730364/70463186-51fa1200-1ab4-11ea-9add-5f8b37ec5311.gif)

0.3.21 with suspense:
![0321-suspense](https://user-images.githubusercontent.com/23730364/70463262-7950df00-1ab4-11ea-8ddf-175619801cc0.gif)

0.3.16 with suspense:
![0316-suspense](https://user-images.githubusercontent.com/23730364/70463350-a8ffe700-1ab4-11ea-8b4f-de2c4a7dc7a1.gif)

**Comment by tannerlinsley** [comment]
Yep, looks like a bug. I'll dig into this later today.

**Comment by tannerlinsley** [comment]
This should be fixed with 0.3.23
