### ISSUE TITLE
Confusing behavior (or bug) with suspense + enabled flag

### ISSUE THREAD

**Issue by flybayer** [tannerlinsley/react-query#744]
**Describe the bug**

In an Next.js/Blitz app, the first render always has empty route parameters during static pre-rendering. This pre-render should render the Suspense loading fallback. This loading fallback does work properly if you leave `useQuery` enabled.

But the problem is that in suspense mode, you want the query to be disabled (so it doesn't query an API with empty data) while at the same time also rendering the loading fallback.

In `2.4.14`, `enabled: false` will not trigger the suspense loading fallback.

For example, we have code similar to this:

```ts
export const Project = () => {
  const projectId = useParam("projectId", "number")
  const stuff = useQuery(['project', projectId], queryFn, { suspense: true, enabled: !!projectId })

  // ...
```

Maybe there's some other existing react-query config combo to get this behavior?

**Comment by marcosvega91** [comment]
I think that the configuration is correct and this behaviour is strange, there is a test case for this [here](https://github.com/tannerlinsley/react-query/blob/cee6175ee27166dc0c43c52a91707efa32f3b517/src/react/tests/suspense.test.js#L156)

I have created also a  working case [here](https://codesandbox.io/s/exciting-haibt-qr2k1?file=/src/Page.js)

**Comment by flybayer** [comment]
@marcosvega91 the problem is that I need a way to have `enabled:false` **and** have show the suspense loading fallback. This is for Next.js pre-rendering which needs to render the loading screen but without making an actual query.

Your example demonstrates this. The loading fallback only shows when enabled is true.

**Comment by tannerlinsley** [comment]
Workaround for this would be to pass a never resolving promise function on the server that won’t call your api but will trigger the suspense boundary.

**Comment by flybayer** [comment]
My current workaround in Next.js & Blitz is to use the below hook to detect pre-render mode. If in pre-render, then I use a never resolving promise as the query function. Otherwise use the real data fetching function.

```tsx
export const useIsDevPrerender = () => {
  const router = useRouter()
  if (process.env.NODE_ENV === "production") {
    return false
  } else {
    const currentRouteHasParameters = /\[.*\]/.test(router.pathname)
    const queryKeys = Object.keys(router.query)
    // This checks if query == {} || query == {amp: any}
    const queryIsEmpty =
      queryKeys.length === 0 || (queryKeys.length === 1 && queryKeys[0] === "amp")
    const isDevPrerender = currentRouteHasParameters && queryIsEmpty
    return isDevPrerender
  }
}
```

**Comment by tannerlinsley** [comment]
Interesting. Yeah, this seems like a good enough workaround. Until it becomes a massive issue for a majority of people. Keep tabs on this experience though and if it gets worse, we can keep working at something more native.

**Comment by flybayer** [comment]
**Update.** That previous hook had some problems (but I forget what lol).

Anyways, I'm now using this instead:

```tsx
const isServer = typeof window === "undefined"

export const useIsDevPrerender = () => {
  if (process.env.NODE_ENV === "production") {
    return false
  } else {
    // useQuery is only for client-side data fetching, so if it's running on the
    // server, it's for pre-render
    return isServer
  }
}
```
