### ISSUE TITLE
Manual query still fetches

### ISSUE THREAD

**Issue by 1saf** [tannerlinsley/react-query#75]
Hi all,

Attempting to have a component which has a manual query. On initial page load it does not poll the server for the query.... however randomly, and I do not know why the query fetches, it seems to be on refocus? I have been unable to pinpoint the source of refetching.

Or is there a use case for manual querying that I could be missing.

I am passing the manual flag to be true

```   
const myQuery = useQuery(
        ['myKey', { key }],
        performQuery,
        { manual: true, staleTime: HOUR_MS },
);
```

is the format I am using.

**Comment by BenMGilman** [comment]
I'm having the exact same issue. What was the fix here which warranted to it being closed?
