### ISSUE TITLE
refetchQueries doesn't work in mutation call

### ISSUE THREAD

**Issue by timrbula** [tannerlinsley/react-query#76]
Based on the [documentation](https://github.com/tannerlinsley/react-query#invalidate-and-refetch-queries-from-mutations), I expected passing the `refetchQueries` key in the second argument object to `mutate` would have refetched the specified queries.
e.g. `mutate(newTodo, { refetchQueries: ["todos"]})`

I am only able to get it to refetch when the key is passed in to the `useMutation` hook. 
e.g. `useMutation(addTodo, { refetchQueries: ["todos"]})`

I've modified the `EditTodo` function in the [default codesandbox app](https://codesandbox.io/s/flamboyant-water-cfph2) to recreate the issue.

Am I doing something wrong, is this a bug or does the documentation just need to be updated a bit to be consistent w/ the other examples?

Awesome library btw. Thanks!

**Comment by tannerlinsley** [comment]
The docs need to be updated, the `refetchQueries` option is only available on the `useMutation` hook, not the mutator that it returns.
