### ISSUE TITLE
doc: config provider missing available props - initialData

### ISSUE THREAD

**Issue by davidnghk01** [tannerlinsley/react-query#761]
**Describe the bug**
The context `ReactQueryConfigProvider` can provide default config for all `useQuery`

And it only accept one params - `config` which is ReactQueryProviderConfig

When i am unit testing, i will prefer make use of the `initialData` feature in order to mocking API response.

So i try following code in my test
```
import { ReactQueryConfigProvider, ReactQueryProviderConfig } from "react-query"
    <ReactQueryConfigProvider
      config={{
        queries: {             initialData: { data: { id: "spaceId1" } } },
      }}
    >
<MyComponentNeedToTest/>
</ReactQueryConfigProvider>
```

**Expected behavior**
above code is working perfectly
But the typescript compiler will complain type error and that method never mention in doc. 

May this is not expected usage ?  If so, what should i do ?

**Comment by tannerlinsley** [comment]
To pass initialData to a query, use the `useQuery` hooks' `initialData` option.
