### ISSUE TITLE
ReactQueryCacheProvider may loose queryCache

### ISSUE THREAD

**Issue by khmm12** [tannerlinsley/react-query#769]
**Describe the bug**
`ReactQueryCacheProvider` creates `queryCache` when it's not defined by developer.  React doesn't give a semantic guarantee ([proof](https://en.reactjs.org/docs/hooks-reference.html#usememo)). It means React may forget previous results and call the factory again, the factory will create a new query-cache instance.

_From: https://github.com/tannerlinsley/react-query/blob/master/src/react/ReactQueryCacheProvider.js_
```js
 const resolvedQueryCache = React.useMemo(
    () => queryCache || makeQueryCache(),
    [queryCache]
  )
```

**Expected behavior**
`ReactQueryCacheProvider` should either to not create anything and notify developer when the property is not defined, or create in safe manner.

```jsx
const resolvedQueryCacheRef = useRef(null)
const previousQueryCacheRef = useRef(queryCache)

if (previousQueryCacheRef.current !== queryCache) {
  previousQueryCacheRef.current = queryCache
  resolvedQueryCacheRef.current = null
}

if (resolvedQueryCacheRef.current === null) {
   resolvedQueryCacheRef.value = queryCache || makeQueryCache()
}
```

or

```jsx
let [resolvedQueryCache, setResolvedQueryCache] = useState(() => queryCache || makeQueryCache())
let [previousQueryCache, setPreviousQueryCache] = useState(queryCache)

if (previousQueryCache !== queryCache) {
   resolvedQueryCache = queryCache || makeQueryCache()
   previousQueryCache = queryCache
   setPreviousQueryCache(queryCache)
   setResolvedQueryCache(resolvedQueryCache)
}
```

or

```jsx
const [resolvedQueryCache, setResolvedQueryCache] = useState(() => queryCache || makeQueryCache())
const previousQueryCacheRef = useRef(queryCache)

useEffect(() => {
   const hasChanged = previousQueryCacheRef.current !== queryCache
   if (!hasChanged) return
   previousQueryCacheRef.current = queryCache
   setResolvedQueryCache(queryCache || makeQueryCache())
}, [queryCache])
```

Depending on your preference, side-effects, number of renders.

**Comment by Ephem** [comment]
Great issue! This is definitely a problem. With the global `queryCache` becoming deprecated in v3 (#772) `ReactQueryCacheProvider` will become required, which makes this issue even more important to get right.

**Comment by jackmellis** [comment]
As of the latest react release I don't believe there is any useMemo garbage collection in place, so this isn't a super urgent bug right now, just something that should be fixed to avoid potential issues at some point in the future. (Yes I did contribute to this bug :disappointed: )

**Comment by rodymolenaar** [comment]
My coworkers actually ran into this problem today. I introduced the `<ReactQueryCacheProvider>` for server side pre-fetching with NextJS and they saw their `useQuery` hooks no longer reacting to `setQueryData()` calls. An easy work-around is creating your own `queryCache` instance with `makeQueryCache()` and passing it to `<ReactQueryCacheProvider>`. I thought this comment might be useful for people running into the same issue.

**Comment by tannerlinsley** [comment]
Looks like good workarounds for this issue are here for those using it in SSR and also with new plans to move to separate client and cache instances (and respective new providers), this should no longer be an issue in the next major version. That said, going to close this issue.
