### ISSUE TITLE
Bug: tanstack link is broken in react query official documentation 

### ISSUE THREAD

**Issue by abdelrahmanahmed** [tannerlinsley/react-query#780]
I opened [react query](https://react-query.tanstack.com/) official documentation, when i navigate to tanstack tab, it responded with **This site can’t be reached**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/8146379/87855844-49579d00-c91b-11ea-85ca-658df991c9ab.png)

**Desktop**
 - OS: Windows
 - Browser Chrome
 - Version: 83.0.4103.116 (64-bit)

**Comment by tannerlinsley** [comment]
This was due to a cloudflare outage.
