### ISSUE TITLE
use with Promise.race

### ISSUE THREAD

**Issue by farshidshahmoradi1996** [tannerlinsley/react-query#782]
**Describe the bug**
Hi there ,I use this awesome in React-Native . but in React-Native axios time out does not work [see this](https://stackoverflow.com/questions/36690451/timeout-feature-in-the-axios-library-is-not-working#:~:text=Let%20say%20you've%20requested,axios%20timeout%20will%20not%20work.).
so I want to implement time out with Promise.race
like this :
![Screenshot from 2020-07-19 21-20-08](https://user-images.githubusercontent.com/37307562/87880266-a62f8200-ca05-11ea-8977-ce41bc2fd914.png)

**Expected behavior**
in 1000 miliseconds set cancel `refetching` and set `isError` to true.
but  this requests take longer time to failed  (when server is down ).
and when use `Promise.race` without `React-Query` that works fine .
Thanks .

**Comment by tannerlinsley** [comment]
React Query automatically retries failed queries 3 times with exponential backoff delay all before it actually marks the query as failed. Try setting the query config with retry: 0
