### ISSUE TITLE
Prefetch example broken

### ISSUE THREAD

**Issue by timdeschryver** [tannerlinsley/react-query#783]
**Describe the bug**

**To Reproduce**
1. Open the example at https://codesandbox.io/s/github/tannerlinsley/react-query/tree/master/examples/prefetching

**Expected behavior**

The example should run.

**Screenshots**

![image](https://user-images.githubusercontent.com/28659384/87881596-a0806f00-c9fa-11ea-8f5d-88c66da82728.png)

**Additional context**

The example doesn't have axios added to its dependencies.
I can create a PR and add it if you want.

**Comment by tannerlinsley** [comment]
A Pr would be great!

**Comment by timdeschryver** [comment]
Oh, I'm too late 😅
Closed by #791
