### ISSUE TITLE
Performance issues?

### ISSUE THREAD

**Issue by bgazzera** [tannerlinsley/react-query#79]
Hi, we are midway through a project which uses react-query for all data-fetching activities. ATM all API calls are mocked using json files imported straight into the data layer of the app.

I started to look at the app's performance and saw a lot of initial CPU usage on the app's intial render, in which I think react-query is using a big part of it. For context, the initial render would be calling a number of times useQuery.

I ran the Chrome profiler and mostly what I see are a number of query.SetState & cleanup calls. I put a logpoint in the line for query.setState and it is being called 110 times, but in the Performance tab I only count 20 that are long enough (8-150 ms) to have a real impact.

![Screen Shot 2019-12-13 at 11 16 07](https://user-images.githubusercontent.com/6751553/70808271-130ed980-1d9e-11ea-8934-ab933926b9fb.jpg)

Just in case, I ran the same performance audit using an incognito session with the production build and saw similar issues. 

I was wondering if anyone has seen something similar and if you had any suggestions (useMemo?).
I'm not 100% sure I'm correctly looking at the data, and I'm happy to help clarify if not. 

Thanks in advance!

**Comment by tannerlinsley** [comment]
I’ll take a look at this ASAP

Tanner Linsley

**Comment by tannerlinsley** [comment]
So clearly operating only off of this image is going to be limiting, but what I can gather is that if `cleanup` is running, that means that you have query functions/getters that are settling (either successfully or failed). Cleanup is just a glorified `finally {}` call:

<img width="377" alt="Screen Shot 2019-12-13 at 2 42 23 PM" src="https://user-images.githubusercontent.com/5580297/70834148-d69ba780-1db6-11ea-9fa4-cedcafa94ee6.png">

As for how much time it's taking for you to initially render, I can't say that I'm experiencing the same thing in any of the examples or in our apps. With that said, it's possible you're experiencing an edge case so more info would be helpful in figuring this out. A codesandbox would be even better that exhibits the problem.

**Comment by tannerlinsley** [comment]
Will gladly continue to diagnose this issue, but we'll need a less opinionated medium (a codesandbox showing the issue would be best) to go forward.
