### ISSUE TITLE
refetchOnWindowFocus triggered by chrome dev tools

### ISSUE THREAD

**Issue by mattcorner** [tannerlinsley/react-query#793]
**Describe the bug**
When "refetchOnWindowFocus" is set to true, all queries are refetched when clicking between Chrome Dev Tools, and the page in question. This is mildly annoying in the scenario where I clear my Network requests list in Chrome Dev Tools, so that I can see what network requests are initiated by a ui interaction, but clicking on the ui results in all react-query requests being refetched.

**To Reproduce**
1. Load any react-app with react-query requests, and refetchOnWindowFocus set to true.
2. Open up chrome dev tools
3. On network tab, clear all network requests.
4. Click to focus on main ui, and all network requests will be re-run.

**Expected behavior**
Would be nice for react-query to ignore windows focus events from chrome dev tools as this improves the developer experience, but would not impact the end-user experience.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Microsoft Edge
 - Version [e.g. 22] Version 84.0.522.40 (Official build) (64-bit)

**Comment by tannerlinsley** [comment]
As far as I know there is no way to detect the source of a window focus event in the browser. I would suggest making a custom dev tools toggle for yourself that turns off the window focus fetching using the ReactQueryConfigProvider
