### ISSUE TITLE
"Was this page helpful" section is broken

### ISSUE THREAD

**Issue by JonathanStoye** [tannerlinsley/react-query#799]
**Describe the bug**
Neither the "thumbs up" nor the "thumbs down" button seem to work in the "Was this page helpful" section of the docs. It seems they are not triggering any network request and are also not changing their state. I know – not highest prio in the world.

**To Reproduce**
1. Go to any page of the docs 'https://react-query.tanstack.com/docs/guides/important-defaults'
2. Scroll down to the "Was this page helpful" section
3. Click on the "yes" or "no" button
4. See, that you don't see anything 🙂 

**Expected behavior**
I guess the state of the button changes and a network request is dispatched to persist this. Also I guess this should be stored locally to prevent multi submission but I guess this is all existing and just waiting to be released but a one-line-fix 🙂 

**Screenshots**
<img width="1323" alt="Screenshot 2020-07-27 at 20 41 46" src="https://user-images.githubusercontent.com/21689428/88579562-84a84900-d04a-11ea-8427-676d00ef3b4f.png">

**Desktop (please complete the following information):**
 - OS: Catalina 10.15.5
 - Browser: Chrome 84.0.4147.89 & Safari 13.1.1

**Comment by tannerlinsley** [comment]
I have external tracking events set up on these buttons. If you would like to see some sort of notification, please feel free to submit a PR!
