### ISSUE TITLE
Use refetch nanually causes error to be displayed in developer mode

### ISSUE THREAD

**Issue by amitripshtos** [tannerlinsley/react-query#80]
Hi!
I had same issue with on focus refetch that I fixed by catching the error, and now I see that refetch doing the same - only on dev mode (red box).

I couldn't find how to fix that on the code and I will appreciate your help.

Thanks,
Amit

**Comment by amitripshtos** [comment]
Same goes when using the fetchInteval - it causing the red box to be triggered.
Maybe we need to do something globally about that.

**Comment by amitripshtos** [comment]
After doing more checking, same goes for mutation function.
Maybe we need to find a way to ignore the errors in development mode?

**Comment by tannerlinsley** [comment]
When you use `refetch` or a mutation function, you must wrap it in a try-catch block. These are asynchronous functions and will trigger redbox's if they are not handled correctly.

**Comment by amitripshtos** [comment]
You are right about refetch and mutation - I will take a look at the README and update if needed.
About fetchInterval, using that code:

`const { data, isLoading, error } = useQuery(['data', { identifier: props.identifier }], getData, { refetchInterval: 3000 });`

After one network call it raises me the exception of getData function.
