### ISSUE TITLE
bug(types): `defaultConfig` for `makeQueryCache` is typed incorrectly

### ISSUE THREAD

**Issue by kamranayub** [tannerlinsley/react-query#806]
**Describe the bug**

I was wondering why the `defaultConfig` wasn't merging correctly with my query configs and it turns out it is just a typing issue.

**To Reproduce**

```
  const testQueryCache = makeQueryCache({
    defaultConfig: {
      queries: {
        refetchOnMount: false,
      },
    },
  });
```

**Expected behavior**

No TS error occurs

**Screenshots**

```
Type '{ queries: { refetchOnMount: false; }; }' is not assignable to type 'BaseQueryOptions<unknown, Error>'.
  Object literal may only specify known properties, and 'queries' does not exist in type 'BaseQueryOptions<unknown, Error>'.ts(2322)
```

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kamranayub** [comment]
I will try to submit a PR to fix this momentarily

**Comment by MichaelDeBoey** [comment]
Is this still a valid problem now #767 is merged? 🤔

**Comment by kamranayub** [comment]
I'll have to check!

**Comment by kamranayub** [comment]
@MichaelDeBoey It's still an issue in terms of publicly consuming the package right now (as the types resolve to `types/index.d.ts`). It won't be an issue once the package generates a `.d.ts` file from the source I think.

**Comment by MichaelDeBoey** [comment]
@kamranayub What I meant was if this is still valid when you install `react-query@tsnext`?

**Comment by kamranayub** [comment]
@MichaelDeBoey Ah, didn't catch there's a tagged package, will try that!

**Comment by kamranayub** [comment]
@MichaelDeBoey Works fine with `tsnext` typings!

![image](https://user-images.githubusercontent.com/563819/89039410-a124d980-d307-11ea-8530-6a69355dc749.png)
