### ISSUE TITLE
[Types] useMutation returning union undefined with new types?

### ISSUE THREAD

**Issue by Buuntu** [tannerlinsley/react-query#810]
**Describe the bug**
Mutate now potentially returns an undefined type, which is different from the return type before I believe?  Maybe that's the expected behavior but by looking at the docs you generally aren't checking that something is returned.  Shouldn't it just throw an error rather than return undefined if something goes wrong?

So using the new types you now have to check that the data exists before using it.

Before
```jsx
const [mutate] = useMutation(mutateFunction);

try {
  const data = await mutate();
  // do something
} catch (err) {
// error handling
}
```

After:
```jsx
const [mutate] = useMutation(mutateFunction);

try {
  const data = await mutate();
  if (data) {
    // do something
  }
} catch (err) {
// error handling
}
```

There might be a good reason for this but it does deviate from the docs (https://react-query.tanstack.com/docs/guides/mutations#basic-mutations) and previous types.

**Comment by MichaelDeBoey** [comment]
Is this still a valid problem now #767 is merged? 🤔

**Comment by Buuntu** [comment]
> Is this still a valid problem now #767 is merged? 🤔

I just installed it today so I think so?  WIth:
```
npm i react-query@tsnext
```

My package.json:
```jsx
"react-query": "^2.5.7-tsnext.1",
```

**Comment by boschni** [comment]
Hi @Buuntu, thanks for giving feedback on the new types! The type has indeed changed because the mutation returns `undefined` when an error occurs and the `throwOnError` option was not set to `true`. The documentation does seem to imply that the mutate function will throw by default because of the try catch in the example. This could either be a bug in the code or in the docs. What should be the default behaviour here @tannerlinsley ?

**Comment by tannerlinsley** [comment]
Mutate does not throw by default unless throwOnError is true. The docs should be updated to reflect this.

**Comment by Buuntu** [comment]
I suppose it's not doable to set a conditional type depending on what the config is.

**Comment by probablyup** [comment]
> Is this still a valid problem now #767 is merged? 

Yes it is, I get the error on 2.5.11 but not on 2.5.7-tsnext.1

**Comment by tannerlinsley** [comment]
Looks like with the docs and the new 2.5.7-tsnext.1 types, we'll be in good shape.
