### ISSUE TITLE
React native / expo - reference error: can`t find variable: document

### ISSUE THREAD

**Issue by gzaban** [tannerlinsley/react-query#816]
**Describe the bug**
React native / expo - reference error: can`t find variable: document

**To Reproduce**
run version v2.5.8 of react-query on react native / expo 

**Expected behavior**

**Screenshots**
![Screenshot_20200730-113934](https://user-images.githubusercontent.com/926338/88901670-be02d380-d259-11ea-9f8b-4038d9710c3c.jpg)

**Additional context**

**Comment by boschni** [comment]
Oops! This PR should fix it: https://github.com/tannerlinsley/react-query/pull/817
