### ISSUE TITLE
useInfiniteQuery with search

### ISSUE THREAD

**Issue by zamith** [tannerlinsley/react-query#819]
**Describe the bug**
I'm trying to use `useInfiniteQuery` together with a search to filter the results. When I add the query to the key via a key array, the cursor is never passed to the query function.

**To Reproduce**
```javascript
  const [query, setQuery] = useState(null);
  const { status, data, error, fetchMore, canFetchMore, isFetchingMore } =
    useInfiniteQuery(
      ["searchItems", {query}],
      searchItems,
      {
        getFetchMore: (lastGroup, _allGroups) => lastGroup.meta.nextCursor,
      }
    );
```

When `setQuery` is triggered, the query is made to the server correctly, but I never have access to the cursor in `searchItems`, which I do if I change the key to be a string.

**Expected behavior**
The query function to get the cursor regardless of the key.

**Comment by tannerlinsley** [comment]
The `getFetchMore` variable is only sent to your function when `fetchMore` is called. The first call with your function will not have the cursor information, since it doesn't exist yet.

```js
  const [query, setQuery] = useState(null);

function searchItems (_, { query }, cursor) {
  // Get your data. The `cursor` will be undefined on the first call.
}

  const { status, data, error, fetchMore, canFetchMore, isFetchingMore } =
    useInfiniteQuery(
      ["searchItems", {query}],
     searchItems,
      {
        getFetchMore: lastGroup => lastGroup.meta.nextCursor,
      }
    );
```

**Comment by tannerlinsley** [comment]
If you have further implementation questions, please use discussions or the discord chat :)
