### ISSUE TITLE
Query not refetching when enabled becomes 'true' and different instance is disabled

### ISSUE THREAD

**Issue by benediktviebahn** [tannerlinsley/react-query#823]
**Describe the bug**
I have 2 Components using the same query. At one point one instance changes the enabled flag to true while the other stays false. The query is not executed.

**To Reproduce**
I created a CodeSandbox: https://codesandbox.io/s/zen-almeida-g2o5z
Click the button to enable one of the queries => nothing happens. If you remove the <DisabledQuery /> component it works as expected.

**Expected behavior**
A query fetches when **any** instance is enabled.

**Comment by mustafawm** [comment]
I think it's because whenever `setEnabled`is called the `<App />` is re-rendered and when it does, `<DisabledQuery />` gets called (rendered) which overrides/writes the `enabled` flag in RQ .

If you extract the logic to a separate component [like this](https://codesandbox.io/s/muddy-wave-ojiwj?file=/src/index.js), I think it will achieve what you're after (_hopefully_)

**Comment by benediktviebahn** [comment]
You're right, that seems to work. I still think this is confusing behaviour and should probably get fixed. This is not intended is it?

**Comment by tannerlinsley** [comment]
Yeah, seems like a bug. Not a terrible one though. IMO, this use case is a tad bit contrived. However, that doesn't mean that technically it shouldn't work this way. Looks like somewhere, an effect is reading from `query.config.enabled` when it should be doing `query.instances.some(d => d.config.enabled)`

**Comment by benediktviebahn** [comment]
Can you explain what is wrong with this use case? I'm using the query on one of my screens where it's always enabled and also inside of a modal where it's only enabled if it's visible. Is there a better way to handle this? 

I think I found what's causing it I'll have a closer look this evening.

**Comment by tannerlinsley** [comment]
The use case you are describing is a good one. I was mostly referring to your implementation in the codesandbox. Be sure to let us know if you would like to tackle this PR, otherwise, we'll definitely get to it as soon as we can.

**Comment by benediktviebahn** [comment]
Sure I'll get to it later today.
