### ISSUE TITLE
Why "isCached" always true ？

### ISSUE THREAD

**Issue by roytan883** [tannerlinsley/react-query#83]
```
const { data, isCached} = useQuery('todos', fetchTodoList)
console.log(`isCached: `, isCached)
```
every time the component render, when data is not empty, it always `isCached: true`, even when network request. so, how to confirm the data is from net?

**Comment by nikoskleidis** [comment]
How about using a combination of isCached and isFetching
> isFetching: Boolean
> Will be true if the query is currently fetching, including background fetching.

When both isFetching and isCached are true then your data is from the cache.  
When isFetching is false, your data is the latest that came from net

**Comment by tannerlinsley** [comment]
Indeed. isCached will be true if there is synchronous data available in the query cache.
