### ISSUE TITLE
useMutation overloading (typescript)

### ISSUE THREAD

**Issue by jackmellis** [tannerlinsley/react-query#844]
I'm finding when I want a mutation that can take multiple argument types, typescript just doesn't understand it.

For example:
```ts
const fn = (args: { name: string } | { id: number }) => { ... };

const [ mutate ] = useMutation(fn);

mutate({ name: 'fred' }); // missing property id
```

It looks like the type of `mutate` is something like `{ name: string } & { id: number }` for some reason.

My original usecase for this was I wanted to accept one or more items. `args: Item | Item[]` and react query kept asking why I didn't have `.length` .`concat` etc. on my `Item`.

**Comment by jackmellis** [comment]
Also this is the first time I've looked at the codebase since v2 was released so I was pleasantly surprised to see the src written in typescript now! :+1:

**Comment by jackmellis** [comment]
Just to add to this. I've got an example that 100% errors in my repo:
```ts
type Named = { name: string };
type Id = { id: number };
type Arg = Named | Id;
type A = (arg: Arg) => Promise<null>;
const a: A = (arg) => Promise.resolve(null);
const b = useMutation(a);
const mutate = b[0];
mutate({ name: 'foo' });
mutate({ id: 1 });
```

But when I check out the latest master in the react-query repo and paste this in, typescript is quite happy with it. So now I'm very confused...

**Comment by jsmith** [comment]
Looks like this might be related to #830. I'm also getting some weird `useMutation` types but switching to `react-query@tsnext` fixed this issue for me (this is probably why it works in the latest version of `master`).

**Comment by jackmellis** [comment]
Yep `tsnext` looks to have resolved this. Is this release tag safe to use?

**Comment by jsmith** [comment]
According to the [docs](https://react-query.tanstack.com/docs/typescript#migration), the `@tsnext` version is currently being used to gather feedback. I'm using it and am having no issues but I guess it depends on your circumstances.

**Comment by jackmellis** [comment]
Thanks for your help, I think I'll use tsnext for now as it resolves this issue. I'm just unconvinced about going to prod with a feedback release! :smile:
