### ISSUE TITLE
`globalStateListeners` imported from "react-query" in codesandbox playground

### ISSUE THREAD

**Issue by IzaGz** [tannerlinsley/react-query#85]
in the example [Playground CodeSandbox](https://codesandbox.io/s/github/tannerlinsley/react-query/tree/master/examples/sandbox)
there is no explanation for `globalStateListeners` what is it, why no documentation for it?
Also seems it would be very cool if some there we can find some documentation for `what is going on ` on the playground
Thank you!

**Comment by tannerlinsley** [comment]
The playground is meant to visualize some of the internals of react-query, but `globalStateListeners` is not intended for public use. Yes it is exported, but only for internal utility and diagnosis scenarios.
