### ISSUE TITLE
index.d.ts types are not in sync with the code

### ISSUE THREAD

**Issue by dpyzo0o** [tannerlinsley/react-query#868]
**Describe the bug**

It seems like `index.d.ts` file which is published on npm is maintained seperately and it caused inconsistence with the acutual code itself. Since the library is now completely written in TypeScript, why not publish types generated by `yarn gen:types`?

**To Reproduce**
`yarn gen:types` and the output is different from what is in types folder right now.

**Expected behavior**
Publish correct types

**Comment by CreativeTechGuy** [comment]
To answer your "why not" question:

https://react-query.tanstack.com/docs/typescript

**Comment by dpyzo0o** [comment]
> To answer your "why not" question:
> 
> https://react-query.tanstack.com/docs/typescript

That makes sense.

**Comment by igor-pavlichenko** [comment]
But tsnext is now outdated and out of sync of latest release right?
