### ISSUE TITLE
TypeScript: Mutation `variables` argument type is never when using union type

### ISSUE THREAD

**Issue by mrlubos** [tannerlinsley/react-query#876]
**Describe the bug**
I have a function performing a server operation.

```ts
const serverFn = async (variables: Variables): Promise<Response> => {
  const { data } = await axios.post('/endpoint', variables);
  return data;
};
```

And `Variables` type defined like this.

```ts
type Foo = {
  foo: string;
  id: 'foo';
};

type Bar = {
  bar: string;
  id: 'bar';
};

type Variables = Foo | Bar;
```

Essentially, the server expects different parameters based on the `id` attribute value. Calling `serverFn()` directly works fine with both variants. The problem is when using the `react-query` mutation.

```ts
const [mutate] = useMutation(serverFn);

const onClick = (): void => {
  mutate({
    foo: 'value',
    id: 'foo',
  });
};
```

TypeScript will complain that `Type 'string' is not assignable to type 'never'`. When I display the `mutate` annotation, I see the following.

```ts
const mutate: (variables: never, options: (MutateOptions<Response, Foo, Error, unknown> & MutateOptions<Response, Bar, Error, unknown>) | undefined) => Promise<...>
```

I thought I need to do some type annotation on my side to fix this issue. However, changing `Variables` type to a single object (e.g. Variables = Foo) will fix the TypeScript error. This leads me to thinking it's an issue with `react-query` type definitions.

I am using `react-query` version `2.5.14`.

**Comment by tannerlinsley** [comment]
The new types are released, huzzah!
