### ISSUE TITLE
tsnext: useMutation's TError defaults to unknown

### ISSUE THREAD

**Issue by danielbrauer** [tannerlinsley/react-query#878]
**Describe the bug**
If no types are specified explicitly, and none can be inferred from the arguments (as is the case when there are no error handlers), TError's type defaults to unknown. 

**To Reproduce**
https://codesandbox.io/s/react-query-useinfinitequery-forked-pqdb5?file=/src/App.tsx

**Expected behavior**
I believe the default type for TError should be Error

**Comment by boschni** [comment]
Hi @danielbrauer! A discussion on the error type can be found here: https://github.com/tannerlinsley/react-query/discussions/814

**Comment by danielbrauer** [comment]
Ah, thanks! I'll continue there.
