### ISSUE TITLE
Request cancellation does not work when queryFn has the async keyword

### ISSUE THREAD

**Issue by chriszhangusc** [tannerlinsley/react-query#886]
**Describe the bug**
Not exactly sure this is a bug, but when the `queryFn` is defined as `async` function(with the async keyword), query cancellation doesn't work.

**To Reproduce**
Here's a codesandbox: https://codesandbox.io/s/confident-saha-zi2o3?file=/src/App.js, so if you set the browser network to slow 3G, click on the "send request" button and then quickly click on the "cancel request" button, you can see the request is being canceled. But when you add async to the queryFn, and redo the above steps, the request doesn't cancel.

**Comment by DennisOluoch** [comment]
I'm experiencing a similar issue. didn't find a solution so I had to declare AbortController outside the queryFn and simply pass it the controller signal. I'm directly calling the controller.abort() onClick event and not cancelQueries function.

**Comment by chriszhangusc** [comment]
> I'm experiencing a similar issue. didn't find a solution so I had to declare AbortController outside the queryFn and simply pass it the controller signal. I'm directly calling the controller.abort() onClick event and not cancelQueries function.

I think the reason was the async wraps on top of what we returned in a promise, and the cancel function we attached to our promise is not called. With that said, could you try to remove the `async` keyword for your queryFn?

**Comment by boschni** [comment]
@chriszhangusc is correct on why it does not work when making the query function async. I think we also cannot get this pattern to work because `react-query` has no way of knowing up front if the promise returned by the query function will resolve into a value or cancelable promise.

**Comment by tannerlinsley** [comment]
This is correct. You must return a promise with the `cancel` attached to it.
