### ISSUE TITLE
Refetch queries when result of a mutation has status "204 No Content"

### ISSUE THREAD

**Issue by matteofrana** [tannerlinsley/react-query#89]
Hi Tanner,
the result of a `DELETE` mutation on a REST API has often a status of `204`.
I see that `refetchQueries` is not triggered in this case, unless I set `refetchQueriesOnFailure` to true, but `204` is an OK status for deletes.

Do you think it is something you could work around?

Thank you,
Matteo

**Comment by tannerlinsley** [comment]
I think the answer to this is simple. If you throw an error in your promise, `refetchQueries` will not be triggered. If you resolve the promise, `refetchQueries` will be triggered. Just make sure your successful DELETE calls are not throwing.
