### ISSUE TITLE
Query Data not fetched initially when refetchOnMount is false in v2.7.0

### ISSUE THREAD

**Issue by MarcusNotheis** [tannerlinsley/react-query#896]
**Describe the bug**
It seems that there is a change in `react-query`'s behavior between `2.6.0` and `2.7.0`. It looks like a query is stuck in `loading` state when it is called for the first time and `refetchOnMount` is `false`.

**To Reproduce**
1. Open this codesandbox: https://codesandbox.io/s/sharp-shadow-81tj5?file=/src/App.js
2. You can see that the username is not showing up and the logged query is stuck in state `loading`. The service call is not fired.
3. If you now refocus the window it fetches the data as expected.
4. If you downgrade `react-query` to `2.6.0` it is working as expected

**Expected behavior**
the query should fetch data when on first execution.

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.6
 - Browser: Chrome 84.0.4147.125

**Comment by boschni** [comment]
Thanks for reporting! Seems that because of the strict mode, the hook is rendered twice without storing any refs in the first render. Because of this two query observers are being created. Will look into how to fix this.
