### ISSUE TITLE
If there is more than 1 instance of the same query on the page none of them is being fetched

### ISSUE THREAD

**Issue by smashercosmo** [tannerlinsley/react-query#898]
**Describe the bug**
With refetchOnMount set to false if there is more than 1 instance of the same query on the page none of them is being fetched

**To Reproduce**
1. Go to https://codesandbox.io/s/react-router-forked-ftzk5?file=/index.js
2. Click on 'users' link
3. Observe that fetchUsers function is not being called

**Expected behavior**
At least one query instance should fetch data

**Additional context**
You can see the problem only with react-query@2.7.0. Everything is fine with react-query@2.6.0

**Comment by boschni** [comment]
Should be fixed in version `2.7.1`
