### ISSUE TITLE
Simple example is broken on codesandbox

### ISSUE THREAD

**Issue by raerpo** [tannerlinsley/react-query#900]
**Describe the bug**
I was just starting learning the library and I noticed that the simple example on Codesandbox is throwing some error. I don't have enough experience with the library to know what could be wrong (not yet at least)

**To Reproduce**
Go to the simple example page:
https://react-query.tanstack.com/docs/examples/simple

**Expected behavior**
Show a working example like on basic, or custom hooks

<img width="1111" alt="Screen Shot 2020-08-20 at 16 15 07" src="https://user-images.githubusercontent.com/1649463/90821298-ab336a00-e300-11ea-9856-659d2c8301bb.png">

Thanks!

**Comment by lgenzelis** [comment]
@raerpo the issue is caused by `ReactQuertDevtools` (Idk why, though). Just remove line 5 for now, so that you can play around with the library till this gets fixed.

**Comment by tannerlinsley** [comment]
Fixed.
