### ISSUE TITLE
Wrong type for prefetchQuery in v2.8.0 (possibly) 

### ISSUE THREAD

**Issue by lgenzelis** [tannerlinsley/react-query#901]
**Describe the bug**
Up to v2.7.1, the return type of `prefetchQuery` was `Promise<TResult>`. In v2.8.0, however, the return type was changed for  `Promise<TResult | undefined>`. I'm guessing this is wrong.. Or is there a situation where `prefetchQuery` can return `Promise<undefined>`?

**Comment by boschni** [comment]
Hi @lgenzelis ! By default the `prefetchQuery` method will return `Promise<undefined>` when the query fails. This is something which can definitely happen during runtime.

**Comment by tannerlinsley** [comment]
It would be a breaking change, so let's discuss it more in v3. I'll add it to the umbrella issue.
