### ISSUE TITLE
Skip Query

### ISSUE THREAD

**Issue by matteofrana** [tannerlinsley/react-query#91]
I'd like to have a `skip` parameter expecting a function that, when returns true, will cause the query function to be skipped, useful when you don't have a required parameter for the fetch (for example productId)

**Comment by nikoskleidis** [comment]
@matteofrana how about passing a falsy key as described here:
https://github.com/tannerlinsley/react-query#pass-a-falsey-query-key

**Comment by czterystaczwarty** [comment]
@nikoskleidis you're right.
I use same hook for update (with id) and create (without id):
```javascript
const useMessage = ({ id = null } = {}) => {
  const queryResult = useQuery(
    id && [queryKey, { id }],
    fetchMessageById
  );
  const [create] = useMutation(createMessage);
  const [mutate] = useMutation(updateMessage);

  const mutateAndUpdateMessage = (message) => mutate(
    { id, ...message },
    { updateQuery: [queryKey, { id }] }
  );

  return {
    ...queryResult,
    create,
    mutate: mutateAndUpdateMessage
  };
};
```

**Comment by tannerlinsley** [comment]
Yep. falsey value :)

**Comment by sultan99** [comment]
**react-query v2**
`const {data} = useQuery(queryKey, queryFn?, {enabled: false})`

**Comment by Sigfried** [comment]
> @matteofrana how about passing a falsy key as described here: https://github.com/tannerlinsley/react-query#pass-a-falsey-query-key

No longer a valid anchor on that page

**Comment by kevinbror** [comment]
Using v4 right now and this seems like a feature gap still. Right now if I set enabled to false, isLoading is always true. This makes sense in a scenario where eventually for this page enabled will become true, but if I have a scenario where it won't eventually be true then I don't want to be in a permanent loading state. Is there a way in v4 to just skip so that isLoading is false and data is falsey?

**Comment by TkDodo** [comment]
> Using v4 right now and this seems like a feature gap still. Right now if I set enabled to false, isLoading is always true. This makes sense in a scenario where eventually for this page enabled will become true, but if I have a scenario where it won't eventually be true then I don't want to be in a permanent loading state. Is there a way in v4 to just skip so that isLoading is false and data is falsey?

use `isInitialLoading`

**Comment by kevinbror** [comment]
@TkDodo Ahh I missed that. Thank you.
