### ISSUE TITLE
Property "data" type from useQuery should not include undefined if "initialData" is informed

### ISSUE THREAD

**Issue by italodeandra** [tannerlinsley/react-query#918]
**Describe the bug**
When using the hook "useQuery" and using the property "data" from the object returned from it, the type of it should not include `undefined` if the config property "initialData" is informed.

**To Reproduce**
```ts
  const { isLoading, data } = useQuery<Company[]>(
    "companies",
    () =>
      axios
        .get("/companies", { params: { pagination: false } })
        .then((res) => res.data),
    { initialData: [] }
  );
```

**Expected behavior**
It should include only type informed on the generic type and typeof initialData.

**Screenshots**
![image](https://user-images.githubusercontent.com/19225266/91042092-821d1d00-e611-11ea-93fb-e47058f8f9db.png)

**Comment by italodeandra** [comment]
I did further research. This is actually not a bug because the "initialValue" works as it is intended because when it is fetching it will become `undefined`. In this case I think a "defaultValue" would work best.

I also passed the property `keepPreviousData: true` to the config. This way it will never the `undefined`, right?

**Comment by agos** [comment]
@italodeandra it can still be `undefined` even with `keepPreviousData` in case you call remove or clear on the query cache. I agree with you that a "default value" would be a very valuable addition. In the meanwhile it's easy to add it wrapping the hook or just adding it to the query result, but it's not optimal as it complicates the return type

**Comment by italodeandra** [comment]
Yeah. I agree. For now I'm doing the good ol' nullish coalescing right after it.

```ts
  const { isLoading, data } = useQuery<Company[]>(
    "companies",
    () =>
      axios
        .get("/companies", { params: { pagination: false } })
        .then((res) => res.data)
  );
  const companies = data ?? [];
```

I'll close this issue, as it isn't really an issue and more of a discussion now.

**Comment by agos** [comment]
here is the function I used to add a default value to a query result and have it , in case anyone stumbles upon this issue in the future:

```typescript
export function queryResultWithDefaultData<T>(
  queryResult: QueryResult<T>,
  defaultData: T,
): QueryResult<T> & { data: T } {
  return { ...queryResult, data: defaultData };
}
```
