### ISSUE TITLE
Is it possible to persist cache query?

### ISSUE THREAD

**Issue by Jekiwijaya** [tannerlinsley/react-query#92]

**Comment by deevus** [comment]
I assume you mean you want to persist the query cache? Looking at the code, the cache is just an array called `queries`. It would be nice to be able to override this and use `localStorage` for example

**Comment by tannerlinsley** [comment]
You're more than welcome to do try that out, but as of today, it's not a first class citizen mostly because invalidation would need to be set up to essentially clear out old persisted queries and that's something that would be difficult to make great for a majority of use cases.

**Comment by deevus** [comment]
Would you accept a PR that decouples the cache implementation? The default implementation would function the same as it does now.

A `localStorage` implementation could be provided for example by a `react-query-cache-local-storage` package.

**Comment by tannerlinsley** [comment]
I would be open to discussing a proposal

**Comment by BrandonSmith** [comment]
@deevus Did you make progress on persisting and seeding the cache? I'm interested in using react-query in a React Native app and with the app lifecycle, seeding the cache between app restarts is an important consideration.

**Comment by tannerlinsley** [comment]
This is really naive, but you could try this:

```js
import { queryCache } from 'react-query'

// Persist to wherever using the super-secret `queries` object

const queriesWithData = Object.values(queryCache.queries).map(query => ({
  queryKey: query.queryKey,
  data: query.state.data
}))

localStorage.set('queries', JSON.stringify(queriesWithData))


// Hydrate from localStorage

const queriesWithData = JSON.parse(localStorage.get('queries'))

queriesWithData.forEach(query => {
  queryCache.setQueryData(query.queryHash, query.data)
})
```

This is highly experimental and undocumented, so you can be my guinea pig :)

**Comment by deevus** [comment]
I got busy but would still love this. 

@tannerlinsley that looks very interesting :)

**Comment by BrandonSmith** [comment]
@tannerlinsley And use the `queryCache.subscribe` to get notified when the cache changes?

**Comment by tannerlinsley** [comment]
Yeah!

**Comment by jgoux** [comment]
I'm also very interested by a offline-first approach! I'll try to be a guinea pig and experiment with this! 😄

**Comment by cliffordp** [comment]
https://github.com/LuudJanssen/localforage-cache worked a treat, especially setting its key like this:

```
import { stableStringify, useQuery } from 'react-query';

/**
 * Consistently get the queryKey to use with React Query, optionally casting to string for use as a local storage key.
 *
 * @param {String} endpoint
 * @param {Object} params
 * @param {Boolean} toSerializedString For use with setting local storage.
 *
 * @returns {[{String}, {Object}]}|{String}
 */
const getQueryKey = (
	endpoint,
	params,
	toSerializedString = false,
) => {
	let arr = [
		endpoint,
		params,
	];

	// https://github.com/tannerlinsley/react-query/blob/v1.2.1/src/config.js#L59
	if ( toSerializedString ) {
		arr = stableStringify( arr );
	}

	return arr;
};


/**
 * Fetch data from the API or, if available and not expired, from local storage cache.
 *
 * @param {String} endpoint
 * @param {Object} params
 */
const fetcher = async ( endpoint, params ) => {
	console.log( 'fetcher' );

	//
	// The `true` is the special bit!
	//
	const queryKeyString = getQueryKey( endpoint, params, true );

	// todo: way to force fresh API hit
	//apiCache.removeItem( queryKeyString );

	const cacheData = await apiCache.getItem( queryKeyString );

	if ( null !== cacheData ) {
		console.log( 'Got API data from local cache.' );
		return cacheData;
	}

	const url = getApiUrl( endpoint, params );
	console.log( url );

	try {
		const data = await fetch(...);
		console.log( 'API was hit: ' + endpoint );
		console.log( data );

		await apiCache.setItem( queryKeyString, data );
		console.log( 'Set API data to local cache.' );

		return data;
	} catch ( err ) {
		console.log( err );
		throw err;
	}
};

```
