### ISSUE TITLE
"refetchOnWindowFocus: false" does not work when supplied by config provider

### ISSUE THREAD

**Issue by estorski** [tannerlinsley/react-query#926]
`refetchOnWindowFocus: false` on the level of `<ReactQueryConfigProvider config={config}>` is not respected when used in conjunction with `useInfiniteQuery`

**To Reproduce**

* go to https://codesandbox.io/s/infinite-query-typescript-example-forked-bxbxr?file=/src/App.tsx
* try to focus the browser frame by clicking anywhere inside of it, then remove the focus by clicking somewhere in the code on the left, then click back into the browser frame
* observe in the console that every time you focus the browser frame, request(s) are being issued

**Expected behavior**
* nothing should be happening on focus change unless you click "fetch more" button

**Comment by boschni** [comment]
Hi Kostia! I think the reason why it doesn't work is because the hook is used outside of the `ReactQueryConfigProvider` component. Only components within the provider will use the provided configuration.

**Comment by estorski** [comment]
@boschni indeed, tested, works as expected 👍 . Thanks for pointing that out.
