### ISSUE TITLE
If "initialStale" is setted or return true, 'isFetching' will be true and 'data'  will be undefined when the key is changed

### ISSUE THREAD

**Issue by TIS-OMiddle** [tannerlinsley/react-query#927]
**Describe the bug**
The `initialStale` behavior is strange. When `initialStale` is false and query key is changed, `isFetching` will always be `true`, and `data` will always be `undefined`

**To Reproduce**
1. codesandbox: https://codesandbox.io/s/rq-initialstale-xg9u2?file=/src/index.js:444-456
2. Click 'add' button

**Expected behavior**
Not sure what it should be.
I think `initialStale` should not be called multiple times, and `data` should be an object.

**Screenshots**
![image](https://user-images.githubusercontent.com/24486385/91250392-7d7c7400-e78b-11ea-980f-a30d882163a4.png)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome
 - Version: 84.0.4147.125

**Additional context**

**Comment by tannerlinsley** [comment]
Hmm, this indeed looks like a bug. Could be happening around here: https://github.com/tannerlinsley/react-query/blob/caa6522a72b3338b610b5e8c207b3b0d332c0784/src/core/queryObserver.ts#L204

**Comment by tannerlinsley** [comment]
@boschni any ideas here? I'm still a bit disconnected from this code lol
