### ISSUE TITLE
Warning in console from ReactQueryDevtoolsPanel

### ISSUE THREAD

**Issue by jmbldwn** [tannerlinsley/react-query#941]
**Describe the bug**

Warning: Cannot update a component (`ForwardRef(ReactQueryDevtoolsPanel)`) while rendering a different component (`OrganizationDetail`). To locate the bad setState() call inside `OrganizationDetail`, follow the stack trace as described in https://fb.me/setstate-in-render

OrganizationDetail is my component.  Happens to be the one hitting this error.

**To Reproduce**
1. Latest react-query (v2.12.1) and react-query-devtools (v2.4.4)
2. Open React Query Devtools
3. Use app

**Expected behavior**
No error (wasn't getting this before updating to latest)

**Screenshots**
https://www.dropbox.com/s/uxhc71b8umvmq8r/Screen%20Shot%202020-08-29%20at%206.59.01%20PM.png?dl=0

**Desktop (please complete the following information):**
 - OS: MacOS Catalina
 - Browser: Chrome
 - Version: 84.0.4147.135 (Official Build) (64-bit)

**Additional context**
Console stack trace:

index.js:1 Warning: Cannot update a component (`ForwardRef(ReactQueryDevtoolsPanel)`) while rendering a different component (`OrganizationDetail`). To locate the bad setState() call inside `OrganizationDetail`, follow the stack trace as described in https://fb.me/setstate-in-render
    in OrganizationDetail (at Organization.js:29)
    in Route (at Organization.js:28)
    in Switch (at Organization.js:27)
    in div (created by Styled(MuiBox))
    in Styled(MuiBox) (at Organization.js:20)
    in Organization (at Home.js:89)
    in Route (at Home.js:88)
    in Switch (at Home.js:87)
    in div (created by Styled(MuiBox))
    in Styled(MuiBox) (at Home.js:85)
    in div (created by Styled(MuiBox))
    in Styled(MuiBox) (at Home.js:81)
    in div (created by Styled(MuiBox))
    in Styled(MuiBox) (at Home.js:79)
    in Home (at App.js:63)
    in Route (at App.js:62)
    in Switch (at App.js:58)
    in div (created by Styled(MuiBox))
    in Styled(MuiBox) (at App.js:57)
    in div (created by Styled(MuiBox))
    in Styled(MuiBox) (at App.js:55)
    in Router (created by BrowserRouter)
    in BrowserRouter (at App.js:54)
    in ThemeProvider (at App.js:51)
    in ReactQueryConfigProvider (at App.js:46)
    in App (at src/index.js:10)
console.<computed> @ index.js:1
overrideMethod @ react_devtools_backend.js:2273
printWarning @ react-dom.development.js:88
error @ react-dom.development.js:60
warnAboutRenderPhaseUpdatesInDEV @ react-dom.development.js:23241
scheduleUpdateOnFiber @ react-dom.development.js:21165
dispatchAction @ react-dom.development.js:15660
(anonymous) @ index.js:322
(anonymous) @ queryCache.ts:93
notifyGlobalListeners @ queryCache.ts:93
buildQuery @ queryCache.ts:236
updateQuery @ queryObserver.ts:208
QueryObserver @ queryObserver.ts:34
useBaseQuery @ useBaseQuery.ts:19
useQuery @ useQuery.ts:51
useMembersById @ organization.js:119
OrganizationDetail @ OrganizationDetail.js:23
renderWithHooks @ react-dom.development.js:14803
mountIndeterminateComponent @ react-dom.development.js:17482
beginWork @ react-dom.development.js:18596
beginWork$1 @ react-dom.development.js:23179
performUnitOfWork @ react-dom.development.js:22154
workLoopSync @ react-dom.development.js:22130
performSyncWorkOnRoot @ react-dom.development.js:21756
(anonymous) @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
discreteUpdates$1 @ react-dom.development.js:21893
discreteUpdates @ react-dom.development.js:806
dispatchDiscreteEvent @ react-dom.development.js:4168
Show 2 more frames

**Comment by boschni** [comment]
Thanks for reporting @jmbldwn! This should probably be fixed in the devtools package. The state update function needs to be wrapped in a `setTimeout` or `Promise.resolve()`.

**Comment by tannerlinsley** [comment]
We have an issue open in the devtools to track this.
