### ISSUE TITLE
queryCache is empty when using ReactQueryCacheProvider

### ISSUE THREAD

**Issue by todortotev** [tannerlinsley/react-query#946]
**Describe the bug**
When I'm trying to queryCache.invalidateQueries(keyGoesHere) and I'm using the new hydration API, the queryCache object is empty, so I cannot invalidate or override any of the data.

**Expected behavior**
queryCache should contain the queries that are prefetched on the "Hydrate" component or another way to invalidate or set new data for a specific query.

**Screenshots**
![Screenshot 2020-09-01 at 11 52 43](https://user-images.githubusercontent.com/51530311/91829082-a8fad500-ec49-11ea-98de-9f13387ff164.png)

![Screenshot 2020-09-01 at 11 52 11](https://user-images.githubusercontent.com/51530311/91829027-9385ab00-ec49-11ea-93d9-4841dce77e9f.png)

![Screenshot 2020-09-01 at 11 51 51](https://user-images.githubusercontent.com/51530311/91829001-8799e900-ec49-11ea-8cb8-a8f5261bca59.png)

**Desktop **
 -macOs

**Comment by todortotev** [comment]
For someone else having the same issue

instead of ```import { queryCache } from "react-query"``` you should use ```const querycache = useQueryCache()```

**Comment by jl-gogovapps** [comment]
I had this issue as well where the 'import' technique was not clearing the cache setup by `ReactQueryCacheProvider`.  Using the hook resolved the issue
