### ISSUE TITLE
Add useMutation.onSuccess/onError?

### ISSUE THREAD

**Issue by tibotiber** [tannerlinsley/react-query#98]
Hi,

I had missed the addition of `onSuccess/onError` event handlers as described in #15. This is something I was doing in a custom hook and I'm really happy to see it added natively 🎉.

What do you think about adding this to `useMutation` as well?

Cheers

**Comment by tannerlinsley** [comment]
Since useMutation is a one-off call, you can simply rely on the promise it returns either resolving or throwing in your try/catch block around it.

**Comment by tibotiber** [comment]
So currently I'd do:
```js
const [mutate, { isLoading, error, data }] = useMutation(postTodo, {
  refetchQueries: ["todos"]
});
// ...
onClick={async () => {
  try {
    const data = await mutate({ name });
    setSuccess(data)
  } catch (error) {
    setError(error)
  }
}}
```
and I'm seeing an opportunity to do this:
```js
const [mutate, { isLoading, error, data }] = useMutation(postTodo, {
  refetchQueries: ["todos"],
  onSuccess: setSuccess,
  onError: setError
});
// ...
onClick={() => mutate({ name })}
```

I have a personal preference for the second (more declarative), and I like that the API is consistent with `useQuery`'s. I can always build this with a custom hook but I feel it would make a nice addition to have this out of the box. Or do you think it encourages anti-patterns? What do you think?

**Comment by tibotiber** [comment]
@tannerlinsley friendly ping in case this got lost in notifications
