### ISSUE TITLE
When Set Config staleTime, Queries always refresh in DevTools

### ISSUE THREAD

**Issue by nandayonah** [tannerlinsley/react-query#995]
**Describe the bug**
I setup a basic react queries app, the code below:

```js
import React from "react";
import { useQuery } from "react-query";
import Planet from "./Planet";

const fetchPlanets = async () => {
  const response = await fetch("https://swapi.dev/api/planets/");

  return response.json();
};

const Planets = () => {
  const { data, status } = useQuery("planets", fetchPlanets, {
    staleTime: 2000,
  });

  return (
    <div>
      <h2>Planets</h2>

      {status === "error" && <p>Error when fetching data</p>}

      {status === "loading" && <p>Loading data ...</p>}

      {status === "success" &&
        data.results?.map((planet) => (
          <Planet key={planet.name} planet={planet} />
        ))}
    </div>
  );
};

export default Planets;
```

When I see in the DeveloperTools, the queries always fresh, not goes to stale after 2 seconds.

**Expected behavior**
The queries becomes stale after 2 seconds

**Screenshots**
![Screenshot from 2020-09-11 14-17-47](https://user-images.githubusercontent.com/44917664/92882308-fe00cd00-f439-11ea-9b0c-fa12b9289565.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Chrome
 - Version: 85.0.4183.102 (Official Build) (64-bit)

**Additional context**
I'm using React Query version ^2.15.4 and React Query Devtools ^2.4.7

**Comment by boschni** [comment]
This should be fixed in `2.17.0`
