### ISSUE TITLE
Abnormal behaviour while using paginated queries / simple queries.

### ISSUE THREAD

**Issue by Ritvyk** [tannerlinsley/react-query#997]
**Describe the bug**
I'll try to be specific and brief about the issue , so the issue I am facing is queries are not getting stale when using **usePaginatedQuery** hook , and also with **useQuery** hook.

Problem is explained below.

**To Reproduce**
Try to  pass complex key params to function directly it will  mark query  as **fresh** 
Pass the params in {...params} this  way it will make query as **stale** but won't use caching :( 

**Expected behavior**
queries should  be marked as stale when  they  are completed.

**Screenshots**
1. When I  pass **params**  directly.
```

const propertyUnitsData = usePaginatedQuery(
    [
      "newProperty-units",
      {
        propertyId: currentProperty.id,
        page: unitsFilters.unitpage,
        unitName: unitsFilters.unitName,
        unitType: unitsFilters.unitType,
      },
    ],
    async (key, params) => {
      **_//see  this line_**
      return await fetchPropertyUnits(key, params)
    },
    {
      ...queryConfigurations,
      enabled: currentProperty.id,
      onError: () => {
        notify("error", "Error while fetching data.");
      },
    }
  );
```

![aq](https://user-images.githubusercontent.com/48027766/92918903-76bd5480-f44d-11ea-8022-ba0bbf222172.png)

2. When I pass {...params} in de-structured way.

```
const propertyUnitsData = usePaginatedQuery(
    [
      "newProperty-units",
      {
        propertyId: currentProperty.id,
        page: unitsFilters.unitpage,
        unitName: unitsFilters.unitName,
        unitType: unitsFilters.unitType,
      },
    ],
    async (key, params) => {
      **_//see this line_**
      return await fetchPropertyUnits(key, {...params})
    },
    {
      ...queryConfigurations,
      enabled: currentProperty.id,
      onError: () => {
        notify("error", "Error while fetching data.");
      },
    }
  );
```
![asa](https://user-images.githubusercontent.com/48027766/92918944-7f158f80-f44d-11ea-8c6c-b3bce8bd6811.png)

**Additional context**
When I am using the above 2nd way it is marking  query as stale but isn't  using cache  when I am paginating I can see this in my network tab  in chrome developers tools.

Please Help  Me Out  !

**Comment by boschni** [comment]
Could you check if the issue is still there in `2.17.0`?

**Comment by tannerlinsley** [comment]
Issue is 7 days old, and thus stale. Feel free to reopen with a codesandbox or test case that illustrates your issue :)
